== Selection from the Journal of George Whitehead

In remembering the Lord our gracious God,
and His merciful dealings with me from my youth--how He found me among His lost
and strayed sheep on the barren mountains of fruitless religious professions;
how He drew me to an inward experience of His power and sanctifying work in my heart,
and to the knowledge of His teaching and spiritual ministry;
how He enabled me by degrees to experientially minister to others,
as also to suffer patiently for His sake, with resignation of life and liberty,
being supported by His power through many great trials and deep sufferings,
and through many eminent deliverances and preservations,
even from my young years--I am pressed with a concern
to leave some remarks or footsteps behind for others,
by way of a historical account of my progress in the Lord`'s work and service.
To this purpose, I have collected several of my papers, notes,
and memorials from past experiences and exercises,
desiring earnestly that the publication of these things will conduce to the glory of God,
to the honor of His excellent name,
and to the advantage of the serious reader in the
consideration of His divine goodness and grace,
which endure forever to all who truly love and fear Him.

From early inclinations and the desires which the Lord was graciously pleased
to stir up in my heart towards His blessed truth as it is in Christ Jesus,
I was drawn to seek after the knowledge of God, to learn how to become truly penitent,
and to witness a real amendment of life from the vain conduct which I, in my childhood,
had been prone to.
Being partly educated under a Presbyterian ministry, I was given to see, at a young age,
several ways in which this people fell far short of all
that they professed and proclaimed in their preaching,
praying, and worship; insomuch that before I had heard of the people called Quakers,
I could not actively join with the Presbyterians.
And being at a loss, at this time, as to what my spirit secretly desired and needed,
I lived as one bewildered,
and so wandered about seeking truth among various other groups and persuasions
who had some higher and more refined notions concerning spiritual gifts, etc.
I was then about fourteen years of age.

After a short time,
I heard of some people called Quakers who trembled at the Word of God;
and observing how they were reviled and reproached by loose and wicked people,
it occasioned my further inquiry about them.
Hereupon the Lord gave me to believe that these were indeed His people,
and I contended for them and their principles so
far as they had been represented favorably to me,
even before I had been to a meeting of theirs, or had heard any of them minister.

And though the Lord had raised good desires in me toward
Himself that I might know true repentance unto life,
yet these desires were often quenched, and my mind led away through an airy,
light disposition, having great fondness for music, amusement, and other vanities,
like many other children and youth.
Nevertheless,
the Lord was graciously pleased to secretly follow
me with judgment and reproof in my very young years,
and often renewed desires in me after the right way.
But while I remained a hearer of the priests and other professors of Christianity,
I was without a true stay for my mind,
not then knowing or following that light of Christ in me,
which convinced and reproved me for the sins of my youth.
In those early days the light shined in darkness, as in a dark place,
and was often clouded before it began to shine out of darkness.
For even as the Spirit of the Lord once moved upon the waters
when darkness was upon the face of the great deep,
before His works of old were wrought, so too,
in order to bring forth His works in the new creation,
to make us new creatures in Christ Jesus, His Spirit moves upon people`'s hearts,
even when they are unstable as waters,
and His light shines in them before they know the living God,
in order to give them the knowledge of the glory and power of God,
and of His dear Son Jesus Christ.

In the course of some religious discourse with a few young men who were soberly inclined,
I heard of a few of the people called Quakers in Sedbergh, in Yorkshire,
and in Kendal Barony in Westmoreland; and after much seeking and wandering,
I was desirous to attend one of their meetings which
was to be held at the home of one Captain Ward`'s,
at a place called Sunny Bank, near Grayrig chapel.
At my first entering the meeting and sitting down seriously among them,
after a little space of silence,
a Friend named Thomas Arey spoke a little while concerning Israel`'s
deliverance out of Egypt from under Pharaoh and his task masters,
alluding to the spiritual deliverances, travels,
and progress of the Lord`'s people in His way and work.
All of this I thought I easily understood in an allegorical or spiritual sense;
but there appeared to me to be a great work of the
power of the Lord taking place in the meeting,
breaking the hearts of many into great sorrow, weeping and contrition of spirit,
which I believed was a godly sorrow for sin unto unfeigned repentance.

I was more confirmed in this opinion by seeing a
young maiden run out of the meeting weeping.
I followed after her in a serious frame of mind in order to observe her sorrowful condition,
and I beheld her,
having sat down on the ground with her face to the earth as if she regarded nobody present,
bitterly mourning and crying out, "`Lord, make me clean!
O Lord, make me clean!`"
This far more tenderly and deeply affected my heart
than all that I had heard spoken that day;
indeed,
it reached me more than all the preaching that ever I had heard from any man or men.
It was a certain testimony to me (the Spirit of the Lord bearing witness
with my spirit) that this was a real work of God`'s power upon her heart,
which I also saw operating upon the hearts of others, causing both trembling,
sorrow and contrition, in order to bring them to true repentance and amendment of life,
and to an experience of the work of regeneration and sanctification from sin and uncleanness.
And indeed, it proved to be so to many; glory be to our God forever.

Upon serious observation, these things made a deep impression upon my mind,
and I was the more confirmed in the belief that I had come to before,
that the Lord was at work among this small despised people,
and that He was about to gather and raise up a people unto
Himself to worship Him in the Spirit and in the truth,
and not in the dead and empty forms that are set up in the will of man.
Such as these (we are told by Christ) the Father seeks to worship Him acceptably.

Under these considerations, I was soon induced to leave the parish priests,
who were ministers made by the will of man,
having no divine authority from God or commission from Christ to teach others.
For seeing that, by their pride and covetousness,
they were not good examples to the flock,
but indeed lived contrary to both Christ`'s command and His ministers`' example,
I knew I ought to turn away from them, which in a very short time I did,
after the Lord (by His light) opened my eyes to see the blindness
of those guides whom I had followed by education and tradition.

And though I met with opposition and hard words from some
near relations and others who were hearers of those priests,
yet I confessed and vindicated the truth according
to the little measure of understanding I then had.
And being but weak and young in years,
and beset with various temptations and discouragements,
yet the Lord my God helped and persuaded me to take up a resolution,
not only to wholly leave off the said priests,
but also to constantly attend the meetings of His despised people called Quakers,
and to sit down among them,
though they were then but few in number in comparison to what they have become since.
Their meetings, which I frequented, were for some time in Sedbergh parish in Yorkshire,
at the home of Thomas Blaykling, whose family was honest and of good reputation.
Also at Richard Robinson`'s at Brigflats, who was an innocent, faithful man,
and sometimes in Grayrig and that area, near Kendal in Westmoreland,
the county where I was born.

In a short time I was fully convinced of the truth of the Quakers`' principles.
My mind was turned to the light,
and I was persuaded and resolved to persevere among Friends
before I ever heard our dear Friend George Fox.
The first time I heard him minister was at an evening meeting at Sunny Bank,
at the home of Captain Henry Ward.
I was then very low, serious, and intent in my mind, willing to see and taste for myself,
for my own inward satisfaction.
And indeed, I saw and felt that his testimony was weighty and deep,
that it proceeded from life and experience, bespeaking divine revelation,
and tending to bring to an inward feeling and sense of the life and power of Christ,
and its sanctifying operation in the heart.
His speech was not with affected eloquence or oratory, or human wisdom,
but in the simplicity of the gospel,
in order to turn the mind to the light and life of Christ; and truly,
the Lord abundantly blessed his ministry to many.

Being now joined to the people who in derision were called Quakers,
and by the grace of God resolved to continue and persevere in their communion,
and to wait upon God in His light (with which He
had enlightened my understanding in a good measure),
I found great satisfaction therein.
For having "`received the love of the truth,`"^
footnote:[2 Thessalonians 2:10]
we were made sensible that our society and converse
with one another was helpful and encouraging,
and tended to our edification and comfort.
I greatly loved and delighted in the free conversation and fellowship of sober,
faithful Friends.
When I had been a school boy at the free-school at Blencoe in Cumberland,
I loved retirement with some of the sober and serious students,
though they were but low and poor in the world, rather than the company of loose,
extravagant boys who were given to much play and gaming.
In the company of the former, we were the most profitable one to another in our learning,
communicating the effects of our studies to each other.
And much more is this true in a spiritual and higher sense,
when we had in some degree come to know the blessed Truth,
in the light of our Lord Jesus Christ.
Our Christian society, and the communications of our inward experiences,
did all redound to our mutual help and edification
in the love of the truth as it is in Christ;
for He is the light and life, and our great Apostle and minister,
who teaches His true followers to profit in that love and life which flows from Him.
Indeed He is the Fountain and Foundation of all our mercies, helps,
and living encouragements in His way and work--to
whom alone be the praise and glory forevermore.

After I was resolved and settled in my mind and conscience
to join in communion with the aforementioned people,
and to frequent their assemblies,
I came to experience (by divine assistance) some progress
in the work of the Lord Jesus Christ in me.
For the Lord, by the light and grace of His Holy Spirit,
fully persuaded me that without being converted as well as convinced,
and without being regenerated, sanctified, and truly born again,
I could not enter or be an heir of His kingdom.
I was given to see that a godly sorrow unto true repentance,
and a real amendment of life, must be wrought by His grace and good Spirit in me; and,
that "`without holiness no one will see the Lord.`"^
footnote:[Hebrews 12:14]

Upon these, and such serious Christian considerations,
I was persuaded by the grace of God to give up in obedience to follow Jesus Christ;
to believe in, and obey His light given to me,
and to diligently wait therein to receive power from Him to become a true child of God;
for to as many as truly receive Christ the Son of God,
He gives power to become the sons of God.^
footnote:[John 1:12]

I saw it was my place to retire inwardly to the light, to the grace of God,
to the immortal, incorruptible Seed or ingrafted Word,
which is the divine gift and living principle,^
footnote:[At the time of this writing,
the word _principle_ was commonly used to refer to "`the source or origin of any thing;
that from which a thing proceeds; the primordial substance;
the operating cause`" - [.book-title]#Webster`'s Dictionary 1828 Edition.#]
frequently testified of among the Society of Friends, according to Holy Scripture.
And as my mind was turned to this light,
I came plainly to see my true inward and outward state,
how much I was fallen into a state of degeneracy, and how much I had been depraved,
corrupted, and alienated from the life of Christ and of God.
The very vanity of mind and the thoughts wherein I had been
wandering and estranged from the light and life of Christ,
became my unspeakable burden and exercise.
Indeed, I longed to be delivered, that I might be truly renewed in the spirit of my mind,
and therein joined to the Lord.

Thus I was persuaded to wait in the light "`in the way of His judgments,`"^
footnote:[Isaiah 26:8]
and to bear and submit to His fatherly chastisements and reproofs of instruction,
believing, that "`Zion must be redeemed through judgment,
and her converts with righteousness.`"^
footnote:[Isaiah 1:27 KJV]
Vain thoughts, imaginations, and wanderings of the mind,
became a source of suffering and burden to me,
and I earnestly sought the Lord for power to suppress and give me victory over them all,
and to stay my mind upon the Lord Himself, that I might enjoy inward peace with Him.

I had a spiritual warfare to go through, and a body of sin to put off and be destroyed.
And though I was still young,
and had not grown to maturity--as others of riper years who are guilty of great
evils by their longer continuance and custom in sinning--I nevertheless found
a real necessity for the work of sanctification,
an inward cleansing from sin, and a real being born again.
This is that birth and life which comes from above,
and which alone is entitled to the kingdom of Christ
and of God which no unclean person can inherit.

In waiting upon God, and sincerely seeking after Him with my mind inwardly retired,
and my soul desiring and breathing after His name and power,
He was graciously pleased often to renew His merciful visitations to my poor soul,
and in the midst of judgment and chastisements, to remember mercy,
that He might be feared.^
footnote:[Psalm 130:4]
The sense of this did often break and tenderize my heart,
and cause me to be even more mindful of the work of the Lord our God,
and to more often consider the operation of His divine hand,
whose dealing with me was in judgment and mercy.
His eternal Word, by its judgment, brought me to fear and trembling in His presence;
and His mercy caused brokenness and true tenderness of heart, which I often experienced.
In the living remembrance of these things,
I still find great cause to ascribe praise and glory to His excellent name, power,
and divine goodness, manifest through His dear Son--even the Son of His love,
our blessed Lord and Savior Jesus Christ.

Many of the Presbyterian priests in Westmoreland, and other northern parts of England,
appeared very envious against us in the years 1652, 1653, and 1654.
And in their lectures and sermons they reviled and
reproached the Quakers and their ministers,
calling them deceivers and antichrists who had come in the last times.
They gathered together whatever evil and false reports they
could to incense their credulous hearers against us,
thereby setting both neighbors and families at variance and sowing discord.

Some of their hearers, even of my own relations,
when returning from their public worship, and from hearing a sermon against Quakers,
have come full and bristling with false and often nonsensical charges and slanders.
Sometimes I offered them a Christian answer, which, when rejected,
I often found it my place to be silent, and to let them clamor and scoff on.
The leaders and priests caused the people to err, and with their sour leaven,
they soured the spirits of many into enmity,
whereby many were hurt and prejudiced against truth.

My parents were hurt by them, and the more incited against me for a time,
until the Lord turned their hearts and opened their understandings
to see far better than they could by following blind guides,
whose work was to make divisions.
My parents and relations had great natural affection and care for me, in their way.
And even when they appeared most opposed and offended,
because I had left their church and ministers and had joined with
the people called Quakers (which was a great trial to me),
still their trouble and grief came more from the influence of their priest,
and their fear of my misfortune or losing preferment in the world,
than from any prejudice against me or my religious profession.
They retained a real natural love and affection to me while I was
absent from them in the ministry and service of the Truth,
for about three years (in which time I suffered several hard imprisonments).
And afterwards, upon returning to visit them, they were much reconciled and loving to me,
and their understandings and hearts were opened towards me and my friends,
who came to visit me when at their house.

My mother, some years before her decease, was really convinced of the Truth,
and became a Friend in her heart.
And my father, seeing the corruption, pride and avarice of the priests,
retained a love toward Friends till the end of his days.
Likewise my sister Anne, before the death of her mother,
became a friend to Truth and Friends, and continued an honest, loving,
and serviceable woman until her death.

Now when the priests or parish ministers could not prevail to stop
the progress and spread of the blessed Truth and power of Christ,
nor prevent the growth of our friends therein,
by all their lectures and reviling sermons and preaching against us,
they then endeavored to incense the magistrates, justices,
and the government against the people called Quakers.
Because of this, many justices and officers were instigated to persecution,
and imprisoned many of our Friends in Kendal and Appleby jails in Westmoreland,
for bearing a testimony against them.
I was moved in the dread and fear of the Lord to bear public testimony
against the wickedness of the priests in several of their places of worship
in Westmoreland before I travelled into the south parts of England,
yet the Lord was pleased at that time to preserve me from any harm or imprisonment,
having a further work for me in other parts of the nation.

The meetings to which I belonged in Westmoreland and Yorkshire,
between the years 1652 and 1654, were kept regularly,
and were often in silence or with but a few words declared,
while we were inwardly exercised in waiting upon the Lord.
After I had been some time among them, the Lord was pleased sometimes,
by His power and Word of life, to tenderize and open my heart and understanding,
so that He gave me (and some others) now and then a few words livingly to utter,
to their and my own comfort; for He opened our hearts in great love one to another,
which then increased and grew among us, blessed be the Lord our God forever.
It was out of these, and other frequently silent meetings,
that the Lord was pleased to raise up and bring forth living witnesses,
faithful ministers, and true prophets, in the early days in Westmoreland,
and in other northern parts of England, in the years 1654 and 1655.

Truly it can be said that, in these latter days and times,
the Lord our God has been pleased to visit this island with His gospel day and power,
according to His promise unto the Gentiles,
and to "`the islands that wait for His law;`" that His elect One, His Christ,
in whom His soul delights, should bring forth judgment to the Gentiles
(Isaiah 42). For we who waited in true silence upon Him,
and eyed His inward appearance in Spirit and the work of His power in us,
came truly to see and feel our strength renewed in living faith, in true love,
and in holy zeal for His name and power;
insomuch that the Lord gradually brought us to experience
what He said of old by His holy prophet;
"`Keep silence before Me, O islands, and let the people renew their strength!
Let them come near, then let them speak; let us come near together for judgment.`"^
footnote:[Isaiah 41:1]

This keeping silence before the Lord,
and drawing near to Him in a true silent frame of spirit,
to hear first what the Lord speaks to us,
before we speak to others (whether in judgment or mercy),
was the way shown to us for renewing our strength,
and also for becoming His ministers--speaking to others only what He first spoke to us.
Oh, that people would truly and seriously consider this!
Then they would not run after or follow such ministers, priests, or prophets,
who run when God never sent them; who say,
"`Thus says the Lord,`" when God has not spoken to them.
These are those of whom the Lord has declared,
"`they cause My people to err by their lies and by their recklessness.
Yet I did not send them or command them;
therefore they shall not profit this people at all.`"^
footnote:[Jeremiah 23:32]

Even before I was esteemed a Quaker, or was joined in communion with them,
I had some understanding given to me concerning those parish ministers, or priests,
that they were not sent by God or Christ,
and had no divine commission or call to the ministry.
I saw that they were made and set up by the will of man,
and preached not their experience,
but rather what they studied or gathered from others or composed beforehand,
without either waiting for,
or receiving immediate openings or instructions from the Spirit of Christ.
Indeed, many had not so much as a belief in the Spirit`'s influence,
or the necessity of immediate help from the Spirit and power of
Christ Jesus in order to minister or preach Him in these days.
Much to the contrary, they have openly denied these things,
and opposed our Christian testimony therein,
which none of Christ`'s true sheep or flock will do,
for they both hear and know Christ`'s voice,
and follow Him--He being their leader and commander--but a stranger they will not follow.

Their pride and covetousness set many well-inclined people against them,
and caused some to turn away from them;
and even more so when many of them showed their envy and covetousness in persecuting,
imprisoning,
and greatly oppressing the people called Quakers for conscientiously
refusing to pay tithes or failing to gratify their avarice.
For the meager value of a tithe pig or goose,
they have mercilessly prosecuted many honest men to imprisonment in jails,
as if they valued their neighbor`'s pig or goose (which they
coveted) more than the liberty or life of their neighbor.
But when the priests became rigid persecutors and oppressors,
it turned greatly to their own disadvantage, disgrace and shame,
for it set the tender-hearted people against them, and caused our numbers to increase.
Though but weak in ourselves,
we came to be more confirmed in our views concerning those persecuting ministers,
or parish priests,
knowing that the Christian religion is not a cruel or persecuting religion, but tender,
loving, and compassionate.
We knew also that true Christians were persecuted, but they were not persecutors;
they were patient sufferers, not oppressors; they prayed for their enemies,
but sought no revenge against them.

I was early convinced and persuaded that tithes ought not
to be required or paid under the gospel dispensation.
And the reason why the people called Quakers could not (for conscience
sake) pay tithes or oblations in this gospel day,
is chiefly: First, because Christ`'s ministry is and ought to be a free ministry,
as He commanded His ministers; "`Freely you have received, freely give.`"^
footnote:[Matthew 10:8]
And secondly, because Jesus Christ, the one offering,
the great Apostle and High Priest of our Christian profession, has,
by the offering and sacrifice of Himself, put an end to tithes,
oblations and priests`' revenues,
together with the entire priesthood and first covenant
under which these things were upheld and maintained.
This is made plain by the reasons and arguments which the
apostle gives and urges in his letter to the Hebrews,
in the 7th, 8th, 9th and 10th chapters.
So that to demand tithes and oblations, revenues or priestly dues,
appears to be a denial of Christ crucified, and His being offered once for all,
and consequently a denying of the privileges of the new covenant dispensation and ministry,
which were ratified by Him through the death of the cross.

But to return to my own inward state,
and the experience of my spiritual travel and progress:
The Lord was graciously pleased to lead me through the law,
through judgment and condemnation against sin in the flesh (which Christ came to condemn),
in order to bring me to the more glorious ministration
and "`law of the spirit of life in Christ Jesus,`"^
footnote:[Romans 8::2]
which is the foundation of the apostles and prophets.
I was brought to experience the mystery of John`'s ministry of repentance,
the washing of regeneration, the axe being laid to the root of the trees,
as well as the cutting off of all superfluous branches,
that a thorough work of regeneration might be wrought.
These things were spiritually, and by degrees, experienced inwardly,
through the obedience of faith, waiting and persevering in the grace, light,
and truth received from Christ, in order to obtain victory over sin and Satan,
that his work of sin, and the body thereof, might be destroyed in root and branch.

And whatever divine openings, prophecies, sights, or discoveries,
the Lord was pleased at any time to give me by His Holy Spirit for my encouragement,
or for the increase of faith and hope,
I saw I must still be mindful of His inward work of grace, sanctification and holiness,
that it might go on and prosper.
Although many weaknesses and temptations attended me, His grace was sufficient for me,
and oftentimes gave me strength and victory over the enemy of my soul,
and frustrated his evil designs.
When he would have come in like a flood with manifold temptations and devices,
the Spirit of the Lord lifted up a standard against him, and repelled him.
Glory to our God, and to the Lamb,
in whom is our salvation and strength forever and ever,
whose kingdom is an everlasting kingdom, and His dominion without end.

Our blessed Lord Jesus Christ declared, "`If anyone wills to do His will,
he shall know concerning the doctrine.`"^
footnote:[John 7:17]
So in the day of His power, as the light did appear,
a willingness was wrought in my heart to do His will, as it came to be made known to me.
And I was made willing to follow Him in self-denial, taking up the daily cross,
which every man must do if He seeks to be His disciple.
Thus by His light and teaching I came livingly to believe, to understand,
and to receive those doctrines and principles which
are essential to Christian life and salvation,
especially and particularly these following:

[.numbered-group]
====

[.numbered]
1+++.+++ God`'s free love in His dear Son Jesus Christ,
and His universal grace in Him offered to all mankind;
that Christ died for all men who were dead in their sins,
and gave Himself a ransom for all, for a testimony, in due time,
of God`'s free love to mankind in general.
For it was by the grace of God that Christ tasted death for every man,
so that now the free grace and love of God to mankind are testified and evident,
both in Christ`'s dying for all men, and by His being the "`Light of the world,`"^
footnote:[John 8:12]
"`which enlightens every man coming into the world.`"^
footnote:[John 1:9]

[.numbered]
2+++.+++ The necessity of man`'s repenting and truly believing the gospel,
and of his being converted to Christ in such a way as to truly receive Him,
and to experience a living and steadfast faith in Him, in His light, name and power,
in order to become the children and sons of God.
For it is by His power, and through faith therein, that men are made sons of God,
and not by an outward profession or traditional belief,
without spiritually receiving Christ into their hearts.
For men must know His work of faith and power within them,
unto conversion and a real change of their hearts and minds,
by the washing of regeneration which is sanctification,
or the one saving baptism of the Spirit, which washes us from our sins,
and restores us to newness of life in Christ Jesus.

[.numbered]
3+++.+++ To understand and witness the true and acceptable worship of God,
that it is "`in Spirit and in the truth;`" and not according
to human traditions or forms of men`'s prescribing.
This indeed is a great satisfaction to the soul:
to be retired in mind and spirit to that Holy Spirit and truth, even the living Word,
wherein God can truly be worshipped, bowed unto, and waited upon in true humility;
for herein He comforts and refreshes His people, and causes living praise to arise.

====

All of these things are agreeable to the testimony of holy Scripture,
and are known and understood by every true believer in Christ,
who is our light and our life.

From my childhood, I had always had a love for the Bible and for reading therein,
yet I did not truly understand or experience the doctrines essential to salvation,
nor the new covenant dispensation, until my mind was turned to the light of Christ,
the living and eternal Word,
"`the entrance of which gives light and understanding to the simple.`"^
footnote:[Psalm 119:130]
Yet I do confess,
it was some advantage to me to have frequently read the holy Scriptures even when I
was ignorant and did not understand the great and excellent things testified therein.
For when the Lord had in some measure livingly opened my eyes to His blessed truth,
my having often read the Scriptures from a child and become familiar with them,
proved a help and advantage in my secret meditations,
when a living sense and comfort concerning the things contained
in Scriptures was in measure given to me by the Spirit.
Hereby I was even more induced to a serious reading
and consideration of the sacred writings.
And indeed I found that all the promises of God, which are yes and amen in Christ Jesus,
are truly comfortable when applied by the same Spirit;
for He will make no wrong application of them.
The Spirit will never apply peace to the wicked, nor to persons living in their sins;
nor tell the unjust that they are just or righteous in God`'s sight.

It is through "`the faith which is in Christ Jesus,`" that the holy Scriptures are said
to make the man of God "`wise unto salvation,`" being profitable to him "`for doctrine,
reproof, admonition, and instruction in righteousness,
that he may be perfect and thoroughly furnished in every good word and work.`"^
footnote:[2 Timothy 3:15-16]
Doubtless,
Paul esteemed Timothy`'s knowing the holy Scriptures from
a child to be of some advantage and help to him,
but their benefit is principally "`through the faith which is in Christ Jesus.`"

These things being duly considered,
I desire that Christian parents not be remiss in
causing their children to read the holy Scriptures,
but rather to induce them both to learn and frequently to read the Bible.
This may be of real advantage and profit to them
when they come to have their understandings enlightened,
and to know the Truth as it is in Christ Jesus.
Indeed, I have sometimes observed children when reading the Bible,
become very affected by the good things they have read.
And these, from a secret belief and impression which is stamped in their young hearts,
have been more induced to seriously peruse the Scripture when the Lord subsequently
opens their understandings by the light of His grace within them.

But by what I have here declared in commendation of holy Scriptures,
and the advantage thereof,
I would not be understood to limit the gift of the Spirit
of God or His ministry and divine graces from the illiterate,
the unlearned, or from persons of little education, such as plowmen, herdsmen, shepherds,
fishermen, etc.
For God has indeed given His good Spirit and spiritual gifts to such as these,
and has promised "`to pour out of His Spirit upon all flesh,
that sons and daughters should prophesy.`"^
footnote:[Joel 2:28; Acts 2:17]
And Moses said, "`Oh,
that all the Lord`'s people were prophets and that
the Lord would put His Spirit upon them!`"^
footnote:[Numbers 11:29]--among whom, both men and women,
learned and unlearned are included.

My entrance into, and beginning in the Spirit,
and believing in the light of our Lord Jesus Christ,
was in order to really come into the new covenant and gospel dispensation;
for Christ was given both for a light and a covenant,
and to be God`'s salvation to the ends of the earth.^
footnote:[Isaiah 42:6; 49:8]
This new covenant is a covenant of grace,
and of mercy and peace with God in His dear Son Jesus Christ.
This is the reconciliation, or near agreement with God and Christ,
which man must come into if ever he will enjoy true peace.
It is in this covenant that all the Lord`'s people and true Christians know Him,
from the least to the greatest, and where all are taught of God,
having His laws written in their heart by His divine finger,
and put into their minds by His Holy Spirit.

It is in this covenant that the Lord blots out all their former, forsaken transgressions,
and remembers their sins and iniquities no more,
so long as they continue in this everlasting covenant and in His goodness.
He is a God keeping covenant and mercy forever to all that truly fear Him.
And so my cry, my soul`'s breathing, my inward spiritual travail,
and my watching and praying have been to this end: "`O Lord,
preserve and keep me in Your holy fear, in humility, in the sense of Your power,
that I may never depart from You or from Your covenant;
that I may never dishonor Your Truth or our holy profession!`"
And hitherto the Lord has helped me on my spiritual journey and race towards the prize.
I ascribe the glory and praise to Him alone, for He gives power to the faint,
and to those who have no might He increases strength;
and often in my weak state He has manifested strength.

It was my early belief and persuasion when convinced of the blessed Truth,
that all who are truly called to be ministers of
the everlasting gospel and preachers of righteousness,
must be sanctified, divinely inspired, and gifted for that sacred work and service.
They must be careful that their conduct be such as adorns the gospel;
they must live good lives, as well as speak good words;
they must be men who fear God and shun evil,
who hate covetousness and give no offense in anything,
so that the ministry cannot be blamed.
Concerning this,
the Lord has laid upon me a godly care (which still remains upon me to this day,
both for myself and others), that our ministry indeed be blameless,
and that no offense may be given to cast reproach upon it.
What good is it for any to have a name to be alive, when they are dead?
What will it avail them?
Or what good is it for loose, vain, proud, covetous,
or unsanctified persons to claim to be in a holy way,
when they themselves are altogether unholy, polluted, and sinful?
In my very young years I was fully persuaded that Jesus Christ would neither
employ wicked or corrupt persons in His sacred service of the ministry,
nor grant His presence to such as these in their preaching,
whatever they pretend or profess in His name.
It is the faithful ministers who truly obey Him and follow His example,
that Christ will accompany with His divine presence
and assistance in their ministry and gospel testimony.
Yes, it was to such as these that He gave that great encouragement and promise: "`Lo,
I am with you always, even unto the end of the world.`"

What that kingly prophet David earnestly prayed in Psalm fifty-one,
does truly set forth the state and condition of real gospel ministers,
whose ministry is attended with God`'s power and presence and thereby
made effectual for the conversion of sinners unto Him.
"`Wash me thoroughly from my iniquity, and cleanse me from my sin.
Create in me a clean heart, O God; and renew a right spirit within me.
Cast me not away from Your presence; and take not Your Holy Spirit from me.
Restore unto me the joy of Your salvation; and uphold me with Your free Spirit.
_Then_ I will teach transgressors Your ways; and sinners shall be converted unto You.`"

These things I have sincerely aimed at, and earnestly desired of the Lord.
Inwardly in spirit I have travailed for them with my whole heart and soul.
And I can truly say that the Lord, in measure, answered me herein,
before I began to travel abroad in the ministry of
the gospel of Christ--even the gospel of His grace,
which grace He gradually gave and increased unto me and in me from very small beginnings.
Blessed be His most excellent name forever; for He promised unto His people, saying;
"`I will give you shepherds according to My heart,
who shall feed you with knowledge and understanding.`"^
footnote:[Jeremiah 3:15]

The only true shepherds and ministers are those who are of God`'s giving.
Many has He given, and even more will He give to His church in this gospel-day,
according to what was testified by one who preached
both the coming of Christ in the flesh,
and the mystery of His coming in Spirit--"`Even the mystery
which has been hidden from ages and from generations,
but now has been revealed to His saints.
To them God willed to make known what are the riches
of the glory of this mystery among the Gentiles:
which is Christ in you, the hope of glory.
Him we preach, warning every man and teaching every man in all wisdom,
that we may present every man perfect in Christ Jesus.
To this end I also labor, striving according to His working which works in me mightily.`"^
footnote:[Colossians 1:26-29]
And according to a real belief and persuasion that
God would reveal this mystery of Christ in us,
I was made tenderly concerned to wait for it, that I might experience, witness,
and feel the power and coming of Christ inwardly in Spirit, both to sanctify my heart,
and to give me understanding to do His will.

And when He called me to bear testimony of His name and power,
and also of His inward and spiritual work in man,
I was engaged in spirit to wait for His power and Spirit to move and work in me,
that I might labor in His service according to His working in me,
and not otherwise to run or to strive in my own will, wisdom, or strength,
knowing that without Christ (His power and presence,
help and counsel) I could do nothing of myself, nor for anyone else.
And when my ability was but small, and I was in much weakness,
fear and trembling many times, the Lord helped me,
and increased strength and ability in my labors beyond expectation.
But this care always rested upon me, even in my early travels:
to minister only according to the ability and gift given to me by my heavenly Father,
and so to keep within the compass of my own gift and ability.
And so when the Spirit of the Lord opened and moved in but a few words,
I dared not exceed it, but rather sat down in silence when it ceased.
Many times in waiting upon the Lord, and secretly breathing to Him in silence,
the spring of life would arise and open counsel afresh
to my own and other souls`' refreshment and consolation.
Often has my soul been brought very low,
and the Lord has helped me and renewed my strength to persevere in His service.
Thus I became sensible that the more low I was in myself,
and the more I was kept in fear toward God, though but weak and simple of myself,
the more He would manifest His power through me, and bless my endeavors and service.
Let Him have the praise of all, who is forever worthy.

After many blessed and comfortable seasons and refreshments
from the presence of our heavenly Father,
which we enjoyed in our meetings in the northern parts;
and after having cleared my conscience in a testimony for the Truth,
both in word and Christian conduct toward my parents and relations,
a weighty concern came upon me (after harvest,
in the year 1654) to leave my father`'s house and county of Westmoreland,
and to travel southward.
I acquainted some Friends with my prospect,
and my dear friend Edward Edwards--who then was a young man and lived at Gervase Benson`'s,
near Coatley Cragg,
though he was not then called into the ministry--gave
up to travel with me and to keep me company.
Both of us were given up to travel on foot, and went together some sixty miles to York,
where we stayed two or three days and attended a Friend`'s meeting there on first-day,
which was small, but the Lord gave me a few words to livingly declare among them.

From there we travelled southward in Yorkshire,
and met with our beloved friend and brother in Christ, George Fox,
at the home of Captain Bradford`'s, where we attended a meeting with him in the evening.
Afterward we travelled into East Holderness, to Joseph Storr`'s,
where again we met up with George Fox, and several other Friends,
and were comforted together.
We travelled a little while in that country to some other meetings with George Fox,
who then had the public service laid wholly upon him,
for the strengthening and settling of Friends in the Light and in the Truth.

Before I left that county I had some testimony laid upon me to bear at two steeple houses,
but I met with no hard usage, except for being haled out of their meeting place.
But the Lord supported me in faith and hope for the service He had for me further south.

My honest, dear friend, Edward Edwards and I parted in Holderness,
and then Thomas Ralison (who had travelled with George Fox) came with me to Hull,
from which we crossed the river Humber in a boat about four miles over into Lincolnshire.
We had a rude, abusive, drunken company in the boat,
who threatened and otherwise abused us,
but the Lord preserved us from being harmed by them.
The next day, being first-day,
a burden came then upon me to go and bear testimony for the Truth at two steeple houses,
one in the forenoon, and the other in the afternoon.
I had no harm or violence done to me at either,
except for pulling or pushing me out of the meeting.
But Thomas Ralison being at the meeting in the afternoon, was abused and beaten,
and then followed into the field by a parcel of young fellows.
I was sorry that he was so evilly treated.

The next day he and I parted, and I travelled on toward Lincoln,
taking a meeting along the way, where the Lord opened my mouth in a living testimony.
I stayed but one night in Lincoln,
being pressed in spirit to travel forward toward Cambridge and Norwich,
though left to travel alone, and still on foot.
I went to Cambridge from Lincoln in less than three days,
though my feet were pretty much raw and blistered even before I came out of Yorkshire;
yet they mended while I travelled, even before I got to Norwich,
and I was preserved in health all along,
which I thankfully esteemed as a great mercy from God,
being then not yet eighteen years of age.

At Cambridge I was received kindly by alderman Blakeling and his wife,
and by the few Friends there.
James Parnell met me before I went from there, and we were comforted together.
After two or three days`' stay, I was still pressed in spirit for Norwich.
From Cambridge, Thomas Lightfoot travelled with me toward Norwich,
and we got within about three miles of Thetford in Norfolk the first night,
the weather being wet and showery.
It proved difficult to get lodging for our money at a little village where we stayed,
for then the people were very shy or timid of us;
yet finding a house where they sold beer,
we prevailed with them to accommodate us for the night,
but the room in which we lodged was but cold and decrepit,
and the window so shattered that the snow came in upon us.
The next day we travelled to Windham, which is about six miles from Norwich,
where Robert Constable and his wife kindly received us,
both having been convinced of the Truth a little time before
by the testimony of our dear friend Richard Hubberthorn,
who was then a prisoner in Norwich castle,
for bearing public testimony to Truth at the steeple-house at Windham.

From Windham we went to Norwich the next day,
and I visited Richard Hubberthorn in prison,
where we gladly embraced each other in dear and tender love,
and were comforted together in the Lord.
There were then a few Friends in that city who had
been convinced by his testimony and sufferings,
and some having come to visit him in prison, had been united to Truth and Friends.

The most noted and serviceable Friend then in that city was Thomas Symonds,
a master-weaver, who received traveling Friends into his home.
He was a loving, honest man, and came to receive a gift in the ministry,
and was faithful unto death.
He lived and died in the faith,
and was made partaker of the promises which are yes and amen in Christ Jesus.
He was exemplary in the Truth,
and serviceable both in the city of Norwich and the county of Norfolk, where he lived.

Though I expected to suffer imprisonment in that city,
yet the Lord so ordered it that I had liberty for some weeks
to have several meetings at Thomas Symonds`' house in Norwich,
and at Windham, in the home of Robert Harvey`'s, a glover, who was an honest,
innocent man, that received the Truth in the love of it.
To a meeting at his house came Captain John Lawrence,
who being then tenderly affected with the Truth,
was desirous I should have a meeting at his house at Wramplingham,
which I was very willing and glad to do.

To that meeting came three priests to oppose me, Jonathan Clapham, priest of the town,
and two others.
They stayed in the parlor until the meeting was settled, and then peeped out to see me.
My appearance was contemptible in their eyes,
for they esteemed me but a boy because of my youth, and not fit to discourse with them.
Nevertheless,
Jonathan Clapham at length began to oppose and interrogate
me about our not respecting persons by bowing and scraping,^
footnote:[The normal greetings between peers at that time
involved scraping the right foot backwards along the ground,
bowing low while removing the hat,
and then flattering one another with titles like
"`your Lordship,`" "`your Eminency,`" etc.]
etc., being an ambitious man,
who regarded worldly honor and the respect of persons
more than seeking the honor which is from above.
He pleaded what he could for these traditions,
and the Lord gave me suitable and scriptural answers, which,
in the spirit of meekness I returned upon him and his party,
and also laid open some of their unscriptural and unwarrantable practices;
and feeling the Lord`'s power and counsel with me,
I had dominion given me to vindicate the Truth, to the confounding of its opposers.
After a short time, Jonathan Clapham and another priest withdrew,
but the third stayed until the meeting was over;
for after the contest with the other two priests had ended,
I had a very good and blessed opportunity to declare the Truth.
I opened several weighty matters according as the Lord was pleased
to open them to me and to enlarge my spirit to demonstrate them,
so that, at one meeting, most of John Lawrence`'s family, along with several others,
were convinced and persuaded of the way of Truth.

The Lord gave me great comfort and encouragement that day
by His divine assistance in His work and service.
The Friends present were greatly satisfied,
and the priests`' contempt of me (a poor servant and weak
instrument) turned to the contempt and disgrace of themselves,
so that I then had (and have often had since) true cause
to ascribe the glory and praise to the Lord our God,
and to declare that,
"`Out of the mouth of babes and nursing infants have you ordained strength,
because of Your enemies, that You might silence the enemy and the avenger.`"^
footnote:[Psalm 8:2]

John Lawrence received the Truth and gave up freely in obedience thereunto.
When he knew a beginning in the Spirit, he did not turn back, but persevered,
and bore a faithful testimony in suffering for the truth,
both in person and in loss of goods.
He and his family turning to Truth and joining with Friends
was a means to draw many away from the mercenary priests,
unto Christ--His light and free ministry--that they might know Him to be their minister,
their High priest, their Shepherd, and the bishop of their souls.

Near that time, in the ninth and tenth months of 1654,
I had several meetings in and near Wymondham, and in Norwich.
The Lord was with me, and helped me to declare His name and truth,
to preach the everlasting gospel, and to turn many from darkness to the light,
and from the power of sin and Satan unto God and His power,
that people might not continue in empty forms and shadows,
but come to the life and substance of true religion, and to the power of godliness,
and to know Christ to be their teacher and leader, whose voice His sheep hear,
and will not follow the voice of a stranger.
Many in those parts were convinced of the truth of these things,
and turned to the light of Christ within them.
Let the work of the Lord praise Him which began in those days,
and has since prospered in those parts,
both in the offspring of many who then first received the love of the truth,
and in many others,
whom the Lord has blessed in their obedience and willingness to serve Him,
having come unto the dawning of the day of Christ`'s power,
wherein His people are made a willing people.

The first opposition I met with at a meeting in the
city of Norwich was at Thomas Symonds`' house,
by an Antinomian^
footnote:[_Antinomianism_ (meaning _"`against law`"_) is the belief that grace in the new
covenant releases men from any obligation to observe the moral law of God.]
preacher, who pleaded from Paul`'s warfare in Romans 7 that sin must continue,
even in the best of saints, throughout life; and that though men continue sinners,
they are not under the law, but under grace and reckoned righteous in Christ.
We met with much similar sin-pleasing doctrine from
the professors of Christianity in those days,
whom in the name of the Lord we withstood, as I did this Antinomian;
and by the Lord`'s help, I stood over him and his perverse arguments,
much to his confusion.
I saw that the Antinomians were very dark and corrupt in doctrine,
and stood contrary to Christ`'s work,
which is to destroy sin and to save His people from sin and transgression.

At that meeting there were also some of the people called Ranters,^
footnote:[Ranters were a somewhat odd,
non-conformist group that sprung up in the mid 1600s. Many
denied the authority of both the church and the Scripture,
and instead promoted a sort of pantheism, insisting that God was in every creature,
and that sin was nothing more than the product of human imagination.
Ranters would often interrupt established religious gatherings with shouting (ranting),
singing, playing instruments, or making other loud noises.]
who allow corrupt, fleshly liberties.
One of the chief of them seemed to acknowledge what I said against the Antinomian,
but I had a sense given to me that he was of a corrupt spirit,
and I told him that I denied his spirit also,
for I felt a zeal from the Lord against them both.
The Lord`'s power was over all,
and in His service He encouraged me from one meeting to another,
insomuch that I was sure the Lord stood by me,
and strengthened my spirit in His work and service.
And the more I travelled and labored therein,
the more my strength in Him increased--for which
my soul did often praise His glorious name,
and sing praises to Him even in solitary places.

A little time after this I had another meeting at Thomas Symonds`' house in Norwich,
on a first-day of the week.
A company of those persons came who were in the spirit of ranterism,
and also the same person who seemed to take my side against the Antinomian opposer.
The power and dread of the Lord God fell weightily
upon me to bear testimony against sin and wickedness,
both root and branch--against the lust of the flesh, the lust of the eye,
the pride of life, and the love of the world.
And the powerful Word of the Lord pierced through the meeting,
and so wonderfully struck down the spirits of those ranters and other loose spirits,
that they came to me afterward like men greatly wounded
and brought down from their high floating notions,
now questioning their salvation,
which before they had assumed was like a mountain that could never be removed.
Yes, now they were under doubts and fears and full of questions,
like the jailer in Acts who fell down trembling and said to Paul and Silas, "`Sirs,
what must I do to be saved?`"
In compassion to their poor souls,
I earnestly exhorted them to bear the judgment of the Lord, and His indignation,
because they had greatly sinned against Him,
that they might find mercy from Him through true humiliation and repentance,
with other necessary counsel and warning,
as the Lord by His light then showed me was most suitable to their conditions.

I had not been acquainted with this sort of people before the meetings in Norwich.
Most of them were convinced of the truth,
and several of them became reformed in their lives and conduct;
though some turned back into their corrupt carnal liberty, through carelessness,
and lack of watchfulness, not keeping in the fear of God.
Indeed, we have seen in our day, that wherever the deadly wound in the beast,^
footnote:[Revelation 13:3]
or beastly nature, has been healed,
in those who have not gone forward through mortification,
nor patiently waited to see judgment brought forth into victory, these have miscarried,
and turned the grace of God into licentiousness in order to embrace the world.
Thus they have sold the truth, and themselves too, even their poor souls,
for their own iniquities, as Isaiah has testified, "`Behold,
for your iniquities have you sold yourselves.`"^
footnote:[Isaiah 50:1]

[.asterism]
'''

+++[+++_Note from the editor:_
George Whitehead was one of several young and unschooled messengers of
the gospel whom the Lord sent forth at this time from the northern,
rural parts of England into the more populated south,
in order to call a high-minded nation to repentance, and turn them from their dead,
formal religious professions to the life and light of Jesus Christ.
George Fox, James Parnell,
Richard Hubberthorn--who have already been mentioned--along with Edward Burrough,
James Nayler, William Dewsbury, John Burnyeat, and many others,
though young in years and unimpressive in appearance, descended upon London, Bristol,
Oxford, Reading, and other larger cities, being clothed with that humility, wisdom,
and authority that are only obtained in the Spirit`'s school of Christ.
Isaac Penington was then a resident of London,
and a diligent seeker of the kingdom of God,
though not yet in fellowship with the Society of Friends.
The reader may be interested in Penington`'s description of these
"`young country lads`" when they first came down from the north
with glad tidings of spiritual and substantial Christianity.

[quote]
____
+++[+++Consider now]
the contemptibleness of the vessels, which the Lord chose to fill with His treasure,
and through whom He began to pour forth this dispensation of life.
They were for the most part lowly as to the outward; young country lads,
of no deep understanding or ready expression,
but very fit to be despised everywhere by the wisdom of man,
and only to be acknowledged in the power of that life wherein they came forth.
How ridiculous was their manner of coming forth and appearance to the eye of man!
About what poor trivial circumstances, habits, gestures,
and things did they seem to lay great weight and make great matters of importance!
How far did they seem from being acquainted with the mysteries and depths of religion!
But their chief preaching was repentance, and about a light within,
and of turning to that,
and proclaiming the great and terrible day of the Lord to be at hand; wherein, I confess,
my heart exceedingly despised them,
and I cannot wonder that any wise man or professing Christian did,
or still do despise them.
Yes, they themselves were very sensible of their own weakness,
and their unfitness for that great work and service wherewith the Lord had honored them,
and of their inability to reason with man.
And so, in the fear and in watchfulness of their spirits,
they kept close to their testimony, and to the movings of His power,
not looking to answer or satisfy the reasoning part of man,
but singly seeking to reach to and raise the gift of that Seed in man,
to which their testimony was directed.

And O the blessing that God gave to this His dispensation of life in their hands!
O how did the Lord prosper them,
in gathering His scattered wandering sheep into His fold of rest!
How did their words drop down like dew, and refresh the hungry, thirsty souls!
How did they reach to the life in those to whom they ministered,
raising up that which had lain as dead in the grave,
to give a living testimony to the living voice of God in them!
How did they batter the wisdom and reasonings of man,
making the loftiness thereof stoop and bow to the weak and foolish babe!
Eye has not seen, ear has not heard,
nor has it entered into the heart of man to conceive,
what the power of life has wrought through them,
in the hearts and consciences of those who have longed after and waited for the Lord.
Oh! the breathings and meltings of soul, the sense of the living presence of God,
the subjecting of the heart unto the Lord,
the awakening of and giving strength unto His inward Witness,
the falling down and weakening of the powers of darkness,
the clear shining of the light of life in the heart,
and the sweet running of its pure streams into enlivened souls,
which has often been known and confirmed by the powerful
appearance of God in their ministry!

Indeed, when I have considered these and such like things in my heart,
and closely watched them in my converse with them,
I have been often forced to cry out concerning them,
'`Truly here is man very weak and contemptible; but God very glorious and powerful!`'
And indeed, when at any time I looked on the man,
I was hardly able to keep from disdaining them; but, on the other hand,
when the eye of my spirit beheld the power and glory of the Lord in them,
I could hardly forbear over-esteeming and exalting them.

And now, these many years later,
how has the Lord advanced these vessels to greater
glory since His beginning to make use of them.
How has He enriched them with gifts and abilities,
and in every way fitted them for the service and employment He has had for them!
How has He enlarged their ministry, that they who once had very little to say,
either by way of declaration or disputation at first, now abound with strength,
and abundantly surpass the knowledge and wisdom both of the world,
and of other professors of religion!
The Lord indeed has adorned them, putting His beauty upon them,
and causing them to grow up in His strength and in His wisdom.
This my eye has seen, and often took notice of, blessing the name of the Lord,
and praying to Him for their preservation.
And surely, whoever he may be, that has either known himself,
or heard the relation of the poverty of these young striplings
when they first came forth in the power of the Lord,
how empty in themselves they then were,
how carefully they went up and down in their own weakness,
how little they had to say to people that came to observe them and inquire of them,
how afraid they were to be drawn from their watch,
at what a distance they stood from entering into reasoning about things; I say,
he that does know and consider this,
and also beholds how the Lord has advanced them since,
making them mighty and honorable with His gifts and abilities,
cannot but acknowledge the change to be wonderful.
____

[.asterism]
'''

It was about this time that I +++[+++George Whitehead] first met our ancient and faithful friend,
William Barber, of Gissing, in the county of Norfolk.
I declared the truth to him and some others who were present,
and opened something of the mystery of Christ and
of the ministry and work of His Spirit within,
along with the enemy`'s contrary work in man,
as the Lord was pleased to open and enable me.
William was very tenderly affected, and broken into tears, and his spirit was humbled,
though he had been a great man in the world and a captain in the army.
Truth was near him, and I felt him near it,
and my heart was open and tender toward him in the love of Christ.

It was some time later that I first met his wife.
She was an honest, sober woman,
who received the truth and Friends in great love and tenderness,
and continued a faithful, innocent and loving Friend until her dying day.
I observed how the Lord had endued her with much patience,
especially during the great and long suffering her
husband endured by imprisonment in Norwich Castle,
for the space of twenty years or more,
chiefly for non-payment of tithes to an old priest of the parish,
who appeared implacably malicious in his prosecution, or rather persecution and revenge.
William Barber bore a faithful testimony through patience and long-suffering.
I know of none who suffered like him in those parts,
though many Friends thereabouts have suffered deeply on the same account,
and the Lord supported them therein.

A few days after, it being near the end of the tenth month, 1654,
there was a lecture at what is called Peter`'s Church in Norwich,
and I believed it required of me to go there and bear such
testimony as the Lord would be pleased to give me,
being endued with a holy zeal against iniquity,
and the pride and covetousness of the high priests in those days,
as well as with compassion for the ignorance and blindness of the people misled by them.

When the priest, one Boatman, had ended his sermon,
I was permitted to say but very little--just a few words against iniquity--before
some of the priest`'s hearers came violently upon me to hale me out,
some pulling me by one arm, and some by the other;
some striving to hale me out at the north door, and some out at the south porch.
By their violence I received some hurt and inward pain in one side of my breast,
being overstrained by their pulling and haling me contrariwise;
but it pleased the Lord in a few days to remove the
hurt and pain I got by their hard usage.
From the steeple-house I was haled to Guild-hall, before Thomas Toft, mayor,
who after examining me about water baptism and some other things,
committed me to the city jail.

In a little more than two months, in the first month 1655,
I was released from my bonds and travelled in Norfolk and Suffolk towards Ingworth,
Lammas and those parts, as well as Windham, Wramplingham, and New Bucknam.
My dear friend and brother Richard Clayton was with me at some meetings in Norfolk where
there was an honest-minded people inquiring after the Lord and His living truth,
whose hearts He had prepared to receive the love of the truth.
And I well remember in what manner the Lord opened my heart
and enlarged me in gospel testimony toward those people;
it was much in testimony to the universal love and grace of God,
the light of Christ given to every man.
I labored to turn their minds to it,
and showed that they must wait in this light to know God`'s teachings,
and to come into the new covenant dispensation where
all the Lord`'s people are taught of Him,
and may know Him, from the least unto the greatest,
as they witness His law written in their hearts and His Spirit in their inward parts,
according to His blessed promises; for this is the new and everlasting covenant,
prophesied of by the holy evangelical prophets.

In this new covenant,
not only the house of Israel and Judah may have a share and be partakers of Christ,
but all truly believing Gentiles also,
to whom Christ has been given as a light and a covenant,
and to be God`'s salvation to the ends of the earth.
For God is not only the God of the Jews, but the God of the Gentiles also;
and they are the true Jews and the true Israel who are spiritually such; that is,
inward Jews,
by the spiritual circumcision of the heart performed by the Holy Spirit of God.

And in order to come under this new covenant dispensation and ministry,
and therein to know and experience Christ to be their minister, their teacher,
their high priest and prophet, the people were encouraged to cease from man,
and from all ministers and priests that were made so by the will of man;
and to turn away from hired ministers who preached for filthy lucre and dishonest gain,
making a trade of the holy Scriptures, and adding their own divinations,
meanings and notions to them, having no divine revelation,
or commission given them to preach,
much less to make a trade of the words and testimonies of the holy prophets,
Christ Jesus, or His apostles,
even as they walk contrary to their steps and practices in pride and covetousness.

The Lord often laid a pressure upon me to testify
against the pride and covetousness of the priests,
and their preaching for hire, for obligatory tithes and forced maintenance,
contrary to Christ`'s command, and His ministers`' example.
And for this cause the religious leaders were the more envious against us,
and in their pulpits exclaimed and made a great noise to incense
the people and magistrates against the Quakers (so called),
even unto severe persecution and imprisonments.
But it is still a matter very memorable to me,
that by preaching livingly concerning the light, the new covenant,
the Word near to people in their hearts, yes,
the gospel of the grace and love of God in Christ to mankind,
many were really and effectually convinced and persuaded
of the blessed and everliving truth as it is in Christ Jesus,
both in the counties of Norfolk, Suffolk and Essex,
where the Lord led me early to travel, and helped and prospered me in His service;
blessed and praised be His name forever.

The same year 1655, about spring time,
John Lawrence was summoned to a meeting at a parish church in Norwich,
where the leaders were intending to excommunicate him.
I went with him there, and found a great concourse of people, men and women met together,
along with their pastor and elders.
They repeated their allegations against him, namely,
that he had forsaken their communion, entertained strangers or dangerous persons,
and held dangerous doctrines.
John Lawrence then gave his reasons for leaving their communion,
answering that the apostle Paul had exhorted all to turn
away from such men as "`have a form of godliness,
but deny its power,`" who are "`lovers of themselves, lovers of money, boasters,
proud,`"^
footnote:[2 Timothy 3:2, 5] etc.

After this, in the fear and dread of the Lord,
I stood up to declare a few words among them, but they quickly pulled me down,
and by force held me down in the pew where we were.
Some of their members then forcibly haled and pushed me out of the steeple-house,
and exposed me to a rude multitude, who stood ready to lay violent hands upon me.
They pushed and haled me away through the streets and the market place of the city,
sometimes throwing me down upon the stones, whereby I was bruised and hurt.
They followed and encompassed me, pushing me along, roaring and shouting,
until I came near to the city gate, called Giles`' gate, next to a little pasture ground.
At the upper end of the pasture I saw a large house,
where the lady Hubbard dwelt (as I understood afterward).
Upon seeing the house,
I was in a great predicament in my mind--the tumult being
great around me--whether I should then go out of the city,
in order to go toward Wramplingham to John Lawrence`'s, which I desired,
or whether I should turn up toward this large house,
desiring the Lord to direct me at that instant.

I considered that if I should turn out of the city into the highway,
toward Wramplingham,
I might be in danger of losing my life out on the road or in a field
by the violent tumultuous company that was then about me,
and my death would be less taken notice of.
But if I was to lose my life,
I thought it would be better to die where my testimony
could be borne within the city of Norwich,
and where my persecution had begun,
rather than be killed more secretly by the tumult outside of the city, or out in a field;
for I was given up to suffer whatever violence the Lord might permit them to do to me.

On due consideration, I immediately turned up toward the lady Hubbard`'s house,
with the raging company continuing still about me.
By reason of the noise and shouting, the lady`'s chaplain, Dr. Collins,
and most of the family, promptly came out to see what was the matter,
and why such a mob had approached their house.
When they saw that I was the person beset and persecuted,
the chaplain (understanding that I was a Quaker) undertook to discourse
with me concerning the Spirit which the apostles of Christ had,
asking me if I had the same Spirit?
I acknowledged that in my measure I partook of the same Spirit,
though I would not equal my degree of attainment to theirs.
If I had that Spirit, the chaplain replied, why not prove it by some sign or miracle,
or by speaking in tongues, as the apostles did.
I answered him according to the apostle Paul`'s words on that subject,
speaking of the diversities of gifts given by one and the same Spirit.
I told him, not all who had the Spirit of Christ had those same gifts,
such as tongues and miracles; for to one is given the word of wisdom,
to another the word of knowledge, to another faith, to another working of miracles,
to another prophecy, to another different kinds of tongues,
to another the interpretation of tongues, yet all by the same Spirit,
the Spirit and power of Christ.
And it is evident that these gifts of tongues and miracles were not common
to all who had the Spirit of Christ in the primitive church,
but peculiar to some, as these questions of Paul imply: "`Are all apostles?
are all prophets?
are all teachers?
are all workers of miracles?
have all the gifts of healing?
do all speak with tongues?`"^
footnote:[1 Corinthians 12:29-30]
Indeed, this shows that all the ministers and members of
the church were not equally gifted in all these respects,
though they all had one and the same Spirit, from whom these gifts came.

When the chaplain perceived how tumultuous and rude
the company about me had been against me,
he questioned why I did not quiet or suppress them,
if I indeed had the same Spirit or power that the apostles had?
I answered him,
that the apostle Paul himself desired the church of the Thessalonians to pray
for him that the Lord would deliver him out of the hands of unreasonable men,
for not all have faith.
And he was sometimes in the hands of unreasonable men, and in tumults,
but the Lord delivered him out of their hands.

While we discoursed, my persecutors stood silent, as in a ring about us,
and heard us on the subjects before related.
The discourse held but a little while, I suppose about half an hour.
In the mean time, a soldier or trooper came up with his sword by his side,
and perceiving me to be the person persecuted and harassed by that rude company,
he came to me and said he would go along with me and guard me to my lodging.
Then, laying his hand upon his sword, he commanded the mob to stand off and make way.
So I was quietly rescued, and he went with me to my dear friend, Thomas Symonds`' house,
in the city.

I then saw it was the Lord who had put it in my mind to approach
the lady Hubbard`'s house when I was in danger from the tumult,
and also who had stirred up the mind of a stranger to rescue me out of the hands
of the unreasonable men who had surrounded and abused me with violence.
I have often been thankful to God for His merciful providence in that deliverance.
The soldier who took such care to rescue me afterward became a Friend,
and came into society with the people called Quakers,
wherein the Lord showed mercy to him.
His name was Robert Turner, of Lynn, in Norfolk.
I did not know that he was the man who rescued me until twenty-five years later,
when I was again a prisoner in Norwich castle, with many more Friends, in the year 1680.

In those days prisons and jails were made sanctuaries and
places of refuge to us from the fury of the tumultuous mob,
though we also met with poor treatment and hard usage in those places of severe confinement,
many times among notorious criminals.
But though I suffered harsh treatment both from tumults and imprisonments,
yet the Lord helped and sustained me by His divine power and goodness,
so that I was not weary of His service, nor did my spirit grow faint in suffering.
The grateful remembrance of His goodness,
and the living sense of His love to my soul in those days,
still lives and remains upon my spirit; praised be our God forever and evermore.

[.asterism]
'''

_George Whitehead continued to grow in the life and power of the gospel,
and though he was often imprisoned, persecuted, abused,
and even publicly whipped by the magistrates of England,
he clung to the Lord, and became a pillar and elder in the church of God,
constantly laboring for the advancement of truth and the welfare of the Society.
Though a humble grocer by trade, he was eminent for his profound spiritual understanding,
skill in debate, and ability to defend the truth with his pen.
Perhaps more than any other Friend, he was given great favor with kings and princes,
and on numerous occasions stood before King Charles II, James II,
and William III to plead the cause of his persecuted brethren.
And though he lived at the time of the hottest persecution,
and received a large share of the painful trials and cruel opposition
that were common in that day, he managed to outlive almost all of his contemporaries,
dying in 1723 at the age of 87 years._
