== Chapter V

It was observable, that notwithstanding all the persecutions,
reproaches and calumnies which we suffered under, and were multiplied against us,
especially against such of us as did bear a public
testimony for Christ Jesus and his truth,
and against the corruptions of the world; yet the truth gained ground and prevailed,
and our numbers and meetings increased in those days of the commonwealth, so termed.
The covetous, proud priests were sorely offended and disturbed,
that so many of their hearers and benefactors left them and resorted to our assemblies;
and though we that were public preachers of righteousness,
had some respite and ease from open persecution in the years 1658 and 1659,
after Richard Cromwell was set up for Protector, yet in his short time,
those priests ceased not their persecution,
by grossly misrepresenting and reproaching us in their pulpits and congregations,
to incense people against us,
and to deter and affright them what they could from hearing us.
But their pulpit noise against us made the indifferent,
unprejudiced people the more inquisitive and willing to
come to our assemblies to hear and see for themselves,
and not to be so credulous and partial as to take all evil
reports or reproaches upon trust against us,
our doctrine or ministry, as too many have unjustly and injuriously done,
to their own disgrace and shame.

When in some places I heard the priests thus busy in preaching against us,
a weighty and conscientious concern fell upon me, to send to several of them,
particularly to desire a meeting with them in their public places or parish churches,
fairly to discourse matters of difference, or what they could object,
before their hearers.
By this method I obtained several meetings with them in public,
whereof I may give some instances.
A+++.+++ D. 1659.

Some priests in the county of Kent being busy against us, especially in the east of Kent,
about Sandwich and those parts, and particularly Thomas Danson, priest at Sandwich,
agreed to have a public meeting with some of our friends,
which we being given to understand at London, Richard Hubberthorn,
Samuel Fisher and myself, agreed to meet those priests at Sandwich;
and took our journey into Kent near the beginning of summer.

On the day appointed, we were at Sandwich the former part of the day;
by that time we were come to their parish church, so called,
it grew so thronged with the concourse of people,
that it was something difficult to crowd in; however, they made way for us.
The priests got up near the pulpit, and we into a pew opposite to them.

Thomas Danson chiefly appeared to manage their controversy
against us and our Christian principles,
of the universal light of Christ in men; perfection being attainable in this life,
through the power of Christ within; justification through sanctification;
and about the Scriptures of truth and true use of them,
by the help of divine illumination, as truly owned and professed on our parts.

Richard Hubberthorn and I, for some time,
took our turns to answer the priests`' objections and questions,
according to plain Scripture, which I much endeavoured to hold the priests to,
and to use what plainness I could for the people`'s information and edification.

Whereupon Thomas Danson appeared very uneasy,
and seemed desirous to be at his logical way of syllogizing,
and endeavouring to put me by,
called upon Samuel Fisher to undertake the dispute in his logical manner of syllogisms,
calling out, "`Mr. Fisher, Mr. Fisher, pray do you undertake the dispute,
or answer me by syllogism.`"
Samuel being unwilling to take it upon him,
humbly signified to the people that the controversy being so well managed by his friends,
i+++.+++ e. Richard Hubberthorn and myself, he had rather be silent;
telling them that these his friends, meaning us two,
were heavier upon the priests`' shoulders than he could be,
disputing logically with them;
for that would tend to keep things more hidden from the people`'s understandings,
and thereby the priests would hide themselves the more out of their sight.

Howbeit, the priest making a noise, to prevent me calling out to Samuel Fisher,
he at last condescended to answer him in a logical way,
in mood and figure as they termed it, wherein they held the debate for a while,
and Samuel put the priest hard to it, about good works, namely;
the works of Christ in man being meritorious, or deserving justification and salvation;
not opposing the works or sufferings of Christ, without man, being meritorious.
Thus arguing, if evil works deserve damnation, then good works deserve justification;
still intending Christ`'s works: but evil works deserve damnation: ergo.

Hereupon the priests would needs compare him to Bellarmine, though very unjustly;
for Samuel only pleaded for such good works as were wrought by Christ,
and which he is author of, as deserving, in order to man`'s salvation and peace with God,
as knowing, "`That by grace through faith we are saved; not of ourselves,
it is the gift of God; not of works, lest any man should boast;
for we are his workmanship, created in Christ Jesus unto good works,
which God has ordained that we should walk in them.`"
And to be sure as saving grace is the gift of God,
so is true faith and God`'s work by Christ, and it is a good work too;
and also it is our duty and work to believe,
when by the grace of God it is given us to believe;
as when we receive that faith of the operation of God,
and are really in the obedience of faith.

Their chief objection was, that sanctification or holiness wrought in man by Christ,
is imperfect in this life, therefore not justifying.
Which is still to invalidate Christ`'s work, and lessen his dignity,
or worthiness and merits, who did not deserve to suffer, but to reign and rule.
He did not merit his sufferings, but his kingdom and glory therein;
and his merits redound to our justification and salvation,
both by his own obedience to the Father,
and also by his work of righteousness and sanctification, which he perfects in us,
if we "`continue in the faith grounded and settled.`"

The dispute between Samuel Fisher and the priest about good works,
and the priests`' undue reflections thereupon held for sometime longer.
In the meanwhile, by the crowd and pressure of the people the pews were much broken,
and great damage done among their seats;
insomuch that the next day a meeting was appointed in their school house,
a pretty large room, where they could not do such damage, if any.

In the school house the priests got together again, Thomas Danson being foreman still.
We entered upon the same subjects which we had in discourse the day before,
about Christ and his light, and work of grace within, or in men,
in order to their justification and salvation,
who truly believe and obey him in his light given them.

While I was bearing my testimony to our Lord Jesus Christ,
in order to open some weighty and essential matters relating to salvation,
according to the holy Scriptures, that I might clear my conscience to the people,
the priests in a short time appeared impatient to hear me out,
and occasioned a great confused noise among their rude hearers,
insomuch that I was constrained to raise my voice very loud,
to be heard for a little time,
greatly desiring I might have opportunity fairly to clear my conscience;
but the opposite party were not so civil, neither did the priests quiet their hearers,
as in point of civility they ought to have done.

But I have often observed in disputes with many of the priests,
when they were put closely to it to keep to the point under debate,
and they have been pinched,
they have used that trick to raise a confused noise and clamour among their hearers,
to prevent the truth from being heard, and to hide themselves from being detected;
which treatment is but a poor piece of artifice and school craft,
as persecutors use to send soldiers with their drums into our religious assemblies,
therewith to make a hideous noise, that we might not be heard by the people,
either in preaching the gospel, or in public and fervent prayer to Almighty God,
in the name and spirit of his dear Son Jesus Christ.
But, however, we knew that he has often heard us to our comfort and great encouragement,
when opposed and encompassed by the greatest noises
and tumults of our adversaries and persecutors;
they could never stop the ear of the Almighty,
which is always open to the prayers of the righteous.
But to return to the account of our treatment at the said school house.

While the rude company made a noise to prevent my being heard,
our friend Samuel Fisher endeavoured to procure silence, that he might be heard,
using the words of Job, "`Permit me that I may speak; and after that I have spoken,
mock on.`"
Sometimes he and the rest of us obtained some respites of silence and were heard,
being sensible of the Lord`'s power and truth that was with us,
and our sincere endeavours being for the discovery and advancement thereof,
so that we were made the more easy and comforted in our spirits; though our adversaries,
the priests, were left uneasy, retaining their prejudice and enmity against us,
and our testimony for the truth in life and power.
Thomas Danson afterwards published an envious book to reproach us, falsely styled,
"`The Quakers`' folly made manifest to all men;`" whereby he gave
occasion to expose his own and his brethren`'s ignorance and envy,
as they are clearly manifest and detected in our answers; one entitled,
"`The voice of wisdom uttered against antichrist`'s folly,`" etc.
By George Whitehead, printed A. D. 1659;
and more especially in Samuel Fisher`'s ample answer
to Thomas Danson and others of his brethren,
entitled, Rusticus ad Academicos, etc., first printed A. D. 1660,
unto which I never heard of any answer or reply made or attempted by any of them.

Having notice that Henry Johnson, priest of Emneth in Norfolk,
had preached or exclaimed publicly against the people called Quakers and their principles,
I wrote a few lines, which I sent him by our friend Richard Sanders,
for a public meeting with him in their parish church, so called, before his auditors,
that we might have a fair dispute or examination
of those points or matters wherein we differed.
To this he consented in a paper which he returned to me,
to which he annexed seventeen questions to discourse upon, and which he supposed might,
with my answers thereto,
contain our opinion and persuasion--as his terms were--and to which he expected my answer,
yes or no, to each question respectively, at the time of our public discourse.
Because we had not opportunity to discourse,
or examine all his questions at that one meeting which we had,
and he having enough of dispute at that time,
I think convenient first to insert all his questions with particular answers,
and then to give some account of the chief parts of our discourse.
The questions and answers follow.

[.discourse-part]
1+++.+++ Whether Jesus Christ has a body glorified in the heavens,
distant and distinct from the bodies of his saints here below?

[.discourse-part]
_Answer._
Yes, as a glorified body is distinct from natural or earthly bodies,
and heaven from the earth.

[.discourse-part]
2+++.+++ Whether the blood that Jesus Christ shed at Jerusalem,
is the blood that believers are justified by?
or whether he dies in men for their justification '`?

[.discourse-part]
_Answer._
Both sanctification, forgiveness of sins, cleansing from sin and justification,
are sometimes ascribed to the blood of Christ,
and to the spirit of our God and our Lord Jesus Christ, which effects,
works and manifests the same in all true believers.

But here are two questions put for one;
the first appears not a scriptural or proper question.
Where does the Scripture use those words: "`the blood that Jesus Christ shed?`"
Seeing it was by wicked hands he was put to death, and his blood shed upon the cross?
Yet as the blood of Jesus Christ is put for, or represents his life which he laid down,
and even the offering and sacrifice of himself at Jerusalem,
that was a most acceptable sacrifice and of a sweet smelling savour to God, for mankind,
respecting his great dignity and obedience,
who humbled himself even to the death of the cross,
and gave himself a ransom for all men, for a testimony in due time.
And his sacrifice, mediation and intercession,
has opened a door of mercy for mankind to enter in at,
through true repentance toward God, and faith toward our Lord Jesus Christ,
which are wrought in man, that obeys his call thereto, only by his grace and good spirit,
unto sanctification and justification, in the name and power of our Lord Jesus Christ,
who of God is made unto us wisdom, righteousness, sanctification and redemption,
God`'s great love toward mankind was manifest in his dear Son Jesus Christ;
"`And God was in Christ, reconciling the world to himself,
not imputing their trespasses unto them.`"

The latter question of the second, is groundless and perverse.
"`We know neither Scripture nor minister among us
that asserts Christ`'s dying in men for their justification,
but that once he died, i. e. for our sins, and rose again for our justification,
and that he ever lives to make intercession, and death has no more dominion over him.
Christ Jesus lives and reigns forever in the power and glory of the Father,
although some are said to crucify to themselves the Lord of life afresh,
and to tread under foot the Son of God,
which cannot be taken properly in a literal sense; but by their contempt of truth,
and doing despite to his spirit of grace, as some malicious apostates have done,
not to their justification, but condemnation.

What any of us, or among us,
have spoken or written of the seed or word which the Son of man, Jesus Christ,
sows in men`'s hearts; and of the same being oppressed, or suffering in some,
or as being choked with worldly cares and the love of riches in others,
these and many such like expressions may have been used,
according to the parables and similitudes which Christ Jesus himself spoke,
relating to the kingdom of heaven, the Word or Seed of life and grace,
sown by him in men`'s hearts; and likewise of grieving,
vexing and quenching his spirit in them, by their disobedience; and yet by all these,
never to intend or mean,
that Christ himself properly dies in men for their justification,
although his spirit be both grieved and quenched in many;
and many do lose the true sense of his living Word in themselves,
by allowing their soul`'s enemy to draw out their minds from that seed, that word,
that light, that spirit of our Lord Jesus Christ in them, which, in itself,
in its own being, never dies.
The immortal Seed, the immortal Word, is of an immortal Being,
though many be dead thereunto, in their trespasses and sins.

[.discourse-part]
3+++.+++ Whether this individual body of ours shall be raised at the last day?

[.discourse-part]
_Answer._
This appears an unscriptural, as well as an unlearned and dubious question,
if not anti-scriptural.
If he means this our natural, numerical body of flesh, blood and bones,
the testimony of the apostle Paul may both answer and refute his question,
the resurrection body being not natural, but spiritual, not flesh and blood,
for they cannot inherit the kingdom of God.
1 Cor.
xv.

And how is this earthly body of ours individual,
if it may be divided and parted into pieces and small particles, or dissolved into dust,
or in the earth, or in the sea, or in the fire into smoke or air.
Nevertheless God gives a body as it pleases him, and to every seed his own body; yes,
to every soul its own proper body.

[.discourse-part]
4+++.+++ Whether any saints before death are sinless?

[.discourse-part]
_Answer._
Yes, those saints whom Christ sanctifies and cleanses from all sin,
as he does all true and constant saints.

[.discourse-part]
5+++.+++ Whether the Father, Son and Holy Spirit be three distinct persons or substances`'?

[.discourse-part]
_Answer._
We do not find them so termed, i. e. three distinct persons, in holy Scripture,
but rather three witnesses, or three that bear witness in heaven, the Father, the Word,
and Holy Spirit, and these three are one.
1 John v.

[.discourse-part]
6+++.+++ Whether water baptism be a gospel ordinance?

[.discourse-part]
_Answer._
No, it was typical, and rather legal, as it was John Baptist`'s ministration,
than a gospel ordinance, though sometimes condescended unto in the church`'s infancy.

But if by water baptism be meant sprinkling infants, that is no real baptism,
nor gospel ordinance, but rather rantism, and a tradition of the Romish church,
than any gospel ordinance.

[.discourse-part]
7+++.+++ Whether the Scriptures be the rule of your faith and life, or the Spirit?

[.discourse-part]
_Answer._
We do not find that the Scriptures call themselves the rule of faith and life,
but refer us to the Holy Spirit to be our guide into all truth;
and they testifying of Christ, as he is the way to the Father, even the Way, the Truth,
and the Life;
we do therefore truly esteem the holy Scriptures as a subordinate rule or directory,
directing us to Him who is the principal or chief guide, way, or rule of faith and life;
and we do sincerely own that the holy Scriptures contain many divine rules,
precepts and doctrines, relating to our most holy faith and life.

[.discourse-part]
8+++.+++ Whether children of darkness have the light of Christ within them?

[.discourse-part]
_Answer._
They have some degree of light from Christ in them, though it shines in darkness,
as a light shining in a dark place, otherwise they could not come,
nor be translated out of darkness; they must believe in the light,
in order to become children of the light; and therefore Christ exhorted,
"`Believe in the light, that you may be children of the light.`"

[.discourse-part]
9+++.+++ Whether that act be sin in a saint, which is a sin in a wicked man?

[.discourse-part]
_Answer._
The act of sin and every transgression of the law of Christ, is sin in fact,
in whomsoever it is; but the saints, or sanctified in Christ, who dwell in him,
do not allow or permit sin to dwell in them, nor themselves to commit it;
"`he that abides in Christ sins not.`"

[.discourse-part]
10+++.+++ Whether there be any moral difference in days under the gospel?
Answer.
No, not as was under the law in the observation of sabbaths,
which were a shadow or sign to Israel, and are ended in Christ,
in whom is the faithful soul`'s everlasting rest or sabbath.
Yet there is,
and may be a religious or an occasional difference made in days under the gospel,
as where a day is or may be regarded unto the Lord; especially in religious assemblies,
and particularly as was and is practised on the first-day of the week among Christians.

The apostle Paul was tender in this case,
about one man entertaining and regarding one day above another,
and another man`'s esteeming every day alike, and about meats,
so as not to judge one another; "`But let every man, said he,
be fully persuaded in his own mind;`" yet condemns
the Jewish and superstitious observation of days,
meats and drinks, etc.

[.discourse-part]
11+++.+++ Whether it be a duty for Christians to celebrate
the Lord`'s supper with bread and wine?

[.discourse-part]
_Answer._
In this question,
the man begs the question--imposing and taking for granted their bread and wine,
as ministered by the priest,
to be the Lord`'s supper--which I must deny until proved by Scripture.
For that which was properly the Lord`'s supper,
was when he and his disciples eat the passover; Luke 22:15.
There is no necessity now for Christians to celebrate that supper,
for that was both celebrated and fulfilled by Christ himself.
And the passover and outward bread and wine, or cup,
were typical and shadows fulfilled by Christ Jesus, and in him,
unto his true spiritual believers and followers,
who are spiritually partakers of Christ the substance,
being come to receive him to sup with them, and they with him; Rev. 3.

[.discourse-part]
12+++.+++ Whether an outward mission, by imposition of hands, with fasting and prayer,
by men so ordained themselves to the work of the ministry, be according to gospel order?

[.discourse-part]
_Answer._
An outward mission by these, without an inward divine call,
is not sufficient to authorize anyone to be Christ`'s minister or ambassador;
neither have they any divine authority to commissionate
ministers by their imposition of hands,
fasting or prayer,
who themselves have no divine call nor authority given them by Christ thereunto;
but who rather conclude that his immediate call,
ministry and prophecy are long since ceased.

[.discourse-part]
13+++.+++ Whether the Scriptures be the ordinary means to beget faith in men`'s hearts?

[.discourse-part]
_Answer._
No; 1. Not without the help of the holy Spirit and light thereof,
to give the true understanding of them.
2+++.+++ Not the ordinary means to beget faith in men`'s
hearts in a limited or universal sense,
as if none might believe without them, for God may make, and has made,
use of other means than the Scriptures, as by preaching the gospel in spirit and power.
3+++.+++ By his works in the creation.
4+++.+++ Chiefly by the word of faith in men`'s hearts,
which is the efficient cause of begetting and working faith in them,
being the faith of the operation of God and our Lord Jesus Christ,
the author and finisher of our faith.
5+++.+++ Nevertheless the holy Scriptures being opened and applied by the Spirit,
are often made instrumental to beget faith in many men`'s hearts.

[.discourse-part]
14+++.+++ Whether the Scriptures need any interpretation and reconciliation?

[.discourse-part]
_Answer._
Yes, to the first part; many Scriptures are mysterious, allegorical,
parabolical and prophetical,
and need to be interpreted and opened by the Spirit from which they came,
but not by man`'s human or fleshly wisdom, or private interpretation;
for the natural man perceives not, nor can he know the things of the Spirit of God,
they being spiritually discerned.
Neither need the holy Scriptures reconciliation in themselves; for they are harmonious,
and do agree, and the Scripture cannot be broken.

[.discourse-part]
15+++.+++ Whether the divine nature of Jesus Christ be united to the bodies of believers,
as it was to his own personal body in Judea?

[.discourse-part]
_Answer._
No; although true believers who are Christ`'s members, are spiritually united unto him,
and members of his body, and made partakers of his divine nature;
yet not in the same fulness as it is in Him who is the Head,
in whom it has pleased the Father that all fulness should dwell.

[.discourse-part]
16+++.+++ Whether the pope of Rome be antichrist, and papacy anti-christian?

[.discourse-part]
_Answer._
Yes, to both.

[.discourse-part]
17+++.+++ Whether George Whitehead will take the oath of abjuration, and renounce the pope?

[.discourse-part]
_Answer._
George Whitehead has not a renunciation or denial of the pope or popery now to make,
having never owned either, but always utterly denied and disowned both:
although George Whitehead may not swear to such renunciation,
because for conscience sake he may not swear at all; either by that oath of abjuration,
i+++.+++ e. to renounce the pope, etc., or by any other oath,
lest he should fall into condemnation; Matt. 5. James 5.

Thus I have conscientiously answered the foregoing questions, some of them more largely,
for the information of others, than they deserved,
and more particularly than we could have time then to dispute,
for we could go through but a few of them;
and Henry Johnson had enough of disputing upon those which we did discourse.

[.offset]
A brief account of our discourse on some of the foregoing questions follows.

Being met in their parish church, as it is called, the 2nd day of the first month, 1659,
and a great auditory present, among which were many of our friends called Quakers,
the said Henry Johnson being minded to enter upon his interrogations or questions,
before cited and answered, I gave a direct answer to his first question;
For the glorious body of Christ is in heaven,
according to the answer herein given thereunto.

But he not getting any advantage against us by my direct and plain answer,
being according to Scripture, took occasion to accuse our friend Richard Sanders,
with affirming that Christ has no body; when the contrary was manifestly proved, namely,
that Richard Sanders confessed that Christ has a glorious body,
i+++.+++ e. peculiar and proper to Christ himself, according to Scripture language;
but he questioned Henry Johnson`'s words about Christ`'s
body in heaven being a human body,
consisting of flesh and bones.
It was the word human, as applied to Christ`'s glorious body in heaven,
that was most questioned by Richard Sanders and others,
as not being a Scripture term in this case; and though it be applied to mankind,
yet it is made relative to man; in relation to the earthy part,
as humanus relates to humus, the ground or earth, out of which man, the first Adam,
was taken and formed.
And therefore that term was thought too low to ascribe to the second Adam,
or his glorious body, who is the Lord from heaven; not an earthly man,
but a heavenly man, both morally and essentially.
Howbeit, could we have had Scripture proof to ascribe human to the heavenly man,
Christ Jesus, in his glorified state, it had decided the question;
but that we could not have from our antagonist when it was desired,
though he promised to prove it by Scripture.
But instead thereof,
he rather imposed his own assertion and repetition of the same thing or term in question,
instead of Scripture proof.
And when that course would not do, then he fell to his logic with his syllogisms.
Using such expressions as these:
Christ is in heaven in our human nature he took upon him, of our flesh and blood, etc.

[.discourse-part]
_Question._
But is he in heaven now in the self same manner as
he was on earth in the days of his flesh,
when he took upon him the form of a servant, and was made like unto us in ail things,
sin only excepted?

This question he added for further consideration.
I suppose no real Christian will presume to affirm,
that Christ as he is now in heaven and glory, is still like unto us in all things,
both in his glorious body, matter, manner, and form thereof, sin only excepted.
For if any should thus affirm, it would from there follow,
that they might as well say we are now so like unto
Christ Jesus in his glorified state in heaven,
and our bodies now on earth, are so like unto his glorious body in heaven,
that they need not be changed or fashioned like unto his glorious body; Phil. 3:21;
for that they are already, if he be still like unto us in all things, sin only excepted;
Heb. 2:17, and iv.
15.

Surely no true Christian here on earth can entertain any such high thoughts of himself,
and of his low earthy body, as that he is so very like Christ and his glorious body.
But rather let us all be humble and self-denying, and little in our own eyes,
and exalt Christ above ourselves,
and let him have the glory and preeminence in all things; to whom be glory and dominion,
forever and ever.
And let us all who profess Christ and Christianity,
labour to be truly conformable to his example of humility,
innocency and truth when on earth, that we may be with him, where he is,
and see his glory in heaven.

I have somewhat enlarged and argued here upon this point,
more than was required in our said discourse, or was then necessary:
for the first question was not much insisted on by either side,
being fairly answered at first;
although the parson was willing to show us some of his skill in logic,
when he argued thus: Argument.
If Christ had a human body of flesh and bones when
he was upon earth then he has a human body in heaven,
consisting of flesh and bones; but Christ had such a body upon earth, ergo.

The first proposition, or major part of the argument being general,
is liable to just exception; taking it for granted,
that whatever Christ had when he was upon earth,
he must needs have the same now in heaven; and then he must have natural food, meat,
drink and clothing in heaven, such as he had upon earth;
and sometimes suffer hunger in heaven as he did upon earth;
but these we have no reason to believe concerning him, now in his glorified condition.
He is far above all these human necessities, weaknesses and suffering state.
And this our opposer`'s logic aforesaid, being still short of Scripture proof,
was the less taken notice of.

Upon his fourth question he showed his opinion and doctrine, which was.
That none of the saints are freed from sin while upon earth;
yet that they were freed from the guilt of sin.

[.discourse-part]
Answer.
This doctrine is expressly contrary to the apostle`'s doctrine;
"`But now being made free from sin, and become servants to God,
you have your fruit unto holiness, and the end everlasting life.`"
And it is very inconsistent to teach that men may be free from the guilt of sin,
when they either continue in sin or do commit sin;
or to tell them they cannot be free from sin during life, and yet not guilty of sinning;
which is no better doctrine than to tell them, a man that is addicted to stealing,
or often steals his neighbour`'s goods is not guilty of theft, or is no thief,
though he actually steals.
What miserable stuff were this?
And what untempered mortar is it, thus to daub and soothe up sinners in their sins,
and to strengthen the hands of evil doers--as false prophets
did--that they may not repent and forsake their sins?

The priest also, in opposition to my answer for freedom from sin,
said that the believers mentioned in Heb. 12:22-23, the being come unto mount Zion,
etc., and to the general assembly and church of the first born, etc.,
and to the spirits of just men made perfect, was not while upon earth,
but in heaven and at the resurrection.
As if Paul wrote to the believing Hebrews when they were dead, or not upon earth,
but after their departure into heaven; but herein the priest was out,
and beside the text.

And further, to oppose the doctrine of perfection, of sanctification,
or freedom from sin in this life, the priest objected,
that our preaching that men may attain to perfection before death,
renders the mediatorship of Christ useless.
But in this he was mistaken also; for Christ Jesus, by his mediation and intercession,
has in great love and mercy undertaken to be our advocate with the Father,
to reconcile us to God; and to obtain mercy, reconciliation and peace for mankind,
he made intercession as well as suffered for the transgressors;
land also he appears in the presence of God for us, making intercession for the saints,
according to the will of God, and that is for their preservation and help,
that they may be preserved and kept from the evil of the world; and also if any man sin,
or be overtaken with a fault, and not willfully,
we have this our advocate with the Father, "`even Jesus Christ the righteous.`"
And as he said unto Peter, "`I have prayed for you, that your faith fail not.`"
Therefore that true believers in Christ may attain
to perfect sanctification and freedom from sin,
by his power, help and assistance, even in this life,
is so far from rendering his mediatorship useless, that it renders the same very useful,
for their safety and help, against the temptations of Satan and sin.

The eighth question was chiefly insisted upon, and controverted about the light within,
or in man, upon which question Henry Johnson affirmed, that the children of darkness,
or wicked men, as drunkards, swearers, etc., have no spiritual light in them;
quoting Isa. 8:20.

In answer whereunto, I insisted on John 1:9, That was the true light,
which enlightens every man that comes into the world;
which is spoken and predicated of Christ the eternal Word, the Son of God,
as being that true light.
And also verse 4; In him was life, and the life was the light of men;
which life and light therefore is not natural, but spiritual and divine.
It was the life that was in him, which was the light of men.

To which the priest replied, that Christ enlightens every man, as in John 1:9;
but it is not with the light of grace, but with a natural light:
and that the life of Christ, or which was in him, which is the light of men,
is not the light of grace, but a natural light.

Another priest then present to help him, in like manner imposed his opinion, which was,
that the wicked have the light of conscience, but not any saving,
spiritual light in them.
Thus far both these ministers, then esteemed priests,
imposed their own opinions against the light,
and contrary to holy Scripture testimony also; and instead of Scripture proof,
that the light in every man is but natural, a light of conscience, and not spiritual,
nor the light of grace, etc.
The said Henry Johnson again fell to his logic, and thus syllogized from Isa. 8:20:
Argument.
If there be some men or persons in whom there is no light,
then there are some men who have no spiritual light in them;
but there are some men in whom there is no light, ergo.

I inverted his argument against himself, thus;
If there be some men in whom there is no light,
then there are some men in whom there is no natural light;
which is a plain contradiction to what he has asserted, namely,
that there is a natural light in every man; and his advocate, the other priest,
confessing that the wicked have the light of conscience in them.
Therefore by their own confession, there is some light in every man;
so that the argument drawn from having no light in them,
falls to the ground by their contrary confession.
And as to that in Isa. 8:20; To the law and to the testimony;
if they speak not according to this word, it is because there is no light in them.
This appears not according to the Hebrew text,
as I told them they might see in the margin of many Bibles; Heb.
No morning, instead of No light;
wherein there is a manifest difference between no light and no morning;
and they would not affirm that there is no light before morning,
or in the night time in the creation: and to apply the matter to a spiritual sense,
respecting the divine Word or Light in man,
the same appears and shines gradually until the darkness be dispelled and past.
The same Word shines as a light in a dark place, even in men`'s hearts,
until the day dawn and the day star arise in them.
It is the just man`'s path, who obeys and walks in the light,
and shines more and more until the perfect day.
David esteemed this divine Word, the Light, to be as a lantern to his feet,
and a light unto his path; and surely the use of a lantern is before the morning,
chiefly in the night time.

After I had fairly evinced the priest`'s contradiction, from his logic or argument,
before cited, and insisted upon the Hebrew note on Isa. 8:20, No morning, etc.,
the said Henry Johnson and his assistant soon ceased disputing and withdrew,
the assembly continuing peaceable, and generally serious and attentive to the conclusion;
insomuch that I had a good opportunity to demonstrate the truth among them,
the Lord standing by me and assisting me with his divine power and presence,
and his gospel testimony; glory to his worthy and excellent name forever.
Thus we, i. e. I and our friends, and the assembly quietly parted,
without any reflection or words of contempt against us, or any of us, or our principles,
that I can remember.

Although those of the Presbyterian or Independent
priesthood were gotten so high in those days,
especially the parish priests,
that they would scarcely allow any of us to bear testimony for the truth,
or to preach the gospel of Christ, according to our gifts, in their public assemblies,
or places termed parish churches,
without either imprisonment or being violently haled or pushed out of doors,
as we have been often so uncivilly treated, and hardly used through their instigations,
and incensing people against us, though we have patiently heard them out,
and stayed until they had ended sermon and prayer; yet some of them,
even of their priests, have many times come into our meetings,
and without cause made opposition and disturbance,
as persons envying our liberty of meeting religiously together to worship God,
according to our conscientious persuasions,
wherein they did not by us as they would be done by themselves.
Howbeit we would not allow any violence to be done to any of them in our assemblies,
but civilly treated them, and soberly answered their objections,
and with meekness endeavoured to inform their understandings
and rectify their mistakes concerning us and our principles;
finding that many of them were ignorant thereof,
and had taken up reproaches against us from reports of others,
which were false and malicious.

I had a meeting at Stephen Hart`'s, by the palace yard at Westminster,
which was thronged with more than the room could well contain,
of our friends and other people of several sorts and ranks.
The meeting continued quiet until near the end,
and the people appeared generally well satisfied with the
clear and plain testimony the Lord enabled me to bear.

At last a priest, one Thomas Smith of Cambridge, keeper of the University Library,
stood up and made opposition, with a charge against the Quakers, as being heretics,
such as bring in damnable heresies, even denying the Lord that bought them;
applying and perverting that Scripture, 2 Pet. 2:1.
But he could not produce any proof,
or colour of proof against the Quakers, or any of us,
of any such heresy or denial of the Lord that bought
us--who gave himself a ransom for us,
and for all men--either by our doctrine or conduct.
Contrariwise we were,
and still are deeply obliged to confess him both in doctrine and practice,
for his great love in giving himself for us, to redeem us from all iniquity,
and for his light and grace given us for that end,
that we might receive and experience that redemption through his blood,
which he obtained for us: therefore, blessed be his glorious name,
we are far from denying the Lord that bought us.

The said priest being more confident and loud in his charge than proof,
and there being a denial of Christ the Lord in practice, as well as in doctrine,
I turned the same Scripture, 2 Pet.
ii, upon the priest, which he brought against me and my friends called Quakers,
reading to the people several verses of the same Scripture,
to show what teachers they were who denied the Lord that bought them,
whose ways were pernicious, verse 2;
and many shall follow their pernicious ways by reason
of whom the way of truth shall be evil spoken of;
verse 3, And through covetousness shall they with feigned words make merchandise of you:
whose judgment now of a long time lingers not, and their damnation slumbers not.
And verse 14, Having eyes full of adultery, and that cannot cease from sin;
beguiling unstable souls: a heart they have exercised with covetous practices;
cursed children; verse 15, Which have forsaken the right way, and are gone astray,
following the way of Balaam the son of Bosor, who loved the wages of unrighteousness.

Upon my urging these Scriptures, 2 Pet.
ii. against the covetous priests`' practices, which are against Christ and his doctrine,
and consequently a denying of him; as also against their doctrine, whereby they teach,
that no man can be freed from sin in this life,
so that they cannot cease from sin while they believe
they cannot or may not be freed from it in this life;
hereby they also deny the Lord that bought them,
in their denying the end and purpose of his purchasing or redeeming mankind,
and of his being made manifest to destroy the works of the devil,
and to redeem us from all iniquity, for which end he gave himself for us.
See 1 John iii.
Titus ii.

I say, upon my urging the Scriptures cited before,
against the covetous practices of priests, and their not ceasing from sin,
but rather arguing for it in this life,
our dispute at that time soon came to an end,--the priest had enough of it,
for his unjustly charging the Quakers with damnable heresies;
even as unjustly as the persecuting Papists would brand the martyrs with
being heretics when they were minded to murder or destroy them.
But the controversy did not end here; the said library keeper some time after,
had a mind to try his strength and skill further against us.

The same summer, A. D. 1659,
the Lord laid it upon me to visit Friends`' meetings
in Cambridgeshire and the parts adjacent;
at Cambridge I had several meetings, both on first and other days, where,
to one meeting on a week-day, the library keeper came and made some opposition,
his design still being to prove me a heretic,
but with no better success than he had before at Westminster.
He made poor work of it; and yet seemed willing to have another public meeting,
on purpose to dispute the point with me, which I readily granted,
and he soon withdrew out of our meeting for that time.

I and another Friend went to the mayor of Cambridge,
to desire liberty to have our meeting for the dispute at the guild-hall,
suspecting Friends`' meetinghouse would not contain the people.
The mayor being a moderate man, and his wife a friend of ours,
after some consideration signified to us, that he dared not let us have the guild-hall,
for fear the scholars would do some mischief when
a great number of them were gathered together;
but he told us, that if we met at our own meetinghouse,
which was over against Sidney college, he would send his officers to keep the peace,
or to see the peace kept; which accordingly he did.

On the day of our meeting to dispute, came our learned antagonist, Thomas Smith,
attended with a great company of scholars of several degrees,
bachelors and masters of art, etc.
He again resumed his old charge against us of being heretics,
having had time to study some new arguments for proof,
and then proceeded with his logic and syllogisms,
and I did not at all go about to prevent his essay that way, being willing to watch him,
and see what he would make of it; and thus he attempted it:
He that is a Papist is a heretic: But you are Papists, i. e. the Quakers.
Ergo, you are heretics.

[.discourse-part]
_G+++.+++ Whitehead:_ I deny the minor, or second part of the argument; that is,
I deny that we are Papists.

[.discourse-part]
_Priest:_ He that refuses to take the oath of abjuration is a Papist:
but you refuse to lake the oath of abjuration, ergo, you are Papists.

[.discourse-part]
_G+++.+++ Whitehead:_ I except against the major, or first part of the argument,
and the consequence deduced therefrom, for the following reasons:
Christ has commanded us, Not to swear at all, etc. Matt. 5:34.
And his apostle James likewise forbids all swearing; saying,
"`Above all things, my brethren, swear not, neither by heaven, neither by earth,
neither by any other oath: but let your yes be yes; and your no, no;
lest you fall into condemnation.`"

Now suppose the apostle James were here present,
to maintain this doctrine against all swearing, or taking any oath,
he must refuse the oath of abjuration, because it is an oath;
he must obey the doctrine of his Lord and Master, Jesus Christ.
Then by this person`'s way of arguing against me and the Quakers,
he would be charged with being a Papist and heretic; for by refusing to swear at all,
or to take any oath, he must refuse to take the oath of abjuration.
And thus the argument consequently unjustly charges
or reflects upon Christ and his holy apostles;
to which the priest could make no reply,
to clear himself from the absurdity and fallacy of his argument and false charge.

For their doctrine of the trinity, to prove three separate persons in the deity,
about which he questioned us, he argued thus: That when Christ was baptized, one person,
i+++.+++ e. God, was in heaven; another person, i. e. his Son, was in the water,
and the Holy Spirit descending upon him like a dove, ergo, etc.
Another argument was.
If they are three he`'s, then they are three persons; but they are three he`'s, ergo.
What rare logic was this!
What absurdities may not be drawn from this logic?
But when he failed in his arguments so that he was detected,
some of the scholars who stood by would say to him,
"`Take that off;`" by which I understood they meant, drop that argument, or let it fall,
or evade it, and slide off to some other point or argument, for so he did.
And this I have found to be the shift and subterfuge of many adversaries,
to evade a fair disquisition of the question or point in hand;
insomuch as I have often called out upon them, to keep to the point in hand,
and not to evade nor use shifting.

This is a brief account of the discourse at that meeting,
though much short of what passed; the matter in question,
and several points being answered more fully in print, in two books, the one entitled.
Truth defending the Quakers and their principles;
wherein fifty-five queries or questions, put forth by the said Thomas Smith,
who was esteemed the author, are answered.
The truth of it is, he appeared so ignorant of our principles,
that it seemed necessary for him to make such large inquiry into them,
more for his own better information, than for our confutation.

The other book of ours in reply to him, is entitled.
The Key of Knowledge, not found in the University Library of Cambridge.
The said Thomas Smith pretended to great learning or reading in some oriental tongues,
and as I remember, I have seen in print some boast of that kind.

Our dispute was managed in such moderation,
that the meeting was continued pretty quiet to the end,
the scholars being generally civil.
And we being sensible the truth gained ground at that meeting,
we came off very easy and comforted in our spirits; i. e. George Fox,
junior and the rest of Friends and friendly people,
who were present with me at that time.

In the town of Cambridge, I had in those days many good meetings,
and effectual service for the truth, and the meetings generally were peaceable,
while I was concerned in them,
the scholars being more civil towards me than we could expect,
for many of them would stand to hear the truth quietly, with great attention,
and I often felt the Lord`'s power over their spirits in our meetings.
Some time after I left them, I heard that Friends met with disturbance,
and some of them with hard usage at their meetings, from the scholars,
which I was sorry to hear, it being partly occasioned by some striving with them,
not in the wisdom of God, as I understood,`' by several circumstances related by Friends,
whereby it plainly appeared, that the devil, or evil spirit,
might be more easily raised and let loose than subdued or bound.

I have observed, that when I and other public brethren have, in a meeting in that place,
met with opposition,
if it was by any person of understanding or learning that would deport himself soberly,
we could have some fair and quiet discourse, tending to information and edification,
and the scholars present would demean themselves with attention,
as persons willing to receive instruction.
But if a vain, irreligious person came into a meeting to scoff, deride, or laugh at us,
or show contempt against our Christian testimony, such a one,
as a base and wicked instrument of Satan,
would raise levity or laughter in some of the loose scholars, to their hurt and shame.

One time an old priest, who was naturally blind, as they said he had been from a child,
and some company with him, came into our meeting, and behaved themselves pretty civilly;
the priest seemed to be a learned person,
and would undertake to question me about the trinity, as to my belief therein.
I answered him in terms of holy Scriptures: "`That I really own, and believe the Father,
the Son, and the Holy Spirit, are the three which bear record in heaven; the Father,
the Word, and the Holy Spirit;
and these three are one,`" according to the doctrine of John the evangelist; 1 John 5:7.

But this answer would not please the priest, and I would give him no other.
I would not enter into a dispute about three distinct persons,
which the priest would have drawn me into;
I not being free in point of conscience to give other
names or appellations to the one true God,
than what are given in holy Scripture.
I did not esteem it safe to use unscriptural, or metaphysical, or school terms,
in such a sacred point as that of the deity,
but to keep to plain Scripture terms and language.

Whereupon the priest being disappointed of an answer in his own terms, replied,
"`You say there are three; three what?`"
said he.
I answered again.
The Father, the Word, and the Holy Spirit.
The priest still unsatisfied, repeats his question again; "`Three what?`"
quoth he.
I answered again.
What the Scripture terms them, namely: the Father, the Word, and the Holy Spirit;
and these three are one, as before.
Nothing would satisfy the priest but.
Three persons.
If to his reiterated question, "`Three what?`"
I had answered witnesses, that would not have done,
though more Scriptural than the other; for God is witness, Christ the faithful witness;
his Spirit bears witness, being the three that bear record, or witness, in heaven,
the Father, the Word, and Holy Spirit.
This was an answer safe and sufficient, from which I therefore would not be moved,
but insisted upon in Scripture terms;
whereupon that dispute quickly and quietly broke off.

There was a people termed Manifestarians, Universalists, or Free-willers,
and Mooreans by some, at Lynn Regis, in the county of Norfolk,
and some other places adjacent, about the Fenn country.
They had that name, Mooreans, given them from one Thomas Moor,
their chief minister or leader, who proselyted and gathered a congregation to himself,
and ruled over them while they were under his ministry.
Among them I have been very credibly informed,
there were many persons who had living desires and
stirrings in them after the Lord and his power,
insomuch that some of them were drawn at times to meet together somewhat privately,
to wait upon the Lord God, to feel his power and spirit to move in them,
to pray and to utter words for edification,
and exciting one another to an inward and spiritual worship or devotion toward God.
Of this some of them accordingly came, in measure,
to have some touches and sense inwardly, which brought fear and trembling over them;
and Thomas Moor coming to take notice thereof,
endeavoured to discourage and quench those motions
and effects of the Spirit which appeared in them,
as a very tender-hearted, ancient Friend, who had been one of them, gave me a large,
substantial, as well as circumstantial account, from certain knowledge and observation.
Upon being thus discouraged, and their good motions and desires opposed,
some turned into a loose spirit and corrupt notions;
from which several were reclaimed afterward,
when truth was demonstrated to them in the spirit and power of Christ,
and their minds thereby turned to his light in them,
to wait for an inward sense of his power.

After some time, Thomas Moor, Jr., son of the said Thomas Moor,
became a preacher among them; also John Horn,
who had acquired some more school craft and cunning than the other two.
He was set up and promoted as a parish priest at Lynn,
but as destitute of the knowledge of the light and mystery of Christ, and of his power,
as the other; for they are all joined in bitter opposition thereto,
as held forth by our friends,
especially when several deserted them and left their communion.
John Horn became very invidious, and made it much of his business with his brethren,
the two Thomas Moors, to revile, asperse, and calumniate the people called Quakers,
by words and writings.

They made a great noise against us in and about the town of Lynn,
to stir up enmity in the people against the Quakers, rendering them deceivers,
antichrists, heretics, accursed, etc.
And when some of us have been at Lynn to visit our friends`' meetings there,
John Horn has set up papers in the market, or some public place near it, against us,
to represent us as odious as he could; thereby showing as bitter envy and malice,
as some of the popes by their bulls have expressed against the protestant martyrs,
condemning them as heretics, etc.

Our friends perceiving John Horn`'s and Thomas Moor`'s great bitterness against us,
and how implacably envious they showed themselves,
it was thought fitting that some of us should endeavour
a public meeting with them at a certain time,
when George Fox the younger was with me at Lynn,
which was the 15th day of the seventh month, 1659,
and which accordingly we endeavoured for and obtained.

We met in John Horn`'s parish steeple-house at South Lynn in Norfolk,
where he and Thomas Moor, Jr., joined in the controversy with us and our principles,
relating to a sinless perfection of saints and true believers in Christ,
in this life attainable.
This was opposed by them, but affirmed and vindicated by us, according to holy Scripture,
in behalf of Christ and his manifestation and work,
which is to destroy the works of the devil,
and to restore and save man from sin and condemnation.

In opposition to which they pleaded and affirmed,
that sin is a natural heritage in believers, while they live,
or so long as they are here upon earth; contrary to the state of the new birth,
or of him who is born of God, in whom his seed remains; 1 John iii.

A perfection of sincerity toward God, they would seem to own, but not without sin;
alledging Asa king of Judah, that his heart was perfect with the Lord all his days; 1 Kings 15:14.
And yet Asa was reproved by the prophet Hanani,
for not relying on the Lord his God, but on the king of Syria; 2 Chron. 16:7.
Our opposers argued from all his days,
wherein his heart was perfect with the Lord,
to include all the days he lived when he was king; when it is plain Hanani the seer,
shows him his imperfection in his reproof;
"`The eyes of the Lord run to and fro throughout the whole earth,
to show himself strong in the behalf of them whose heart is perfect towards him.
Herein you have done foolishly; therefore, from henceforth you shall have wars.
Then Asa was wroth with the seer, and put him in a prison house,`" etc.
Herein Asa`'s imperfections appeared; and not only in these,
but also when he was greatly diseased in his feet,--he sought not to the Lord,
but to the physicians; verse 12.
It is clear then, that all his days,
wherein his heart was perfect with the Lord his God,
were those days wherein he relied on the Lord, prospered and prevailed over his enemies,
and had real dominion given of the Lord, so long as he relied on him;
for after he declined, so as not to rely on the Lord, nor seek unto him,
thenceforth the judgment of wars must follow and attend him; then all his days,
i+++.+++ e. his good and prosperous days were over.
It is plain the seer`'s reproof has in it such an exception,
that as though in one part of the history it is said,
"`Asa`'s heart was perfect with the Lord all his days,`" the other part is excepted,
"`When he relied not on the Lord, and was reproved by the seer, the honest prophet.`"

By this our opposers aforesaid,
urging Asa`'s perfection of heart with the Lord all his days,
it was easily perceived what sort of perfection they owned;
not a perfection of sanctification or holiness,
but such a perfection wherein sin must be their natural heritage during, life;
or wherein they may do foolishly, commit sin, decline from the Lord,
and not rely upon him, nor seek to him in a day of distress or affliction.

But this was their great imperfection, far short of that perfect sanctification,
by the spirit and power of Christ, and perseverance in his grace, and abiding in Christ,
which we believe and plead for; the grace of God in and through Christ Jesus,
being sufficient for those blessed attainments,
and that good end aimed at and pursued by all the faithful in Christ Jesus.

But these our opposers and adversaries,
would not be persuaded to quit possession of their natural heritage during life,
but rather would accuse and vilify us,
for our Christian testimony to the power and work of Christ within,
to regenerate and redeem us out of the sinful nature,
and fit and prepare us by a perfect sanctification of the Spirit,
for a better inheritance than that of sin and iniquity.
No, these men who pleaded for sin being their natural inheritance,
and remaining even in believers while they are here,
though they confessed their nature to be a filthy nature,
yet as filthy as it was they flatter themselves it is restored in Christ.
But how is it restored in Christ, if it remain filthy all their days,
or while in this life?
What fellowship has righteousness with unrighteousness?
and what communion has light with darkness?

To prove sin a natural inheritance in believers so long as they are here,
they quoted Rom. 7:17, "`It is no more I that do it, but sin that dwells in me.`"
Which proves not that to be Paul`'s state all his life time,
much less that sin was his natural heritage so long as he lived, for he knew deliverance;
"`he was made free from sin and condemnation,
and more than a conqueror through Christ that loved him.`"

"`The light wherewith Christ enlightens every man that comes
into the world,`" they would not confess to be spiritual,
as immediately shining from Christ the divine Word.
But Thomas Moor said,
"`It is both natural and spiritual;`" though they never could make that out,
of that light spoken of John 1:4,9. It being the life which was in the Word,
which was and is the light of men from the beginning,
and which is therefore divine and spiritual, and not man`'s natural reason;
which in one sense they esteemed spiritual, as opposed to the natural body;
but in another sense natural, as opposed to divine light, though the Word be divine.

I perceived,
that though these men and their followers would be esteemed above many others
of the parish priests and church people in matters of faith and religion,
yet they were as carnal in their notions and faith,
and as ignorant of the true light and eternal Word, as other literal professors,
who were strangers to the mystery of Christ in spirit, and of the true,
living faith in Christ.
They were as much addicted to plead and argue for sin in believers for term of life,
and also as envious against us, for our preaching up the gospel Urim and Thummim,
i+++.+++ e. light and perfection, the light of Christ in man; and perfection of sanctification,
as any other of our invidious adversaries;
and as ready to pervert and misconstrue our words,
and to draw false inferences and implications as any of them, especially John Horn,
to beget or raise prejudice and hard thoughts in people against us.

Because we owned Christ`'s body in his glorified state in heaven, to be a glorious,
spiritual body, and the resurrection bodies of the saints not to be carnal,
but spiritual;
they would insinuate against us either a denial or
no faith of the body of Christ in heaven,
and of the resurrection.
We did not only confess the resurrection and ascension
of Christ`'s body that was put to death,
that his flesh saw no corruption, i. e. that he did not corrupt,
but rose again a real body, and not a fantastical body;
but also we turned some questions upon them,
concerning the body of Christ after he ascended,
to know if they owned the same to be a spiritual, glorious body;
or in what sense they owned it?
They confessed it to be a body of flesh and bones, from his saying,
"`A spirit has not flesh and bones, as you see I have.`"

[.discourse-part]
_Query._
But had he no blood in it?
Thomas Moor affirmed openly that Christ`'s body in heaven
is a body of flesh and bones without blood in it,
and that he ascended without material blood.

Here they went too far, besides what Christ or the Scriptures says.
For his body being a real complete body,
these men knew not but it might have some blood left in it when
crucified or renewed in it when quickened and raised from the dead,
although the flesh and bones were more visible to be seen.

Upon our questioning Thomas Moor`'s affirmation,
they appeared staggered and shaken in their minds about it, and yet willing to excuse,
and also to palliate his illiterate notion therein.

Thomas Moor pleaded for excuse,
i+++.+++ e. of Christ having a body of flesh and bones in heaven, without blood in it,
that we do not read that there was any blood in Adam`'s body in paradise.
To which unscriptural excuse, John Horn and Thomas Moor add.

That Thomas Moor brought forth indeed such an observation
as a conception or thought of his,
which rendered it probable to his apprehension,
that a glorified spiritual body needs not the being of material blood in it,
and that he reads not that Adam`'s body had blood in it before the fall,
in which he conceives what before was more purely spirits, was changed into blood,
and therein the body became mortal: but this is his private conception,
which he gives not forth as an oracle to be believed as an article of faith; page 63,
Fuller Discovery.

But what philosophy is this rare notion grounded upon.
That Adam`'s body had no blood in it before the fall, but was made up of pure spirits,
and after changed into blood?
Consequently it must be after the fall that Adam`'s
body was made of the dust of the earth,
tor which they have as much Scripture as that Adam`'s
body had no blood in it before the fall,
or so long as he was in paradise.
What wonderful philosophy is this?

But again they turn about and decline their notion and private conception before,
and leave the matter uncertain,
wherein they appear more ingenious than they have done in
contesting about hidden secrets which belong to God;
for in their said Fuller Discovery, page 76, they tell us thus:
"`We say that that body of Christ which had flesh and bones after the resurrection of it,
is taken up into heaven,
and is in heaven;`" Luke 24:39,40,51,52. What change or
transmutation further it had in its ascension and glory,
we know not.

Herein they showed more ingenuity than in their contention
against us about things they know not;
yet implying and granting they had a belief that Christ`'s body had such
a change or transmutation in its ascension and glory as they knew not.

Nevertheless, they have not only been too busy and intruding in this case,
as well as inconsistent with themselves,
but also uncertain in their propositions and conjectures,
and also very unjust in their reflections; as where, to clear themselves,
they tell us our query is perverse,
in that it intimates or charges them with calling the personal body of our Lord Jesus,
a body of flesh and bones, which they say is a slander; for it is not their expression;
and yet say,
"`Possibly they may sometimes have let it pass without
consideration or particular notice of it,
in some discourse that may have passed between us.`"

How should that be either a slander or not their expression,
which they have as before confessed.
Thomas Moor brought indeed such an observation, as a conception or thought of his;
"`And now that possibly they may sometimes have let it pass without consideration.`"

How inconsistent these men were in their notions, and how mutable in their conjectures.

After much carnal contest held by them,
upon further consideration they would appear more refined and spiritual in their notions,
when they tell us: "`We are assured that even the children of the first resurrection,
when they shall attain to that resurrection of the dead,
and have their bodies that now are vile,
fashioned into the likeness of his glorious body, they, in those very bodies,
being spiritual, immortal, powerful, incorruptible, shall be equal to the angels,
who cannot be hindered from passage by any corruptible things, as doors, walls,
or the like;
but can make their own passage through any such obstacles
more easily than mortal bodies through the air.
And why should it be thought a thing incredible?`" etc.

[.numbered-group]
====

[.numbered]
_Observe 1._ That Christ`'s body is glorious, is according to plain Scripture undeniable;
and that the bodies of the saints in the resurrection
shall be like unto his glorious body,
is unquestionable with us; as also that they shall be spiritual, incorruptible,
equal to the angels;
which equality is ascribed to the sons of God and of the resurrection.

[.numbered]
2+++.+++ But how agrees the description and comparison these men
have given of those spiritual bodies in the resurrection,
with their being bodies of flesh and bones?
How inconsistent have our adversaries appeared in this matter!

[.numbered]
3+++.+++ And it appears very improbable that bodies of flesh and bones
should penetrate or make their own passage through any such obstacles,
as doors, walls, or the like, more easily than mortal bodies through the air;
nor have they produced Scripture for this notion.
They must be very sublime, subtle, airy and etherial bodies,
and not these gross bodies of flesh and blood, that can make such penetrations.

[.numbered]
4+++.+++ Yet we question not the angelical powers to penetrate
and pass through obstacles after a wonderful manner;
howbeit,
it is not safe for men to be too busy and intruding
into these matters and things not seen.
For by such intrusion, questions and critical disputes arise,
about the manner of the resurrection, how, and with what bodies,
and in what form and manner they shall appear?
This is next to a denial or unbelief of the doctrine of the resurrection of the dead,
and tends to beget questions, doubtings, and unbelief thereof,
which is not safe for the weak in the faith, to be received into doubtful disputations.
There were some among the Corinthians that said,
"`There is no resurrection of the dead,`" whose foolishness the apostle reprehended,
when they questioned, "`How are the dead raised up, and with what body do they come?`"
Whom he answered in these words: "`You fool,
that which you sow is not quickened except it die; and that which you sow,
you sow not that body that shall be,`" etc.

====

Now as to the resurrection according to holy Scripture, we do not doubt or question,
but sincerely believe it; and that if in this life we have a part in Christ,
and experience him to be the resurrection and the life unto us, we doubt not,
but believe we shall have our own proper bodies,
which shall be both spiritual and glorious, like unto his glorious body.
To every seed he will give a body as it pleases him;
and therefore if we should be so nice or curious as to question God, or Christ,
or his saints, or ministers, what manner of bodies,
and of what essence or substance they shall be; or how bright, glorious and spiritual;
this would bespeak a diffidence or unbelief of a future state of the saints in glory,
and of the divine power,
as well as the appointment and promises of God and
Christ to bring them into such a state of glory.
Certainly if the Lord own us for his children and sons of God while in this life,
though yet it appears not what we shall be, we know that when he shall appear,
we shall be like him; for we shall see him as he is; 1 John 3:1-2.
And our Lord Jesus Christ declared; "`This is the will of him that sent,
me, that every one which sees the Son, and believes on him, may have everlasting life;
and I will raise him up at the last day.`"
And, "`Father, I will that they also whom you have given me, be with me where I am,
that they may behold my glory, which you have given me.`"
We may rest contented in the real faith and earnest given us,
of these glorious promises and privileges, without being busy with unlearned questions,
perverse disputings, or intruding into things not seen;
or secret unrevealed things which belong to God.
And if any should question what manner of change or transmutation Christ`'s body had,
after he arose from the dead, or in his ascension, or how it was changed,
being seen to have flesh and bones, and no blood in it, as supposed,
when he was risen from the dead,
as these adversaries have uncertainly and dubiously suggested,
I should conclude such busy intruders ought not to be gratified or answered,
but to be avoided.

We may without doubt,
believe Christ`'s body wonderfully changed and glorified in his ascension,
and that Enoch, Heb. 11:5. who was translated, that he should not see death,
was changed; and the prophet Elijah in his rapture, 2 Kings 2:11.
when he was taken up in a fiery chariot,
and by a whirlwind went into heaven; whereby was typified Christ`'s ascension,
he being an eminent type of Christ.
We may without offence believe Elijah`'s body must be changed before he got into heaven,
seeing flesh and blood cannot inherit the kingdom of God, 1 Cor. 15:50.
and yet without offence conclude, that the body of Enoch,
before he was translated, and the body of Elijah, before his rapture,
were not without blood in them, or else they had no such change,
as to be made fit for that kingdom which flesh and blood cannot inherit.

The great power and works of God in these transactions and matters,
should rather be occasion of admiration, than of disputation;
as well as the resurrection by the power of Christ, and sudden change of the living,
even in a moment, in the twinkling of an eye at the last trump,
for the trumpet shall sound and the dead shall be raised incorruptible,
and we shall be changed, 1 Cor. 15:51, 62.

It is by the great and glorious power of our Lord Jesus Christ,
the power and wisdom of God,
that such a sudden and wonderful change must be effected and the dead raised incorruptible.
And, it being appointed for men once to die, and after this the judgment;
and that there shall be a resurrection both of the just and unjust,
and that by divine appointment, and that it shall go well with the righteous,
but ill with the wicked;
I have always believed it better to labour to be righteous in this life,
than to trouble ourselves about what or how we shall be in the life to come,
or what manner of bodies or clothing we shall have in heaven,
and to trust the Lord therewith.
Our chief care and concern should now be to walk in the way to heaven,
to get there even in the way of truth and righteousness,
and there we shall not be in want,
but enjoy all things to complete our joy and felicity in heaven and eternal glory;
even in the full fruition of that incorruptible inheritance which will never fade away,
reserved in heaven for all them who are kept by the power of God,
through faith unto salvation. 1 Pet. 1:4-5.

Many persons, by vain imaginations and high thoughts, intruding into things not seen,
and matters too high for them, and their human wisdom and carnal reason,
do thereby darken themselves,
and cloud their understandings from the true sanctifying and saving knowledge of God,
and mystery of Christ Jesus, and his power and spirit;
who is mighty and powerful in himself, and in his saints and members,
who being spiritually united to him, and thereby made members of his body,
are one body in him; so that there is one body and one spirit: Eph. 4:4.

There are other persons who in their singular opinions, strange or new notions,
exalt themselves in their own conceits above all others, and thereby cause contention,
strife, and divisions, many times either about words, critical distinctions,
or things not essential to salvation, or to the saving knowledge of the true God,
or his son Jesus Christ;
and thereby such endeavour to make divisions and parties to themselves,
that they may be exalted as sect masters.
But the judgment of Truth has gone forth against all such,
and will stand over that exalted, arrogant spirit forever.

"`Without controversy, great is the mystery of godliness: God was manifest in the flesh,
justified in the spirit, seen of angels, preached unto the Gentiles,
believed on in the world, received up into glory.`"
Now this mystery of godliness being a great mystery, without controversy,
it is best for professors of Christianity to keep
out of controversies as much as they can,
and shun perverse disputes of men of corrupt minds,
with all their unlearned and unprofitable questions;
and rather to turn in their minds to the light of
Christ,--retire to the simplicity in him,
and watch therein to understand this great mystery of godliness,
both with respect to God manifest in the flesh, and justified in spirit.
The manifestation and power of Christ in the flesh was excellent in him,
and therein by his most precious precepts and doctrine, his wonderful works and miracles,
his blessed example and sufferings,
he declared and showed forth the holy design of Christianity.
To be truly sensible of his being justified in spirit, is very precious,
and arises from a true, spiritual, living knowledge and experience of Christ in spirit,
and as known after the spirit, and not after the flesh, or any fleshly knowledge of him;
for as wisdom is justified, commended and praised of her children,
by the fruits thereof in them, so Christ is justified and exalted in spirit,
in his faithful followers, his holy generation and children.

God and his great power was wonderfully manifest in Christ in the days of his flesh,
in many respects,
and he showed various signal tokens and signs of his power in those days,
as in his wonderful miracles, laying down his life and taking it up again;
transfiguration in the mount, so as his face did shine as the sun, etc.
Mat. 17. In his appearing in several forms after he arose from the dead, Mark 16:12.
and at sundry times showing himself,
and appearing in the midst of his disciples, the door being shut, John 20:19,26.
And also when he sat at a meal with them,
and in such a familiar manner manifested himself, that their eyes were opened,
that they knew him, he vanished out of their sight; Luke 24:30-31.
Such wonderful power he showed after he was risen from the dead,
to manifest himself and confirm his disciples in the faith,
knowledge and testimony of his resurrection, as well as in his ascension.

Thomas Moor`'s declaring, that the blood of Christ shed,
is the foundation of their faith, occasioned some further question.
As where it is?
Which they answered not, nor could they tell,
yet said that the life of Christ is not the blood of Christ;
wherein they showed themselves both ignorant of the mystery of his blood,
and of the foundation of faith, which is Christ himself.
Though the blood of Christ that was shed for remission of sins,
was truly acceptable to God, as being offered by him,
as part of his offering to make reconciliation and atonement for mankind,
who had transgressed; for He, i. e. Christ, gave himself a ransom for all,
for a testimony in due time of God`'s free love to all mankind,
yet Christ is the foundation and chief corner stone.
Their contesting about Christ`'s body in heaven,
and his blood as wholly shed--on further thoughts--came to be abated,
and they varied in their book against us, styled,
A Brief Discovery of the people called Quakers, etc.; for in page 11, they told us.
That his blood that was shed, or poured out for the remission of our sins,
in the virtues of it is with the Father, and so in and with Christ.
In page 12 they say.
That there are indeed very probable arguments used to prove,
that that precious blood was re-united again with the body of Christ in the resurrection.
But how agrees this with their holding it to be a
body of flesh and bones without blood in it?
In both which they appeared to go beside what they have declared,
i+++.+++ e. That it is rather a virtue to which they are advised not to be wise, or think,
or guess, above what is written; page 12.

Had they kept to this advice, they had shunned much vain contention as well as confusion,
about their uncertain conjectures and imaginations,
whereby many foolish hearts have been darkened.
When men intrude into things not seen, and set their imaginations on work about them,
whether it be about the body of Christ in heaven, or the resurrection bodies of saints,
as what forms or shapes they have, or what manner of bodies;
not being content to acquiesce in the will of God and his good pleasure,
who gives a body as it pleases him, and to every seed his own proper body;
they may form ideas or likenesses in their minds, and never be the nearer to heaven,
but further off from the life, the light,
and true knowledge of Him who is the resurrection and the life.

When a person fearing God, and loving our Lord Jesus Christ in sincerity and truth,
confesses his or her real belief, faith or hope, in terms of holy Scripture,
it is sufficient; whether it be of the suffering, death, resurrection,
or ascension of our Lord Jesus Christ into heaven and glory;
or of his body being spiritual and glorious in heaven.
And as the saints being spiritually united to him, are his church and body also,
and esteemed mystical, while here on earth;
so their low or humble body shall be changed and fashioned like unto his glorious body;
and of the resurrection of the dead, both of the just and unjust,
and of eternal judgment, according to holy Scripture--I say, whosoever fearing God,
or friends of truth, are at any time questioned about these things,
it will be sufficient, and ought to be satisfactory,
to answer them in plain Scripture language, and keep to the same.
And I would advise all Friends to keep to the words, terms,
language and doctrine of holy Scripture, and not to be wheedled or drawn from the same,
nor allow themselves to be imposed upon, either with unscriptural terms,
or unlearned questions, by any contentious or carping adversaries whatsoever.
For foolish and unlearned questions, as well as profane and vain babbling must be avoided.

I have here given but a brief account relating to
the controversies between the said John Horn,
Thomas Moor, and us, the people called Quakers,
they being more fully discovered in several answers to their invidious books.
What relates to our first dispute, is answered in a treatise, entitled,
A Brief Discovery of the dangerous Principles of John Horn and Thomas Moor, Jr.,
printed A. D. 1659.

In our said meeting, matters and questions were for the most part quietly debated,
and the people, though numerous, were generally civil, and the meeting ended peaceably.
There were persons present who took some care of us, i. e. George Fox (the younger),
and myself, that none might do us any harm.

John Horn not obtaining his ends to bring us under popular odium,
appeared uneasy and angry, both in his preaching and writing, to render us contemptible;
divulging his defaming papers in the town,
and taking great pains to write abundance to reproach us and our principles;
and much writing passed between him and me, by way of queries and answers.
He crowded whole sheets with small writing against me,
which did not well consist with his vilifying, highly despising,
and setting me at naught, as much as he could, condemning me as one accursed, a heretic,
and what not; as may be made further appear.

However our paper pellets did not end the fray,
but the said John Horn and I had another public meeting
in the chancel of his parish church,
in South Lynn aforesaid, the 13th of the eleventh month, 1659,
a few weeks after the first.
At this meeting,
John Horn undertook to make good his former charge against the people called Quakers,
which it seems was a work not done, but still to do, namely:
To prove them to be deceivers, and such as people ought not to hear or follow,
but to account them accursed, etc.

This was a very heavy charge against us as a people, but far from proof,
and as unbecoming a professed minister of Christ, thus to teach people to curse us,
or so to judge or account us accursed,
as opposite to the doctrine of Christ`'s ministers.
Bless, and curse not.

But for what cause was this heavy curse pronounced against the said people as deceivers?
Principally because they hold the doctrine of perfection, that is,
a sinless perfection attainable by true believers in this life,
or on this side the grave; which was both believed and taught by the holy prophets,
Christ Jesus, and his faithful ministers;
according also to what God has promised his faithful people,
whom he washes from all their filthiness; and Christ`'s true followers,
who believe and walk in the light, and experience the blood of Jesus Christ,
the blood of the everlasting covenant, to cleanse them from all sin.

But contrariwise, this our severe judge, John Horn,
appeared also against the true apostles of God and Christ, in his affirming.
That they did use to confess themselves sinners; to be weak and brutish in themselves,
as of themselves, and to own themselves sinners;
and that they use to confess sin in themselves,
and none of them to glory in their perfection and sinlessness.

[.numbered-group]
====

[.numbered]
1+++.+++ That they use always so to confess of themselves, I did, and still do deny;
they did not only confess, but forsook sin and evil, and exhorted others so to do.

[.numbered]
2+++.+++ They gloried in the God of their salvation;
and rejoiced in his salvation and deliverance from sin and Satan,
which deliverance God wrought in thorn, and for them, by Jesus Christ.

====

How odious,
and how much accursed soever John Horn has rendered the people called Quakers,
they will never be reconciled to his raillery;
or to his doctrine pleading for sin during life,
and accusing the holy prophets and apostles with
having sin in them so long as they lived,
and all men, while living, with sinning, Jesus Christ excepted.

But blessed be the Lord our God,
that has given us a faith contrary to such sin-pleasing doctrine;
that he has given us to believe unto righteousness, and unto the salvation of our souls;
that he has given us the word of faith in our hearts, to believe in him,
i+++.+++ e. Jesus Christ, upon whom help is laid, who is mighty,
and able to save to the uttermost all that come unto God by him.
So that we find great cause to glory in the God of our salvation,
having laid aside all glorying in the flesh, with all self-confidence and ostentation.
There were some other points discoursed between us at the aforesaid meeting,
relating to the said charge against the people called Quakers,
but this about perfection was the principal point.

After the discourse, John Horn divulged a partial, lame, and abusive account,
falsely styled, The Quakers proved deceivers,
and such as the people ought not to listen to, or follow, but to account accursed.
Whereby, in the very front,
he exposed his own great envy and abuse against an innocent religious society and people,
whom the Lord has preserved, supported and blessed, through all their persecutions,
reproaches and sufferings.

An answer entitled.
The Quakers no Deceivers, was also published,
to detect the said partial and abusive account, wherein John Horn`'s abuses,
confusion and envy,
relating to the said discourse are more fully demonstrated and detected.

That the bitter spirit of those our adversaries may further appear,
and what sort of persecutors they were, observe their treatment of us;
in a paper against me and the Quakers, they give us these characters, viz;
That they be indeed vipers and scorpions, cockatrices, not to be charmed;
and like the locusts out of the bottomless pit, whose sting is in their tails, etc.
And yet these persons who thus reproached us, have confessed that we, i. e. the Quakers,
are a heavy judgment that God has ordered to them,
to punish them for their neglect of Christ, the salvation of God,
and the truth of him so long abused by them, as in their Brief Discovery, page 22.

Upon which I made this observation: "`Now from their own confession,
they are such as have not the seal of God upon their foreheads,
for the locusts were only sent to punish such men
as had not the seal of God upon their foreheads; Rev. 9:4.
Thus their malice and confusion are gone abroad,
and they shall know one day, that we are another manner of judgment against them,
than the locusts.
And the more they strive against the heavy judgment that God has ordered to punish them,
for their neglect of Christ and abuse of his truth,
the greater will their shame and torment be.`"
Quakers no Deceivers, page 32.

And it was apparent, how this heavy judgment of God affected these persons:
how impatient they were under it, and how fretted and disquieted they were;
how perplexed, vexed, and provoked to jealousy, rage and confusion,
by a foolish and contemptible people, in their esteem.

After some disputes between us and them,
and letters and manuscripts passed between John Horn and myself;
I had a furious letter from him,
containing his raging bull of excommunication and repeated curse against me;
which greatly showed the temper of his spirit, that he was not of a Christian,
but of a bitter persecuting spirit.
Some passages contained therein, follow in his own words:
"`God stood by and enabled me to stop your mouth,
and prove you such as the people ought to account accursed.
The gall of bitterness you are in--deceivers, hardened in your way,
and it is to no purpose to multiply answers, or writings, or words,
to you that are self-condemned; and the apostle bids,
after the first and second admonition, reject a heretic, one that has chosen his own way,
and is hardened therein.
What but labour in vain, is it to bestow writings or answers upon you?
Seeing you are full of tergiversations, craft and subtlety, and resolved in your way, etc.
And therefore I hereby reject you as a self-condemned person,
once and the second time admonished, or detected to be a deceiver;
which is reason sufficient for my refusing to answer these, or any other queries,
henceforth to you, upon whom there is no hope of any good to be done thereby,
unless you recant and repent, etc.
Having written this rejection of you, "`I know you, being deceivers,
cannot write anything worth the reading, for any rightness therein.
We are satisfied, and so were the people that heard our discourse, very generally,
that you Quakers, so called, are deceivers, and such as we ought to reject,
and you are hardened in your evil way;
your writings we know are full of equivocation and falsehood,`" etc.
Thus far John Horn.

[.discourse-part]
_Remark._
As to the judgment and rejection here denounced against me and the people called Quakers,
as deceivers, accursed, heretics, etc., I am well satisfied in my conscience,
that it is a mere piece of foul rubbish and presumptuous raillery,
unjustly to defame and calumniate me and my friends, the said people;
and as grossly false it is, that the people that heard our discourse,
were very generally so satisfied, that we who are called Quakers are deceivers.
For the people generally, except a few of John Horn`'s scornful proselytes,
were civil toward me at that discourse; and in the conclusion many of them so kind,
that they took care to see me safely attended and conducted out of the chancel and steeple-house,
where we had the discourse, that I might sustain no harm from any of the ruder sort.
And the Lord by his power, so stood by me, that even those of the rougher sort,
counted as of the mob, were so moderated and kind, that they attended me in my defence.
For as I believed, so I felt the power of the Lord over all, to moderate, calm,
and quiet their spirits,
even beyond the doubts and fears which aforehand
had somewhat entered the spirits of some Friends,
because they expected the seamen and others of the looser sort of people,
would then be at liberty,
and they knew not how these adversaries might incense
them by vilifying and reproaching us.
But blessed be the Lord our God, who stood by and defended us;
to him who has bounded the sea and limited the waves thereof,
be glory and dominion forevermore.

After these public discourses and controversies, with the said John Horn and Thomas Moor,
Jr., they published two books more against the people called Quakers; the one styled,
A Fuller Discovery, by John Horn and Thomas Moor, sen.
and Thomas Moor, Jr. And the other boastingly styled.
Truth`'s Triumph, by John Horn.

To both which books an answer was given by George Whitehead, chiefly entitled,
Innocency elevated against Insolency, etc.
Wherein the matters in controversy are more particularly touched and answered,
than in the preceding relation;
and these men`'s envy and calumnies against us also detected,
being far more numerous than are specified or touched upon in this brief account.

Our adversaries before mentioned, being implacably set against us,
and bent in their persecuting spirit, to revile and reproach us and our holy profession,
to possess the minds of other people with prejudice against us,
occasioned a greater concern to be laid upon me from the Lord,
the oftener to visit that town of Lynn,
and to have the more meetings there for Truth`'s sake,
and in good will to the people and true love to their souls,
that they might not be misled through these adversaries`'
injurious calumnies and invidious noise.

And I had not only many considerable meetings of our friends and others in that town,
but also several public discourses with our adversaries,
as twice with John Horn and Thomas Moor, as before related;
and thrice with William Falconer, then a Presbyterian minister or priest, in Lynn,
with whom I had three public meetings, but not in their parish church, so called,
but at certain convenient houses in that town.

To prepare us for a public discourse or dispute,
William Falconer proposed the following nine questions to discourse upon;
to which brief answers are likewise here given.

[.discourse-part]
_Question 1._ Whether there be three persons in the Godhead?

[.discourse-part]
_Answer._
Three persons in the deity we read not of in holy Scripture;
but of three bearing witness in heaven,--the Father, the Word, and the Holy Spirit,
and that these three are one.

[.discourse-part]
_Question 2._ Whether the Scriptures be the rule to try doctrines and spirits?

[.discourse-part]
_Answer._
The holy Scriptures are truly owned and esteemed a rule subordinate to the Holy Spirit,
from which they were given forth; and by the help of the same Spirit,
doctrines and spirits may be tried; but the Spirit is the supreme,
universal guide and rule, which affords light and understanding,
to discern and try both spirits and doctrines, to the truly spiritually minded;
for discerning of spirits is a spiritual gift of the Holy Spirit; 1 Cor. 12:10.

[.discourse-part]
_Question 3._ Whether the Scriptures are the Word of God and the means of salvation?

[.numbered-group]
====

[.numbered]
_Answer 1._ The Scriptures, i. e. the writings are not properly the Word,
but Christ is the Word: In the beginning was the Word; John 1:1,3; Rev. 19:13;
which the Scriptures were not; though the holy Scriptures contain the words,
holy commands and doctrine of God and Christ; and they, i. e. the Scriptures,
cannot be termed the Word of God, in a proper and strict sense, but rather figuratively,
the effect being put for the cause; The worlds were framed by the Word of God;
Heb. 11:3; not by the Scriptures.

[.numbered]
2+++.+++ The Scriptures are not the means of conversion and salvation universally;
for many we hope may be and are converted and saved, who have them not,
and many who cannot read them.
But Christ, who is given to be the light of the Gentiles,
and God`'s salvation unto the ends of the earth.
He is the way to the Father,
and his light the universal and effectual means of conversion and salvation.

[.numbered]
3+++.+++ Sometimes true preaching is a means of conversion and salvation by the power of Christ;
and the holy Scriptures being given by divine inspiration,
are by his spirit made profitable to the man of God, for doctrine,
reproof and instruction in righteousness, that the man of God may be perfect.
And they are able to make wise unto salvation;
but it is through faith which is in Christ Jesus.

====

Therefore Christ is the efficient cause of salvation,
he being our blessed and only Saviour.

[.discourse-part]
_Question 4._ Whether there be in every man a sufficient
light to bring him to believe in Christ?
Answer.
Yes, Christ being the light of the world;
that true light which enlightens every man that comes into the world,
whose light directs and leads to him who gives it:
Christ exhorted to believe in the light, that you may be children of the light;
therefore his light is sufficient to bring men to the faith of Christ, to believe in him,
even in his name and power.

[.discourse-part]
_Question 5._ Whether believers are justified by the
imputation of the righteousness of Christ,
applied to them by faith, which he fulfilled without them in his flesh?

[.discourse-part]
_Answer._
This question is not a fair or clear question, but obscure and ambiguous;
the terms not being explained, it may be equivocally turned into various meanings:
howbeit, in truth`'s simplicity and plainness I answer:

[.numbered-group]
====

[.numbered]
1+++.+++ The application or imputation of Christ`'s righteousness, when made by himself,
i+++.+++ e. by his own spirit, unto believers,
who truly apply their hearts to obey and follow him,
is unto their justification and salvation;
yet not experienced without the sanctification of his Holy Spirit and work within them;
nor by any men`'s reckoning or applying to themselves the righteousness of Christ,
or his obedience considered only without them,
while sin and disobedience are continued within them; "`If I wash you not, said Christ,
you have no part with me.`"

[.numbered]
2+++.+++ Christ`'s obedience, even unto the death of the cross, though it was for us,
to make peace, and obtain great good for us, as mercy and eternal redemption,
yet that will not justify or save us,
unless we yield sincere obedience unto him in us also.

[.numbered]
3+++.+++ Too many there are that please themselves in their polluted sinful state,
with a false faith, imputing or reckoning to themselves that, which in reality,
they have no share in: as that of Christ`'s righteousness only without them,
while they themselves are filthy and unrighteous still;
not agreeable to the justified state of true believers, who are washed, sanctified,
and justified, in the name of our Lord Jesus, and by the spirit of our God; 1 Cor. 6:11.

====

[.discourse-part]
_Question 6._ Whether all, or any believers attain to such a perfection in this life,
as to be without sin?

[.discourse-part]
Answer.
Yes; those true believers who are born of God, and abide in Christ;
whose work is to destroy the devil`'s works, and to put an end to sin,
and finish transgression, and bring in everlasting righteousness.
These believers attain to such a sinless perfection in this life.

[.discourse-part]
Question 7. Whether the Lord`'s supper--administered
in bread and wine--and baptism with water,
be not the standing ordinances of Jesus Christ till the end of the world?

[.numbered-group]
====

[.numbered]
_Answer 1._ In the first part he begs the question, and imposes without proving,
the priest`'s ministering bread and wine to be the Lord`'s supper;
for the supper of the Lord, Christ, with his own disciples,
consisted not only in bread and wine--or the cup--but chiefly the passover,
which was typical and legal, and therefore not any standing ordinance of Jesus Christ;
Luke xxii; Matt. 26:18.

[.numbered]
2+++.+++ Baptism with, or in water, was John`'s baptism, and not Christ`'s baptism,
nor a standing ordinance, but a decreasing, shadowy, or typical ministration; and John,
as he preferred Christ before himself,
so he preferred Christ`'s spiritual baptism above his own.
The dispensation of Christ and the new covenant, is a dispensation of substance,
not of shadows; and the higher the sun rises, and the brighter the same shines,
the more the shadows decrease and flee away.

[.numbered]
3+++.+++ But I take it for granted, this querist, the Presbyterian minister,
by baptism with water, did not mean what was properly water baptism, as John`'s was;
but sprinkling infants on their faces; which is no real or proper baptism,
but rather rantism, for which they produce no foundation in sacred Writ.

====

[.discourse-part]
_Question 8._ Whether the present ministry of England, whom the Quakers revile,
be not the true ministry of Christ?

[.discourse-part]
Answer.
That we revile them, is not true;
yet we do not believe them to be the true ministry of Christ,
or called by Christ to be his ministers; for if we did, we should not dissent from them.
And the same cause of dissent which we had in those days, i. e. of the Commonwealth,
so called, we have still, namely: the great corruption, avarice, and pride of priests.

[.discourse-part]
Question 9. Whether the same body which dies, shall rise again?

[.discourse-part]
Answer.
For answer, I refer to the apostle`'s answer to the like question, which was,
"`How are the dead raised up?
And with what body do they come?`"
His answer in a way of allusion, or simile, was, "`You fool,
that which you sow is not quickened except it die; and that which you sow,
you sow not that body that shall be, but bare grain, it may chance of wheat,
or of some other grain: but God gives it a body as it pleases him;
and to every seed his own body,`" and to speak more plainly in his negative,
of the sameness of the body, he says; "`Now this I say brethren,
that flesh and blood cannot inherit the kingdom of God;
neither does corruption inherit incorruption.`"

The said William Falconer promised aforehand,
to dispute the seventh and eighth questions at any time and place,
and on such conditions as should, by some men of each party, be seen fit;
and that he would prove the ministry of England to be the ministry of Christ.
This he promised at Isabel Barnet`'s, of Lynn, the 17th day of the eighth month, 1659.
But at our first dispute or discourse, we got not to the seventh and eighth questions,
but upon some of the questions before.

When we were met in a large room, yet small enough to contain the people,
I gave answer to his first question, according to Scripture,
and to the same effect as I have answered it before; but that would not satisfy him,
unless I would answer his question in his own terms,
i+++.+++ e. about the personalities or three distinct persons in the deity.
Which terms he being desirous to prove by Scripture, partly insisted on Ps. 2:7;
The Lord has said unto me, you are my Son, this day have I begotten you.
But hereby he did not prove the terms, three persons in the deity,
or three distinct coeternal personalties in the Godhead, according to their principle.
For he could not deny that Christ the Son of God, was begotten in time, and that.
This day have I begotten you, was an act in time; and yet the Son of God,
the eternal Word, was in and with God from eternity, before days and time;
and in due time proceeded and came out from God;
"`In the fulness of time God sent his Son made of a woman, made under the law,`" etc.

The holy Scripture trinity, or three thereby meant, we never questioned, but believed;
as also the unity of essence, that they are one substance; one divine, infinite Being;
and also we question not, but sincerely believe the relative properties of Father, Son,
and Holy Spirit, according to holy Scripture testimony.
Matt. 28:19; and that.
These three are one; 1 John 5:7.

The said priest, William Falconer, being deficient in Scripture proof of their terms.
Three persons in the Godhead, our discourse of that point, and first question,
soon went off, and with ease to us; George Fox (the younger),
being also with me at our first discourse with William Falconer.

I well remember in a conference which I had with Dr. Tennison, archbishop of Canterbury,
our friends, Gilbert Latey and Dr. Thomas Lower, present;
the bishop and I fell into some friendly discourse about the trinity;
as to their definition of a person, what a person is.
I told the bishop I had discoursed many, especially of the learned, about that point;
and that upon the definition of a person, or what the word person means,
I never could find them consistent, but contradictory to themselves,
on their own article of faith; as when they thus define person: an intelligent being;
or individual substance, of a rational nature, as Thomas Aquinas,
who has been quoted against us, says; Persona est nature rationalis individua substantia,
qua, nee est pars alterius nee ah alio sustentatur,
i+++.+++ e. "`A person is an individual substance of a rational nature,
which is neither a part of another, nor upheld by another.`"
I mentioning this to the archbishop, told him withal,
that to assert three persons in the deity, seeing they are not three beings,
nor three substances,
I confess I could never reconcile with there being three distinct or separate persons,
and not three substances, but one substance, or being,
when a person is a rational substance by their own account.
And moreover, they deem it blasphemy, to hold the blessed trinity to be three substances,
or three beings, for that were to make them three Gods;
how then are they three distinct persons, i. e. rational substances?
These, as I told the said archbishop, I could never reconcile;
for if they be not three distinct substances they are not three distinct persons.
Unto which he ingenuously answered;
"`It is safest or best to keep to Scripture words
or terms in expressing such weighty matters of faith,
concerning the deity, and not to express them in metaphysical terms of philosophy,
or the like, which are not in holy Scripture.`"
And truly I was glad when I heard such an honest confession from him.

As to the second question, and first part of the third,
we preferring the holy Spirit to the Scriptures, as being the chief guide and rule,
and the holy Scriptures as truly useful in their place,
under the help and guidance of the Spirit; and the Word before the Scriptures,
we had little controversy.

But on the second part of the third question,
whether the Scriptures are the means of conversion and salvation;
and on the fourth question,
of the sufficiency of the light in man to bring him to be a true believer
in Christ which tends to resolve the conclusion of the third,
when truly answered and distinguished between the internal Word, the Light,
and the Scriptures.
Here arose the chief controversy, the priest giving the preference to the Scriptures,
from the text in 2 Pet. 1:19; We have also a more sure word of prophecy;
whereunto you do well that you take heed, as unto a light that shines in a dark place,
until the day dawn, and the day-star arise in your hearts.

The priest would have this more sure word to be the Scriptures of the prophets,
which I was constrained to oppose,
considering wherein and between what the comparison more sure word consisted;
as being between the voice that came from heaven to Christ in the
mount--which Peter and James and John heard--and the word,
the light, or the spirit of prophecy, in the hearts of those believers,
who heard not that voice from heaven, nor were with Peter,
James and John in the mountain,
when they heard that voice from the excellent glory from heaven.
Yet that voice was certainly true, that Christ was the beloved Son of God, whom,
by that voice they were required to hear.
It is not said.
You have also a more true word of prophecy, but a more sure word.
It was more sure to them who had it in their hearts constantly to take heed unto,
and to guide them to the arising of the day-star in their hearts,
even the bright and Morning Star.
I say this word, this light, which they had in their hearts,
must needs be more sure to them, than that voice which they never had nor heard;
it being especially and peculiarly heard by three disciples, not by all believers;
but this internal word or light, is generally manifest, and continues in the believers,
who wait for the appearance of Christ in spirit.

The priest would have this more sure word of prophecy, unto which Peter directed them,
to be the Scriptures of the prophets, who prophesied of Christ to come, before he came.
To which I answered; the voice from the excellent glory, which Peter,
James and John heard, when they were with Christ in the mount,
testified of Christ being come, saying; "`This is my beloved Son,
in whom I am well pleased; hear him.`"
Therefore this voice and testimony so express to them,
must be more sure than the Scriptures of the prophets, before he was come;
for it would be no small perversion of Peter`'s words, to turn them thus;
although we have a voice and testimony from heaven,
that Christ the Messiah is come already,
yet you have also more sure Scriptures of the prophets,
which foretell and declare unto you that the Messiah is to come,
and that you do well to take heed thereunto until he come.
This were to deny Christ to be already come,
contrary to the testimony given of him from heaven,
to and by three of his faithful and credible witnesses, Peter, James and John.
And though that voice from heaven was sure and certain, to them who heard it,
yet that word, that light of Christ,
which in many appears as a light shining in a dark place, even in dark hearts,
is more sure to them than that voice or vision which they have not heard or seen.
This word or light, will be known to be a very sure guide and rule, will prophesy, open,
and show things to come, especially to them that do well, that is,
in taking timely heed thereunto.

This point about the more sure word held longest in dispute,
but I argued the matter so closely, the Lord standing by and assisting me,
that the priest appeared to come down in his spirit,
as one under some conviction when his logic failed him; which being observed,
George Fox the younger called out to him to mind that which
convinced him in his own conscience of the truth,
that had been demonstrated to him; to which he made no reply that I remember,
but appeared more moderate, and less in prejudice than either of our adversaries before,
namely; John Horn and Thomas Moor.

There was little discourse, if any at that time, upon the 4th, 5th and 6th questions,
about the sufficiency of the light in men, perfection and justification,
which therefore I shall not, nor need I, here insist upon,
having answered them already before.

At our second meeting,
many considerable persons and others of Lynn were gathered together, and generally civil,
as they were before.
William Falconer had some time before promised to prove
the ministry of England to be the true ministry of Christ,
in answer to his 8th question, which he then affirmed, but I could not grant,
and put him upon proof in several respects.

[.numbered-group]
====

[.numbered]
1+++.+++ Because they could not be the ministry, ministers, or messengers of Christ,
unless they were called, gifted, qualified and sent by him,
as his ministers and messengers ought to be;
but of this the priest gave no proof or demonstration from,
or according to holy Scripture.
The laying the hands of the Presbytery upon him for approbation,
alledged from 1 Tim. 4:14,
could not evidence this person either gifted or called by Christ Jesus into his ministry.
It could not prove him to be either so qualified or gifted, or a minister of Christ,
as Timothy was; for those elders who gave their approbation of Timothy,
and signified the same by laying on of hands,
no doubt understood he was well gifted and qualified,
in order to be employed in the work of Christ`'s ministry;
for Paul thus exhorted him in the very place pleaded;
Neglect not the gift that is in you, which was given you by prophecy,
with the laying on of the hands of the Presbytery or elders; one of whom Paul was; 2 Tim. 1:6.

This Presbytery or company of elders, owned both the inward divine gift,
and prophecy in those days, which Timothy partaking of to prepare him for his ministry,
was approved of by those elders in Christ, who knew Timothy;
by which we could not therefore believe that those of that Presbytery,
which were of William Falconer`'s society,
could either make or confirm him to be a minister of Christ,
or prove him called by Christ unto his ministry.
No more than if he should have argued,
because Timothy and Titus were ministers of Christ,
and approved and encouraged by St. Paul; therefore, I William Falconer,
am a minister of Christ, approved by my brethren of the Presbytery,
which would be but a poor way of arguing;
according to which any false pretender may claim a part in Christ`'s ministry;
but no sincere honest man or minister of Christ Jesus will say, or argue,
that because Peter and Paul, etc., were Christ`'s ministers and ambassadors,
therefore I am a minister of Christ.

[.numbered]
2+++.+++ Their education at their academies, schools, and colleges,
to learn and study natural arts and sciences, philosophy, and divinity, etc.,
and esteeming such learning and acquirements essential to their ministry,
or to qualify them for divines or gospel ministers, or to this effect,
was objected against their being Christ`'s ministers.

[.numbered]
3+++.+++ Besides, their colleges erected by Papists in the dark times of Popery,
and many of them called by saints`' names; this was also objected against their ministry,
as not being called by Christ, but set up by man, and in the will of man.

====

The priest`'s chief plea or allegation for their colleges, was,
that there was a college in Jerusalem; 2 Kings 22:14; 2 Chron. 34:22.

I showed the meeting that was no sufficient proof or warrant for their colleges now,
to educate men for Christ`'s ministry, or to make them Christ`'s ministers,
by natural learning and study at these colleges;
this could be no proof of Christ`'s call or ministry.
In that college or second court, as it is called in Jerusalem,
dwelt Huldah the prophetess, to whom Josiah, king of Judah,
sent Hilkiah the priest and others, to inquire of the Lord for him, and for the people,
and for all Judah, concerning the words of the book of the law,
when it was read before the king; 2 Kings xxii.
Here was a good woman, a prophetess, who dwelt in this college, or second court,
to whom the king sent a priest and others, his servants, for counsel.
It appears the king had more confidence in this woman, than in the priest,
as also believing she had more of the counsel of God,
and more understanding of his law and judgments written therein, than the priest had;
or else he needed not to have sent the priest to her for counsel.
She had the spirit and gift of prophecy,
to discover judgments when coming or approaching,
which were foretold in the law of Moses.
It was by this divine gift, as appears, she could expound the law better than the priest;
yet she had not this knowledge or learning from the college, or by natural learning,
for she was a prophetess, endued with the spirit and gift of prophecy,
which came not by the will of man, nor was it of man, but of God, and from him.

But these colleges pleaded for to make ministers in, i. e. the ministry of England,
can make no such ministers as this prophetess;
neither do they believe or own that true prophets or prophesying are in these days,
who say and conclude that both prophesying, visions,
and immediate revelations are long since ceased, as many of the priests have declared,
and generally do conclude;
consequently they have no divine or immediate call from Christ into his ministry,
but only a human call from men, when educated in human learning,
without being qualified or gifted by the Holy Spirit.

Yet we allow and own human learning in its place,
as useful and necessary in many respects;
but do not so idolize it as to think men may thereby
be made divines or ministers of Jesus Christ,
for they must be of his own making and calling.
And what authority have they, either of the Presbytery or Episcopacy,
to authorize others unto Christ`'s ministry,
who themselves are not authorized by his power and spirit,
i+++.+++ e. the same spirit which the holy apostles, primitive elders and overseers had?
Surely their ceremony of laying on of hands cannot convey it,
nor give them divine authority.

Our discourse about their colleges held not long,
and that meeting ended civilly and quietly;
though the auditors were disappointed of their parson`'s proving
the ministry of England to be the true ministry of Christ.
That remains still to be proved, both as to their call, conduct and practices.
We have not found them to be Christ`'s ministry in any of these;
for the ministers of Jesus Christ, who truly followed him,
were free from pride and avarice, and preached the gospel freely,
as Christ their Lord and Master required of them;
but so do not our proud and covetous priests.

We had another meeting at the house of our friend Isabel Barnet, in Lynn,
in a large parlour, at which the said William Falconer`'s 7th question was entered upon,
about water baptism, and what he termed the Lord`'s supper;
esteeming both standing ordinances of Jesus Christ, till the end of the world,
according to his question before cited, which he affirming,
it required proof on his part.
I being upon the negative, he accused me with denying all ordinances, which was not true,
nor truly inferred against me from my reciting Col. 2:20-22;
"`If you be dead with Christ from the rudiments of the world,
why as though living in the world are you subject to ordinances?
Touch not, taste not, handle not, which are all to perish with the using,
after the commandments and doctrines of men.`"
This instance could not be a denial of all ordinances,
nor of any that are standing in force, and to continue by divine appointment,
and the dispensation of the new covenant, which consists not in carnal ordinances,
or human institutions or impositions, nor yet in things elementary, typical or shadowy,
but is a dispensation of spirit, life and substance.
Christ was ordained and appointed of God to be our High
Priest and minister of this new and everlasting covenant.

William Falconer alledged Matt. 28:19, and Acts 10:47,
for water baptism being an ordinance of Christ to continue to the end of the world;
thereby he fell short, though he used the Baptist`'s plea for his proof,
yet his practice and theirs differ, in their baptizing believers, as they esteem them,
and his sprinkling infants.
But in reply to those Scriptures pleaded,

[.numbered-group]
====

[.numbered]
1+++.+++ There is no water mentioned in the first; "`Go therefore and teach all nations,
baptizing them in, or rather into, the name of the Father, and of the Son,
and of the Holy Spirit.`"
Here is no water mentioned; their gospel ministry was a spiritual, powerful,
baptizing ministry, even into the name, power and spirit of our heavenly Father,
and of his Son Christ Jesus, and his Holy Spirit; for as said the apostle,
"`Our gospel came not unto you in word only, but also in power, and in the Holy Spirit,
and in much assurance.`"

[.numbered]
2+++.+++ Neither will Peter`'s questions or command to those Gentiles,
mentioned in Acts 10:47-48,
prove water baptism a standing ordinance of Christ to the end of the world;
water baptism being John`'s baptism, decreasing and giving place to Christ`'s baptism,
and being condescended to in the church`'s infancy,
to show a respect to those believing Gentiles, as well as to the Jews;
all this proves it not an ordinance of Christ, nor its standing to the end of the world.

====

Neither was water baptism included in Paul`'s commission, as William Falconer affirmed,
for Paul declares the contrary; "`For Christ sent me not to baptize,
but to preach the gospel;`" nor will these words bear such a construction,
as that baptism was not the principal thing he was sent for,
as William Falconer construed them.
Paul did not say, Christ sent me not only to baptize, but also to preach, but positively,
"`Christ sent me not to baptize,
but to preach the gospel,`" This was the general and plain reason he gives,
why he thanks God he baptized none, and no other of them but Crispus and Gaius,
and the household of Stephanus: his particular reason was, "`Lest any should say,
that he baptized in his own name.`"
But his general reason is more extensive; "`For Christ sent me not to baptize,
but to preach the gospel.`"
Certainly if he had had a commission to baptize as well as to preach,
he would not have denied his commission, nor have thanked God for his neglecting,
or not performing it but to so very few,
far short of the number of those he preached unto: this in substance I insisted upon.

It may therefore be rationally concluded, first, That if Paul was not sent to baptize,
that is with water, but to preach the gospel, the commission the other apostles had.
Matt. 28:19, does not include or intend water baptism,
for Paul`'s commission was as large and comprehensive as the rest had;
he had the whole counsel of God to declare, not being behind the chiefest apostles.
Therefore his complying to baptize a few at Corinth,
must needs be rather in condescension, than by a commission from Christ.

But what insincerity or hypocrisy is it,
for any of these ministers or priests to use the arguments of those called Anabaptists,
for water baptism to continue in this gospel day, from Matt. 28:19, and Acts 10:47,
when thereby they do not mean that which is the real baptism of water,
but sprinkling the faces of infants with a little water,
when they know that sprinkling is rantism, and not baptism.

Thus my opposer at last argued for infants`' baptism, so miscalled, saying;
That as the promise was to Abraham and his seed,
so all infants of believers are as visibly the members of the church,
and have right to the outward privileges of the gospel covenant as their parents,
and therefore have right to water baptism,
as all the seed of Abraham had to circumcision.

This is an old, worn and torn argument, still imposing without any Scripture proof,
either that sprinkling infants is real baptism,
or that it is a privilege of the gospel covenant,
or that Christ has set it and enjoined it in the room or place of circumcision,
as if that were a type of sprinkling infants.
But we have no Scripture proof for any of these,
or to ascribe any of these to that human tradition of rantism on infants`' faces,
both of male and female; whereas it was only the males of the seed of Abraham,
which were circumcised: how then did circumcision typify this infants`' baptism,
as it is miscalled?

When 1 Cor. 12:13 was instanced,
that it was the baptism of the spirit by which true
believers were baptized into the church,
William Falconer said that referred to water baptism,
yet confessed there was both an inward baptism of the spirit,
and an outward baptism of water,
whereby they were baptized into the church or body of Christ,
thereby adding to the express words of the text;
"`We are all baptized by one spirit into one body.`"
He does not say we are all baptized by two baptisms,
that of water and that of the spirit into one body.
Therefore the one saving and uniting baptism is that of the Spirit;
as there is one body and one spirit, so there is one Lord, one faith, and one baptism: Eph. 4:4-5.
Here are no more baptisms than Lords.

Concerning their sacrament of bread and wine, as their terms are,
called the Lord`'s supper,
he said that the passover was not included in the Lord`'s supper;
which was expressly contrary to plain Scripture.
The passover was prepared or made ready as Christ required his disciples,
which he and they did eat at his supper; Luke xxii.
Mat, xxvi.
And it appeared to be the principal part of his and their last supper,
at the feast of the passover, which was a legal feast, supper and type,
fulfilled and ended by Christ.

We proceeded not far upon this point, our friend Thomas Briggs being with me,
gave a powerful testimony to Christ, as being the bread of life from heaven,
the substance and end of the shadows,
and who gives life and nourishment to the immortal soul.

When we had discoursed but a short time upon this subject,
a discomposed man stood up in the meeting, which was crowded,
and made a hideous noise and was clamorous,
which put the people into a great disturbance and uproar,
many being surprised and frightened with the clamour he made,
and the uproar he occasioned.
William Falconer, the priest himself, appeared sorely amazed and frightened,
so that he was past disputing against the Quakers,
and great care was taken by some of his hearers to
get him safely conveyed out of the house,
for he was glad to be gone;
so in a little time they crowded him out of the meeting and house,
and he went out of doors trembling,
having a friend of ours--who told me--by the hand as he went out.

The man that made the disturbance in the meeting, did, in like manner,
make a disturbance at the other meeting which I had in the chancel with John Horn;
upon which Thomas Moor unjustly reported,
that it was the fruit of George Whitehead`'s ministry, when the contrary was well known,
that my ministry was, as it still is, the ministry of the gospel of peace,
tending to turn people`'s minds from darkness and distractions to the true light,
and to settle them therein, to wait upon God without distraction.

Although that turbulent person had been partly convinced of the truth,
and for some time came to our friends`' meetings,
yet not keeping his mind low and humble, in the measure of light given him,
to feel and understand the power and spirit of Christ
to work in him unto sanctification and self-denial,
he grew conceited and exalted in his imaginations;
and setting up a righteousness and making a cross of his own,
he would thereby make himself more righteous than all other Friends,
and a judge over all,
until the enemy of his soul prevailed to hurry and disorder his mind and spirit,
so as from his getting into a self-righteousness and singularity, he ran into confusion,
vain and distracted imaginations, and turbulent behaviour; though I question not,
he was not without sufficient and seasonable instruction and warning to the contrary.

I had early drawings in spirit to visit the city of Norwich, and county of Norfolk,
in the year 1654, and among other places in the same county, to visit Buckingham,
Gissing, and Pulham-side, in which parts I believed the Lord had a people to bring forth,
as it afterwards came to pass.
And hearing of one Thomas Benton, a noted teacher or pastor,
of an Independent people about Pulham, I believed that some, if not many,
of them would be gathered from among them, out of their formal profession and worship,
unto the light, life and power of God, and of Christ Jesus.

At a certain time being informed that the said Thomas
Benton was to preach at a lecture at Diss,
in Norfolk, in the spring time, in the year 1655,
a weight came upon me to go to the steeple-house, my dear friend Robert Duncon,
accompanying me, and I stayed there and heard him until he had ended;
and then I was moved to call to him and tell him, You are weighed and found too light.
And so he was proved upon further trial afterward, as I am about to relate.

He seemed to be somewhat stirred and offended at my speaking to him,
and prepossessed against the people called Quakers,
by some priest`'s book out of the north; as I remember,
it was styled The perfect Pharisee under monkish holiness:
set out by the priests of Newcastle.
However, I was quickly pushed out of the steeple-house by his instigation;
but then I got upon a tomb or grave stone, and preached the truth in power and plainness,
showing the barrenness and fruitlessness of the people under such ministers,
and their dead ministry;
and how the vineyards of such vine dressers were grown over with briars and thorns;
and what cause they had to howl and lament.
The people heard me quietly for a pretty space; but some rude persons,
after I stepped down, would have set me in the stocks; but others,
one whereof was the schoolmaster, prevented them.
I had a good time then to clear my conscience.

Above four years after that, I obtained a public meeting with the said Thomas Benton,
at his parish church, as it is called, at Pulham,
which was on the 4th day of the eighth month, 1659.

The chief points of our controversy were about the light within or in man,
and ministers taking tithes of their hearers in this gospel day; the first I vindicated,
i+++.+++ e. the light of God and Christ in man; the second I opposed, i. e. tithes, etc.

The first question propounded to Thomas Benton to be discoursed on was,
whether every man in the world be enlightened with a spiritual light, yes or no?

His answer was, that he denied that every man is enlightened with a spiritual light;
but with a natural light,--as the light of reason, creation light, or the like;
yet confessed that every man is enlightened by Christ as a Creator,
but not as a Mediator.

Herein his inconsistency was apparent,
for if every man be enlightened by Christ as Creator,
then is every man enlightened with a spiritual, divine light; for as Christ is Creator,
he is a divine, spiritual Light, and the fountain of light, for God is a spirit,
and light also, in whom is no darkness at all.

Nevertheless, Thomas Benton confessed that the word enlighten, is with a light within,
in the soul, but that he could not fully interpret that Scripture, John 1:9.
Wherein he showed some ingenuousness in confessing his shortness.
And it may be observed,
he did not demonstrate from Scripture his distinction
of two such different lights in men,
as one from Christ as Creator, that is only natural in all men; and another light,
which is spiritual, from Christ as Mediator, only in some men.
Christ himself speaks more plainly and generally; "`I am come a light into the world,
that whosoever believes on me should not abide in darkness.`"

But to render the light of the Creator natural, or natural reason,
and the light of Christ spiritual, is not only to divide the light, which is one,
but to set the light of the Mediator above the light of the Creator.

John the evangelist testified of Christ the Word, that was with God and was God,
that he was the true Light, which enlightens every man that comes into the world;
and that in him was life, and the life was the light of men; John 1:4,9.
This life of the eternal Word,
is above any natural light or natural reason,
for it is a divine principle of life and light.

And, "`God who commanded the light to shine out of darkness,
has shined in our hearts;`" for what end?
To give us the light of the knowledge of the glory of God, in the face of Jesus Christ:
2 Cor.
iv. Therefore, before we have that knowledge or degree of light given,
God shines in our hearts to give it unto us:
and still it is the light and glory of one and the same God and Christ Jesus,
gradually revealed and made known in us.

Moreover we ought to consider, that Christ, as he is God and man,
does not act or give spiritual gifts separately from God the Creator,
whether they be light, grace, spirit, power or wisdom; for Jesus Christ,
when he speaks as man, or as Mediator, always gives preference to the heavenly Father;
as when he says, "`The Son can do nothing of himself, but what he sees the Father do:
and my Father works hitherto, and I work,`"

And likewise, what power, glory, spirit, life, light and wisdom,
the Son has to give or impart unto men, especially unto true believers, his followers,
it is all first given him of the Father.
He received gifts for men; yes, for the rebellious also,
that the Lord God might dwell among them; Psalm 68:18.
Of whom did he receive them, but of his heavenly Father?

As our heavenly Father and his dear Son are not divided,
no more is their light--it is one individual light and life;
the fulness whereof dwells in Christ the Son of the living God,
in whom it pleased the Father, that all fulness should dwell; Col. 1:19.
And to give all power in heaven and earth unto him; Matt. 28:18.
Although unto every one of us is given grace,
according to the measure of the gift of Christ; Eph. 4:7.
What he has of light and grace in fulness,
who received the spirit not by measure, but in immensity or immense fulness,
he gives to us by measure, and the knowledge thereof gradually,
if we be sincerely obedient to his gift.

The said Thomas Benton also affirmed, that if those Gentiles mentioned, Rom. 2:14,
had improved that light to the utmost which they had,
it had not been sufficient for them unto salvation.
This still is relative to his mistaken notion,
that they had only a light from God the Creator, but not from Christ the Mediator,
which appears contrary to the text, Rom. 2:13-15,
For both Jews and Gentiles were all to be judged, even the secrets of men,
without exception, by Jesus Christ, according to the gospel; verse 16.
But if they should be judged and condemned,
either because they had not a sufficient light given them of God to save them,
or no gospel light by Jesus Christ, to improve unto salvation;
this were to render God and Christ both unmerciful and unjust judges.
What! judge and condemn men for not improving, or not obeying a light, law or gospel,
which they never had, nor might have, if not given unto them?
Or when they made the best improvement they could of that light given unto them,
yet for all this, to fall short of salvation,
and consequently to be judged unto condemnation.
O! unmerciful and cruel, and contrary to common justice among men;
and surely such doctrine cannot be according to the
gospel of the free grace of God in Jesus Christ;
but rather agreeable to the partial, narrow notion of predestinarians, and such as would,
by their doctrine, limit and confine the grace and love of God,
only to a small select number of mankind.

Such partial opinion is manifestly repugnant to the free and universal love of God;
with whose great love his dear Son Jesus Christ, was so fully replenished,
that he was well called the Son of his love;
which he has so freely and universally extended unto the world,
according to the good will of his heavenly Father,
in all the good he has done and given to the children of men;
and therefore the love of Christ testified of in holy Scripture,
is truly the love of God in him to us all.

And if God spared not his own Son, but delivered him up for us all;
how shall he not with him, also freely give us all things? Rom. 8:32.

Jesus Christ showed his own and his heavenly Father`'s great love to all men,
as he is the light of the world, and given for a light unto the Gentiles,
and to be God`'s salvation to the ends of the earth; and also in his dying for all men;
by the grace of God tasting death for every man; giving himself a ransom for all men,
and in making intercession both for transgressors and for the saints;
also according to the will of God, even in heaven itself,
he appears in the presence of God for us;
and also by his Holy Spirit in all true believers: his Spirit makes intercession,
helps our infirmities, moves and assists us in prayer.
They who are sons of God,
are sensible that he has sent forth the Spirit of his Son into their hearts, crying,
Abba Father; Gal. 4:6.

The humility, mercy and condescension of Jesus Christ, our blessed Mediator, are such,
that he is touched with the feeling of our infirmities, weaknesses and temptations,
and ready to succour, help, and relieve all them that are tempted,
even by his grace and good Spirit,
in their drawing near to the throne of his mercy and grace.

O faithful Creator, O King of saints, O merciful High Priest, O compassionate Mediator,
let your light and your truth shine forth more and more,
to the glory of your great and excellent name and power,
and expel the great darkness of apostacy that has
covered many nations and professions of Christianity,
and greatly appeared in these latter times against your light, your truth and people,
whom you have called and delivered out of darkness into your marvellous light.
Glory and dominion be to your great name and power, forever and ever.

To return to the matter in controversy: my opposer Thomas Benton,
affirmed that it was a corrupt nature by which those Gentiles--mentioned
in Rom. 2:14--did those things contained in the law,
which he confessed was the moral law, or ten commandments.
Herein the man was as far out as in the rest of his mistakes;
for who can bring a clean thing out of an unclean?
Do men gather grapes of thorns?
Or can an evil tree bring forth good fruit?
No sure; no more could those Gentiles by a corrupt, unsanctified nature,
do those things contained in the righteous law of God;
which requires sincere and entire love to him,
and true love to our neighbours as to ourselves.
If by a corrupt nature, this law may be performed, by what nature is it transgressed,
where men neither love their Creator nor their neighbours?
The opposer did not well consider the text, Rom. 2:14,
nor the state of those Gentiles, who did by nature the things contained in the law;
whom the apostle does instance in justification; verse 13.
Though they had not the law, i. e. in the letter,
they had it in the spirit, even in their hearts.
And what was the work of "`the law in their hearts, being written therein?
Surely it was a sanctifying work in them, from which their performance proceeded.
The`' law of the Lord is perfect, converting the soul; Ps. 19:7.
Therefore their performance of those things contained in the law of God,
was not by, or in, a depraved nature, but in a converted, sanctified,
or reformed nature and state.

Other gross mistakes and errors were at that dispute committed by Thomas Benton, as,
that those mentioned, Rom. 1:20, saw the invisible things of God by a natural light;
and that natural men might clearly see the eternal power of God as a Creator,
but not Christ as a Mediator.

Herein his mistake is notorious; for the invisible things of God there mentioned,
are his eternal power and deity, or Godhead,
and they who understood and saw them from the creation,
were of those Gentiles who knew God, and yet liked not to retain him in their knowledge,
but became vain in their imaginations, whereby their foolish hearts were darkened;
and so they became miserable apostates.
The sight and knowledge they sometimes had of God and his eternal power,
was not by a natural light or knowledge; but by a spiritual divine light,
given them of God; and their knowledge they had of God,
and their understanding and sight of his invisible things,
originally sprang from a divine principle in them; seeing,
that which might be known of God was manifest in them,
for it was God that showed the same unto them; Rom. 1.
Insomuch that they themselves were without excuse in their declension from the same.
For it is plain, that the natural man neither receives,
nor can know the things of the spirit of God, they being spiritually discerned; 1 Cor. 2:14.
And surely vain by nature are all men who are ignorant of God,
and cannot know him, that is, by the good things that are seen, Wisd. 13:1.

Men must be changed and renewed in the spirit of their minds, in some measure,
before they can clearly see or know the invisible things of God, or of his spirit.
It is not by the spirit of this world, nor by the wisdom thereof,
nor yet by any mere natural light, that those things of God,
which he has freely given unto us, are made known unto us, but by the Spirit,
which is of God; 1 Cor.
ii. Which Spirit being obeyed, we follow God`'s teachings and drawings thereby,
and shall not fall short of the knowledge of Christ our Mediator,
nor be deprived of the great benefit or fruit of his mediation; who said,
"`Every man that has heard and learned of the Father, comes unto me.`"
And Christ Jesus the Son of God, being the way to the Father;
"`No man comes unto the Father but by him.`"

Again, our adversary`'s doctrine reflects upon God,
and in effect charges him with injustice, as requiring an impossibility of men;
in his saying that, all men may believe in Christ, if they will or can;
but all men have not power; "`As, said he, I may travel a hundred miles before night,
but I cannot.`"
Yet men are reproved and condemned for the sin of unbelief,
because they believe not in him, i. e. Christ, whom God has sent.

But how will it stand either with the mercy or justice of God,
to reprove men for a sin they cannot avoid, or for not believing in, or obeying Christ,
if they have not light or power given them to believe and obey when they are willing.
But it is their sin if they will not; as it was their sin and rebellion,
who would not be gathered by Christ, nor come unto him that they might have life,
when they might have come at his call,
who gives men both light and grace to persuade and enable them to believe and obey.
It is the work of God to believe in his Son Christ Jesus; but it is our act of obedience,
we must be exercised in this work of God, in the obedience of faith.
With the heart man believes unto righteousness;
otherwise it is unrighteous to charge God with condemning men for their unbelief,
if he did not give them light and grace, or power to believe.

And as unjust and erroneous doctrine it is, to teach, that where Christ said;
"`God sent not his Son into the world to condemn the world,
but that the world through him might be saved;`" that by world here,
is meant only the number of believers,
which is a manifest perversion of Christ`'s testimony in this place;
for God sent his Son into the world of unbelievers and sinners,
to call them to repentance, and he called such to repent and believe the gospel; Mark 1:15.
Christ is the author of faith;
he comes to work faith in the hearts of people by his light and grace;
the world are not believers until he works faith in them.
Shall he find faith on earth when he comes?
No sure; he finds men unbelievers.
It would be injurious to Christ`'s words, and impertinent to turn and limit them thus:
God sent not his Son into the world of believers, to condemn the world of believers,
but that the world of believers through him might be saved.
Christ`'s testimony is more general,
and an indication of the universal and free love of God to mankind,
where he likewise says in the place mentioned, John 3:16; God so loved the world,
that he gave his only begotten Son, that whosoever believes in him, should not perish,
but have everlasting life.
He does not say here, that this is only the world of believers,
or the world of the elect, as some of these partial, narrow spirited,
pitiful preachers have done.
But this is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil; John 3:19.
Surely he did not mean the world of believers,
that this is the condemnation of the world of believers,
or that believers loved darkness rather than light; no surely;
for they are children of the light, they all love the light, they walk in the light,
and bring their deeds to the light, who are true believers, and children of the light,
and of the day.

[.discourse-part]
_The second question:_ Whether he be a true minister that takes money, gifts or tithes,
for preaching?

[.discourse-part]
Answer.
I deny that he is.

[.small-break]
'''

To which question Thomas Benton replied,
that ministers may take money or tithes for maintenance,
for the labour of preaching the gospel.
Yet that he claims not tithes by a divine right, but yet for aught he knew,
they belong to the priesthood of Christ the antitype,
because they were received by Melchisedeck in the type.
But herein he was not fully resolved or clear,
for he desired to receive more light from George Whitehead in it.

Thus it appeared in those days, how ready some persons who pretended to be gifted men,
and to a reformation above the parish priests, were to lay hold of their profit,
gain and revenues, by tithes or otherwise,
so as their avarice might be answered and satisfied.
And seeing such persons who were not bred up to the priesthood, but were tradesmen,
some of the inferior sort, as butchers, tailors, weavers, etc.,
yet pretending to be gifted by the Spirit,
were set up by the seeking people to be preachers in their pulpits,
like priests in some parish churches, so called,
chiefly because they made them believe they were spiritually gifted,
and had not their ministry by human learning at universities;
and honest-minded people were betrayed and misled by such pretenders,
to set them up and promote them,
until they became as corrupt and covetous as the parish priests;
and then they would evade Christ`'s command to his ministers,--"`Freely you have received,
freely give;`" and his ministers`' example agreeably thereto.
A free ministry would not be allowed by such mercenary ministers,
when the people had promoted them for their pretended gifts,
many then having a secret belief,
that the Spirit`'s teaching and gifts were not all ceased; upon which their selfish,
mercenary teachers took advantage to get into preferments.
Then tithes and forced maintenance became acceptable, though not jure divino;
that divine law and right the priesthood of Levi had--requiring
tithes and oblations--being abolished and ended by Christ,
according to the 7th, 8th, 9th, and 10th chapters of the Hebrews.

Although tithes be granted to be typical, being received by Melchisedeck in the type,
yet now, quoth Thomas Benton, for aught he knew,
they belong to the priesthood of Christ the antitype.

How can that be, when they cannot be claimed by a divine right,
according to his own confession;
but if in the antitype they belong to Christ`'s priesthood,
then that must be jure divino.
But for that we have no Scripture proof,
no more than for turning a type into an antitype, as this my opposer seemed to do,
in making tithes that were a type in Melchisedeck`'s receiving them,
the antitype in Christ`'s priesthood.
If he could thus turn types into antitypes,
he might as well turn legal shadows into gospel substances.

But his instance of Melchisedeck`'s receiving tithes of Abraham,
being the tenth of the spoil taken in war,
will not parallel or warrant the case of tithes as now it stands.
It is not that sort of tenths the priests now take,
but of the choicest fruits of the earth, corn and cattle, pigs, geese, wool, and lambs, etc.
Then I showed Thomas Benton that, although Melchisedeck was a type of Christ,
his receiving the tenth of the spoil taken in war, which Abraham freely gave him,
is no ground for priests now taking those tithes they do,
nor any warrant or proof for Christ`'s ministers to take tithes of any sort,
either of spoils or otherwise.

When I answered Thomas Benton to this purpose, he replied thus: "`George Whitehead,
your answer is like his who was asked how many miles it was to London?
and he answered, a pope full of plums;`" whereby he showed his levity and impertinency.

When he could not maintain his claim to tithes, as due to the priesthood of Christ,
by Scripture or divine right, then his chief plea was,
that the tenths were never the people`'s, which is not true,
but given the ministers by the magistrates or state;
and that if the people will be so base, that they will not maintain their ministers,
then they are to be forced by the law to do it.

It was not the practice of Christ`'s faithful ministers to force maintenance from people;
neither coveted they any man`'s money or gold, food, drink, or apparel,
but preached the gospel freely, without making the same chargeable,
being under a necessity, which Christ laid upon them, to preach the gospel.
Yet they were allowed and had power to eat and to drink,
and to be relieved by such as were worthy to receive them;
and also to reap where they had sown, for their necessary relief,
but not to compel or force maintenance from any, whether unworthy, base, or worthy;
but the worthy need no compulsion to be charitable and kind,
especially to their friends and brethren.
And for such as are base and unworthy, who reject Christ`'s ministry,
both they and theirs are rejected; and no more credit can any priests gain,
by compelling tithes or maintenance from such as they deem base and unworthy,
than by persecuting those who are none of their hearers,
because they cannot for conscience sake follow them,
nor sit under their fruitless ministry.

Yet Thomas Benton blamed our friend Richard White, and accused him of unrighteousness,
for detaining tithes from the priest that sued and persecuted him for the same,
when it was known Richard was then no hearer of the priest`'s;
he had no work done by him,
therefore the more unjust in the priest to demand wages of such for whom he did no work.

As for Richard White, he was well known;
he received the truth in true love in early days,
among the first stock of our friends in High Suffolk;
and because for conscience sake to Christ Jesus,
and with a true regard to the gospel and new covenant dispensation,
he refused the payment of tithes, and denied that priesthood that takes them,
and yet pretend to be Christ`'s ministers; he suffered long imprisonment in Ipswich jail,
and otherwise, wherein he bore a faithful testimony for Christ Jesus,
and the truth of the gospel.

Our meeting and dispute ended peaceably, and the eyes of many were opened,
to see the corruption of such ministers as opposed the light of Christ in man,
and the universal grace of God to mankind,
and pleaded for tithes and forced maintenance for preaching.

When it pleased the Lord to send some of us,
his faithful servants and ministers among them,
who were really partakers of his spiritual gift and ministry,
many honest-minded people in those parts left those ministers,
who under pretence of being spiritually gifted, grew selfish, corrupt and covetous,
preferring their gain to godliness, and gathering to themselves, and not to Christ Jesus,
nor to his light, grace, or spirit, in their hearts.
Many serious people even in those days came out from among those self-exalted ministers,
teachers and priests, and were turned to Christ, their light,
and he became their Minister, High Priest, and Pastor:
to whom be glory and dominion forever.

A short time after the said public dispute at Pulham,
Robert Duncon and I went to visit Thomas Benton at his house,
where we had some moderate discourse,
and I endeavoured to inform his understanding in some weighty matters of Christianity,
at which he seemed not offended, but rather friendly,
and accordingly we parted peaceably.

After which, for his further information,
I wrote a brief answer to those points in controversy at our public dispute,
to remind him of his deficiencies and inconsistency in several points;
and in the conclusion of my answer, I wrote him the following lines:

[.embedded-content-document.letter]
--

[.salutation]
Thomas Benton,

Where is your equity or righteousness?
Who would have a priest take tithes of such as he does no work for, nor are taught by him?
Surely if you did hearken to the equal and just principle in you,
it would teach you better lessons than this you have taught;
but from that principle you are erred.
And this I must tell you, since you are got into the old, dirty road of the priests,
and are not only a partaker with them, of their covetous practices,
but a preacher up thereof, you are grown as dark as they are, upon whom the sun is set.
You have lost the sincerity of the truth, that has been in times past stirring in you;
for now many of the honest-hearted begin to loathe your covetousness and hypocrisy,
for which the Lord will judge you; dryness and withering are already come upon you.
Remember from where you are fallen, and consider your sad apostacy,
if happily you may find repentance.
From a friend to your soul,

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
The 8th of the Eighth month, 1659.

--

One James Bedford, priest of Bluntisham and Erith in Huntingtonshire,
having made a great boasting and clamour against the people called Quakers,
to render them ridiculous and odious,
some of our friends had some public discourses with him, in order to abate his clamour,
yet notwithstanding he persisted in his reviling and ostentation against us,
as if he could refute and run down the Quakers.
At a dispute which our dear friend, John Whitehead, had with the said priest,
at the steeple house at Haddenhain, in the isle of Ely, where I was present,
but did not much interpose, the appointment being between the priest and John,
I observed the priest to be a mere empty, confident boaster and reviler,
and made but poor work of it.

The dispute being over, the priest went to justice Castle`'s in the town,
and I went there after him, in order to have some discourse with him before the justice,
which I obtained, and discovered his ignorance,
of which the justice was made sensible in some measure;
yet seemed a little to speak in the priest`'s favour, but could not vindicate him.

Nevertheless the priest continuing a boasting, clamorous adversary,
and being a notorious persecutor of our friends for tithes;
it was desired by some Friends that I might have a public meeting with the said priest,
to dispute with him; and also I understood that our dear friend and brother, George Fox,
senior, was desirous that I should meet him.
After serious consideration thereof,
I found the Lord gave me freedom to meet this priest publicly,
whereupon I wrote him a few lines,
importing my willingness or desire to meet him at his own parish church, so called,
on a certain day mentioned in my note.

But to divert my intention and disappoint me from
meeting him on the day that I had pitched upon,
the priest craftily appoints another day: the 14th of the twelfth month, 1659-60,
whereon he understood, being told,
that I was engaged to be at a meeting at Cottenham in Cambridgeshire.
The priest by his note, published in Ives market the day of his own appointment,
pretending that he and George Whitehead were to have
a dispute that day at Bluntisham church;
though he did not expect I should meet him that day,
knowing that I was otherwise engaged in Cambridgeshire, if the Lord pleased;
that being always the condition of my appointments aforehand, to be at meetings;
I used to write, or say, if the Lord will, I intend to be at such a meeting.

Having notice of the priest`'s fraudulent appointment,
the day before that which he had appointed, and my dear friend John Crook,
being then with me in Cambridgeshire, I entreated him to ride to Erith or Bluntisham,
the next morning, and the Friend that gave us notice thereof to go with him,
being about eight or nine miles, and that John would excuse me to the people, when met,
and show them how the priest had circumvented me, as to the day and time of meeting;
that day he had appointed not being agreed upon,
and I otherwise pre-engaged to another meeting.

John and the other Friend willingly took horse and rode to Erith, and I to Cottenham,
in order to be at the meeting appointed for me; but when they got to Erith,
they considered or understood the priest would take
great advantage and insult over Friends,
if I did not meet him that day, and pretend I was afraid to meet him,
which was far from me.

Whereupon John Crook and the other Friend immediately took horse again,
and came to me at Cottenham before the meeting there was begun,
and told me the necessity of my going to meet the said priest that day,
on the considerations before mentioned, it being then near-mid day,
and John said he would stay that meeting at Cottenham in my stead.

I forthwith took my horse, and the said Friend with me,
and we hastened to Erith and Bluntisham, about five miles, and quickly got there;
and I was in the steeple house about half an hour before the priest came,
and sat down quietly in a pew.
When he came in with his books or tools, to make a noise against us,
smiling and bowing toward the people, I only looked at him,
and sat down again quietly in the pew.

The priest mounted the pulpit like some conqueror;
and not expecting antagonist or combat, vauntingly called for George Whitehead.
I sat still a while, being out of his sight, to hear how he would boast or insult.
He called over and over, "`Where is George Whitehead?`"
At last Henry Foster forwardly answered, "`He is here;`" thereupon I stood up and said.
Here I am;
but the priest would not own that I was the George Whitehead that was to meet him.
I saw then he was surprised, being disappointed in his fraudulent design;
yet still he questioned as if he would have shuffled me off, or shifted disputing;
saying, "`You are not Whitehead, though you have a white face.`"
Justice Castle being present, said; "`Yes, he is the man; Mr. Bedford, look to yourself.`"

Seeing the priest so vain and trifling in his talk, before he would enter into dispute,
I called to him.
Leave your babbling, and let us come to matter.

Then the priest took out his watch and laid it before him,
and proposed for each of us to declare one quarter of an hour at a time, and not exceed,
and he would begin first; and I should have the like time to answer.
I told him I should not be limited to a quarter of an hour,
perhaps I might answer him in less time;
but if what he alledged against us required more to answer,
I ought to have time`' allowed accordingly.
I did not know but in a quarter of an hour he might accuse us with so many particulars,
as might require more time to answer.
However, he would keep to his quarter of an hour, as he pretended.

Then he began to read various accusations and perverse stories out of a book or books,
against the people called Quakers, written by some invidious adversaries,
priests or others,
and with contempt and derision he descanted upon what he read against the said people.
The heads of his accusations are abstracted as follows.

James Bedford manifested his ignorance and irreligious frame of spirit,
by scoffing at quaking and trembling without distinction,
judging the same to be of the devil.
He derided the Quakers`' silent meetings, terming the same a ridiculous foppery.
He falsely accused the Quakers with treading under foot the Word of God,
which was for their confessing Christ to be the eternal Word, which was in the beginning,
and not the Scriptures.
He affirmed that all the Scriptures,
from the beginning of Genesis to the end of the Revelations, is the Word of God;
and that the devil`'s words recorded in Scripture, are the Word of God.
He denied that every man is enlightened with a spiritual light; and affirmed,
that the light within led men to murder; his proof was, John 16:1-2. And Paul`'s,
instead of Saul`'s, persecuting the saints.

Having made some scornful reflections upon these accusations,
until his quarter of an hour was out, I gave answer in brief, to the following effect:

His accusation and judgment against quaking and trembling,
appeared grossly erroneous and blasphemous,
for many of the servants of the Lord did tremble and quake at his powerful word; see Isa.
Ixiv.
2, and Ixvi.
2, 5, Job 21:6, Jer. 5:22, and xxxiii.
9, Ezek. 12:18, Heb. 3:1,16 Cor. 2:3, Phil. 2:12.

He also derided the practice of many of the Lord`'s people and servants,
who kept silent and met in silence, waiting upon the Lord;
first to hear him speak and minister to them,
and to endue them with his power and spirit, before they spoke or ministered to others;
see Jer. 8:14, Lam.
iii, 28, Hab.
ii, 20, Zech.
ii, 13, Isa, xli, 1, Luke xxiv, 49.

The Quakers confessing Christ the Son of God, to be the Word which was in the beginning,
before the Scriptures were written, cannot be any treading under foot the Word of God;
for the holy Scriptures testify the same.
See John 1:1, Rev.
xix.

He was greatly out in affirming all the Scriptures--which
are writings--to be the Word of God,
without making any exception; for though the Scriptures contain the words, doctrines,
commands, divine precepts, and faithful sayings of God and of Christ;
yet the Scriptures themselves make distinction between
these and the devil`'s words and sayings,
and blasphemies of wicked persons, which are also historically recorded in Scripture;
and therefore it is blasphemy to call the devil`'s words the Word of God.

His denying a spiritual light to be in every man,
is contrary to the holy evangelist`'s testimony of Christ the true light, etc.;
John 1:4,9; and in his affirming that the light within led men to murder and persecute,
from John 16:2, he puts dark and murderous, persecuting thoughts,
enmity and madness of persecutors for the light,
and consequently he puts darkness for light;
whereby this priest showed himself in great darkness.
See Isa. 5:20.

When I had made my first defence, and refuted the priest`'s invectives,
justice Castleton saw he could not stand to maintain his cause against us,
and went his way before the debate or meeting was ended;
concluding the priest had enough, as I was told, seeing he could make no reply,
but took care to stop me when the quarter of an hour was ended; calling to me,
"`Will you break faith and truth?`"
But he rambled into many other accusations and impertinent stories against the Quakers,
wherein he exceeded his quarter of an hour, and took up much more time.
His chief complaint against the Quakers was, that a Quaker called him a beast,
and he took up some time to prove himself no beast.

Seeing he had broken his faith and truth by so much exceeding
his own appointment of a quarter of an hour,
I several times called out, and desired I might be heard;
but he went on in his rambling and reviling discourse,
and would not allow me to be heard, to give answer,
until the people grew impatient and disturbed at his tedious impertinences,
and called out several times, "`Pray, Mr. Bedford, hear him, or allow him to answer.`"
He would not regard them for some time, but went on with his ramble and clamour,
complaining against the Quaker that called him a beast.

I told the people, if I might be heard, I would prove him a beast;
at which the people--some of his chief hearers--were
the more earnest to persuade him to be silent,
that I might be heard prove him a beast;
but he eagerly strove to hold on in his prating against the Quakers,
on purpose to take up the time, and prevent me;
so that some of the people said he was mad, or they thought him mad;
but they prevailed at length with him to be silent,
that I might be heard prove what I had promised against him.

Whereupon I first proposed, that some men were termed beasts in Scripture,
i+++.+++ e. for several causes or crimes: and if I proved James Bedford guilty of the same,
or the like, then I proved him a beast according to Scripture.

Then to prove that some men or persons were termed beasts in Scripture,
I instanced Titus 1:10-12; There are many unruly and vain talkers and deceivers, etc.,
whose mouths must be stopped, who subvert whole houses,
teaching things which they ought not, for filthy profit`'s sake.
One of themselves, even a prophet of their own, said, the Cretians are always liars,
evil beasts, slow bellies.

Now if I prove James Bedford guilty of these evils,
for which these were called evil beasts, then I prove him such a beast as they were.

First then, it is evident to this auditory,
that James Bedford has showed himself an unruly and vain talker,
having taken up a great deal of time here in vainly talking and prating to no purpose,
without giving any reply.

That he teaches, or has taught things which he ought not,
in teaching that the light within led men to murder,
which is contrary to the light of Christ in man, and to holy Scripture;
+++[+++and no better than blasphemy against that light.]

That his teaching is for filthy profit`'s sake, is manifest by his covetous practices,
and his persecution for filthy profit, against such as dissent from him:
witness his and his men`'s taking away by force and violence, wheat, barley and pease,
in great quantities, as much as he and his men pleased, for tithes, from John Cranwell,
besides four lambs and wool, what his men pleased in quantity,
without account of the value; and also three cows with calf, and a cart and wheels,
in all amounting to 20 worth of goods, for 12 demanded.
And besides all this oppression and extortion,
he imprisoned John Cranwell in Huntington jail,
to show how legally he pretended to proceed,
when he had so arbitrarily and illegally proceeded by force,
to spoil and take away his honest neighbour`'s goods,
to gratify his own avarice and revenge against him.

Thus it was apparent this priest taught for filthy profit`'s sake,
such things as he ought not; consequently he was openly,
before his own hearers and others, proved a beast,
according to the sense of the apostle Paul, and the Scriptures of truth; and I may add,
that consequently he merited the character of an evil beast.

And when according to the preceding argument and instances,
I made proof of my charge against the said priest Bedford,
instead of making any reply or defence for himself, he quickly came down, fled away,
quitted the place, and left the assembly;
so that his former boasting and insulting was at an end,
as I really believed the Lord would stop his mouth;
for I felt the zeal of the Lord and his power with me at that time, as at many others,
in vindication of his blessed truth and people.
To the Lord our God, who stood by me, and has hitherto helped me,
I do ascribe the praise of all, and over all, blessed forever.

After the priest got away and left the assembly,
I had a very good and quiet opportunity to declare and demonstrate the truth,
and preach the gospel to the people, and all were peaceable;
and when I had thereby cleared my conscience to them,
I gave them public notice of a meeting I intended, if the Lord pleased,
the next day at the same town.
We all went peaceably out of their steeple-house, without any disturbance, affront,
or molestation; and the next day, according to appointment,
we had a very good and serviceable meeting in the town,
to which several men of account came.

After I had travelled and laboured some time in the work of the gospel,
in Cambridgeshire, Huntingtonshire, the isle of Ely, and some parts of Lincolnshire,
as that called Holland, etc., also in some parts of Northamptonshire,
I was much pressed in spirit to endeavour for a meeting in the city of Peterborough,
though I heard of no Friends there to receive me or our friends.
But upon inquiry, there was found a sober, honest-minded man, of reputation and quality,
who was willing to have a meeting at his house,
which accordingly was appointed to be on a first-day of the week;
I know not whether it was in the first or second month, in the year 1660.
It was in the spring time, and many Friends`' from adjacent parts resorted to it,
out of the Fens, and some out of Rutlandshire.

In the week before the meeting,
I had a great weight and sense upon my spirit that we should have some trial and exercise,
by suffering at that meeting,
being sensible of the great darkness and wickedness that was in that city,
though but a little one; and so it came to pass.
When our friends and I had begun to meet in the house,
the mob and rude people gathered about it, and in the yard,
in such a rude and turbulent manner, as if they were minded to pull down the house,
so that we thought it best to remove the meeting into the court yard adjoining,
being unwilling the honest man`'s house should be any ways damaged by that rude crew.
I was resigned in the will of Lord, rather to be given into their hands,
than that the family where we met, should suffer on account of the meeting being there.

After we had removed into the yard, I was moved to stand up on a stool,
and in the name of the Lord to preach the truth for some time, near an hour.
The Lord stood by me and strengthened me,
so that I was enabled livingly to declare the truth,
with a free resignation also to suffer what violence
or evil he should permit the wicked to do,
or inflict upon me;
for I had often before that time resigned life and liberty for the gospel`'s sake.

While I was declaring the truth, a tall man, who they said was an innkeeper,
with a rude company after him, rushing violently and furiously, came into the meeting,
aiming chiefly to pull me down.
The meeting being somewhat crowded, and several Friends in his way,
he could not readily get at me; in the mean time, others threw dirt and eggs,
thought to be rotten, at me, by which my head and face were greatly daubed,
yet I went on declaring the truth.
The furious man still striving to come at me, took up a stool by the feet,
and heaving it up to strike such as were in his way, a Friend standing by,
caught hold of the stool as he was making his blow, to prevent it;
yet he gave an ancient woman, a friend of ours, a blow with the edge of the stool,
on the side of her head, which made such a cut and wound on her temple, near her eye,
that it was thought if his blow had fallen directly on her head,
it might have beaten out her brains; but the Lord providentially prevented that.

The man`'s fury and rage seemed to be chiefly against me, and his struggle to get at me;
and rather than he should do more mischief, I desired the meeting to make way,
that he might come to me, for I was above the fear of any hurt he or they could do to me.
Then he and his company came and violently pulled me down,
and when I was in their hands I felt much ease in my spirit, being sensible the Lord,
who stood by me, was secretly pleading my cause with them,
so that their fury was immediately abated, and their spirits down,
and they were restrained from doing me harm.

They haled me out of the meeting, through part of their cathedral church, so termed,
there being a passage open near one end, and then they quickly let me go.

There were some soldiers, as it was said, of Lambert`'s, or the old army,
then quartered in Peterborough, who were spectators,
and beheld how I and others of us were treated and abused at the said meeting.
Some of them took compassion, and had us to one of their quarters,
where I got to the pump, and washed the dirt off my face,
but could not then wash my head, to get my hair clean.

Some Friends with me, were then directed into an upper room in the inn,
where we sat together, waiting upon the Lord for some time, I think near two hours,
and the Lord comforted and refreshed our spirits,
and he put it into my heart to return again to the same house,
from which I had been haled away out of the meeting.
Several sober people were gathered there in the afternoon,
and I had a good meeting and service for the Lord,
in bearing testimony for his blessed truth among them; and we held the meeting quietly,
and parted peaceably, without molestation.

That evening, after the meeting was over, I left Peterborough,
and some other Friends with me, much comforted and refreshed in the Lord my God;
having felt his living power and presence with me and my friends,
to our preservation and deliverance out of the hands of unreasonable men.
Though they had so much shown their fury and madness against us that day,
they were not permitted to do us much harm,
except the ancient woman Friend being wounded in her head; but so far as I know,
she got well again in a short time.
The same evening we rode a few miles to an honest Friend`'s house,
I think his name was John Mason, who had left the army, received the truth,
and became a serviceable Friend.

Next morning Isabel Hacker, the wife of Col, Hacker, who had been at the said meeting,
bestowed some labour to get out of my hair,
the dirt which was thrown at me the day before, at the said meeting.
After that, I rode with her and company to Oucom, to her house in Rutlandshire,
where the priest of the town came the next day,
with whom I had some discourse in the presence of Col.
Hacker.
The priest being high and proud, was apt to get in a passion,
which made him incapable of holding any fair discourse.
I told him of it, which he would not acknowledge, but told me I was in anger,
because I spoke somewhat earnestly to him.
I told him he could not provoke me to anger if he
should rail against me from morning till evening;
so our discourse quickly broke off, and I did not perceive that Col.
Hacker, or anyone present, could excuse the angry priest.

When Presbyterian and Independent ministers had the design to reform from corruptions,
immoralities, profaneness and superstitions,
which were increased and spread under Episcopacy, there appeared some sincerity and zeal,
in their way, for the practice of religion and piety;
and their preaching was against drunkenness, sabbath breaking, swearing, lying, envy,
pride, covetousness, idolatry, superstition, etc.
What care and caution did they show toward their hearers,
to prepare them to be worthy communicants, that they might not eat and drink unworthily,
nor damnation nor judgment to themselves, as those that discern not the Lord`'s body;
though that discerning has been long lacking, since the apostacy from the substance.

In those early days of the designed reformation from Episcopacy, some of those reformers,
in their zeal, believed the Lord was with them,
and that his presence attended their ministry.
And while there was a zeal in any of them against vice, and for promoting virtue,
no doubt a secret presence of the Lord, in measure, attended the ministry of such,
which had some good effect toward a reformation.

But when the teachers and leaders of several sorts and societies,
got to be parish priests, and into pride and covetousness, into high places,
great livings, to preach for profit, forced maintenance, tithes, oblations, obventions,
revenues, etc., being favoured therein by the revolutions of the government,
their zeal grew cold, corruption and covetousness increased,
their ministry and preaching became dead and barren,
and many well disposed people began to see their declension and corruptions,
and grew weary of them.

Then the gospel harvest drew near and came on,
for many to be gathered to the life of the Christian religion,
and the power of godliness; from darkness to the true light;
from the flesh to the spirit; from dead forms to the living power;
from shadows to Christ the substance; from dead ways and false worships,
into the living way and worship of God in spirit and truth.
For this end and purpose God was graciously pleased, in an acceptable time,
to raise up living and faithful witnesses and ministers of the everlasting gospel,
to open the eyes and understandings of the people, To turn them from darkness to light,
and from the power of Satan unto God; that thereby truly repenting,
they might receive remission of sins, and an inheritance among the sanctified,
through faith in our Lord Jesus Christ, the true light.
And the ministry of these faithful witnesses was very acceptable and effectual to many,
whose hearts God had prepared and opened to receive the love of the truth,
as it is in Christ Jesus.

Then were the proud and covetous priests, and mercenary preachers of all sorts,
greatly disturbed.
The very report of a people risen in the north of England, called Quakers,
and of their increase and spreading, and the prevalency of their testimony,
caused a fear and consternation to seize upon the spirits of many of those preachers,
when their trade was in danger, and their gain lay at stake,
as Christ`'s free gospel ministry took effect and place in people`'s hearts.
Then rung the pulpits; lectures were promoted and conferences;
complaints and petitions were exhibited to magistrates against the Quakers,
under the unjust and false pretences of their being antichrists, come in the last days;
deceivers, seducers; dangerous to church and state.
Some of them being conscious of their decaying ministry,
and that they were declining and going downward in the eyes and esteem of the people,
their hearers, they became the more afraid and jealous of their standing;
especially knowing partly their own corruptions, that whatever good words they could use,
yet that they lived bad lives.
They thus pleaded with their hearers, to excuse themselves, "`You must do as we say,
and not as we do;`" thereby rendering themselves
but in the state of the scribes and pharisees,
who sat in Moses`' seat.
And as therein they represented Moses`' law being then in force,
they bid people observe the same, which was what they were then to observe and do;
but said Christ, Do not according to their works; for they say and do not: Matt. 23:3.
See the whole chapter,
how sharply and zealously our Lord testified against those hypocrites,
with several woes to them; so far was Christ from owning them for his ministers.

I very well remember some of the heads of a remarkable conference,
among some of those called Independent ministers or pastors,
which it appears occurred when they were declining from the sincerity
and zeal that had been formerly moving among and in some of them.
I had the account from our dear, ancient, and faithful friend, Robert Ludgater, senior,
of Great Coggeshall, in Essex, in effect following:

That many Independent ministers or priests, at a meeting at Coggeshall, had a conference,
which was chiefly on a question first put by one Samuel Crosman,
pastor of a church at Sudbury in Suffolk.
The question was this:

"`What is the reason why the presence of God does
not attend or accompany our ministry now,
as it did at first, or in the beginning?`"
To which--he that put the question--first answered:

"`At first we had respect to good lives and conduct--to be good examples therein;
and then we sought the good of the people`'s souls; we coveted them, not theirs;
we then preached in the simplicity of the gospel, in plainness and sincerity,
without affected high strains of eloquence, or words of men`'s wisdom;
for it is a great pity any man should stand up in a pulpit to preach,
and not preach the plainness and simplicity of the gospel.

"`But now the case is altered with us; though we speak good words, we live had lives;
we are not good examples to our hearers.
We covet theirs more than them.
We now affect flourishing eloquence, rhetoric, philosophy, or school learning,
more than the plainness and simplicity of the gospel, in our preaching;
for these reasons the presence of God does not go along with us in our ministry now,
as at first, or formerly.`"

Another of the company, the minister or parish priest of Coggeshall,
repeated the question,
"`What is the reason why the presence of God does not go along with our ministry now,
as it did in the beginning?`"
And then proceeded, "`I would add this question;
What was that presence of God that did accompany our ministry in the beginning?`"
To which he answered, "`It was an enlightening presence;
it was an enlivening or quickening presence;
it was a strengthening and confirming presence;
and all this is now lacking in our ministry,`"

Another professing minister of the company, repeated the question,
but varied in his answer, from his two brethren before:
"`What is the reason why the presence of God does not now go along with our ministry,
as it did at first?`"

Which he answered to this effect; "`Our ministry is God`'s ordinance,
and we may not suppose God will forsake his own ordinance;
but there are many persons or people turned against us,
who deny the ordinances and tell us.
Your ordinances are barren ordinances; they are wilderness ordinances;
your ministry is a barren ministry; it is a fruitless ministry, a dead ministry;
and therefore, to such it must needs appear ineffectual and barren.`"
But he concluded to this effect;
"`Although our ministry or ordinances appear to you to be but as barren ordinances,
wilderness ordinances; yet you should continue, or persist, in the observation thereof.`"

Another of the company, esteemed a great pastor among them,
at last repeating the question,
"`What is the reason why the presence of God does not attend our ministry?`"
answered to this purpose, in contradiction to the two first;
"`God has not forsaken our ministry,
he has not withdrawn his presence from his own ordinances,
though it does not now appear so effectual as at first, or not to have the like effect.
That is because our ministry has had its effect upon the elect, for their conversion,
who were ordained to eternal life or salvation;
but for those who are otherwise predestinated to damnation,
it is not to be expected that our ministry should take effect upon them,
for their conversion or salvation.`"

The first and second answers to the foregoing question, were ingenuous and honest,
but the two last cloudy and prejudicial, especially the last,
relating to the predestinarian notion,
which is repugnant to the free and universal grace and love of God in Christ Jesus,
to mankind; and to the free offers thereof, conditionally,
in his gospel preached universally unto all.

Great notice was taken of the said Samuel Crosman, who first put the question,
as to his further declension from his former zeal, sincerity, and professed reformation,
independency, and dissent from Episcopacy.
After king Charles the second came to the throne,
and suffering by persecution began upon the most conscientious dissenters,
and conformity was required and imposed, Samuel Crosman fled the cross,
evaded his dissent and independency, conformed and temporized,
left his congregation and people at Sudbury, and removed to the city of Bristol,
and there showing himself a zealous conformist, got preferment under the bishop,
and became a parish priest in that city.

At a certain time being at Bristol, and visiting Bersha Speed, widow,
Samuel Crosman came into her parlour, where I was sitting,
and demanded Easter reckonings of the widow, which I argued against, as unreasonable,
as well as unscriptural, to demand that of her,
who was none of his hearers or communicants.
And I took occasion to relate to him the fame I had heard and understood concerning him;
as what an eminent minister he had been among the Independents at Sudbury,
questioning how he could now be such a Conformist,
after all his high profession of reformation to the contrary;
or how he could quiet his conscience therein.

He gave me a smooth, but evasive answer, no ways satisfactory or sincere,
making it but as a matter of indifferency to conform to the church of England;
and the ceremonies thereof but indifferent things, that might be dispensed with,
provided he might preach the gospel.
Such like allegations have many of the temporizing
priests used to excuse themselves in the like case.

Having the opportunity, I reminded him of the passage before mentioned,
and repeated his question and answer to himself,
according as Robert Ludgater had related them to me.
I was the more particular with the said Samuel Crosman,
he being the person immediately concerned;
to see if he could deny any part of the matter related upon his question,
"`What is the reason why the presence of God does not attend our ministry now,
as it did in the beginning?`"
This, together with his answer, I reminded him of, and he did not deny any part of it;
whereby the truth of Robert Ludgater`'s account was the more confirmed to my satisfaction.

In humility and thankfulness to our great and most merciful Lord God,
I must confess to his power and goodness, yes,
and his special providence in helping me hitherto,
and strengthening me in his work and service, and in preserving and delivering me,
through many trials, sufferings and persecutions,
that I have not been delivered to the will of my enemies and persecutors,
who sought my destruction; not only breathing out cruelty against me,
and others of the servants of Christ, in our early days; but, to their power,
have acted maliciously and cruelly against us;
but the remainder of their wrath has the Lord so far restrained,
as not to allow them to execute the utmost thereof against us;
the Lord having reserved for me more service in my day, as well as trials, suffering,
and exercises of various kinds.
The persecutions and hardships which I had undergone,
were not permitted to put an end to my days, or service in the gospel of Jesus Christ,
but to make the same more observable and effectual,
through the Lord`'s power and tender mercy unto me and his people;
and for the sake of many poor souls.

The hard imprisonments, confinements, tumults, cruel stripes, beatings, stonings,
bruisings, and evil treatments, of various sorts, I say,
were not allowed to put a period to my days,
but the Lord`'s power sustained and preserved my spirit, in faith and patience,
in all those afflictions and jeopardies,
to obey and serve him with sincere resolution in the gospel and work thereof.
Let my soul forever bless and praise the worthy name and power of the Lord my God.
