== Chapter VI

I proceed now to some account of my further progress and exercises for the blessed truth.

In the year 1660, the commonwealth government,
under which many of us had suffered persecution, being nearly expired,
preparation was made for the return and reception of king Charles the second,
upon his declaration, in substance as follows:

In king Charles the second`'s letter from Breda, that was sent to the house of peers,
and read in the house, May the 1st, 1660,
and ordered by the lords in Parliament assembled,
that the same should be forthwith printed and published, for the service of the house,
and satisfaction of the kingdom, it is declared;
"`And because the passion and uncharitableness of
the times have produced several opinions in religion,
by which men are engaged in parties and animosities against each other, which,
when they shall hereafter unite in a freedom of conversation,
will be composed or better understood, we do declare a liberty to tender consciences;
and that no man be disquieted or called in question for differences of opinion,
in matters of religion, which do not disturb the peace of the kingdom; and,
that we shall be ready to consent to such an act of Parliament,
as upon mature deliberation shall be offered to us,
for the full granting that indulgence.`"

This declaration and promise made way for the king`'s more
easy and free reception at his return and restoration;
many dissenters having a hope and expectation of the performance thereof.

But in a few months after his coming to the crown, it so fell out, that a few,
about the number of thirty-five persons, called Fifth-Monarchy men,
made an insurrection and disturbance in the city of London, against the government,
pretending for the monarchy and government of king Jesus;
and thereupon being confident that one should chase a thousand,
misapplying the Scripture, they made their attempt with great fury and violence,
until suppressed and apprehended.

From which insurrection occasion was taken by the king, to issue out a proclamation;
some of the heads whereof follow:

Prohibiting all unlawful and seditious meetings and conventicles,
under pretence of religious worship, etc.; giving for a reason thereof.
That some evil effects have already ensued, to the disturbance of the public peace,
by insurrection and murder, by reason of the meetings of Anabaptists and Quakers,
and Fifth-Monarchy men, and such like appellation.

And to the intent,
that none of these persons who have presumed to make so ill a use of our indulgence,
may be strengthened in such their proceedings, etc., no meeting whatsoever,
of the persons aforesaid, under pretence of worshipping God,
shall at any time hereafter be permitted and allowed,
unless it be in some parochial church or chapel in this realm, or in private houses,
by the persons there inhabiting; and that all meetings and assemblies whatsoever,
in order to any spiritual worship and serving of God, by the persons aforesaid,
unless in the places aforesaid, shall be esteemed,
and are hereby declared to be unlawful assemblies, and shall be prosecuted accordingly;
and the persons therein assembled, shall be proceeded against,
as riotously and unlawfully assembled.

And we do will and command our justices,
that they cause the oath of allegiance to be tendered
to every person so brought before them, etc.

Hereupon the most irreligious and profane sort of people were animated,
and took occasion against our religious and peaceable meetings,
eagerly to endeavour to suppress them,
being encouraged by the new justices and magistrates then got into commission.
The most vile and profane, as drunkards, swearers, cursors,
and the most wicked of all sorts,
being exalted in their spirits upon the restoration of the king,
and his accession to the crown,
were then triumphant and insulting against all religious dissenters;
and especially threatening the Quakers and their meetings with ruin.
Seeing; what a great flood of wickedness and debauchery was broken forth,
and religion and virtue despised,
we expected no other but severe and hard treatment from our persecutors,
whose hearts were set to ruin us, or to root us out of the land;
dark clouds then appearing and threatening a great storm.

At a certain time, when I was travelling alone on the highway,
and in earnest supplication to the Lord,
and spreading our case and my complaint before him,
in deep humility and contrition of spirit, I said in my heart and in expression, O Lord,
this wicked, persecuting spirit that has got up and is let loose,
will seek to lay waste and root your heritage and people out of the land.
O Lord, plead our cause; plead the cause of your people, your seed and heritage.
Whereupon the Lord revealed and gave me this answer:
"`The wicked shall not have their evil designs accomplished against my people;
I will frustrate their wicked purposes; they shall not root my heritage out of the land,
though they be permitted for a time to persecute and try my people;
I will stand by and defend, and in due time deliver them.`"
Yes, and to this purpose, and much more of the same tendency,
has the Lord often livingly signified and revealed to me by his Holy Spirit,
even in times of deep suffering and trials, that under any of them I might not faint,
or be discouraged;
but still to believe to see the goodness of the Lord in the land of the living,
where praises ever live to him.

After the insurrection, and the offenders were brought to punishment,
and the proclamation was issued, persecution,
outrage and violence quickly broke out in the land.
Then the roaring, raging,
busy persecutors bestirred themselves to hunt up and down after religious meetings,
assemblies and congregations, which they unjustly termed seditious conventicles,
to break up and disperse them, and cause many to be imprisoned in filthy jails,
where great numbers of innocent persons suffered, in most counties of England and Wales,
especially of the people called Quakers,
whose meetings were most open and easily come at.

Friends did not fail to plead and make known their innocent cause,
to the king and government, both by word and writing;
and to show how clear their religious meetings were, as they always have been,
from any sedition, plots, conspiracies,
or contriving of insurrections against the government or nation,
and consequently they are no such meetings as are by law deemed conventicles,
unlawful or riotous meetings.
So that those persecutions inflicted upon us, because of other men`'s crimes,
who are a people wholly innocent, appeared to be no small perversion of justice,
as well as injury, done to many hundreds of honest, industrious families,
whose innocent cause the Lord in his own time, pleaded in those days;
and since has not failed to stand by and help his faithful people in their times of need,
I proceed to give some account of my own share of suffering and exercise in those days,
and of the manner thereof.

A brief account of my commitment to Norwich castle, with other Friends,
the 20th day of the Eleventh month, 1660.

George Whitehead, John Lawrence, Joseph Lawrence, and William Barber,
with many more of our friends,
being peaceably met together in the worship and service of God,
at a meeting at Pulham-Mary, Norfolk,--while we were calling upon the Lord in prayer,
one in the office of chief constable, with a company of horsemen and footmen,
without warrant from any justice, came with halberts, pistols, swords, pitchforks,
clubs and hedge stakes, and haled us and others of our friends out of the meeting.
The next day we were carried on horseback several miles, and had before Thomas Talbot,
justice of peace, near Wymondham, or Windham, who committed us to prison,
upon information which the constable gave him in writing, touching the meeting;
wherein we were falsely accused of being unlawfully met together.
There appeared none to prove the charge against us,
nevertheless we were next day sent to Norwich castle;
persecution being then generally stirred up against our friends especially,
throughout the nation, and most prisons were filled with them,
because of their religious meetings.
To this jail of the castle of Norwich many of them were committed,
and their meetings disturbed and broken up, from one end of the county to the other,
and likewise in the city of Norwich, which is a county distinct.
We were so crowded in the castle, that we had not convenient room for lodging,
thirty or above, being crowded in that old, nasty jail;
and there being a hole in a corner of the castle wall, called the vice,
we four Friends betook ourselves to that place to lodge in, though a narrow hole,
without any chimney in it; yet there we got up two little beds, and lodged two in each.
It was a very incommodious habitation and lodging room, for lack of a chimney;
and having an old decayed stone arch over it, the rain came so much in upon us,
that we could not well keep it off our beds, though we set basins to catch what we could.
In the cold weather we burnt a little charcoal in the evenings,
which we found somewhat injurious and suffocating,
having no chimney to vent the smoke or steam;
and in the day time we endeavoured often to keep
ourselves warm by walking upon the castle hill,
and under the wall, being within the liberty of the prison;
though it was but a cold bleak place in winter,
yet we were glad that we had that benefit of the air.

Although the hole in the wall was so incommodious, we chose it for our lodging,
partly for the relief of our friends, who were too much crowded in a better room below,
within the castle walls.
Here we had many good and comfortable meetings together, without disturbance,
several friendly persons being let into prison, met with us, on first-days especially;
so that at that time the prison became a sanctuary to us,
as prisons and jails were to many of our poor, innocent, suffering friends,
when persecution was hot, and persecutors raging and roaring abroad;
and we praying and praising the Lord our God, in prisons, jails, and holes.

Our friends William Barber and John Lawrence, having been men of note,
and captains in the commonwealth`'s day,
it appeared in them a piece of great self-denial and subjection to the cross of Christ,
patiently so to suffer for his name and truth sake, in such a poor, incommodious lodging.
I remember one morning when we were in bed, Joseph Lawrence, after his pleasant manner,
said to his brother John; "`O captain Lawrence,
I have seen the day that you would not have lain here;`" that is,
in such a contemptible place, or mean lodging as that was; for both brothers,
and William Barber, were well accommodated at their own houses in all respects;
though then partakers of the sufferings of Christ`'s followers.

In the time of that imprisonment in Norwich castle, near the latter end of winter,
or about the beginning of the first month, 1661, I was taken sick of an ague and fever,
which brought me so low and weak, that some friends who came to visit me,
were ready to lake their last leave of me, thinking I should die in that prison.
Elizabeth, the wife of John Lawrence, being one day at my bedside, said, "`Ah! poor,
dear George, I fear we must part with him; his travelling among us is near at an end.`"
But in a few days, it pleased the Lord that I had some recovery and strength given me;
yet each other day a very sick fit of the ague and fever continued for a little time.
One night after I was in bed,
I was sorely affected with the smoke of a little charcoal fire in the room,
and earnestly called to have it put out presently,
otherwise I questioned whether I should live till next morning;
so it was immediately put out, and I was quickly eased.

The time for our appearing at the spring court session at Thetford drawing near,
I believed J should be enabled to ride there; for we were all to appear there,
who were prisoners for our religious meetings;
and in order to my going to the court session,
my horse was brought to the prison door three days before the court session began.
I rode with John Lawrence to his house at Wramplingham, on the seventh-day of the week,
being five or six miles on my way toward Thetford,
and stayed there the next day and night following.
That day I had again a very sick fit of the ague, but grew better before the next day,
and then we took horse for Thetford, being about twenty miles from Norwich.
The weather being cold, a hail shower overtook us,
and I was again taken with a fit of the ague on the road, before we got to Thetford,
yet with the Lord`'s help I held on, and grew better by the time we came to Thetford;
and that afternoon could readily walk up to the top
of the noted mount or hill which is by the town.
We met the rest of our friends, who came from Norwich castle, at Thetford prison,
where we were in the day time, after the court session began;
but at night had liberty to lodge at our friends`' houses in or near the town.

Judge Hale and judge Windham, i. e. Wadham Windham,
were the two justices who served at the same court session,
and judge Windham sat on the crown side.
In his charge he terribly threatened dissenters,
and such as would not go to the parish church and conform,
or that kept conventicles or unlawful meetings;
giving the country notice of several ancient severe penal laws made against such,
and causing some of them to be read in court.
An ancient Friend, Elizabeth Hawes, then living at Snare Hill near Thetford,
gave me a a full account with tears, after she had heard the said charge;
being very sorrowful to see how they were bent to persecution.
To encourage her, I signified the Lord would plead our cause and stand by us,
and I would have no Friends discouraged, but be faithful to the Lord,
and valiant for the truth upon earth; as I had often exhorted Friends.

Friends were several times called into court before the court session were over;
I was called four times,
and particularly questioned for what cause I came into that county from my own;
to which I gave the judges a sober and conscientious account,
that I was called of the Lord to preach repentance, and to bear testimony to the truth,
against hypocrisy, sin and wickedness.

Being required to take the oath of allegiance, I told the judges,
that Christ has commanded us not to swear at all, and his apostle James,
who well knew the mind of Christ, exhorted, "`Above all things, my brethren, swear not,
neither by heaven, neither by the earth, neither by any other oath:
but let your yes be yes; and your no, no; lest you fall into condemnation.`"
From which I inferred, if we may not swear by any other oath,
then not by the oath of allegiance.
Therefore I cannot swear at all, nor take any oath,
either that of allegiance or any other;
the judges did not dispute the point or the argument.
But seeing that I and the rest of our friends then prisoners,
were all of a mind in that case, that we all refused to swear,
choosing rather to suffer for conscience, we were remanded to the prison in Thetford.

Before the court session was ended, some of us were again called into court,
and an indictment read against me and some others of us,
stuffed with false and bitter accusations and invectives,
because we refused to take the oath of allegiance;
that being the snare generally laid against us,
for which we were charged with obstinacy and contempt against the king,
his crown and dignity, and such like injurious charges.
Being required to plead guilty or not guilty, I began to distinguish upon the indictment,
that some part of it was true, that we refused to take the oath,
but it was not out of obstinacy or any contempt against the king or government,
but for conscience sake, in obedience to Christ`'s command.
Judge Windham urging us to plead guilty or not guilty,
to prevent me from opening our case, I waved pleading in those terms,
unless he would allow me to plead specially, with distinction,
on the several parts of the charge, in order to manifest the inconsistency thereof,
and our clearness and innocence, who were the sufferers.
The judge then grew offended,
because I was not willing to be confined only to plead guilty or not guilty,
and he was for having me taken away and remanded to prison;
whereupon I returned him this answer, that Paul when a prisoner,
was permitted to plead and speak for himself before king Agrippa; Acts xxvi.,
and before the Roman or heathen magistrates and rulers.
It is therefore a hard case,
that we may not be permitted to speak or plead for ourselves before you,
who profess yourselves to be Christian magistrates.
The judge appeared angry and disturbed; I was quickly removed out of the court.
Take him away jailer, was such a knocking argument in those days,
that it must not be disputed;
yet judge Hale behaved himself more mildly and gently toward us.

It was observed that when several of us, the prisoners, were called into court together,
some of the country justices on the bench, particularly one of them,
would be accusing us to judge Windham, to incense him against us,
and especially against John Hubbard senior, of Stoak ferry in Norfolk,
and others for receiving and entertaining the Quakers and their preachers at their houses.
Our loving, honest friend John Hubbard, seeing the envy of those persecutors,
who would make him an offender for entertaining strangers, as the apostle taught,
was stirred up with zeal to answer his accuser,
and plead a good conscience toward God and man, as being known to be an honest man,
fearing God.
Testifying with zeal and courage, it gave a check, at that time,
to his accusations against innocent prisoners.
But it was no unusual thing in those days, for ill-natured, persecuting justices,
to be both accusers and judges upon the bench, against our friends;
and like invidious informers, endeavour to incense the judges against us,
by unjust insinuations and accusations, with the intent to induce hard usage against us,
and often to prejudge our case, before judicially heard or tried.

Although in the time of the court session at Thetford,
the persecuting spirit was eagerly at work in our adversaries,
I daily felt the Lord`'s power over all,
whereby I and my fellow prisoners were supported,
strengthened and preserved in innocency and great peace,
to the praise of our most gracious God.
Although I could expect no other but that our persecutors
would be permitted to strengthen and prolong our bonds,
at least against some of us, whom they designed to make terrifying examples,
yet I was not at all discouraged nor dejected in spirit, under that persecution;
but returned cheerfully to prison to Norwich castle,
and was better every way as to my health and strength, than when I came out from there,
to go to the court session at Thetford.

It was to me a very remarkable and memorable token
of the merciful Providence and love of God,
that although I had been very weak and sick in prison
in the said castle but a few days before,
and rode to Thetford court session in a weak condition,
yet while I was attending upon the court session, I quickly recovered my health,
so that my ague and fever were quite removed,
and I had not the return of one fit all the time of that imprisonment,
but was restored to perfect health, which continued for several years after.

Six of us, to whom the oath was tendered, and who were indicted, were, with some others,
remanded to the castle; and the rest were released, being mostly labouring men,
farmers and tradesmen;
our persecutors having picked out such to send back to prison
as they esteemed to be the most noted among the Quakers,
as John Lawrence, Joseph Lawrence, William Barber, Henry Kettle, senior and junior,
John Hubbard and several others, because of their love and kindness to their friends,
and entertaining meetings at their houses.
The time we were detained prisoners in Norwich castle, in the years 1660 and 1661,
was about sixteen weeks, from the eleventh to the third month.

Our release was obtained by the king`'s proclamation of grace, as it was termed, wherein,
notwithstanding his grace or favour expressed towards the Quakers,
it was not without a menace or threat, i. e. not intending their impunity,
if they should offend in future in like manner as they had done.
This was chiefly their religious meetings,
intended only for the worship of the living God,
according to their consciences and persuasions;
and for this cause our impunity or lack of punishment was not intended,
as afterward in a short time it more fully appeared.

One thing I may not omit some account of,`' when we were together in Thetford prison,
in order to appear at the court session, I met with Henry Kettle the elder,
a prisoner there, who was an ancient man,
and had been mayor of the town and a justice of peace,
before he was in communion with us.
After he had received our friends and had meetings at his house,
having a love to truth and us, he was committed to prison;
where he and I walking together in the prison yard,
he opened his condition and exercise to me; how he was beset with relations,
and pressed to take the oath of allegiance,
otherwise they feared that he and his family would be ruined;
whereupon the trial came the harder on him, considering his own weakness.
However, he tenderly told me, he had considered Christ`'s words,
He that puts his hand to the plough, and looks back, is not fit for the kingdom of God;
concluding therefore he must not look back; he must not draw back,
or decline from the truth.

I was very glad to hear him voluntarily give such an honest account,
both of his trial and good resolution, having well understood his weakness,
how he had been wavering and halting in his mind; and how hard it was for him,
being a person of great note, to give up to the cross of Christ,
so as to endure reproach and persecution for Christ Jesus and his truth.
Yet now when he was given up to suffer for Christ,
by him he was assisted and strengthened, rather to suffer with the rest of us,
than to lose his inward peace, by declining Truth`'s testimony;
so that because he could not submit to the will of his persecutors, he was,
contrary to law, removed from Thetford, the corporation where his residence was,
to the county jail in Norwich castle,
where his son Henry was detained prisoner with the rest of us.

At the ensuing quarter-sessions held at Norwich castle, for the county of Norfolk,
Henry Kettle the elder, was called into the court of sessions, where, to ensnare him,
it was required of him to take the oath of allegiance,
with endeavours to impose it upon him.
But he stood it out, and would not be imposed on, telling the justices,
that he was removed out of his own respective corporation, to which he belonged,
contrary to law, and therefore was unduly brought before them in that court.
It was a breach of his and the corporation`'s privilege,
to remove him from there to that quarter-sessions, to be prosecuted or tried;
and expressly contrary to Magna Charta,
whereby the liberties and privileges of corporations are to be upheld and maintained,
and not violated.

I and another fellow-prisoner being then on the Castle-hill,
heard him plead after this manner, and hold them closely to the point;
but instead of answering him legally, or vindicating their proceeding by law,
they still obtruded and imposed upon him, saying.
It is no matter; it is no matter how you came here,
that is not our business to inquire after: now you are here,
we have power to tender you the oath.
Mr. Kettle, will you take the oath of allegiance, ay or no?

He answered.
Let me be returned back to my own corporation, the town of Thetford,
and there I may answer.
Rut otherwise he esteemed himself not bound to answer in that court of sessions,
held for the county of Norfolk, being unduly removed there out of his own.

This is the substance of their procedure against Henry Kettle, sen., at that time,
so near as occurs to my remembrance;
and I gave serious attention to the discourse between him and the justices,
who when they could not by persuasion or menaces, prevail with him to take the oath,
returned him to the castle jail, to remain prisoner with the rest of us.

I was glad and comforted, that he stood that trial as well as he did,
and that the Lord supported him so as not to fall into the snare laid for him;
but to avoid swearing, and evade their striving to impose an oath upon him,
contrary to his conscience.
I was sensible he thereby gained more strength in the Truth,
and his prosecutors were not permitted to bring him under the penalty of a premunire,
no more than the rest of us, who were prosecuted in order thereto,
but all discharged by the proclamation aforesaid.

I was sensible the Lord had regard to Henry Kettle, sen., and his family;
for they retained their love to the Truth and Friends;
as did in particular his son Henry, and daughter Anne, who was a sober virtuous maid,
though she lived not many years after she received the Truth;
but her brother Henry lived to old age.
And their mother, an ancient woman, had so much love to Friends,
that she not only kindly entertained them,
but when her son Henry was prisoner with us in Norwich castle,
she came on foot from Thetford, to visit him and us in prison,
manifesting her love and kindness thereby to us; and so far as I understood,
she bore his suffering patiently, as well as she did her husband`'s afterward,
beyond expectation, considering her weak condition.
One cause of her coming on foot to visit us in prison, I suppose was,
her age and weakness, not being able to endure riding so far on horseback.
The Lord showed mercy to that family, as he did to many others in those days,
who since are gone to rest from their labours and sufferings.

A copy of John Lawrence`'s letter to Justice Talbot,
after we were committed prisoners to Norwich castle,
which I thought fit to insert in this place.

Friend,

I could not have believed that any magistrate would
have acted so unjustly as you have done toward us,
in sending us to prison, when no witness did appear against us,
to prove us transgressors.
Surely the magistrate that desires to do uprightly, and as he would be done unto,
would not have sent men to prison upon so slight an information as you had against us.

And whereas you did accuse us for meeting in contempt
of the king`'s proclamation;--I answer,
that our meeting was not in contempt of the king, but in obedience to the Lord,
whose presence is enjoyed among us in our meetings,
and from whose presence you cannot separate us,
although you have sent us into a noisome prison.
For know assuredly, that we have much peace in our sufferings,
and are not afraid what man can do unto us; for our trust is in the living God,
who made heaven and earth, and will plead the cause of the innocent;
and will not let persecutors go free.

There are also three men who were haled out of a peaceable meeting,
and were sent to prison by you.
Two of them are poor men,
and have great charges of children to maintain only by their labours;
and if they be long detained prisoners, their children may famish for want,
and your oppressing will become your own burden; but your rage and envy is such,
that it is likely you do but little regard either old or young,
if they be contrary to your principles.
And it is likely if these men had been taken drinking, or drunk, in an ale-house,
they had been let alone, and not punished; for how does wickedness abound in that town?
Are there none to punish or imprison,
but those who meet in the service and worship of God?
When those that feared the Lord often met together, the Lord hearkened and heard;
and a book of remembrance was written before him for them; as you may read, Mal.
iii.

Our sufferings are for righteousness and conscience-sake;
and although we should suffer the loss of all outward things we enjoy,
and of our lives also, yet, neither you, nor any other, can take our peace from us.

It is not long before you must give account for all your unrighteous actings; therefore,
while you have time, prize it; and slight not the day of your visitation,
but mind God`'s witness in your conscience, which shows you sin and evil,
and that will bring to your remembrance all that ever you have done,
and will let you see how you have spent your time,
and how unprofitably you have walked before the God of heaven all your days.
If you will return at God`'s reproof, and forsake the evil of your doings,
you will find mercy; but if you do persist and go on, provoking the Lord,
then woe and misery will assuredly be your portion.

Written in love to you, by a sufferer for the testimony of a good conscience,
who am a friend to your soul.

John Lawrence.

Norwich Castle, the 25th of the Eleventh month, called January, 1660.

[.asterism]
'''

The substance of a letter to the Mayor of the city of Norwich,
when he was busy in persecuting and imprisoning our friends there, A. D. 1660.

Friend,

Do you not own yourself to be a Christian magistrate?
But have you acted like one in sending the servants of Christ to prison in this city;
separating poor men from their wives and children,
who can hardly subsist in their absence.
And for what cause, but for meeting together to worship God in spirit and in truth,
as the primitive Christians and saints of old did;
or for not swearing the oath of allegiance,
which in conscience to Jesus Christ and his doctrine, they could not take,
nor any other oath; Matt. 5. James 5.

How have you acted like a Christian magistrate,
in causing our friends to suffer imprisonment, because they could not in conscience,
transgress the doctrine and commandment of Christ and his apostle,
which forbids all swearing?
What malice and envy have you shown, in sending for poor harmless men,
on purpose to ensnare and imprison them,
upon the oath of allegiance being required of them;
and for conscience sake refused by them.
How do you herein act like a Christian magistrate?
What compassion do you show to the needy?
Or how do you break off your iniquities, by showing mercy to the poor?
May you not justly expect, that the cries of the poor and needy,
whom you have thus oppressed, will be heard of the Lord against you,
and his judgments fall heavy upon you,
if you do not speedily break off your sins by true repentance, and your iniquity,
by showing mercy to the poor and needy, and setting the oppressed free?
For had you any more against those our friends, whom you have imprisoned for meeting,
than you might have had against the apostles and primitive Christians for the like practice,
had you been in their days?
And might you not as well have persecuted and imprisoned them upon the same account,
as you have imprisoned these?

We knowing that our justification is with the Lord in our meeting together,
which is to wait upon and worship him, can challenge you, and the whole nation,
to prove any evil against us therein;
or anything done by us contrary to the Scriptures of Truth,
or the doctrine of Christ or his apostles, whose divine law against swearing at all,
is to us, and to all true Christians, of more weight than all contrary laws of men,
for swearing.

The oaths of allegiance and supremacy were never
intended to ensnare and imprison poor harmless men,
and Protestants; nor is our refusing to swear for conscience-sake to Christ,
any proof of our being papists--for they can swear;
and our averseness to Popery is well known, more than theirs who do swear,
and are ready to tender oaths to others upon every turn;
and also our innocency in patiently suffering under the several sorts of rulers or governments,
manifests our clearness from wicked plots and insurrections.

Your lying in wait to ensnare our friends with the oath,
manifests that it is more out of envy than justice, and will bring no honour to you,
but shame and disgrace, and in the end misery, woe and confusion of face,
if you do not speedily repent, and return to the light of Christ,
which calls for humility, moderation, equity, and love toward all men;
and to do to all men as you would be done by.
Let not the sun go down upon your wrath, lest you give place to the devil,
and the day forever become dark over you.

This letter is given out of tender affection and love which I bear to your soul,
and not from any contempt or prejudice against your person.

From a friend to your soul, who am a sufferer for obeying Christ.

George Whitehead.

1660, in the Eleventh month.

[.asterism]
'''

The substance of a letter, in answer to the Mayor of Norwich,
when our friends were prisoners there.

Friend,

Whereas in answer to my letter, you have sent the late proclamation of the king,
prohibiting all unlawful and seditious meetings and conventicles,
under pretence of religious worship, etc.,
this will be no warrant in the sight of God for what you have done against our friends.
Seeing you own yourself to be a Christian magistrate,
you should have acted according to Christ`'s law, and done as you would be done by.
Would you be so hardly dealt with for your religion and worship,
as you have done by our friends?

You have not proved our friends`' meetings, which you have broken up,
either unlawful or seditious, or contrary to the meetings of the primitive Christians.
Neither have you acted according to this proclamation, which you own as your rule,
especially in imprisoning our friend Robert Turner, of Lynn,
who was not taken by warrant out of a meeting, but sent for to you,
he being come to visit us and our friends in prison.
And we know no warrant whereby he was taken according to the king`'s latter proclamation,
which we have also seen; and since that came forth,
our friends have had meetings in peace at London;
so it does not appear that you have acted according to either of these proclamations,
especially against Robert Turner.

Yet if you should say or think, he was at an unlawful meeting,
in his being among us in prison, when he was sent for to come to you,
then it would from there follow,
that those magistrates who have imprisoned so many of us together,
have caused unlawful meetings in prisons;
for instead of breaking up or dissolving our meetings, under pretence of being unlawful,
they have crowded so many of us in prison, that we can scarcely get room to lodge.

Surely the Lord takes notice of this grievous oppression and persecution,
under which the innocent suffer; and to him we commit our cause,
who in his own time will plead it.
Take heed how you go on persecuting the innocent;
for there is that witness of God in you, which will trouble and judge you for it.
Consider it while you have time.

From a friend to your soul,

George Whitehead.

During our imprisonment we not only faithfully warned
our persecutors against their hard proceedings,
with information of the innocency and righteousness of our cause,
so that they were left inexcusable; but also the king was acquainted therewith,
and the general sufferings of our friends laid before him, and their innocency pleaded,
as a peaceable people,
not having forfeited their interest in his promise
of liberty to tender consciences in matters of religion.
Some of our friends at London, reminded him thereof,
and by solicitation and frequent complaints of our persecutions and hardships,
he was induced to issue the proclamation of grace for our release out of the prisons.
It also contained a threat, that impunity was not intended us,
if we continued to practice, as we had done, upon the score of religion.

So it came to pass that it was but a short time after we were set at liberty,
that we could enjoy our religious meetings quietly; the irreligious, persecuting spirit,
being at work in the nation among priests and magistrates,
who would have all compelled to go to church, and conform.
The pretence was, for all to be of one religion; when there was but little of the life,
substance, or purity of religion designed in the case; but rather empty form, ceremony,
and an outward show and pretence, to palliate covetousness, pride, looseness of conduct,
manifold corruptions, and fleshly liberty, then abounding, and more and more manifest.
The libertines of those days boastingly told us, You must all go to church,
or else you must lose your estates; or you must be hanged or banished;
with many such threats and cruel mockings; yet still it was a stay to us,
and sure ground of faith and hope, that we knew Him,
in whom we livingly believed and hoped for salvation and strength.

So precipitant was the persecuting spirit, and eager to be at work,
and that too under some colour of law,
that in the first parliament chosen after the king`'s restoration,
they soon contrived a bill for suppressing our meetings;
and many of the persons chosen to be members of that parliament,
being known to be persecutors, they swayed and carried it by vote,
so that the bill was committed, and at last passed into an Act, which is entitled:

An Act for preventing mischiefs and dangers,
that may arise by certain persons called Quakers,
and others refusing to take lawful oaths.

Whereas, of late times, certain persons under the name of Quakers,
and other names of separation,
have taken up and maintained sundry dangerous opinions and tenets, and among others,
that the taking of an oath in any case whatsoever, although before a lawful magistrate,
is altogether unlawful and contrary to the Word of God;
and the said persons do daily refuse to take an oath, though lawfully tendered,
whereby it often happens that truth is wholly suppressed,
and the administration of justice much obstructed.

And whereas the said persons, under a pretence of religious worship,
do often assemble themselves in great numbers, in several parts of this realm,
to the great endangering of the public peace and safety, and to the terror of the people,
by maintaining a secret and strict correspondence among themselves,
and in the mean time separating and dividing themselves
from the rest of his majesty`'s good and loyal subjects,
and from the public congregations and usual places of divine worship.
+++[+++It was therefore enacted,]
"`That if five or more Quakers, of sixteen years of age, or upward,
assemble under pretence of joining in religious worship, not authorized by law,
the party offending, being convicted by verdict, confession,
or by the notorious evidence of the fact, shall forfeit for the first offence,
the sum imposed, not exceeding five pounds: and for the second, the sum imposed,
not exceeding ten pounds, to be levied by distress and sale of the goods:
and for lack thereof, or non-payment, within a week after conviction,
shall be committed to the jail or house of correction; for the first offence,
three months; for the second, six months; to be kept at hard labour.
And if after two convictions, they offend the third time, and are convicted,
they shall abjure the realm, or the king may order them to be transported in any ship,
to any of his plantations.

This Act was levelled against the people called Quakers,
when nothing was justly chargeable against them, nor could any matter of fact be proved,
but what concerned religion, and worship toward Almighty God,
according to their conscientious persuasions;
therefore it was purely for serving and worshipping him according to our consciences,
that we suffered greatly by this Act for a time.

Edward Burrough, Richard Hubberthorn, and myself, having notice,
and understanding the matter contained therein, when it was formed into a bill,
attended the parliament, and solicited against the same,
that it might not be passed into an Act; discoursing with many of the members,
and showing them how unreasonable and injurious it would be,
to pass such an Act against us, an innocent people;
our religious assemblies being peaceable,
and only intended for the worship of Almighty God, according to our consciences,
and in no way tending to the terror of the public, in appearance or action.

When the said bill was committed, we sundry times attended the committee,
on the 10th and 13th days of the fifth month, 1661,
and each of us were permitted to appear, and our reasons to be heard before the same,
concerning the bill, why it should not pass against us.

What I declared to the committee, I kept this account of: the first time I signified,
"`That our meetings are in and for the worship of God,
which really is a matter of conscience and of great weight to us,
and that which in tenderness of conscience to Christ`'s command, we practice,
for no other end but singly for the worship and service of God,
according to the example and practice of the primitive saints and Christians;
and that we behave ourselves peaceably towards all men;
therefore we ought therein to have the liberty of our consciences,
according to the king`'s promises of liberty to fender consciences in matters of religion.

"`And that if we suffer for our peaceable harmless meetings,
which are only for the worship of God, according to the saints`' practice,
who met often together for that end, we suffer for the cause of God,
and shall commit our cause to him,
and know that he will plead and avenge it against our persecutors, or to the same effect,
exhorting them to act in the fear of God, etc.
With other words of concernment to them.

"`The second time we were before the said committee,
I told them as concerning our meetings, which their intended law chiefly was against,
that we met together in the name and fear of the Lord God, and in obedience to him,
as the saints of old did; so that they might as well go about to make a law,
that we should not pray in the name of Christ Jesus,
as to make one to hinder or suppress our meetings, which are in his name,
and from which we may no more refrain, than Daniel could forbear praying to the true God,
though it was contrary to king Darius`' decree.`"

One called Sir John Goodrich being one of the committee, stood up,
and most busily inveighed against us, accusing our meetings, calling them unlawful,
and contrary to law, tending to seduce people from the church,
and to seduce such as are orthodox, and the like.

To which I answered, "`That if our meetings be contrary to law,
then that implies there is some law, they are contrary to.
If so, it seems superfluous and needless for you to go about to make another,
if there be some law already in force against them.
But no such thing, we hope can be proved against us,
as that our meetings are unlawful in themselves, being in obedience to the Lord our God,
only for his worship, and agreeable to the practice of the primitive Christians,
recorded in the Scriptures of truth.
Such meetings are not unlawful, and such are ours, as we can prove,
and therefore not unlawful.

"`If your intended law come to be put in execution against us,
for our peaceable meetings,
it may produce sad sufferings upon thousands of innocent people in the nation,
and endanger the ruin of many families;
and the loss of some lives,--and so it did--by persecution and imprisonments.
Of what a bad report will this be,
that an innocent people should thus be oppressed for their consciences,
when no matter of fact, or crime, worthy of suffering for, can be proved against them,
or to that purpose.

"`And further, if this intended law be effected against us,
it will elevate and strengthen wicked, malicious and lawless persons,
to take occasion to persecute us beyond the law,--to exceed the severity thereof,
as they have lately done--as for instance,
when great numbers of us were imprisoned upon the king`'s Proclamation,
for meeting together, some of our friends were taken out of their beds, by rude fellows,
and committed to prison; some poor men were taken from their callings,
and from their poor families, whom they were to maintain, and sent to prison;
and others were taken travelling on the king`'s high-way,
about their lawful occasions and committed to prison, contrary to law,
and which the king`'s Proclamation did not warrant them to do.
Now if you make a law to cause us to suffer for our peaceable meetings,
how much more will rude and lawless persons, take encouragement thereby,
to act their cruelty and persecution against us,
both beyond and contrary to what the law requires;
and it is not your intended law that will satisfy that malicious spirit.

"`Therefore seriously consider and weigh our cause;
these things I leave to your serious consideration.`"

Not having a particular or full account in writing,
what my friends Edward Burrough and Richard Hubberthorn declared to that committee,
I cannot insert the same with mine, otherwise I would have done it;
but I remember the last time we were before the committee,
Edward Burrough told them to this purpose,
that if they made a law against our religious meetings,
he should esteem it his duty to exhort our friends to keep their meetings diligently.

Notwithstanding what is before related,
and more also that was urged by us before the said committee against the bill,
they went forward, being intent upon it,
in order to make their report to the whole house;
and we being given to understand what day the bill was to be read in the house,
were concerned to attend that day;
and to endeavour to obtain leave to be heard in the house,
before it was passed into an Act.

The day appointed, being the 19th of the fifth month, called July, A. D. 1661,
Edward Burrough, Richard Hubberthorn and myself, with Edward Pyott of Bristol,
who had been a captain, went up to the Parliament House,
and spoke to some of the members, whom we knew were friendly to us,
to move for our admittance to be heard in the house, before the bill was passed,
for which we gave them in writing,
a proposal to this purpose:--"`That we desired to
have the liberty that criminals are allowed,
that is, if they have anything to say, or offer in court,
why sentence should not pass against them, they may be heard;
so we desire that we may be heard, what we have to say,
why the said bill ought not to pass against us.`"

Whereupon a motion being made in the house, and leave given that we might be called in,
and heard;
accordingly we were forthwith called in before the bar of the House of Commons,
there being a full house, and all in a quiet posture, ready to hear what we had to offer.

As Edward Burrough began to plead in vindication of the Quakers`' meetings,
on occasion of the bill before them, and against the same,
some of the members said to him,
"`You must direct your speech to Mr. Speaker:`" he told them he would.
The point he chiefly insisted upon was,
That our meetings were no ways to the terror of people,
as was suggested in the preamble of the bill, but peaceable innocent meetings,
only for the worship and service of Almighty God,
and as we are required by the law of God, placed in our hearts and consciences,
which they ought not to make any law against.
No human law ought to be made contrary to the law of God, enjoining us to worship him,
for if they did make any such law, it would not be binding to us,
to disobey the law of God:
for which he mentioned and quoted to them that ancient law book.
Doctor and Student, which he had then in his hand: where, treating of the law of God,
the law of reason, etc., written in the heart of man, it is said,
"`Because it is written in the heart, it may not be put away,
neither is it ever changeable by diversity of place or time;
and therefore against this law, prescription, statute or custom may not prevail;
and if any be brought in against it, they be not prescriptions, statutes, or customs,
but things void and against justice.`"

Wherefore Edward Burrough told them, that if they made such a law against our meetings,
which are appointed for the worship of God, it would be contrary to the law of God,
and void, or ought to be void, ipso facto.

I remember this was the import of what Edward Burrough pleaded to the house at that time.

And what Richard Hubberthorn argued, was upon this point:
"`It being suggested that we were numerous,
and holding a close or strict correspondence among ourselves,
our meetings might be the more dangerous, to contrive and cause insurrections, etc.,
as is implied in the preamble of the bill.`"

To which Richard Hubberthorn gave a fair and ingenuous answer,
That there could be no such danger in our meetings as the
contrivance of insurrections or plots against the government;
for our meetings being public, where all sorts of people may resort,
and come to hear and see what is said or done,
it is not likely or probable we should plot or contrive insurrections in them,
in the sight of the whole world.
And if our meetings should be reduced to such a small number as but four or five persons,
besides those of the family, it could not break our correspondence,
but we should have more opportunity privately to correspond,
and to plot and contrive insurrection or mischief,
if we were a people of such bad principles, or so evilly principled; which we are not.
Therefore it is most reasonable to permit our meetings to be public, as they are,
and not to punish us on causeless suspicion of danger,
when there appears no reason for the same;
nor to make a law to limit them to small numbers; or to this import.

After Edward Burrough and Richard Hubberthorn had spoken against the bill,
which was chiefly designed against our religious meetings, George Whitehead began thus:
"`I have a few words to offer to you, relating to what has been said,
and I desire I may be heard, for I shall use as much brevity as I can.`"

Speaker: Then offer them, and do not reiterate.

George Whitehead: We desire you in the fear of the Lord, to consider us,
as we are an innocent and suffering people,
and have been so under the several governments since we were a people,
as our patience and innocency towards our persecutors in all our sufferings,
have plainly manifested.
For both under Oliver Cromwell and since his days, have we endured much hard suffering,
persecution and imprisonment for our conscience;
and yet we have not rebelled or sought revenge against our persecutors;
but in all our undeserved sufferings, have committed our cause to the Lord.
And therefore what an unreasonable thing is it,
that a law should particularly be made against us, when we have done no evil,
nor any injury against any man`'s person; nor could any such thing be proved against us,
in respect to our meetings, that ever we were found guilty of.
So that for you to make a law against us, tending to our ruin,
and to go about to trample us under foot,
when we are innocent and peaceable in the nation,
and no matter of fact worthy of suffering proved against us,
will neither be to the honour of the king, nor add anything to your security.
No, what a hard thing is it,
for you to make a law to add afflictions and sad sufferings upon us,
when there are several laws already, whereby we are liable to suffer,
as those for tithes, oaths, and others; so that to make another law to afflict us,
when nothing worthy of suffering is proved, seems to us very hard and unreasonable.

And moreover, we have neither forfeited our liberties, nor abused the king`'s indulgence,
in anything acted by us.
And the king having promised liberty to tender consciences,
on condition that they do not disturb the peace of the kingdom,
and we not having forfeited our interest therein, ought not, therefore,
to be hindered of our liberty in matters of worship and conscience towards God.
We can prove that our practice of assembling ourselves together, and our principles also,
are grounded upon the righteous law of God, and agreeable to Christ`'s doctrine;
and we are willing to vindicate and demonstrate them according to truth,
if we might have liberty here;
and that for the satisfaction of such as oppose or scruple them.

In the fear of the Lord consider what you are doing,
and seek not further to add affliction to us, lest you oppress the innocent.
However, if we suffer for our conscience, in obeying Christ,
we shall commit our cause to the Lord our God, who will, no doubt,
plead it against our oppressors.

After Edward Burrough,
Richard Hubberthorn and George Whitehead had declared to the House of Commons as related,
Edward Pyott was also permitted to speak a few words to them,
which he did very weightily, on this subject;
reminding them of that golden rule which Jesus Christ has laid down,
and requires us all to observe; which is,
To do to all men as we would be willing they should do unto us;
thereupon cautioning them, that as they would not be persecuted,
oppressed or made to suffer for their religion or conscience,
or have a law made for that purpose against them,
no more ought they to make a law against us,
to punish us for worshipping God according to our consciences or inward persuasions.
This Edward Pyott pressingly urged upon them.

As we were withdrawing out of the house,
some of the members near the door gently pulled me by my coat sleeve;
I turned and asked them what they would have with me?
They said, "`Nothing,
but to look upon you:`" I being but a young man about twenty-four years of age.

We appeared and declared what was upon our minds, in great simplicity and sincerity;
and the Lord`'s power and presence were with us, and helped us in our endeavours;
and I saw clearly that what we declared innocently to them, had some effect upon,
and reached the consciences of several of the members,
who appeared serious and sober in their carriage toward us.
I had an intimation afterwards, that some of the members confessed that,
what we had declared was very reasonable; and if they had feared God,
or regarded his counsel, and permitted Him to rule among them,
they would not have made that act against us.

But we had only a very few in that Parliament who appeared openly to be our friends,
or friends for liberty to tender consciences, in those days; namely, Edmund Waller,
senior, Esq., who was termed Witt Waller; he was principled against persecution,
and for liberty of conscience, and always kind to us; and one Michael Mallett, Esq.;
who afterward was convinced of the truth, and frequented our meetings,
even in suffering times, when our meetings were kept out of doors in the streets,
in Westminster and London.
And sir John Vaughan, then a young man, appeared also for us,
and afterward was convinced of the truth,
and went to our meetings when we were persecuted upon the conventicle act,
and was imprisoned in Newgate with our friends, for a little time,
being taken at a meeting at Mile-end.
He continued afterward among our friends, and visited us in prison;
and though at length some of his relations drew him aside, to his great prejudice,
yet he retained a kindness, even when he came to be earl of Carberry,
and continued friendly to us when he was an old man, and until his latter end;
not wholly forgetting what conviction and knowledge
of the truth he received when among us.

There were also some few more of the members of that Parliament,
friendly toward us at that time when we appeared before them;
but the majority being resolved and bent to persecution,
they passed the bill into an act.
Upon which great persecution and imprisonments followed.
