== Chapter XIII

The people called Quakers were left under severe persecutions,
oppressions and sufferings, as before mentioned, when king Charles the second died,
and his brother the duke of York succeeding, was proclaimed king.
A fear entered many, and a question, What would now become of Protestant dissenters?
expecting either the continuance of that persecution,
which was endeavoured for some time after, or greater; besides the danger of popery,
the king being of that profession.
In a serious consideration of these things, I had a very lively opening,
early on a first-day morning, that the Lord would be good to his people,
and they should have ease, even under that king`'s reign;
and I intimated the same to our brethren at our morning meeting, to their comfort.

Accordingly it came to pass, through the good hand of the Lord our God,
that after we had used great endeavours to make the king sensibly
understand the greatness of our suffering and persecution,
in the several parts thereof; as, the great number of prisoners,
the great havoc and spoil made by informers, and by bailiffs upon exchequer processes,
etc., and all on account of our tender consciences,
and the exercise thereof toward Almighty God; I say,
after the king was made sensible thereof, and understood the same,
by degrees we obtained relief for the oppressed and afflicted.

What care, industry, and methods were used and taken to procure the same,
and how granted and obtained, I may give some relation of;
being willing to make use of all opportunities under divine Providence,
to do my suffering friends what good I could, as the Lord has been pleased to enable me,
which he has often done: blessed be his name.

In order to give the king to understand the heavy, unmerited sufferings,
persecutions and oppressions we were left under by his brother, king Charles the second,
and which were still continued, renewed, and increased upon us, our dear friends,
Gilbert Latey, Alexander Parker and myself,
presented him the case of fourteen hundred and sixty of our friends then prisoners.

Our beloved friend, Robert Barclay and myself,
made application to the king for the liberty of our consciences,
that we might be freed from all those severe persecutions we were exposed to,
and suffered under;
I having then a large and free opportunity to discourse the king upon that point,
and to remind him of king Charles the second`'s declaration for liberty to tender consciences,
A+++.+++ D. 1672.

Upon further solicitation and petition, a commission was obtained from the king,
directed to sir Robert Sawyer, the attorney general,
to issue out warrants to release so many of our friends
out of the prisons in England and Wales,
as the king could legally discharge, being under processes as his prisoners;
whereupon great numbers were discharged.
All which the Lord enabled me earnestly to solicit and pursue with great industry,
until our friends were released.

The informers continuing eagerly to make spoil and havoc upon our goods,
thereby seeking our ruin, for our innocent religious meetings,
which they hunted and haunted up and down, in city and country;
I was greatly pressed in spirit to make complaint to the king,
by way of petition against them and their injurious
and unwarrantable proceedings against us.

Whereupon the king gave order to summon those informers in and about London,
to appear before two of his commissioners, appointed to hear and examine our complaints,
face to face, that they might see how matters of fact, i.e.:
their excessive spoil upon our friends`' goods; their bearing false witness,
and forswearing themselves, as many of them had done,
in several cases against various persons; could be proved and made out,
according to our complaints, and to make report thereof to the king.

All which was proved, and made evidently appear before the said commissioners,
at two sundry meetings at Clifford`'s inn, to the informers`' own faces,
to their great confusion and shame,
and to the weakening their hands and abating their persecutions;
so as by degrees they came to be stopped,
especially after the said commissioners had made their report to the king;
and some of the informers were prosecuted by other dissenters, for perjury,
and some of them stood in the pillory for the same.

Particular application was made to the king for a noli prosequi,
or a stop to be put to the processes, qui tarn writs, out of the exchequer, etc.,
which were commonly issued out against some hundreds
of our friends in many parts of the nation,
for twenty pounds per month,
and two-thirds of estates made forfeit to the king and prosecutors,
for being absent from parish churches, so called,
upon old statute laws made against popish recusants.
A commission from the king was accordingly obtained,
to put a stop to those exchequer writs, processes and estreats,
which prevented the ruin of many families.
To effect this relief I earnestly solicited, and laboured early and late,
as if it had been to save many lives,
until one time I was almost disabled by a fit of sickness, but the Lord restored,
revived and helped me: blessed be his name forever.

I shall proceed to give some more particular accounts of our applications
and endeavours relating to these cases before hinted,
as they were presented to the king, and how far relief was obtained.

[.embedded-content-document.address]
--

[.letter-heading]
To King James the Second.

[.blurb]
=== The humble application of the people called Quakers.

Whereas it has pleased Almighty God, by whom kings reign,
to take hence the late king Charles the second, and to preserve you peaceably to succeed,
we your subjects heartily desire that the Giver of all good and perfect gifts,
may please to endue you with wisdom and mercy, in the use of your great power,
to his glory, the king`'s honour, and the kingdom`'s good.
And it being our sincere resolution, according to our peaceable principles and conduct,
by the assistance of Almighty God, to live peaceably and honestly,
as becomes true and faithful subjects, under the king`'s government,
and a conscientious people, that truly fear and serve God;
we do humbly hope that the king`'s tenderness will appear and extend with his power,
to express the same; recommending to his princely clemency,
the case of our present suffering friends hereunto annexed.

--

This petition, with the case and account of the number of prisoners annexed,
was presented together to the king, and by him accepted, the 3rd day of the first month,
called March, 1684-5, by George Whitehead, Alexander Parker, and Gilbert Latey.

[.embedded-content-document.address]
--

[.letter-heading]
To the King.

[.blurb]
=== The distressed case and request of the suffering people commonly called Quakers, humbly presented.

[.salutation]
Showing,

That according to accounts lately given, above fourteen hundred of the said people,
both men and women, are continued prisoners in England and Wales,
only for tender conscience toward Almighty God that made them.
Many under sentence of premunire, and many near it;
not for refusing the duty or substance of allegiance itself,
but only because they dare not swear: others under fines on the act for banishment;
many on writs of excommunication; besides some hundreds have died prisoners,
many by means of this long imprisonment, since the year 1680, as it is judged,
thereby making widows and fatherless, and leaving poor innocent families desolate,
in distress and sorrow.
These two hard winters`' confinement tending also
to the destruction of many in cold holes and jails,
their healths being greatly impaired thereby: besides,
the violence and woeful spoil made by merciless informers, on the conventicle act,
upon many convicted, unsummoned and unheard in their own defence,
both in city and country.
As also on qui tam writs, and other processes, for twenty pounds a month,
and two-thirds of estates seized for the king: all tending to the ruin of trade,
husbandry, and industrious families; to some not a bed left,
to others no cattle to till their ground, or give them milk, nor corn for bread or seed,
nor tools to work withal: and all these, and other severities,
done under pretence of serving the king and the church,
thereby to force us to violate our consciences, and consequently to destroy our souls,
which we are very tender of, as we are of our peace with God and our own consciences,
though accounted as sheep for the slaughter.
And notwithstanding all these long sustained extremities,
we the said people do solemnly profess and declare, in the sight of the heart-Searcher,
that we have nothing but good will and true affection to the king,
praying for his safety and the kingdom`'s peace.
We have never been found in any seditious or treasonable designs,
as being wholly contrary to our Christian principles and holy profession.

And knowing that where the word of a king is, there is power, we in Christian humility,
and for Christ`'s sake,
entreat that the king will please to find out some
expedient for our relief in these cases,
from prisons, spoil and ruin.

And we shall, as in Christian duty bound, pray God for the king`'s welfare in this world,
and his eternal happiness in that which is to come.

[.signed-section-context-close]
London, the 2nd of the First month, called March, 1684-5.

[.postscript]
====

[.blurb]
=== An account of the number of the said prisoners called Quakers, in the several counties.

Bedfordshire, 30; Berkshire, 37; Bristol, 103; Buckinghamshire, 19; Cambridgeshire, 8;
Ely, 11; Cheshire, 9; Cornwall, 32; Cumberland, 22; Derbyshire, 1; Devonshire, 104;
Dorsetshire, 13; Durham, 39; Essex, 10; Gloucestershire, 66; Hertfordshire, 18;
Herefordshire, 1; Huntingtonshire, 10; Kent, 16; Lancashire, 73; Leicestershire, 37;
Lincolnshire, 12; London and Middlesex, 66; Norfolk, 52; Northamptonshire, 59;
Nottinghamshire`', 6; Oxon, 17; Salop, 18; Somersetshire, 36; Southamptonshire, 15;
Staffordshire, 1; Suffolk, 79; Surrey, 29; Sussex, 17; Warwickshire, 31; Westmoreland, 5;
Wilts, 34; Worcestershire, 15; Yorkshire, 279; Wales, 30 Total, 1460.

====

--

Considering our continued sufferings by informers,
and those magistrates who abetted and encouraged them to take away our goods,
and that to great excess and spoil, I was deeply concerned in spirit to go to the king,
to give him further information thereof,
and to endeavour to persuade him to put a stop to those informers`' ruinous persecutions.
I was the more desirous to argue for the same,
from what the king had before promised in council the first time,
after he was proclaimed.
And acquainting my beloved friend, Robert Barclay,
with my intention of going to the king, he was willing to go with me, and accompany me,
he being more acquainted with the king than I was,
and the king having a particular respect to him,
from the knowledge he had of him in Scotland,
the said Robert Barclay being an inhabitant of that country,
and having occasion to visit him when he was there, before he was king,
it being in his brother king Charles the second`'s days.

On the 26th day of the third month, called May, 1685, about four in the afternoon,
we had admittance into the king`'s presence.

[.discourse-part]
_George Whitehead:_
We thankfully acknowledge the king`'s favour in granting us this admittance:
having acquainted the lord Peterborough with our great sufferings by informers, etc.,
in and about London, he promised us to acquaint the king therewith, which we hope he did,
for he said he had acquainted the king with our desire,
that he would speak to the recorder, that a stop be put to the informers.
And further told us,
that the king promised to send for the recorder and speak to him himself,
and that we should shortly feel the effects.
But the informers still proceed against us.

[.discourse-part]
_King:_ The lord Peterborough did speak to me, and acquainted me with it:
I have not as yet spoken to the recorder, but intend to speak to him tomorrow;
I will send for him into the prince`'s lodgings, and speak with him about it:
therefore do you put me in mind of it when I go into the House of Lords tomorrow.

[.discourse-part]
_George Whitehead:_ If the king please to speak to him and the lord mayor,
that a stop may be put to these informers,
that they may not go on to ruin families as they do,
we doubt not but it would be effectual, with the king`'s leave and favour,
I have something more to propose.

[.discourse-part]
_King:_ You may.

[.discourse-part]
_George Whitehead:_ It is about the king`'s late promise, which has two parts in it,
namely, that which concerns the defence of the church,
and that which concerns the king`'s endeavouring to follow
the example of his deceased brother the late king,
most especially in that of his great clemency and tenderness to his people.
This being the first and principal part of the promise,
the church takes hold of that part which concerns its defence.
We take hold of that part which concerns the king`'s endeavours
to follow the example of his brother the late king,
most especially in his great clemency and tenderness to his people,
and these may very well consist; which if the king please to give me leave, I shall,
under favour, remind him of some acts of clemency, which his deceased brother,
the late king, showed towards us.

[.discourse-part]
_King:_ Leave granted to go on.

[.discourse-part]
_George Whitehead:_ The late king, after his coronation,
gave out his proclamation of grace,
to release our friends out of the jails throughout England,
upon which many hundreds were released.

And in the year 1672, the late king gave out his declaration of indulgence,
for the liberty of tender consciences, and his letters Patent, or pardon,
under the great seal, to release our friends out of prisons.
Whereupon we had liberty for some years.

[.discourse-part]
_King:_ I intended a general coronation pardon,
but the reason why it was deferred until the meeting of the Parliament, was,
because some persons who are obnoxious, by being in the late plot,
would thereby have been pardoned, and so might have come to sit in Parliament,
which would not have been safe.
But I intend that your friends shall be discharged out of prison.
And for the declaration you speak of in `'72,
I was the cause of drawing up that declaration,
and I never gave my consent to the making of it void:
it was the Presbyterians who caused it to be made void, or cancelled, in Parliament, etc.

[.discourse-part]
_George Whitehead:_ They were our adversaries to be sure, that caused it to be made void.
The king may defend the church of England, and yet grant indulgence,
which may very well stand together, so as liberty to tender consciences may be allowed,
with such moderate defence of the church as may not destroy conscientious dissenters.

[.discourse-part]
_King:_ I am of that mind that they may consist.

[.discourse-part]
_George Whitehead:_ There is a plain instance in the said declaration,
the late king grants indulgence and liberty to tender consciences;
and yet engages to preserve the church of England in doctrine and discipline;
and if the king please, I will leave him the said declaration of indulgence,
for the sake of that passage, to remind it; for I have it.

[.discourse-part]
_King:_ You need not leave it, for I have it without book.

[.discourse-part]
_George Whitehead:_ The imprisonments, as also the great spoil made by informers,
are still very hard upon many in and about London, and other parts;
five warrants at once have been executed upon one person, amounting to fifty pounds,
being ten pounds a warrant: we entreat the king to put a stop to these informers,
for many are greatly disabled by them, and about giving over their trades and shops;
although we are as willing to pay our taxes and civil
duties to the king as any other people.
And by the close imprisonment of many, even here in London, in Newgate jail,
some of our friends have been so suffocated,
that they have been taken out sick of a malignant fever, and in a few days died.

[.discourse-part]
_King:_ I intend your friends shall be released out of prison;
and I will consider of a way how to stop the informers;
but they having a part of the fines,
I must consider which way I may best take to stop them, and ease you.
+++[+++or to the very same effect.]

[.discourse-part]
_George Whitehead:_ We have just exceptions against the conventicle act itself,
in several clauses.

[.discourse-part]
_Robert Barclay:_ Convicting men behind their backs, is contrary to the law of nations.

[.discourse-part]
_George Whitehead:_ And then the awarding treble costs against the appellant,
in case he is cast in the trial of his appeal, but no costs against the informers,
nor any provision made, that they shall make any restitution to the party grieved,
in case they be cast or nonsuited in their unjust prosecution: this appears very unequal.
And if the king please to give me leave, under favour,
I will give him one instance of a law somewhat like this against conventicles,
which was made in the reign of king Henry the seventh, for informers, prosecutions, etc.,
which was repealed in the beginning of the reign of king Henry the eighth,
by his first Parliament; yet that was more tolerable than this conventicle act, i. e.,
in the prosecution,
for we do not find that persons were thereupon convicted in their absence;
and provision is made therein for the informers, or prosecutors, if nonsuited,
to make restitution to the party grieved;
but here is no provision in this for their making any restitution.
Therefore this conventicle act is more intolerable than that repealed one,
which is not cited in the new statute book, but only mentioned as repealed;
but it is cited at large in some old ones.
We are inclinable to present an account of our sufferings to the Parliament,
wherein we desire the king`'s favourable concurrence,
and therefore thought fit to acquaint the king first with our intention;
for we are willing and desirous that he should be acquainted
with all public applications we make to the parliament.

[.discourse-part]
_King:_ What is it?

[.discourse-part]
_George Whitehead:_ It is a plain account of our sufferings in matters of fact,
of the same kind with that which we lately gave to the king,
with some reasons offered for the repeal of the conventicle act.

[.discourse-part]
_King:_ Let me see it, and I will give you my opinion concerning it.

[.discourse-part]
_George Whitehead:_ We intend to show it to the king.

[.discourse-part]
_Conclusion._
And we humbly and thankfully acknowledge the king`'s favour,
in admitting us thus far to be heard.

On the 1st day of the fourth month, 1685,
George Whitehead and Gilbert Latey had access to the king,
with the papers of the suffering case of our friends,
having the case fairly transcribed at length, and a summary abstract thereof,
for the king to take which he pleased; which George Whitehead tendered in this wise:
"`We are come to give the king the case of our suffering friends, as we were engaged:
here is the case at large, and the abstract, the king may take which he pleases.`"

[.discourse-part]
_King:_ I will take the abstract.

[.discourse-part]
_George Whitehead:_ When shall we wait the king`'s pleasure to have his sense upon it?

[.discourse-part]
_King:_ You need not wait now.

[.discourse-part]
_George Whitehead:_
We would not willingly miss our opportunity to present it to the Parliament.

[.discourse-part]
_King:_ You may deliver it when you please.

After Robert Barclay and I had been with the king, and discoursed him as before related,
Robert Barclay expressed himself very much satisfied in my discourse with him,
and in the king`'s behaviour towards us, and hearing matters so fully and well as he did:
so that we had still hopes of some relief from the great hardships of imprisonment,
and that a stop would be put to those devouring persecutors, the informers.

[.embedded-content-document.address]
--

[.blurb]
=== To the king and both Houses of Parliament: the suffering condition of the peaceable people called Quakers, only for tender conscience towards Almighty God; humbly presented.

[.salutation]
Showing,

That of late above one thousand five hundred of the said people, both men and women,
having been detained prisoners in England, and part of them in Wales,
some of which being since discharged by the judges, and others freed by death,
through their long and tedious imprisonment, there are now remaining,
according to late accounts, about one thousand, three hundred, and eighty three;
above two hundred of them women.
Many under sentence of premunire, both men and women,
and more than three hundred near it; not for denying the duty,
or refusing the substance of allegiance itself, but only because they dare not swear:
many on writs of excommunication, and fines for the king,
and upon the act for banishment.
Besides above three hundred and twenty have died in prison,
and prisoners since the year 1660; nearly one hundred whereof,
by means of this long imprisonment, as it is judged,
since the account delivered to the late king and Parliament, in 1680,
thereby making widows and fatherless, and leaving them in distress and sorrow:
the two last hard winters`' restraint,
and the close confinement of great numbers in various jails,
unavoidably tending towards their destruction,
their healths being evidently impaired thereby.

And here in London,
the jail of Newgate has been from time to time crowded within these two years,
sometimes near twenty in one room, to the prejudice of their health; and several poor,
innocent tradesmen, of late, have been so suffocated by the closeness of the prison,
that they have been taken out sick of a malignant fever, and died in a few days after.

Besides these long continued and destructive hardships upon the persons of men and women,
as aforesaid, great violence, outrageous distresses, and woful havoc and spoil have been,
and still are, frequently made upon our goods and estates,
both in and about this city of London, and other parts of this nation,
by a company of idle, extravagant, and merciless informers,
and their prosecutions upon the conventicle act,
many being convicted and fined unsummoned and unheard in their own defence.
As also on qui tarn writs, at the suit of informers,
who prosecute for one-third part for themselves, and on other processes,
for twenty pounds a month, and two-thirds of estates seized for the king:
all tending to the ruin of trade, husbandry and farmers,
and the impoverishing of many industrious families, without compassion shown to widows,
fatherless, or desolate.
To some not a bed left to rest upon; to others, no cattle to till their ground,
nor corn for bread or seed, nor tools to work with:
the said informers and sheriff`'s bailiffs,
in some places being outrageous and excessive in their distresses and seizures,
breaking into houses and making great waste and spoil.
And all these and other severities done against us by them,
under pretence of serving the king and the church, thereby to force us to a conformity,
without inward conviction or satisfaction of our tender consciences,
wherein our peace with God is concerned, of which we are very tender.

The statutes on which we, the said people suffer imprisonment, distress and spoil,
are as follows; The 5th of Eliz.
chap.
33, de excommunicato capiendo.

The 23rd of Eliz, chap.
1, for twenty pounds per month.

The 29th of Eliz.
chap.
6, for continuation.

The 35th of Eliz, chap.
1, for abjuring the realm, on pain of death.

The 1st of Eliz.
chap.
2, for twelve pence a Sunday.

The 3rd of king James I. chap.
4, for premunire, imprisonment during life, and estates confiscated.

The 13th and 14th of king Charles II. against Quakers, etc., transportation.

The 22nd of king Charles II. chap.
1, against seditious conventicles.

The 17th of king Charles II. chap.
2, against nonconformists.

The 27th of Henry VIII.
chap.
20, some few suffer thereupon.

Upon indictments at common law,
pretended and framed against our peaceable religious assemblies, for riots, routs,
breach of the peace, etc., on which many, both men and women, are fined,
imprisoned and detained for non-payment, some till death.
Instance, the city of Bristol,
where a great number have been these many years straitly confined and crowded in jail,
mostly above one hundred on such pretence, about seventy of them women, many aged.
And in the city of Norwich, in the years 1682, and 83, about seventy were kept in hold,
forty five whereof in holes and dungeons for many weeks together,
and great hardships have been and are in other places.
So that our peaceable meetings are sometimes fined on the conventicle act,
as for a religious exercise, and other times at common law, as riotous, routous, etc.,
when nothing of that nature could ever be proved against them,
there being nothing of violence or injury, either done, threatened,
or intended against the person, or property of any other whatsoever.

The during and tedious imprisonments are chiefly on the writs de excommunicato capiendo,
upon the judgment of premunire, and upon fines, said to be for the king.

The great spoil and excessive distresses and seizures,
are chiefly upon the conventicle act, and for twenty pounds a month,
two-thirds of estates, and on qui tam writs.
In some counties,
many have suffered by seizures and distresses above eight years last past,
and writs lately issued out for further seizures in several counties,
for twenty pounds a month, amounting to the value of many thousands of pounds,
sometimes seizing for eleven months at once, and making sale of all goods and chattels,
within doors and without, both of household goods, beds, shop goods, moveables, cattle,
etc., and prosecution hereupon still continued, and in some counties much increased.
So that several, who have long employed some hundreds of poor families in manufacture,
and paid considerable taxes to the king, are greatly disabled from both,
by these writs and seizures, as well as by long imprisonments.
So many Sergemakers of Plymouth, as kept above five hundred poor people at work,
were disabled by imprisonment: many in the county of Suffolk, under a long imprisonment,
were sentenced to a premunire,
one whereof employed at least two hundred poor people in the woollen manufacture,
when at liberty.
Omitting other instances, that we may not seem too tedious,
these may evince how destructive such severities are to tirade and industry,
and ruinous to many poor families.

On the conventicle act, within these two years past,
many in and about this city of London, have been extremely oppressed,
impaired and spoiled in their estates and trades,
upon numerous convictions and warrants made against them in their absence,
upon the credit of informations sworn by concealed informers,
many of them impudent women,
who swear for their profit in part of the fines and seizures,
their husbands being prisoners for debt through their extravagancies.
The warrants were commonly made to break open and enter houses,
which is done with rigour and great spoil, not sparing widows, fatherless,
or poor families, who are sustained by their daily care and industry,
nor leaving them a bed to rest upon:
the fines upon one justice`'s warrants amounting to many hundreds of pounds;
frequently ten pounds a warrant,
and two warrants at once for twenty pounds executed upon one person,
and three warrants at once from another justice, for sixty pounds upon another person,
and all his goods carried away in about ten cart-loads;
and five warrants at once for fifty pounds upon another,
besides what we have suffered by others in the like kind.
And in this destructive course the informers have encouragement,
and are allowed still to go on,
to the ruining many families in their trades and livelihoods;
some being so discouraged and disabled,
that they are forced to give over their shops and trades.

These informers being accepted for credible witnesses,
yet parties swearing for their own profit and gain,
in the absence of the persons prosecuted, we think is very hard, and an undue proceeding,
not consistent with common law or justice.

As also convicting and fining us upon their depositions,
unsummoned and unheard in our own defence, and so keeping us ignorant of our accusers,
unless upon traverse of our appeals.
This procedure appears contrary to the law of God, common justice and equity,
and to the law and justice of the ancient Romans, and of nations.

And although it has been openly manifested, upon trial of appeals,
at several quarter sessions, both for Middlesex and London, and other places,
that the depositions of many informers have been false in fact,
yet the great trouble and charge in the traverse of appeals,
and the great encouragement informers have from him who grants the most warrants,
has been a discouragement to many from seeking such difficult remedy,
considering also the treble costs against the appellant, in case he succeeds not,
or is not acquitted upon trial.
Whereas neither costs nor restitution is awarded
or given against the informers for unjust prosecution.
Some also have refused to grant appeals,
and others denied copies of warrants to prevent appeals;
and whether this be equal or just, pray consider, you that are wise and judicious men;
and whether it be for the king`'s honour, and the people`'s interest, that idle, drunken,
extravagant informers,
should either be encouraged or allowed to go on thus to ruin trade,
husbandry and families, or to command and threaten justices of peace,
with the forfeiture of a hundred pounds,
if they do not make convictions and issue out warrants,
upon their bare informations and uncertain depositions,
frequently in the absence of the accused.

Lastly, one-third part of the fines being assigned to the king, he can only remit that,
but the informers and poor being assigned two-third parts,
seems not to allow him to remit them,
how much cause soever may appear to him to extend his favour in that case.
Is not this against the king`'s prerogative, to restrain his sovereign clemency?
And how far it reflects upon the government, and is scandalous thereto, for beggarly,
rude informers, some of them confident women, not only to command,
threaten and disquiet justices, peace officers, etc., but to destroy the king`'s honest,
industrious, and peaceable subjects, in their properties and estates,
is worthy of your serious considerations?
And whether the said conventicle act ought not therefore justly to be repealed?
A noted instance of the like case, we have concerning the statute of the 11th Henry VII,
chap.
3, for determining certain offences and contempts, only upon informers`' prosecutions,
being repealed in the first year of king Henry VIII.
chap.
6, though that, in some respects, was more tolerable than this.

Be pleased to make our case your own, and do to us as you would be done unto;
as you would not be oppressed or destroyed in your persons or estates,
nor have your properties invaded, and posterities ruined,
for serving and worshipping Almighty God, that made all mankind,
according to your persuasions and consciences, but would enjoy the liberty thereof.
We entreat you to allow the same liberty to tender consciences,
that live peaceably under the government, as you would enjoy yourselves;
and to disannul the said conventicle act, and to stop these devouring informers,
and also take away all sanguinary laws, corporal and pecuniary punishments,
merely on the score of religion and conscience,
and let not the ruin and cry of the widow,
fatherless and innocent families lie upon this nation, nor at your door,
who have not only a great trust reposed in you for
the prosperity and good of the whole nation,
but also do profess Christianity, and the tender religion of our Lord Jesus Christ.

And notwithstanding all these long sustained extremities, we the said suffering people,
do solemnly profess and declare in the sight of the all-seeing God,
who is the searcher of hearts,
that as we have never been found in any seditious or treasonable designs,
they being wholly contrary to our Christian principle and profession,
so we have nothing but good will and true Christian affection to the king and government,
sincerely desiring his and your safety, prosperity and concurrence in mercy and truth,
for the good of the whole kingdom.

Having thus given you in short, the general state of our suffering case,
in matter of fact, without personal reflection, we, in Christian humility,
and for Christ`'s sake,
entreat that you will tenderly and charitably consider of the premises,
and find out some effectual expedient or way for our relief from prisons, spoil and ruin.

--

After the king was given fully to understand our hardships,
through the great persecutions and sufferings, which many of our innocent,
conscientious friends had long undergone, both in their persons and estates;
various applications having been made to him for relief from the same;
he was pleased to grant a comprehensive warrant or commission,
to the then attorney general, sir Robert Sawyer, in our suffering friends`' behalf,
including the several sorts of processes, convictions, and judgments,
which many then suffered under, even by laws never intended against us,
especially by those made and designed against popish recusants.
These were often perverted by persecutors,
and they many times exceeded the severity of those laws in their mal-administrations,
executions, and outrageous distresses, havoc, and spoil of goods, as also close,
unmerciful confinements of men and women`'s persons.
Many of the forfeitures, fines and confiscations were made forfeit to the king,
and imprisonment during his pleasure;
and many suffering by such old laws as were made against popish recusants,
in the reigns of queen Elizabeth, and king James the first;
and this affecting king James the second, being a Papist,
he might the more easily conclude it in his power, and the prerogative of the crown,
to pardon and relieve dissenting Protestants from their extreme oppressions.

[.offset]
A copy of the aforesaid warrant and commission follows:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
James R.

Whereas we are given to understand, that several of our subjects,
commonly called Quakers, in the schedules hereunto annexed, are either convicted,
or upon process in order to their conviction of premunire for not swearing,
or indicted or presented for not coming to church, or convicted for the same,
and several of them have been returned into our exchequer,
and in charge for twenty pounds per mensem,
according to the statutes in that case provided,
and some of them lie in prison upon writs de excommunicato capiendo,
and other processes for the causes aforesaid,
and we being willing that our said subjects, and other our subjects,
commonly called Quakers, who are, or have been prosecuted, indicted, convicted,
or imprisoned for any of the causes aforesaid,
should receive the full benefit of our general pardon,
which we have been pleased to grant to our loving subjects, by our royal proclamation,
with all possible ease to them, our will and pleasure is, and we do hereby authorize,
will, and require you to cause such of our subjects commonly called Quakers,
who are in prison for any of the causes aforesaid,
to be forthwith discharged out of prison, and forthwith to stop and discharge,
or cause to be discharged, by giving your consent on our behalf, all fines, forfeitures,
or sums of money, charged upon any of our subjects, commonly called Quakers,
for not coming to church; or set upon them any process for the same;
as also all processes, indictments, presentments, and convictions,
for any of the said causes, by entering noli prosequi, or otherwise,
as you shall judge necessary for rendering that our pardon
most effectual and beneficial for our said subjects;
and for your so doing, this shall be your warrant.

Given at our court at Whitehall, the 15th day of March, 1685-6,
in the second year of our reign.
To our trusty and well beloved, our attorney general: by his majesty`'s command.

[.signed-section-signature]
Sunderland, P.

--

When this warrant was granted and delivered to us, the attorney general,
sir Robert Sawyer, was not in London, but nearly forty miles from there,
at his country house at Highcleare in Hampshire;
and friends in London being very desirous that our friends in the
several prisons in the cities and counties throughout England,
might forthwith be released;
it was concluded that two or three of us should take
a journey to the said attorney general,
and deliver him the aforesaid warrant from the king;
and obtain a warrant or liberate thereupon,
to discharge and release our friends in and about London.

John Edge,
Rowland Vaughan and myself were desired forthwith to undertake
the journey to the attorney general for that service.
At which time I was but weakly in body, and so much indisposed as to my health,
having laboured and attended much at court for our friends`' ease and relief,
that I thought myself very unfit for that journey, for I then kept my chamber.
Howbeit, they not being willing to go without me,
having been mostly concerned in solicitation to obtain
the said warrant from the king to the attorney general,
I was in the greater strait,
and after a short consideration was persuaded and concluded to go with them,
if possibly I might be enabled to perform the journey.

We were part of two days and the morning following,
before we reached the attorney general`'s, who civilly received and entertained us,
when we had produced the king`'s commission to him;
and we quickly persuaded him to give instructions to our then companion, Rowland Vaughan,
to draw up a warrant to release our friends, who then were prisoners in London,
And according to his instructions Rowland drew up several
warrants to discharge our friends out of prison,
which the attorney general signed that day;
to get which done he would have us stay dinner,
as it was near the fourth hour before we could get all done and signed, to come away.
It was within night before we got to Theal, about four miles beyond Reading,
where we stayed at an inn, and the next day came to Brentford;
before which time I was recovered,
and was so well that I could travel much better than when I left London;
wherein I thankfully observed the merciful providence of God,
in affording me health and ability beyond expectation.

In a short time the attorney general returned to London, to his office in the temple,
where I attended him, with Gilbert Latey sometimes, to sign the rest of the warrants;
which according to his direction, Rowland Vaughan had prepared,
to discharge the rest of our friends out of prisons throughout England,
so far as he had power given him by the commission aforesaid,
which took up considerable time to see effected.
The prisoners by degrees were released,
although we had something to do to obtain the warrants for release in some places,
especially at Bristol, because of the fees demanded.
The town clerk detained our friends there in prison, for non-payment of his demands,
which occasioned our complaint against him to the king;
and I debating the matter with him before the attorney general,
he was persuaded to submit the matter to our friends`' courtesy and freedom,
and was desirous I should let him have the attorney general`'s
warrant to discharge our friends when he returned to Bristol;
and accordingly I entrusted him with it,
whereupon he got them released out of prison there.

We were greatly concerned to importune the king to put a stop to the ruinous prosecutions
and persecutions of the mercenary and merciless informers in London and Middlesex,
and presented several petitions and complaints against them to him;
the Lord having laid a weighty concern upon me, and enabled me by his power,
in faith and zeal for his truth and suffering people, to pursue them,
in order to discover their deceits and wickedness,
their unlawful and unjust proceeding against us, to the government,
for a due examination and proof thereof; which at last was obtained,
pursuant to our petitions and complaints.

I also wrote a short request to the king,
to appoint commissioners to hear us and the informers face to face,
that we might have a fair opportunity to prove the
matters of fact complained of against them,
to their faces.
The king granted my request, and gave commission accordingly,
which was delivered me by the secretary freely, without fees.
And I, with some others, prosecuted the same effectually against the informers.

We were constrained to repeat our complaints by way of petition to the king,
because those persecuting informers,
even after the king had expressed some clemency and compassion towards us,
and averseness to persecution, would take no notice thereof for some time,
but contrary thereto, confronting the king`'s favour,
would renew their unjust and ruinous prosecutions frequently against us;
until they met with open detection and reprehension before the king`'s commissioners,
for their great injustice, false swearing, clandestine convictions,
excessive and outrageous distresses and havoc which they made and
caused to be made upon the goods and estates of our friends,
tending wholly to disable and ruin them,
and all this occasioned only for their tender consciences towards Almighty God,
in sincerely serving and worshipping him, to whom only we are accountable for the same.

Upon the said request to the king,
to appoint commissioners to hear us and the informers face to face,
he gave commission to two persons,
whom he nominated to hear us and make report of the case to him.
The commissioners were R. Graham and P. Burton, esquires,
to whom we delivered the king`'s commission;
and they authorized me to give out summonses to those
informers whom we had complained against,
as also to those friends who were persecuted and injured by them.
I had liberty to summon whom and as many as I thought fit,
both of those informers and of our friends in and about London and the county of Middlesex,
to appear before the said commissioners at Clifford`'s inn, the 4th of June, so called,
1686.

Having beforehand collected,
and fairly stated the particular cases of above fifty of our friends,
sufferers by the informers`' unjust prosecutions and false informations,
I sent out summonses for them to appear before the said commissioners,
on the day and at the place appointed,
and to bring their witnesses who could detect the informers of their swearing falsely, etc.
And likewise we gave timely notice by summons, to many of the informers,
who were chiefly concerned.

When we were at Clifford`'s inn the day appointed,
we met a great company of informers without door,
who seeing a large number of our friends, the informers were in a great rage,
and some of them cried out, Here comes all the devils in hell; and seeing me, they said,
And there comes the old devil of all.

Jeffery Nightingale and Peter Lugg, esquires, justices of peace, came also,
against whom the informers were offended,
and some of them had entered actions against the first,
because they had refused to grant warrants against some of our friends,
or to convict them in their absence.

Being called before the commissioners into a large upper room,
to manage and prove against the informers, our complaints and charges,
which were comprehended in our petition to the king;
and having in readiness the cases fairly and distinctly
written in above twelve broad sides of sheets;
I began first with those cases wherein the informers had sworn falsely in fact,
producing each friend`'s case in order, and each one was called upon,
and the particular informer, or informers therein charged,
called in to hear his and their charge, and proof made against him and them;
which was effectually done, and made obvious against many of them,
to their great confusion and shame, to be so proved false witnesses and false swearers,
against our friends, in plain matters of fact;
as their informing upon oath against several of our friends,
for being at such and such meetings, which they were not at;
and also for having meetings at Certain places and houses, where there were no meetings;
and sometimes swearing upon trust from one another`'s false and presumptuous information.
The women informers were desperate in their swearing,
and making oath against our friends, as well as the men, who were the grand informers.

The several cases of swearing falsely in fact,
could not well be contained in six broad sides.
I showed the commissioners one case after another,
in order for a thorough consideration and examination of each,
and produced plain demonstration and positive proof of each article as we went along,
not only by the sufferers themselves, but also by various credible witnesses present,
how grossly and abominably those informers had forsworn themselves,
and borne false witness in several cases.
The king`'s commissioners, and the said justices present,
were made apparently sensible thereof, and could not otherwise be,
when they saw those informers so confounded and put to a nonplus,
that they could not defend themselves.

One thing by the way was somewhat remarkable; that when their captain, John Hilton,
was called to come in, to answer for himself before the commissioners,
his companions would not allow him to come in before them; for they said,
he was in drink, and not in a fit condition.
He was several times called for; at last he told the messenger that went out for him,
that he cared not for the king`'s commissioners; which answer of his was told them;
and they understanding what disorder he was in, passed by his incivility.
How little regard or honour he showed to the king;
yet such drunken informers esteemed themselves eminent
servants to the king and the church in those days.

Secondly; Breaking open doors of houses and shops with force and violence,
by informers and constables,
to make distress upon our household and shop goods to great excess;
for sometimes they carried away by cart loads.
Thus was I served as well as many others, who had their doors broken open,
and goods taken away to great excess and spoil,
so that the cry of these oppressions was loud among our neighbours,
and we are sure the cry thereof entered into the ears of the Lord of Sabaoth,
and he did plead our innocent cause.

We gave to the said commissioners, the first day of our meeting,
so many instances and proofs against the informers`' abuses, false swearing,
violence and spoil, that they seemed almost weary with hearing them that day,
matters of fact being evidently proved against the informers to their faces,
and to their great shame and confusion.
The season also was hot, and the room pretty much thronged;
which made the time of so many cases and discoveries, the more wearisome to them,
although on the first day of our meeting we did not go through scarcely the fourth
part of the cases and charges which we had to produce before them.
The commissioners appointed another day of meeting, which was the 14th of the same month,
called June, at which time we met again, and many of the informers aforesaid,
who appeared as they were called, one after another.
Thomas Hilton brought a lawyer with them in his gown, to plead their cause and help them;
but when he attempted, he could not vindicate their unjust and barbarous proceedings,
their forswearing themselves, convicting persons in their absence,
breaking open houses to seize and take away our goods, etc.
For these unwarrantable proceedings he had no colour of law to plead;
though he would at first have excused the informers a little faintly.
I showed him out of the conventicle act, how they had exceeded the severity thereof,
and how mistaken he was in his allegation for them;
so that he was quickly silenced before the commissioners and his clients the informers.

At the second meeting we got not through half of our complaints
and charges against those persecuting informers.
The commissioners then thought they had enough of them for their discovery,
and to ground their report upon to the king: and the informers to be sure,
had enough to their shame and confusion.

In the close of that our last meeting,
I made this proposal for the commissioners`' consideration:
that seeing it was evidently proved before them,
how frequently the informers had forsworn themselves in plain matters of fact,
and made such spoil upon the king`'s peaceable subjects,
they would consider whether they ought not to be discouraged and stopped
from any further proceeding in their prosecutions against us,
that they might not be reputed to be the king`'s servants therein,
as they would be esteemed, while seeking the ruin of his subjects, by swearing falsely,
etc. or to this effect.

To which proposal the commissioners made little answer;
but they conceived it was not within their commission
to give their opinion or judgment in that case;
yet one of them said, that in point of prudence he thought it safest for them to desist.

The guilty informers being clearly detected, and their falsehoods exposed,
they were in a great rage against me,
especially for proposing to have them discouraged and stopped
from any further prosecution against us.
They were so bitterly enraged against me, railing, and threatening,
that friends somewhat feared they would endeavour to do me a mischief.
I told them, I feared them not, nor what they could do,
for I was bound in conscience to make them manifest to the government;
they should not deter me by their threats;
for I dared and could appear before the highest in authority against them;
which I questioned whether they dared do, to vindicate themselves.

I can truly say, I was greatly assisted and strengthened by the Lord`'s power,
in true faith and zeal, to clear my conscience in those concerns,
against that persecuting spirit, and the destroying work thereof,
I bless the worthy name of the Lord our God, who strengthened and sustained me,
in that and many other exercises and services, for his blessed truth and people`'s sake.

I may not omit an exercise that befell some of us,
between the two meetings we had before the king`'s commissioners at Clifford`'s inn,
before mentioned, the 4th and 14th of June, so called, 1686,
in the following case of John Dew, William Ingram, John Vaughton and George Whitehead.

Some of the informers having procured a warrant, bearing date the 12th of June, 1686;
the persons abovesaid were apprehended thereupon, on the 13th day of the same month,
at their usual meeting place in Gracechurch street, London, being about to come away,
and no proclamation made for their departing;
and in the said warrant no mention was made of Quakers, but of disloyal, factious,
and seditious sectaries, no ways justly chargeable upon the persons there met,
and apprehended.

We four were taken prisoners, and went with the constable to the lord mayor`'s,
where we waited several hours for his coming from his worship: when he came,
I signified to him,
that we were engaged to appear that week before the
king`'s commissioners at Clifford`'s inn,
who had order to enquire into certain complaints
we had made to the king against the informers,
and showed him one of our summonses to the informers to appear also before them.
And seeing none of them appeared to give evidence against us, according to the warrant,
whereby we were apprehended, I desired we might be dismissed,
especially seeing our habitations were well known,
and we should be ready to appear upon lawful summons.

But this the mayor would not grant, but we must stay till witnesses, i. e., informers,
came to give evidence against us, who he said, would come by and by, but none came;
though under pretence of their coming by and by, we were detained, I think,
till about ten o`'clock that night; at last the mayor came to us and demanded security,
or for us to be bound over by recognizance to appear at the next sessions for the peace,
and in the mean time, to be of good behaviour,
and presently caused the clerk to write the same.
I told him we were willing to promise to appear, if the Lord please,
but not to be bound to good behaviour,
seeing there was no misbehaviour proved against us; for I conceived,
that to require bond for good behaviour, implied some misbehaviour,
which could not be proved against any of us; to which the mayor answered,
"`You are a company of coxcombs; make their court order,`" said he to his clerk.
Howbeit he withdrawing a little space of time,
and the constable and some of his officers seeming unwilling we should be sent to prison,
after some private consultation,
and the said constable refusing to be bound to prosecute us, knowing nothing against us,
the mayor took our words to appear at the next sessions without our bond;
so we were dismissed for that time.

Appearing at the sessions, and our names being called, and none,
either informers or others, coming in against us, upon proclamation made in court,
we were discharged, so that the informers, who caused us to be taken,
were disappointed of their design against us.
They would have been glad to have had us confined to prevent
our appearance the second time at Clifford`'s inn,
before the said commissioners, that we might not further detect their misdemeanours,
irregularities, forgeries, and false swearing, but the Lord our God, who stood by us,
frustrated their evil designs in that case,
so as we had liberty to appear again at Clifford`'s inn,
to make further public discovery of the injustice
and wickedness of those implacable and restless men.
Their ungodly gain, gotten by rapine and spoil upon the king`'s peaceable subjects,
did not prosper; though for a long time they swarmed about in city and country,
they were so extravagant and profuse,
that many of them could not keep out of prison for debt;
and others were made to turn beggars when their informing trade was stopped.
In order whereto,
the Lord was pleased to make our endeavours successful in a short
time after our second appearance at Clifford`'s inn.
At our second meeting we got through but about half of our cases,
having the second part also fairly drawn up.
But no further meeting could we have, to examine the second part of our complaints,
against the informers`' work.
The commissioners thought they had heard enough at the two meetings before,
though I would gladly have met again, having many sufficient witnesses,
to detect the informers`' abuses,
which were particularly and plainly specified in the second part as well as in the first;
and they are worthy to be fully recorded and divulged to posterity,
that it may be understood and seen what wicked courses have been taken by informers,
to ruin honest people, and how such vile persons have been exposed,
to their utter shame and contempt.

Seeing we could not have a third meeting,
I persuaded the commissioners to allow me an hour or two in an afternoon,
to show them the second part of our case, before they drew up their report to the king.
This they granted, and accordingly I read it to them.
After that I went to them again, and desired to see their report,
which they showed me a draught of;
and then I saw it was very deficient and improperly drawn up:
for instead of stating plainly matter of fact,
as it had been proved before them against the informers swearing falsely,
unjust prosecutions, and cruel oppressions, etc., against us;
the commissioners gave their opinions for some easier ways of dealing with us;
as for not going to parish church, twelve pence a Sunday, etc.,
I told them how improper that was for them to report to the king;
it was rather to dictate and prescribe to the king what penalties we should suffer,
whereas their business was to make true report of matter of fact,
which we had complained of, and which was plainly proved and made appear before them,
against the informers`' unjust and injurious proceedings.
One of the commissioners told me how hardly they were put to it, to draw up their report,
being sent to out of London, from some great person or persons of the church,
and requested to do or report nothing that might disable the informers,
they being of so great service to the church,
as I understood his relation of the caution sent them, for I took good notice thereof:
notwithstanding this, I pleaded for justice to`" be done us, in their report to the king,
respecting matter of fact.

Whereupon they were so honest, as to amend their report, and made it more to the purpose:
and then we gave the king some further intimation of our case, in the following letter:

[.embedded-content-document.letter]
--

[.salutation]
May it please the king,

Since the king was graciously pleased to refer our
late petition about the informers`' proceedings,
to the enquiry of two appointed commissioners in Clifford`'s inn, we,
with many of our suffering friends, have, at two sundry times,
clearly proved matter of fact complained of in our said petition,
to the informers`' faces before the said commissioners, to their full satisfaction;
and therefore, many cases were omitted to avoid tediousness,
as is signified and implied in their report;
as their convicting our friends upon oath behind their backs;
their frequent false swearing, upon the bare report from one to another;
their taking compositions or bribes, that is of other people;
besides their breaking open houses, excessive distresses; charge of appeals;
ruining families and trades, etc., not expressed;
their troubling such justices with suits,
as scruple granting warrants against us unsummoned,
as in the case of justice Nightingale and justice Lugg.
And since the discovery as aforesaid,
they have appeared very revengeful against many of us,
causing several to be taken and bound over to sessions, and others to be imprisoned,
as they threatened us at the time of their false swearing, etc.,
was discovered to the commissioners: the two Hiltons and their accomplices,
as also Christopher Smith and John Brown, Arthur Clayton, and other informers,
being most busy and violent against us: since which,
several of the informers have been indicted and convicted of perjury,
at the quarter sessions for London, and for Middlesex, prosecuted by other people.

These, with the said report considered, we hope the king will be graciously pleased,
in his wisdom to put a speedy stop to these informers,
and restrain them and the rest of their confederates from further spoiling of us, etc.

[.signed-section-context-close]
10th of the fifth month, 1686.

[.signed-section-context-close]
Delivered the day following at Windsor, to the king,
per George Whitehead and Gilbert Latey.

--

[.asterism]
'''

[.blurb]
=== Some proposals to the Lord Chancellor about the informers.

Since the king in cabinet, on the 11th of July, 1696,
has been graciously pleased to refer the matters
complained of by the people called Quakers,
in their late petition against the informers,
together with the report made thereupon by two appointed commissioners, namely:
Rd. Graham and Ph. Burton, esquires, to the Lord High Chancellor of England,
in order to correct the irregular proceedings of some justices and the informers,
we the said people do humbly propose as follows:

[.numbered-group]
====

[.numbered]
1+++.+++ That no person charged on the conventicle act, 22 Car.
2, for meeting, be convicted, or warrants issued out for distress,
without being first summoned to appear before the convicting justice,
to answer his accusers or prosecutors face to face, according to the law of God,
and of nations, and the common course of justice.

[.numbered]
2+++.+++ That no persons be admitted to take upon them to be informers or prosecutors,
but such as are credible persons, and responsible in estate,
to make satisfaction to the party grieved, if unduly or unjustly prosecuted.

[.numbered]
3+++.+++ That those informers named in the said report,
made by the king`'s commissioners aforesaid, having committed great abuses,
irregularities and misdemeanours, not only through their unskillfulness in law,
but dishonesty, as by false swearing, and some of them by compositions and bribery, etc.,
be utterly disabled from any further prosecuting henceforward,
together with all their party, servants, or deputy informers, confederates and abettors;
some whereof being already convicted of wilful perjury,
and various others having voluntarily made oath as witnesses,
in the case of the perjured persons, in the court of quarter sessions,
held at Guild-hall, London, the 14th day of July, 1686,
thereby attempting to make good the same information,
wherein their associates were convicted of perjury, as aforesaid.

[.numbered]
4+++.+++ That the intention of the said act, in employing informers,
and providing reward for their encouragement,
being for discovering or finding out conventicles, which supposes them obscure or hidden,
as well as seditious, or tending to insurrection,
this work of informers being altogether useless and groundless,
in reference to the public, known, and constant meetings of the people called Quakers,
which have never tended to sedition or rebellion,
but always have been peaceable and inoffensive towards the king and government;
it is therefore humbly requested, that a stop may be put to the informers`' prosecutions,
with respect to those known public meetings of the said people.

[.numbered]
5+++.+++ That no convicting justice may be admitted to sit judge
or chairman in the traverse or trial of appeals;
seeing the appellant by law appeals from the convicting justice
to the judgment of the other justices of the quarter sessions.

[.numbered]
6+++.+++ That the peace officers, constables, church wardens, or overseers of the poor, etc.,
may not be forced to turn informers, either by any justice of peace,
or court of sessions, before whom any supposed offender,
or person under prosecution is or may be brought.

[.numbered]
7+++.+++ That no justice of the peace may be prosecuted for not gratifying the informers,
or not receiving their informations, he being dissatisfied with them;
either because they are not persons of credit,
or that he does not believe in his conscience that they are credible witnesses;
or for his refusing to grant them warrants,
without summoning the prosecuted parties to answer them face to face.

[.numbered]
8+++.+++ That neither the convicting justices of peace, nor constables, or other officers,
after distress made, be suffered to divide, embezzle,
or detain to themselves the monies levied, or any part thereof, as some have done,
but that the whole sum of money levied, be brought into the sessions,
according to the act; many having suffered by embezzlements,
that they could not have the legal benefit of appeals.

[.numbered]
9+++.+++ None ought to be allowed to prosecute as witnesses, or make oath for profit or gain,
nor be allowed part of the fines for swearing against any persons under prosecution;
that being a snare whereby many have been tempted to forswear themselves,
and have so done in plain matter of fact.

====
