== Chapter XVII

Testimonies of George Whitehead

We shall conclude with the character given him after his decease, in two testimonies,
the one written by Richard Claridge, his intimate friend and acquaintance,
who survived him but a few weeks;
the other by the friends of the monthly meeting at Devonshire house, London,
in whose neighbourhood he had been an inhabitant many years.

Richard Claridge`'s Testimony concerning George Whitehead.

George Whitehead was one whom the Lord had highly dignified in his day,
calling him about the sixteenth year of his age,
to the acknowledgment of the blessed truth, and about the eighteenth,
to bear a public testimony to it,
in which testimony the Lord preserved him faithful until the end of his day,
which was on the 8th of the first month, called March, 1722,
being about eighty-seven years of age.

The Lord had bestowed on him such a measure of his divine gifts of faith, wisdom,
judgment, understanding, self-denial, patience, love, meekness, utterance,
and other graces of the spirit,
that he was an instrument in his hand to open the blind eyes,
and turn men from darkness to light, and from the power of Satan to God.

And as it pleased the Lord to make him an able minister of the New Testament,
so his speech and his preaching was not with enticing words of man`'s wisdom,
but in demonstration of the Spirit and of power,
that our faith should not stand in the wisdom of men, but in the power of God; 1 Cor. 2:4-5.
; so that when he spoke, he spoke as the oracles of God;
and when he ministered, he did it as of the ability which God gives; 1 Pet. 4:11.

He was not as many which corrupt the word of God, but as of sincerity,
but as of God in the sight of God, spoke he in Christ; 2 Cor. 2:17.

His ministry was a sound and living ministry,
and many yet living have a testimony thereunto in their hearts and consciences.

He was an eloquent man, and mighty in the Scriptures, and fervent in the spirit;
Acts 18:24-25, A good man, and full of the Holy Spirit, and of faith,
and much people was added unto the Lord; Acts 11:24.

He was an elder, whom the Lord had anointed unto the spiritual and evangelical ministry,
raised up among many others, near the first breaking forth of this gospel day,
after a long night of apostacy,
which had overspread this and other nations with gross darkness,
in matters relating to Christianity.

And though bonds and afflictions attended him, yet none of these things moved him,
neither counted he his life dear unto himself,
so that he might finish his course with joy and the
ministry he had received of the Lord Jesus,
to testify the gospel of the grace of God; Acts 20:23-24.

For having this ministry, as he had received mercy, he fainted not;
but renounced the hidden things of dishonesty; not walking in craftiness,
nor handling the word of God deceitfully, but by manifestation of the truth,
commending himself to every man`'s conscience in the sight of God; 2 Cor. 4:1-2.

* * *

The Testimony of Devonshire house monthly meeting,
A short account and testimony concerning our dear and worthy friend, George Whitehead.

Our ancient worthy friends, who in the morning of this gospel day,
were about the same time sent forth to declare the truth, with this our deceased friend,
are now most of them gone to their rest;
yet the generality of friends of middle age may have had a long knowledge of him,
and of his gravity, wisdom and abilities, beyond many in the church of Christ;
but for the sake of the younger friends, that have not had that knowledge,
and for the encouragement of those in faithfulness, that are,
or may be convinced of the blessed truth, or receive a gift of the ministry,
we of the monthly meeting of Devonshire house, of which he was a very eminent member,
about the space of fifty years,
esteem ourselves engaged to give in this our short account and testimony concerning him.

We find he was born at Sun-bigg, in the parish of Orton, in the county of Westmoreland,
about the year 1636, of honest parents, who gave him an education in grammar learning.

At or about the seventeenth year of his age, when some friends,
by the mighty power of God, were gathered to be a people,
the Lord was pleased to visit him, and by the testimony of truth,
he was reached unto and convinced of the necessity of an inward
and spiritual work to be known and wrought upon the souls of men;
and of the emptiness and insufficiency of outward show and formality,
out of the life and power.
In the year 1654, and the eighteenth year of his age,
the Lord sent him forth to preach the everlasting gospel in life and power;
and having passed through York, Lincoln and Cambridge,
he had some service in his journey, and travelling on foot,
came a youth into Norfolk and Suffolk, where he visited some few meetings of friends,
and steeple-houses, and meetings of sober professors; at one of which,
near a whole meeting was convinced, by the mighty power of God,
through his lively and piercing testimony and prayer.

He continued some months in Norfolk and about Norwich, where having meetings,
he preached the everlasting gospel, and thereby turned many from darkness to light,
and from the power of sin and Satan, unto God and his power;
that people might not continue in empty forms and shadows,
but come to the life and substance of true religion;
and to know Christ their true Teacher and Leader: and great was his service,
labour and travel in those counties, whereby many were reached unto, convinced of,
and established in the blessed truth;
and some raised up to bear a public testimony thereunto.
But he suffered great opposition, hardships, long and sore imprisonments,
and severe whipping, for his testimony to the truth, in those his tender years,
although few now remain who were living witnesses thereof;
yet by a journal of his own writing, which we desire may be printed,
the same will more largely appear; and the perusal of which, we hope,
may be edifying and serviceable to the present and succeeding generations.
We would not be too particular in relating his suffering, imprisonments,
services and travels, throughout most parts of this nation,
but proceed to say something of our own experience, and that knowledge we had of him,
and of his eminent services and great concern for the peace
and prosperity of the church of Christ everywhere,
during his long abode with us in this city.

We may say,
he was one whom the Lord had fitly qualified and
prepared by his divine power and Holy Spirit,
for that work whereunto he was called;
and whereby he was made one of the most able ministers of the gospel in our day.
He was a large experiencer of the work of God,
and deep mysteries of the heavenly kingdom,
and was frequently opened in meetings to declare of, and unfold the same,
in the clear demonstration of the Spirit and power, dividing the word aright,
opening and convincing the understandings of many,
who were unacquainted with the way and work of truth; and comforting, confirming,
and establishing the people and children of the Lord, in their journey towards Zion.

He was not only a zealous contender for,
and asserter of the true faith and doctrine of our Lord and Saviour, Jesus Christ,
in a sound and intelligible testimony,
but also was valiant and skilful in the defence thereof,
against adversaries and opposers of the same; and one,
who through a long course of many days,
was careful to adorn the doctrine of our holy profession
by a circumspect life and godly conduct,
wherein the fruits of the spirit, namely: love, joy, peace, long-suffering, gentleness,
goodness, faith, meekness, and temperance, did eminently shine forth through him,
to the praise and glory of God.

Being thus qualified, and of a meek and peaceable disposition,
he was had in good esteem among most sorts of people that were acquainted with him;
which tended much to the opening his way in his public service for truth:
and frequent solicitations unto several kings and Parliaments, bishops and great men,
of our land, for the relief and release of his suffering friends and brethren,
under sore persecutions and hard imprisonments, and for liberty of conscience,
and also for relief in the case of oaths.
In these labours of love and eminent services among other brethren,
this our dear friend was principally exercised, and the Lord was with him,
and made way for him in the hearts of the rulers of the land;
so that his faithful labour was often crowned with success,
to the comforting and rejoicing of the hearts of many suffering brethren.

He was a good example to the flock,
in his diligent frequenting of first and week-day meetings for public worship,
and other meetings for the service of truth, so long as his ability of body remained;
willing to take all opportunities for publishing and promoting the truth;
zealous to support good order and discipline in the church of Christ.
And as he was not suddenly for taking hold of any,
so he was as exemplary in not being forward to cast any off,
in whom there appeared anything that was good,
being always desirous to encourage the good in all, condescending to the weak,
but admonishing the faulty in the spirit of meekness and wisdom,
that they might be preserved in love to truth, and come into the unity of the one Spirit,
which is the bond of peace.

We may truly say, he was a tender father in the church,
and as such was of great compassion, sympathizing with friends under affliction,
whether in body or mind; a diligent visiter of the sick,
and labouring to comfort the mourning soul; careful to prevent,
and diligent in composing differences.

Dear friends, much more we might say on the behalf of this our dear deceased friend,
an elder worthy of double honour;
but it is not with us to give large encomiums of the dead;
we have rather chosen to give but short hints of some of
the Christian virtues and qualifications he was endued with,
believing there is a witness in the hearts of many yet remaining,
that does testify for him and his faithful labours and service in his day;
desiring the Lord may raise up many, in the room of this and other worthy elders,
some of which are lately removed from us, and we believe, taken into mansions of glory,
in the kingdom of God.

It pleased the Lord to visit this our dear friend,
with some severe pains and weakness of body,
so that he was disabled for some weeks from getting to meetings,
but he often expressed his desires for the welfare of the church of Christ,
and that friends might live in love and unity.

He continued in a patient, resigned frame of mind to the will of God,
waiting for his great change, rather desiring to be dissolved and be with Christ, saying,
the sting of death was taken away.
He expressed a little before his departure,
that he had a renewed sight or remembrance of his labours
and travels that he had gone through from his first convincement;
he looked upon them with abundance of comfort and satisfaction,
and admired how the presence of the Lord had attended and carried him through them all.

He departed this life in great peace and quiet, the 8th day of the first month, 1722-3,
about the eighty-seventh year of his age; and we firmly believe he died in the Lord,
and is at rest from his labours, and his works follow him.

He was a minister of the gospel about sixty eight years,
and was buried the 13th of first month, in friends`' burying ground, near Bunhill-fields,
among many of his ancient brethren,
being attended by a very large number of friends and others.

Signed in, and on the behalf of the monthly meeting, at the Devonshire house,
the 15th day of the third month, 1723, by,

William Mackett, Theodore Eccleston, John Knight, Lascells Metcalf, Arnold Frowd,
William Price, John Belch, Benjamin Sanchey, Robert Plumsted, John Baker,
Jonathan Scarth, Thomas Eedes, John Lunn, Thomas Broadbank, Peter Ext on, Richard Price,
Richard Lea, Thomas Crawley, James Lambert, Josiah Knight, William Hodgson, John Lee,
Joseph Rossell, John West, Samuel Mackerness, Caleb Hughes, Miles Walker,
Jonathan Stevens, Samuel Bowley, Samuel Scott, John Hayton, George Fossick, Joseph North,
William Dodd, Elizabeth Fossick, Richard How, Herman Hingsberg, Thomas Mayleigh,
William Teaguij, Benjamin Bealing.
