[quote.epigraph, , Psa. 115:1]
____
Ascribe the glory of all to God, for his mercy and truth`'s sake.
____

[quote.epigraph, , Isa. 50:5]
____
The Lord has opened mine ear, and I was not rebellious, neither turned away back.
____

[quote.epigraph, , 1 Sam. 7:12]
____
Hitherto has the Lord helped us.
____

== Brief Testimony of George Whitehead

The following brief notice of George Whitehead,
is taken chiefly from the Testimony respecting him,
given by the monthly meeting of Devonshire house, in London, of which he was a member.

He was born at Sun Bigs, in the parish of Orton, in Westmoreland, about the year 1636,
and was educated at a grammar school in that neighborhood;
where he appears to have made such progress in his literary pursuits,
as to have been employed for some time as a tutor.

His parents had a view to educating him for the
office of a minister in the Established Church,
and his religious disposition and inquiring mind no doubt
raised their sanguine hopes of his fitness for the office.
In his seventeenth year, however,
he embraced the opinions of the then universally despised Quakers;
and in the following year he went forth, traveling on foot,
to preach the Truth in several of the midland counties,
and on one occasion nearly all the persons composing a meeting which he was addressing,
were convinced through his lively testimony and prayer.

"`He was one,`" says the document referred to,
"`whom the Lord had fitly qualified and prepared by his divine power and Holy Spirit,
for that work whereunto he was called,
and whereby he was made one of the most able ministers of the gospel in our day.
He was a large experiencer of the work of God and deep mysteries of the heavenly kingdom,
and was frequently opened in meetings to declare of and unfold the same,
in the clear demonstration of the spirit and power; dividing the word aright,
to the opening and convincing the understandings of many who
were unacquainted with the way and work of Truth;
and to the comforting, confirming,
and establishing of the people and children of the Lord,
in their journey and travel towards Zion.

"`He was not only a zealous contender for and assertor of the
true faith and doctrine of our Lord and Savior Jesus Christ,
in a sound and intelligible testimony,
but also was valiant and skillful in the defense thereof,
against adversaries and opposers of the same;
and one who through a long course of many days,
was careful to adorn the doctrine of our holy profession,
by a circumspect life and godly conduct, wherein the fruits of the Spirit: love, joy,
peace, long-suffering, gentleness, goodness, faith, meekness, and temperance,
did eminently shine forth through him, to the praise and glory of God.

"`Being thus qualified, and of a meek and peaceable disposition,
he was had in good esteem among most sorts of people that were acquainted with him;
which tended much to the opening his way in his public service for Truth,
and frequent solicitations unto several kings and parliaments,
bishops and great men of this our land,
for the relief and release of his suffering friends and brethren,
under sore persecutions and hard imprisonments, and for liberty of conscience,
and also for relief in the case of oaths:
in which labor of love and eminent services among other brethren,
this our dear friend was principally exercised;
and the Lord was with him and made way for him in the hearts of the rulers of the land,
so that his faithful labor was often crowned with success,
to the comforting and rejoicing of the hearts of many suffering brethren.

"`He was a good example to the flock,
in his diligent frequenting of first and week-day meetings for public worship,
and other meetings for the service of Truth, so long as his ability of body remained;
willing to take all opportunities for publishing and promoting the Truth;
zealous to support good order and discipline in the church of Christ:
and as he was not for taking hold suddenly of any,
so he was as exemplary in not being forward to cast any off,
in whom there appeared any thing that was good;
being always desirous to encourage the good in all, condescending to the weak,
but admonishing the faulty in the spirit of meekness and wisdom,
that they might be preserved in love to Truth, and come into the unity of the one spirit,
which is the bond of peace.

"`We may truly say, he was a tender father in the church,
and as such was of great compassion,
sympathizing with Friends under affliction whether in body or mind;
a diligent visiter of the sick, and laboring to comfort the mourning soul:
careful to prevent, and diligent in composing differences.

"`Dear friends, much more we might say on the behalf of this our dear deceased friend,
an elder worthy of double honor;
but it is not with us to give large encomiums of the dead;
we have rather chosen to give but short hints of some of the
Christian virtues and qualifications he was endued withal,
believing there is a witness in the hearts of many yet remaining,
that does testify for him and his faithful labors and service in his day;
desiring the Lord may raise up many in the room of this and other worthy elders,
some of whom are lately removed from us, and, we believe,
taken into mansions of glory in the kingdom of God.

"`It pleased the Lord to visit this our dear Friend
with some severe pains and weakness of body,
so that he was disabled for some weeks from getting to meetings;
but he often expressed his desires for the welfare of the Church of Christ,
and that Friends might live in love and unity.

"`He continued in a patient resigned frame of mind to the will of God,
waiting for his great change; rather desiring to be dissolved and be with Christ, saying:
'`The sting of death was taken away.`'
He expressed a little before his departure,
that he had a renewed sight or remembrance of his labors and travels,
that he had gone through from his first convincement;
he looked upon them with abundance of comfort and satisfaction,
and admired how the presence of the Lord had attended and carried him through them all.

"`He departed this life in great peace and quiet, the 8th day of the first month, 1722-3,
about the eighty-seventh year of his age; and we firmly believe he died in the Lord,
and is at rest from his labors, and his works follow him,
"`He was a minister of the gospel about sixty-eight years;
and was buried the 13th of the first month,
in Friends`' burying ground near Bunhill Fields, among many of his ancient brethren;
being attended by a very large number of Friends and others.

[.signed-section-context-close]
"`Signed in and on the behalf of the monthly meeting at Devonshire house,
the 15th day of third month, 1723, by forty Friends.`"
