== Chapter III

Being set at liberty without being sent to our respective homes,
we could then travel where the Lord pleased to order us,
to visit our friends and meetings: and the Lord laid a concern upon me,
especially to visit our friends and meetings in Norfolk and Norwich,
where I had laboured in the gospel, and had suffered before,
and also in High Suffolk and Essex, and some other parts,
where the Lord did greatly strengthen and assist me by his power in his service;
and made the same effectual to his praise,
and his people`'s comfort and confirmation in the living faith, which is in Christ Jesus,
his light and grace.

Although our hardships in Bury prison were extreme, as before related,
yet the Lord caused all to work together for good to us;
our faith and strength in Christ came to be greatly increased,
the blessed truth promoted, many convinced thereof, and added to the church,
and gathered into our spiritual communion and Society,
through the great sufferings of those times, and our faithful testimony borne therein.
The great persecutions then against us,
caused great inquiry among the unprejudiced and well disposed people,
who could not but think, that persecution and cruelty against us for religion,
was no sign of a good religion in the persecutors;
and that the patient sufferers were more like true Christians than the persecutors.

In the time of our severe confinement in Bury jail before mentioned, my fellow prisoners,
George Fox and George Rose,
received a gift and part in the ministry of the everlasting gospel,
and were enabled by the power and Spirit of Christ,
to thunder out judgment against deceit and wickedness,
and to preach the way of life and salvation;
which they did in the zeal and love of the Lord God,
and ministered according to their several gifts and abilities,
received from the giver of every good and perfect gift.

George Rose became a great traveller in the work of the Lord beyond the seas,
not only in Holland and Germany, but also in the American colonies, as New England,
Virginia, Bermudas, Barbados, and other remote places.
I have not a particular account of his travels in those parts and islands,
and we have often desired a more full relation thereof.
After various difficulties and dangers he passed through by sea,
and great travels and service in those foreign parts in America, he,
with some other Friends, lost their lives in a storm at sea, near the coast of Virginia,
as has been related to us.

George Fox the younger,
did not live long after an imprisonment he underwent
when king Charles the second came in;
though that was no hard imprisonment, being removed from Harwich to Lambeth,
on some groundless suggestions or complaints.
He died some time after he was at liberty, in the country.

John Harwood, who was prisoner with us in Bury jail, while we were there confined,
patiently suffered with us, and walked orderly and soberly;
and was for some days together in fastings, low and humble in his spirit,
and had some part in the ministry: but within three or four years after we were released,
he came to loss by proceeding disorderly with a widow toward marriage,
but was disappointed: and what added to his hurt,
he conceived prejudice against some of the brethren, as George Fox senior and others,
for disowning his irregular and unwarrantable procedure.
This I mention to prevent reflection,
that we may not be unjustly upbraided by his miscarriage.

When I was at Colchester and Coggeshall side, one Okely, or Okey, priest of Stanway,
three miles from Colchester, busying himself against the Quakers,
in his ignorant opposition, to whom Stephen Crisp gave some answer,
gave us occasion to desire a public discourse with him in his parish church, so called,
at which place a meeting and time was agreed to; but when we came there,
the priest took up most of the time in preaching upon the text,
"`Remember the law of Moses, my servant, which I commanded unto him in Horeb,
for all Israel,`" etc.
The scope of his discourse being to prefer the Scriptures for their only rule.
But it being near night before the sermon was ended, and days then short,
we had very little time to discourse matters;
neither did he know how to begin to charge us,
but questioned us about Christ and his human nature, as their term is.
We owned his divine nature, and his being man also, as he is our only Mediator, etc.,
according to Scripture.
But our dear ancient friend, Robert Ludgater,
questioning the priest about the two natures of Christ, as that he called human,
and the divine, the priest turned it into a sort of levity and impertinency.
It growing night, the meeting soon ended, with no advantage,
but disadvantage to the priest, the people being generally civil,
and more serious than their priest.

Before the winter in 1656 was ended,
the Lord gave me an opportunity to visit Friends at London, of which,
before my imprisonment at Edmundsbury, I was prevented;
that visit was very acceptable to Friends there,
and I had very good service in and through the meetings,
in the ministry and demonstration of the holy Spirit and truth of Christ;
and many were convinced thereby, while I was among them, which was not long then;
but I was concerned to return into Essex and Sussex.
And having visited meetings at Colchester, Coggeshall, and other parts of Essex,
as in Denge hundred, and various parts of the county, and also at Sudbury and Haverhill,
and other places in Suffolk, a concern fell upon me to have a meeting at Saffron Walden,
where I had a large and good meeting, though toward the conclusion,
some professors made a little opposition, but were soon answered and silenced.
Yet notwithstanding, some Friends of Essex and myself being at an inn that evening,
at supper, the bailiff of the town with a constable, or some officer,
and others with them, came in and caused me to be taken away, set in the stocks,
and there kept for some time in the night, before they let me out;
and this without any breach of law or crime laid to my charge,
but only out of a peevish humour, and their own envious wills,
and to cast causeless contempt upon me and my friends.
I wrote to the bailiff next morning, to know if he had any matter of fact against me,
or any more to say to me; but he gave me no answer, so I went from there to Cambridge,
and parts adjacent, and visited meetings in the love of God to and fro, in the countries,
until I returned into Essex, to Colchester.

I had a meeting at Nayland in Suffolk, not far from Colchester,
where the common people were so rude that they would
not allow the meeting to be quiet within doors,
but were ready in appearance, to pull down the house, which was but small;
whereupon we drew out the meeting into a meadow ground,
near the town`'s end on Essex side.
The meeting was large,
and I had a good and full opportunity to declare and demonstrate the living truth,
with power and dominion given me of God, whose power was over all,
and came so over the meeting, that it was quiet,
though it was held for near three hours together, and the season then somewhat cold.

That morning before the meeting, the Friend of the house where it was appointed,
at Nayland, came to me weeping, and under trouble,
because some wicked fellows of the town had threatened
to kill me if I had a meeting there.
I pitied the man for letting in such fears from their threats,
and told him I did not fear them,--I was given up in the will of God,
in whose hands my life is, and they should do no more than he permitted them;
I doubted not that the Lord would restrain them and their envy and wicked purposes;
and I would not disappoint the said meeting, nor alter the appointment thereof.
So I encouraged the poor Friend against his fears, and the Lord appeared for me,
both in his service and in my own and Friends`' preservation,
by his divine power that gave us dominion and a quiet meeting, as before related.
Let the dominion, glory and praise, be ascribed and returned to him forever.

After a few weeks the Lord again laid a concern upon me to have another meeting at Nayland,
which, accordingly was appointed at the same Friend`'s house where the first was.
But this second meeting we had in his yard, or little orchard,
to which many Friends of Colchester, and other places in Essex and Suffolk, came.
After we had for some time waited upon the Lord in silence,
I was moved to stand up and preach the everlasting gospel,
and testify against sin and wickedness, against the beast and false prophet,
and against the devil`'s persecuting power and ministry.
After I had for a considerable time declared the truth in the meeting, a person,
a pretended gentleman, came rushing in with a constable and rude company,
and with violence pulled me down as I was declaring the truth; and some of them,
with the constable, had me to Affington, to our old adversary, John Gurden, who,
when I came before him, and he had information given him against our said meeting,
presently began to threaten me.
I desired his moderation to hear me before he passed judgment.
"`You are a moderate rogue,`" said he.
"`Moderate rogue!`" said I; "`such language does not become a justice of peace,
especially one professing Christianity.`"
He in great fury highly threatened me,
by which I apprehended he then designed to lay me fast in jail again,
as he had caused several of us deeply to suffer.
After his angry threats, he returned into his parlour,
where his son and the priest of the parish were to consult.

In the interim I sat in his hall, waiting upon the Lord, and some Friends with me;
and then I secretly breathed in spirit, that if it might stand with his will,
he would not then permit that persecutor to send me to Bury jail,
where I and others had so lately, and for a long time, deeply suffered;
for his malice ended not with that hard imprisonment of ours.
The Lord was pleased to answer my desire,
and immediately to show me that he should not send me to prison,
but cause me to suffer by stripes.
I was greatly refreshed, strengthened, and given up in the will of the Lord,
patiently to endure that punishment,
which the invidious persecutor was permitted to inflict upon me,
it being for Christ`'s sake and his gospel truth,
wherein I had great peace and strong consolation in him, for whose sake I suffered.

Being soon called into the parlour before the said John Gurden, and his son Robert,
the priest being present, I was examined by several questions, as of my name, country,
and reason of travelling abroad,--to which I gave particular answers,
and plainly told him and those present,
how God would overturn them and take away their power,
who were persecutors and oppressors of his servants or seed; and withal,
that God would limit him, i. e. John Gurden,
that he should not effect all his evil designs.
He deridingly bid me "`Go quake.`"
I said.
"`Do you then despise quaking?`"
He answered, "`Yes; I do despise quaking.`"
I said, "`Then you despise that which the word of the Lord has commanded.`"
"`How prove you that?`"
said he.
"`Bring me a bible,`" said I; a bible being there,
I showed him Ezekiel 12:17-18. "`Moreover the word of the Lord came to me, saying;
Son of man, eat your bread with quaking, and drink your water with trembling,
and with carefulness.`"
Whereupon he could not vindicate his despising quaking.

His clerk took part of my examination in writing as he ordered him, which being read,
John Gurden required me to sign it.
I signified that it was deficient, or lamely taken.
He would have urged me to sign it;
then I took the pen and began to write my exception against the deficiency of the relation,
intending to sign the same at the bottom of what the clerk had written.
But John Gurden plucked the pen out of my hand,
and said I should write nothing but my name, which I positively refused;
if he would not allow me to write my distinction,
he ought not to impose upon me to sign a lame relation, which was but in part true.

When thus treated, and being ordered to withdraw into the hall,
John Gurden and his son directed the clerk to draw up a
warrant to have me severely whipped next day at Nayland,
the town where I was taken and haled out of the meeting.
John Gurden came out to me into the hall, and highly threatened me again,
having a law book in his hand, which I took to be Dalton`'s Justice of Peace,
and there read some abstract of an ancient statute or law, against vagrants,
sturdy beggars, idle and dissolute persons, loiterers, peddlers, tinkers, etc.,
with the penalties, etc.:
intimating to me that they had ordered me to be whipped at Nayland;
and if I came again into that country, I should be branded in the shoulder for a rogue;
but if I came a third time I should be hanged.
I answered, "`I am no such person as you have mentioned; you are an old man,
and going to your grave; you do not know how soon the Lord may put an end to your days,
and disappoint you of your evil designs against me.
However, I fear not your threats,
if the Lord whom I serve require my return into these parts, I must obey him.`"
"`I know I am an old man,`" said he.
"`Aye,`" said I, "`you are old in iniquity; it is high time for you to repent.`"

I was called to hear their warrant for my punishment read,
and the constable to have his charge of execution given him, which being read,
Robert Gurden charged the constable to see their warrant executed upon me to the purpose,
at his peril.
I told him I could expect no better from him, who falsely swore against Henry Marshall,
an honest man, at the quarter sessions, that he said Christ was a vagabond;
whereupon Henry was wrongfully fined as a blasphemer,
and kept in jail with us at Edmundsbury, nigh twelve months;
his words being most grossly perverted,
quite contrary to what he said when taken prisoner;
for being accused for a vagabond or vagrant, Henry told them, "`That Cain was a vagabond,
though he had a city upon earth; but Christ was no vagabond,
though he had not whereon to lay his head.`"
How contrary was this to the information given upon oath against him at sessions.
Which I believe the said Henry told us above forty times in prison,
and which I also charged the said Robert Gurden with,
one time when he came scornfully to look upon us, when we were in prison;
and reminding him thereof before his father,
when he charged the constable to see their warrant executed to purpose upon me:
his father to excuse him, said he swore to the best of his remembrance.
I asked him if he could not remember to speak the truth?
Do men use to swear in court upon uncertainties, or doubtfully?
With other discourse.
The warrant being signed and sealed by the father and the son,
I was returned back to Nayland, in order to endure the execution thereof the next day.
That night I lodged at a public house, where I rested quietly in much peace.

[.offset]
A copy of the warrant and pass follows.

[.embedded-content-document.legal]
--

[.letter-heading]
To all constables, and all other officers whom it may concern, and to every of them.

Be it remembered, that one George Whitehead, a young man about twenty years of age,
who confesses himself to have been born at Orton, in Westmoreland,
being this present day found vagrant and wandering at Nayland, in this county,
contrary to the laws of this nation, and being thereupon brought before us,
two justices of the peace for this county,
is by us ordered to be openly whipped at Nayland aforesaid, till his body be bloody,
as the law in such case enjoins; and he is to pass from there from parish to parish,
by the officers thereof, the next way to Orton aforesaid,
before the first day of June now next ensuing.

[.signed-section-context-close]
Dated at Affington, in this county of Suffolk, the 1st day of April, 1657.

--

Be it remembered, that this bloody warrant is grounded upon a notorious falsehood;
for I was neither found vagrant nor wandering at Nayland,
but in a religious meeting for the worship of God,
and out of the same was pulled away with violence,
and had before these two persecuting justices, who, contrary to their office and titles,
have therein acted both contrary to law, justice, and to the peace of the nation,
in causing an innocent person to be cruelly scourged,
and that upon a gross and notorious falsehood.

The said warrant was the next day after its date,
put into severe execution by a foolish fellow, whom the constable got to do it.
When the constable had stripped me above the waist,
which he could not persuade myself to do, but I let them act their own cruelty,
the fellow, with a long, sharp whip, laid on so violently,
that he cut and wounded both my back and breast with long stripes,
tearing the skin and shedding blood, till some people present cried out to stop him.
There was a great number present, it being in a public place, like a market place,
in the street, and many wept to see their cruelty; yet,
by the Lord`'s power I was enabled cheerfully to bear it all with patience,
great comfort and rejoicing, even in the very time of the execution,
whereby many were amazed and smitten.
How many stripes I had, I do not well know,
but remember that the marks thereof were to be seen a long time after,
both on my back and breast.

It is also very memorable to me, how wonderfully the Lord, by his divine power,
supported me, even while they were inflicting their cruelty and punishment upon my body;
that even then my spirit was raised,
and my mouth opened to sing aloud in praises to the Lord, my God,
that he counted me worthy to suffer for his Name and truth`'s sake.

When the hand of the executioner was stayed from beating me,
by the cry or call that was made to stop him,
I told the people that it was a proof of a minister of Christ,
patiently to endure afflictions, persecutions, stripes, imprisonments,
according as the holy apostle testifies;
"`Approving ourselves as the ministers of God in much patience, in afflictions,
in stripes, in imprisonments, in tumults,`" etc., as it is more fully in 2 Cor.
vi. And while I stood with my stripes and wounds naked before them,
I then told the officers concerned, that if they had any more to lay upon me,
I was ready and given up to suffer, it being in the cause of Christ, for conscience sake.
I may not forget the wonderful power,
aid and comfort which the Lord afforded me in that suffering condition,
and the contempt my persecutors enviously designed to cast
upon me and our friends by that sort of punishment,
legally intended against rogues and thieves, but unjustly inflicted upon me,
who was innocent.

This memorial is given to warn all justices and magistrates professing Christianity,
against following the steps of those invidious, persecuting justices before mentioned.

The said execution against me, and the solemnity attending it being over at Nayland,
I took my horse and was accompanied out of the town by the constable and others,
towards Sudbury, to which town the officers with their said warrant and pass,
attended me the same day it was executed.

The next day I was passed away from constable to constable, through Clare and Haverhill,
into the edge of Cambridgeshire.
In Clare, when the warrant was produced to pass me forward, as ordered,
several persons took great notice of me, and seeing me have a pretty good horse,
and well habited, some said, "`This young man does not look like a vagrant.`"

In the edge of Cambridgeshire, we met with a constable in the field at the harrow.
And being made to understand it was about nine miles to have me the next way,
as the warrant required, to another constable toward Cambridge,
he thought it was too far for him to go with me, I said he need not trouble himself,
I knew what way to go.
He then freely delivered me the warrant, it drawing toward night.
I returned alone to find some town where I might lodge that night,
and not in the very way that I came, but somewhat more toward the south;
so I rode about five miles that evening, to a town called Steeple Bumsted, in Essex,
where I got lodging in an inn.
The inn keeper being drunk, and understanding I was called a Quaker, I heard him say,
"`I`'ll kick him from style to style;`" yet the next morning being more sober,
when I paid for what I had, he parted friendly with me.

Then I rode to Halsted and Coggeshall, and after that to Colchester,
and had several good meetings there and in those parts, and at Sudbury, and near Nayland,
aforesaid.
The country being alarmed and awakened by my suffering,
the people were the more stirred up to come to meetings,
to see and hear the young man that was so cruelly whipped at Nayland.
Many were tenderly affected and convinced,
and the truth of our testimony was the more spread and prevailed;
so that the dark wrath of man turned to the praise of God,
and I had great joy and consolation in Christ Jesus my Lord,
for whom I was freely given up to suffer,
and he did powerfully sustain and stand by me therein; glory to his name,
and dominion be to him forever.

I was more deeply concerned in spirit,
to travel and labour in the gospel ministry in that country,
and those parts where I had so greatly and openly suffered;
and often to visit those eastern counties, being supported in spirit,
and borne up above all the threats of branding and hanging,
and above the envy of that cruel, persecuting spirit,
and made to despise all the shame it could cast upon me, by reproach and contempt.

In the forepart of that summer, in the year 1657,
meeting with my dear friend and brother, Richard Hubberthorn,
we travelled together out of Huntingtonshire, from King-Rippon to Leicester,
and to Coventry, Warwick and Worcester, and visited Friends as we went in those places,
having some meetings with them.
In Gloucestershire, we met with our dear brother, George Fox senior,
at one justice Grimes`' house, a few miles from Gloucester, who with his wife and family,
were convinced of the blessed truth, as it is in Christ Jesus, his life and power.
In the court yard of this house, George Fox had a large meeting that first-day we met him.
I showed the justice John Gurden`'s bloody warrant against me,
and the pass before mentioned, at which he wondered, and was offended at his cruelty,
and minded to write to him against his persecution.

The next day I went to Gloucester, and visited those few Friends then in that city,
which was very acceptable to them.
After that, I travelled about in that county and Worcestershire,
and visited the meetings of Friends mostly round the counties,
and in part of Herefordshire; the word of Christ and of life,
being plenteously in my heart and ministry, enabled me by his power largely to preach,
to the convincing, strengthening, and comfort of many.
Although I met with opposition and contention from some Baptists,
and others in those parts, as in Gloucestershire, Lemster in Herefordshire,
and in the city and county of Worcester, where the Lord stood by me,
and strengthened me to stand against all the opposition and contention which I met with,
or stood in my way; for which I did,
and ever shall bless that divine Power whereby I was called forth,
and greatly assisted in the defence of the gospel of our blessed Lord Jesus Christ.

Our friend and brother, Thomas Goodyear, and some Baptists,
had appointed or agreed to a meeting at our Friends`' meeting place at Stoak Orchard,
near Tewksbury, to dispute or discourse matters of difference about religion;
and hearing of that appointment, I went to the meeting,
which was held in a barn where the said Thomas Goodyear and the Baptists,
and a great company of people, Friends and others were met.

The Baptist preacher began in a kind of preaching,
instead of arguing against our friends and principles; chiefly about eternal life,
where he thought we might have it, namely: in the Scriptures,
and not by following a light within; not confessing Christ or his light within,
or in man, nor to his divine revelation or immediate teaching and ministry in believers;
but placing all chiefly upon the Scriptures without, giving them the preference;
insisting on John 5:39. Search the Scriptures;
for in them you think you have eternal life, etc.
Further, in his preaching on this subject, he mentioned these words of Christ:
"`The words that I speak unto you, they are spirit, and they are life,`"

From which the Baptist thus argued: "`If the words of Christ are in the Scriptures,
then there is spirit and life in the Scriptures,
or we may find eternal life in the Scriptures:
but the words of Christ are in the Scriptures, therefore spirit and life,
or eternal life is in the Scriptures,
or we may find eternal life in the Scriptures;`" with more
such doctrine,--upon which he continued preaching so long,
I think near an hour, that after we had borne it so long patiently,
I was constrained to call out to be heard, to give answer.

I obtained silence and liberty to answer,
and then went through the heads of his objections, and gave him plain answers,
refuting them particularly; yet sincerely owning the holy Scriptures,
words and doctrine of Christ therein contained.
But the Baptist`'s argument and inference from Christ`'s words I distinguished thus:
that though the words of Christ, as proceeding immediately from his mouth,
are spirit and life when he speaks them,
yet the same words as written and only read in the Scriptures, are not spirit and life;
for many read his words without his spirit, and without a true understanding thereof.
By his saying, "`The words I speak unto you,`" they are spirit and they are life;
he does not say the words as written, much less the Scriptures or writings,
are spirit and life.
When Christ himself speaks to a soul, his words are spirit and life to that soul,
for spirit and life are in his words, when he speaks them.
But when another reads or speaks them without his spirit,
they minister neither spirit nor life.
For instance, Christ`'s calling to Lazarus when dead and buried,
"`Lazarus come forth;`" his words were spirit and life to Lazarus.
But let another read or speak the same words to a man dead and buried,
and cry to him to come forth, they will not raise him to life.
With much more in the plain demonstration and evidence of truth, against his objections;
on which he having made a large preachment, it required the longer time to answer,
which I claimed as my right on truth`'s account.

The Friends present at the meeting were much satisfied in
the defence which the Lord enabled me to make at that time,
in vindication of the blessed truth, and the friends thereof.
The auditory who were unprejudiced, were the better informed,
and their understandings opened, and the opposer and his party quieted, and so went away;
for the Lord`'s power went over all in that meeting, and truth gained ground,
though it was through some contention.

At Worcester city I had a large meeting, where I met with some opposition,
and one time from some professors, several persons of note being present;
but their dispute was soon over, for they could not maintain their opposition,
and the truth prevailed over them, to the convincing of many.
The Lord was with me in my testimony for his name,
and gave me suitable answers by his immediate power and spirit,
opening matters in vindication of the truth of the gospel,
which he had given me a dispensation of, to bear witness to his light and grace,
and to turn people thereto in their own hearts and consciences.
Glory to his excellent name and power forever.

I also had a meeting at a place called Clifton upon Teamd,
about seven miles from Worcester; it was outside in an orchard,
and many Friends and others came to it, some Friends out of Hereforshire, etc.
After I had some time to preach the truth, one John Dedicote,
esteemed a minister or priest of Richard Baxter`'s communion,
accompanied with several others of his brethren, and Colonel Birch,
as mouth of the rest with him, must needs enter into dispute against me.
His main point was to dispute against perfection and freedom from sin in this life,
as not attainable to believers or saints on this side the grave.

One or two Friends out of Herefordshire, who had been professors,
being convinced of the truth,
one of them would undertake to answer the priest in my stead, being jealous of me,
that I should not be able to deal with him because of my youth,
and the priest being ready to run into his logic and syllogisms.
I forbore a little,
and observed what essay the Friend would make to answer the priest`'s argument;
on which I quickly saw I must step in and discourse the point, and not be put by.
After I entered upon the dispute, the Friends who had been afraid of my inability,
concluded I should deal well enough with the priest,
and quietly left the controversy with me to manage.

The chief point of doctrine John Dedicote insisted upon,
was for sin and imperfection to continue in men during life; that perfection, that is,
freedom from sin, is not attainable in this life;
accusing even St. Paul with not being free from the act of sin while in the body,
or upon earth; but could not lay any actual sin or act of sin to Paul`'s charge,
or to the charge of any other of the saints who died in the faith,
which they were not freed from before their decease.
On the Scripture, Heb. 12:22-23, those attainments therein mentioned,
my opposer would not own to be attainable in this life,
particularly their being come to the spirits of just men made perfect.
He would have it construed, that was not in this life, or on this side the grave,
arguing after this manner; if perfection be not attainable on this side the grave,
then they did not come to the spirits of just men made perfect in this life,
or on this side the grave: but perfection, that is, freedom from sin,
or the act of sinning, is not attainable in this life; ergo,
they did not come to the spirits of just men made perfect on this side the grave.

I clearly saw the fallacy of his argument in the second proposition and consequence,
and the absurdity thereof,
and showed the people how the apostle then wrote to those believing Hebrews,
to whom he says: "`But you are come unto mount Zion, and unto the city of the living God,
and to the general assembly and church of the first born which are written in heaven,
and to God the judge of all, and to the spirits of just men made perfect.`"
That those believers were not then dead and in their
graves when the apostle wrote thus to them,
and told them they were come to the spirits of just men made perfect.
Can you think the apostle would write to them when they were in their graves?
Then the argument was forced to be dropped,
and some other arguments our opponent attempted, but made little of it,
being fully answered and refuted,
and matters cleared relating to the inward and spiritual work of Christ,
and his being made manifest to destroy the work of the devil,
which is sin and the pollution thereof.

I had then and oftentimes, great comfort, life,
and strength given me in pleading the cause of Christ and his righteousness
against the devil`'s cause and work of sin and unrighteousness;
and the power of Christ and his counsel did really accompany and assist me in that service,
to the confounding of such as would plead Satan`'s cause,
for the continuance of sin term of life:
in which work they were none of Christ`'s friends, servants, or ministers,
whatever their professions or pretensions were.

In this dispute the Lord showed me both the fallacies of the adversaries`' arguments,
and gave me more discovery and sight of their kind of logic,
and their crafty way of syllogizing, than ever I had before;
and quickly to find out fallacies, and many times absurdities, in their arguing,
though they pretended mood and figure for it.

The Lord gave me to perceive when a proposition was false,
and when the inference was unjustly deduced from a proposition, though in itself true;
knowing that it is a principal part of true logic in disputations,
to see that the proposition is true or truly stated,
and that the consequence which naturally follows, so that they truly agree.

After the Lord was pleased to give me a clear understanding in this matter,
between the true and the false way of arguing, between what was true logic,
and what was falsely so termed,--as there is a true
science and that which is falsely so called;
then I was the more prepared to withstand all the crafty opposition
of pretended logic and syllogisms which I met with,
both at Cambridge and other places, and valued them no more than pedantry;
and I could easily invert an adversary`'s absurdity back upon him by way of syllogism.
I have met with many priests very dull at their acquired artificial logic,
and incident to run into many absurdities,
while they would often contemn and deride us as illiterate men;
but when we have discovered and refuted their ignorance and absurdities,
then they would cry out against us, and asperse us as Jesuits.
Thus I have been often treated by them.

After the said John Dedicote and his brethren could not stand their ground,
to maintain his plea and arguments,
for the continuance of sin and imperfection in the best of saints during life.
Colonel Birch resumed the plea to maintain their point,
contrary to the apostle John`'s testimony:
"`Whosoever is born of God does not commit sin; for his seed remains in him,
and he cannot sin, because he is born of God.`"
Against this the Colonel argued from that article in the Lord`'s prayer;
"`Forgive us our trespasses, as we forgive them that trespass against us.`"
"`Therefore,`" said he, "`they had trespasses that needed to be forgiven,
and they were born of God, and were his children,
because he was their Father when they said.
Our Father which art in heaven,`" etc.

This seemed to be the chief argument that was advanced at that dispute,
wherein he appeared to go beyond the priests:
but I demonstrated the several states and degrees of children,
of such as might call God father, of such children under Christ`'s teaching,
or in his school, as needed to crave forgiveness of their trespasses;
and of such children whom John wrote unto when he said;
"`I write unto you little children, because your sins are forgiven you.`"
Had they need always to pray for forgiveness of their sins all their life time,
after their sins were forgiven?
No sure, that would imply that still they lacked forgiveness,
or were in a state of condemnation when their sins were already forgiven them,
which is very inconsistent.
To which I did not understand any reply could be given by the Colonel or priests; who,
after full discourse quietly withdrew from the meeting.

[.offset]
But further, as to the point then in question, about calling God our father, etc.

[.numbered-group]
====

[.numbered]
1+++.+++ He is so; and may be so called, as he is our Creator,
having created man in his own image: "`Have we not all one Father?
has not one God created us.`"

[.numbered]
2+++.+++ God is owned to be our father when we are begotten by his living Word,
into a measure of true and living faith in Christ, in order to be sanctified,
being adopted or chosen to be his sons and heirs of eternal life;
and being such children or sons by adoption, we have received the spirit of adoption,
whereby, as young and weak children, we cry to him, Abba Father.

[.numbered]
3+++.+++ When we did experience but a small entrance
into the work of regeneration or sanctification,
and our hearts were turned toward God with tender breathings and desires to him,
that the work might go forward and prosper, toward the completing of the new birth,
then we could truly call God, "`Our father,
having begotten us again unto a lively hope.`"

[.numbered]
4+++.+++ And though little children, whose sins are forgiven,
through repentance and faith in the name of the Lord Jesus Christ, are but weak,
and may stumble and possibly fall, so as to get some bruises or hurts,
yet the apostle John gives this encouragement to such; "`My little children,
these things write I unto you, that you sin not,`" etc.
Whereby he implies a possibility of a sinless state, as also our duty not to sin.
And also not to despair of help and recovery,
if any of us in that weak condition of little children, happen to sin, or get some fall,
hurt, or bruise, as in these following words; "`And if any man sin,
we have an advocate with the Father, Jesus Christ the righteous;
and he is the propitiation for our sins, and not for ours only,
but also for the sins of the whole world.`"
Such kindness and help has our Mediator afforded, if we do not sin willfully.

[.numbered]
5+++.+++ And furthermore, even such little children as are but weak and feeble,
who experience a measure of true faith and repentance in the name of Christ,
God is not willing to cast off, but to own them for his children and people;
and if they be sincere in their desires and love to him, and do not draw back,
but follow the Lord fully, yes,
follow the Lord Jesus Christ in and through the work of regeneration,
they will become his free born children; he will be an everlasting Father unto them,
and they shall be his sons and daughters, and heirs of his heavenly kingdom forever.

[.numbered]
6+++.+++ God was pleased to esteem Ephraim his dear son and pleasant child,
when he was humbled under his chastisement, and prayed to be turned, and repented;
see Jer. 31:18-20,
And in that low condition the Lord extended compassion and mercy to him, or that tribe.
Oh! the bowels of the tender mercies of God,
which move and are opened abundantly in his dear Son Jesus Christ,
to the truly penitent and humbled, through his fatherly chastisements.

[.numbered]
7+++.+++ Now to consider the new birth completed or perfectly formed in Christ Jesus;
such who are perfectly born from above, by the Holy Spirit,
born of water and of the Spirit, so as to be thoroughly washed, sanctified,
and made living to God in Christ, abide in him and sin not, as John said.
Whosoever abides in him, sins not; and he who is so born of God, that he cannot sin,
it is because he is so born, and his seed remains in him.
To attain to this state and stature in Christ Jesus, requires a true travail of soul,
a perseverance and growth in grace and faithfulness in the love of God,
a being rooted in love, and a real stability in truth and righteousness.
The true and heaven born child must be kept in the bosom
of the Father,--and blessed be our heavenly Father,
he has many such children, who will never forsake him who is the God of their salvation,
and who will rather die than deny the truth.
And, "`Who shall separate them from the love of Christ?`"
And, "`We can do nothing against the truth, but for the truth.`"

====

Contrary to which apostolical doctrine,
the said John Dedicote has also argued in a letter to me,
dated the 23rd of the fifth month, 1657, though I had otherwise fully informed him,
both at our dispute and by writing.
His doctrine therein is much as before,
against perfection and a sinless state in this life,
signifying that his heart is saddened,
because that perfection in this life and freedom from sin are preached up by us.
And that no error does more sadden his heart than that doctrine,
and that it is a soul ruining doctrine.

His doctrine herein is contrary to the holy apostle`'s doctrine; "`Finally, brethren,
farewell; be perfect, be of good comfort, etc.`"
The doctrine of perfection, therefore, was not to sadden their hearts,
but to comfort them.
Neither could it be either an erroneous or soul ruining doctrine;
and to affirm it to be such, is to reproach Christ and his ministry,
who preached the same doctrine of perfection and holiness.
See Matt. 5:48. Luke 6:40. 2 Cor. 7:1. Eph. 4:12. 2 Cor. 13:9. 2 Tim. 3:17.
Heb. 10:14. 1 John 4:12-13. 2 Cor. 7:1. Ps. 1:2.

This person whose heart was saddened,
because of our doctrine of perfection and freedom from sin being attainable in this life,
further affirms, that the righteous are not perfect in graces,
and that faith is imperfect;
that the faith of the best is sometimes weak and full of doubtings;
and that faith and knowledge are both imperfect.

[.discourse-part]
_Observe._
A heavy charge against the righteous, and even the best of men,
together with their graces, faith and knowledge, without exception:
but he has not affirmed this either from his own experience, or from holy Scripture;
as himself being either one of the best of men, or one really righteous,
or one in the faith of Christ, whereby he purifies the heart of a true believer;
for if by imperfect, he means sinful, or mixed with sin, or having sin,
for he joins imperfection and sin together, he, with many others of his profession,
who are but sinful ministers, do greatly err herein,
as being ignorant both of the divine graces and faith of the righteous and best of men.
It is no good sense to affirm their faith is sometimes full of doubtings;
which is little better than to tell us,
that the faith of the best is full of distrust or unbelief;
which is contrary to the nature of that true and living faith which is the gift of God,
which Christ is the author of, and a fruit of the holy Spirit.
It is also called, the faith of the operation of God;
and though there be a state of weak believers, who are weak in faith,
or of little faith for a time, yet their faith grows and increases, who follow Christ,
the author of true faith; even the most holy faith,
which was and is the saints`' victory.
The degrees and increase of faith,
prove not the faith of the best of men to be sometimes full of doubtings and imperfection.
And littleness, as to growth,
for some time proves not impurity in the nature of true faith,
if it be but as a grain of mustard seed.
It is a weakness on the creature`'s part to let in doubtings, fears or distrust,
whereby there is a declining from the faith which is the gift of God,
from whom every good and perfect gift comes.
And men`'s declining or erring from the faith,
is not the condition of any truly religious, much less of the best of men,
whose faith and confidence stands in the name and power of Christ Jesus our Lord,
in whom we receive the end, the blessed reward of our faith,
even the everlasting salvation of our immortal souls.
