== Chapter IX

In the year 1670, in the eighth month, having been in the country,
and returning to London, I was taken with a great pain in my head, whereupon I grew sick,
which turned to an ague and fever.
I became very weak in body,
so that for some weeks there appeared little hope of recovery; this sickness continued,
and I remained in much weakness about six months,
until the beginning of the second month 1671, and partly the beginning of that summer,
and then it pleased the Lord, gradually to restore me to health and strength.

In that sickness, when most weak in body,
being well prepared and freely resigned in the will of the Lord to die,
that I might ever be with him, I had an opening or apprehension,
that when I died my soul should be received into the bosom of my heavenly Father.

While I was in great weakness of body,
I was several times told of the great and cruel sufferings of our friends in Southwark,
for meeting together at their usual meeting place at Horsleydown;
how barbarously and cruelly they were used, and grossly abused by soldiers and armed men,
both horse and foot, being not only kept out of their meetinghouse in the street,
but both men and women were violently pushed with muskets and other weapons--beaten,
bruised, hurt and wounded,
and much blood shed by the blows and wounds from
those inhuman persecutors and brutish persons.
The accounts of these and such barbarities against the innocent,
did very sorrowfully affect me;
and I deeply sympathized in spirit with the innocent sufferers,
earnestly praying to Almighty God for them, that he would preserve and deliver them,
and rebuke that persecuting spirit by which they suffered:
earnest prayers with tears being then the church`'s very great concern,
which the Lord our God in his own time, graciously heard and answered;
blessed be his name.

The occasion of the barbarous persecutions against our said meeting in Southwark,
was by the following order.

[.embedded-content-document.legal]
--

[.blurb]
=== At the court at Whitehall, the 29th of July, 1670;--present, the king`'s most excellent majesty, his Highness, Prince Rupert, Lord Archbishop of Canterbury, Lord Keeper, Duke of Monmouth, Duke of Ormond, Earl of Ossory, Earl of Oxford, Earl of Anglesey, Earl of Bath, Earl of Craven, Lord Ashley, Mr. Treasurer, Mr. Vice-chamberlain, Mr. Secretary Trevor.

His majesty being informed that there have been of late,
frequent conventicles and seditious meetings, under pretence of religious worship,
contrary to and in contempt of the laws established,
at a house or building at Horsleydown, adjoining to the Artillery garden;
and that the persons who there assemble,
behave themselves in such a riotous and tumultuous manner,
that if their meetings be any longer endured,
his majesty`'s peace and the quiet of the government will thereby be manifestly endangered.
For the prevention whereof, it was this day ordered, his majesty present in council,
and by his express command, that Christopher Wren, esq.,
surveyor general of his majesty`'s works,
do cause the said house or building to be pulled down and demolished,
in case from henceforth any persons whatsoever,
shall presume to meet or hold any conventicle, or unlawful assembly therein,
under colour of religious worship.
And it was further ordered by his majesty,
that this signification of this his royal pleasure be affixed on the said building,
to the end that the owners and occupiers of the same, may take notice thereof,
to prevent and hinder such meetings at their peril.

[.signed-section-signature]
John Nicholas.

--

Which order was both affixed on the door of the meetinghouse,
and soon after put in execution; for they sent, and very much spoiled,
and pulled down the meetinghouse, and took away the boards, windows, benches and forms,
and sold them.

It is observable, that here was no judicial trial, or legal proceeding in this hard case;
but an order grounded upon information of our meetings being conventicles, seditious,
riotous and tumultuous; which information was altogether unjust and notoriously false,
and no such things could ever be proved against our assemblies or meetings.

Our innocent friends, as obliged in conscience toward Almighty God,
resolved to keep their solemn meetings in his dread and fear;
not being terrified therefrom, by the rage and violence of their persecutors,
but constantly resorted to their said meetinghouse on first-days, while it was standing.
After it was pulled down, they removed the rubbish,
that they might meet on the ground where their own house stood;
which they did until by force haled out, and barbarously used by the soldiers.

On the 25th of the seventh month, 1670,
Friends being peaceably assembled at their usual meeting place aforesaid,
there came some musketeers, and haled them forth into the street,
where the troopers came and rode in among them, in a violent, furious manner,
beating and abusing both men and women, punching them in the face and bodies,
with their carbines.
Soon after the foot soldiers came and fell upon them also, and beat both men and women,
in a cruel and outrageous manner--punching them on
the feet with the but-ends of their muskets,
till they broke some of them;
and running the muzzle of their muskets violently against the bodies of many.
Then a party of horse came desperately and strove to ride over them;
but the horses being more merciful, or naturally more gentle than the riders,
would not go forward to tread the people under foot; then the riders turning them,
curbed and reined them to do mischief.

The number of those that were wounded and sorely bruised this day,
was above twenty persons.

On the 2nd day of the eighth month, they being kept out of their meeting place aforesaid,
there came a party of foot and a party of horse,
and laid on friends in a violent and cruel manner,
knocking them with their muskets and pikes, and the horsemen with their carbines,
until the blood lay in the streets; and so they continued for some time,
until they broke several pikes and muskets, and one carbine;
and several were so beaten and bruised, that their lives were in danger.
They that were wounded and sorely bruised this day, were above thirty persons.

On the 9th of the eighth month, the soldiers, horse and foot,
came to the meeting at the aforesaid place; and one of them having a shovel,
threw dirt and mire upon both men and women, in a shameful manner.
After him, both horse and foot furiously fell upon them, striking and knocking down,
without regard to age or sex, in a very cruel manner, until they shed blood from many.
When some of the inhabitants in pity took them into their houses to save their lives,
the soldiers forced open the doors, haled them out again into the street,
and plucked off their hats that they might strike on their bare heads,
so that many had their heads broken in a grievous manner.
Thus they continued for some time, tearing men and women`'s clothes off their backs,
and haling women through the mire, by their horse sides;
some of the foot soldiers impudently putting their hands under the women`'s coats,
using obscene expressions and very indecent behaviour.
A red coat soldier struck one woman Friend twice on the body with his musket,
and once on the breast; another flung dirt in her face,
and through their abuses her life was greatly endangered.
A man Friend, after he had suffered by blows, was carried into the meeting place,
where one demanded his money, and endeavoured to rifle his pockets,
cursing and threatening he would stab him, if he did not give it him,
again swearing that he would pistol him.
The number of those sorely bruised, and that had their blood shed that day,
was above fifty persons.

On the 16th day of the eighth month, 1670, being again kept out of their meeting place,
there came a party of horse and foot, ready to fall again violently upon our friends,
but some constables being there, for some little time, kept them off.
Howbeit, at last they broke out into a rage,
and some of the foot with the but-ends of their muskets,
and the horsemen with great truncheons and staves,
did so furiously lay on and beat them who were met,
as if they would have killed all in the place,
causing the blood to run down about the ears of many.
Above twenty persons then received sore wounds and bruises,
and one constable endeavouring to stop them from shedding blood, and to keep the peace,
they fell upon him also and broke his head;
and when they were reprehended for their cruelty, some answered,
If you knew what orders we have, you would say we dealt mercifully with you.

The substance of this foregoing account was presented to the king and his council,
and for a time there was some cessation of these cruelties;
but afterward they began in the like manner, though not to the same degree,
yet with great threatenings to be worse and worse,
in their behaviour towards our Friends; which could not well be,
except they directly committed murder on the place.

It was observed, that when the troopers and soldiers have come,
and thus abused and wounded the innocent, some have asked them, saying.
How can you deal thus with a people that have love and good will to all men,
and make no resistance or opposition?
They have replied,
We had rather and it would be better for us, if they did resist and oppose;
as if they wanted an occasion to imbrue their hands in innocent blood,
and have the lives and estates of honest people for a prey.
But as they never could get any such occasion against us,
so the Lord our most gracious God, for his own name and truth`'s sake,
restrained the remainder of our adversaries`' wrath, frustrated their evil purposes,
and disappointed their mischievous designs.
And in him we have trusted, who has helped and delivered us out of many troubles.

I was the more willing to insert the foregoing relation in this place,
because I was very deeply and sorrowfully affected
by the frequent accounts which came to me,
of those barbarous and cruel persecutions,
in the time of my long sickness and great weakness of body.
The Lord my God having restored me to health,
enabled me again to labour and travel in his service,
in the gospel of his dear Son Christ Jesus, and also to suffer with his people,
and to attend and solicit the king and government for their relief.
The hand of the Lord and his counsel were often with me,
to help, encourage, and strengthen my heart in those services,
which many times had good effects, the Lord`'s power going before,
and making way in the hearts of both king and council.
A further account of which may be given hereafter.

There was but little respite from persecution in twelve years time, from the year 1660,
unto 1672, in which was the last war at sea between the English and Dutch.
One judgment and calamity followed another; plague, fire, and war,
unto great depopulation and devastation,
showing God`'s heavy displeasure against persecution and cruelty,
and that spirit which had been so highly at work against innocent,
conscientious and honest people, some whereof the Lord delivered by death;
yet many persecutors were so hardened, that they repented not of their cruelties,
and we have observed in our times, how suddenly the Lord swept away many of that sort.

Howbeit, by this time, A. D. 1671-2, the king seemed to bethink himself,
to take other measures than to continue persecution to destroy his own subjects,
not knowing what consequence the Dutch war against him might come to;
insomuch that he published a declaration of indulgence to dissenters,
to suspend the execution of penal laws in matters ecclesiastical, entitled:

[.embedded-content-document.legal]
--

[.blurb]
=== His Majesty`'s Declaration to all his loving subjects, dated March 15th, 1671-2, published by the advice of his privy council: the principal heads whereof are as follows:

Our care and endeavours for the preservation of the rights and interest of the church,
have been sufficiently manifested to the world,
by the whole course of our government since our happy restoration,
and by the many and frequent ways of coercion,
that we have used for reducing all erring and dissenting persons,
and for composing the unhappy differences in matters of religion,
which we found among our subjects upon our return.

But it being evident by the sad experience of twelve years,
that there is very little fruit of all those forcible courses,
we think ourselves obliged to make use of that supreme power in ecclesiastical matters,
which is not only inherent in us,
but has been declared and recognized to be so by several Statutes and Acts of parliament.

And therefore we do now accordingly issue out this our declaration,
as well for the quieting the minds of our good subjects in these points,
for inviting strangers in this juncture to come and live under us,
and for the better encouragement of all to a cheerful
following of their trades and callings,
from which we hope, by the blessing of God,
to have many good and happy advantages to our government.

And in the first place, we declare our express resolution, meaning and intention to be,
that the church of England be preserved, and remain entire in its doctrine,
discipline and government, as now it stands established by law, etc.

We do in the next place declare our will and pleasure to be, that the execution of all,
and all manner of penal laws in matters ecclesiastical,
against whatsoever sort of nonconformists, or recusants, be immediately suspended,
and they are hereby suspended.

And all judges, sheriffs, justices of the peace, etc., are to take notice of it,
and pay due obedience thereunto.

And we do declare, that we shall from time to time, allow a sufficient number of places,
as they shall be desired, in all parts of this our kingdom,
for the use of such as do not conform to the church of England, to meet and assemble in,
in order to their public worship and devotion;
which places shall be open and free to all persons.

To prevent such disorders and inconveniences as may happen by this our indulgence,
if not duly regulated, and that they may be the better protected by the civil magistrate,
our express will and pleasure is,
that none of our subjects do presume to meet in any place, until the same be allowed,
and the teacher of that congregation be approved by us.

And, we do further declare, that this our indulgence,
as to the allowance of public places of worship, and approbation of teachers,
shall extend to all sorts of non-conformists and recusants,
except the recusants of the Roman Catholic religion,
to whom we shall in no way allow public places of worship,
but only indulge them their share in the common exemption
from the execution of the penal laws,
and the exercise of their worship in their private houses only.

And if after this our clemency and indulgence,
any of our subjects shall presume to abuse this liberty and preach seditiously, etc.,
we will let them see we can be as severe to punish such offenders,
as we are indulgent to truly tender consciences.

--

Thus far the heads of the aforesaid declaration;
from the first part whereof two or three things are observable.

[.numbered-group]
====

[.numbered]
1+++.+++ His care and endeavours in using those many and frequent ways of coercion,
which were severe and frequent persecutions,
designed and used for the preservation of the church, i. e., the church of England.

[.numbered]
2+++.+++ Yet for all this his great care for the church,
it was made evident by the sad experience of twelve years,
that very little fruit came of all those forcible courses, those many ways of coercion,
or the frequent severe persecutions.
Little fruit indeed could these produce,
and none at all to the true conviction of dissenters;
but rather such bitter fruit as was very offensive,
and highly provoking to the righteous God, dishonourable to the king,
and greatly scandalous to that church with which he complied,
and to which he had given power in the use of those ways of coercion,
and forcible courses;
all which proved fruitless and ineffectual to answer the design thereof, i. e.,
universal conformity to the said church.

[.numbered]
3+++.+++ However, it was well the king at length made such an ingenuous confession,
how fruitless coercion or forcible courses were about matters of conscience and religion,
though it was from the sad experience of twelve years trial;
the sad effects whereof had been prevented, if such courses had never been tried,
and his repeated solemn promises of liberty to tender consciences,
had been kept and performed.

[.numbered]
4+++.+++ After the said declaration of indulgence was published in print, and took effect,
in a short time our persecutors were stopped and restrained,
and our religious meetings generally quiet throughout England, Wales, etc.,
for several years.

====

Several good effects followed the before-mentioned declaration, before it was cancelled,
and made void, as:

[.numbered-group]
====

[.numbered]
1+++.+++ The stop put to informers, persecutors and persecutions for a time.

[.numbered]
2+++.+++ The quiet and peaceable enjoyment of our innocent meetings and religious assemblies.

[.numbered]
3+++.+++ The preservation of our goods from rapine and spoil by informers and other persecutors.

[.numbered]
4+++.+++ The king`'s discharge and deliverance of many
of our suffering friends out of the prisons,
remitting their fines and releasing their estates,
by his letters patent under the great seal,
which were forfeited to the king by judgment of premunire.
And for the discharge of the aforesaid sufferers, I faithfully laboured and solicited,
some account whereof follows.

====

Soon after the declaration of indulgence was published in print,
as I was solitarily upon the road, returning toward London, out of the country,
a very weighty and tender concern fell upon my spirit,
with respect to our dear friends then in prisons,
being above four hundred in and about England and Wales,
many of whom had been long straitly confined, under various prosecutions,
sentences and judgments, as to imprisonments, fines, forfeitures and banishments,
for meeting, for not conforming, for not swearing allegiance,
and many under sentence of premunire,
some having endured ten or eleven years imprisonment,
besides those who suffered long for non-payment of tithes.

Whereupon I was moved to write a few lines to the king, requesting their liberty,
which I intimated to our honest and loving friend, Thomas Moore,
who was often willing to move the king in behalf
of our suffering friends for their liberty,
the king having some respect to him;
for he had an interest with the king and some of his council, more than many others;
and I desired him to present my few lines to the king, which he carefully did;
and a few days after, both he and myself had access into the king`'s presence,
and renewed our request which I had made to him in my letter before;
whereupon the king granted us liberty to be heard on Friday, as he said,
before the council, being the next council-day in the same week.

And then Thomas Moore, myself and our friend Thomas Green,
attended at the council chamber at Whitehall,
and were all admitted before the king and a full council,
and being called to go up before the king, who was at the upper end of the council-board,
I had a fair opportunity to open the case of our
suffering friends as a conscientious people,
chiefly to show the reason of our not swearing allegiance to the king;
that it was not in any contempt, or disrespect,
either to the king`'s person or government,
but singly as it is a matter of conscience to us, not to swear at all, in any case,
and that in sincere obedience to Christ`'s command and gospel ministry.
When I had opened and more fully pleaded our suffering friends`' case,
the king gave this answer: "`I will pardon them.`"

Whereupon Thomas Moore pleaded the innocency of our friends, that they needed no pardon,
being innocent.
The king`'s own warrant in a few lines will discharge them;
'`for where the word of a king is, there is power,`' said Thomas Moore.
The king answered, '`O, Mr. Moore, there are persons as innocent as a child new born,
that are pardoned, that is, from the penalties of the law you need not scruple a pardon.`'
The Lord Keeper added, '`I told them that they cannot be legally discharged,
but by a pardon under the great seal.`'
Then stood up Duke Lauderdale, and made his reflection upon what Thomas Moore said,
in this manner: '`May it please your majesty,
I wonder that these men should be no better counselled to accept of your gracious pardon;
for if your majesty should by your own private warrant release them out of prison,
their prosecutors may put them into prison again the next day, and still their estates,
forfeited to you upon premunire, remain confiscate;
so that their persons and estates cannot be safely discharged
without your majesty`'s pardon under the great seal.
With which the rest of the council concurred.`'

Whereunto I returned this answer:
'`It is not for us to prescribe or dictate to the king and his council,
what methods to take for our friends`' discharge;
they know best their own methods in point of law; we seek the end thereof,
namely the effectual discharge of our suffering friends out of prison,
that they may live peaceably, and quietly enjoy their own.`'

Whereupon they all appeared satisfied, and the king said, "`Well, I will pardon,
or discharge them, etc.`"

After more discourse between the king and us, I looked about on the council,
and in the Lord`'s power thus declared:
'`I do not question but God at times inclines your hearts to tenderness towards the sufferers,
especially those for conscience sake.
O therefore take notice thereof, and mind that tenderness,
and that which inclines your hearts to commiserate their conditions,
who have long groaned and lain under heavy burdens, and sore oppressions, etc.

'`As for our refusing the oath of allegiance, for which many suffer in prisons,
God does bear us witness, yes, God does bear the sufferers record,
that it is not from a disaffection to the king, or government,
but singly for conscience sake, because it is an oath.`'
Concluding with these words, '`This is the fast the Lord requires,
to undo the heavy burdens, and to let the oppressed go free.`'
+++[+++Being near the time of an appointed fast, as I remember.]

Pursuant to the king`'s promise of pardon, etc., the following order was given:

[.embedded-content-document.legal]
--

[.blurb]
=== At the court at Whitehall, the 8th of May, 1672;--present the king`'s most excellent majesty. Archbishop of Canterbury, Lord Keeper, Duke of Lauderdale, Lord Chamberlain, Earl of Bridgwater, Earl of Essex, Earl of Anglesey, Earl of Bath, Earl of Carlisle, Earl of Craven, Earl of Shaftsbury, Viscount Falconbery, Viscount Halifax, Lord Bishop of London, Lord Newport, Lord Hollis, Mr. Vice-Chamberlain, Mr. Secretary Trevor, Sir John Duncomb, Mr. Chancellor of the Dutchy, Master of the Ordnance, Sir Thomas Osburn.

Whereas his majesty of his princely clemency, was graciously pleased to direct,
that letters should be written from this board,
to the sheriffs of the respective counties and cities, and counties and towns,
and counties within his majesty`'s kingdom of England and dominion of Wales,
requiring them to return perfect lists and calenders of the names, time,
and causes of commitment of all such prisoners, called Quakers,
as remain in their several jails or prisons, which they accordingly did;
and the same were by order of his majesty in council, of the 3rd instant,
delivered into the hands of the right honourable
the Lord Keeper of the great seal of England,
who having considered thereof, did this day return them again,
together with his opinion thereupon as follows:

The returns that are made touching the prisoners, in the several jails,
are of several kinds.

[.numbered-group]
====

[.numbered]
1+++.+++ All such of them as are returned to be convicted to be transported,
or to be convicted of a premunire, upon whose convictions I suppose judgment was given,
are not legally to be discharged, but by his majesty`'s pardon under the great seal.

[.numbered]
2+++.+++ All such that are returned to be in prison upon writs of _Excommunicato Capiendo,_
not mentioning the cause, ought not to be discharged till the cause appears;
for if it be for tithes, legacies, defamations, or other private interests,
they ought not to be discharged till the parties be satisfied.

[.numbered]
3+++.+++ All those that are returned in prison for debt, or upon exchequer process,
or of any of the other courts at Westminster, are not so discharged,
till it be known for what cause those processes issued, and those debts be discharged.

[.numbered]
4+++.+++ Those that are in prison for not paying their fines,
ought not to be discharged without paying their fines, or a pardon.

====

[.offset]
All the rest I conceive may be discharged.

Which being this day taken into consideration,
his majesty was graciously pleased to declare,
that he will pardon all those persons called Quakers,
now in prison for any offence committed relating only to his majesty,
and not to the prejudice of any other person:
and it was thereupon ordered by his majesty in council,
that a list of the names of the Quakers in the several prisons,
together with the causes of their commitment, be,
and is herewith sent to his majesty`'s attorney general,
who is required and authorized to prepare a bill for his majesty`'s royal signature,
containing a pardon to pass the great seal of England,
for all such to whom his majesty may legally grant the same:
and in case of any difficulty, that he attend the lord Keeper,
and receive his directions therein.

[.signed-section-signature]
Edward Walker.

--

[.offset]
Here follows a copy also of the king`'s warrant to the attorney general.

[.embedded-content-document.legal]
--

Our will and pleasure is, that you prepare a bill fit for the royal signature,
and to pass our great seal of England, containing our gracious pardon unto, etc.,
+++[+++the place of the prisoners`' names,]
of all offences, contempts, and misdemeanours by them, or any of them committed,
before the 21st day of July, `'72, against the several statutes made in the first,
twenty-third, and thirty-fifth years of the reign of queen Elizabeth;
in the third year of the reign of our late royal grandfather, king James,
and in the sixteenth year of our reign, in not coming to church,
and hearing divine service; and refusing to take the oath of allegiance and supremacy,
and frequenting, or being present at seditious conventicles; and of all premunires,
judgments, convictions, sentences of excommunication, and transportation thereupon;
and of all fines, amercements, pains, penalties and forfeitures,
whatsoever thereby incurred, with restitution of lands and goods, and such other clauses,
and _non obstantes,_ as may render this our pardon most effectual;
for which this shall be your warrant.

[.signed-section-context-close]
Given at our court at Whitehall, the day of June, in the twenty-fourth year of our reign.
To our attorney general.

--

After we had taken out the foregoing order and warrant,
our friend Thomas Moore and I carried and delivered
the same to the king`'s attorney general.
Sir Heneage Finch.
Thomas again scrupling the word pardon to him, as he had before to the king, etc.
He took up Thomas somewhat short, telling him, "`Mr. Moore,
if you will not accept of his majesty`'s pardon,
I will tell him you will not accept thereof.`"
Then to pacify him, I told him that it was not our business to question,
but accept what the king had granted for the relief of our suffering friends,
that they might be released and discharged from their imprisonments and sufferings, etc.
Whereupon he seemed satisfied.

And further to inform and satisfy Thomas Moore in the case,
after we came out of doors from the attorney general, I got him to return in again with,
me to his clerk, one Sanders, an old man, who engrossed the king`'s letters patent,
or pardons, that he might inform Thomas Moore of the nature and manner thereof,
which he very fairly did; whereupon Thomas said,
"`Now it begins to have some shape,`" etc.
And then was better satisfied,
as better understanding the form or shape and nature of that instrument than before.

Thomas Moore`'s scruples or objections against the word pardon,
or its being necessary to our suffering friends, were upon these tender points.

[.numbered-group]
====

[.numbered]
1+++.+++ That they being innocent, and no criminal persons, needed no pardon, as criminals do.

[.numbered]
2+++.+++ That their testimony for Christ Jesus allowed of no pardon;
neither indeed can we allow or accept of any man`'s pardon in that case,
singly considered; we cannot give away the cause of Christ,
or our sincere obedience to him,
as any offence or crime needing any pardon or forgiveness from men;
nor does Christ require us to ask it of him, but accepts and approves of us,
in that wherein we truly obey him.

====

But then on the other hand, we must reasonably allow of this distinction;
that wherein we, or our friends were judged or condemned by human laws,
and the ministers thereof, to imprisonments, fines, forfeitures, premunires,
or confiscation of estates to the king, and power given him to banish us,
and thereby we made debtors to him, though unduly, the king has power to remit, pardon,
or forgive what the law has made a debt to him,
as well as any creditor has power to forgive a debt owing him;
and to pardon and release his debtor out of prison.
The case is plain, and the distinction evident.

Neither pope, priest, nor prince can acquit or pardon men in the sight of God,
for offences against him; but the king may forgive debts owing by law to him,
and release and re-convey his subjects`' estates, by law forfeit to him,
or else he has less power than any of them.
An earthly king cannot pardon a guilty conscience before God,
but he can forgive debts owing him, and release estates forfeited to him,
as well as persons who are within his power to release;
good consciences and well-doing need no pardon, but deserve praise.

Besides in this case of our premunired friends,
if the king had not re-conveyed their estates as he did,
by his letters patent--under the great seal of England,--from him and his heirs,
to them and their heirs, they had remained forfeited, and liable to future claims,
and the proper owners to be dispossessed thereof;
and therefore the report and counsel of the lord Keeper, Sir Orlando Bridgman,
to the king, in our friends`' case before related,
was both legal and safe for their discharge; being also recorded in the several offices,
where patents and pardons are kept upon record,
to have recourse to in cases of necessity.

The attorney general ordered his principal clerk, +++_______+++ Nicolls,
to draw up the said bill, to contain the king`'s letters patent,
for a full discharge and release of our suffering friends, from their imprisonments,
sentence of banishment, fines, forfeitures, premunire, fee, which, when he had done,
I got Ellis Hookes, our writer,
to draw out four or five fair copies thereof for expedition,
to be passed and entered and remain upon record in the several offices,
which the same was to pass through; as the Privy Seal, the Signet, the Patent,
and Hannaper offices, etc.

And understanding that because of the number of names in the patent,
great fees would be required in most of those offices, except the lord Keeper`'s,
who had promised to remit his fee, and that he would ask none of us,
which was a kindness;
for there being above four hundred names of the sufferers in one and the same instrument,
to be discharged, we understood they would demand a great fee for each person, and,
as we heard,
it would cost a single person twenty or thirty pounds charge
in fees to get a patent or pardon through all those offices,
to pass under the great seal of England,
that we were constrained to make further application to the king,
to remit or abate the great fees.

Whereupon the king gave order, according to our request, as follows:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Locus Sigilli.

His majesty is pleased to command,
that it be signified as his pleasure to the respective offices and sealers,
where the pardon to the Quakers is to pass, that the pardon,
though comprehending a great number of persons, do yet pass as one pardon,
and pay but as one.

[.signed-section-signature]
Arlington.

[.signed-section-context-close]
At the court at Whitehall, the 13th of Sept, 1672.

--

But though we had this warrant from the king,
yet we had trouble from some of the covetous clerks, who strove hard to exact upon us.

When the instrument for the discharge of the prisoners was granted to our friends,
there being other dissenters besides Quakers in some prisons, as Baptists, Presbyterians,
and Independents; some of their solicitors, especially one William Carter,
seeing what way we had made with the king for our friends`' release,
desired their friends in prison might be discharged with ours,
and have their names in the same instrument;
and earnestly requested my advice or assistance, which I was very willing to give,
in compassion to them.
Accordingly, I advised them to petition the king, with the names of the prisoners in it,
for his warrant, to have them inserted in the same patent with the Quakers,
which they petitioned for, and obtained.

So that there are a few names of other dissenters, who were prisoners in Bedfordshire,
Kent, and Wihshire, in the same instrument with our friends, and released thereby.^
footnote:[Among these was John Bunyan, the author of the Pilgrim`'s Progress.]
I was very glad that they partook of the same benefit, through our industry;
for when we had made way, it was easy for them to follow.
Indeed I was never backward to give any of them advice, if I could, for their help,
when any of them have been in straits, and come to me for help.
Our being of different judgments and societies, did not abate my compassion or charity,
even towards those who have been my opposers in some cases.
Blessed be the Lord my God, who is the Father and Fountain of mercies,
whose love and mercies in Christ Jesus to us,
should oblige us to be merciful and kind one to another, we being required to love mercy,
yes, to be merciful, as well as to do justly, and to walk humbly with the Lord our God.

After the king had signed a copy of the said instrument on several skins of parchment,
which we got engrossed aforehand, for expedition, in the Patent office, in chancery hand,
as is usual, we then got it passed under the great seal of England.
And there being eleven skins of vellum, in chancery hand,
it was swelled to that size by the names of above four hundred
persons repeated eleven times over in it,
that Ellis Hookes and I, and some other Friends,
were hard put to it to find out a way to have it dispensed
to all the prisons throughout England and Wales,
where our friends were confined; that they might be released,
and not too long detained under confinement, as many had been, especially since,
with great industry, we had obtained their discharge.

The best expedient I could at first pitch upon,
was to get two duplicates of the original instrument,
prepared and passed under the great seal, as the first was,
which I got done very shortly; and then sent messengers with them several ways,
to the sheriffs and jailers; as into Sussex, Bucks, Oxford, Warwick, and Stafford,
where our friends had suffered long in their jails,
that they might be forthwith discharged out of prison; which accordingly was done,
when the king`'s discharge under the great seal was
shown to the respective sheriffs and officers concerned,
by our Friends, the messengers,
sent on purpose to see our dear friends released out of their long confinements.

Although at that time I had been in long and great labours and
solicitation for the liberty of our oppressed friends in prisons,
and thereby impaired my health and strength;
yet I was willing to undertake a journey into Essex, Suffolk, Norfolk, and Hertfordshire,
to see our friends released out of the jails in those counties,
as also in Huntington and Cambridge.

And having the original patent under the great seal,
Edward Mann and William Gosnell of London were willing to accompany me on that journey.
So we all took horse early, and got to Chelmsford that day,
and lodged at the inn by the prison that night;
and the next day the quarter sessions being held in that town, for the county of Essex,
we went in the morning to several justices of the peace,
where they were together at another inn.
When we came before them, I gently told them our errand,
and what was the intent of our coming there before them;
and producing the king`'s letters patent,
showed them what names of our friends were in it,
who then were prisoners in Chelmsford prison, and how by it they were discharged.
They seemed somewhat surprised at the sight of such a great instrument,
under the great seal of England, and that in favour of so many Quakers;
and some of them having no good will to us, seemed disgusted at our hats; however,
I told them, I hoped they would allow of the discharge,
and release our friends out of prison. So after they had it into court,
they ordered our friends who were in that prison to be released.

We proceeded on in our journey towards Edmundsbury in Suffolk,
in order to reach the quarter sessions there;
which began the beginning of the week following the other in Essex,
being about two or three days between each session.
The justices in Suffolk carried pretty fairly toward us,
and after they viewed the king`'s discharge in court, seemed affected with it;
but it so happened that all our friends`' names then in that prison,
who were intended in the king`'s grant, were not in the said discharge,
though their case was included, being the case of many others therein.

We could not suppose where the omission had happened,
unless in the sheriff`'s return of the names and causes of the Quakers in prison,
which the king had ordered.
The under sheriff took it somewhat hard that we should suspect him for such omission;
however,
I desired the justices to release those Friends out of prison whose names were omitted,
seeing their case came under the king`'s clemency,
and they had a right to their liberty as well as the rest, in point of justice;
so their liberty was obtained, the justices not opposing, but allowing thereof.

At that time, while we were in Edmundshury,
I very opportunely met with the under sheriff for Huntingtonshire and Cambridgeshire,
who was a very fair, civil man, and showed him the king`'s patent,
and the names of our friends in it, who then were prisoners in those two counties,
and I desired him to see them delivered out of prison in both counties;
which he was very ready to undertake, and honestly performed, so far as I could hear.
After which, we travelled into Norfolk, and to Norwich,
and there meeting with the high sheriff, got our friends released who were prisoners,
and named in the king`'s patent to be discharged.

We returned to Hertford in two day`'s time, before the quarter sessions ended;
and Henry Stout producing the said patent,
the magistrates released those Friends that were prisoners there.
In two weeks`' time we performed that journey and service
for our suffering friends in the said counties of Essex,
Suffolk, Norfolk, Norwich, Huntington, Cambridge, and Hertford.

When we returned to London,
we were yet more concerned for our suffering friends
in the northern and western parts of England,
and also in Wales; for it was a difficult and tedious undertaking,
to send messengers into all those remote places, where many Friends were prisoners,
with three such great instruments.
The patent, which we carried in a leather case and a tin box, with the great seal in it,
was so cumbersome, that Edward Mann was made to tie it cross the horse`'s back,
behind him.

Being sensible of the difficulty and delay it would be to
dispense the same to the several counties and jails,
where our friends were confined, throughout England and Wales;
and what a hard matter it would be to move the king again for any
instrument pursuant to his pardon already granted and confirmed,
for their more speedy deliverance out of prisons so remote,
either by proclamation or warrant from some of his privy council,
or the secretary of state, or attorney general, or otherwise,
and considering the great number of names and places mentioned in the said pardon,
we did not then see how we could acceptably move for such an instrument.
Besides,
having had so much wearisome toil and solicitation
for what we had already obtained for Friends`' release,
the labour and difficulties considered, I was minded to acquaint judge Hale therewith,
who was then chief justice, to see what he would say to it;
if he could put us in a way to get our friends released, who were in such remote prisons,
as before mentioned.

I went accordingly to judge Hale`'s house at Acton, and our friend Ellis Hookes with me,
where we met with the judge at home, and I intimated our case and difficulty to him,
which he fairly heard, and viewed over a copy of the king`'s pardon, or letters patent,
so termed.
How to have the same dispensed for the speedy release
of our friends throughout England and Wales,
was our difficulty,
and so many as the king had given his grant for their discharge under the great seal,
we desired might be delivered out of prison before winter,
which was then approaching and I told him,
considering that many of our friends had lain long under strait confinement,
it might be their death if they were detained much longer,
especially in the winter season.

The judge appearing very serious and intent upon the matter, told us,
that if they would remove themselves by _Habeas Corpus,_
and come before him at the king`'s bench, "`I will release them,`" said he,
i+++.+++ e. upon the king`'s pardon.
I then signified to him,
that would be such a hardship and hazard as we dared not put them upon;
because of the remoteness of the counties in the north.
The health of many of the prisoners was so impaired by their long and hard confinements,
that it might endanger their lives to remove them up to London,
being one or two hundred miles or more;
also many were much disabled and made poor by their sufferings and imprisonments,
and the charge of such removal would be so great, that it would be too heavy for them,
besides the danger of the journey, etc.

The judge then proposed something of an instrument from the attorney general,
though it was not his place to give us counsel, as he said,
yet he appeared willing to help our suffering friends if he could,
by proposing such expedients as he could then think of,
wherein I could not but take notice of his compassion and good will towards us,
and we parted kindly.

Yet hitherto we were at a loss how to expedite our
poor suffering friends out of the remote prisons:
by all the advice or proposals given to us,
we could not get all our friends actually delivered
out of the jails nearly so soon as I desired.

The Michaelmas term, as it is called, being then very near;
and the under sheriffs coming out of the several remote counties to the term,
I told Ellis Hookes we might take the great patent
and show to the sheriffs at their inns and offices,
that they might draw out Liberates,
and send to jails in their respective counties and prisons,
to set our friends at liberty.

We went to the sheriff of Yorkshire, who was an ancient man; and I showed him the patent,
and the names of the Friends who were prisoners in their county and castle of York,
and those clauses for their discharge, which he readily assented to,
and bid us give him a copy thereof,
and he would draw up and send a Liberate to the jailer, for their release,
which accordingly we did, and he performed his promise.

I was thereby further informed how we might hasten and dispatch
our friends`' release in other remote counties;
and I drew up the form of a Liberate, agreeable to the king`'s patent,
briefly comprehending the heads thereof, which concerned the prisoners`' discharge.
Ellis Hookes transcribed as many copies as we needed for the remaining remote counties,
where our friends were not set at liberty;
inserting the prisoners`' names in each Liberate,
respectively appertaining to the same county; as those in Montgomeryshire prison,
in a distinct warrant or Liberate, for the sheriff of that county;
and in like manner for the other counties and prisons in Wales,
where Friends were detained.
Warrants for the sheriffs of Cornwall, Devon, Dorset, Somerset, Cumberland, Durham,
Lancashire, and for the rest of the counties respectively,
where Friends were not released out of prisons, were prepared for the sheriffs severally,
to sign and seal.

Ellis Hookes and I went to their inns and offices, and showed them the king`'s patent,
with the Liberates, that they might see how agreeable they were;
and they approved thereof, and readily signed and sealed each Liberate,
being a warrant to each jailer to set our friends at liberty, out of jail,
where they had been detained, as many of them had been for a long time.
So at last, through much labour, care and diligence,
the difficulty we had been under came to be removed.

I do in deep humility, tenderness of spirit, and with a thankful heart,
retain the remembrance,
how the Lord our God helped and enabled me to go through that great care and
diligence in solicitations for the liberty of my dear suffering friends and brethren.
Although I laboured for the same nearly six months together,
before it was fully effected, the Lord gave me great encouragement, peace and comfort,
in my daily endeavours for them.
My love towards them was such as made the same more easy to me,
in all which I still have great satisfaction and peace, which remain with me,
in Christ Jesus, my Lord and my God;
I bless his name and power which upheld and strengthened me; let him have the glory,
praise and dominion forever, says my soul.

The liberty granted to tender consciences by king Charles`' declaration, A. D. 1671-2,
held not long; for the Parliament,
or a party among them not being reconciled to the liberty granted and allowed thereby,
took occasion against the declaration, and moved the king to cancel it.
They alledged that thereby he extended his prerogative too far,
or advanced it above the law, by suspending the execution of penal laws,
in matters ecclesiastical; suggesting, of what dangerous consequence it might be,
to have such a precedent remaining.
But they took no care of Christ`'s prerogative and
government over the consciences of his subjects;
they must be exposed to severe sufferings, oppressions, and cruelty,
for conscience sake towards him, and for obeying his doctrine,
chiefly in refusing to swear at all, or in any case,
and for solemnly meeting together in his name and spiritual worship.

If the Parliament and all parties who were displeased with the king`'s declaration,
because it was not an act of Parliament, but of prerogative,
had been so generous and noble as to allow a general liberty to tender consciences,
or freedom from persecution,
they might easily have turned the substance or effect
of the king`'s declaration into an act of Parliament.
And no doubt the king would readily have signed and confirmed the same;
seeing he had so often not only publicly promised liberty to tender consciences,
but also in his declaration from Breda, positively and voluntarily promised,
"`That no man shall be disquieted or called in question
for differences in opinion in matters of religion,
which do not disturb the peace of the kingdom`';
and that we shall be ready to consent to such an act of Parliament,
as upon mature deliberation shall be offered to us for the full granting that indulgence.`"
What could be a more plain promise, or more encouraging to them,
to have ratified the same by act of Parliament?
And moreover, in the king`'s declaration concerning ecclesiastical affairs,
dated October the 25th, 1660, it is again declared; "`In a word,
we do again renew what we have formerly said in our declaration from Breda,
for the liberty of tender consciences; that no man shall be disquieted,
or called in question for differences in opinion in matters of religion,
which do not disturb the peace of the kingdom.`"

And in the same declaration, it is further said; "`Our present consideration and work is,
to gratify the private consciences of those who are grieved with the use of ceremonies,
by indulging to, and dispensing with, the omitting of these ceremonies,`"

And in the king`'s speech to both houses of Parliament, the 8th of July, 1661;
"`It is to put myself in mind as well as you,
that I so often (I think so often as I come to you)
mention to you my declaration from Breda;
and let me put you in mind of another declaration published by yourselves,
about the same time, and which I am persuaded made mine the more effectual.
An honest, generous, and Christian declaration,
signed by the most eminent persons who had been the most eminent sufferers,
in which you renounced all former animosities, and the memory of all former unkindnesses.
And, my lords and gentlemen,
let it be in no man`'s power to charge me or you with the breach of our words or promises,
which can never be a good ingredient to our future security.
And in the chancellor`'s speech to both houses, May the 8th, He told you but now,
(meaning the king) that he valued himself much upon keeping his word,
upon performing all that he promises to his people.`"

Now upon the whole it is observable, that when the king made, and so often repeated,
those promises of liberty to tender consciences, there appeared no design of persecution,
or intention to violate his promises, but the contrary;
and how easy it would have been to establish that liberty by a law.
But too many selfish and partial men were otherwise minded;
for before the reign of king Charles the second was expired,
some of these who were against his declaration, would have had an act of comprehension,
to include in the church of England some parties of dissenters,
as Presbyterians and such like; some allowances,
exceptions or limitations were claimed for those,
so as not to be made conformable to the said church in all her articles,
ceremonies and formalities, but to be dispensed with,
or allowed in some things not esteemed essential,
so as they might be comprehended in one with the church of England.
All other dissenters more conscientious than themselves,
who could not come so near a conformity, were excluded the comprehension,
and not allowed a general liberty to exercise their religion and conscience.
These were still exposed to persecution, suffering and ruin, under the penal laws,
if that partial project and comprehension had taken effect,
by a church made up of Presbytery and Episcopacy.
O then, who should have been permitted to stand before them,
without conformity to such elders and bishops?
This partial project and selfish design,
several of us were concerned in conscience to oppose, argue, and testify against,
to certain members of Parliament, who promoted such a comprehension, and to others also.

I discoursed with several of them about it,
showing them wherein they gave away the cause of
all the most honest and conscientious dissenters,
and thereby greatly lost ground.

It was well the project did not take effect;
and there was doubtless a divine hand and providence in its prevention.
It would have gone hard with the high Episcopal clergy,
if Presbyterian ministers had partaken with them and been
made sharers in their parish churches and livings,
tithes and glebe lands, oblations and revenues, with which they were formerly, chiefly,
if not wholly invested for the space of twelve years, until the year 1660,
when the act of uniformity came to be in force.
Then Presbytery must give way to Episcopacy, and lay down church revenues,
or else conform;
whereupon many great Presbyterian ministers did conform with such pretences as these;
that they must not lay aside preaching the gospel,
for lack of conforming or dispensing with a few ceremonies,
which are but indifferent things; their great livings, tithes, oblations and profits,
were to them far more considerable.

In the meanwhile their solemn league and covenant against
Episcopacy was not well considered or thought of,
by such occasional conformists.
Yet some of the Presbytery, who were noted for their zeal against prelacy,
and pretending some greater reformation,
deserted those places where they had been so noted for their zeal and reformation,
and removed into other counties; some south, and some north,
where they were not so known, and could more easily, and with less reflection,
conform for a benefice or church living,
and there put on the surplice--sign infants with the sign of the
cross,--bow to the high altar,--conform to all the ceremonies of
their church,--and plead decency and good order in them all,
which before were but superstitious relics of popery,
and altogether indecent in God`'s worship.

Yet to do the party right,
some ministers and people were more conscientious than to allow of or
indulge themselves in such an occasional conformity for profit`'s sake.
Indeed, many could not obtain parish church livings, if they would,
where there remained some old Episcopal clergymen, who had claim to the livings,
having been formerly turned out of the same.
So that those who could not conform on such occasions, nor obtain parish maintenance,
were made to keep private meetings, termed conventicles, as long as they could or dared.
For few of them would suffer for their religion, but rather privily slide away,
or flee out at back-doors, rather than be seized or taken by the persecutors.
Many of the Baptists suffered imprisonment at first; but the heat of the day,
the burden of suffering and persecution, chiefly arose and fell upon us the poor Quakers.
When we were not permitted to meet quietly in our public meetinghouses,
but many of us were violently haled out to prison, and the rest by force turned out,
and kept in the street; there have we stood and kept our meetings outside,
both when turned out,
and when officers were set on purpose to keep us wholly out in the streets.
Here we have often met, and stood both in winter and summer, and all weathers,
as near our meetinghouses as we could get, and waited upon the Lord our God,
in testimony against our injurious, hard-hearted persecutors.
So that some of the other dissenters, who dared not meet publicly,
have thanked God that he had enabled the Quakers to stand in the gap, and bear the brunt,
and keep the blow off them; according as I was credibly told,
when we suffered so much in London as we did.

The king being prevailed upon in a short time, I think about two years,
to cancel his indulgence to tender consciences, some persecutors began to appear again,
and a new persecution arose in various places,
where they picked up Friends who bore public testimony to truth;
and yet for some time after, we could travel quietly,
and visit our meetings in many counties.
But the old and chief snare which our great persecutors
were ready to make use of against us,
was the oath of allegiance.
They knew that we could not swear in any case, either for the king, or for ourselves;
though we sincerely practised and performed just allegiance toward him,
as true and faithful subjects, giving Caesar his due, and to God his due,
the things that are truly his; namely, his worship and service,
according to our conscientious persuasion in matters of faith and religion.
We chose rather to lay down our bodies as the street to be trod upon,
than subject our souls for our persecutors to go over them;
and when they could not go over our souls,
nor make them bow to their corrupt wills and impositions,
they would hunt us out to apprehend and confine our bodies in prisons.

In the tenth month, 1673, our dear friends and brethren, George Fox and Thomas Lower,
being at a Friend`'s house in Worcestershire,
on their journey towards their relations and habitations in Lancashire, were obstructed,
and committed to prison at Worcester, by warrant from one Henry Parker, justice of peace,
and detained prisoners a considerable time.
The injustice and illegality done them, is further related in George Fox`'s journal.

After George Fox had long remained prisoner at Worcester,
Thomas Moore and I went to the king at Hampton court,
and requested his liberty out of prison; though the king gave us little answer,
yet after some time the Lord made way for his release.

This imprisonment I have mentioned,
that it may appear how early the invidious persecutors fell to work,
after the king`'s declaration for liberty was rescinded.
The persecutors being let loose again,
the several modes of prosecution were renewed against us, the people called Quakers; as,
for not swearing allegiance, the penalty was imprisonment and premunire;
for not going to parish church, so called, twenty pounds a month,
or two thirds of a person`'s estate forfeited and seized on exchequer process or excommunication,
and writs _De Excomunicato Capiendo,_
issued out to take and imprison the persons excommunicated.
And for our innocent religious meetings, great spoil was made upon our goods,
which were taken and torn away by a company of loose idle informers,
who cared not what havoc and spoil they made upon us, nor how much they ruined poor,
honest, industrious families; besides the many hard and tedious imprisonments,
which many of us underwent, both before and after the declaration of indulgence.

Because of these sufferings, on several sorts of processes,
application was often made to the king, and sometimes to the judges,
before they went their several circuits,
for some redress from those hardships and severe sufferings;
and great endeavours were used,
at least to make the king and his ministers sensible thereof,
according to the following brief account.

[.embedded-content-document.letter]
--

[.letter-heading]
To the King`'s Justices, appointed for the several circuits throughout England.

Many of our friends, called Quakers, being continued prisoners,
and many prosecuted to great spoil by informers, and on _Qui-tam_ writs,
and by presentments and indictments for twenty pounds, _per mensem,_
in various counties throughout England,
only on the account of religion and tender conscience toward Almighty God,
we esteem it our Christian duty to remind you of their suffering condition,
as we have done from time to time.
Humbly entreating you in the circuits,
to inquire into the several causes of their commitments and other sufferings,
which they lie under, and to extend what favour you can to them,
for their ease and relief.
Praying the Almighty to direct and preserve you;
we are your Christian friends and well-wishers.

--

But we found little redress from the judges in those days,
after several applications to them;
except when the king gave them some instructions thereto;
for which end we sometimes applied to the king to stay proceedings against our friends;
whereupon he showed some compassion towards the sufferers,
when their case was presented in manner following.

[.embedded-content-document.letter]
--

[.letter-heading]
To The King.

[.blurb]
=== The case of the people called Quakers, who are still sufferers by prosecutions upon old statutes, made against popish recusants.

[.blurb]
=== +++[+++Presented to the king by George Whitehead, William Mead, and John Osgood, the 16th of the eleventh month, 1679. Being introduced by William Chiffins, Esq., closet-keeper to the king; as he had given leave and appointed. After a brief introductory speech to the king, by George Whitehead, the following case was presented and read:]

It may be remembered, that about two years last past,
our case of sufferings was represented before the king and his privy council, that is,
the late and unprecedented prosecutions upon the
statutes of the 23rd and 28th of Queen Elizabeth,
made against popish recusants; by colour whereof,
and of the statute of the 3rd of King James, two-thirds of our lands, tenements,
hereditaments, leases and farms, for two or three years then last past,
were seized into the king`'s hands; and process made out of his exchequer twice yearly,
to collect the rents and profits thereof,
for which the bailiffs seldom lake less than double;
their distresses frequently amounting to more than the yearly value of the whole estates.
The king was then pleased to express his sense of the unreasonableness of such prosecution,
saying,
It was hard we should suffer by laws made against us,
and also by those laws never made or designed against us.
But the parliament being then sitting, the king referred us to them,
as the more proper place for an effectual redress.

In obedience whereunto, we made our application to the House of Commons,
who by a committee then examined by witness and records,
the justness and reasonableness of our complaints, and had true presentments thereof;
but before they could yield us any relief, were prorogued; and soon after dissolved.

We also represented our case to the succeeding parliament,
who for our relief were pleased to insert a clause in a bill then before them,
to distinguish between Papists and Protestants,
which would have tended to redress our grievance;
but the king also proroguing that parliament before the said bill
had passed its last customary reading in the upper House,
we are still left under the said heavy pressures.

Now although the most effectual redress of these present and future prosecutions,
as the king has directed, would be by Act of Parliament; yet it being so,
that the king has power by law, to grant a stay, or cessation of processes,
which are made out to collect the fines and profits levied upon our estates,
the forfeitures being made to the king;

We therefore in true Christian humility desire,
that the king will be pleased to grant a present stay, or cessation of process,
until we can have a more effectual redress in a parliamentary way.

--

The king received this case, with a list of the sufferers, i. e.,
of our friends under prosecution, and he was pleased to give this answer:
"`That it is very unreasonable you should thus suffer
by laws that were never intended against you;
I am against persecution, or persecuting any for conscience;
and I shall consider of your case, and afford you what relief I can.
I will advise with my Lord Chancellor and Attorney-General about it,
what way I may do it: i. e., that which we requested,
that he would please to give order to put a stop to process against us in the exchequer.`"

The king further told us, that it should be moved the next council day;
he would remember it; and Shephard should give us notice;
he being a noted sort of a witty person and courtier, who much attended the king,
and was intimate with him.

We were sensible that the king at that time, as I have known him at several others,
was touched in his conscience,
and somewhat tenderly affected with the extremity and long continuance
of those great sufferings upon our friends in this and other cases.
But some persons about him were not our friends, and had too much influence upon him,
whereby his good inclinations against persecution, and for liberty of conscience,
as well as his promises for the same, were many times frustrated,
and our suffering heavy pressures and troubles by persecutions,
were in great measure continued under his reign, till his days were ended.
The little respite which we obtained in his days,
was through the earnest solicitations and industry of some few among us,
whom the Lord raised up, gifted, and qualified for that service.
These were given up in great love and compassion to the conscientious sufferers,
to appear in the face of authority in their behalf;
in which labour of love I am a living witness of the Lord`'s power and presence with us,
and of his counsel to strengthen and help us in our tender
Christian endeavours for our suffering friends and brethren.

Though our solicitations did not at all times take the effect desired,
yet I had this secret encouragement to move betimes in a good cause,
and to pursue the same so far as I could,
believing that if it was for some time delayed or rejected,
it would in the Lord`'s time lake effect; if we did not receive present gain,
we should not lose by early moving in and following a just cause.
Many times when we have laboured under severe persecutions and confinements,
we have called for justice when we could not have it;
yet thereby we have cleared our consciences, and had the more inward peace,
believing that the just God would appear for us, if men would not hear us.
And our God has often manifestly pleaded our cause,
and vindicated our innocency in various respects, both in men`'s consciences,
and in removing our implacable persecutors, when they have filled up their measures.
