== Chapter X

[.chapter-subtitle--blurb]
The following account of the imprisonment of George Whitehead and Thomas Burr,
was printed for circulation.

Although the publication of this noted case,
of our friends George Whitehead and Thomas Burr, has been for some time delayed,
through other occasions of Truth`'s concern intervening,
yet it is not fitting that such matters should be buried in oblivion,
or be laid by in obscurity; wherefore,
at the desire of many judicious and well meaning persons,
with respect to the good of our nation and English birthrights,
is this following treatise exposed to public view,
not in revenge to the persecutor of our friends,
but for instruction and warning for time to come,
especially of men in commission for the peace.
The late irregular and unjust proceedings against these our Friends concerned,
and how well the Lord enabled them to acquit themselves,
both as Englishmen and Christians, in defence of their Christian cause,
many have understood; and their Christian and gentle behaviour towards the magistrates,
their language in the following account bespeaks,
wherein they do as well confess the civility of those magistrates of Norwich,
as impartially detect the irregularities and injustice of their persecutor.

I am not ignorant what the judgment of able counsel was in their case,
being one that made inquiry therein, as to matter of law,
and it was concluded that it was false imprisonment, being against law:
and knowing our friends`' innocency and good repute among their neighbours,
as real Protestant Christians,
this following account is the more freely recommended to the most
serious and impartial perusal and consideration of the reader.

[.signed-section-signature]
E+++.+++ Hookes.

George Whitehead and Thomas Burr, providentially and unexpectedly meeting together,
about ten or twelve miles from the city of Norwich, the 19th day of the first month,
1680, determined, from a necessity upon our spirits,
in true friendship and Christian charity,
to visit our friends at their public meeting in the said city, on first-day,
the 21st of the same month.
We could not well omit this duty with clearness in the sight of God,
or with inward satisfaction to our consciences,
although we understood beforehand that persecuting informers and disturbers
were apt to be busy against our friends`' meeting in that city.
We freely submitted to the will of God, and with our eye to him,
were resigned to divine Providence, as to what might be allowed to come to pass,
for the holy truth`'s sake and service.

The meeting of the people called Quakers, of the said city,
continued peaceable in the forenoon and likewise in the afternoon,
for about half of the usual time,
in which time Thomas Burr had an opportunity peaceably to declare the truth,
and after him, George Whitehead, for a little space.
In the interim came in a rude company, chiefly informers,
tumultuously and violently crowding into the meeting, to pull George Whitehead down.
He several times required them to show some legal authority.
They used abusive words,
and endeavoured to insinuate to the people that he might be a Jesuit,
and demanded their names and places of abode.
George Whitehead detected their abuse and false defaming insinuation to the people,
and gave his name and habitation, to prevent suspicion.
Again he demanded by what authority they came thus
to disturb our meeting and call us in question,
bidding them produce their warrant; but they refused to give account,
or show any warrant.
So after a tumultuous bustle and a hideous noise, which they made in the meeting,
being prevented by the great crowd from coming at us to hale us away,
the chief of them withdrew.

In a little time after, Thomas Seamans, one of the sheriffs of the city, came in,
calling for us, and came to us, the people making way for him.
He required us to go along with him, taking George Whitehead fast hold by the hand,
and led him along out of the meeting, about half way to the prison, with other persons,
who were the disturbers and informers, to guard us to the prison.
The sheriff turned us in at the jail door, and left us there,
where we were detained about two hours, and then were sent for,
and by the jailer had before Justice Bacon, the recorder of the city.
After some time he called us into a room--many other
persons coming in--where the priest of the parish,
one Whitefoot, was also with him, who at first seemed offended,
and began to question us about our hats, and afterwards about sacraments,
often interrupting and interposing between us and the justice,
as one seeking occasion against us; but he was plainly answered and reprehended by us,
the prisoners, for his incivility, though the recorder showed no dislike of his carriage.

Having his law books and bible before him, he began with us about our names,
habitations and trades; and inquired, if we were in orders, or had orders from Rome.
To all which we gave him a plain account, denying any such orders; and solemnly,
in the presence of God, declared our abhorrence of popery.
Then he questioned us about our preaching that day in the meeting,
to which we also gave him a plain and Christian answer.
After some discourse, he read part of the act against conventicles,
and insisted that we were offenders against it,
and threatened that he would fine us twenty pounds a man;
and then demanded of us to deposit the money.
But we told him, we had not freedom to do that, although we have estates responsible,
that lie open to the law, where our habitations are.
This we told him, and did somewhat insist upon it,
that he might not fine others on our account;
and partly to prevent him from imposing the oath of allegiance upon us,
to circumvent and entrap us; he questioning us, whether we would take it or not.
We answered in general, that we could take no oath for conscience sake;
and therefore desired him to lake that as a caution,
not to go about to ensnare us therewith, since he had begun with us upon another statute,
touching our meeting.
He said, if we could neither pay the fines nor take the oath, he would commit us to jail.
And finding none ready to deposit the fines, the informer whispered in his ear,
as he allowed him several times to do, though requested by the prisoners to the contrary.

Then he inquired, when we came into the city, and where we lodged?
And where we set up our horses?
To all which we gave him account.
One or more of the informers, after some whispering with the recorder,
went from him to the inn where our horses stood,
but in the interim some friends had taken them away unknown to us,
though some have wrongfully upbraided us in that matter,
as craftily designed and knowing of it.
So he told us, he would commit us to prison till next sessions,
and there the oath of allegiance should be again tendered us,
and we should be premunired if we refused to take it; but if we would pay our fines,
he should not send us to prison.
Which we not doing, having told him where our habitations and estates were,
which were responsible, he concluded with these words:
_de non apparentihus et non existentibus eadem est ratio;_ of things not appearing,
and things not in being, there is the same reason; i. e.,
our estates that are at London and Ware, appear not at Norwich;
therefore they are not _in rerum natura,_ or not in being.
Strange kind of logic or reason in this case!

After a little space he told us,
that if we would give security to appear at next quarter sessions,
he would not send us to jail.
Not having freedom to do so,
we requested that he would but let us lodge out of prison that night,
that convenient lodging might be made ready in prison for us,
it being then somewhat late in the evening, we promising, God willing,
to appear at prison next morning;
and some others present offering to engage for our forthcoming then.
But by no means would he grant us that small civility,
unless we would engage in forty pounds bond or security,
for our appearance next morning at prison; which kindness of his,
not being worth further discourse, we did not accept.
So he sent us that night to the jail,
where we remained satisfied in the will of the Lord,
to wait upon him in patience and submission to his good pleasure.

Many material things passed between us, which cannot well be collected in due order,
and others are omitted for brevity`'s sake.

Among other reflections, the recorder, rendering the said prisoners seducers, seditious,
etc., told them of a statute yet in force, that was made in queen Elizabeth`'s days,
to hang such persons as they were.
Being asked by the prisoners if he could prosecute them upon that law,
or execute it upon them?
He answered.
Yes; if the king should give order to have it put in execution, he would do it;
he would prosecute them, and have them hanged, if they would not abjure the realm,
or to that effect.

After the substance of the account given before was written,
these following testimonies were by some Friends delivered to the prisoners,
wherein are the names of some of the tumultuous disturbers and informers before-mentioned,
some whereof refused to tell their own names when asked in the meeting.

It was observed in the late disturbance of our meeting in Norwich, that Paul Hartly,
one of the chief of them, was seen to snatch off John Sharping`'s hat,
and threw it a great way over the people`'s heads in his wrath.

One Christopher Nobs, clerk of Gregory`'s parish, came into the meeting at Norwich,
pushing on each side with his elbows,
and smote Rose Gogny such a hard blow on her breast, that it was sore several days.
Also Charles Alden, the vintner, at the sign of the Charing Cross, came calling out,
"`The church doors stand open, but they will be hanged before they will come there.`"
And while a Friend was speaking, said, "`Pull down that puppy-dog;
why do you allow him to stand there prating?`"

It plainly appeared that Charles Alden and the rest of those rude and tumultuous persons,
behaved themselves more like atheists, than persons of any seriousness,
having regard to religion, or Christianity: no,
let humanity and common civility condemn their deportment.
What ornament such sons of the church can be to her,
let their priests and all serious persons judge.
Though the said Alden be accounted a great singer at the cathedral, i. e.,
one of their singing men, how immoral and brutish was his behaviour?
How busy was he also with the recorder against the prisoners, informing, muttering,
and whispering against them?
Greatly inconsistent with so much as the pretence of common justice to suffer,
much more to countenance such work.
Surely the righteous Judge of all will plead with all such malicious agents,
and such injustice will not go unrebuked.

A copy of the prisoners`' letter delivered to the mayor before the quarter sessions,
containing a twofold request.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Mayor, Justices, mid Aldermen of the city of Norwich.

We whose names are hereunto subscribed,
being prisoners in your city jail for our conscience towards God,
do heartily wish health, happiness, and prosperity in the way of righteousness,
unto you all; and desire of the all-seeing and heart-searching God,
that you may be preserved from all injustice, prejudication, and arbitrary proceedings,
both in our case, which we understand is to come before you,
and in all other cases proper to your cognizance, as civil magistrates;
wherein you are required to discharge a good conscience,
both in the sight of God and men,
as that which will greatly tend to your peace with God and your reputation among men.

Forasmuch as we have for some weeks been detained prisoners in your city jail,
and you have had no hand therein, saving that one person, by whom we were committed,
we are the more encouraged to make this brief application to you,
upon a twofold request on this wise:

[.numbered-group]
====

[.numbered]
_First;_ We request your moderation and indifferency so far towards us,
as that when we are called before you, as a court of judicature in your quarter sessions,
to hear and determine matters that come judicially before you,
you will please to hear us with patience, and permit us to open our case,
and to plead and argue, whether it be in point of law, conscience, reason, or fact,
as our case shall require.
First hear, before you determine, that we may not be overborne nor run down,
nor any precipitation be used towards us in court,
to divert or prevent us from making our defence,
in reference to the prosecution and charge we suffer under.

[.numbered]
_Secondly;_ We further request, that if upon a deliberate hearing,
and due inquiry into those proceedings which we suffer under,
we make it appear that we are illegally and unduly proceeded withal,
and contrary to due process and order of law, that then you will not countenance, abet,
or confirm such proceedings against us, but stand clear thereof, and show your dissent.
For whoever be deputed judge in your court,
as the king`'s minister and mouth of the court, it is no otherwise so legally intended,
than as he shall appear to be the minister and mouth of the law and justice;
and therefore it cannot be reasonable or safe,
nor yet for your reputation or the honour of your court,
to espouse or confirm any prosecution or procedure, that is injurious,
or contrary to due course of law,^
footnote:[37 Ed. 3, c. 18.]
and so tending to the grief and dishonour of the king,
or destruction of any of his peaceable people.

====

We hope you will not deny, but assent to these two foregoing propositions,
as just and reasonable; and therefore we shall not need now to urge,
but only remind you of these material points of law following.

[.numbered-group]
====

[.numbered]
_First;_ It is the king`'s will, in point of law,^
footnote:[25 Ed. 1 c. 1 Coke Inst, part 2, fol. 527. 25 Ed. 1 c. 2. 5 Ed. 3, 9, 28. Ed. 3, 3, etc.]
that all his justices, sheriffs, mayors, and other ministers, who, under him,
have the laws of the land to guide,
shall allow the great charter of the liberties of England to be pleaded in all points.

[.numbered]
_Secondly;_ That if any judgment be given,
or anything done contrary to the points of the said charter, by the justices,
or any other the king`'s ministers that hold plea before them,
against the points of the charter, it shall be undone, redressed, and held for naught.

[.numbered]
_Thirdly;_ The court ought to be of counsel with the prisoner,
to see that nothing be urged against him contrary to law and right.
Coke.
Inst, part 3, fol.
29.

[.numbered]
_Fourthly;_ That the court ought to be so far from overawing,
or forcibly diverting the prisoner from his plea or answer,
that the judge ought to exhort the prisoner to answer without fear;
and that justice shall be duly administered unto him.
Coke Inst, part 2, fol.
316.

[.numbered]
_Fifthly;_ That any learned man who is present, may inform the court,
for the benefit of the prisoner, of anything that may make the proceedings erroneous:
as also, even in cases highly criminal, it is lawful for any man that is in court,
to inform the court, lest the court should err,
and the prisoner be unjustly proceeded with.
See Coke, part 3, fol.
137.

====

Now friends, these things are recommended and left to your serious consideration,
we not designing hereby, as you may easily understand,
to enter into the merits or justification of our cause;
but fairly to introduce the right and legal cognizance thereof,
in order to have justice and right done us as Englishmen,
and as we are your well-wishers.

[.signed-section-signature]
George Whitehead, Thomas Burr.

[.signed-section-context-close]
Norwich jail, the 17th of the Second month, 1680.

[.postscript]
====

We desire this may be communicated.

An account of the substance or principal parts of
the procedure at the quarter sessions at Norwich,
held for the city and county of the same, the 28th day of the month called April, 1680.
Collected and compared by several hands,
and digested into as much order as the capacity of the sufferers,
and the circumstances of proceedings would admit.

====

--

The quarter sessions for the city and county of Norwich, begun the 19th day of April,
so called, 1680.
Adjourned until the 26th, and continued the 27th and 28th of the same.
And again adjourned until the 17th of May, 1680.
The aforesaid prisoners, George Whitehead and Thomas Burr,
were called into court the 27th of April, in the year above-said:
nothing was said to them then by the court, but they returned back immediately to prison,
upon pretence of a mistake about their being called forth.

At the quarter sessions for the city and county of Norwich, the 28th day of April,
so called, 1680, the prisoners were brought to the bar,
their hats ordered to be taken off, and their hats were taken off.

George Whitehead standing up to the bar, began thus;
"`The law of England requires two things of the court with respect to the prisoners,
namely: The patience of the court,
and the indifferency of the court towards the prisoners.

"`That their case may be patiently heard and considered, without prejudication,
before any judgment pass against them.
This we expect from the court.
We have been five weeks in prison; it is fitting the court should know for what.
Pray let our court order be produced and read in court,
that it may be understood what charge we suffer under.

"`Our suffering is twofold; first, above five weeks confinement.
Secondly, the charge that is against us in the court order:
we request that the court order may be produced and read in court.`"

[.discourse-part]
_Recorder:_ There is no need of your court order to be read here:
I will give account of the cause: I will inform the court.
These persons had been two^
footnote:[An untruth.]
months from home, and had been up and down in the country in Suffolk,^
footnote:[Not true of Thomas Burr, it was only George Whitehead.]
at a burial, etc.
And then they came here, and here they gathered a company together, of about two hundred,
and the officers went from me to dissipate them, but could not;
whereupon I sent the sheriff, and he took them away, and put them in prison.^
footnote:[The prisoners had not opportunity to speak to all this account.]
And then they were brought before me; and after conviction made, I proposed to them,
that if they would pay their fines, I would not commit them to prison;
but when they would not, I tendered the oath of allegiance to them:
and after they would not take it, I sent them to jail; as I think I very well might.

[.discourse-part]
_George Whitehead:_ We are Englishmen, and have a right to travel in any part of the nation.

[.discourse-part]
_Thomas Burr:_ I am a person that have been concerned in trading in corn,
as well in this county as in others; and by the law of England,
a man may travel from place to place about his concerns,
and ought not to be molested while he walks peaceably.

[.discourse-part]
_Recorder:_ Had not you better been turning your malt at home, than to come here to preach?
The apostle Paul exhorts to follow the vocation whereunto you are called.
The Scripture says,
"`God added to the church such as should be saved:`" but you draw from the church.

[.small-break]
'''

The prisoner heard not these words, but some others affirmed they did.
However, had the prisoner heard this reflection before,
upon a fair debate upon the point, he might have answered the recorder,
that to be a tradesman or layman, so called,
is not inconsistent with being a preacher of the gospel.
When God added to the church, it was through laymen`'s preaching, such as fishermen,
handicraftsmen, and such like.
It is popery, and the popish spirit, that would hinder laymen and labouring men,
being endued with the Holy Spirit, from being preachers of the gospel;
and not the spirit of Moses, who wished that all the Lord`'s people were prophets;
nor the spirit of the holy prophets, Christ, or his apostles,
who did not go about to exclude laymen or mechanics, so called,
from preaching the gospel; for the best preachers were generally such,
in the prophets`' and primitive Christians`' days.

[.discourse-part]
_Recorder:_
There is a law--and the church of England will never
be at quiet till some of you be hanged by that law,
or till such fellows as you are hanged.

[.discourse-part]
_George Whitehead:_ The court may see the frame of the recorder`'s spirit toward us,
and that he stands not as a person indifferent, but a party against us.
You ought not to inveigh against the prisoners, nor threaten us.
That stands not with the indifferency of the court;
nor yet your determining or resolving aforehand against us, as you have done.
Judges ought not to declare their opinions aforehand against the prisoner.
Hussey, the chief justice, would not do it to the king, in the case of Humphrey Stafford,
the arch traitor, but begged of the king,
he would not desire him to declare his opinion aforehand,
that the prisoner might come judicially before him, and have justice done him.
And the king accepted his request in the case------interrupted.

[.discourse-part]
_Recorder:_ What king`'s reign was that in?

[.discourse-part]
_George Whitehead:_ In king Henry the seventh`'s.

[.discourse-part]
_Recorder:_ I perceive you have read, or are read.

[.discourse-part]
_George Whitehead:_ Seeing that none of the court have as yet had any hand against us,
except the recorder,
we may charitably hope that the court will stand indifferent towards us,
and let us have a fair hearing before any determination.
For as the laws of our nation require a due process and a due course of proceeding,
before men be sentenced or condemned; so there ought to be a due hearing.
As where a process or proceeding consists of several parts,
each part ought to be inquired into, and answered in due order,
without confounding one thing with another, or putting that first,
which in course is last.
Let us have a fair hearing and trial.
Let us be tried before we be hanged.
Let us not be hanged first, and then tried.
It will be too late to try us after we are hanged.

[.discourse-part]
_Recorder:_ You were sent to prison for refusing the oath of allegiance.

[.discourse-part]
_George Whitehead:_ That is a mistake.
We were sent to prison for being at a meeting charged to be against the peace,
which is the premises in our court order, to which we are here to answer.
And therefore that all may know what is laid to our charge,
we desire our court order may be read,
that so if there be any persons who will undertake to prove the matter in charge,
let us see them, and have liberty to answer the premises contained in the court order.

[.discourse-part]
_Recorder:_ I will show you, that when a person is committed to prison,
he may have several actions laid upon him, if new charges be brought against him.

[.discourse-part]
_Prisoner:_ I grant that; but that is not our case.
For we presume the recorder had no new matter brought against us,
after he committed us to prison; and therefore could not lay any new charge upon us.

[.discourse-part]
_Thomas Burr:_ There could not be any new charge against us,
to render us suspicious of being Jesuits or Papists; but instead of that,
we have certificates to take off any jealousies of
that kind that might be in any concerning us,
which are subscribed by credible persons of our neighbourhood.

[.discourse-part]
_George Whitehead:_ The premises which we are to answer to,
is matter of charge contained in the court order: let it be read in court we request you.

[.discourse-part]
_Recorder:_ It shall not,--I will give account.
These persons were taken at an unlawful meeting.
There is also a second court order,
which signifies my requiring them to take the oath of obedience, and their refusal.

[.discourse-part]
_George Whitehead:_ The second is a warrant to detain us without bail or mainprise,
till sessions: it is not the court order, it is of another date.

[.discourse-part]
_Recorder:_ It is the court order; and you are to answer to it,
whether you will take the oath of allegiance to the king.
These persons have refused to show their obedience to the king.

[.discourse-part]
_Thomas Burr:_ Pray forbear to accuse us.
We have showed our obedience by our peaceable conduct.

[.discourse-part]
_George Whitehead:_ The second warrant is not the court order.
The court order is that by which we were sent to prison,
bearing date the 21st day of March.
The second warrant bears date the 23rd day of March.

[.discourse-part]
_Recorder:_ The second is the court order; you are to answer to it.
We will put the oath to you.

[.discourse-part]
_George Whitehead:_ The second is not the court order; we were not sent to prison by it.
We were sent to prison the 21st of March.
The second warrant bears date the 23rd of March.
We were in prison nearly two days before the date of the last warrant.
There needed not be a court order to send us to jail,
when we were sent by one already so long before,
I pray let our court order be read in court.

[.discourse-part]
_Recorder:_ Put the oath to them, that is in the second court order.

[.discourse-part]
_George Whitehead:_ I beg of this court, for God`'s sake, and the king`'s sake,
to be heard fairly, without thus being run upon.
For God`'s sake, because he is a God of justice and truth; and for the king`'s sake,
because the king`'s will toward us as subjects, is what the law and justice wills.
As his will is the will of the law, he wills that none of his subjects be injured,
or unduly prosecuted contrary to law.
I appeal to the mayor as chief magistrate of this city,
and the rest of the justices here present,
whether you ought not to see us have that right so far done us,
as to have our court order produced and read in court,
that you may understand the cause of our commitment.
We were not committed for refusing the oath.
We entreat that the court may hear our court order,
that we may not have any other premises put upon us than what is contained therein.

[.discourse-part]
_Recorder:_ It shall not be read; there is no need of that:
I am present that committed you.

[.discourse-part]
_George Whitehead:_ I appeal to the mayor and the rest of the justices,
who are more indifferent towards us, for justice in this case,
that we may have our court order read, and answer to the premises contained in it,
and not thus be run upon, and diverted with that which is none of the premises.

[.discourse-part]
_Mayor:_ You have appealed to me: truly we are tradesmen, and no lawyers:
we leave matters of law to the recorder; he knows the law,
and we must acquiesce in his judgment.

[.discourse-part]
_Thomas Burr:_ You understand we ought to have our court order read, and be heard:
and you are the chief magistrate in this court.

[.discourse-part]
_George Whitehead:_ You all have a conscience towards God,
and an equal and just law therein; and you are under a severe obligation, namely,
your oath to see justice and right done us.
We appeal to the mayor and justices here for justice, in relation to our court order,
that it may not be thus evaded.
We are at this sessions to answer to the premises or matter of charge therein contained;
you are concerned in conscience to do us right herein.
The honour of this court is also concerned not to see us precipitated,
or run down upon other premises.
The court order was given under the hand and seal of your recorder;
his reputation and honour are also concerned.

[.discourse-part]
_Recorder:_ My honour concerned; wherein?

[.discourse-part]
_George Whitehead:_ Your reputation and honour are concerned,
in that you are bound to stand by our court order; it is under your hand and seal.
Now you go about to evade it, by imposing other premises upon us, or to the same effect.

[.discourse-part]
_Recorder:_ They sent their court orders to the attorney general,
and solicited him for advice, to know whether they were according to law or not,
and moved for a _Habeas Corpus:_ but it would not be granted.

[.discourse-part]
_George Whitehead:_ We neither sent to the attorney general,
nor have we yet moved for a _Habeas Corpus._

[.discourse-part]
_Recorder:_
The second court order or warrant is about their refusing the oath of allegiance;
as for the first, I did not make it by book.^
footnote:[This the prisoners did not hear, but others nearer.]

[.discourse-part]
_George Whitehead:_ It is not a reasonable thing to bring a prisoner,
and not withal to signify the crimes laid against him:
it was contrary to the very law of the Romans.--Interrupted, being about to add:
as Festus said in the case of Paul.
"`It seemed to me unreasonable to send a prisoner,
and not withal to signify the crimes laid against him;`"
which always ought to be in warrants of commitment.

[.discourse-part]
_Recorder:_ What tell you us of the law of the Romans;
we have laws of our own to act by +++[+++or to that effect.]

[.discourse-part]
_George Whitehead:_ It is according to the law of reason and nations,
that the crimes and offences should be known,
for which prisoners are committed and detained in prison; else why should they suffer?

[.discourse-part]
_Recorder:_ The court must tender you the oath.

[.discourse-part]
_George Whitehead:_
Wherefore then were we committed and detained in prison above these five weeks?
If we be offenders, let us know our offence, for which we were committed; if not,
do not go about to ensnare us; do not seek occasion against us.
It is enough to punish us,
if found guilty of what is charged against us in our court order.
We entreat the mayor and court to do us right in this matter,
that our court order may be read.

[.discourse-part]
_Mayor, and some others:_ Well, you shall have it read.

[.discourse-part]
_George Whitehead:_ Keeper, where is our court order?
produce it, that it may be read,
as the mayor and other justices here present have engaged.

[.discourse-part]
_Recorder:_ Tender them the oath: put the oath to them: if you will take it,
that shall serve; if not you incur a premunire.

[.offset]
+++[+++A hideous noise in the court, among some under clerks and officers, about the oath:]

[.discourse-part]
_Some under-clerks:_ What say you?
Answer.
Will you take the oath?
Will you kiss the book?

[.discourse-part]
_Clerk reads:_ I Thomas Whitehead do truly and sincerely acknowledge, profess,
testify and declare in my conscience, etc.--Here was an interruption,
upon his mistake of Thomas for George.

[.discourse-part]
_George Whitehead:_ The oath is none of the premises contained in our court order,
which we are to answer to at this sessions, and to be tried upon.

[.discourse-part]
_Thomas Burr:_ Our all is at stake.
We perceive the recorder is determined concerning us.
We must have liberty to speak.
We are freeborn Englishmen.
+++[+++This on the interruption.]

[.discourse-part]
_Recorder:_ We have power here to tender you the oath,
without taking notice of any other cause.

[.discourse-part]
_George Whitehead:_ It is preposterous to run us upon the oath in the first place,
we being not committed for that, but for other causes.

[.discourse-part]
_Recorder:_ You affront the court: is that a fit word to give the court,
to charge the court with preposterous proceedings, +++[+++or to that effect].

[.discourse-part]
_George Whitehead:_--I do not charge the court;
I do distinguish between the recorder in this point, and the court:
he seeks to run us upon that first, which in course is last,
according to his own court order and warrant,--and is not that preposterous?
Let our court order be read, and that will show we were not committed upon the oath.

We ought to have due process, or proceeding in due course of law;
therefore the court should know how we were first
arrested and turned into jail by the sheriff,
without examination, court order, or warrant; and how afterward,
we were had out and committed; and what the court order is;
what are the premises contained in it, that we are to answer unto.

The law of England is tender of men`'s liberties, properties, estates and lives,
all which are concerned in our imprisonment.
// lint-disable invalid-characters
_Lex Angliæ,_ is said to be _Lex misericordiæ,_
i+++.+++ e+++.+++, the law of England, is a law of mercy;
one reason whereof is,
that the innocent may not be worn or wasted through long imprisonment,
but be brought forth speedily to trial, according to Magna Charta.

[.discourse-part]
_Recorder:_--Look what an argument or consequence you would draw from hence,
// lint-disable invalid-characters
the law of England is a law of mercy; it is _Lex misericordiæ,_
therefore thieves or malefactors must not be brought to condign punishment,
+++[+++or to that effect].

[.discourse-part]
_George Whitehead:_--That is none of my consequence;
mine is the same that Judge Coke does instance,
// lint-disable invalid-characters
wherein the law of England is _Lex misericordiæ,_ in that it is tender of men`'s liberties,
and prescribes a due course of procedure Interrupted as it may be applied to our case.
Either we are innocent or nocent; if innocent, we ought to be heard,
and not delayed in prison; if nocent, or criminal,
we ought to have due and orderly proceeding, according to the law of the land,
that our offence may the more plainly appear, that others may take warning thereby,
and not incur the like penalty or suffering.
However, let us have fair dealing; let us not be unduly run upon,
or diverted from our plea, and our mouths stopped,
so that the court and people here cannot know what we suffer for.
No freeman shall be taken, or imprisoned, or disseized of his freehold,
or otherwise destroyed, but by due process and order of law.
This, Magna Charta enjoins, where in the 29th chapter it is said,
No freeman shall be taken or imprisoned, but by the law of the land; that is,
by due order of law, by due process, according to law.
The law of England requires due process, or proceeding, from the very first arrest,
taking, and imprisoning, to the very end and execution of the same.
Therefore the first arrest, imprisoning and committing us,
ought to be known and understood, whether it was in due manner and course of law, yes,
or no.

Let us have our court order read, we expect it;
it is granted and promised us by the mayor, and others indifferent.

[.small-break]
'''

[.offset]
+++[+++A little respite, in expectation of the court order.
But the recorder seemed greatly offended at the prisoners urging this,
and at the mayor and justices assenting to it.]

[.discourse-part]
_George Whitehead:_--Seeing that the law is tender of Englishmen`'s liberties,
as that no freeman shall be taken or imprisoned, without due proceeding in law,
it is but fitting and reasonable, that the court and people here,
should understand what capacity and repute we are under among our neighbours, that is,
whether as freemen of England and of any repute among our neighbours, or as bond-slaves,
rogues, vagrants, or renegadoes.
Hear what our neighbours say of us; we desire their certificates may be read.

[.discourse-part]
_Recorder:_--What have we to do with your certificates?
Will any swear to them, that they are true ones?

[.discourse-part]
_George Whitehead:_--They are real certificates; pray let them be read; here they are.

[.discourse-part]
_Recorder:_--We do not know but that you might make them yourselves in prison.

[.discourse-part]
_George Whitehead:_--They are no fictions: Pray read them, or let them be read;
they are from persons of credit and repute, as common council-men, deputy constables,
churchwardens, and others.

[.discourse-part]
_Recorder:_--They shall not be read.

[.discourse-part]
_George Whitehead:_--We beg they may be read.
Look upon this certificate, here are the persons`' own (different) hands to it;
it may tend to inform the court, and to remove suspicion and jealousies concerning us.
+++[+++But this would not be granted the prisoners.]

[.discourse-part]
_George Whitehead:_--Seeing our certificates may not be read, nor permitted to be read,
which is hard measure,
now let our court order be produced +++[+++several expecting the keeper had sent for it]
pray let us have our court order produced and read.

[.discourse-part]
_Recorder:_--We have it not, the jailer has it.

[.discourse-part]
_George Whitehead:_--Where is it?
Keeper, produce it; you had it.

[.discourse-part]
_Recorder:_--+++[+++To the prisoner]
No doubt you have a copy.

[.discourse-part]
_George Whitehead:_--Yes, we have; may I read it?
I crave liberty of the court to read it,
that the court may understand what we are committed for, and to answer to that,
this court is to take judicial cognizance of.

[.discourse-part]
_Court:_--The justices asked the question from one to another, to have it read,
generally assenting thereunto, as being of the mind it ought to be read.

[.discourse-part]
_Justice Briggs:_ I am of the mind it should be read; what say you Mr. Bendich?

[.discourse-part]
_Justice Bendich:_ Yes, truly I am of the mind it should be read.

[.discourse-part]
_Justice Briggs:_ Pray speak to Mr, Mayor; +++[+++which was done.]

[.discourse-part]
_Mayor to the Recorder:_ Sir, the justices are agreed it should be read.

[.small-break]
'''

[.offset]
+++[+++Recorder turning himself toward them, as one greatly offended,
that the court order should be read.]

[.discourse-part]
_George Whitehead:_ It concerns the court to let us have our court order read.
I am ready to read the copy, seeing it may not be otherwise produced and read;
shall I read?
We expect that justice from the court, that it should be read.

[.discourse-part]
_Recorder:_ Let them read it then, I am not ashamed of it; then read the other also,
for you have them both.

[.discourse-part]
_Court:_ You may read it.

[.discourse-part]
_George Whitehead:_ Now we have the leave of the court, I hope you will keep to it:
observe it, it is a true copy.

[.offset]
The court order read, which follows:

[.embedded-content-document.legal]
--

[.letter-heading]
The Court Order

[.signed-section-context-open]
City and county of Norwich.

Whereas George Whitehead
of the parish of St. Buttoiph in London,
grocer, and Thomas Burr of Ware, in the county of Hartford, maltster,
have this day assembled together, with several other persons,
in disturbance of the public peace, and against the laws of this realm;
and being required to find sureties for their respective
appearance at the next general sessions of the peace,
to be held for the said city and county, to answer the premises,
which they refused so to do:
these are therefore to will and require you to receive and keep the said George
Whitehead and Thomas Burr in the common jail for the city and county aforesaid,
until they shall be from there discharged by due order of law; and hereof fail not.
Given under my hand and seal, the 21st day of March, Anno Dom.
1679.

[.signed-section-signature]
F+++.+++ Bacon.

[.postscript]
====

To the constables of the Ward of West Wymor, and to either of them, to convey,
and to your keeper of the common jail aforesaid,
to receive and keep the said George Whitehead and Thomas Burr, according to this warrant.

====

--

[.discourse-part]
_George Whitehead:_ Does the recorder own this to be a true copy, yes or no?

[.discourse-part]
_Recorder:_ I care not whether it be true or false;
there is another court order against you.

[.discourse-part]
_George Whitehead:_ Let this court order be considered first:
do you own it to be a true copy, or no?
We have it attested.

[.discourse-part]
_Recorder:_ It may be it is, what then?
It may be true for aught I know, etc.
+++[+++or to that effect.]

[.discourse-part]
_George Whitehead:_ Then pray observe this court order, the tenor of it, what it contains.

[.numbered-group]
====

[.numbered]
_First:_ As to the cause of our commitment.

[.numbered]
_Secondly:_ That is, the premises which we are to answer to,
and to be tried and delivered upon.

[.numbered]
_Thirdly:_ And that according to law, or according to due course of law.

====

First; Then, the charge concerns matter of fact, i. e. being at a meeting.
And, Secondly; What such a meeting, or how qualified, i. e.,
a meeting in disturbance of the public peace.
These are the matters in charge against us,
which the court ought to take judicial cognizance of; either to acquit us, if clear,
or to condemn us, if guilty of any such meeting.

[.discourse-part]
_Recorder:_ Read the other court order; you have a copy doubtless.

[.discourse-part]
_George Whitehead:_ We have a copy of the second warrant.
But this is not to be evaded; this is the court order;
this contains the cause of our commitment, and the charge that lies against us,
which the court is bound only to take cognizance of;
for we are thereby referred to the quarter sessions.

[.discourse-part]
_Recorder:_ Read the second warrant, that contains the cause, namely,
my tendering you the oath; by taking whereof you ought to show your allegiance,
or obedience to the king.

[.discourse-part]
_George Whitehead:_ Either the court order is a legal court order, or it is illegal;
if legal, then let us answer to the premises.
If the oath be insisted upon, to evade the court order,
that will bespeak either lack of other matter against us,
or else that the court order or commitment is illegal.

[.discourse-part]
_Recorder:_ Read the second warrant, etc.,

[.discourse-part]
_George Whitehead:_ We have exceptions against the second warrant: If I read that,
the exceptions ought also to be read.
Shall I read them when I have read the warrant?

[.discourse-part]
_Court:_ Well, you may read both.

[.discourse-part]
_George Whitehead:_
Now the court is engaged and concerned to make good the liberty granted me,
to read our exceptions when the warrant is read.

[.offset]
The second warrant read, which follows.

[.embedded-content-document.legal]
--

City and county of Norwich.--Whereas George Whitehead and Thomas Burr,
were lately sent by my warrant unto the common jail for the city and county aforesaid,
for being seditiously assembled with some hundreds of other disloyal persons,
against the public peace, and in contempt of the laws and government of this realm.
Now, for that the said George Whitehead and Thomas Burr are suspicious persons,
and strangers to this city aforesaid, and being unwilling to declare that duty,
which they and every true and well affected subject ought to bear,
by bond of allegiance to our gracious king,
they did severally refuse to take and pronounce the
oath of obedience to the king`'s majesty,
duly tendered unto them; and after they were severally required to do the same by me:
these are therefore in his majesty`'s name,
to will and command you to keep the said George Whitehead
and Thomas Burr in the common jail,
for the said city and county, without bail or mainprise,
until the next general quarter sessions of the peace,
to be held for the city and county aforesaid; and hereof fail not.
Given under my hand and seal, the 23rd day of March, A. D. 1679.

[.signed-section-signature]
F+++.+++ Bacon.

[.signed-section-context-close]
To the keeper of the common jail, for the city and county of Norwich.

--

[.discourse-part]
_George Whitehead:_ I hope the recorder cannot deny the copy to be true.

[.discourse-part]
_Recorder:_ I will vindicate it by law in any court in England, +++[+++or to that effect.]

[.discourse-part]
_George Whitehead:_ Hear the exceptions against this second warrant:
I will read them deliberately.
If the court has anything to object against any particular,
that may be read over again after the first reading.

[.discourse-part]
_Court:_ Read them.
Go on.

[.numbered-group]
====

[.numbered]
_First;_ The prisoners being committed till sessions,
there to answer to the premises contained in their court order:
therefore the court ought to take judicial cognizance thereof, that is,
of the charge contained in the said court order, for their trial and discharge thereupon,
by due order of law, and not to permit the second warrant to be insisted upon,
or the court order to be evaded.

[.numbered]
_Secondly;_
Because that after the command given to the keeper to keep them in the common jail,
until the next general quarter sessions, the lawful conclusion is lacking, i.e.:
+++[+++until they shall be delivered by due course of law,]
see Coke, in the second part of his Institutes, concerning a commitment by lawful warrant.
The warrant or court order, says he, containing a lawful cause,
ought to have a lawful conclusion, i.e.;
And him safely to keep until he be delivered by law, etc.
And not until the party committing does give further order.
And this does evidently appear by the writs of Habeas Corpus,
both in the king`'s bench and common pleas, exchequer and chancery.

Again he says.
The court order ought to be, as has been said, till he be delivered by law.

Again, as the court order must contain the cause,
so the conclusion must be according to law, i.e.: the prisoner safely to keep,
until he be delivered by due order of law; and not until he that made it,
shall give other order, or the like.

[.numbered]
The _third_ exception is deduced by way of inference from the second.
Therefore the justice had no legal power to give other order or warrant,
which interposes between his commitment of the prisoners,
and their deliverance by due course of law,
which is mentioned in the warrant of commitment;
but not in this pretended warrant for detention.
The justice who committed the prisoners, had no legal jurisdiction over them,
thus by himself to interpose to fasten them.
They were thrust out of his hands by their commitment,
and thereby referred to the quarter sessions, for their discharge thereupon,
by due order of law.
+++[+++Interruption on the reading the third exception in this objection]:

[.discourse-part]
_Recorder:_ If a man owe twenty men money, the first that arrests him lays him into jail,
but the other may lay their actions upon him for all that:
or if a man robs in several places, and is laid into jail for one robbery,
and there comes a hue and cry after him for another,
shall he go free of that because he is arrested already?

[.discourse-part]
_George Whitehead:_ That is not our case; there is no parity between them:
we were not committed to jail on any such account, as upon any action of debt or robbery.
Nor were we chargeable with any new matter or crime when the second warrant was written,
more than when our court order was written, and we first committed to prison.
Pray let me read on; the matter is further cleared.

[.numbered]
_Fourthly;_ The second warrant is contradictory to the first,
in that it admits of no bail nor mainprise for the prisoners,
which the first admits of in these words, i.e.:
Being required to find sureties for their respective
appearances at the next general sessions.
Whereas the prisoners were no more criminal when the second warrant was made,
than when the first was made, being then in hold upon their commitment.

[.numbered]
_Fifthly;_ The prisoners were not convented nor had in examination before the justice,
when the second warrant was made, to answer for themselves,
as they ought judicially to have been, if he had any new matter unbailable against them,
or any matter of such high and criminal nature when he made the second,
which he had not when he made the first, as to render them incapable of bail.
Therefore his second warrant is illegal and extrajudicial,
and the court is not bound to take notice of it.

[.offset]
+++[+++After the fifth exception the recorder again interrupted]

[.discourse-part]
_Recorder:_ While I have to do here, I will not allow myself to be thus reflected upon.
It is a dishonour to the court.

[.discourse-part]
_Court:_ How many more have you to read?

[.discourse-part]
_George Whitehead:_ But a very few; I shall quickly have done.
You may call for any of them to be read over again when I have done.

[.discourse-part]
_Court:_ You may go on.
Go on.

[.numbered]
_Sixthly;_
If it be objected that the prisoners refused to take
and pronounce the oath of obedience to the king,
being duly required by Justice Bacon, that is an apparent mistake.
If the warrant of their commitment be of credit, it shall be evidence,
in that it admits of no bail, as before: which the refusal of the said oath,
being so required, admits not of: but the prisoners were not committed on that account.
And therefore the second or collateral warrant, which is of another date,
and no commitment, is grounded on a mistake in that point, and is an extrajudicial thing;
and therefore not to be taken notice of, but rejected by the court, and held for none.

[.numbered]
_Seventhly;_ Justice Bacon could not legally, nor duly,
require the prisoners aforesaid to take the said oath,
according to the tenor and plain express words of the statutes, provided in that case;
they not being under those circumstances and causes, which the law provides and limits,
as precedent to one justice`'s being authorized to require it.

[.offset]
Upon the seventh exception, when read, the recorder alledged thus:

[.discourse-part]
_Recorder:_ If I find you under any one of those circumstances or causes,
I might tender you it.

[.numbered]
+++[+++Observation added,--__First;__
But he did not assign or show any one circumstance that the prisoners
were under to warrant him alone to tender of the oath.
However, he hereby granted, that he had no power alone to require the said oath,
without limitation of such precedent circumstances.

[.numbered]
_Secondly;_ The circumstances and causes precedent, and prescribed by the statute are,
"`The persons standing indicted or convicted for not coming to church,
or complained of by the minister, petty constable and church wardens, or any two of them,
to any justice of peace near adjoining to the place,
where any person complained of shall dwell,`" etc.
It is only in such case that one justice has power to require the said oath.
His power is apparently limited by the law to certain precedent circumstances,
under which circumstances and capacity, neither the prisoners nor the justice stood;
and therefore were not in statu quo,
for the oath to be legally required of them by one justice.]

[.numbered]
_Eighthly;_ The oath of obedience could not be legally tendered on the 21st of March, 1679,
being the Lord`'s day; because that no writ, process, warrant, order, judgment,
or decree are to be served on that day, except in cases of treason, felony,
or breach of the peace, which the case of the said oath is none of:
it is a case of itself distinct.
See the act for the better observation of the Lord`'s day, commonly called Sunday,
_Anno vicesimo nono Caroli secundi,_ 1677.

====

[.offset]
+++[+++After the eighth exception being read.]

[.discourse-part]
_Recorder:_ Now you have prepared a knife to cut your own throat withal by that exception;
+++[+++in case of treason, felony, or breach of the peace]
your meetings are against the peace, or to that effect.

[.offset]
+++[+++The recorder did not deny the tender of the oath to be a proceeding in law: no,
we presume he could not deny it.]

[.discourse-part]
_George Whitehead:_ That our meetings are against the public peace,
remains to be proved upon the premises of our court order +++[+++prevented and interrupted,
when these words should have been added,
being clearly intended for argument in relation to the exception.]
That the tender of the oath of allegiance is a case of itself,
distinct from the cases of treason, felony, and breach of the peace.
For it cannot be justice to excuse or acquit traitors, felons, or breakers of the peace,
by tendering them the oath of allegiance, or by their taking it.
That were an easy way for traitors and felons to
escape the condign punishment of the law;
there is other process or proceeding in law,
more properly limited and assigned against them.
For how many oaths would not traitors and felons take,
if swearing would free them from the judgment or condign punishment of the law?
What oaths would not such take to save themselves?
Seeing the recorder seemed not to deny the tender of the oath to be a process in law,
his answer.
That your meetings are against the public peace, was beside the point.
His requiring the oath is neither the process nor the penalty of the law,
for the breach of the public peace: they are distinct cases and processes.

[.discourse-part]
_Recorder:_ Have you anything against the oath of allegiance?
Or do you except against anything contained in it.?

[.discourse-part]
_George Whitehead:_
We have nothing to except against the declaration of allegiance contained in it,
as to the substance thereof.

[.discourse-part]
_Thomas Burr:_ We show our allegiance by our conduct, that is,
by our living peaceably under the king and government.

[.discourse-part]
_Recorder:_ Do you scruple any word or thing contained in the oath?
If you do, tell us what it is.

[.discourse-part]
_George Whitehead:_ We both own and can sign the declaration of allegiance,
in opposition to the pope and popery:
and to those seditious or treasonable practices and
positions abjured and renounced by that oath.

[.discourse-part]
_Recorder:_ Do you hold it unlawful to take an oath in any case?

[.discourse-part]
_George Whitehead:_ We are not committed to prison to answer questions at sessions;
but to answer to the premises contained in our court order.

[.discourse-part]
_Recorder:_ Do you not hold it lawful to tell a lie?
i+++.+++ e+++.+++, an officious lie, to prevent an imminent danger, or to that effect.

[.discourse-part]
_George Whitehead:_ No, by no means; that is not a true Protestant principle,
to tell or maintain an officious lie, so called.

[.discourse-part]
_Recorder:_ Will you take the oath?
If you will, hold up your hand as a testimony that you do take the oath, or swear,
that shall serve.

[.discourse-part]
_George Whitehead:_ We have a protestation or declaration against the pope and popery,
which was delivered to the committee of Parliament,
and thereby judged sufficient to distinguish us from popish recusants:
we crave leave of the court to read it.

[.discourse-part]
_Recorder:_ What difference is there between a protestation and an oath?

[.discourse-part]
_George Whitehead:_ It may be a protestation or testimony against popery, yet not an oath.
I pray you, let us read our protestation,
that we may not lie under suspicion without cause.

[.discourse-part]
_Court:_ You may.
Read it.

[.offset]
The protestation read in court, which follows:

[.embedded-content-document]
--

[.letter-heading]
A Protestation or Declaration, to distinguish Protestant dissenters from Popish recusants.

I +++________+++, do in the presence of Almighty God, solemnly profess,
and in good conscience declare, it is my real judgment,
that the church of Rome is not the real church of Christ; nor the pope,
nor bishop of Rome, Christ`'s vicar:
and his or their doctrines of deposing heretical princes,
and of absolving their subjects of their obedience,
of purgatory and prayers for the dead, of indulgences, and worshipping of images;
of adoring and praying to the virgin Mary, and other saints deceased;
and of transubstantiation,
or changing the elements of bread and wine into the body and blood of Christ, at,
or after the consecration thereof, by any person whatsoever; are false, erroneous,
and contrary to the truth of God, declared in the holy Scriptures.
And therefore, that the communion of the said church is superstitious and idolatrous.

And I do likewise sincerely testify and declare, that I do from the bottom of my heart,
detest and abhor all plots and conspiracies that are,
or may be contrived against the king or Parliament, or people of this realm,
or the true Protestant religion therein professed.
And I do hereby faithfully promise, by God`'s help, to live a peaceable and sober life,
as becomes a good Christian and Protestant to do.

And all this I do acknowledge, intend, declare and subscribe,
without any equivocation or mental reservation; according to the true plainness,
simplicity, and usual significations of the words.

[.signed-section-signature]
--Witness my hand.

--

[.discourse-part]
_George Whitehead:_ This was accepted by a great committee,
and entered in the journal of Parliament,
in order to distinguish us from popish recusants, etc.

[.discourse-part]
_Recorder:_ We have not a law to accept it.
It is not enacted or made a law.
We must proceed according to law.
You seem to declare for the true Protestant religion,
when you dissent from the church of England.^
footnote:[This renders protestancy but in a narrow compass,
as if all dissenters were no Protestants.]
I am not in that point satisfied with your declaration, +++[+++or to that effect].

[.discourse-part]
_George Whitehead:_ We have no mental reservation in the case:
we are willing and ready to sign this declaration
+++[+++Interrupted when about adding these words:]
The true Protestant religion is wholly opposite to popery;
it stands in protestation or testimony against popery;
it is a negative testimony thereof.
So far as any Protestants in the church of England, or elsewhere,
do really protest against, and sincerely disown popery,
so far are we of the same judgment with them.
But there are Protestants of several degrees; some are more refined,
and more clear of popery than others.
Is there any evidence against us to prove the premises contained in our court order?
Where are our accusers?

[.discourse-part]
_Recorder:_ The premises; what are they?

[.discourse-part]
_George Whitehead:_ The being at an unlawful assembly, in disturbance of the public peace,
as is pretended against us; let us be tried, and either condemned or acquitted hereupon.

[.discourse-part]
_Recorder:_ I was more favourable to you than you deserved;
for I could have drawn an indictment against you at common law,
and brought you to a trial upon it: which being found against you, I must have fined you.
We who are in commission for the peace, are _lex loquens,_
and to give the true meaning of the law.
We are not to make laws, but to interpret the law.
We are to punish or amerce offenders,
_secundum qualitatem et secundum quantitatem delicti,_ etc.

[.discourse-part]
_George Whitehead:_ We are not at present about to justify ourselves, as to matter of fact.
We are willing to hear evidence of what any can prove against us,
in relation to our assemblies.
Let us have due process.

[.discourse-part]
_Recorder:_ If the court will agree to it, we will adjourn:
and I will provide an indictment, and give order that the witnesses shall be here,
and will give it to the grand inquest; and if they find it against you,
you shall be fined forty pounds, and imprisonment till paid.

[.discourse-part]
_Prisoner:_ It seems the witnesses are yet to procure.
Is there any here that can give evidence against our meeting, of the breach of the peace, etc.

[.discourse-part]
_Recorder:_ That is a lie.
I did not say I would procure witnesses: that is scandalous.

[.discourse-part]
_Thomas Burr:_ We desire that no advantage may be taken against us for a word.
You ought not to take advantage.

[.discourse-part]
_George Whitehead:_ I intended no offence in the word procure;
I intended it not in the worst sense, i. e., as by way of subornation;
for I intended no other than according to the recorder`'s own words,
that witnesses should be here, or the like, which doubtless many present heard.

[.discourse-part]
_Prisoner:_ Well, we refused not to be tried upon the charge in our court order,
touching our meeting, etc.

[.discourse-part]
_Recorder:_ You shall have the oath put to you.
And I will tell you what danger you incur:
if you refuse to take it you are to be put out of the king`'s protection,
your lands and estates forfeit to the king,
and your bodies imprisoned during the king`'s pleasure.

[.discourse-part]
_George Whitehead:_ We understand what a premunire means,
according to the statute of premunire,
made in the sixteenth year of king Richard the second;
though there is no equity that should be brought upon us while we practice our allegiance.
Suppose we cannot for conscience sake swear.
It is but hard measure to bring us under the penalty of premunire for that cause only.
What equity can there be in it?
Seeing we utterly deny the pope and popery; to which we may justly add,
and abhor those treasonable practices and positions which are abjured by that oath.
Suppose we have such a scruple of conscience, as that we cannot swear allegiance,
while we both practice it, and are willing to declare it;
and to sign the declaration or substance of our allegiance.
Can it be equal or just to run us to a premunire, to forfeit our estates, liberties,
etc., only for lack of swearing?
How can that be either _secundum qualitatem,_ or _secundum quantitatem delicti,_
as it is supposed.

[.discourse-part]
_Recorder:_ You talk of conscience.
Friend, friend, let me ask you one question: pray what is conscience?

[.discourse-part]
_George Whitehead:_ It is that knowledge that God has placed in man;
it is a knowing together between God and our own souls,
by virtue of the law of God in man, whereby he knows what is good, and what is evil:
and whereby he is taught to embrace the good and shun the evil.
It is called the law of truth, the law of equity, the law of reason, etc.
Against which law, says the law book, Doctor and Student,
no law or custom ought to be brought, but it is void.

[.discourse-part]
_Recorder:_ Although I asked you a question, I did not bid you preach upon it.
But conscience may be seared; as when men will not be reclaimed,
but have their own wills, be they never so contrary.

[.discourse-part]
_George Whitehead:_ It is true; some men become hardened and seared through sinning,
and for lack of being exercised by that law of God in them:
yet there is a universal law of truth in mankind, whereby even the wicked,
and those of seared and hardened consciences,
shall finally be convicted and awakened in torment.

[.discourse-part]
_Recorder:_ You must have the oath put to you:
the court must tender you the oath of allegiance; will you take it?

[.discourse-part]
_George Whitehead:_ We lie under a charge in our court order:
let us be discharged of that first.
That contains the premises which we are to answer to.
Let us not be hood-winked.
Are we discharged of the two warrants that are against us, yes or no?
The rest of the court ought to know, that one thing may not confound another.

[.discourse-part]
_Recorder:_ You talk law as you talk gospel; here you talk a little,
and there you talk a little: it is pity you have the benefit of the law:
you put yourselves from the protection of the law.

[.discourse-part]
_George Whitehead:_ The recorder is a party against us: he is our accuser,
prosecutor and judge.
He inveighs against us.
He is determined against us: he has told his resolution aforehand.

[.discourse-part]
_One Justice:_ You offer contempt against the king, in what you say against his minister:
the recorder is his minister, +++[+++or to the same effect].

[.discourse-part]
_George Whitehead:_ No such matter:
I only oppose an undue and irregular procedure--which is not the king`'s will.

[.discourse-part]
_Recorder:_ Your words tend to stir up the people here to sedition.

[.discourse-part]
_George Whitehead:_ We have no such design: we only plead our own rights as Englishmen:
the losers must have leave to speak: our liberties and estates,
and families are concerned our wives and families suffer by our restraint.

[.discourse-part]
_Recorder:_ Clerk, tender him the oath: offer him the book.

[.discourse-part]
_Clerk reads:_ I George Whitehead, do truly and sincerely acknowledge, profess, testify,
and declare in my conscience, etc.

[.discourse-part]
_George Whitehead:_ Forbear: we have matter of plea which ought to be heard first.

[.offset]
+++[+++Here a great noise was made by some present.]

[.discourse-part]
_Crier:_ O yea: silence in the court.

[.discourse-part]
_George Whitehead:_ We beg of the court that we may not be thus run upon,
but duly heard upon the process we suffer under.

[.discourse-part]
_Recorder:_ Will you take the oath: answer,
and then you shall know the pleasure of the court.

[.discourse-part]
_George Whitehead:_
We ought to be at some certainty whether we are discharged
of the premises laid against us in the two warrants.
The recorder was even now for indicting us at common law:
now he is all in haste to put the oath upon us.
Thus he appears inconsistent with himself: he is not now _lex loquens_ to be sure;
for the law speaking, does not contradict itself.
He is not the mouth of the law,
in running thus unduly and abruptly upon us with the oath,
to evade the premises which we were to answer.
Are we discharged of the two warrants, yes or no?
Let us have the plain advice or sense of the court.

[.discourse-part]
_Recorder:_ It may be you may suppose you are discharged:
what is the consequence you will infer from there.

[.discourse-part]
_George Whitehead:_ We desire a plain answer: we are not to be answered by supposition,
nor from there to draw consequences now.
We are not called here to dispute upon a hypothetical argument.
We expect a positive, plain answer,
and the sense of the court concerning our court order and warrant.
Are we discharged of them, or not?

[.discourse-part]
_Some of the court to the recorder:_ Let them be discharged of them.

[.discourse-part]
_Some of the court:_ You are discharged of them.

[.discourse-part]
_George Whitehead:_ Does the recorder say so?
Does he assent to it?
Let proclamation be made of it then, that we may be set at liberty,
in the same capacity we were in before we were first arrested.

[.discourse-part]
_Recorder:_ No, no; seeing you will take your way, I will take my way:
you shall have the oath first, and then your discharge.
Will you take the oath, and then you shall be discharged.
What say you to it?
Read the oath.

[.discourse-part]
_Thomas Burr:_ It is a force put upon us; it is very hard dealing we may not be duly heard.

[.discourse-part]
_George Whitehead:_ Are the rest of the justices of the same mind,
that we should be thus run upon?
We hope you are not all of the same mind with the recorder in this proceeding.
He is engaged against us: he is resolved to make something of it,
and to make us exemplary in suffering.

[.discourse-part]
_Recorder:_ Stop his mouth; take him away.
They had not only need to have their hats pulled off, but their mouths stopped also.^
footnote:[This the prisoner did not fully hear, others affirm they heard it.]

[.discourse-part]
_George Whitehead:_ Pray hear us; we have more to offer, as about this tender of the oath,
to show how undue it is, if you will but permit the law to be read, which we desire.
+++[+++But we ought first to have had proclamation made for our discharge from the two warrants.]

[.discourse-part]
_Recorder:_ If we should made proclamation, and let you go, we should be laughed at.
No, no: I see you lay upon the catch; we will not discharge you.
Now we have you here, we shall not let you go, to send a warrant after you,
to fetch you again.
Will you take the oath or not?

[.discourse-part]
_George Whitehead:_ Is this intended for a first tender, or a second?
We desire an answer.

[.discourse-part]
_Recorder:_ We will tender it you _de novo:_ it shall be for a first tender;
and if you will not take it, you shall be committed till next sessions, etc.

[.offset]
Clerk reads the oath.

[.discourse-part]
_Clerk:_ I Thomas Burr, do truly and sincerely acknowledge, profess, testify,
and declare in my conscience, etc.

[.discourse-part]
_George Whitehead:_ We appeal to the mayor, and the rest of the justices.
The recorder is a party against us; he has determined against us beforehand:
I will prove that he is no competent judge in our case, if I may be heard.
+++[+++--Interruption]
Are we discharged of the two warrants?
Pray let us have fair and plain dealing.
Do not thus force upon us; it is unfair and undue proceeding.
Let us be discharged of the two warrants first, before we be put upon an answer.
We ought not to be put to our answer, but upon due process.

[.discourse-part]
_Some of the court:_ You are discharged from those two court orders.
Clerk, read their discharge.
+++[+++The clerk reads what the recorder had caused him to enter into the book,
to this purpose.]

[.discourse-part]
_Clerk:_
George Whitehead and Thomas Burr are discharged of
the matter contained in their two court orders.
And the oath of allegiance, and the testament, to swear in open court,
at this present sessions was severally tendered to them;
and the said George Whitehead and Thomas Burr,
having severally refused to take the said oath of allegiance, it is therefore ordered,
that the said George Whitehead and Thomas Burr,
be committed to the common jail of the said city,
there to remain without bail or mainprise, until the next quarter sessions, etc.

[.discourse-part]
_George Whitehead:_ The latter part is not true; we have not yet refused the oath;
we were not duly or regularly brought upon that point, so as to give a positive answer,
because of the other precedent charges, which we were to answer to.
We have yet matter of plea about the tender of the oath, _de novo,_ in court.
We request further time to be heard upon an adjournment
before we give our positive answer.
We desire to know upon what law or statute it is tendered.
+++[+++No answer was given to this question.]

[.discourse-part]
_Recorder:_ You have stronger lungs than I: I understand you had a feast last night.
Adjourn the court: take them away jailer.

[.discourse-part]
_George Whitehead, prisoner:_
Pray let us have more time to consider and speak to this point.
I entreat that I may have leave to read the clause in the statute,
that concerns the tender of the oath.

[.small-break]
'''

These endeavours of the prisoners to be heard, after the pretended order was entered,
were because the prisoners did not believe that the justices, or greater number of them,
did concur with the recorder`'s proceeding against them; but that they had more,
both of moderation and justice in them;
and that he carried things on too much over their heads,
and all to run down and ensnare the prisoners, to oppress them,
and continue them under suffering.

[.discourse-part]
_Officers:_ The court adjourned.

[.offset]
Prisoner, George Whitehead held by the bar, pressing to be further heard,
after the adjournment, when the court met again,
and for the statute to be read about the oath;
neither whereof would be granted the prisoners,
but two of the keepers pulled the prisoner away.

[.discourse-part]
_Prisoner:_ Take notice, that we have not yet refused the oath,
being not duly nor regularly brought upon that point;
but we have owned the declaration of allegiance, contained in it;^
footnote:[These last words are since added,
the prisoner being hurried away that he could not then speak them out.]
and do still freely assent to it, in opposition to,
and abhorrence of all those treasonable practices, positions and principles,
abjured and renounced by that oath; though we are conscientiously afraid to swear it,
only with respect to Christ`'s prohibition, in the case of swearing.

[.small-break]
'''

On the 3rd day of the month called May, 1680,
being about five days after the prisoners were thus proceeded against in court,
the recorder, Francis Bacon, was voted out of place by the common council.

Many of the said recorder`'s reflections and hard speeches against the prisoners,
are purposely omitted in the foregoing account for
brevity sake and with respect to the moderate reader,
by whom we would not be thought to overcharge any person, though he was an adversary;
therefore we have in some particulars been more sparing than we might have been.

A copy of the prisoners`' certificates, which the recorder, Francis Bacon,
would not permit to he read in court.

[.embedded-content-document]
--

These are to certify all whom it may concern, that George Whitehead,
of the parish of St. Buttolph Bishopsgate, London,
has lived in the same parish for about ten years last past, in good repute,
and is esteemed a man of a competent estate, and has lined for all offices in the parish,
save church warden, and has demeaned himself peaceably in his conduct;
and he has never been accounted or reputed to be a Jesuit or Papist,
or any way popishly affected.
All which we certify under our hands.

[.signed-section-signature]
John Freeman, Thomas Fyge, Common Councilmen; John Russen, Deputy; Gilbert East,
John Osburn, Church Wardens; John Sumner, Constable; Charles Bathurst, Thomas Dawson,
Nicholas Harding.

[.signed-section-context-close]
London, April 22nd, 1680.

--

[.embedded-content-document]
--

These are to certify any person or persons whom it may concern, that Thomas Burr of Ware,
in the county of Hartford, maltster, has lived,
and been a trader in malt for about fourteen years past;
and is a man whom we judge of a good competent estate,
and of good credit and reputation among his neighbours in this place,
and has never been accounted a Jesuit or Papist.
All which we certify under our hands.

[.signed-section-signature]
Giles Roe, Henry Hart, Church Wardens; John Lark, William Moakes, Constables;
John Perrot, Henry Peach, Thomas Johnson, Richard Dickinson, Rivers Dickinson,
Edmund Pease, Isaac Hadsley.

[.signed-section-context-close]
Ware, in Hartfordshire, this 14th day of April, 1680.

--

A copy of the next letter, after the foregoing proceedings in court,
delivered to the mayor, etc.

[.embedded-content-document.letter]
--

[.salutation]
Friends,--the Mayor, Justices, and Aldermen of this city, Norwich.

We do acknowledge, and kindly resent, that indifferency and moderation towards us,
which we beheld among you when before you in your court of sessions,
as also the justice you did us, in making way for the reading our court order,
our exceptions, our declaration against popery, and the fixing of our discharge in court,
from the matters contained in our court order and warrant;
whereby we are the more encouraged to make this one small request to you, which is,
that you will please but to afford us the liberty
to come before you in your council chamber,
though it be with a keeper,
that we may show you one material point of law in the statute book,
relating to this _de novo,_ or new tender of the oath, in your quarter sessions,
which we now suffer under,
it being the same point that we were earnest to have shown you out of the statute book,
but were forcibly prevented.

In granting us this small request,
you may happily be capable of doing yourselves and us more justice and right,
than you may at present be aware of.
It is not too late to reverse an error and embrace truth, when made appear in any case;
nor will any sincere mind shun the discovery of either.
It is in real love and good will to you, this proposition, by way of request,
is made for your own sakes as well as ours.
We design no tediousness to you; our case is now contracted into a narrow compass:
what we have to show you, is both very brief, and easy to understand;
it is directly statute law.
Our confinement before sessions was but one man`'s act;
but now others of you are concerned.

Howbeit, we may reasonably as well as charitably think and believe,
that both the forcible tender of the oath,
while not actually discharged and freed from our imprisonment,
and the conclusion against us, for our detention,
were rather the hasty and indiscreet acts of one person, carried on over your heads,
than of the whole court, or major part thereof; and hope,
that as you calmly come in God`'s sight to the righteous test of conscience and truth,
and upon better deliberation consult the law in our case,
it will so appear to your understandings.
We are yet willing charitably to think and hope the best
concerning you in this weighty concern of our liberties,
estates, families, and consequently our lives, which are exposed to jeopardy and ruin,
through our present suffering among you.

Nevertheless our case is not desperate in the eye of the law.
They who are appointed ministers of equal law and justice,
ought to understand both before they pass judgment, or inflict punishment.
As Michael Dalton puts the commissioners of the peace in mind,
How that justice may be perverted many ways,
if they shall not arm themselves with the fear of God, the love of truth and justice,
and with the authority and knowledge of the laws of this realm, etc.
Among which causes of perversion, he mentions these:

[.numbered-group]
====

[.numbered]
1+++.+++ Fear, When fearing the power or countenance of another, they do not do justice.

[.numbered]
2+++.+++ Perturbation of mind, as anger, or such like passion.

[.numbered]
3+++.+++ Ignorance, or lack of true understanding what is to be done.

[.numbered]
4+++.+++ Precipitation, or too much rashness, as when they proceed hastily,
without due examination and consideration of the fact, and all material circumstances, etc.
(Thus far M. D.)

====

We design no personal reflection,
but only tender information and caution in these passages.
The thing we aim at, is but the leave of a few minutes before you,
to show you the point of law mentioned, which we forbear to relate in writing to you,
as not being proper or seasonable for us so to do at present,
considering the circumstances which we are under.
We are your real friends and well wishers,

[.signed-section-signature]
George Whitehead, Thomas Burr.

[.signed-section-context-close]
Norwich prison, the 8th of the third month, called May, 1680.

[.postscript]
====

P+++.+++ S. This provision we would further add,
that if so be our proposal of coming before you, in your council chamber,
may not be accepted, or be not thought feasible,
we then desire you would please to transmit our request to your quarter sessions,
yet in being upon adjournment,
that we may have the liberty at your next meeting in your court of sessions,
briefly to offer what we have to plead in point of law,
to your serious and more deliberate considerations, about the late tender of the oath,
_de novo,_ according as we desired further time for the same purpose,
when last in sessions.

====

--

The substance of a further application made by the prisoners to the mayor, recorder,
justices, and aldermen of the city of Norwich,
delivered to them the 17th day of the third month, 1680,
being the last day of the quarter sessions.

The first part relates to the mediation of certain persons of note and eminency,
on the prisoners`' behalf, and particularly by a letter from London,
from a person of quality, on application made by some of their friends there,
unto which the prisoners referred the magistrates in these words:

[.embedded-content-document.letter]
--

We therefore request, that you would please to call for the said letter,
and know the contents thereof, that if such mediation may take effect with you,
for our enlargement, we may not put you or ourselves to trouble, upon any further motion.
Otherwise, if you are not pleased to accept thereof, so as to grant us our enlargement,
we have another proposition to make on this wise:

Whereas, we the prisoners, whose names are hereunto subscribed,
do find ourselves oppressed and grieved, not only by the illegal proceedings,
as we conceive, of the late recorder in our commitment and detention in prison,
by two erroneous warrants, which were reversed in court,
but also by his late commitment from sessions,
which not only we do conceive to be illegal and contrary
to the form and order of law prescribed in the statutes,
but also we have the advice and judgment of able counsel in the case, averring,
this last commitment not good, but against law, etc.

Upon which premises, if you please not to allow us remedy on the mediation aforesaid,
we do in humility request, that you will please to call us into court,
before this sessions be ended,
and grant us the liberty but briefly to offer our exception in point of law,
unto your serious and deliberate considerations,
in order to afford us so much relief and right, as may either by apparent law, equity,
or good conscience, be allowed us.
Your friends and prisoners,

[.signed-section-signature]
George Whitehead, Thomas Burr.

[.signed-section-context-close]
Norwich jail, the 12th day of the third month, 1680.

--

Our friends Mary Duncon and Mary de France of Norwich,
attended the court of mayor and justices in their council chamber,
and delivered the aforesaid application and certificates to them, where they were read,
as the prisoners were informed.

After the mayor and justices came down into the hall, our friends above-said,
attended the court of sessions, and moved for the liberty of the prisoners,
as some of the justices had before directed, to which others of them said,
that could not be, for they were committed by order of sessions; which the steward,
being then judge of the court in the recorder`'s absence, caused to be read.
Mary Duncon then requested the prisoners might be called into court and heard;
the new recorder having promised her, as she affirmed,
immediately after she came from him, that they should be called into court;
and that if it appeared they were committed contrary to law, they should be discharged.
But he being then absent, they were not called into court.

Samuel Bolton of London, being present, got leave of the court, upon his request,
to tell them, that he did suppose it was contrary to law,
to make the first tender of the oath in court;
and that was done on purpose to ensnare the prisoners.
Whereupon the steward called to bring the statute book, to see whether it was so or not;
but in the interim, after a little consultation, the court was suddenly dismissed,
before the book came: so the prisoners were detained until the next quarter sessions.
Whereof an account is hereafter given, as to their discharge.

After two letters had been sent to the recorder,
upon the prisoners`' request for a little discourse
with him and the steward about their case,
they were called into the council chamber, and the keeper with them,
before him and the steward, and Thomas Corys, etc.,
and there admitted to open their case,
and to enter into some discourse about the proceedings against them.
They did not seem to vindicate the other recorder`'s proceedings,
only some little controversy was about the late tender of the oath, _de novo,_ in court.

However,
the prisoners kindly acknowledged their civility
in giving them that opportunity of discourse.

[.embedded-content-document.letter]
--

[.blurb]
=== A few lines to the mayor, court of aldermen, and justices, on some other considerations more particular.

[.salutation]
Friends,

We being injured and hurt in several respects by our confinement,
for above these three months past,
by means of the late recorder`'s prejudicial and undue proceedings against us,
both before and at your last quarter sessions, together with your passiveness therein,
and all this under a wrong suspicion of our being Papists, or popish recusants,
secretly suggested against us;
which being intimated to some persons of quality and credit at London,
who have better knowledge of us,
and the Earl of Yarmouth being moved by them on our behalf,
he was pleased to mediate for us by letters,
to be communicated to some of the magistrates in this city,
in which we understand he has lately signified what
testimony he has of our being no Papists,
and therefore desires that you would show us all the favour the law will allow us,
as we have been informed, which cannot reasonably intend the rigour of the law,
much less to be detained in prison contrary to law, as we still conceive we are.

We therefore entreat you, first; To consider what favour the law allows us as no Papists,
nor persons so reputed, as indeed we are altogether averse to popery.

Secondly;
As persons injuriously imprisoned and detained under
a wrong suspicion of what we really are not.
We request our liberties;
which request we think ourselves both obliged in conscience and warranted by law,
to make to you, as justices of the peace,
according to the statute made in the fourth year of king Henry the seventh,
which is worth your while to read over,
and seriously to consider the tenor and purport thereof.

[.signed-section-closing]
Your friends and prisoners,

[.signed-section-signature]
George Whitehead, Thomas Burr.

[.signed-section-context-close]
From your city jail, the 19th of the fourth month, 1680.

--

[.embedded-content-document.letter]
--

[.letter-heading]
For the Mayor and Justices of the city of Norwich.

[.offset]
Friends, you are entreated to peruse the following narration.

The great pretence for our strict detention in your jail,
being the late order from sessions, we think ourselves obliged for your sakes,
as well as our own, to remind you, that we esteem ourselves injured,
in that we were not allowed to be called into the
court the last day of your quarter sessions,
for an opportunity to have made our exception,
which we conceive we had good ground for both in law and good conscience; especially,
since we had promise of such an opportunity,
and that if it appeared our commitment were contrary to law, we should be discharged.
This we understand was made to one of our friends, who,
upon encouragement by some of the justices, moved for our liberty in court;
which not being granted, then, that we might be called into court;
but being prevented of both,
we are detained to our own and our families`' great prejudice in various respects;
our present restraint being also a depriving us of our rights in the creation,
and to the impairing of our healths.
The late order from sessions for our restraint without bail or mainprise,
was of Francis Bacon`'s ordering,
and we know no other law than that to detain us so severely until next sessions;
and no doubt you had power to reverse it before the termination of the last,
when the illegality thereof had been made appear,
which we endeavoured an opportunity for; we sought and earnestly requested it,
charitably thinking to find so much of humanity, tenderness,
equal law and right among you towards us,
as not thus to delay us in prison upon the said order,
which we are persuaded will not redound to the honour of your city or court,
considering our innocency, and the circumstances of the person who was the cause of it.
We cannot reasonably suppose,
that such an order should bind your consciences from answering the law of Christ,
To do to others as you would be done by; and the law of our nation, Not to deny, defer,
or delay justice, or right, especially to any free born Englishman.^
footnote:[Magna Charta, cap.
29, J. Coke, Inst, part 4, fol.
182.]
Illegal or unjust imprisonment, more especially where prolonged,
being accounted odious in the eye of the law; that you may more clearly perceive,
that to detain us in the pursuance of Francis Bacon`'s procedure and order against us,
will not redound to your reputation and honour,
either as civil magistrates or Christians,
pray consider how irregularly and arbitrarily he has acted towards us in his whole procedure.

In sending the sheriff to apprehend and imprison us for being at the meeting,
as he confessed in sessions he did,
by which means we were turned into the jail by the sheriff, like cattle into pinfold,
and there detained for some hours, without examination or court order,
other than Francis Bacon`'s verbal commission.
How arbitrary and illegal was this?
You that are wise men,
judge what absolute monarch could have shown more rigour in such a case:
consider the consequence of such proceedings.

We hope your design in choosing recorders, is for a just and legal end,
to assist you as the king`'s ministers of equal law and justice,
and not to be as kings and emperors over your city,
nor that any one should assume such prerogative or preeminence,
so contrary to law and the king`'s interest.

The king has a prerogative in all things that are not injurious to the subject;
but the late recorder assumed a prerogative or dominion,
injurious in these his proceedings.

In his inflicting a twofold punishment for one supposed offence, i. e.,
fining and imprisoning for being at a meeting,
contrary to that very act against conventicles,
which was not made to commit the persons to jail, but only to fine them;
albeit our meetings are no otherwise designed by us than for God`'s worship and service.
When he first examined and committed us, he told us,
"`If you will neither pay your fines nor take the oath of allegiance,
I must commit you to prison; you may choose whether you will pay your fines,
take the oath, or go to prison.`"

To excuse these proceedings against us, being all on the 21st of March, 1679,
which was the Lord`'s day, +++[+++so called,]
when we excepted against them, as contrary to a late act of parliament,
for the better observation of the Lord`'s day,
he alledged that our meeting was against the peace.
And what follows?
Therefore he might first send the sheriff to apprehend
and imprison us without court order,
and after that fine us, and tender us the oath the same day;
and if we would neither pay our fines nor take the oath, then commit us to prison.

The act for the better observation of the Lord`'s day,
prohibits the serving or executing any writ, process, warrant, order, judgment,
or decree, excepting in cases of treason, felony, or breach of the peace.

If in these, or any of these cases, the requiring persons to take the said oath,
and their taking of it will serve the turn to excuse them of such crimes;
then that oath may be a cure for all diseases or enormities
against law of what different species or kinds soever.
The justices need but require treasonable, felonious, fighting,
and quarrelsome persons to take the oath of allegiance,
and their taking it shall quit them of all pains and penalties.
But we hope you are so rational as to understand,
that legally to require the said oath is a distinct case,
or process from the cases of treason, felony, or breach of the peace;
and that there is no more reason to require the said oath in any one of these cases,
than in all of them.

In his laying our fines upon other persons,
and imprisoning us for being at the said meeting,
and giving out warrants to break open their doors and distrain their goods,
upon a false pretence of our poverty, after we had plainly signified the contrary to him,
both as to the competency of our estates and known habitations,
so that he could have no reason to think us unable.

But besides the illegality hereof,
what justice could there be between his fining others because of our poverty,
and committing us to jail because of our non-payment thereof?
He imprisons us because we do not pay our fines;
and lays our fines upon others because we cannot pay them.

But this is not the least inconsistency in his perplexed proceedings:
he demands twenty pounds of each of us for preaching;
and because we did not deposit the money, he commits us to the common jail,
under pretence of being assembled in disturbance of the public peace,
by a warrant made in his own, and not in the king`'s name,
and then lays our fines upon others, which was all for one and the same meeting.
These proceedings are as reconcilable as if he had fined us for praying,
and committed us to jail for fighting while at prayer;
but we are more serious in our devotion, and innocent in our deportment,
blessed be the Lord our God.

We further entreat you to view Francis Bacon`'s proceedings
against us at your quarter sessions,
and seriously to consider whether he proceeded either legally or justly with us; as.

In his appearing a party, an open adversary, an accuser, a villifier of us the prisoners,
in the open court, telling us that there is a law to hang such;
and that the church would never be at quiet till such fellows were hanged;
as you may well remember, to the same effect he also told us, when he first committed us.

In his denying and opposing the reading of our court order in open court,
contrary to all reason,
and to the mind and declared judgment of the mayor and other justices upon the bench;
how imperiously did he behave himself in this?

In his not allowing our certificates to be read in court, which we earnestly requested,
which were from certain officers and other credible persons of our neighbourhood,
to remove the calumnious aspersion and suspicion of our being Jesuits or Papists,
prejudicially insinuated against us.

In his frequently and abruptly causing the oath of allegiance to be put to us,
on purpose to ensnare and circumvent us,
before the charge of our commitment was determined in court,
notwithstanding our court order signified that we
were then to answer to the premises therein contained;
and we also begged that we might be heard in our plea and
answer to the premises upon which we were committed,
before any other process was entered upon against us.

In his not allowing the law to be read in court, which we earnestly begged,
upon which he forced the said oath on us,
in order to run us to a premunire at the same quarter sessions,
as he threatened when we were first before him, understanding that we did fear an oath,
or to swear in any case.

In that when our court order and his erroneous warrant,
and his first pretended tender of the oath, by himself alone,
were reversed by our being discharged in court from the matters contained in them,
he would not allow us to be actually freed of our imprisonment;
but in pursuance of his premeditated design, forced a tender of the oath, _de novo,_
as his words were, and an order immediately to be entered for our commitment to jail,
without bail or mainprise, until the next quarter sessions,
without allowing us any further time for consideration or answer, as we desired.

His precipitancy and rashness towards us, was such therein,
that the rest of the justices, doubtless,
could not take so much time as to consider his proceedings,
before he concluded the order of commitment,
wherein they might very justly have given him a check,
and put a stop to his furious motion,
for a more general and serious consideration of the case among them,
and not have permitted him to make such a sudden conclusion against us.
For justices ought to see with their own eyes, and be sure their judgment is just,
before they give their judgment or assent in any judicial case,
seeing they had such fair warning also in our publicly
desiring to know if you were all of a mind,
or agreed against us, as to that severe commitment, charitably hoping, as we do still,
that you were not; but no answer could we have in that case.
The recorder was in such haste for that conclusion against us and the court`'s adjournment,
and to have the jailer to take away the prisoners;
he would have you to understand he wanted his dinner, upbraiding us, the prisoners,
with an idle story of our being at a feast the night before.

Besides his _de novo_ tender of the oath to us the prisoners, in sessions,
appeared neither legal nor formal, according to the form of the statute,
which intends popish recusants, as appears plainly to be the title and preamble thereof,
which we the prisoners were not, nor are we Papists at all;
but it was also against the form and course of procedure,
both of the statute allowed even to the popish recusants convict,
and that also for a first tender of the oath,
to be made out of court or quarter sessions, and a commitment of the party refusing,
and the second tender in the open session or quarter sessions, in such manner,
and on such precedent causes as the law directs, and wherein we were unconcerned.

And moreover neither of these statutes of king James do
warrant any such order for commitment of persons to jail,
from one quarter sessions to another, without bail or mainprise,
as is the late order of our commitment.

The premises considered, we really think it had been your best,
your clearest and wisest way, to have manifested your dissent,
as we gave caution at first, from Francis Bacon`'s precipitant,
irregular dealing with us about the oath, and his illegal commitment from sessions,
which is entered for pretext of authority, with the title per curiam;
and therefore our strict confinement thereby appears as your act,
howbeit it is not subscribed by any of you.
Wherefore we yet in love and good will to you,
both for your own inward peace and outward reputations, as well as our own rights,
request our liberty, we being wronged and grieved in various respects,
by the said proceedings of your late recorder;
whereof we do once more make our complaint to you for relief,
according as we think ourselves obliged in conscience, and directed also by law.

And now as we can in good conscience say,
we are persons that refuse not to swear from favour
to any principles of disloyalty or rebellion,
we do sincerely offer in relation to the declaration
of allegiance contained in the oath of obedience,
That fidelity and true allegiance to the king we do bear,
which in good conscience we believe is our duty, in opposition to,
and utter abhorrence of all those horrid seditions, and treasonable practices,
principles and positions, which are abjured and renounced in the said oath.

This declaration, in the sight of Him who searches all hearts, we do really assent to,
and own, and through his gracious assistance,
hope ever to be found in the practice of that fidelity and innocency towards the king,
whom God preserve, that become true Protestant subjects, and peaceable minded Christians;
desiring only to enjoy the liberty of the peaceable and inoffensive
exercise of our tender consciences towards our Lord Jesus Christ,
in his worship and service.
That he may direct you in righteousness, and bless and preserve you and yours,
is our prayer also.
Your friends and prisoners, for conscience sake towards our Lord Jesus Christ;

[.signed-section-signature]
George Whitehead, Thomas Burr.

[.signed-section-context-close]
Norwich jail, the 21st of the fourth month, 1680.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Recorder and Steward of Norwich.

The most that can be charged against us, as to matter of fact,
since we were discharged from the matters contained in our court order and warrant,
is our not swearing allegiance.
We were no offenders till a trap was laid to make us such, by Francis Bacon,
in his abruptly surprising us with that oath, to run us to a premunire,
as he had threatened us aforehand;
whereas the law was never intended to ensnare and entrap men.
And God knows our not swearing is not for any the least
favour to those seditious and treasonable practices,
principles and positions, abjured and renounced by that oath,
for they are an abhorrence to us.
For if we were so unnatural and perfidious as to reserve any such wicked principles,
we might as easily take that or any other oath for our own interests.
But let such collusion and fallacy be forever far from us;
it is only for fear of offending our Lord and Master, Christ Jesus,
as in all other cases.
For we your prisoners never took an oath in our lives; we dare not swear in any case,
because of Christ`'s and his apostles`' universal prohibition, as we understand it;
and many of the primitive Christians and martyrs, even Protestant martyrs,
were of the same mind.
We freely and publicly assented to the declaration
and promise of allegiance contained in the oath,
and hope ever to be found in the practice thereof;
only we are under a conscientious restraint not to swear it.
We are no papists, nor in the least popishly affected, but wholly averse to popery,
as is well known to many.

What is then lacking on our parts in this case?
Is it not only in that we swear not to that which we profess and practice?
Pray then have so much charity, humanity and good nature towards us,
as not to think so hardly of us for our conscientious persuasion,
as if we justly merited any such severe penalty, as the judgment of a premunire,
to be put out of the king`'s protection, next to the punishment of traitors,
when we bear no ill will to the king;
we have nothing but love and good will to the king and his people.

Moreover,
being sensible of a divine hand of Providence in permitting our suffering in this place,
as also that our religious cause should lose nothing by our imprisonment,
we have been the more armed with patience and clearness of spirit, in love and good will,
towards the magistrates of this city.
Also our tenderness and respect to them,
has been some stop to us hitherto from presenting our grievance, as a formal case,
to the king^
footnote:[Though we suppose he has heard by others of it.]
and council, which we really intended by way of complaint,
if the late recorder had continued in place, seeing him so much bent against us;
and if the justices would have been swayed by him,
as that we could not have found relief from them after application made to them.
And from the little converse and solicitation I, i. e., George Whitehead,
have been concerned in at court,
I could easily presuppose how the irregular and arbitrary proceedings of Francis Bacon,
and the others`' omission, apparently repugnant to the interest of both king and people,
would have been resented, and what reflection it would have procured.
Which method we find advisable and warranted for
any subject who is hurt or grieved in anything,
that remedy may not be delayed.

It is true, we have intelligent friends at London,
and some of them understanding how hardly and wrongfully we have been dealt withal,
have used some solicitation on our behalf to some persons of quality,
though we have not as yet given any direction for
a formal complaint to the king upon our case.
And what interest has already been sought for us
was never intended to interfere with the law,
or invalidate the due course of it.
The earl of Yarmouth, to whose kindness we are much obliged,
has been pleased to mediate on our behalf, by letters,
desiring that all the favour the law will allow, may be shown us,
as having received sufficient testimony concerning our reputation as being no papists,
in order to remove that pretended suspicion, to render us obnoxious.
And we hope he will be of so much repute with you
as neither to expose us to the severity of the law,
for our conscientiously fearing to swear,
nor yet to prolong us under restraint upon any such infamous, or causeless suspicion.

[.signed-section-context-close]
Norwich jail, the third of the fifth month, 1680.

This account is given you in real love and good will,
which we can assure you we bear towards you, as we are your friends,
who truly wish you well.

[.signed-section-signature]
George Whitehead, Thomas Burr.

--

A copy of the discharge of the aforesaid prisoners.

[.embedded-content-document.legal]
--

Norwich,--At the general sessions of the peace, held for the city of Norwich,
and county of the same, before Robert Freeman, esquire, mayor of the city of Norwich;
John Norris, esquire, recorder of the said city, John Mingey, esquire,
steward of the said city, and other his majesty`'s justices of peace of the said city,
the twelfth of July, in the two and thirtieth year of the reign of our sovereign lord,
king Charles the second, etc.
Anno.
Dom. 1680.

Proclamation being there publicly made, That if any person would come into the court,
and give any information or evidence,
or prefer any bill of indictment against George Whitehead and Thomas Burr,
prisoners at the bar, they should be heard.
And because no person came into the court, to prefer any indictment,
or to give in any information against them,
the said George Whitehead and Thomas Burr are ordered to be discharged,
being committed by order of the last sessions, to remain in prison until this sessions.

[.signed-section-closing]
Per Curiam

[.signed-section-signature]
Corie.

--

[.discourse-part]
_Observe._
That although we must needs grant,
that after the sense of the prisoners`' case and
suffering had made impression upon the mayor^
footnote:[i. e., H. C., whose mayoralty was out before the prisoners were released.]
and justices of the said city,
the greatest part of them appeared to be inclined and desirous
that they should be discharged before sessions,
if they could have understood how it might be regularly done,
their eye being to the recorder`'s advice in the case;
and some of them gave expectation they should be discharged at sessions.
Howbeit, in order to the more certain obtaining thereof,
the Christian care and great industry of some Friends, both at London and Norwich,
on the said prisoners`' behalf, is not to be forgotten,
and particularly that of our dear friend, William Mead,
in his efforts and hard journey to Norwich, to visit the said prisoners,
and to solicit for them, and see their discharge effected.
Such labours of love and Christian charity, God is not unmindful of.
And blessed are the true followers of Christ,
that continue in the true Christian spirit and unfeigned
love one to another unto the end;
for herein is a true sympathizing with,
and fellow-feeling of one another in all afflictions
and sufferings for the testimony of Jesus Christ,
and of a good conscience towards God.
