== Chapter XII

On the 22nd day of the twelfth month, 1682-3, a state of the case of the prisoners,
commonly called Quakers, in Norwich, Gloucester, Bristol, Yorkshire, and Northampton,
directed to the king, with request for relief,
was delivered into the hands of the Earl of Rochester, by George Whitehead,
with desire that he would please to show it to the king, which he promised he would.

The 23rd of the twelfth month, George Whitehead again spoke to the Earl of Rochester,
and desired him to show the said case both to the king and duke,
which he promised he would do, and said, "`I will read it to the king this night.`"
George Whitehead told him,
That we are advised to deliver the Norwich case singly by itself, to the council,
which we intend to do this day, being council day.
Accordingly the same day, the judges appeared at council before they went their circuits,
and George Whitehead and Gilbert Latey then attending,
the case of the Norwich suffering Friends was presented
at the council board by sir Philip Lloyd,
who was pre-engaged to it, and to move the reading of it, which accordingly he did,
but was obstructed in the reading by some in council,
on pretence that it was not a formal petition, or not in the usual form.

The 24th of the twelfth month, 1682-3, George Whitehead and Gilbert Latey,
went to the Lord Privy Seal,
and spoke to him about the said case of the Norwich prisoners,
being obstructed in the reading of it, at the council board.
He told us, that notwithstanding, after that,
the king gave a moderate recommendation to the judges when they were below,
to inquire into the state of the prisoners, and their usage.
This he told us twice over.

A little after George Whitehead and Gilbert Latey had spoken to the Lord Privy Seal,
they went up into the gallery to speak with the king, at his coming out of the park;
where, after some time of waiting,
the duke and his attendants passed by to meet the king, and after a little space,
the king and his attendants came along the gallery towards his lodgings;
George Whitehead then stepped up to the king without any interruption,
the whole company being civil, and thus proceeded:

[.discourse-part]
_George Whitehead:_ May it please the king to grant us the favour of a few words.
It is in behalf of many of the king`'s peaceable subjects who are prisoners at Norwich,
and there like to be buried alive in holes and dungeons.

[.discourse-part]
_King:_ Can they not swear themselves out of prison?^
footnote:[For this cross question,
he took occasion from some apostate taking an oath to be a livery man of the city,
as we understood.]

[.discourse-part]
_George Whitehead:_ Under favour, such are not in society with us.
We entreat the king to commiserate this distressed case of the prisoners in Norwich,
for they are burying them alive in a dungeon under ground.

[.discourse-part]
_King:_ Have you a paper?
If you have a paper of their case, I will take it.

[.discourse-part]
_George Whitehead:_ Yes, here is a paper: +++[+++which he delivered into the king`'s hand,
and he gently took it.]
George Whitehead proceeded: They are a poor, harmless people, poor wool-combers, weavers,
and tradesmen, etc., like to be destroyed in prison, in holes under ground;
we entreat the king not to allow these his peaceable subjects to be buried alive.

[.small-break]
'''

I perceived these last words took most hold upon him, i.e.:
my entreating him not to allow his peaceable subjects to be buried alive,
they being straitly confined in a low,
nasty dungeon or hole under the Guildhall of the city.

Gilbert Latey then stepped to the king, saying, "`We are the king`'s subjects,
who never did anything against him, have been peaceable, and we can truly say,
have served him, and never were against him; yet our friends are great sufferers,
and they lie in a dungeon twenty-seven steps deep in the ground, in Norwich.
Wherefore we have more earnestly sought their relief of the king.`"

My friend Gilbert Latey, as well as myself,
being often tenderly affected with our friends`' deep sufferings and hardships,
spoke to the king in very tender affection,
and a sense of the Lord`'s power and holy fear;
which reached the king`'s heart and conscience, and others about him,
beyond his utterance, or what he could in words demonstrate.
Gilbert was freely resigned to accompany me and according to his
ability to assist in those exercises and applications to the king,
in the sufferers`' behalf;
and we were often comforted together and assisted in our endeavours,
by the power of the Lord, which we had special and very tender regard to;
and he thereby helped and strengthened us to his praise,
and our great comfort and encouragement.
Glory to his excellent name and power forever.

After I had earnestly moved the king for relief of our suffering friends in Norwich,
he gave some instructions about the prisoners to the judges who
were to go the Norfolk circuit for the next court sessions following:
accordingly at Norwich, judge Hugh Windham gave order that the prisons, or rooms therein,
should be viewed, where the Quakers were confined,
and affidavits to be made thereof before a master in chancery,
which accordingly was done by an attorney,
and the affidavits were sent up to me at London,
containing a true account of matter of fact,
relating to the places where our friends were so miserably confined.

Whereupon our friend William Crouch, went with me to judge Windham,
to deliver the affidavits to him,
esteeming him the most proper person to take cognizance thereof,
being obtained pursuant to his order or advice, at the court session before,
that he might acquaint the king therewith; but instead of so doing,
or of showing compassion to the sufferers,
he refused to receive or accept the affidavits which he himself had ordered;
only he did a little look upon and read them, or part of them,
and fell to reproaching the meetings of our friends as being riots and riotous, etc.,
when they were forcibly kept out of their meetinghouse, and met peaceably in the street;
and there stood quietly waiting upon the Lord in a peaceable and inoffensive posture.
Thus our friends at Norwich and other places did, as I told the judge;
and that therefore such meetings could be no riots, nor riotous meetings,
there neither being any show of arms, nor menacing words, nor any violence offered,
nor any injury done to the persons or properties of any others;
and therefore I conceived there was nothing of the nature of a
riot committed by any of our friends in their said meetings.

Upon this discourse the judge seemed offended, and standing up with his arms a-kimbo,
and his hands on his sides, he answered: "`You will know the law better than I,
I warrant you; but I will have you know you shall not be masters over the law,
but the law shall be master over you, so long as I live, or have to do with the law.`"

I answered, "`I will not compare with you as to knowledge and learning in the law.
You have had the advantage of education therein, as well as of age above me,
which I have not had;
yet nevertheless I have had occasion in my time to
understand something of truth and justice,
having been a sufferer myself on a conscientious account,
under the several governments since we were a people,
both in Oliver Cromwell`'s days and since; and in all my sufferings and trials,
I never saw cause to change my judgment, or turn with the times,
but rather through all to be the more confirmed in
what I believe and profess respecting religion.`"

I also spoke further and closely to him;
that he had the opportunity and power to do our suffering friends in Norwich some kindness,
in order to their relief; and that he, and I, and all men,
must give account to the great Judge of all, for all our actions,
and he for not relieving our poor suffering friends, or to that purpose:
and seeing he would not accept the affidavits before mentioned,
so as to deliver the same to the king, I asked him what we should do with them?
He said, "`You may carry them to my Lord Keeper, i. e. Lord North,`" which advice,
though slightly given, I readily took hold of, having cleared my conscience to him,
the said judge,
who at last carried himself more mildly towards us
than he did in the former part of our discourse.

The next day William Crouch and I went to the said Lord Keeper, at his house,
and after being admitted to him in his closet, I told him at judge Windham`'s advice,
we were come with certain affidavits from Norwich, which the judge had given order for,
concerning the confinement of our friends, who were detained close prisoners;
and then delivered the affidavits to him.
Whereupon he began to accuse our friends`' meetings with being riotous, etc.,
much after the same manner that judge Windham had done.
I fairly reasoned the case with him a little while on our friends`' behalf,
and after some discourse, told him that we hoped he would present,
or make report of those affidavits to the king,
they being procured by judge Windham`'s order, pursuant to the king`'s instructions.
Whereupon the keeper promised he would deliver them to the king;
upon which I was eased in my spirit,
for that the king might thereby see our complaints of our friends`' hard usage in the
jail and dungeon in Norwich confirmed by such a legal proof as he could not deny;
not doubting the keeper`'s performance of his promise, we left the case with him,
and withdrew.

It was something remarkable,
that the said judge Windham had no long time to master us with the law,
which he menaced us with, i. e., that the law should be master over us;
which I took to mean the persecuting laws,
or rather the mal-administration of our persecutors,
who would judge and punish our peaceable religious meetings for riots, etc.,
when nothing of a riotous nature or fact could ever be proved against them,
or against us in them.
Though the said judge appeared very fierce against our meetings, charging them,
and threatening us with the law, etc., he knew not how near his time then was;
for after that he lived but a short space, if he died in the next Norfolk circuit,
as was reported:
however he lived but a little time after he threatened
us that the law should be master over us.

[.embedded-content-document.letter]
--

[.blurb]
=== George Whitehead and William Crouch`'s Letter to Friends at Norwich prison.

[.salutation]
Dear Friends,

Anthony Alexander, Mary Booth, John Fiddeman, etc., friends in prison in the dungeon,
at Norwich.
After the tender salutation of our dear love to you all in the Lord,
these are to acquaint you of our care and industrious endeavours on your behalf,
since we received your last letters, the one dated the 19th instant,
and the other the 21st, together with the enclosed letter from the attorney,
and the affidavits, court orders, and the county jailer`'s letter to your jailer,
and also sheriff Stebbings`' severe order to him.
In answer to all which, and your desires signified, we return you this following account:
We did yesterday seek for John Hill, to whom the said attorney directed his letter,
but he was out of the city, in the country.

We sought out judge Windham, and in the afternoon had admittance to speak to him.
He was prepossessed with sheriff Stebbings`' account against you and his own vindication,
having rendered you obstinate, riotous, affronting the law in your meetings,
and standing in the street, contrary to proclamation, etc.
But be not discouraged at such injurious reflections.

We told him sheriff Stebbings is your extreme adversary, and party against you.

On the sheriff`'s account he also reflected upon you,
as refusing to give in security for your appearance at sessions,
and refusing to pay for convenient rooms in prison,
and said that you chose a free prison, etc.^
footnote:[So they might, and not choose a dungeon under Guildhall.]
This and more from sheriff Stebbings`' account.
But still we excepted against him as not an indifferent person.

We told him we had affidavits enclosed in a letter from persons indifferent;
upon which he called for the letter to John Hill, and opened it,
and read the court orders and affidavits, which caused some calm,
having before that read the letter dated the 19th of the first month,
which he plucked out of George Whitehead`'s hand,
wherein you give account of sheriff Stebbings being with the judge,
and of his and the jailer`'s being more severe towards you since;
which passages we made improvement of,
to show the sheriff`'s contradiction to what the king, the lord-keeper,
and judge Windham himself had ordered on your behalf.

The judge said, he had delivered sheriff Stebbings`' account to the lord-keeper,
and he gave us back the court order and affidavits,
and said we might do what we would with the affidavits.

We gave account last night to the meeting of our friends,
of our endeavours with the judge,
and your letters and the affidavits were then read in the meeting,
which left the matter to us further to manage and write to you, which herein we do.

This morning we went early to the lord Keeper`'s, obtained admittance to him,
and spoke with him in your case and behalf.
He showed us sheriff Stebbings`' account against you,
we told him what an extreme party and adversary he is against you;
we delivered him the affidavits,
and told him they were from indifferent persons who viewed the jail,
and we desired his tender notice of them, and to give report to the king accordingly.
He received them, and promised he would deliver them to the king.

Lastly, we having thus far endeavoured and laboured for you,
and vindicated your cause much more than we can here express;
to what you propose of drawing up your case to the king, we think it very fitting,
that if you be still continued under the same hardship,
you briefly draw up your complaint by way of humble petition, or request to the king,
showing your hard usage in the most material points;
for we have lately found that some are apt to reject compliments at the council-board,
unless the words +++[+++humble petition]
be in the front.

Thus dear friends, having given you these brief notes of our endeavours,
being but as a short index thereof, we hope that further endeavours will not be lacking,
as the Lord shall open our way.

[.signed-section-signature]
George Whitehead, William Crouch.

--

Our labour and solicitation for our oppressed friends at Norwich,
held a considerable time,
and their suffering was prolonged by their persecutor Stebbings, the then sheriff,
of whose cruelty their chief complaints were; to excuse and palliate which,
his endeavours were to render the sufferers criminal and as obnoxious as he could,
aspersing them as obstinate, riotous, etc.,
thereby to incense the magistrates and government against them.
This gave us occasion to be the more zealously concerned
to discover to his and our superiors,
his unwarrantable and inhuman actions and proceedings against the poor,
harmless sufferers;
and further to make application to the king in the sufferers`' behalf.
Wherein my ancient friend Gilbert Latey, was willing and free to be concerned with me;
and accordingly we waited an opportunity to go to the king at Hampton-Court,
when he was to come there from Windsor.

On the 25th of the second month, 1683, we took boat for Kingston, in the afternoon,
but before we got to Wansworth,
the weather began to be so very stormy and tempestuous upon the river Thames,
that we were forced to take in at Wansworth,
and lodge there that night at the widow Springet`'s.
Next morning we rose by that time it was well light,
and walked on foot to Kingston, it raining almost all the way,
so that we were much wetted in going there.
We made some stop at Anne Fielders, at Kingston,
till we had a little refreshed ourselves, and dried our clothes at the fire,
and then we hastened away to Hampton-Court,
to meet with the king before he went to council.

As we went along the park toward the court,
we saw at a distance several persons standing in the porch looking towards us,
and I observed one above the rest; believing it was the king,
by his blue riband and black cap, I said to Gilbert Latey,
"`I am persuaded yonder is the king;`" and as we drew nearer,
I saw it was the king indeed.
And not being willing to go abruptly into his presence,
to open our case to him without his leave, at a little distance I called to the king,
desiring him to favour us a few words, which he presently granting,
one of his gentlemen who knew us, came to us, and gently took off our hats,
and hung them on the pales of a fence before the court, and then we went to the king,
who was ready to hear us.

Several great persons being present with the king, at the gate or porch,
I proceeded to open our case to him concerning the continuance
of the hard suffering of our friends in Norwich,
in manner following:

[.numbered-group]
====

[.numbered]
_First,_ I reminded the king that our poor friends in Norwich,
were still continued under great duress or hardships in jail, in holes,
and a dungeon under ground, and desired that the king in his clemency,
would please to relieve them, further opening their distressed case, etc.

[.discourse-part]
_The king answered:_ It is against law they suffer so, and I will take care concerning them.

[.small-break]
'''

I was truly glad when I heard him give this answer,
believing that the complaints which had been made
to him of our friends`' hard usage and confinements,
and the said affidavits of others thereof,
had such credit and weight with him that I hoped he would cause them to be released.

[.numbered]
_Secondly,_ the king questioned us about the reason of our not putting off our hats,
and using the terms, thee and thou, yea and nay?
To which we gave him answer, particularly Gilbert Latey:
That if we could put off our hats to any mortal, it should be to the king first,
but for conscience sake we could not to any mortal,
but only in our approaching God in prayer; to which the king gave no particular reply.

====

[.discourse-part]
_George Whitehead:_ Thou and thee to one person,
is Scripture language and the true way of speaking.

[.discourse-part]
_Gilbert Latey:_ As Paul did to King Agrippa, Acts 26:2 i.e.: I think myself happy,
O King Agrippa, because I shall answer for myself this day before thee;
touching all the things whereof I am accused of the Jews;
especially because I know thee to be expert in all customs and questions,
which are among the Jews, etc.

[.discourse-part]
_George Whitehead:_--__Thirdly,__ concerning yea and nay,
we are not strictly tied to the expressions,
but sometimes use those of the same signification; as yes and no, etc.

[.discourse-part]
_A great person present asked us:_ Why do you call him king?
Why do you not call him his majesty?

[.discourse-part]
_George Whitehead:_--As he is king, he has majesty belonging to him, it is included:
his majesty is his greatness and power.

[.discourse-part]
_King:_--You should not stand upon things in affectation; the word you,
is now become usual in English; and the word yeah,
is used by seamen when they call from the top of the mast, to be heard upon the deck;
it is also a Dutch word, who express it yah.

[.discourse-part]
_George Whitehead:_--We affect not singularity in words, or behaviour,
but desire to demean ourselves in that plainness and simplicity,
which we are in conscience and truth persuaded unto.

[.discourse-part]
_King:_ The words thee and thou, might have been better translated out of the Greek, you.

[.discourse-part]
_George Whitehead:_ If so, then the translators were as simple as we the Quakers.

[.discourse-part]
_King:_ Many of your friends can swear, or take an oath,
rather than loose their voices in election.

[.discourse-part]
_George Whitehead:_ Though some few persons have sworn,
who have sometimes gone under our profession, yet they are not in society with us,
or we with them.

[.discourse-part]
_Gilbert Latey:_ We are as much dissatisfied with such as have so done, as the king can be.

[.discourse-part]
_George Whitehead:_ We desire nothing to be done to the prejudice or dishonour of the king,
nor to join with, or promote any interest against the king.
The Lord knows our hearts,
we have not the least design or desire for the subversion or change of the government.
Nor can we reasonably be supposed to have any such design,
seeing we were deep sufferers in Cromwell`'s time, as I myself was;
therefore there is no reason we should seek to promote any interest against the king,
but only desire, that God in his wisdom may direct and preserve the king,
and that nothing may be done or permitted that may be to the king`'s dishonour or hurt.

[.discourse-part]
_Gilbert Latey:_ We would not loose our point that we came to the king for; that is,
the case of our distressed friends in Norwich,
to whom we desire the king to show his princely clemency for their relief.

[.small-break]
'''

Although it was my friend`'s care we should not be
diverted from our point by other discourse,
I was as mindful of that as he could be; but by the way,
I was willing to clear our innocency from jealousies and prejudice
wrongfully suggested to the king against us and our friends.

[.offset]
In answer to Gilbert Latey.

[.discourse-part]
_King:_ I will take notice of their case, and care about it,
that it shall be called for in council.

[.discourse-part]
_George Whitehead:_ If there be any objections against us, i. e., in council,
we pray the king to let us know them,
and we hope to give such answers as shall be satisfactory.

[.small-break]
'''

The reason of this proposal by George Whitehead was, that we were informed the secretary,
sir L. Jenkins, intended to produce an apology from the sheriffs of Norwich,
against the affidavits concerning the jail and dungeon wherein our friends were confined,
whereupon we attended the council that day, in order to be called in before them,
or to hear the result thereof, in our case, respecting our said suffering friends,
but we were not called in, nor did we hear of any such apology produced by the secretary,
though he was a favourer of our adversary, sheriff Stebbings.
It may be supposed, that the king`'s favourable answers to us,
and his confessing that their suffering was against law,
and promising to take care concerning them,
might anticipate and prevent producing any apology against them or their case.

[.offset]
To George Whitehead`'s last proposal before.

[.discourse-part]
_King:_ You shall know I will take care about your business.

[.discourse-part]
_George Whitehead:_ We gave affidavits to the Lord Keeper,
which we hope were delivered to the king.

[.discourse-part]
_King:_ Yes, yes, I will take notice of their case, and it shall be called on in council.

[.discourse-part]
_Gilbert Latey:_ We accept it as a great favour, that we have this admittance to be heard,
and pray God to preserve and direct the king.

[.discourse-part]
_George Whitehead to the rest of the nobility present, etc.;_
And we acknowledge all your civilities and kindness towards us.

[.discourse-part]
_George Whitehead to the king, as he was withdrawing:_
We hope the king will be mindful of our suffering friends in Norwich.

Yet after so great endeavours and long solicitation,
our suffering friends in Norwich were continued prisoners
until the next court session that summer,
and then were released, pursuant to the king`'s promise and instruction,
as it was concluded,
to the great comfort and relief of them and their afflicted families.

Although, with God`'s assistance,
we prevailed with the king for relief in certain extreme
cases of suffering through great labour and solicitation,
wherein I was much concerned, in great compassion toward our sorely oppressed friends,
yet hitherto there remained great oppression and sufferings
throughout most counties and cities in England,
by various kinds of severe prosecutions; insomuch that several of us, namely, George Fox,
Gilbert Latey, Alexander Parker, Francis Camfield, myself, etc.,
were weightily concerned to have a general statement
of our suffering friends`' case and condition,
drawn up by way of address or application, to be presented to the king,
in order to make him the more sensible of the great oppressions
and persecutions we still were exposed to.
Accordingly I took particular care to have such an
application effectually drawn to Friends`' satisfaction.

The intent whereof was,
to clear our innocency from a plot that was reported
to have been against the king and the duke of York.

To make the king sensible of our long continued,
as well as extreme sufferings for our religious, tender consciences towards Almighty God;
and Earnestly to move the king for our relief: a copy whereof follows:

[.embedded-content-document.address]
--

[.letter-heading]
To the King.

[.blurb]
=== The humble address of the people commonly called Quakers.

O king, The King of kings,
and Lord of the whole earth incline your heart to
do that which is just and merciful in his sight,
and to make such clear and equal distinctions, as that the innocent may not suffer,
in any case, for the guilty, that it may ever redound to your honour and safety,
and your peaceable subjects`' comfort.

Our innocency,
love and good will to your person and the government that God has committed to you,
encourage us, in this our humble address and application.

Whereas the late plot against the king, and his brother the Duke of York,
is made an occasion to persecute many of us for our
religious meetings more severely than formerly;
We do solemnly declare, that it is known to the divine Majesty and the all-seeing Wisdom,
whereby kings reign and princes decree justice, that our manifold,
extreme and continued sufferings, being only on a religious account,
have not been the least motive or provocation to us, to desire,
much less to contrive the least hurt either to your person or government,
or to the person of your brother the Duke of York.
We are clear in the sight of God, angels and men,
from all hellish plots and traitorous conspiracies,
and from all murderous designs and undertakings against the king, his brother,
or any person on earth whatsoever, being works of the devil and darkness;
having contrariwise learned of Christ Jesus our Lord,
by his light and grace in our hearts, not so much as by force to defend,
much less avenge, ourselves from injuries done us,
but to commit our cause to Him that judges righteously,
as peaceable followers of our Saviour and Redeemer,
in his patient example and sufferings, who is the Prince of peace.

O king, we do further declare,
that God Almighty has taught and engaged us to acknowledge and actually to obey magistracy,
as his ordinance, in all things not repugnant to his law and light in our consciences,
which is certainly agreeable to the holy Scriptures,
and admits not of any immoral or injurious action.
And that even where through tenderness of conscience we cannot conform,
it is our duty patiently to suffer, and not to rebel or seek revenge.
We hope by his divine grace, ever to demean ourselves as peaceable minded Christians,
in our conduct under the civil government.
As we do sincerely,
and with reverence confess to his divine power and providence in your restoration,
and the preservation of your person hitherto,
so our prayers and supplications are to the Almighty for your future safety and peace,
and that in a thankful remembrance of God`'s great mercies towards you,
you may be thereby obliged to show mercy,
and to relieve the oppressed from these unmerited afflictions and persecutions,
which a great number of us your peaceable subjects, do even at this day suffer under,
in our persons and estates, not only by laws made against,
but also by laws never intended against us.
And what is more extreme, many severities of late have been,
and still are inflicted on us,
for which no colour or pretence of law has been or can be alledged,
several jails being so filled that they lack air,
and many innocent persons are held under extreme distress, without regard to age, sex,
or condition, to the loss of some lives already, and the apparent hazard of many more,
if not to the endangering of infection in various cities and places in this nation.
Many houses, shops, barns and fields, are ransacked and swept of goods, corn and cattle,
tending also to the great discouragement of trade and husbandry,
and to the impoverishing of a great number of quiet and industrious people;
and that for no other cause, but for their religious worship,
and the exercise of their tender consciences towards Almighty God, who made them,
who is the sovereign Lord of all, and king in men`'s consciences.

Therefore we humbly entreat you, O king, in princely justice,
Christian charity and compassion, to open our prison doors, and take off our bonds;
relieve the innocent and oppressed in your land,
who fear God and in conduct truly honour the king.
Permit not the ruin of such as are quiet in the land, nor the widow and the fatherless,
for their peaceable consciences,
to lie at the door of a prince professing the tender and compassionate religion of Christ.

--

This address was presented to king Charles the second, and by him accepted,
at Windsor castle, the 8th day of the sixth month, called August, 1683,
by George Whitehead, Alexander Parker, Gilbert Latey, and Francis Camfield,
and read distinctly to the king and the duke,
in the presence of many more of the nobility, etc., by me.

After I had read it to the king,
our ancient friend Francis Camfield declared a few words, very weightily,
reminding him of the mercy of the great God to him, both in his great deliverances,
preservation, and restoration;
desiring that as the Almighty had shown mercy and compassion to him,
in his afflictions and straits,
he would show mercy and compassion to his afflicted people; or words to the same effect,
so near as I well remember, and withal prayed for the king,
according to our supplications hinted in the foregoing application, to which he said,
'`I thank you.`'

The king at that time appeared seriously affected with our complaint and sufferings,
and soon after we were told by a great person, that he said to a duke that stood by,
What shall we do for this people?
The prisons are filled with them.
And that the duke to divert him from his concern therein, drew him into other discourse.

I have been bowed in spirit under a great weight and concern,
with earnest breathing and secret supplication to the Lord to assist me,
so often as I have had occasion personally to appear before the king,
to make application or request to him on behalf of my suffering friends and brethren,
and my exercise was the greater when it was difficult to obtain access to,
or to meet with him, which I have many times very earnestly laboured for;
and also to be admitted to appear before him and his council, to plead their cause.
And the Lord our God has made way for me therein, and by his power assisted me,
in freely and boldly pleading the cause of the innocent, for truth and justice,
without being any ways timorous or daunted by the face of king, princes, or nobles;
and in these services, when the Lord has helped me through them,
I have felt great peace and comfort, and his presence with me,
enabling me to speak pertinently, and influencing them to hear attentively:
praised be the Lord my God.

On or about the 8th of the first month, called March, 1682-3,
by warrant made by sir John Moor, then lord mayor of London,
bearing date September the 10th, 1682, to levy the sum of twenty pounds,
on pretence that George Whitehead had preached or taught in a religious meeting or conventicle,
the 13th of August, 1682, in Allhallows, Lombard street, London;
the said George Whitehead had goods of grocery ware
in his shop seized and carried away by James Holsworth,
druggist, in Tower street, constable, and others, to the value of fourteen pounds,
six shillings and ten pence,
according to the best estimate the owners and others present could make.

Also on the 5th of the fourth month, called June, 1683,
by warrant from sir William Pritchard, then lord mayor,
bearing date the 10th of the twelfth month, called February, 1682-3,
to levy twenty pounds more on the said George Whitehead.
The said Holsworth,
with some others came and took again from him goods to the value of twenty-six pounds,
as the owners supposed, not permitting either inventory to be taken,
or the goods to be weighed or appraised; upon the like pretence,
that the said George Whitehead did take upon him
to teach in another religious meeting or conventicle,
held the 23rd of July, 1682, at the Savoy, in the Strand,
on a conviction made and certified by sir Clement Arminger,
on the information of John Plilton and Gabriel Shadd, informers:
and the said goods were never restored to the owner,
nor any part of the money levied upon them;
for Holsworth said that he must be forced to levy fourteen
pounds more to complete the fines of both warrants.

Henry Driver of Hounsditch, saw the carting and carrying away of these two distraints.

On the 13th of the seventh month, 1683, John Manby of Broad street, constable,
with William Humphreys of the same, John Elliot, tailor, in Scalding alley,
and one Gardiner, razor grinder, near the Exchange,
came with violence and fury and broke open the shop back door, and several doors above,
belonging to the chambers of the said George Whitehead, and seized beds and bedding,
not leaving him a bed to lie upon, all moderately valued, worth twenty one pounds,
ten shillings.
Then they seized linen with an escritoire, six cane bottomed chairs, and others,
and a large looking glass, value five pounds, eighteen shillings.
Then they seized shop goods, currants and sugar, value five pounds, twelve shillings,
all moderately valued by the owners amounting to thirty-three pounds.
Though the goods so seized were not permitted to be inventoried, weighed, or appraised,
before they were carried away;
the constable pretending this seizure was for a fine of forty pounds,
by warrant from sir James Smith, dated the 7th of the seventh month, aforesaid,
grounded on a certificate from the said sir Clement Arminger,
for a meeting the 19th of August, 1683, in Margaret`'s parish, Westminster.

Two of George Whitehead`'s friends, namely, John Edge and Joseph Peckover,
fairly endeavouring to persuade the constables to more moderation,
and to allow an inventory of the goods, before being taken away,
were apprehended by the said Manby, at the same time,
and on his prosecution and for no other cause, he swearing a riot against them,
they were committed to Newgate, and there continued, for above ten weeks,
to their own and their families great injury and damage;
the said Joseph being a Norfolk man, was near eighty miles from home.

Manby sold the goods so seized, as aforesaid,
to a person who redeemed them for only fifteen pounds, as appeared by his own receipt;
but paid in to sir James Smith, only eleven pounds nine shillings and six pence,
which he, the said sir James, paid into the court of sessions, as appears by the record,
on George Whitehead`'s desiring his plea upon his appeal, to be accepted in court,
which upon trial he gained; and had restitution only of the said eleven pounds,
nine shillings and six pence,
Manby keeping back three pounds ten shillings and six pence, of the said fifteen pounds,
which he refused to restore to the owner, to whom of right it belonged.

George Whitehead made two appeals, the one against this last conviction,
and the other against a conviction made by sir Thomas Jenner, then recorder of London,
for a fine of twenty pounds, and was discharged upon trial of both appeals:
the charge of prosecuting both,
amounted to seventeen pounds nine shillings and eight pence.
So that the loss to him in all, as it was computed, amounted to sixty-one pounds,
seven shillings, besides the damage done to his house and goods.

Some further notice may be taken hereafter of the said recorder,
Thomas Jenner`'s conviction and proceedings against the said George Whitehead.

I humbly thank the Lord my heavenly Father, and praise his worthy name,
in remembrance how he enabled me to be resigned to his will,
in suffering both in person and estate,
and how well my dear wife was given up to suffer with me, for the blessed truth`'s sake,
in those days: but the Lord our God supported and comforted us under those trials;
as we were with one accord resigned to his will,
to bear a faithful testimony for his holy name and ever-living truth,
of which he had made us partakers and witnesses.
Blessed be his glorious name forevermore.

Our being shut out of our meetinghouses for several years,
in and about the cities of London and Westminster,
and our meetings kept in the streets in all sorts of weather, winter and summer,
was a trial and hardship upon us, even upon old and young, men and women.
But that trial was not so great as to have our estates and
livelihoods exposed to ruin by a pack of ravenous informers;
although it was no small hardship to our persons, to be kept out of doors in the streets,
in the severe and long frost and snow, in the year 1683, for about three months together,
when the river Thames was so frozen up that horses,
coaches and carts could pass to and fro upon it,
and a street also be erected and stand over it.

Yet in all that hard season when we were so long kept out in the streets,
in the bitter cold air, I do not remember that I got any harm or injury thereby,
to the impairing my health, although I frequently attended those meetings in the streets;
wherein I took great and serious notice of the merciful
providence of Almighty God towards myself,
and many more of our friends,
who were sharers in the same mercy and preservation in that suffering and exercise;
no thanks to our unmerciful adversaries and persecutors,
but to our heavenly Father be the glory and praise forever.

We had in those days some opportunities,
and were permitted to publish the truth openly in the streets,
and also to make public supplication to God; but more frequently were not permitted,
but pulled away by force, by the trained bands or officers,
and either sent to prison or turned into the meetinghouse,
and there detained under guard until the meeting was ended in the street.
Thus were the ministers and others among us often forcibly interrupted and served,
and scarcely permitted many times to declare two
or three sentences without being haled away;
however, we saw it our duty in the fear of the living God,
to keep our meetings and patiently to wait upon him,
where often we enjoyed his presence to our consolation,
even in our silent attention upon him:
being not called to strive or contest with our adversaries
or their servants whom they employed,
but in faith and patience to bear all,
believing that in due time thereby we should obtain victory.
It was often then before me,
that the Lamb and his faithful followers should have the victory,
which was matter of secret comfort to me many times: glory to his name forever.

In those days I clearly saw that the testimony required of us to bear,
was not so much in words, declaration or ministry,
as to stand our ground in faith and patience,
and to travail in spirit with secret breathing and
earnest supplication unto God to plead our cause;
it being his own cause for which we suffered,
and therefore we patiently committed it to Him that judges righteously.

Many applications and requests having been made to king Charles the second,
in behalf of our suffering friends,
both for those in prison and those who suffered upon
writs and processes out of the exchequer,
etc., for twenty pounds a month and two-thirds of their estates,
for being absent from their parish churches, so called,
and many under sentence of premunire, for not swearing allegiance;
and these sufferings being long continued upon many hundreds of our friends;
under the great weight and burden thereof,
I being at a certain time solitarily walking the street in London, in 1683,
a great power and dread immediately fell upon me, whereby it was shown me,
that within one year`'s time, there would be an alteration in the government;
whereby I understood the king would be taken away within that time;
and being persuaded the discovery was of the Lord,
I intimated the same to my wife after I came home, and told her,
within a year`'s time you will see an alteration in the government.
I hinted something of it to some other friends, as I remember, a little time after;
and so it came to pass; in the year 1684 the king was removed.

Nevertheless, in the same year before his decease,
I and several other friends were still desirous the king should be made
sensible what great sufferings were continued upon our friends,
both by imprisonment and spoil; and our friend William Mead,
and others of us being concerned that the king should be at last acquainted with them,
and moved thereupon, the same was done; and by the king`'s authority,
direction was given to the sheriffs of the counties respectively throughout England,
to return the names and causes of our friends then prisoners;
an account whereof was given to the king and we moved him by way of petition and information,
a general memorandum whereof follows:

The 15th of the eleventh month, 1683,
George Whitehead and Alexander Parker attended the king,
to present the general suffering of our friends, both in prison and out of prison,
by way of petition.
About the third hour in the afternoon we met with the king in the long gallery,
and presented the petition, which he received,
and George Whitehead spoke a few words to him to this effect:

"`We entreat the king to excuse our importunity, for our extremity is the cause thereof.
We pray the king tenderly to consider our suffering condition, and to afford us relief,
accounts being returned from the sheriffs of our friends in prison, etc.`"

To which he answered.
"`Well, well, well.`"

And perceiving the king then in some haste, George Whitehead told him, If he pleased,
we would acquaint the Lord Sunderland, being secretary of state,
more fully with our case, that he might inform the king thereof, etc.

To which the king answered, "`Do, do.`"

After that, notice was given us from some persons,
observing how the king then resented our case--that
the king said something must be done in this case;
that he read our paper,
and that the king and the Duke of Ormond were discoursing about the Quakers;
and that he then sent for the Earl of Sunderland.

But alas!
The king`'s time was but short; he was then near his end, and did not live to relieve us,
either by opening the prison doors or removing the great
oppressions and severe persecutions we then suffered,
and which he left us under, his opportunity being slipped and day over and gone.

I think I was the last Friend that spoke to the king,
to move him for relief from our sufferings, as before hinted,
but a few weeks before his end.
He left, I think, about fifteen-hundred of our friends, both men and women,
in prisons and prisoners;
besides their being then eagerly followed and persecuted by wicked informers,
and many hundreds under heavy oppression and sufferings, for twenty pounds per month,
and two-thirds of their estates seized,
and great spoil made upon them in many counties and parts of the nation.
We were still kept out of our meetinghouses in the streets, both in and about London,
and various other places;
which persecutions and sufferings were continued upon us
for some time after king James the second came to the throne,
and until he was prevailed upon to afford us some relief and liberty.
All which,
we have cause to ascribe principally to the over-ruling
power and providence of Almighty God,
in whose hands the hearts of kings and princes are, and he can turn them like waters.
To him be the dominion and praise of all forever.

[.embedded-content-document.legal]
--

[.blurb]
=== A copy of a conviction filed by the Recorder of London against George Whitehead.

[.signed-section-context-open]
London, ss.
memorandum.

That the one and twentieth day of October,
in the five and thirtieth year of the reign of our lord, Charles the second,
late king of England, etc., above twenty persons, being subjects of this realm,
and above sixteen years of age, were met in a conventicle or congregation,
under colour or pretence of an exercise of religion in other manner
than according to the liturgy or practice of the church of England,
in a house near the Bull and Mouth, situate in the liberty of St. Martin`'s le Grand,
in the aforesaid city of London, where no family was,
and then and there George Whitebread, of the parish in the city of London, aforesaid,
grocer,
took upon himself to preach and teach to the conventicle and congregation aforesaid,
contrary to the form of the statute in that case made and provided,
as sufficiently appears to me, by the oath of two witnesses, namely, John Sharpless,
of the parish of St. Martin`'s in the Fields, in the county of Middlesex, mason,
and Peter Burdet, of the parish of St. Bridget, alias St.

Brides, London, weaver; whereby the aforesaid George Whitebread, by this my record,
stands convicted, and has forfeited, and moreover,
upon the aforesaid George Whitebread I have imposed a fine of twenty pounds,
for his first offence before me convict, by the tenor of these presents,
in testimony whereof, I Thomas Jenner, knight, recorder of the city of London,
and one of the justices of our said lord the king,
assigned to keep the peace for the city aforesaid, have to this record,
put my hand and seal, the five and twentieth day of October, in the year abovesaid.

[.signed-section-signature]
Thomas Jenner, Recorder.

--

[.offset]
Remarks on the foregoing conviction.

That no conviction is entered against the appellant, George Whitehead,
though in pursuance of a pretended conviction, yet a warrant, dated the 17th of February,
1684, was brought against him, to break open and enter his house for seizure;
whereupon he was constrained to enter an appeal for,

[.numbered-group]
====

[.numbered]
_First;_ The conviction pretended against him, is against one George Whitebread,
four times so named therein, for an unlawful assembly or conventicle,
said to be held the 21st day of October,
in the five and thirtieth year of the reign of our lord Charles the second, late king, etc.

[.numbered]
_Secondly;_ That a record of the said conviction against Whitebread,
was the fourteenth day of January, in the five and thirtieth year of Charles the second,
late king, by Thomas Jenner, knight, under his hand and seal,
according to an act of Parliament,
in the same case and by his own proper hand delivered and certified in court,
at the general quarter sessions of the peace, held for the city of London, etc.,
as is declared in the said record,
which was above a year before seizure was attempted
upon the said George Whitehead`'s goods;
whereas, according to the act of Parliament,
the record of conviction is to be certified into the next quarter sessions,
after seizure, or after the penalty is paid or levied.

[.numbered]
_Thirdly;_ The conviction is for a conventicle said to be held in a house in St,
Martin`'s le Grand, where no family was.
But in the warrant for distress, it is said,
it was held in a house in the parish of St. Martin`'s le Grand,
where there were more than twenty persons,
besides those of the family where the said conventicle was held.
These are contradictory.

====

Great notice was taken in and about the city of London, what an eminent friend to,
and encourager of, the informers, the said Thomas Jenner, recorder of London,
was in those days.

William Luffe and other constables, came to make distress,
the 13th of the first month called March, 1684-5,
The seizure was respited until the 23rd of March ibid.,
and then the twenty pounds fine deposited to the recorder,
upon an appeal made by the said George Whitehead.

Thus it may appear how industrious the recorder was to serve the informers,
and to ruin us; seeing he could authorize officers in several counties,
to break open and enter our houses, to seize, levy and take away our goods and chattels;
whereby he showed what his will and intents were against me and my friends,
though at that time frustrated by my appealing from his conviction to the quarter session,
where, upon traverse and trial my appeal was gained,
though through a considerable charge; which I was the more willing to undergo,
not only upon my own account,
but also for the sake of many others of our suffering friends,
under the like prosecution, by those informers,
that they might not always make havoc upon us,
but be frustrated of their destructive designs,
if we could find and obtain so much justice upon
our appealing from our most notorious persecutors,
and favourers of those devouring informers.

[.asterism]
'''

[.embedded-content-document.legal]
--

[.blurb]
=== A statement of the case of the prisoners called Quakers, indicted at common law, for being routously and unlawfully assembled, with force and arms.

[.discourse-part]
_Proposition._--That their assemblies are not routous or riotous, nor with force and arms,
nor seditious; consequently not unlawful.
On the legal and true definition of riots, routs, etc.

[.numbered-group]
====

[.numbered]
_First;_ What a rout and riot is, defined by the Lord Coke,
Instit, part 3, cap, 79, fol. 176:
_Riotum_ comes from the French word _Rioter,_
and in the law signifies when three or more do any unlawful act, as to beat any man,
or hunt in his park, chase or warren,
or to enter or take possession of another man`'s land,
or to cut or destroy his corn or grass, or other profit, etc.

_Routa_ is derived of the French word _Rout,_
and properly in law signifies when three or more do any
unlawful act for their own or the common quarrel, etc.
As when commoners break down hedges or pales, or cast down ditches, or inhabitants,
for a way claimed by them, or the like.

Observe also William Lambard`'s [.book-title]#Eirenarchia,# lib. 2, p. 175, under the title.
Riots: An unlawful assembly is of the company of three or more persons,
disorderly coming together forcibly to commit an unlawful act, as to beat a man,
or to enter upon his possession, or such like,
+++[+++i.e. any injurious force or violence moved against the person of another, his goods,
lands or possessions, whether it be by threatening words,
or by furious gesture or force of body, or any other force used in _terrorem populi,_
as Mic. Dalton says, of the breach of the peace, fol, 7, The like of riots, routs,
and unlawful assemblies, consisting of three or more persons.]

A rout, says William Lambard, is a disordered assembly of three or more persons,
moving forward to commit by force, an unlawful act:
for it is a rout whether they put their purpose in full execution or no,
if so be that they go, ride, or move forward after the first meeting.

A riot is where three or more persons be disorderly assembled,
to commit with force any such unlawful act; and do accordingly execute the same.

And thus upon the whole reckoning an unlawful assembly is the first degree or beginning:
a rout the next step or proceeding:
and a riot the full effect and consummation of such a disorderly and forbidden action.

Two special things there are that are common,
and must concur both in the unlawful assembly, rout and riot: the one,
that three persons at least be gathered together; the other,
that their being together do breed some apparent disturbance of the peace,
either by signification of speech, show of armour, turbulent gesture,
or actual and express violence, etc.

[.offset]
Pray observe in case of a rout:

Suppose a company of rude persons met to contrive
some mischief or injury against the persons,
goods, or possessions of their neighbours, and moving forward with clubs,
or any offensive weapons, to commit the riot designed,
and these should be apprehended in their motion before the fact be committed,
and then indicted for a rout and unlawful assembly, etc.
The question is, whether the indictment framed against these,
be not in the same manner and form,
or of the same kind that these indictments are against us,
for our religious meetings to pray to God, etc.
What book case, or precedent in common law or equity,
can parallel or warrant the last?^
// lint-disable invalid-characters
footnote:[  page 28.
King Charles the first, in his prayer to God, says:
Make them at length seriously to consider, that nothing violent or injurious,
can be religious.
Therefore in routs, riots, and unlawful assemblies, as defined in common law,
religion is wholly set aside.]

[.discourse-part]
_Observe._
The meetings for which we stand indicted are religious and peaceable,
therefore we conceive they are not such as in common law or reason, can be deemed routs,
riots, and unlawful assemblies.

[.numbered]
_Secondly;_ Not routous or riotous, by the conventicle act, 22 Car. 2, because:
Four persons besides the respective family, may meet and exercise religion,
whereas three persons make a rout or riot,
if met with intention forcibly or violently to do an unlawful act,
or do it to the injury of the person or property of another.

The Parliament in making the said conventicle act,
would not have permitted four besides the family to meet in pretence of religious exercise,
if they had judged them routous or riotous in fact, or such in their own nature:
it is not only the circumstance of number, but the injurious fact which makes a rout,
riot, etc.

Besides, praying to and praising God are not assigned as matters
of fact incurring the penalty of twenty pounds,
awarded for preaching and teaching in such conventicle as therein described.
If praying to or praising God come under the pretence of exercise of religion,
for which five shillings or ten shillings is the fine;
praying is not mentioned in the clause relating to preaching and teaching.

[.numbered]
_Thirdly;_ Seeing the indictment is upon common law, what book case or precedent,
can make our religious meetings routs or riots, they being really for worship to God,
and to pray to and praise him according to our faith and persuasion?

There being various meetings for sports and pastimes, etc.,
which in common law are not routs or riots, but judged lawful,
because not deemed _malum in se;_ query.
What reason then,
that the said peaceable religious meetings should be judged routous or riotous,
seeing they, or any religious exercise in them, cannot be proved _malum in se,_
or evil in their own nature.

[.numbered]
_Fourthly;_ There is a noted book case and precedent, namely, that of Bushel,
in the twenty-second year of the king, reported by the learned sir John Vaughan,
in his book of reports, which begins at fol.
135, and continues to 150. The case was this: Bushel and others of a jury,
having not found Penn and Mead, two persons called Quakers, guilty of a trespass,
contempt, unlawful assembly, rout and tumult, etc., whereof they stood indicted,
were fined forty marks a man, and committed till payment.
Bushel brings his _Habeas Corpus,_
and upon the return it appeared he was committed for that,
contrary to law and against full and clear evidence openly given in court,
and against the directions of the court in matter of law,
they had acquitted William Penn and William Mead,^
footnote:[Note,
that the aforesaid William Penn and William Mead were taken at a religious meeting;
for which they were indicted for being at an unlawful assembly,
routously, riotously, etc.]
to the great obstruction of justice, etc., which, upon solemn argument,
was by the judges resolved to be an insufficient cause of fining and committing them:
and they were discharged, and afterwards brought actions for their damage.

The reasons of which judgment are reported by the said judge Vaughan,
one whereof was this, fol.
140: One fault in the return is,
that the jurors are not said to have acquitted the persons indicted,
against full and manifest evidence corruptly,
and knowing the said evidence to be full and manifest against the persons indicted.
For how manifest soever the evidence was, if it were not manifest to them,
and that they believed it such, it was not a fineable fault, nor deserving imprisonment.

In the margin of fol.
142, it is thus noted; Of this mind were ten judges of eleven:
the chief baron Turner gave no opinion, because not at the argument.

And in the same, fol.
142, he says: The verdict of a jury, and evidence of a witness,
are very different things in the truth and falsehood of them.
A witness swears but to what he has heard or seen generally,
or more largely to what has fallen under his senses;
but a juryman swears to what he can infer and conclude from the testimony of such witnesses,
by the act and force of his understanding, to be the fact inquired after:
which differs nothing in reason, though much in punishment,
from what a judge out of various cases considered by him,
infers to be the law in the question before him.

[.numbered]
_Fifthly;_ Of the credit, good reputation and fame of the witnesses,
to render them good and lawful men, and responsible, etc.,
which the defendants do question concerning some of them, if informers,
for such witnesses as law and justice assign, are no parties, nor interested persons,
but such as the law renders credible, as sir John Fortescue, lord chancellor of England,
in the reign of king Henry the sixth describes them: Not unknown witnesses,
hired persons, poor men, vagabonds, unconstant people,
or such whose condition and naughtiness is unknown; but such as are neighbours,
able to live of their own, of good name and fame, of honest report, etc.
It is by the evidence of such witnesses, that jurors ought to be informed.
_Vid. Fortes, de Laud. Leg. Angl. Cap._ 26, p. 60, 61, cap. 28, p. 63, 64.

Observe further what sir John Fortescue says in this case, in his said book,
in commendation of the laws of England, chap. 28.

Verily, no man can be safe in body or goods,
when his adversary may convince in every case,
with two unknown witnesses of his own choosing and bringing forth, etc.
But such mischief and inconvenience cannot be wrought by witnesses that
make their depositions in the presence of twelve credible men,
who also know the manners and conditions of the same witnesses,
especially if they be nigh dwellers,
and know also whether they be men worthy to be credited or no.

[.numbered]
_Sixthly:_ We do really, and in humility conceive, that our religious assemblies,
and the manner thereof, as well as what we pretend, profess or practice therein,
are warranted and justified by the liturgy of the church of England,
in these following instances:

[.alt.centered]
==== For a meeting of a hundred and twenty persons.

In those days Peter stood up in the midst of the disciples, etc.
The number of the names that were together, were about one hundred and twenty:
to which add, In an upper room, verse 13.
Where they continued with one accord in prayer and supplication, verse 14.^
footnote:[Used by the Church of England, on St. Matthias`'s day, Acts 1:15. cited.]

[.alt.centered]
==== For assembling and mutual exhortation.

Let us consider one another, to provoke unto love, and to good works;
not forsaking the assembling of ourselves together, as the manner of some is;
but let us exhort one another, and that so much the more,
because you see the day approaching.^
footnote:[On Good Friday, Epist. Heb. 10:24-25, cited in the liturgy.]

[.alt.centered]
==== For freedom of ministering by the gift received.

As every man has received the gift, even so minister the same one to another,
as good stewards of the manifold grace of God: if any man speak,
let him speak as the oracles of God: if any man minister,
let him do it as of the ability which God gives, that God in all things may be glorified,
through Jesus Christ.^
footnote:[Sunday after Ascension day, Epist. 1 Pet. 4:10, cited.]

[.alt.centered]
==== The Spirit prayed for by the church of England.

Grant us Lord, we beseech you,
the Spirit to think and do always such things as be rightful,
that we who cannot do anything that is good without you,
may by you be enabled to live according to your will etc.^
footnote:[Ninth Sunday after Trinity, collect.]

[.alt.centered]
==== Give thanks at all times, and in all places, etc.

[.discourse-part]
_Priest:_ Let us give thanks unto our Lord God.

[.discourse-part]
_People answer:_ It is fitting and right so to do.

[.discourse-part]
_Priest._
It is very fitting, right, and our bounden duty, that we should at all times,
and in all places, give thanks unto you, O Lord, holy Father,
Almighty and everlasting God--which art one God, etc.: page 198.^
footnote:[Communion.]

[.numbered]
_Seventhly;_ If the indicted persons aforesaid, be by the jury brought in guilty,
and so liable to be sentenced to pay fines, or to imprisonment till payment,
and suppose they cannot for conscience sake pay the fines,
it being for their religiously meeting to worship God, or to pray to God,
the question is,
whether such imprisonment may not occasion the death of some of the said prisoners?
And whether this in common law, common justice, equity, or reason,
can be esteemed a punishment suitable to the supposed offence;
or whether such peaceable meeting and religious exercise can be justly
judged to demerit such severity in a Christian and Protestant nation.

====

We commit our case to Almighty God, the judge of all,
and to be conscientiously considered by you who are in authority.

--

On the 27th day of the 6th month, called August, 1684, being the fourth-day of the week,
the said George Whitehead being at the meeting of the people of God called Quakers,
at Whitehart court, near Lombard street, London, and near the conclusion of the meeting,
being upon his knees in prayer to Almighty God, John Levens a constable,
came in an angry, turbulent manner, and apprehended him,
commanding him in the king`'s name to go along with him, pretending he had a warrant,
but showed none, though several times desired.
The constable carried George Whitehead before the lord mayor,
and there the wife of one Collingwood, an informer, appeared as prosecutor,
and urged to have the said George Whitehead fined for a conventicle and preacher.
Whereupon he told the mayor and others present, thus:
This woman dictates to the lord mayor, which is not her place to do, or to direct him,
or any justice of peace, what law to proceed upon.
The lord mayor then told her,
it was at his discretion to choose what law to proceed upon,
and then asking George Whitehead if he had sureties for his appearance at the next sessions,
he answered, No, I have none.
Collingwood`'s wife being somewhat urgent and troublesome,
the lord mayor asked her if she would take her oath that George Whitehead was preaching;
she answered, that he was either preaching or praying.
George Whitehead replied, that her evidence was uncertain and doubtful,
it is an ignoramus evidence, she knows not whether it was preaching or praying,
therefore not sufficient for conviction.
Then the mayor asked George Whitehead himself if he did not preach?
He answered.
No, not at that time, I was only praying.
And the constable declared that he took him at prayer.
The mayor asked if it was according to the liturgy of the church of England?
George Whitehead answered, It is warranted and required by the liturgy;
for there is a spiritual worship and praying required in the liturgy.
The mayor asked,
if there was none there that would be bail for his appearance at sessions?
Upon which one of his officers or servants, i. e., one Hern,
voluntarily offered to be George Whitehead`'s bail:
which the mayor accordingly accepted.
And so for that time George Whitehead was dismissed
until the sessions of the peace for the city of London.

[.inline]
=== Proceedings at the sessions at Guildhall, for the city of London, against George Whitehead, the 1st of September, 1684.

Present on the bench, Henry Tulse, knight, lord mayor; Peter Daniel, knight,
and Samuel Dashwood, sheriff`'s; James Smith, knight, alderman; Thomas Jenner,
knight and recorder.

On the 1st of September, 1684, the said George Whitehead,
according to the bail given for his appearance,
attended the court of sessions at Guildhall in the afternoon,
and near evening was called into court.
An indictment for an unlawful assembly, routously and with force and arms,
was read against him.
To which he was required by the recorder to plead:
"`Mr. Whitehead you must plead guilty or not guilty,
in the first place,`" which he promised,
provided his pleading might not debar him from giving
his reasons for his plea in his own defence,
after the witnesses were heard.
The recorder promised he should be heard.
George Whitehead enquired of the court if it was an indictment at common law,
or statute law; but heard no positive answer.
He then pleaded not guilty; the clerk asked him if he would traverse,
or put himself upon trial now?
He answered, I think not to enter traverse, but to put it to a trial now,
and told the court he conceived it was an indictment at common law, being for a rout, etc.
The witness was called; first the little constable that took him; whose evidence was,
that he took George Whitehead at prayer,
in the meetinghouse at Whitehart court in Lombard street.

The recorder asked, "`In what posture did you take him praying?`"

[.discourse-part]
_Constable:_ Upon his knees.

[.offset]
One in court said, "`I thought the Quakers had not kneeled at prayer.`"

[.discourse-part]
_Recorder to George Whitehead:_ What say you to the evidence?
Do you deny it, or not?

[.discourse-part]
_George Whitehead:_ No, I shall not deny that I was taken upon my knees at prayer to God,
but that can be no rout, when I was on my knees at prayer,
this could be no moving forward to commit a riot, etc.

[.discourse-part]
_Recorder:_ But did you do nothing else before prayer?

[.discourse-part]
_George Whitehead:_ No, I did not.

[.discourse-part]
_Recorder:_ Did no body preach?

[.discourse-part]
_George Whitehead:_ Excuse me there, etc.
+++[+++at which question George Whitehead somewhat wondered,
that the recorder should thus endeavour to make him
an informer against our religious meetings.]

[.discourse-part]
_Recorder:_ Call Mrs.
Collingwood.
+++[+++who presently appearing, was sworn.]
What say you Mrs.
Collingwood?
Was there no preaching before George Whitehead prayed?

[.discourse-part]
_Collingwood`'s wife answered:_ Yes, there were two others that preached before he prayed.

[.discourse-part]
_Common Sergeant:_ Preaching and praying are both one--their kind of preaching and praying.

[.discourse-part]
_George Whitehead:_ No; they are not, there is a distinction in common acceptation;
preaching or teaching is done to men, but prayer and supplication is made to God;
men do not preach to God, or teach God, but pray to God.

[.discourse-part]
_Common Sergeant:_ You preach to deceive people.

[.discourse-part]
_George Whitehead:_ That is a reflection; I teach for no such end.

[.discourse-part]
_Recorder:_ Gentlemen of the jury, you hear the evidence,
that there was preaching and praying; it was therefore a conventicle,
an unlawful meeting.

[.discourse-part]
_George Whitehead:_ I am not indictable upon the conventicle act,
there lies no indictment upon it.
The conventicle act allows of four to meet besides the family;
whereas the law allows not three to meet routously.
It is for a rout I am indicted at common law, as I conceive,
though some words of the conventicle act are in the indictment,
that is but an aggravation, the matter is a routous assembly that I am charged with;
wherefore I entreat the court to allow the Lord Coke`'s
definition of a rout to be read in court.
+++[+++George Whitehead calling for Coke`'s Institutes, which one present handed to him,
opened at the place in the third part of Coke`'s Institutes, chap.
79, and fol.
176.]

[.discourse-part]
_Common Sergeant answered:_ My Lord Coke was mistaken, +++[+++but he did not declare wherein,
it was his own ipse dixit, without proof against Chief Justice Coke.]^
footnote:[We may presume Chief Justice Coke was a more eminent
lawyer and author than ever that Common Sergeant was,
though he had the confidence thus to slight judge Coke,
to stop the prisoner from pleading him in his own defence.]

[.discourse-part]
_George Whitehead:_ Pray hear him, hear his definition of a rout and unlawful assembly.

[.discourse-part]
_Common Sergeant:_ I tell you my lord was mistaken.

[.discourse-part]
_George Whitehead:_ Is that the sense of the court?
the Lord Coke and other learned writers agree in the definition.

[.discourse-part]
_Recorder:_ Gentlemen of the jury,
we have heard George Whitehead with a great deal of patience,
he is used to long speaking, you have heard the evidence and what he says.

[.discourse-part]
_George Whitehead:_ Pray hear the Lord Coke in the case.

[.discourse-part]
_Court:_ The king`'s council has done, take him away.

[.small-break]
'''

Upon which George Whitehead was drawn out of court, and after some time he,
with the rest of friends tried before him, were called into court again,
to hear the verdict of the jury, which upon the question,
put severally by the clerk concerning each person,
whether guilty or not guilty of a rout and unlawful assembly?

[.discourse-part]
_The jury answered._
Guilty, to each particular name.

[.small-break]
'''

The prisoners heard not their sentences.
The bench consulted about their several fines privately.
The prisoners had liberty that night to go home,
but the next day returned to the prison of Newgate.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
12th of September, 1684.
Sir Samuel Dashwood`'s, then sheriff, liberate for George Whitehead.

[.letter-heading]
To the keeper, or under keepers of Newgate, London.

Whereas you have in your custody the body of George Whitehead for payment of a fine,
being convicted of being at an unlawful assembly;
these are to desire you to discharge the said George Whitehead from his imprisonment.

And for your so doing this shall be your warrant.
This 12th September, 1684.

[.signed-section-signature]
Samuel Dashwood.

--

I do confess that some of the magistrates of the city of London,
were men of more moderation and compassion towards us than their recorder,
who sought our ruin, not only by imprisonment,
but also by the encouragement given to the informers,
to ruin us in our estates and livelihoods.

[.blurb]
=== George Whitehead`'s plea and defence, relating to his appeal from his conviction by Thomas Jenner the recorder, etc.

That seeing the appellant by the law may plead and make defence,
he humbly offers his defence, viz:

[.numbered-group]
====

[.numbered]
1+++.+++ That the conviction is made against Whitebread, so named therein four times,
and not against Whitehead.

[.numbered]
2+++.+++ That it is for a conventicle in a house near the Bull and Mouth,
situate within the liberty of St. Martin`'s le Grand, London:
in which liberty the Quakers have no meeting,
nor is the Bull and Mouth within that liberty.
Witness, William Cowley and Nathaniel Norris.

[.numbered]
3+++.+++ That seeing he has, as the law directs,
appealed in writing from the person convicting to the judgment
of the justices of the peace in quarter sessions,
to whom it is said, the justice or justices that first convicted,
shall return the money levied, and certify under his and their hands and seals,
the evidence upon which the conviction past.
Wherefore the said appellant humbly requests that
the convicting justice may not sit as judge,
nor determine in the trial of his traverse or appeal.

[.numbered]
4+++.+++ That the long concealment of the conviction,
as well as its being made in the absence of the appellant, appears injurious to him.

[.numbered]
5+++.+++ If the said appellant be the person intended in the record, then his being convicted,
and a judgment and fine of twenty pounds passed on him in his absence,
without so much as any previous notice or summons given him thereof;
he conceives such kind of procedure to be expressly
contrary to the law of God Duet. 19:17-18, and chap. 1:16, 17,
and John 7:51;--to the common justice and law of the ancient Romans and other nations;
to equity and right, due order of law, and common course of justice;
and to ancient English laws and statutes, in the reign of king Edward the third, etc.,
requiring that none be condemned to suffer in person or estate,
without being brought in to answer by due process and order of law, 25 Edward, 3, c. 4,
and 28 Edward, 3, c. 3. And to the great charter of England, 9 Henry, 3, c. 29.

Consequently such concealed conviction is not consistent with the oath of justices,
and therefore ought to be void, and held for none.
For as the Lord Chief Justice Coke says,
How can they be indifferent who have declared their opinions beforehand,
when a small addition or subtraction may alter the case?
And how does it stand with their oaths,
who are sworn that they shall well and lawfully serve our lord the king and his people,
in the office of a justice, and do equal law and execution of right to all his subjects,
vid.
Coke`'s Inst, part III.
fol. 29.

[.numbered]
6+++.+++ What credit the witnesses are of is to be inquired;
whether they have not assumed the place of informers for their own profit,
or whether they are neighbours, able to live of their own, of good name and fame,
of honest report, etc.,
as sir John Fortescue describes credible witnesses
in his treatise in commendation of the laws of England.

====

If the merits of the cause be entered into, about the circumstances of the facts,
then enquire:

[.numbered-group]
====

[.numbered]
_First;_ What manner of exercise of religion did that assembly of twenty persons and above,
as mentioned, pretend or practice, which the appellant is supposed to preach or teach to?
What did that assembly do?

[.numbered]
_And Secondly;_ What did he preach or teach to or among them?
The law describes the circumstances of fact and fines relating to the conventicle,
distinct from those of the preacher, but gives no distinct circumstance of preaching,
as whether it be according or not according to the liturgy,
but mentions only preaching or teaching, without exception or distinction.

[.numbered]
_Thirdly;_
The appellant solemnly denies that he did either preach or teach
in any such conventicle as the law describes and provides against;
as either in a seditious one,
or such an assembly as was met under colour or pretence of an exercise
of religion in other manner than according to what the liturgy and practice
of the church of England do in confession and profession allow of.

[.numbered]
_Fourthly;_ The said appellant solemnly affirms,
that he neither pretends nor practices any other thing in
the exercise of religion and worship towards Almighty God,
than what is required by holy Scripture,
and consequently warranted and allowed by the liturgy of the church of England,
as is also apparent and proved in the liturgy itself.

====

[.numbered-group]
====

[.numbered]
_First;_ For spiritual worship, John, chap.
iv. appointed in the second lesson at morning prayer, in March 17th,`' and July 16th,
+++[+++worship the Father in spirit and in truth,]
verse 23, 24.

[.numbered]
_Secondly;_ For assembling and mutual exhortation, Heb. 10:24-25.
Epistle on Good Friday,
+++[+++not forsaking the assembling of ourselves together, but let us exhort one another, etc.]
p+++.+++ 97.

[.numbered]
_Thirdly;_ For a meeting of one hundred and twenty persons in a certain house. Acts 1:15.
On St. Matthias day, +++[+++the number of names that were together,
was about one hundred and twenty.] p. 163.

[.numbered]
_Fourthly;_
For freedom of ministering by the gift of Christ received. 1 Pet. 4:10.
Epistle Sunday after Ascension day,
+++[+++As every man has received the gift, even so minister the same, etc.]
p+++.+++ 114.

[.numbered]
_Fifthly;_ For the worship of God, being free without exception of time or place.
+++[+++Communion.]
It is our bounden duty, that we should at all times and in all places,
give thanks unto you, O Lord, holy Father, Almighty, etc.

[.numbered]
_Sixthly;_ For what the said appellant and others believe, profess, or pretend,
for the pouring out of the holy Spirit, and liberty of prophecy thereby; Joel chap.
ii. appointed at matins, 20th Sunday after trinity, first lesson, and evening prayer.
+++[+++Verse 28. I will pour out my Spirit upon all flesh,
and your sons and your daughters shall prophesy, etc.]
See also Acts, chap.
ii. verse 17, 18, for the second lesson, morning prayer, April the 5th,
and August 4th. This was an evangelical prophecy, fulfilled in the gospel-day,
and church of Christ.

====

These brief memorandums upon the two precedent cases; viz: That about routs,
and this about the recorder`'s conviction,
were not only intended for my own private use and memory, when I drew them up;
but also for the notice of others,
and future information and caution of magistrates in the like cases,
if any such shall ever hereafter happen, and therefore left to posterity.

[.signed-section-signature]
George Whitehead.
