== Chapter XV

[.section-summary-preface]
George Whitehead introduces his account of his own and his friends`'
proceedings in the early part of the reign of William and Mary,
with the following review.

1689.--The great and merciful providence of the Lord God Almighty, towards us his people,
is worthy to be forever remembered; and I hope shall never be forgotten by us,
who have been really sensible thereof,
and seriously considered the same through many great trials,
deep exercises and hardships, wherein the Lord our God helped and stood by us,
and allowed not our enemies and persecutors to lay his heritage, among us,
desolate or waste.
He gave us not over to the will of our enemies,
who often breathed out cruelty against us, threatening our ruin and desolation.
Blessed be our God, who has frustrated their cruel designs,
and restrained the remainder of their wrath,
and contrary thereunto has carried on his own work, and prospered the same,
to his own praise and his people`'s comfort;
causing all to work together for good to all them who truly love his name and power:
blessed forever be the same.

Although for the space of about twenty-five years, from 1660 to 1684,
we had but little respite from some kind of persecution or other,
notwithstanding the liberty of conscience so often promised and declared from the throne,
yet the truth lost no ground, but gained through all.
The persecution time was a seed time for the truth and gospel of Christ Jesus,
which we suffered for, and the faithful grew and multiplied.
The good seed of the gospel being sown and planted, the same increased and spread,
even in those suffering times,
which neither the devil nor his instruments could ever root out.
That divine presence attended us in our many deep sufferings,
which reached and tenderly affected many hearts,
as they beheld the patience and innocency wherein
the Lord sustained us in our many trials and sufferings,
whereby many were not only moved with compassion to us,
but also to inquire after the Lord and his truth,
the cause for which we patiently suffered.
As the more Israel was afflicted and oppressed under Pharaoh in Egypt,
the more they multiplied and grew:
so as the Lord`'s people have been persecuted and oppressed in this gospel day,
the more their number has increased, and they multiplied;
wherein still the merciful providence of Almighty God has appeared,
to frustrate the evil designs of ungodly persecutors and wicked men.

And moreover it is very remarkable and memorable,
how the Lord God by his wisdom and power, has appeared and wrought for his people,
even for his name and suffering seed`'s sake,
in gradually making way for their Christian liberty,
even for that liberty of conscience from persecution, so greatly laboured for;
insomuch that the understandings of many in outward government,
even of the supreme in authority, have been so far enlightened,
as to see that liberty from persecution is not only most
equal and consistent with a Christian spirit and temper,
but also with their own safety,
and the peace of the government and nation where they rule;
and has been confessed to by many of the great ones in authority.
Yes, I have heard it declared by a great person of the church of England,
as in the name or person of the church, viz:
Neither we nor you are safe without the toleration.
And many that have formerly had a hand in persecution,
are now willing that former sin of theirs should be covered,
that they may be esteemed sincere for liberty of conscience, against persecution.
Others, even persons of note,
have gloried and seemed to rejoice in that they never had a hand in persecution,
nor signed a warrant against any of us for our conscience;
it being generally by men of ingenuity and sobriety deemed scandalous,
or a brand of infamy to be accounted a persecutor.

As the Lord our God has been graciously pleased to help us through many deep sufferings,
hardships and trials, he has also been at work in the hearts of men in power,
and judging among the gods for his heritage; Psalms Ixxxii.
1+++.+++ And in order to give his churches among us, rest from open persecutions,
he prepared the heart of the government, after the revolution,
to allow us the sanction of a law for our liberty,
together with other dissenting Protestants,
respecting our religious exercise in our public assemblies.

I may now give some brief account of the said act,
and how I and others of our friends were concerned for the same.
It commonly goes by the name or title of
The Act of Toleration, but the real title is,
An Act for exempting their majesties`' Protestant subjects,
dissenting from the church of England, from the penalties of certain laws.
_+++[+++Anno primo Gulielmi and Maria.]_

The preamble is: Forasmuch as some ease to scrupulous consciences,
in the exercise of religion,
may be an effectual means to unite their majesties
Protestant subjects in interest and affection.
Be it enacted, etc.

Which act contains much of the substance, and several clauses of the bill entitled,
A Bill of ease to all Protestant dissenters,
which was endeavoured to have been passed into an act,
by the Parliament in king Charles the second`'s time, A. D. 1680 and 1681,
but not effected either in his reign, or in his brother`'s succeeding, as before related.

After a bill was brought into the Parliament, in order to the aforesaid act, entitled,
An Act for exempting their majesties`' Protestant subjects, etc., several of our friends,
with myself, had great care and concern upon our minds,
and endeavoured that it might be as effectual and clear,
without being clogged or perplexed with any snare in it, as we could obtain;
so that we might be truly eased from persecution,
and our religious liberties be uninterrupted.

Upon perusal of the bill, we found some passages or terms not clear,
but such as tended to infringe our liberties, and render the intended law ineffectual,
and in some things, rather a snare to us, if enacted:
as particularly about some articles or confession of faith,
that some members of the House of Commons would have imposed,
for terms of liberty or ease to dissenting Protestants, which seemed partly to aim at us,
the people called Quakers; occasioned by one member especially,
openly declaring in the House, that the Quakers were no Christians:
which was but an old refuted calumny,
cast upon us by our notorious adversaries and some apostates.

Some of the terms in the said bill,
required of Protestant dissenters to prove themselves Christians, were:
That all such who profess faith in God the Father, and in Jesus Christ his eternal Son,
the true God, and in the holy Spirit, coequal with the Father and the Son, one God,
blessed forever: and do acknowledge the holy Scriptures of the Old and New Testament,
to be the revealed will and Word of God.

Although we knew that when the Parliament had granted
liberty of conscience to dissenting Protestants,
in religious exercise, grounded upon this or the like reason, namely,
for the increase of charity among Christians, and that no person or persons,
professing the Protestant religion, although dissenting from the church of England,
should be disquieted or called in question for the same;
which was very fair and plausible;
yet to prevent any such from being stumbled or ensnared
by some expressions in the aforesaid profession or creed,
which appeared unscriptural in the said bill, we instead thereof,
did propose and humbly offer, as our own real belief of the Deity of the Father, Son,
and Holy Spirit: I profess faith in God the Father, and in Jesus Christ, his eternal Son,
the true God, and in the holy Spirit, one God blessed forever:
and do acknowledge the holy Scriptures of the Old and New Testament,
to be given by divine inspiration.

Which declaration John Vaughton and I delivered to sir Thomas Clergis, who,
with some others,
were desirous we should give in such confession of our Christian belief,
that we might not lie under the unjust imputation of being no Christians,
nor thereby be deprived of the benefit of the intended law for our religious liberty.
We were therefore of necessity put upon offering the said confession,
it being also our known professed principle,
sincerely to confess Christ the Son of the living God, his divinity,
and as he is the eternal Word: and that the three which bear record in heaven,
the Father, the Word, and the Holy Spirit, are one: one divine Being, one God,
blessed forever.

Moreover, the said sir Thomas Clergis being satisfied with our confession aforesaid,
delivered unto him,
moved for the same before a grand committee of the whole House of Commons,
mentioning of our names, from whom he had the said confession.
Whereupon we were called into the house, and some other friends,
as William Mead and John Osgood,
that the committee might have our confession from ourselves,
and the Parliament be the better satisfied therewith, in hearing us.
So that I had then occasion to answer the committee very clearly,
and to their satisfaction,
both as to our really owning the Deity and the holy Scriptures of the Old and New Testament,
as given forth by divine inspiration.
The last being most in question, we gave them such plain and clear satisfaction,
both as to the holy doctrine contained in the Scriptures of the Old and New Testament,
and to the historical parts thereof, as being preserved by divine Providence to us,
that I clearly perceived our confession and testimony had
such influence and effect upon the spirit of the Parliament,
that it made for the furtherance of the said bill in order to bring it into an act.

Some of the members, when the committee was over,
would have had it made but a temporary act for three years, in which I opposed them,
and showed the unreasonableness of such a limitation of our religious liberty, urging,
that it ought to be perpetual.
So after much labour and attending on our parts the bill was passed.

Although under the reign of king William the third,
we had so far obtained liberty by law,
as to enjoy our religious meetings for the worship of God peaceably,
without molestation or disturbance by informers or other persecutors,
yet many of our friends remained prisoners, and under prosecution by priests and others,
for non-payment of tithes, and many of them detained in prisons, chiefly upon contempts,
as their term is, for not answering upon oath to the priests`' bills and plaints, etc.

These cases being considered among us, after I had impartially stated and drawn them up,
our friends agreed to have presented to the king,
that he might both understand their cases and suffering, for not paying tithes,
and not swearing: as also that the contempts were by the laws, or court rather,
deemed to be against the king,
which therefore he had power by law to pardon and to discharge
the prisoners who lay under that process or judgment of contempts.

Our friends thereupon desiring me to present the case to the king,
and to take with me three or four friends, that were free thereto,
I accepted of that service,
being always willing and ready to serve and help suffering friends,
as I had been in the two king`'s reigns before, according to my ability,
and as the Lord was pleased to enable me.

Whereupon I desired my ancient companion in solicitation, Gilbert Latey,
Thomas Lower the doctor, John Taylor of York, my late brother-in-law,
and our friend Daniel Quare, to go with me, or accompany me to the king,
and they were all willing, as I believed they would.
Daniel Quare being known to the king, which the rest of us then were not, we sent him in,
to procure our access into his presence.
The king inquired of him who we were, and in what station or places among our people?
Daniel told him we were ministers and elders.

The king then sent for us into a little private apartment, or room, where he was alone,
and I presented our case, which I desired him favourably to accept, which he did.
He inquired of us, what places we belonged to, or to what congregations we did minister?
Which gave me good occasion to answer him.
That we were not settled as ministers or pastors over any particular congregations,
but visited our friends`' meetings in various places, as the Lord inclined us.
For we do not make a gain of our ministry; we do not take stipends or hire for preaching;
but preach the gospel freely, according to Christ`'s command to his ministers,
Freely you have received, freely give.
The king gave no reply, but appeared very serious, and satisfied with my answer.

I offered to read our case to him; he said no, he would read it himself;
seeming rather willing to hear us in discourse than read at that time.

I thereupon acquainted him, that the chief of our friends`' suffering then was,
because they cannot make their answers to the priests`' suits for tithes upon oath,
which for conscience sake they refused in any case;
and no less for conscience sake do they refuse the payment of tithes;
whereby the priests take great advantage against our friends,
to run them to contempts and imprisonments,
and to make seizures upon their goods and estates.
Wherefore we had applied to the Parliament for relief in the case of oaths,
that they might not be imposed upon us in any case;
we offering to submit to the penalty of perjury in case any of us were
found false or corrupt in our evidence or testimonies given without oath.
But our applications to the Parliament have not taken effect as desired,
being sometimes prorogued or otherwise dismissed,
before we could get our case through both Houses.

This our case of conscience in refusing to swear, I told the king,
is the same with the people`'s called Menists in the low countries,
as it was a matter of conscience to them; to whom his predecessors gave liberty,
that their word, in attesting the truth in courts, might be accepted instead of an oath,
which is what we desire:
and therefore when we saw it a season to apply again
to the Parliament for relief in this case,
I desired the king to stand our friend,
and favourably to recommend our case to some leading members of Parliament;
which he seriously promised he would do.

And accordingly he did perform his promise,
as we had account from some of the noted friendly members of Parliament,
one of whom in particular,
told me he was present with the king and one of the House of Lords,
and heard them discourse about the Quakers; and how the king pleaded on their behalf,
contrary to some objections that lord made against them; which was,
That they were against, or disaffected to the government.
And that the king answered him, "`My Lord, I am not of your opinion;
for there is an honest people among them.`"
Thus much I very well remember the said member, sir John Austin, told me.

When I answered the king in several things before mentioned,
relating to our conscience and Christian testimony, he made this objection:
"`You are a divided people.`"
I told him, No; as we are a people, we are not divided, but in union:
although there are some who have separated or gone out from us,
and therefore are not of us; as there were of old,
some who separated and went out from the primitive Christians.
And although some are gone out, separated or revolted from us,
yet we remain a people in unity, i. e., of the same faith and profession.
To which our friend John Taylor, added,
"`Such as turned into separation or division from us, were some disorderly persons,
who therefore were denied by us; or to that very effect.`"
And I further added, That I had known the people called Quakers from the first; and,
as a people, they were still the same, as to faith and principle,
which allows not of division or separation in our Christian society,
and not a people divided.

The king replied to this effect: "`But some among you are disaffected to the government.`"

I answered: It is a hard matter for us to enter into the private affections of persons,
without some overt act.
We do not know that any of our friends have manifested disaffection to the government;
for if we did certainly know that any of those in communion with us,
should by any overt act, in word or deed,
show any disaffection to the present government, we should certainly disown them therein,
and give testimony against them.
It is true, we have of late been aspersed and misrepresented with such nicknames,
as Meadites and Pennites, as if we set up sect masters among us, yet own no such thing;
but Christ Jesus to be our only master, as we are a Christian society and people.

The king appeared well satisfied with my answer, and with the rest of our discourse,
being very serious in his attention to the matters proposed unto him.

I had very great satisfaction and freedom of spirit,
to open several weighty matters relating to our principles and testimony; and the more,
because he was seriously attentive to hear and receive information concerning us.

Near the conclusion I proposed to the king, that inasmuch as the Lord Keeper, i.e.:
the Lord Sommers, knew the laws,
and how far the king might safely extend his prerogative,
particularly in the case we had delivered, if he pleased,
we would deliver him a copy thereof,
that he might be the better prepared to give advice in our case,
what way the king might release our friends, who were prisoners upon contempts,
as set forth in the said case.
The king answered, "`You may deliver it to him;
for I will speak with my Lord Keeper about it.`"
After our humble and grateful acknowledgment for
the king`'s kindness to us and our suffering friends,
we withdrew.

It was the next day, or soon after we had been with the king, that our friend John Edge,
went with me to the said Lord Keeper with a copy
of the case we had presented to the king,
which I thus introduced when I gave it.
I told him we had presented the case to the king,
and having heard a good character of yourself, I being then little acquainted with him,
we made bold to mention you to the king, for counsel in this case, how our friends,
who are prisoners upon contempts, might be released:
and the king told us he would speak with the Lord Keeper about it.

The Lord Keeper took it kindly of us,
showing not only his own willingness and desire our suffering friends should be released,
and enjoy their liberties, but also freely signified to us,
that the king was really for liberty of conscience to dissenters,
and that it was his real principle; which we were very glad to hear from him,
being a person of honour and credit.

A copy of the aforesaid case, which was delivered to the king and the Lord Keeper,
follows.

[.embedded-content-document.address]
--

[.letter-heading]
To the King.

[.blurb]
=== The case and request of the peaceable people commonly called Quakers, in behalf of many of them who are present sufferers for conscience sake, humbly presented.

[.salutation]
Showing,

That as the God of all our mercies has preserved
us a peaceable and quiet people in the land,
according to our Christian principle and profession,
under the various revolutions of government; so we humbly hope and resolve,
by his divine assistance, ever so to continue;
being heartily thankful for the several kindnesses
and compassions received from the government;
especially for the present liberty we now by law enjoy, in point of religious worship.

Yet forasmuch as many of the said people are continued
under deep sufferings in their persons and estates,
by tedious imprisonments, seizures and sequestrations;
several also of late having died in prisons, and many more under prosecution,
and liable so to suffer in England and Wales; tending to the ruin of many families,
for these cases of conscience, i.e.: chiefly on contempts, as adjudged,
for not answering upon oath, in cases of tithes when sued in the exchequer,
and also for not answering upon oath when prosecuted in the ecclesiastical courts,
for tithes, church rates, etc.
Whereupon they proceed to excommunication,
and by __significavits procure writs de excom. cap+++.+++,__
and sometimes justices`' warrants to imprisonment.

We therefore humbly remind the king,
that the great severities and persecutions formerly inflicted on us,
were sometimes abated and respited,
when it pleased God to move the heart of the kings and governments
to show some compassion and favour to us;
whereof these are some instances:

[.numbered-group]
====

[.numbered]
1+++.+++ By king Charles the second`'s proclamation of grace in 1661,
whereby many of our friends were released and freed out of prisons.

[.numbered]
2+++.+++ By his letters patent, or pardon, in 1672,
pursuant to his declaration of indulgence to tender consciences in the same year.

[.numbered]
3+++.+++ By an act of Parliament, 25 Car.
2, chap.
5, entitled, An Act for the king`'s majesty`'s most gracious and general pardon,
pardoning contempts, etc. against the king,
whereby many also of the said people were discharged and released out of prisons.

[.numbered]
4+++.+++ Also by king James the second, many were released out of prisons,
and relieved by various commissions, and two general proclamation pardons,
the one in 1685, and the other in 1688.

[.numbered]
5+++.+++ And also by an act of gracious, general, and free pardon,
in the second year of king William and queen Mary,
several were discharged from contempts and imprisonments.

[.numbered]
6+++.+++ And by your late consort the queen, on application made to her in your absence,
a poor innocent woman, who had been long prisoner at Lancaster, upon a tine,
was released; which as an intimation of the queen`'s tender and merciful disposition,
we very thankfully acknowledged;
as we do also very kindly acknowledge the king`'s late favourable inclination,
to discharge two of our friends, prisoners on fines in Westmoreland,
upon a petition presented by our friend Daniel Quare.

====

These noted precedents of favour and compassion to the oppressed,
and the present confinements and hardships of many innocent persons tenderly considered;

We the said people humbly request that the king would be pleased
to extend his favour and compassion towards the said sufferers,
for their lawful ease and relief from their present confinements, prisons and hardships,
either by proclamation or otherwise,
as in his wisdom and clemency shall seem most fitting and convenient.

--

This case was presented to king William the third, the 2nd day of the second month, 1695,
by George Whitehead, Gilbert Latey, Thomas Lower, John Taylor and Daniel Quare;
and was favourably accepted.

In a very short time after the aforesaid case of our then suffering friends, prisoners,
was presented to the king and Lord Keeper,
there came out an act of grace by the king and Parliament, in the year 1695, entitled.
Pardoning contempts, etc.
Whereupon about forty of our friends were discharged out of prisons.

As to our endeavours with the Parliament for relief in the case of oaths,
from the imposition thereof;
I saw it very fitting and requisite that I should give some account,
having been greatly concerned to assist friends in that weighty case,
wherein some of us innocently laboured early and late, in solicitation.

[.numbered-group]
====

[.numbered]
1+++.+++ To bring the members of Parliament to a right understanding of our case,
as it is a case of conscience toward our Lord Jesus Christ,
that we are under his express prohibition and command, not to swear at all,
or in any case.

[.numbered]
2+++.+++ To show them the great necessity of affording some relief to us in this case,
from the hardships, oppressions and disappointments that many suffered,
because for conscience sake they could not swear or take an oath,
either to relieve themselves or neighbours.

[.numbered]
3+++.+++ Our case and petition to the Parliament, and a copy of the bill,
as it passed the House of Commons,
and how the solemn affirmation was formed and passed the House of Lords,
are fairly stated and related in the ensuing collection.

====

[.embedded-content-document.address]
--

[.blurb]
==== The suffering case of the people commonly called Quakers, relating to oaths and swearing, humbly offered.

It is not unknown to this nation, that ever since we were a people,
it has been our principle not to swear, make or take oaths,
which He who is the searcher of all hearts knows,
is no other than a case of pure conscience,
in tender obedience to the mind of our blessed Lord and Saviour Jesus Christ,
as we are fully persuaded,
according as many eminent martyrs and men of wisdom and renown were,
who testified against oaths and swearing in the gospel day, and not any obstinacy,
disaffection or worldly interest whatsoever on our parts.
We are really willing and desirous to answer the just and good ends of law and government,
as a peaceable people fearing God; and for this cause of not swearing,
we have been exposed to great sufferings and inconveniencies, in our persons and estates,
by tedious imprisonments, and disabled from receiving our due debts,
or defending our just titles and properties;
not permitted to give evidence in courts of judicature at common or civil law,
nor to answer in chancery or exchequer, prove wills and testaments,
or take administrations, or to proceed in our trades at Custom house,
or be admitted to our lands, or trusted in our duties and services in Courts leet,
and Courts baron, but great advantage is taken against us, because we so fear an oath,
as that we dare not swear.
For this cause also,
our children and young men are not allowed their freedoms in cities or corporations,
when they have faithfully served out their apprenticeships,
nor admitted to give our voices in elections of magistrates
and Parliament members in various places,
though known to have right thereunto as freeholders, etc.

Wherefore our request is, that in all cases where oaths are imposed,
and swearing required, our word, that is, our solemn affirmation or denial,
as in the fear and presence of God, may be accepted instead of an oath,
for which we humbly offer and freely submit,
that if any under the same profession among us break their word,
or be found false in such their affirmation or denial,
or guilty of falsehood in any unsworn testimony, evidence, or answers,
that then such penalty be inflicted on the person so offending,
as law and justice require in case of false swearing or perjury.

--

[.embedded-content-document.address]
--

[.blurb]
=== To the respective members of the House of Commons, the humble application of the people commonly called Quakers.

We the said people, being a member of that body which you represent,
and concerned in trade and industry,
and employing many poor in the manufactories of this nation;
as also in contributing to the charge of the government, according to our abilities;
do desire and humbly crave that our liberties, rights and properties,
may be secured to us and ours;
that we may no longer be exposed to unjust and vexatious suits,
nor be a prey to ill-disposed persons, who take advantage against us,
to prosecute and ruin us, merely because in point of tender conscience,
we dare not swear in any case;
which is in obedience to the command of our blessed Lord and Saviour Jesus Christ,
as we verily believe is our duty in this gospel day;
but hold ourselves obliged to declare and testify the truth without oath,
in cases wherein our answers and testimonies may be required.

Wherefore we humbly entreat your Christian compassion
in your favourable acceptance of our petition,
which is, for leave to bring in a bill for our relief;
and so to consider our suffering case, as if it were your own, and you in our stead;
that we and our posterities may have cause to bless the Lord on your behalf.

--

[.embedded-content-document.address]
--

[.blurb]
==== To the Commons of England, in Parliament assembled: the humble petition of the people called Quakers.

[.salutation]
Shows,

Our many, long and renewed sufferings for not swearing,
we hope may give satisfaction to this nation,
that it is purely our conscientious and religious principle not to swear in any case,
in tender obedience to the command of our blessed Lord and Saviour Jesus Christ,
as we are fully persuaded;
and according to the example of many eminent martyrs and men of holiness,
wisdom and renown, who testified against oaths and swearing in the gospel day.
Nevertheless we have been, and yet are, exposed in our persons to tedious imprisonments,
in our estates to sequestrations and seizures,
disabled from defending our just titles and properties, recovering our due debts,
or helping others in like cases, and to many unjust and vexatious suits.

Wherefore, the power of relieving us by law,
from these our grievances and hardships resting in the king and Parliament,
our humble request is, that you will favourably please to give leave to bring in a bill,
that our solemn affirmation or denial may be accepted instead of an oath,
freely submitting that whoever in this case, shall falsify the truth,
and be thereof duly convicted, shall undergo like pains and penalties,
as in law and justice are due unto perjured persons.

This petition was agreed to and signed by the friends following:

[.signed-section-signature]
John Staploe, John Harwood, William Bingley, Walter Benshall, Jo. Hall, George Whitehead,
Thomas Lower, Gilbert Latey, William Mead, Richard Thomas, Thomas Hudson, Thomas Hart,
Theodore Ecclestone, Jo. Butcher, Michael Russel, Samuel Jobson, John Hermon,
Daniel Quare, John Bull, George Oldner.

--

Our petition, thus agreed unto,
and some fair copies thereof prepared for members of parliament,
we showed to many of the House of Commons.
And it took us some weeks`' time in solicitation,
to prepare them for our case and petition,
that it might not be moved too soon or abruptly,
before many of the House were well apprized and prepared.
I did particularly pitch upon Edmond Waller, esquire, and engaged him to help us therein,
he having then pretty great influence in the House,
and being my particular acquaintance and friend:
and when I had given him fully to understand our case, and what we requested,
he sincerely undertook to assist us what he could,
and was very helpful by solicitation and motion in the house, for our said petition,
which when moved, was read on the 7th of the twelfth month, 1695,
and carried by a great majority; and leave given to bring in a bill,
that our solemn affirmation, and negation or denial,
might be accepted instead of an oath, etc.

Whereupon many of the members came out to us with great joy, love and tenderness also,
and showed their satisfaction, that they had so well gained the point for us.

Leave, as before, being given to bring in a bill for our relief,
according to our petition, several draughts were prepared;
the first by counsellor Conyers, which was something large and long,
yet he took some pains in it, to answer what we requested in our petition,
particularly about our solemn affirmation, etc., to be accepted instead of taking an oath,
and to exempt us from swearing.
In his bill, he stated the matter, that the Quakers should solemnly declare the truth,
in like manner and form of words,
as are used by all other persons who are required to declare the same,
except only the attestation thereof upon oath; that is, the words, swear, and,
So help me God, etc., to be omitted.
But then to make our attestation, affirmation or negation,
so solemn as was expected from us by the Parliament, in courts of justice, etc.,
it was the opinion of most of our friends in Parliament,
that there must be some solemn or sacred expressions, religiously respecting God,
as solemnly to declare the truth in his presence; which we dared not gainsay,
lest we should be deemed atheistical; it being our principle that God is Omnipresent,
and Omniscient also.

However, as in a multitude of counsel there is safety,
we discoursed the point with several ingenious men of the House of Commons,
that we might proceed with what safety and success we could.
We went particularly to sir Francis Wynington, an ancient, able counsel,
who greatly stood our friend;
and we showed him counsellor Conyer`'s draught of the said bill, which, upon perusal,
sir Francis judged much too long,
and that it would be the more tedious and difficult
to get it through the House into an act;
adding this reason, that it had better be too short than too long,
that the committee might have the amending of it,
and then they would be the more willing to pass it; whereupon he drew up a short bill,
but would not insert therein the bare words, yes or no,
for attestation in courts of justice; and to offer the same in the House of Commons,
in a bill for an act of Parliament, his opinion was, would be laughed at,
or ridiculed and rejected.

Many others were of the same mind,
that such expressions or terms must be offered in the bill,
as might appear solemn or sacred, whether in affirmation or negation, as to declare,
In the presence of God, to an answer or evidence, etc.
Their forms of oaths and swearing having been of such long standing,
and such great stress and obligation laid upon them, for many hundred years,
that it was a very difficult point,
and a great thing to gain any such variation or alteration from them,
as conscientiously to declare or affirm.
In the presence of Almighty God, instead of the imprecation oath of, So help me God;
and the ceremony of handling or fingering and kissing the Bible.

To obtain such a great alteration from an oath and imprecation, to a plain,
solemn affirmation, as before, was indeed a great point,
as many of our friends were very sensible of, and thankful for, when it was gained.

A copy of the aforesaid bill for solemn affirmation, instead of an oath,
as it was drawn up by sir Francis Wynington,
corrected and passed by the House of Commons, the clause relating to tithes excepted,
which was ordered by the House of Commons, and is in the printed act.

[.embedded-content-document.legal]
--

[.blurb]
=== A Bill that the solemn affirmation or denial of the people called Quakers, may be accepted instead of an oath.

Whereas some dissenters, commonly called Quakers,
refusing to take an oath in courts of justice, and other places,
are frequently imprisoned, and their estates sequestered,
by process of contempt issuing out of such courts,
to the ruin of themselves and families.

For remedy thereof, be it enacted, by the king`'s most excellent majesty,
by and with the advice and consent of the Lords spiritual and temporal,
and Commons in this present Parliament assembled, and by the authority of the same,
that from and after the 4th day of May, which shall be in the year of our Lord 1696,
every Quaker within this realm of England, dominion of Wales,
or town of Berwick upon Tweed, who shall be required, upon any lawful occasion,
to take an oath in any case, where, by law, an oath is required, shall, instead thereof,
be permitted to make his or her solemn affirmation or declaration,
In the presence of Almighty God; which said solemn affirmation or declaration,
shall be adjudged and taken,
and is hereby enacted and declared to be of the same force and effect,
to all intents and purposes, in all courts of justice and other places, where,
by law an oath is required, within this kingdom of England, dominion of Wales,
or town of Berwick upon Tweed, as if such Quaker had taken an oath.
And be it further enacted, by the authority aforesaid,
that if any Quaker making such solemn affirmation or declaration,
shall be lawfully convicted, willfully,
falsely and corruptly to have affirmed or declared any matter or thing,
which if the same had been upon oath,
would have in any case amounted to wilful and corrupt perjury;
every such Quaker so offending, shall incur the same penalties and forfeitures, as,
by the laws and statutes of this realm are enacted,
against persons convicted of wilful and corrupt perjury.

--

The bill was read the 17th of the twelfth month, Feb., 1695, the first time,
and the 3rd of the first mouth, 1696, a second time; and committed:
the same day the committee met.
For its being committed, one hundred and thirty votes; against it, sixty-eight;
more for it than against it, sixty-two.

The 4th of the first month, the committee met again, and passed the bill.
The 10th of the first month it was ordered to be engrossed;
and on the 13th the bill passed the House of Commons
by one hundred and forty-six voices for it,
and ninety-nine against it; forty-seven more yeas than noes;
and the same day it was carried to the house of Lords, where it was read twice;
but the opposition some members of that House made to us herein,
occasioned our longer attendance and labour to inform them rightly of our case,
and the necessity of our being relieved.
Upon my reasoning with several of the peers, who had opposed us, I so far convinced them,
that they were changed in opinion concerning us, and appeared for us; insomuch,
that I was daily sensible the hand of the Lord our God,
that was with us in our endeavours, made way and did work for us therein.
To Him be the glory of all forever.

To incline the House of Peers to grant relief from our sufferings for not swearing,
our case was reprinted and presented with several reasons subjoined;
and among others this following:

[.embedded-content-document.address]
--

We also propose to your serious consideration,
that this moderation to persons scrupling to swear,
has had good effects in neighbouring countries,
as above one hundred years experience has manifested, in the following instance;
on the 26th day of January 1577, Guilliaume de Nassau, Prince of Orange,
and Statholder of Holland, Zealand, etc., with the consent of the government and council,
sent his mandate to the magistrates, commanding on behalf the people called Menists,
who refused to swear in any case,
that their yes should be accepted and taken instead of an oath, they being subject,
in case of falsifying the truth, to the pains of perjury.

In the year 1593, Prince Maurice, son of the former prince,
with the consent of the States, gave forth a mandate in behalf of the Menists,
to the same effect.

--

Upon these passages of the Menists having this liberty
to be exempted from taking an oath upon their yes,
there was this quotation in the margin of the second impression
of G. Burnet`'s History of the Reformation in the Low Countries,
part 1. page 587, 588.

Whereupon some of the temporal lords told me,
that the Bishop of Salisbury had taken occasion to exclaim
against the Quakers openly in the House of Lords,
for falsely quoting his name as author of the said History.
Whereby I was somewhat surprised,
and told the Lords I would make inquiry about the mistake;
and quickly searching the first impression found it to be a literal mistake of the printer;
for in the first, it is G. Brant`'s History, not Burnet`'s. I went the next day,
and showed the same as first printed, to two of the said Lords, i. e.,
the Earl of Carbery, and Earl of Marlborough, desiring them to call the said bishop out,
that I might show him where the mistake was; which they did,
and then I plainly showed the bishop, that it was a literal mistake of the printer;
and that the Quakers could have no design to misrepresent him in the quotation;
neither could the mistake be any great disparagement to him,
to be rendered the author of such a noted or esteemed History of the Reformation aforesaid.

And therefore I hoped he would pardon the mistake, so as not to charge us therewith,
which he cheerfully granted, making then but slight thereof.
Thereupon I wished him to be our friend with respect
to the bill depending before the house of Lords,
to relieve us from oaths, meaning, that it might be put forward and not delayed.
He then objected that the name of God was not mentioned in it, i.e.:
solemnly to bear witness in the presence of God; and if we did not allow of that,
he would be against us; but if the presence of God, was in it,
he promised he would be for us.
I told him those solemn expressions, In the presence of God, were in the bill,
as it came from the House of Commons, I was sure; desiring him to go in and see the bill,
that he might satisfy himself of the truth thereof;
so he went into the House of Lords to see the bill, and quickly came forth again to us,
standing with the two temporal lords: and he then said it was true, as I had told him,
the presence of God was mentioned in the bill.
The Earl of Carbery told him, "`Then you were mistaken,
my lord;`" whereupon I said to him, I hoped he would now be for the bill,
and be present on the day it was appointed, and intended to be moved in the House,
to second the motion for it.
He promised before the two lords he would, but did not,
being absent that very day it was moved; of which, notice was taken by them and others.
Howbeit the Lord our heavenly Father stood by us and helped us,
and inclined many of those in power to help forward the case,
for our desirable and requested relief.

On the 15th of the second month, called April, 1696, the bill was read a second time,
debated, and committed to a committee of the whole house,
and then some debate held a while, chiefly about a solemn declaration instead of an oath;
some of them not being willing it should pass in those general and solemn expressions,
as sent up from the House of Commons, viz; their solemn affirmation or declaration,
to be in the presence of Almighty God.
But some of the bishops urging some other words to be added as:

I call God to witness and judge; As witness and judge; I call God to record upon my soul,
and appeal to God as judge, etc.
These, and such like expressions, some would have had put in the bill,
instead of the usual oaths.

Whereupon some of the temporal lords came out several times,
we waiting at several doors and ways into the House of Lords,
to discourse about those words, which some of the bishops would have had put upon us;
to all which, as I told some of them at first,
our soliciting and petitioning to be freed from the imposition and burden of all oaths,
was not to have any new oath imposed upon us; for if there be any imprecation,
appealing to, or invoking God as judge or avenger, it would be construed to be an oath,
or the nature of an oath.
Upon which, and the like exceptions,
some of those lords who were the most friendly to us, returned into the House,
to discourse further with the bishops.
When they perceived how tender and careful we were,
not to be imposed upon in anything contrary to our consciences;
after they had further discoursed in the committee with those bishops,
they came out again to us in the lobby, where a few of us were attending,
under a true Christian care and fear towards Almighty God.
And those lords who came out to us, and showed most care and kindness to us, urged,
that in as much as the bishops were caught upon these words to be added to the word +++[+++God]
viz; The witness of the truth of what I say,
as containing no imprecation or invocation of God, as judge or avenger,
we would admit of the addition, rather than lose our bill, or have it thrown out;
for as much as God is really witness to the truth sincerely declared,
he being Omniscient as well as Omnipresent.
Then seeing the bishops were argued out of their first proposition,
of calling God to witness and judge, etc.,
the matter was left to those who appeared our friends and were really kind to us,
with this caution not to exceed these words, which they had obtained concession to,
namely: the witness of the truth.
Whereupon they constrained the bishops, so as not to exceed them, by any imprecation,
invocation, or appeal to God, as judge, avenger, etc.

After report made of their amendments by the committee of the lords`' House,
the bill was passed, with the following form of a solemn affirmation inserted in it,
and agreed to by the House of Peers, i.e.:
I A. B. do declare in the presence of Almighty God,
the witness of the truth of what I say.

With some few additions in the bill not very material,
they returned it to the House of Commons, which,
on the 17th of the said second month called April, agreed to the lords`' amendments,
and on the 20th of the same month,
the bill was sent up and carried again to the House of Peers, agreed on, concluded,
and confirmed by the king and both Houses of Parliament, as a temporary act,
then to continue in force for seven years from the 14th of May, 1696,
and from there to the end of the next session of Parliament,
according to the words of the act.
It was renewed again for eleven years, beginning the 22nd of November, 1702;
at which time not being well in health,
I could be but little with the other friends in their
attendance on the Parliament in that concern.

There was a bill entitled, An Act for the better payment of church rates, small tithes,
and other church duties, and the better passing church wardens`' accounts:
which bill the Bishop of London endeavoured to promote in the House of Lords,
in November, 1689, grounding the same partly upon the statute of 32 Henry VIII., chap.
7.

We having beforehand obtained a copy of the said bill, or heads thereof,
and previous notice of the day appointed for a committee
of the lords to sit about the said bill,
I prepared some few exceptions, to show how injurious it would be, if passed into an act;
and how repugnant, to common law and justice,
and the rights and properties of the subject.

In the first place it is fitting to recite some heads and clauses of the said bill,
which follow:

[quote]
____

__Preamble--__Forasmuch as the fabrics of many parochial churches and chapels,
and the value of poor vicarages, within this realm, are daily growing into great decay,
because very many persons do refuse to pay their church rates, small tithes,
and other ecclesiastical duties and charges.
And whereas by a statute made in the two and thirtieth year of king Henry the eighth,
chap.
7, entitled, An Act how tithes ought to be paid, and how to be recovered being not paid,
it is enacted, That if any person or persons,
after definitive sentence given against them, in the court ecclesiastical,
obstinately and willfully refuse to pay their tithes, or such sums of money adjudged,
wherein they are condemned for the same;
that then two justices of the peace for the same
shire where the person condemned does inhabit,
shall have authority upon information, certificate,
or complaint to them made by writing by the ecclesiastical judge,
that gave the same sentence,
to cause the same party so refusing to be attached and committed to the next jail,
and there to remain without bail or mainprize,
till he or they find sufficient sureties to be bound by recognizance, or otherwise,
before the same justices, to the use of our sovereign lord the king,
to perform the said definitive sentence and judgment, as by the said act,
relation being thereunto had, more at large appears.

Be it now enacted by the king`'s most excellent majesty,
by and with the advice and consent of the Lord`'s spiritual and temporal,
and the Commons in this present Parliament assembled, and by the authority of the same,
that if hereafter any suit, or complaint shall be brought, in any court ecclesiastical,
concerning church-rates, small tithes, or offerings, oblations, obventions,
or other church-duties to the clerk, or sexton of the parish, or touching the passing,
or refusing to pass churchwardens`' accounts,
and paying over the remainder to the churchwardens that shall succeed;
the ecclesiastical judge, in all and every such suit, and for,
and concerning all and every of the causes aforesaid,
shall have power to call both the parties before him: And in case any party so called,
and being duly summoned,
shall contumaciously absent himself for the space of one calendar month,
after the return of such summons; that in such cases,
it shall and may be lawful for the ecclesiastical judge,
to declare the party so called or summoned, to be taken _pro confesso;_
and if both parties shall appear, then the said judge shall,
and may hear and examine the matter summarily,
according to the course and process of the said ecclesiastical law,
and to examine witnesses upon oath _viva voce._
And having heard and examined the whole matter,
or in case of either of the parties contumaciously absenting as aforesaid,
and being declared _pro confesso,_
the said ecclesiastical judge shall by interlocutory decree, order,
judge and determine the same, as well principal as costs, and monish the party condemned,
to pay and satisfy the same accordingly.
Which if any person or persons being so monished, shall neglect or refuse to do,
or perform, the said judge his order or judgment,
then the ecclesiastical judge shall certify two of
the justices of the peace of the same county,
and the said justices shall issue out their warrant
to distrain the goods of such person or persons,
against whom such judgment is past; and in case no distress can be found,
then the same remedy shall be had and used in every of the said causes,
as by the fore-recited Act is given and provided in the cases of tithes.

And be it further enacted, by, etc.
That if any party or witness being duly cited, shall not appear in court,
but contumaciously absent themselves, it shall,
and may be lawful upon like certificate to two justices of peace,
to issue out warrant for the attachment of such party or witnesses,
and for his commitment to prison,
there to remain until sufficient surety be given to the king,
to make his appearance in court to which he was cited.

Provided also, that if the party sued for any of the causes in this Act specified,
shall during the suit, or after sentence, go into any other county,
than that wherein the cause is commenced or depending,
that the ordinary before whom such cause shall be brought,
shall (at the instance of the party who has obtained judgment,
etc.) under his seal of office,
make information and request touching the premises to any two justices
of the peace of the county where such person shall be and reside,
who are hereby empowered to attach such person,
and to commit to prison without bail or mainprize,
till the said person shall give in security to stand by,
and make good the orders and decrees of the ordinary in such cause,
or to cause the goods of such party to be distrained, as is above enacted.

Provided nevertheless, that if the ordinary for the time being,
shall be in the commission of the peace in that county,
where the complaint lies for any of the causes in this Act specified, he shall be,
and is by this present statute empowered to act after the same manner,
and to the same effects and purposes in law,
as the justices of the peace upon information,
or request to them made by the ordinary might have done,
or may do by virtue of this statute.
____

[.blurb]
=== An account of the substance of what was pleaded before the committee of lords, against the said bill, the 14th day of the ninth month 1689. With some remarks thereupon added, by George Whitehead.

Present in the committee,--the Bishop of London, chairman, the Bishop of Winchester,
the Earl of Mulgrove, Earl of Suffolk, Earl of Craven, Earl of Kingstone.
After discourse, came in the Earl of Stamford, and the Duke of Bolton.

The friends who appeared, before the committee,--G. Whitehead, J. Vaughton,
T+++.+++ Ecclestone, J. Fiddeman, W. Bingley, T. B Jo. Edge, J. Hall.

We being on our request admitted to appear before the said committee,
and permitted to signify what reason we had to except against the bill aforesaid,
and the Bishop putting the question; I answered,
the same reason that is given in the Act of Parliament,
in the 17th of king Charles the first,
for the taking away the court commonly called the Starchamber and the
power of the ecclesiastical commissioners and their high commission court,
being removed, because of their oppressive and arbitrary proceedings,
upon the repeal of a branch of a statute Primo Elizabeth,
concerning commissioners for causes ecclesiastical, 17 Car.
1 cap.
10 and 11. It is conceived, with submission,
that the same reasons may be alledged against the present bill,
giving such absolute power to the ecclesiastical courts, their judges and ordinaries,
to give definitive sentence and judgment as therein described.

[.discourse-part]
_Bishop:_ You except against the bill itself.
What particulars do you object against?

[.discourse-part]
_George Whitehead:_ Observing several particular clauses therein,
it appears contrary to the great charter of England, i. e. Magna Charta,
as the arbitrary and oppressive proceedings of the Star-chamber
and High-Commission court were judged to be,
and therefore they and their power or jurisdiction which they exercised,
were justly taken away from them.

[.small-break]
'''

By the present bill, the ecclesiastical judge or ordinary,
is made the sole judge and determiner by his definitive sentence,
concerning the penalties upon the persons and estates,
and no appeal to any other or higher court, seems to be granted or allowed by it.

The ecclesiastical judge and court, commonly favour the plaintiff, i. e. the Vicar,
Priest, or Curate, as a party for him,
and therefore appear not to be impartial judges in the case.

And suppose the defendant be sued for a tithe-pig, goose or hen,
or a little orchard fruit, i. e. a few apples, pears, plums or cherries,
or the value thereof, and the party for conscience sake cannot pay the same,
then must he or she be committed to prison for it.
Surely there is no proportion between the punishment and the pretended offence,
whereas punishments ought not to exceed the nature of the offence.
They should be adapted to the quality and quantity of the offence,
as it is a maxim in common law and justice, and in Magna Charta, for a greater offence,
a greater amercement; and for a lesser offence, a lesser amercement.
But if a person for conscience sake cannot pay a tithe-pig, or goose,
etc. the ecclesiastical court, judge or ordinary, by their certificate,
will cause two justices to commit the person to jail,
there to remain perhaps without bail or mainprize, until the court receive satisfaction,
or until payment; which if he can never do,
there he must remain under confinement till death,
and his days may be soon shortened thereby, as many have been, by close confinement,
causing sickness.
How unchristian, as well as inhuman and unjust is it, thus to prefer a tithe-pig,
etc. before a man`'s liberty, health or life!

One of the committee queried, "`Which would you have then?
Do you choose rather to have your goods seized or distrained,
than imprisonment of your persons?`"

[.discourse-part]
_George Whitehead answered:_ Of two evils we had better suffer by the less,
yet choose neither.
If we must suffer for non-payment of tithes,
we would rather suffer the less penalty than the greater;
rather loss of goods than our liberties; as it is a more easy suffering,
to have the small tithes or a tenth taken away,
than to be confined in prison all our life time.

As to paying parish-clerks, or sextons, or to the fabrics of parochial churches,
(so the bishop termed them) we do not think it equal
we should suffer for not paying to them,
whom we do not employ;
and we do not require any of the church of England to pay toward the repair of our meetinghouses;
they would not be so dealt by.

[.discourse-part]
_The Bishop reflected:_ "`What, then, you compare your meetinghouses to ours,
which are established by law.

[.discourse-part]
_I replied:_ We are thankful to the government,
ours are now legally allowed by the late Act of exemption, or toleration, etc.

If any party or witnesses cited to appear in the ecclesiastical court, and absenting,
must incur imprisonment, upon certificate from the same court, judge or ordinary thereof,
may not this tend to force some persons to be informers against their honest neighbours?

And do not the courts ecclesiastical, their ordinaries and judges,
render themselves voluntary informers, as well as severe judges,
if by their certificates to justices of peace,
they should cause the justices to be the executioners of their definitive sentences,
decrees or judgments, to imprisonment of men`'s persons, or taking away their goods?
Does not this bill exceed the Stat, of 32 H. 8. cap.
7, in severity,
and allow a greater and more absolute power to the
ecclesiastical courts over men`'s persons and properties,
than ever they had since the times of popery, excepting that of the Star-chamber,
and ecclesiastical commissioners, or high-commission court, before mentioned?
Both taken away and made void in the seventeenth year of king Charles I. cap.
10 and 11. An appeal being also admitted upon condition by the Stat.
32 H. 8. c. 7. quoted, yet none by this bill,
but sureties required to satisfy the definitive sentence and judgment of the court.

[.small-break]
'''

One of the lords temporal of the said committee, put this question to us:
"`But what reason have you in point of conscience, for your refusing to pay tithes?`"

I answered, that is a serious and weighty question, and deserves such an answer.
The reason of our conscience in this case, is grounded upon,
and has respect unto our Lord Jesus Christ`'s command in his commission to his ministers,
freely you have received, freely give. Matt. 10.
And to his changing the priesthood of Levi,
and disannulling the commandment and their law for tithes,
as is fully signified in the seventh chapter to the Hebrews.
Therefore Christ`'s ministry is a free ministry, under the gospel dispensation,
and not to be upheld by tithes, or forced maintenance; and it is very manifest,
that Christ changed the priesthood from the tribe of Levi to himself,
as our great High-Priest, who came not of the tribe of Levi, but of the tribe of Judah,
of which tribe Moses spoke nothing concerning priesthood; Heb. 7:14.

And our refusing to pay tithes for conscience sake, in these respects,
in this gospel day, and for these reasons, under the gospel dispensation,
is no new or strange thing;
for many eminent martyrs and reformers were of the same judgment with us in this matter,
or testimony against tithes, in this dispensation.

And as I was then beginning to mention some of those martyrs, etc. as William Thorp,
Walter Bruce, John Wickliff, etc. the said Bishop being chairman,
was pleased to interrupt me from proceeding further in my instances,
and thus reflecting turned upon me, saying: "`Here you bring scraps of scripture,
but we have scripture as well as you, viz: If we have sown unto you spiritual things,
should not we reap of your temporal, or carnal things.
And the Lord has ordained, that they who preach the gospel, should live of the gospel,
etc.`"

[.discourse-part]
_Answer:_ Reaping temporal things, or living of the gospel, is not limited to tithes.

[.small-break]
'''

Here I was interrupted and prevented from further discourse against tithes.

[.discourse-part]
_The Bishop asked us:_ "`Have you any exceptions or reasons to offer in writing?`"

[.small-break]
'''

I answered, "`yes, we have,`" which we then delivered to the clerk, John Relph, Esq.
to read; which he did very distinctly, and no reply was given;
but the Bishop directed him to lay them by for further consideration, or to that effect.
But we heard of no further consideration, or debate about the said bill,
in the House of Lords, but that it was wholly laid aside.

The temporal lords, who were present in said committee, were very civil to us,
and after that discourse, several of them appeared more kind to us than ever before.

I was very glad and esteemed it a great mercy from the Lord to us,
that the said bill was stopped and laid aside; for if it had been gotten into an act,
or law, I was persuaded that the priests of the persecuting sort,
would have taken such strength and encouragement thereby,
that they would have persecuted and imprisoned a
great part of our friends throughout England, etc.

Blessed be the Lord, they were disappointed,
that that weapon was not formed ready to be put into their hands,
or power to make use of.

[.blurb]
=== Exceptions against the Bill, entitled An Act for the better payment of Church-rates, Small Tithes, and other Church-duties; and for better passing Church Wardens accounts; humbly offered.

[.offset]
It is observed.

That in the said bill, no appeal to any other, or higher court is granted,
or provision made for redress, or restitution to the persons wrongfully prosecuted;
nor for the punishment of such as may maliciously or wrongfully prosecute others:
but the ecclesiastical judge is made the sole judge and determiner,
by his definitive sentence,
concerning the penalties upon the persons and personal estates.

No trial by juries is allowed, although the penalty seems to be two-fold,
or of two kinds, imprisonment of person and distress of goods.

No discharge of the prisoner is provided, when distress is made.
Doth not this amount to two punishments, for one supposed offence, that is,
loss of liberty, and loss of goods,^
footnote:[Some have suffered by imprisonments and sequestrations, being excommunicated,
etc.]
tending to starve the poor wife and children at home.

No legal excuse is admitted or provided for the party cited, summoned, or prosecuted,
suppose he be gone a long journey,
or otherwise unavoidably prevented by his emergent occasions from appearing,
but he must be taken _pro confesso,_ which is to condemn him without hearing.

The penalty is the same for not paying the clerks or sexton, or church-rates,
as it is for not paying small tithes.
Query, how can this be equal, or bear proportion?
May not this increase our trouble and sufferings,
by thus giving power to so many and such prosecutors, as clerks and sextons,
etc. and on such small accounts as theirs?

Any party, or witness cited to appear in the ecclesiastical court,
are liable to imprisonment upon certificate from the said court, which is,
or may be very hard, especially as to our friends, who cannot, for conscience sake,
swear in any case.

Whether this bill does not exceed the Stat. 32. H. 8. c. 7., in severity,
and give greater and more absolute power to the ecclesiastical
courts over men`'s persons and properties,
than ever they had, excepting the power of the Star-chamber,
and the ecclesiastical commissioners, or high commission-court, which was taken away,
repealed, and made void, 17 Car. 1. chap 10, 11.

An appeal seems allowed, Stat. 32. H. 8. chap. 7., but there is none in this bill.

Imprisonment till sureties to perform the definitive
sentence and judgment of the court ecclesiastical,
but no distress of goods in the interim, by the said Stat. 32. H. 8. c. 7,
which yet is very hard and severe of itself.

It is also with submission conceived,
that other reasons against this bill may be duly alledged,
and such as formerly did legally and justly induce the Parliament
to repeal the Statute made the 11th year of king Henry VII.
ch, 3, which was repealed in the first year of king Henry the VIII.
ch. 6. Vide Chief Justice Coke`'s Institutes, part 4, fol. 40, 41, and second part,
fol. 51. where Rd. Empson, and Edmund Dudley`'s arbitrary proceedings thereupon,
are discovered and condemned; as well as the said court of the Starchamber,
and the power of the high commission court, were taken away by king and Parliament,
as before quoted.

It is conceived, that the same reasons for removing those courts,
and the repeal of the branch of the said Stat.
1 Eliz.
(which gave them their power and jurisdiction) stand good against the present bill,
as being contrary to the great charter, and common course of justice,
by giving such absolute power to the ecclesiastical courts and their judges,
to determine and give definitive sentence and judgment upon subject`'s personal estates,
or goods and chattels, and for confinements of persons; which tends greatly to oppress,
burden, and ruin them.

Lastly, the liberty of conscience already confirmed by law,
may greatly be infringed and lessened, if the ecclesiastical judges, or courts,
have such absolute power and jurisdiction given them over men`'s persons and properties,
according to the import of the present bill; which it is really believed,
must needs greatly dissatisfy many thousands of the
king`'s conscientious protestant subjects,
and increase the number of prisoners,
of whom there are many on the account of conscience already.

There was a suffering case and complaint of some of the people called Quakers,
concerning an undue execution of the late Poll-acts,
by distraining the goods of certain persons, as preachers, or ministers,
for twenty shillings quarterly, who had no contributions or wages for preaching;
with some reasons against such execution,
humbly presented in print to the members of Parliament,
requesting the prevention of the like suffering for the future.

There being a clause in a late Poll-act, which runs thus:
"`Every clergyman not being a lord spiritual, having or receiving, in or by,
any benefice or contribution or otherwise, sixty pounds by the year, or upwards;
and every preacher or teacher, in any congregation whatsoever,
not having taken orders according to the discipline of the Church of England,
other than French Protestants, shall be charged, and pay twenty shillings quarterly.`"

These last words relating to every preacher or teacher,
being general and without limitation,
or mention made of any profits or contribution received by such preachers,
proportionable to raise such tax upon, advantage has been taken from there,
on a literal construction by some commissioners and assessors,
to extend the same to the great injury of many persons,
as preachers among the said people, who have no profits, gain, or contribution at all,
on that account.
Which severity we conceive to be both contrary to the just intention of the Parliament,
and to the equity, tenor, and coherence of the said act in its other parts.

Of which said suffering in this case, by execution of the said Poll-act,
about thirty instances of sufferers were subjoined for proof.

When the said Poll-act was near expiring,
the Parliament ordered a new one to be drawn up, or the old one renewed in the year 1695,
and many of our friends were still liable to suffer, as before they did,
upon the old Poll-act,
(the same clause being recited in the bill for the new one) some of us,
particularly Thomas Lower and myself,
renewed the remembrance of our said suffering case and complaint,
to several eminent leading members of Parliament,
and acquainted them how undeservedly many of our friends had suffered as preachers,
by a mal-administration of the said Poll-act, when they have no profits, gain,
or contribution at all on that account.
We convinced some of them how incoherent it was to the tenor and equity of the said act,
that persons that had no gain or profit for preaching,
should have a tax of four pound per annum laid upon each of them, equal to a clergyman,
having, or receiving sixty pound per annum, or upwards.
Whereupon I proposed a brief emendation to the aforesaid clause,
in order to defend our friends from the undue imposition of the tax as preachers,
and for prevention of the like suffering for the future.

The amendment I offered to be inserted in the bill and clause following was this:

[quote]
____
And every teacher or preacher in any congregation whatsoever,
(receiving ten pounds per annum, or upwards) not having taken orders,
according to the discipline of the Church of England,
(other than French Protestants) shall pay twenty shillings quarterly,
at the several days before mentioned;
and none of the said last mentioned persons so charged, to be further charged,
or pay as a gentleman, or reputed gentleman.
____

The words I proposed to be inserted in the said clause, (namely,
receiving ten pounds per annum,
or upward) I desired them to insert in the bill before it was enacted,
and some leading members were quickly convinced of the reasonableness thereof,
as William Lownds, Esq., who drew up the bill, Sir Christopher Musgrave,
and several others, to whom I applied particularly.

I proposing ten pounds per annum, in relation to dissenting preachers,
though that might seem to pinch harder upon us than other preachers,
who as teachers or preachers, receive sixty pounds or upward per annum,
and might better pay twenty shillings quarterly, than we who receive no contributions,
wages, or profits, for preaching or teaching;
yet considering how clear our ministers are in this case,
from making the gospel chargeable,
and how free they are from making a gain of their hearers for preaching to them;
it being our principle and practice to preach the gospel freely,
as Christ our Lord commanded, and not for any worldly profits, or filthy profit,
I was the more ready to offer what I did then in this case,
in order to give the design of charging any of us as preachers, a short turn,
that we might not have twenty shillings quarterly imposed upon us, for teaching,
or preaching the gospel freely, as we do.

My said proposal for an emendation being approved of as reasonable, took such effect,
that our ministers were not taxed in that last Poll-act, 9th and 10th W. 3. 1695.
Nor did they suffer thereupon, as many of them had before upon the other Poll-act.

I was still thankful to the Lord our God,
when I was in any measure instrumental in obtaining some ease to our friends and brethren,
or in preventing further oppressions and sufferings, which they might be liable to,
by undue or mal-administration, if not timely prevented.

[.asterism]
'''

[.embedded-content-document.letter]
--

[.blurb]
=== To the Czar of Muscovy, when in England. A salutation of Christian love, from certain persons commonly called Quakers.

[.salutation]
May it please you, O great Czar!

We heartily wish you tranquillity,
health and happiness in this life and that which is to come,
having true love and good will to you, and all people in your dominions.

We are a people loving and fearing the Most High God, who rules in the kingdoms of men:
and because we have trembled at his word and power,
as his prophets and servants of old did, being humbled under his mighty hand,
we are commonly called Quakers, though under the sincere profession of Christ Jesus,
in the life and purity thereof, worshipping the true God in the Spirit,
and having no confidence in the flesh.
In the love of our God, we give you this good and necessary counsel:

Do you love and fear the Lord God, who is your Maker and Preserver, who gives life,
breath, and being to all mankind.
O, fear to offend him; he has extended great love to you and all men,
in sending his dear Son, Jesus Christ, a light into the world,
and in giving all men light and grace to guide them in his way of truth,
righteousness and peace, unto everlasting salvation and felicity.^
footnote:[John 1:4,9, John 3:16,19, John 8:12, John 12:46, Acts 12:47,
Luke 1:75,79, Luke 2:32, Ephesians 4:7.]
And it is by Him, who is the wisdom and power of God,
that kings reign and princes decree justice: and they, as well as all other men,
are accountable to the just and holy, and all-seeing God, for all their ways and actions,
and by him must be rewarded accordingly: and know,
that he who rules over men must be just, ruling in the fear of God;
and then he shall be as the morning without clouds, when the sun rises.

Oh!
Czar!
The great God requires of you, to do justly, love mercy, and walk humbly before Him,
who is a God of knowledge, and by whom actions are weighed,
and who is the righteous Judge of all.

We pray you, observe the good resolution of that great king Artaxerxes,
when he was made lord over many nations,
he would not exalt himself by reason of his power,
but proposed with equity and gentleness, always to govern his subjects,
and wholly to set them into a peaceable life,
and thereby to bring his kingdom into tranquillity.

And know, that it is by mercy and truth that the thrones of kings are established,
and that thereby you may obtain mercy and favour with the Most High God,
and gain the real love and affections of your subjects.
O be tender and merciful to them all, as they are all your fellow creatures,
created by one God: break off your sins by righteousness and showing mercy to the poor.

And let the example of our renowned king William,
influence you to the like moderation and clemency throughout all your dominions,
which he has showed, in granting free liberty of conscience,
in the peaceable exercise of religion and worship towards Almighty God,
as they may be persuaded by him who is the Sovereign Lord over the consciences of men.

From your real well-wishers, and friends to your immortal soul,
who desire your everlasting happiness.

[.signed-section-closing]
Signed,

[.signed-section-signature]
George Whitehead, Thomas Lower, John Vaughton, William Penn, Francis Camfield.

[.signed-section-context-close]
London, the 23rd of the Twelfth month, 1697-8.

--

When it was agreed among friends that some of us should visit the Czar,
the contents of the foregoing paper were presented to my view,
as very fitting to visit him with such a just Christian testimony;
and I had true ease and satisfaction in spirit, in drawing up the same;
yet it was some time before we could pitch upon an opportunity to go to him,
in order to visit him, as I find, it was in the second month, called April, 1698,
5th day, that we took boat in the morning for Deptford,
where the Czar then had his palace.
When we came, we sent up to him in his chamber, to know his pleasure,
if he would admit us into his presence to speak with him, and we waited for his answer;
which, when it came, was of this import,
That it was not fitting to speak with him at that time, he was not well,
or under some indisposition of body, or the like.
We understood the meaning thereof, as what such great persons are incident to,
who do not keep within the bounds of temperance and moderation,
in their manner and course of living.

Seeing we could not then be admitted to speak with the Czar himself,
we declared the intention of our coming to a great person or prince, who attended him,
and left our paper with him to deliver to the emperor,
which he seriously promised us he would do; who appeared a very fair, discreet man.
So not doubting but the emperor would have our paper safely delivered him,
and a fair account of us, we returned in peace.

There were some priests in the county of Norfolk,
who appeared very invidious against us and our liberty of religious exercise,
being instigated by our old apostate and adversary, Francis Bugg,
having what assistance he could afford them,
they must needs have a public meeting with some of our friends at West Deerham,
in their parish church, so called,
where some of our friends of London and of the country, met them at the time appointed;
and though the priests had gotten many of our friends`' books together,
and endeavoured to render them obnoxious, yet they gained no advantage against them,
but were disappointed of their evil designs;
which were for some pretence to incense the people and the
government to raise a new persecution against us,
as hereafter is made more obvious.
I intended to go that journey into Norfolk, to meet them,
but was prevented by a sudden indisposition and weakness of body,
which remained for some days, till the Lord was pleased to recover me.

However, the said Norfolk priests, in pursuit of their invidious designs and attempts,
published two calumnious books, entitled, 1. A Brief Discovery, etc.
2+++.+++ Some few of the Quakers`' many horrid Blasphemies, etc.;
which they delivered to the Parliament:
the priests chiefly concerned against us in the said books,
that they might appear men of note and learning,
gave their names and distinctions in the title page of their said Brief Discovery,
in this order: Edward Beckham, D. D. and Rector of Gaytenthorp; Henry Meriton,
Rector of Oxborow; Lancaster Topcliff, L. B.,
sometime Senior Fellow of Gonvil and Caius college, Cambridge; all of Norfolk.

The said L. Topcliff, also styled himself Rector of Hockwold in Norfolk.

These priests thought to do great matters against the people called Quakers,
by most falsely and maliciously rendering their principles blasphemous and seditious,
etc., wherein they were sufficiently detected and refuted, in two books which I wrote,
in full answer to them and their most bitter and unjust charges against us and our principles.

One of my answers to them is entitled, Truth and Innocency Vindicated,
and the People called Quakers defended in Principle and Practice,
against invidious attempts and calumnies, etc., printed 1699,
and delivered to members of Parliament, in order to wipe off the priests`' calumnies.

The other answer I put forth is entitled, Truth prevalent,
and the Quakers`' discharged from the Norfolk Rectors`' furious charge,
in a sober answer to their book falsely styled,
The Principles of the Quakers further shown to be Blasphemous and Seditious,
printed in 1701.
Which though it be large, several of them were delivered to members of Parliament,
and I delivered some of them myself.

Yet the implacable enmity of the said priests, and their assisting agent, Francis Bugg,
and others of their abettors, was such,
that their persecuting us with gross aspersions and calumnies in print,
would not appease their wrath; but they got an invidious petition framed against us,
which they intended to present to the House of Commons; in order to which,
the two knights of the shire were instructed to move the said petition in the House;
two priests, namely: John Meriton and the said Lancaster Topcliff,
attending and soliciting for some time,
to have their petition moved and promoted in the House, but were disappointed therein,
and their persecuting purposes justly frustrated.

For I having obtained a copy of their petition,
showed it to several leading members of Parliament,
and how greatly the design thereof tended to raise a new persecution,
and to make void the toleration and liberty of conscience,
granted and legally settled by the government.
They were made sensible thereof, and resolved to oppose the said petition,
and to throw it out with contempt, if it came to be moved in the House,
asking me in whose hands it was; I told them, in the hands of the two Norfolk knights,
with whom I various times discoursed about it,
to show them the nature and tendency of the petition,
and how greatly we were misrepresented in it.
They understanding that many eminent members in the House were set against it,
were in a strait, and intimated thus much to me,
that the clergy and some of the gentry of their own county of Norfolk,
were earnest with them to present the said petition;
but perceiving it would be rejected and thrown out, it brought them under that strait,
that they must either displease those of their own county, who chose them,
or the House of Commons.
I told them it was an unthankful office that was put upon them: they confessed it was.
However I said, we did not solicit them to prevent their presenting,
or moving the said petition in the House; but if they were disposed to present it,
we desired the justice of them to give us some previous
notice of the time when they intended to move it,
that we might attend in readiness to answer for ourselves,
to those charges that were against us in the petition.
This was fairly granted by them; however, upon their deliberate consideration,
the petition was prudently dropped, and not moved in Parliament.

[.offset]
A copy of the said petition follows:

[.embedded-content-document.letter]
--

[.blurb]
=== To the House of Commons: Norfolk petition of justices and grand jurors.

We cannot without resentment,
take notice of the great growth and daily increase of the Quakers,
and the mischiefs and dangers from there threatening this nation.

It is observable with what restless zeal their deluding teachers and, as we suspect,
many Romish emissaries under their disguise, ramble into all parts of these kingdoms,
and boldly spread their venomous doctrines everywhere;
attempting to infect and shake the minds of weak Protestants,
and assuming rules of discipline, powers in matters of religion, and forms of government,
repugnant to the established laws of this kingdom,
contrary to the very acts of toleration, and not allowed by any other dissenters;
vouching all their actions by divine inspiration for their warrant;
and the indulgence of the government for their indemnity.

How apparently their blasphemous books and pernicious
principles tend to subvert the fundamentals of Christianity,
and undermine the civil government, are sufficiently demonstrable;
the publishing whereof, by pretended permission of the government,
is of most dangerous consequence.
The prayer is, to take these things into consideration, that,
with whatsoever tenderness to the persons and estates of these people,
their said principles and practices may be strictly examined and censured, or suppressed,
as they shall appear to deserve, and as in your great wisdom shall seem expedient;
and that the true Christian religion may be preserved from popish superstition,
and unpolluted with enthusiastical innovations.

--

I shall not need to make any large comment on this petition,
to evince the nature and tendency thereof;
it being self-evident to proceed from a spirit of persecution and invidious prejudice,
and is full of old, bitter, refuted calumnies,
always made a cloak and excuse for persecution,
against the most sincere professors of Christianity and religious reformers.
I need say the less to it now,
since it was so illy resented by the most sensible
and judicious representatives of the House of Commons,
that it was not permitted to come to life or birth in that house.
And the same calumnies and unjust insinuations and charges contained in the said petition,
being maliciously cast upon the Quakers, in several books and pamphlets of Francis Bugg,
and the three Norfolk priests before mentioned, were fully answered,
detected and refuted, by me and some other friends;
and particularly the said petition out of Norfolk,
and another petition of the same kind from Bury in Sutfolk,
in a reply on behalf of the people called Quakers, to two petitions against them,
the one out of Norfolk, the other from Bury in Suffolk, printed 1699,
being some brief observations made on those petitions,
and humbly tendered to the consideration of the House of Commons,
to whom those petitions were directed.

And that it may further appear what a malicious spirit was
then at work to raise a new persecution against us,
after our liberty was legally granted;
I think fit to add a copy of the said petition from Bury, which is as follows:

[.embedded-content-document.letter]
--

[.blurb]
=== To the honourable the Commons of England, in Parliament assembled; the humble petition of the aldermen, assistant justice, and chief burgess and burgesses of the common council, in behalf of themselves and the other inhabitants of the borough of Bury St. Edmonds, in Suffolk.

Humbly shows, That we considering all ancient heresies,
which have vexed both church and state,
were never so formidable in their rise and progress, as are the Quakers;
we have too just a cause of dreading the subversion of our government by them,
if not carefully prevented and suppressed, being in their clandestine constitutions,
opposite to the condition of our established policy, and in their principles of faith,
anti-Christian; of government, antimonarchial; in points of doctrine, anti-scriptural;
and in practices, illegal; having their weekly, monthly, quarterly, and yearly meetings,
which we cannot but reasonably believe, tend not only to the subversion of our laws,
but of our religion also, to us of greater concern than our lives.

We therefore, obliged in duty to God and our country,
do humbly pray your timely consideration of our jealousies, and remove our fears,
if not by totally suppressing,
yet at least by preventing their after growth and increase among us:
that our posterity may untroubled live, by this early care of our laws and liberties,
and we enjoy the wished for happiness of a peaceful life.

--

I need not make any larger remark on this petition, than on that from Norfolk,
it being a plain indication of the like envious and persecuting spirit.
The old popish clamour of heresies and heretics, etc.,
against the conscientious reformers and Protestant martyrs,
being always such brands of infamy as were designed to introduce persecutions,
to suppress and destroy the most conscientious and sincere Christians:
such clamorous defamations were bruited abroad by the persecuting, popish hierarchy,
against the reformed Protestants and Protestant martyrs of old,
to excuse their cruelties against them.

Although these aldermen of Bury,
were wheedled or seduced to patronize such a foul and invidious
petition against the people called Quakers,
I do not believe that they could prove any one of
their various charges from their own knowledge,
if they were asked one by one, upon the particular matters of fact,
as they stand charged against the people called Quakers;
neither can we think they are so frighted with the Quakers,
or so afraid of them as they would seem to be.
One would think they should have had better knowledge of
the innocency of their neighbours by the time of their petition,
than to render them so odious, so formidable, yes,
seditious and obnoxious as their said petition very unjustly represented them.

However, one good turn was observable,
that the Suffolk representatives showed more moderation and prudence,
than either to solicit for, or promote the said Bury petition in Parliament;
they showed more discretion therein, by dropping it,
than the aldermen or common council of Bury did,
in patronizing or countenancing such a bitter, invidious attempt.

I remember several of the Suffolk members of Parliament were against the Norfolk petition,
and expressed their dislike of such persecuting dispositions,
which were so repugnant and contradictory to the
toleration and religious liberty of conscience,
granted and settled by the king and government.

Before we could get our answers to the three Norfolk priests`' books,
prepared and printed for the Parliament,
it was thought fitting the following short paper should be delivered in print,
in order to moderate the spirits of those whom they endeavoured
to prepossess with prejudice against us and our Christian principles.

The endorsed title on the outside of our said paper was,
"`The Quakers`' modest observation upon the three
Norfolk clergymen`'s and Francis Bugg`'s books.`"

The title on the inside: "`The three Norfolk clergymen`'s brief discovery, etc.;
presented by them to the king and Parliament against the people called Quakers,
modestly observed to our superiors.`"

[.embedded-content-document.paper]
--

It does not surprise us to be evilly entreated,
and especially by those that have an interest in doing it.
But if conscience prevailed more than contention, and charity overruled prejudice,
we might hope for fairer quarter from our adversaries.

But such is our unhappiness, that nothing less will satisfy them,
than breaking in upon the indulgence that we enjoy,
if they could persuade the government to second their attempts to a new persecution.

In order to which, we perceive they have been hard at work to pervert our books,
violate our sense, abuse our practice, and ridicule our persons;
knowing very well with whom they have to do, and that the patience of our profession,
is their security in abusing of it.

However,
if it has weight enough with our superiors to expect
a fresh defence of our principles and practices,
we shall, with God`'s assistance, be ready for their satisfaction,
once more to justify both, against the insults of our restless adversaries;
who otherwise, we take leave to say, would not deserve our notice:
since we have already repeatedly answered their objections in print,
and think it our duty, as well as wisdom,
to use the liberty the government has favoured us with,
in as peaceable and inoffensive manner as may be.

[.signed-section-signature]
George Whitehead, John Vaughton, John Fiddeman, Henry Gouldney, William Penn, John Field,
John Bellers, Joseph Wyeth.

--

The priests in our days have made a great noise for tithes and offerings, etc.,
and the envy and persecution of many of them, against us,
is chiefly for refusing to pay the same,
which is purely for conscience sake to our Lord and Master Jesus Christ.

As to the priests`' claim of tithes, oblations and obventions,
we find no warrant in holy Scripture,
that Christ`'s gospel ministers ever made such claim or demand, but the contrary.

I have had many discourses with bishops and others of the clergy,
and I never met with any of them that could maintain
their plea for their pretended divine right to them,
under the new covenant dispensation; nor yet for ministers to force maintenance,
wages or hire from their hearers;
both being contrary to the new covenant dispensation and ministry,
and repugnant to Christ`'s express commission and precept,
and to his ministers`' practice.
Tithes as well as offerings or oblations were abolished and ended by Jesus Christ.

Their flying to human and popish laws for their claim to tithes,
is but a weak shift and mean subterfuge,
and a giving away the cause of their pretended spirituality and priesthood,
on which their claim of divine right is grounded,
and consequently thereby they unpriest themselves;
Christ having put an end to both the priesthood, old covenant and law,
which did enjoin the payment of tithes to the Levitical priesthood.
Wherefore the priests`' said claim now is to set up human
authority and laws above Christ Jesus`' divine authority,
and law of the new covenant; which appears not only repugnant to his crown and dignity,
who is Lord of lords, and King of kings,
but also inconsistent with the true Christian profession,
whereof Jesus Christ is our great High Priest and Apostle;
to whom be glory and dominion forever.

=== The Conclusion.

Manifold exercises, trials,
and tribulations has the Lord my God supported me under and carried me through,
in my pilgrimage, for his name and truth`'s sake,
more than could possibly be related in this history; having spent a long time,
even the greatest part of my life, from my youth upward, in the testimony,
service and vindication of the living, unchangeable truth, as it is in Christ Jesus,
my Lord; for whom I have suffered many things, both in body and spirit,
as also by reproaches and calumnies, and sincerely laboured in his love,
who has supported me, and hitherto helped me in the gospel of the grace of God,
and of his dear Son Jesus Christ, even the gospel of life, salvation and peace,
to them who truly believe:
and yet I esteem not all my sufferings and afflictions
worthy to be compared to the glory set before me.
For all which, I must ascribe blessing, honour, glory, power,
and dominion to the Lord God, and the Lamb upon his throne, forever and ever.

And when, by the grace and assistance of my heavenly Father,
I have finished the work he has given me to do;
I firmly believe and livingly hope in the Lord, I shall die in the Lord Jesus Christ,
and ever live with and rest in him, in his heavenly kingdom,
O my soul! enter into your rest, even your eternal rest, from your manifold labours,
travails and sufferings; for the Lord your God has dealt bountifully with you:
glory to his excellent name forevermore.

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
Concluded, London, the 18th of the Sixth month, 1711.
