== Chapter IV

In the same year and summer of 1657,
I travelled and laboured much in the gospel ministry in the several counties of Nottingham,
Derby, Leicester, Warwick, and in Staffordshire, and other parts;
and visited many meetings in the love and good will of God,
of which I had through his dear Son, received a true and living sense and experience,
whereby I was strengthened and supported in great
labour in the work of the ministry of the gospel;
and in which love my service was very acceptable
where I travelled among Friends and friendly people,
I met with little opposition, disputes or controversies from adversaries,
after those I met with in Gloucestershire, Worcestershire,
and once at a meeting at Lemster in Herefordshire, at the latter end of the meeting;
and at a meeting in Warwickshire, where a fierce Baptist began a contest about the Word,
but made little of it;
for it was observable how impertinently he opposed
our asserting Christ to be the Word of God,
which was in the beginning.
And consequently, that the Word was before the Scriptures were written.

Against which the Baptist made exception from Christ`'s parable and construction thereof.
Matt. 13:19-4. Mark 4:15-4. Luke 8:12-5;
concerning some seeds which fell by the way side, which the fowls came and devoured;
that is.
When any one heareth the word of the kingdom, and understandeth it not,
then cometh the wicked one and catcheth away that which was sown in his heart; or,
the devil cometh and taketh away the word out of their hearts,
lest they should believe and be saved.

Hence it was objected, that the devil could not take away Christ out of their hearts.
And what then?
Neither is it said the devil taketh away the Scriptures out of their hearts,
or that the Scriptures were sown in them, or in those several sorts of ground.
Parables are not to be taken literally, nor always to be strained to a literal sense.
Though the devil cannot catch away Christ out of men`'s hearts,
he can catch away loose and ignorant hearers`' hearts from the sense of the Word preached,
when touched therewith, that they may not believe and be saved;
which is too common among forgetful, barren hearers.
And all that can be argued from thence can never prove that the Word is not Christ,
for that is to contradict John 1:1; or that Christ is not the Word preached,
for that were to contradict his ministers, who preach Christ the living, eternal Word.

I had sometimes heard of one Rice Jones,
and that he was at first convinced of the truth testified by George Fox;
but soon turned aside against him and Friends,
and gathered a separate meeting to himself, which some people termed proud Quakers,
he making them believe he was divinely inspired,
so as to open the spiritual sense of the Scriptures.
They kept their meetings at the castle at Nottingham.
When I was there on a first-day of the week,
I was concerned to visit them at their meeting, where I sitting a while,
and observing the manner of their exercise,
and their attending to hear Rice expound Scripture to them;
and seeing how dead and empty their devotion or exercise was,
I was moved to bear a plain testimony against their deadness;
not waiting to feel the power of the Lord to quicken them unto his spiritual worship,
or to the same purpose and effect: and I had some discourse with Rice,
upon which he seemed somewhat down in his spirit, and stopped from going on that time.

A woman present, who appeared to be a sober and chief hearer,
seemed somewhat offended at my discourse with him.
She said to me, "`I saw a simplicity in you after you came among us,
but now the subtlety
is got up in you;`" whereby she seemed to aim at,
or own simplicity.
However, my spiritual, living testimony then borne among them,
had so much effect upon that woman and some others,
that they were convinced of the truth,
and left Rice Jones and his meeting and came to Friends; perceiving that,
"`though he had a form, he denied the power of godliness,
and therefore they might well turn away from such.`"

And though the said Rice came to some few of our meetings afterwards,
yet I never heard that he came to any true settlement in his mind,
in the light or power of truth, or to a real love to Friends.
It is not men`'s professions or notions, gathered merely from the letter;
but the spirit that begets true love, amity and unity.

Having laboured in the gospel work in the counties and places before mentioned,
and had many large meetings without doors that summer; and being,
after my confinement and hard usage in prison in Edmundsbury, as before related,
toward the latter end of summer, at a meeting without doors at Leicester, on a first-day,
I became somewhat weak in body, and was taken sick of a fever,
through some cold that had seized upon me,
insomuch that I was at times very sick and weak, so that my recovery was doubted.
When the disease was at the height, or thereabouts,
the Lord showed me that he would restore and raise me up again;
my work was not yet done--I must yet live to bear testimony against the covetous priests, etc.
This was so clearly and powerfully revealed and shown to me,
that I was immediately revived thereby; and certainly believed,
what I had cause before to question,
that the Lord would restore me to health for his name and work, and people`'s sake.

The next morning I told some Friends where I lay,
how the Lord had that night discovered to me that
he would raise me up and restore me to health.
My work was not done, he had yet more work for me to do;
I must further testify against the covetous priests.
The Friends who heard me were very glad; and my health sprang up so speedily,
that I recovered and grew better and better, and increased in strength every day;
the time of that sickness being about two weeks before I recovered.
The place where I lie that time, was at a town called Whetstone, near Leicester,
at Thomas Pauley`'s or Parley, who with his wife, were honest, loving Friends.

Quickly after my recovery,
I travelled again in the work and service of the
Lord through part of Warwickshire and Coventry,
and northward through Yorkshire,
visiting meetings as I could conveniently in my journey toward my own county,
Westmoreland, the summer being then well nigh over and winter approaching.

I had several good meetings in Yorkshire,
and got well to my parents`' house in Westmoreland, to whom I was very acceptable,
and received with great joy and kindness, having been above three years absent from them.
In that space of time I was known to have suffered great hardships under persecution;
so that I was to them as one risen or come from the dead,
for they had esteemed me as one lost or dead, as it was in a contrary case to mine;
"`This my son was dead, and is alive again;
he was lost and is found,`" Though I never was a prodigal, yet accounted as one lost,
until the Lord gave them a better understanding who had so thought of me.

In the time of my three years absence, the Lord secretly, by his power,
removed those prejudicial and hard thoughts out of the hearts of my parents and relations,
which the priests had at first influenced them with, concerning me and my friends,
the people called Quakers.
I was and am still fully satisfied, the Lord did secretly plead my innocent cause,
after I was rendered as a miserable object, and given over for lost and undone;
yet through all the Lord gave me faith and patience to bear all,
and to outlive many oppositions, trials and exercises, as well as hardships;
glory to his excellent name and power forever more.

Being returned into my native county,
I had good opportunities to visit Friends at the several meetings which I had frequented,
and where I was most known before I travelled abroad in the work of the ministry;
as Sedbergh, Grayrigg, Kendal, Ravenstondale, and Strickland meetings,
and those parts in Westmoreland, etc., where I was joyfully received, and my ministry,
given me of the Lord, very acceptable and to the great comfort of many innocent Friends,
in whom their first love was fresh and lively,
and which they retained to the end of their days.

I also rode over the sands to Swarthmore, in Lancashire, to judge Fell`'s,
to visit Margaret Fell and her family, and the meeting of Friends at their house;
where we were comforted together in the Lord,
and in the great love and unity which our Friends there, and in those parts were then in.

I also visited Friends`' meetings through Cumberland,
where I had not been conversant or much known before that journey;
yet Friends being very loving in that county also,
they very kindly received me and my testimony and service
for the Lord God and his blessed everliving truth;
he having made me zealously concerned for the promoting and spreading thereof,
as well as he had enabled me to endure great suffering and hardships for the same.

I remember in those days.
Friends in the west part of Cumberland kept their meetings without doors,
at a place on the common called Pardsay Cragg,
not then having convenient house room to contain the meetings.
It was very cold, stormy, snowy and sleety weather,
at one of the meetings which I had there on the said Cragg;
but as there are several sides of it, where sheep may shelter from the wind and storm,
so Friends commonly took the same advantage to meet on the calmest side.
And truly several good and blessed meetings I had at the said Pardsay Cragg,
without doors, both in the winter and summer times, and some within doors,
since our friends got a meetinghouse built there.

Likewise our friends of Strickland and Shapp, and that side of Westmoreland,
kept their meetings for some years on the common, both winter and summer,
until they got a meetinghouse built at Great Strickland.
Our friends in those northern counties were greatly
enabled to bear the cold and all sorts of weather,
when they had their meetings on the commons and mountainous places,
for several years at first.

It rained most of the time at some meetings, and we have been very much wet;
yet I do not remember that ever I got any hurt thereby,
the Lord so preserved and defended us by his power; blessed be his name,
who enabled me and many others, to stand and to bear divers kinds of storms and winds.

I travelled the former part of the winter, 1657, in Westmoreland,
and also into the county of Durham to Newcastle and Northumberland,
and thoroughly visited the meetings of Friends in those parts, and at Berwick upon Tweed;
and returned back to that called the Holy island, by the sea side.
The wife of the governor of the garrison or fort there, was a Friend; Richard Wilson,
a Friend of Sunderland, accompanying me to Berwick and back again.
We were kindly received in that island, both by the governor, captain Phillips,
as they called him, and his wife; and that evening I had a meeting in the castle,
with the family, where the garrison was kept, and among the soldiers,
who were civil to us.
We lodged there that night, being kindly entertained;
and the next morning the governor sent his man to guide us over the sands;
being then convinced of the truth, he did the more manifest his kindness to us,
and became a Friend; and some time after, he and his wife removed into Oxfordshire,
to Banbury side, and so far as I know both continued Friends to the end.

In our return through Northumberland I declared the truth,
and warned the people in several towns to repentance and amendment of their lives.
Particularly in one town where they had a piper playing, and people about him dancing,
by a hay stack in a yard; I rode up to them,
and in the dread of the Lord warned them to repentance.
The piper ceased playing,
and he and the people present heard me quietly till I had cleared my conscience,
and then parted peaceably from them.
But few Friends or meetings were then in that county.
As we travelled to Berwick and back again,
it was hard for us to get lodgings in some places,
particularly at Alnwick and one other place in our return;
we had but a small meeting of Friends at Berwick.
Our loving friend John Dove, and his wife and family at Whittlesey,
kindly received me at his house, and at Northshields and Tynemouth,
I had a meeting in each place.

Great endeavours were used for us to have meetings in Newcastle upon Tyne,
while I was in those parts; but the mayor of the town, influenced by the priests,
would not suffer us to keep any meeting within the liberty of the town;
though in Gateside, being out of the mayor`'s liberty,
our friends had settled a meeting at our beloved friend Richard Ubank`'s house.

The first meeting we then endeavoured to have within the town of Newcastle,
was in a large room taken on purpose by some Friends;
William Coatsworth of Southshields with other Friends,
being zealously concerned for the same.
The meeting was not fully gathered, when the mayor and his officers came,
and by force turned us out of the meeting, and not only so, but out of the town also;
for the mayor and his company commanded us,
and went along with us as far as the bridge over the river Tyne,
that separated Newcastle and Gateside; upon which bridge there is a blue stone,
to which the mayor`'s liberty only extends;
when we came to that stone the mayor gave his charge to each of us in these words, viz:

"`I charge and command you in the name of his highness the lord Protector,
that you come no more into Newcastle, to have any more meetings there, at your peril.`"

On a first-day after, we met again within the liberty of the town of Newcastle,
without doors, near the river side,
where the mayor`'s officers came again and haled us away out of the liberty,
on the bridge as before; and in Gateside we could enjoy our meetings peaceably,
for which we were thankful to God.

Being thus forcibly disappointed of keeping any meetings within the liberty of the town,
some Friend or Friends, agreed with the man that kept the Guild-hall, or shire-house,
to suffer Friends to have a meeting therein, it being without the liberty of the town.
Although the keeper of the hall had agreed for the price,
the priest of the town interposed to prevent our meeting after it was appointed there,
and persuaded the keeper to break his word and bargain made with our friends;
and to keep them out of the house he had agreed they should meet in,
the priest giving him half a crown to go back from his bargain--as we had account given
us--for the said keeper was constrained to show the cause of the breach of his agreement,
in keeping us out of doors.

Being thus disappointed of the house,
after the meeting had been beforehand appointed and the time fixed,
we were necessitated to keep the meeting without doors,
on the side of the hill near the shire-house, being without the mayor`'s liberty.

It was so ordered of the Lord, by his over ruling power,
that we had not only a large meeting of a great concourse
of people besides our own friends,
but it was also kept quiet,
and the spirits of the people subjected and brought under
by the power and prevalency of the truth and gospel testimony,
which the Lord our God gave me strength to bear in that meeting, in power and authority,
for a considerable time, I believe, for two or three hours together;
and my voice was raised to that degree,
that some said I was heard from the side of the castle hill over the river Tyne,
into Gateside, which ascends opposite to the other.

And considering, that besides many people soberly inclined who resorted to the meeting,
there was also a great concourse of loose, rude and ignorant people,
it was by the great mercy and providence of God the
meeting was kept in such a quiet state,
especially seeing the priests and the mayor were so much set against us,
as not to suffer us to have a meeting within the liberty of the town,
nor without the liberty within doors, where a priest could fraudulently prevent,
as in the case of the poor man who was persuaded and bribed to break his word and bargain.

The peaceable posture, order and end of the meeting were greatly to our comfort,
who were concerned for the promotion of truth therein,
and it was to Friends`' great satisfaction.

I remember the care of some persons that were present,
some of whom seemed to be in office, to go along with me,
and see me secured out of the hands of the mob, when the meeting was ended,
and as I went along through part of the town of Newcastle.

That day`'s work and service is to me very memorable, as it was remarkable;
and the fresh remembrance of the goodness and power of the Lord,
my strength and help in his own work and service, is still matter of comfort to me;
and the more,
in that I have a living sense of the continuance of the same divine goodness,
love and power of the Lord God with me still,
that did assist and help me through deep sufferings,
trials and weighty undertakings in his service, for his holy name and blessed truth sake.
O my soul, bless thou the Lord, and let all that is within me praise his holy name,
for his mercy endures forever.

About the time when we were disappointed of having meetings in Newcastle,
being turned out of the town by the mayor, as related,
there fell out a sorrowful occasion and trouble to many Friends, as followeth:
The aforesaid William Coatsworth being zealous for procuring a meeting in Newcastle,
and being disappointed, he let in too much grief and trouble of mind,
insomuch that it did somewhat discompose him,
so that in a hurry he took horse to ride to London in all haste,
to speak to Oliver Cromwell, Protector,
to complain and make his case known against the mayor of Newcastle, as was supposed:
but when got to Durham, he was stopped at his father-in-law`'s, John Joplin.

Being seen to be in some discomposure where he was detained,
and brought under the hands of physicians, they gave him physic several times,
until he was near his end;
some reported he had physic given him within an hour before he died,
though he had before denied the use of such carnal means, as he termed them.

Before he died he was better composed,
and became so sensible as to declare several things for the clearing of the truth,
and taking the blame upon himself, wherein he had missed his way and committed error,
confessing to the just judgments of God which had been upon him;
telling his father-in-law and mother Joplin,
"`It is the just judgment of God to bring me hither to lay my shame open among you.
Father and mother, I feasted and rioted with you,
and when you were light I was light and when you laughed and talked, I did so;
and so betrayed the simplicity of God in me; poor William Coatsworth!
And though ye were friends to me in the outward,
ye were enemies to the seed of God in me.`"
Poor man, he was made sensible he had not stood in the cross,
nor been so watchful as he ought to have been.
And it was no doubt a mercy to him that he was made so sensible before his end.

He spake several times of George Fox,
and said he was tender over the simplicity of God in him;
and that Richard Farnsworth bade him labour to be little--little in his own eyes;
"`But,`" said he, "`I could never get to be little, little in my own will.`"
These things I had from several Friends that were with him;
he died in a few days after he stopped at Durham, on the 8th day of the eleventh month,
1657.
His example may be a warning to others who are convinced of the truth,
to be low in their minds, little in their own eyes,
and watchful to dwell under the power of the cross, to their own wills and runnings.

I was truly sorry for his afflicted and distressed widow,
and in Christian compassion visited her, and had a meeting at her house at Southshields,
and for a little time visited other meetings in that county of Durham,
as Sunderland and other places: When I found myself clear in spirit of those parts,
I took my journey to York, and forward pretty directly toward the south,
as the isle of Ely, Norfolk, Suffolk, and Essex, where my service as well as sufferings,
had chiefly been.

After great labour and travel in many parts of the nation, as before related,
in the second month of the year 1658, I was taken sick of an ague and fever,
which began in Essex.
I laboured under it for some days, and had divers meetings until I got into Norfolk,
though in a low condition, insomuch that my weakness so increased,
I was constrained to stay at a Friend`'s house at Dysse, for two or three weeks.
The Lord was pleased to recover and restore me by degrees, to my health and strength,
although I was brought so very low by that sickness,
that my recovery appeared to be by a special providence of God,
who hath been pleased to lengthen out my days for his name and work`'s sake.
By his over-ruling power and merciful providence,
he hath afforded me such manifest preservations, as that neither furious tumults,
stonings, beating, cruel confinements, severe stripes, manifold labours, travels,
nor sickness, have been hitherto suffered to shorten my days;
for the Lord has prolonged them even far beyond my own expectation, many years ago,
as well as to the disappointment of my cruel persecutors`' expectations and desires.
Let my heart and soul in true humility,
bless the Lord our God for his manifold blessings and eminent preservations,
both inward and outward.
Let him have the glory and praise of all, who alone is worthy forever more.

On the 12th day of the fifth month, 1658, as I was riding through the town of Hoxon,
in Suffolk, and meeting with Edward Willan, priest of the town,
I exhorted him to fear God and cease from iniquity.
We fell into some discourse,
wherein the priest accused me with seducing his flock from the church.
Having had a meeting in the town the day before,
I asked the priest concerning Hoxon steeple-house--we
being near it--if that was the church he spake of?
He affirmed that it was the church.
I demanded of him to prove that such a house made
of wood and stone was the church of Christ.
He pretended to prove it was, from 1 Cor. 11:22;
"`Or despise ye the church of God,`" which no way proves the church
of God to be such a house as is made up of wood and stone;
for the apostle in the very same place distinguishes
between their houses and the church of God;
in saying, "`What, have ye not houses to eat and drink in?
or despise ye the church of God?`"
I told the priest that the church of Christ was built
up of living stones:--that he granted;
yet stood to maintain the outward house or fabric, as Hoxon steeple-house,
to be the church; though he acknowledged that house was not built of living stones,
but alledged that when the apostle spake of the church, he spake of the thing containing,
for the thing contained, wherein he wronged the apostle`'s words and sense;
for when the apostle wrote to the church of Christ, or to the church of God,
he wrote to them that were sanctified in Christ, called to be saints, etc. 1 Cor. 1:2.
And to the church which is in God the Father,
and in the Lord Jesus Christ. 1 Thess. 1:1.
It was the sanctified people, the saints to whom he wrote,
not to a house of wood and stone.

I having detected the priest`'s error, he grew angry,
for he appeared both ignorant and envious,
and could not fairly hold an argument with moderation.
In our discourse, his envy and rage rose to that degree,
that he took my horse by the bridle and forcibly held him,
having some of his followers presently to assist him, who, together with the priest,
forced me to go before one Anthony Barry, who was called a justice of peace,
and was a member of an Independent congregation or church, at Silam, near Hoxon,
where one +++_______+++ Habergham was pastor,
who was esteemed a noted minister among that people.

The said Edward Willan the priest,
gave some invidious information to this justice Barry against me,
for calling him persecutor and the like,
which was after he had assaulted me in Ploxon street,
and threatened to pull me off my horse; though it was made apparent to the said justice,
what an ignorant, invidious person the priest was,
and what small and groundless occasion he took against me, to persecute me;
and what a breaker of the peace the priest himself was,
in his assaulting me in the highway; yet to gratify the envy of the priest,
the pretended justice, Anthony Barry,
made a warrant to commit me to the county jail in Ipswich,
under pretence of having reviled the priest,
though he could not prove any law transgressed by me in my discoursing with the priest,
which was fairly and Christianly done on my part.

But justice Barry pretended a law he accused me with the breach of,
which he told us was a late act of Parliament, made for the punishment of vagrants, idle,
loose, dissolute persons, and fiddlers, etc.; which he said, was only for Quakers.
But it could not be true; for it was made against idle, loose, and dissolute persons,
who might properly be termed vagrants or vagabonds.
As for the people called Quakers, I believe there then were, and still are,
as sufficient responsible men among them as himself ever was, if not more responsible,
and of better reputation every way.
And therefore it was very unjust in him to term the Quakers vagabonds or vagrants,
telling us that the said act of Parliament made against vagabonds,
was only made for Quakers, and thereupon to take an unjust,
as well as illegal occasion to commit me to prison.
However, he would make a mittimus to send me to jail,
and they were so hasty to convey me thither,
that they would not suffer me to take one night`'s rest, but being laid down on a bench,
the very same night after I was apprehended, I was hurried away on horseback,
and guarded by some men of the town of Hoxon to Ipswich jail.
We rode most of that night, and got thither a little after sun-rising, it being,
as I take it, above twenty miles.

When I was delivered up to the keeper,
I found three of our friends then in the common jail, where they put felons;
one was William Alexander of Needham, an honest young man, and two other honest Friends,
who suffered for non-payment of tithes.

I was very well content to suffer with such good company in the common ward,
where both the place and our lodgings were but mean,
having no other beds to lie upon than pease straw,
yet we had sheets and bed clothes upon the straw.
John Story, the keeper of the jail,
although he had dealt hardly by George Rose and some other Friends before,
yet he was far more civil to me, and Friends with with me, than Robert Newton,
the jailer at Edmundsbury had been.

I was detained there until the next quarter sessions, and then had before the justices,
where the priest, Edward Willan, and another invidious person, Thomas Yellop,
appeared to prosecute me, who gave a false, partial,
and aggravated information upon oath against me;
that I had reviled the ministry of the Word of God at a meeting at Hoxon.
Yet he confessed in court, that he did not hear me at the meeting, for he was not at it,
but took an envious bailiff, one Thomas Yellop, for his witness,
who swore to the same thing the priest had done against me.
But neither of these prosecutors would discover the
occasion Edward Willan had given against me,
by assaulting me in the highway, only for exhorting him,
and disputing against his erroneous doctrine about the church,
and his demanding tithes or wages for praying for people, as he had before confessed.
He would not inform the Sessions of these things, being conscious of them himself;
but complained of my charging him as a persecutor,
and testifying against his envy and malice, which was Cain`'s way,
and which his own violence and abuse against me did evince he was justly chargeable with.
This he took as a great affront, and reviling him,
having come so far as from Hoxon to Ipswich, to prosecute me upon oath,
which he could scarcely do without trembling, like one under some consternation, guilt,
and great envy and revenge.
Whether to gratify or pacify him, Edmund Harvey and others of the justices,
were pleased to show the priest so much favour as to fine me twenty shillings,
when a jury of ignorant men had brought in their unjust verdict or sentence against me,
according to what the priest had falsely sworn;
though I did clear my conscience in testimony against their
persecution and partial proceeding against the innocent.

Being returned back to prison, I was there detained for some weeks,
until their lord Protector, Oliver Cromwell died, in whose name I was committed, fined,
and detained prisoner, as many others of our friends were in his days,
and his son Richard Cromwell was proclaimed Protector in his place.
In a short time after, my dear friend Robert Duncon,
making application to his uncle Duncon of Ipswich, and to justice Edgar,
or some of the justices on my behalf, I was set at liberty from that imprisonment,
in which I was confined about sixteen weeks in all,
which I esteemed but a small suffering in comparison with what I had undergone before.

I would give a further hint of priest Willan`'s envy and ignorance,
with observations thereupon.
Threatening some persons who were none of his hearers,
to get a warrant from justice Barry for tithes or wages he pretended they owed him,
he was asked in the presence of the justice,
if it was equal a man should receive wages of such as he doth no work for?
The priest answered, "`I pray for all within my parish, or that have heard me,
whether they come to hear me or not.`"

The priest and justice agreed in envy against the Quakers,
though not in profession of religion, the one being a Presbyterian parish priest,
and the other a member of an Independent church,
who pretended to be better reformed and more refined
than those parish priests and their churches were;
pretending to spiritual gifts, as having the spirit of Christ,
and the other not to have that infallible spirit; the one for a parochial church,
without exception; the other for a select church,
better qualified to receive their communion; but in the spirit of persecution,
the priest and the justice were agreed.

Where any minister of Christ demanded tithes or money of any people for praying for them,
we want Scripture proof; nor have we any precedent or example in Scripture,
that any of Christ`'s ministers did sue men at law,
or procure a warrant from any magistrate to force them to pay tithes or wages,
either for preaching to them or praying for them;
for they both preached and prayed freely, as Christ commanded,
by the spirit of Christ Jesus, which they had received of him.

But the said priest Willan confessed that he was not called by an infallible spirit,
and disowned having an infallible spirit in himself.
Whereby he showed that his preaching and praying proceeded from his own fallible,
erring spirit, and not from the spirit of Christ,
which is an infallible and unerring Spirit;
and the Lord is against those foolish prophets that follow their own spirits,
and have seen nothing.
And "`He that hath not the spirit of Christ, is none of his.`"

Now in what a sad case is that people,
and how miserable are they who are led by such blind
guides as follow not the spirit of Christ,
but their own spirits?
and what good will the prayers of those who are none of Christ`'s, do for people?
and what a poor bargain have they who are forced to pay tithes or money for their prayers?
This trade must surely cease and come to an end where Christ comes to be king, priest,
prophet, minister and bishop over the souls of people.

After I was released from my imprisonment in Ipswich,
I had very good and comfortable service in the work of the gospel ministry,
in several places in the country, particularly at Trembly and Waltonside, in Suffolk,
and at Harwich, Manningtree, Colchester, and other places in Essex,
where we had quiet and comfortable meetings; things appearing then for a little space,
pretty easy towards us and our meetings,
upon this new change in government of the Protector, so called.
Still the persecuting spirit secretly remained, and the enmity thereof,
in a sort of professing people and their teachers, against us the people called Quakers,
and our religious meetings.
They would not willingly allow any people liberty of conscience but themselves,
wherein they did not exercise a conscience void of offence, either toward God or men.
Their own self-wills had greater sway over them than any just, equal,
or tender conscience; for that would have had some tender respect to that just,
equal and divine precept of doing to all men as we would be done by;
which these persecutors`' consciences had not, as may appear in the following account.

A meeting of our friends with me, being desired in the town of Ipswich,
some weeks after my release out of prison, and our honest friend, Timothy Grimble,
ship master, and Mary his wife, being willing and desirous we should meet at their house;
accordingly on the 6th day of the eleventh month, 1658,
we had there a good and peaceable meeting for the worship and service of Almighty God,
and manifestation of his blessed truth.
Many sober, honest people met, and the Lord`'s presence was known among us,
but our adversaries in that town being still possessed with
prejudice and envy against us and our innocent meetings,
were uneasy thereat, and minded to stir up persecution in their new Protector`'s name,
to make him culpable and guilty thereof, as the persecutors had done by their old one;
for the mal-administration of inferior ministers,
has often brought reproach upon their superiors in government,
when they have acted in their names.
In pursuance of those persecutors`' invidious designs against us,
to prevent Friends having more meetings in Ipswich,
the following presentment was devised and made against our friend Timothy Grimble.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Ipswich, Suffolk.

The jury for his highness, Richard, lord Protector of the commonwealth of England,
Scotland and Ireland, and the dominions and territories thereunto belonging,
upon their oaths do present, that Timothy Grimble, late of Ipswich,
in the county aforesaid, mariner at Ipswich aforesaid, the 7th day of January, 1658,
and continually after, until the day of the taking this inquisition,
hath received into his house, countenanced, harboured and supported divers dissolute,
idle, loose, lewd and suspected persons, disturbers of the public peace,
to the jurors unknown, commonly called Quakers, of evil conversation;
doth also keep disorder, evil rule and government in his house,
to the great nuisance of his neighbours and other people of this commonwealth,
and against the peace.

[.signed-section-signature]
The names of the said jury:--John Mall, John Hamont, Thomas Wright, Jr., John Donty,
Robert Stebbing, Thomas Grigg, Charles Wright, John Gray, John Jolley, Samuel Humphrey,
Edward Keen, Richard Humphrey, Joseph Haymor, Richard Clopton, Peter Cole, Robert Grows,
Edmund Darby, Thomas Brook, Richard Thurston, William Goodale.

--

An abstract of an answer that was given to the said presentment,
by some Friends concerned.

[.embedded-content-document]
--

Let all sober people observe,
how envious these jurymen and inquisitors have appeared
against Timothy Grimble and his innocent friends.

[.numbered-group]
====

[.numbered]
1+++.+++ Their presentment being grounded and made up of false accusations,
gross lies and slanders.
The meeting that we had at Timothy`'s house,
which was on the 6th day of the eleventh month, 1658, was a peaceable meeting,
for the service of God and his worship, and the holy truth therein held forth;
and no cause thereby given for these jurors or any others,
to be offended at such a meeting, which was both according to the law of God,
and owned by him, and also tolerated by the government.
What enmity and malignity therefore, appears in such a scandalous presentment,
thus to defame an honest man for suffering a peaceable meeting, and entertaining quiet,
innocent people at his house, who ought by law to be protected,
and not punished for the exercise of their religion, or conscience toward God.

[.numbered]
2+++.+++ As for those called Quakers, whom Timothy Grimble received and harboured in his house,
who they say are unknown to the jurors, some of their names are, Robert Duncon,
Robert Grassingham, Joseph Scott, and George Whitehead;
and they are well known to be no dissolute, no idle, no loose,
no lewd or suspected persons, nor disturbers of the public peace,
as they are unjustly defamed and reproached in the
presentment given upon oath against them.
But very well known to be sober, honest persons, and also responsible where they live.

What a large conscience did appear in these jurors,
who could swear against men unknown to them,
and upon oath present them so highly criminal, as being no other than dissolute, idle,
loose, lewd, and suspected persons,
while unknown to these their accusers and swearers against them.

[.numbered]
3+++.+++ We ask you jurors, wherein and when did we, called Quakers,
whom you have sworn against, disturb the public peace?
And what evil conversation can you charge or prove against us?
If you cannot prove the matter of fact charged, and by you sworn against us,
be ashamed thereof.
Surely those magistrates, or that court, that have such a presentment as yours,
ought not to trust your oath to the same,
but to examine you of the particular crimes or accusations charged,
you having grossly and very unjustly defamed Timothy
Grimble and his friends called Quakers,
for which you are accountable.
Let the magistrates inquire of you, what suspected persons he hath harboured continually,
and try you upon what ground you have cast such aspersions upon sober, honest men.
And what disorder, evil rule and government, doth Timothy Grimble keep in his house?
What sober, honest neighbours will say that they are annoyed or disturbed by disorder,
evil rule or government,
kept at Timothy Grimble`'s? Produce your proof for these accusations;
or else like forsworn persons, forever stop your mouths, and let shame cover your lips.
For have you herein acted either like rational men or Christians,
or done as you would be done by?
Would you take it well to be presented or indicted for entertaining your friends,
as you have presented and grossly misrepresented
Timothy Grimble for harbouring his friends?

[.numbered]
4+++.+++ Many can witness, that the meetings we had at Timothy Grimble`'s house in Ipswich,
were peaceable and lawful.
And those priests and professors who were offended at them,
had done more honestly or discreetly if they had come to
our faces in our meetings to have manifested openly,
what lewdness or errors were practised or held forth by any of us, if they could;
rather than to go behind our backs, to instigate the magistrates against us,
without any just cause.
But the deceit of those who have thus acted in the dark against the innocent,
is made manifest to their shame; and the more by grossly abusing innocent people,
as the said jurors and their abettors have done.

[.numbered]
5+++.+++ To swear at all, is a transgression against Christ`'s doctrine.
But to present lies and slanders upon oath, to cause the innocent to suffer,
is a much greater offence,
which these jurors have done against Timothy Grimble and his friends, called Quakers,
who are witnesses against all idleness, disorder, looseness, lewdness,
and evil government whatsoever; though thus the wicked have made lies their refuge,
and like men mad with envy, have forged such slanders against honest men,
as are contained in the said presentment.
So that we may even say with the prophet; '`They that were mad against us,
were sworn against us.

====

--

Thus I have abstracted the substance and greatest part of our original answer,
which was signed by Robert Duncon, George Whitehead, and Robert Grassingham.

[.blurb]
=== George Whitehead`'s letter to the inhabitants of Ipswich, both teachers and people.

[.embedded-content-document.letter]
--

Oh! the pride,
high-mindedness and self-conceitedness which abound in this town of Ipswich!
What feignedness, hypocrisy and will-worshipping are among the professors,
who ignorantly worship an unknown God according to their own wills;
who have gotten words of the saints, and of the Scriptures of truth,
but the light which led the saints they are out of,
and have grieved and quenched the spirit of it,
when it hath appeared in their own consciences to convince them of sin and evil.
So that their sin remains in them,
and the curse of God hath power over them that live in pride, deceit,
superstition and ungodly conversation.

There hath been a zeal stirring for the Lord in several of them formerly,
according to what they knew; but now much deadness, coldness,
emptiness and barrenness is over their spirits,
and unrighteousness hath the preeminence among them.
The teachers have gotten the saints`' words to speak of,
and are painted over with an empty profession, and a feigned humility,
but inwardly are proud, covetous and rebellious--resisting the truth,
and make a trade upon the Scriptures; teaching for hire, and divining for money.
Such the true prophets of God cried against;
"`For they are as women that sew pillows under people`'s arm holes,
speaking peace to the wicked, where there is no peace.
And they are as foxes in the deserts, that are greedy, waiting for their prey.`"
And much willfulness and slavery is in the proud and covetous priests,
and in many of the professors, who will not bring their deeds to the light,
neither dare they try all things, as the apostle commanded,
but cry out against us called Quakers behind our backs,
but would not be tried face to face, nor suffer others to come and try us face to face;
though for the truth`'s sake several of us have suffered among them in prison.
Many of the teachers incense the people against us and that which we profess,
which is the truth; so are they kept in slavery and ignorance.
And you professors in Ipswich, Christ may justly say to you;
"`I was a stranger and ye took me not in.
I was in prison among you, and ye visited me not:
inasmuch as ye did it not to these little ones that believe in me,
who have suffered among you, ye did it not to me.`"

Yet this from the Lord I declare unto you,
that the day of visitation and the kingdom of God is come nigh unto you;
and woe unto them that still walk on in filthiness, resisting and hating the light,
which is God`'s witness in their own consciences,
which doth convince them of sin and evil, and reproves them when they commit it.
Take heed how you always resist the truth, since the Lord hath warned you;
lest you perish in your iniquities, and your blood be upon your own heads,
and upon your teachers, who retain the wages of unrighteousness,
and exercise lordship over you, to keep you in ignorance of the true light in yourselves,
which Christ hath enlightened you withal, which all must come to and follow,
who ever come to be saved from the wrath of God,
and from the curse which abideth upon the children of disobedience.
Away with all your empty professions, and let such as name the name of Christ,
depart from iniquity.
Away with all your proud and covetous teachers who preach for hire,
who make a trade upon the saints`' words,
which were spoken forth freely from the Spirit of truth.
Away with all your pride, gaudy attire, and superfluity of naughtiness,
the Lord is grieved with you because of these things;
you are not come to the modest apparel outwardly, nor to the true adorning inwardly,
which is not costly nor gaudy attire, but it is that of a meek and quiet spirit,
which is of great price with the Lord.
"`How long shall the Lord wait to be gracious to you,`" and yet ye resist his grace,
which hath appeared unto you, to teach you to deny ungodliness and worldly lusts,
and to live soberly and godly in this present evil world.
How long shall the Lord warn you, and yet you repent not?
How oft shall he call you, by his light in you, out of your filthiness,
and yet you answer him not, nor hearken to his voice?
How often shall the Lord knock at the door of your hearts, and yet ye open not?
Yet know that his spirit will not always strive with man: but it cometh to pass,
that they that will be filthy, must be filthy still.
Therefore as ye love your souls take warning.

From a friend to all that desire to know the Lord, and one who for the gospel`'s sake,
hath lately suffered fifteen weeks, or above, in Ipswich prison.

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
Suffolk, the 1st day of the Ninth month, 1658.

--
