== Chapter VII

In the year 1662,
our meetings in and about London were broken up with force and violence,
by the trained bands and officers, especially on the first-days of the week;
which though professed to be their Christian sabbath, no holiness was observed,
but rending and tearing innocent people out of their religious assemblies,
and haling them to prison.
Such furious work of persecution they commonly wrought on that day,
which they pretend to be their Christian sabbath and the Lord`'s day,
and to be kept holy,
as Israel was required to observe and keep the seventh-day for the sabbath,
according to the fourth commandment.

Yet these our persecutors made no conscience of violating
and profaning their professed sabbath,
by their works of violence and persecution.
Even after an act of Parliament was made for the better observation of the Lord`'s day,
as it was termed, those self-condemned, pretended Christians,
in many places furiously went on in their persecution and cruelty,
against their fellow creatures and honest neighbours,
without regard to God or religious worship, on any day;
to the great reproach and scandal of the profession of Christianity.

Pursuant to the aforesaid act, as was pretended, my beloved brethren,
Richard Hubberthorn, Edward Burrough and myself, with many more of our faithful friends,
were haled out of meetings and imprisoned in Newgate, London;
where so many of us were crowded together, both in that called justice-hall side,
and in the chapel side of the prison, that we were hard put to it for lodging room.

The chapel was on the top of Newgate, where many Friends lay crowded in hammocks;
and Richard Hubberthorn and I lay on a small pallet bed,
in a little hole or closet behind the chapel, and opening into it,
so that the breath and steam of those that lay next to us, in the chapel,
came much upon us.
We chose to lodge on the chapel side for the encouragement
of many of the poorer sort of Friends who were there,
and that they might not be offended or troubled, as we thought they might,
if we had taken up our lodging among the richer sort of our friends,
on justice- hall side.
We had many good meetings in the chapel, and the Lord was with us,
to our great comfort and encouragement in his name and power,
for whose sake we suffered patiently.

It being in summer time, and a hot season, when we were thus crowded in prison,
some of our friends who were prisoners too, fell sick of a violent fever,
whereof some died; and were viewed by the coroner`'s inquest.
And when some were removed out of prison on account of sickness,
they quickly ended their days, after their close confinement.

In those days of hot persecution, one called sir Richard Brown,
was chief persecutor in London,
and gloried much in his persecuting and imprisoning our friends, insulting over them.
I remember one time when several of us were called
into the court of sessions in the old Bailey,
one Friend was moved to testify against their persecuting
and oppressing the righteous seed and people of God,
calling out to the magistrates on the bench,
"`How long will ye oppress the righteous seed,`" etc.,
with other words on the same subject.
While he was so speaking, the said sir Richard Brown in derision, began to sing,
"`Ha you any kitchen stuff maids?
Ha you any kitchen stuff maids?
Hey, Wall fleet oysters, will you buy any Wall fleet oysters?
Will you buy any Wall fleet oysters,`" etc.

And he tuned it out much like the women that cry kitchen stuff, and Wall fleet oysters,
up and down the streets in London.
I thought it very strange,
indecent behaviour for a justice of peace and alderman of London,
thus anticly to show himself upon the bench, in a court of judicature,
in the presence of the lord mayor and the rest of the magistrates,
many people being present in court.
But it showed how, in this persecuting spirit,
a principal persecutor triumphed in his own iniquity, and gloried in his shame.

Many of us were committed for three months imprisonment in Newgate,
being our first commitment upon the aforesaid act.
Before the time of that imprisonment was expired, my dear friend and brother,
Richard Hubberthorn, was taken sick and died; and our dear brother, Edward Burrough,
who was detained prisoner after I was released, was also taken sick of a fever and died.
Thus the Lord was pleased by death to release both these my dear brethren,
companions and fellow-labourers in the gospel of Christ Jesus;
whose death was lamented by many tender friends,
respecting the great service which they had in their day.

And though I had a full share in suffering with my
friends and brethren in those days of hot persecution,
and was carried through such imprisonments and sufferings as ended the days of several,
yet my days have been lengthened much beyond my expectation;
so that I have been ready humbly to inquire, Lord for what end am I so long spared alive,
and my days prolonged, when so many of thy faithful servants are removed?
Whereupon he has showed me that my trials and service in his church, and for his people,
were not yet finished;
and he has often made me sensible of his merciful providence
in my preservation through many trials and exercises,
being supported by the word of faith and of his patience,
in the kingdom and patience of our blessed Lord and Saviour Jesus Christ;
to whom be glory and dominion forever and ever.
O my soul, praise thou the Lord, my life, my strength, and my salvation,
and let all that is within me bless his holy name.

In those days of hot persecution it was observable,
how furious some of the judges were against our friends,
when brought prisoners into court,
and they wanted evidence of matter of fact against them upon trial,
and some of our friends would not answer interrogatories to accuse themselves,
but asked for their accusers, or where are our accusers.
Some of the judges would use the words, "`Sirrah, sirrah, you are an impudent fellow,
leave your canting;`" threatening them, with severe menaces, and frowning on them;
much unbecoming a justice or judge, who ought to be impartial,
to do equal justice and right, without premeditation or partiality against any person.

The act against Quakers, to fine, imprison,
and transport them out of the land for not swearing, or for their religious meetings,
did not satisfy those rigid persecutors, when they had made trial of it.
The process of three months and six months imprisonment,
before it came to transportation or banishment,
was too slow a procedure to answer their invidious designs.
They could not thereby so expeditiously rid the land of us as they would,
though many suffered hard imprisonments;
and therefore in a short time they procured another
engine to shorten their work against us,
to wit; an act entitled an act to prevent and suppress seditious conventicles;
of which act, and the administration thereof, some account may be given hereafter.

A relation of my imprisonment with other Friends, in the White Lion prison in Southwark,
near London, for assembling together in the worship and service of Almighty God,
and of our treatment in prison, will show the manner how our friends,
being often apprehended, were treated in those days, for our innocent,
religious meetings.

Upon the 3rd day of the fifth month, 1664, being the first-day of the week,
our friends were peaceably met together at their usual meeting place at Horsleydown,
according to their wonted manner, waiting upon the Lord in his fear.
And after some time, George Whitehead spake to the assembly by way of exhortation,
in truth and righteousness.
In the interim, a company of soldiers with muskets and lighted matches in their hands,
rushed in, and before they came to the inner door, one of them fired a musket;
and two of them violently pulled George Whitehead down,
and haled him and some others out of the meeting, and carried themselves very rudely,
pushing and threatening our friends, forcing many out of the meeting,
and raging at and pushing women when they came near their husbands,
whom they had taken into custody.
George Whitehead asking them to show their warrant for what they did,
a soldier held up his musket over his head, and said that was his warrant.

Then they whose names are mentioned in the mittimus hereafter, with several more,
some of whom they took near the meetinghouse door, and others in the street,
were had to the main guard on Margaret`'s hill; where they kept them for some time,
until those called justices came,
who asked our friends whether they were at the meeting aforesaid?
To which answer was made, that they desired to hear what evidence came against them;
for some were taken in the street, and not all in the meeting;
but they put it upon George Whitehead to confess, if he was not present at the meeting;
to which he answered.
What evidence have you against me, and I shall answer further?
Whereupon some of the soldiers were called to give evidence concerning him,
and the rest with him; they witnessed,
that he was taken in the meetinghouse speaking to the people;
which was all the evidence that was given against him.

George Whitehead excepted against the soldiers, as being incompetent witnesses;
for they came, said he, in a rude and inhuman manner, with force and arms,
and so apprehended us illegally, without any justice present,
or warrant for what they did, but one holding up his musket, said that was his warrant,
when they took us.
They came in a terrifying manner among a peaceable people;
which was both contrary to the late act, upon which they pretended to proceed,
contrary to the king`'s proclamation,
which prohibits the seizing of subjects by soldiers,
unless in time of actual insurrection, according as was told them.
By the said act the deputy lieutenants and militia officers and
forces are not required to be assisting in suppressing meetings,
unless upon a certificate under hand and seal of a justice of peace, that he,
with his assistants, are not able to suppress them.
It was also told them, that no dwelling house of any peer or other person whatsoever,
shall be entered into, by virtue of the said act,
but in the presence of one justice of peace.
But there was no justice of the peace present when they were taken,
neither was their meeting seditious or tumultuous,
as those are which the militia officers are required to be assistant to suppress.
The words of the act were mentioned to them,
and George Whitehead required justice against those
who had so illegally apprehended them,
and broken the peace thereby.

Friends also complained against one of the soldiers for
firing his musket near the meeting door in the entry,
and shooting a bullet through two or three ceilings and a dwelling room,
which bullet was found near a child`'s cradle, where the child used to be laid;
and one present had the same to show them, as it was bruised.

George Moor, one of the justices, answered, that it was done accidentally,
and not intentionally; but how it could be that it was not intentionally done,
does not appear;
seeing the rest of the soldiers held their matches apart from their muskets.
If accidentally done, consider whether such a man who had no more discretion or care,
was a fit person or officer, to come in that manner with a musket charged,
among a peaceable, harmless people, assembled to worship God?
But George Moor excused their having their muskets loaded.
And to George Whitehead`'s saying that there was no justice present when they were apprehended,
George Moor answered, that he was present; George Whitehead told him,
they did not see him there; and the soldiers being asked if he were present among them,
they said no; but he said he was present, for he was near the meeting,
or but a little way off.
And when George Whitehead required justice against
those soldiers that had broken the peace,
and desiring that they would correct or stop such proceedings for the future, for,
said he, if any hurt be done by the soldiers, it will be required at your hands;
answer was made by some present, that our friends might take their course,
and have the benefit of the law, if they would swear the peace against them.

As to the charge against George Whitehead, that he was at an unlawful assembly,
and there was taken speaking; he answered,
that it must be some unlawful act done by the persons
met that could make the meeting unlawful;
and therefore desired to know what unlawful act they had committed in their meeting.
He told them that it was neither simply the meeting, nor the number met,
whether five or five hundred, that could reasonably be judged unlawful,
if the act or occasion met about was lawful;
but it is an unlawful act that makes an unlawful meeting.
As to the act of Parliament, which is named, An act to prevent Seditious Conventicles,
the name should signify its nature and intent,
and the preamble the reason or cause of it,
and that is against such as under pretence of tender consciences,
do contrive insurrections at their meetings.
The preambles of laws are esteemed the keys of laws.
One of the justices said, he did not know but that our meetings were to that intent.
George Whitehead told him,
whatsoever he or any other might suspect against them proves nothing.
Suspicion proves no fact; we are an innocent people, fearing God.

Some of the justices alledged upon the evidence,
that George Whitehead was at the meeting, and taken speaking,
and the meeting was above the number of five.
To which George Whitehead said, That proves nothing of the breach of the law against him,
unless they could prove some unlawful act done or met about;
for it is not the number makes the transgression, but the fact, if it be unlawful;
and if three be met about an unlawful act, it is an unlawful meeting, or a riot;
which Friends urged several times,
that it must be an unlawful act that must make a meeting unlawful.
Thereupon they excepted against the evidence as insufficient for conviction,
or passing sentence of imprisonment upon them, in order to banishment.
And it was urged as a matter of weight, which concerned them to consider of.

Whereupon George Moor with some others, commanded the people to depart,
and caused the soldiers to disperse those who stood civilly by,
to hear and see what became of our friends--that they might not hear their trial,
and would have had George Whitehead taken away.
George Whitehead being several times accused for speaking in the meeting,
desired the justices to ask the witness what he spake in the meeting;
but they would not ask the question,
neither could the witnesses answer to it when it was propounded by our friends;
so that no breach of the law was proved against them.
One Friend told them,
We suppose you will not account it a transgression to speak,
where nothing can be proved against what is spoken, unless you would have us dumb,
and not speak at all.

And then as to meeting to the number of five or above,
under colour or pretence of religious exercise not allowed by the liturgy,
which incurs the penalty of the act,
George Whitehead questioned what manner of religious
exercise the liturgy did disallow of;
and granted that he was at the meeting, and there did speak,
having a word of exhortation to the people;
but that still they fell short in their proof,
either that the meeting was seditious or tumultuous,
or that the exercise of religion or worship that
we practised was disallowed by the liturgy.
For, said he, the liturgy allows what the holy Scriptures allow of;
and if I had a word of exhortation to speak according to the gift of God received,
this is allowed by the Scriptures, therefore not disallowed by the liturgy,
so that you have not proved the transgression of the law against me.
To which they gave no answer.
The clerk said it was a dilemma.
Some Friends they let go,
because the soldiers could not testify whether they
took them in the street or in the meeting.

But seeing they resolved to proceed against some of our friends,
George Whitehead told them that if they had so much moderation in them, they needed not,
neither were they enjoined, to proceed to the rigour of the law,
so as to imprison them for three months,
seeing the law allowed any time not exceeding three months.
But if they would imprison them to the utmost,
George Whitehead demanded that they might have sufficient prison room,
and not be stifled and destroyed by many being crowded together,
as several were before in the same prison; for if they were, he told them,
it would be required at their hands, and God would plead their cause,
and call them to account for what they had done against them.

After several passages betwixt them, more than are here mentioned.
Friends refusing to pay five pounds fine each,
were committed to jail without bail or mainprize.
While the justices were committing them, there was exceedingly great thunder,
lightning and rain,
and the water was so high in the street that the soldiers could not get them to prison,
but kept them in the street in the rain,
and afterwards had them back to a house until the water was fallen;
and then they were had late to prison very wet.

The two keepers, Stephen Harris and Joseph Hall,
after a little space demanded of each of them, 3s. 6d. a week for lodging,
or 2s. apiece for the bare room, the best whereof overflowed with water.
But they could not yield to the jailer`'s oppression, or pay him down ten shillings,
which he required for that first night, but desired to be left to their liberty;
and if they received any courtesy or accommodation from him,
they should consider him as they found cause; but could neither pay for a prison,
nor uphold oppression in it.

Stephen Harris threatened them with the common ward, where the felons lie,
and commanded them to go into it, which they refused,
as a place not fit for true men to be in;
yet he turned them into the common ward among the said felons.
Friends warned him not to suffer them to be abused, but they made light of it, saying,
"`It is your own faults,`" and seemed to encourage the felons against our friends.

Soon after the keepers had turned their backs the felons demanded half a crown apiece,
swearing what they would do to them;
and because Friends could not answer their unjust demands, they fell upon them,
searched their pockets, and took what money they found from several of them.
When they had so done the keeper came to the window,
and the felons confidently told him what they had done and how much they had taken,
and that they must have more from them, for which he did not at all reprove them.
They said they hoped he would stand by them in what they did;
he made them return the cloak they had taken from one Friend,
after they had taken his money; and laughed upon them when they threatened Friends,
and swore and cursed; the keepers also swore at them, and threatened to make them bow;
whereupon the felons gave a shout, crying, God a mercy, boys, we`'ll be upon them again.

Besides these abuses which our friends met with from the jailers and prisoners,
the ward was such a nasty, stinking hole, and so crowded with those felons,
and several women lying among them, which some called their wives,
that our friends had not whereon to lay their heads to rest,
nor a stool to sit down upon; but when they were weary,
were fain to sit down on the floor, among the vermin, in a stinking place.
Of which gross abuses, complaint being made to some of the justices that committed them,
the next night the jailer was made to let Friends
have room to lodge apart from the felons.

[.offset]
A copy of the mittimus follows.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Surrey, ss.

[.salutation]
To the keeper of his majesty`'s jail for the county aforesaid;

Forasmuch as George Whitehead, George Patteson, Joseph Dunsdale, Gilbert Hutton,
George Rawlins, Edward Pattison, Timothy England,
were this day taken at a seditious assembly or conventicle,
and are convict for the same before us; wherefore, according to the said act,
we have fined them at the sum of five pounds apiece,
which they do refuse to pay down unto us.
Therefore in his majesty`'s name,
we command you to receive their bodies into your said jail,
and them safely to keep without bail or mainprize,
for the space of three months from this present day.
And hereof see that you in no wise fail,
under the pains and penalties in the said act mentioned.

[.signed-section-context-close]
Dated the 3rd day of July, 1664.

[.signed-section-signature]
John Bromfield, John Lenthal, George Moor.

--

A few days after my commitment to White Lion prison, another trial befel me.
I was had out of the prison, before John Lenthal, about the plot in the north of England,
A+++.+++ D. 1663, being unjustly accused by a Yorkshire man, a sort of an attorney, or lawyer,
to have been concerned in that plot, because I was a Westmoreland man born;
and though he could not make out any proof against me,
yet he persisted in his own evil jealousy and surmise, that I was such a person,
whom he named, and said was in the plot; affirming that my name was not Whitehead,
but another name.
I was then carried in a boat to White-hall, guarded with musketeers,
and the jailer also with us, and there had into a room near the secretary`'s office,
where the jailer waited with me.
The lawyer, who had falsely suggested the crime against me, went in,
and after some time a person was sent out to examine me and my accuser with him.
Then I was questioned about my name, the examiner,
looking in a list of names which he had in his hand.
I gave him a just account of my name and clearness,
yet my accuser would confidently contradict me, saying, "`Your name is not Whitehead,
but Marshden,`" or such a like name.
I told him surely I knew my own name, as I had declared it.
Presently stepped in one who seemed to be an ancient gentleman,
hearing my accuser tell me my name was not Whitehead, and contradicted him; saying,
"`Yes his name is Whitehead; he has written divers books,
to which his name is in print;`" which gave a check to him,
and prevented further examination.

This busy, false accuser and prosecutor, went in again to the secretary`'s office,
and in a little time came out and warned the jailer not
to discharge me until he had order from the secretary.
Whether he had order so to caution the jailer was questionable,
for the man appeared very busy against me without cause, or any previous knowledge of me,
or I of him.
But seeing he was so confident in his unjust prosecution,
I questioned in my thoughts whether he might not be suborned to prosecute me,
or did it to get himself a name or some reward for a pretended discovery.
However,
I esteemed it best and safest for me to trust in the Lord my God for preservation,
and to be resigned to his will;
and I desired if he suffered me to be prosecuted and tried for my life,
I might have opportunity to vindicate and clear our holy profession and friends,
and my own innocency also, from all such works of darkness,
as plots and conspiracies against the king or government.
And this I thought to do, if brought to a place of execution;
nevertheless I wrote a letter from prison to the lord Arlington, then Secretary of State,
to clear my own innocency from those false suggestions
and insinuations which were made against me,
about the plot before mentioned, which was delivered to him, and I heard no more of it,
but was released out of prison with the rest, when the three months were expired,
for which we had been committed.

On the 16th day of the eighth month, 1664, being the first-day of the week,
our friends were met together in the fear of the Lord, according to their usual manner,
in their meeting place at the Bull and Mouth, near Aldersgate, London,
and George Whitehead being there,
declared the truth in the power and dread of the Lord God.
After some time a great company of men with halberts came into the meeting,
and a little after shut the meetinghouse door,
and kept out many people that would have come in.
The halberteers stood and heard quietly for near an hour, as it was thought;
only one rude fellow attempted to pull George Whitehead down, but did not.
Afterward came the lord mayor and a company with him, and Richard Brown followed.
In a little time after the mayor came in,
a rude fellow violently pulled George Whitehead down from speaking,
and haled him near the door; the mayor asked him his name, which he told him.

Richard Brown came somewhat rudely into the meeting, reviling and deriding our friends;
whereupon one of them giving testimony for the presence
of the Lord in our meeting after this manner,
viz: "`The Lord brought us hither; and the presence of the Lord is among us;
and this is my testimony.`"
Richard Brown answered, "`The devil brought you hither; and the devil is among you,
and this is my testimony;`" laughing, and swinging his arms to his words.
The devil is among you, our friends presently replied,
"`It is since thou camest then among us.`"
He threatened some to send them to Bridewell,
but George Whitehead exhorted the said Richard Brown and
the mayor to moderation and civility towards us;
Richard Brown answered, "`If you will be civil to us, we will be civil to you.`"
George Whitehead desired the mayor to produce the law they had broken,
and that they might have a fair trial.
Richard Brown answered,
"`Yes you shall have a fair trial at the sessions tomorrow,`" it not being then ended.
Then some of the halbert men had George Whitehead and some of his friends into the street,
and after they had kept them some time, they sent them in companies to Newgate,
without sending warrants with them, being fined one shilling each,
or six days imprisonment.

At the same time a particular warrant was sent to the jailer,
from the mayor and Richard Brown, to detain William Smith, James Carter, William Parker,
Elizabeth Chapman, and Jane Boadle, prisoners, for a pretended third offence,
until delivered by due course of law.

In such manner both our men and women friends were frequently imprisoned,
and jails filled with them in those days;
for their persecutors were in great heat and haste to get them
banished upon the second act of Parliament made for that end.

If they could bring them under conviction for a third offence,
as they termed our meeting to worship the only living and true God;
which if any one among us did but confess, it was enough to make him or her an offender,
and to be convicted presently thereupon, either for a first, second, or third offence.
The shortness of our last imprisonment,
as well as the smallness of the fines of one shilling apiece,
seemed designed to dispatch us the sooner out of the land by banishment,
after conviction for three pretended offences.

Now it may not be improper to give some account of
the contents of the second act of Parliament,
designed not only for our imprisonment,
but also for our banishment out of the land of our nativity;
and that with more expedition than could be effected by the first act,
though the Lord our God would not suffer that design of
banishment to take any such general effect against us,
as was desired by our invidious persecutors;
for by his judgments in a great measure he frustrated our adversaries.
Howbeit many of our innocent friends were sentenced for banishment,
yet but few in comparison, actually shipped or banished out of the land.

The preamble and penalties of the said act follow, 16 Car.
2, ch.
iv.

It is styled, An act to prevent and suppress seditious conventicles.
In the preamble, the 25th Eliz.
ch. i. is declared to be in force:
and also for providing of further and more speedy remedy against
the growing and dangerous practices of seditious sectaries,
and other disloyal persons, who under pretence of tender consciences,
do at their meetings continue insurrections, as late experience hath showed.
Thus far the preamble and reason given for the act.

Thereupon it is enacted, that if any person of the age of sixteen years and upwards,
being a subject, etc., shall be present at any assembly, conventicle, or meeting,
under colour or pretence of any exercise of religion,
in other manner than is allowed by the liturgy of the church of England,
every such person being convicted before two justices of the peace,
to be committed to the jail or House of Correction,
there to remain without bail or mainprize, for any time not exceeding three months,
unless such person pay down to the said justices
such sum of money not exceeding five pounds,
as they might fine the offender at.

And for the second offence,
the person convicted incurred the penalty of imprisonment
for any time not exceeding six months,
without bail or mainprize, unless the person convicted pay down such sum of money,
not exceeding ten pounds, as the justices would fine him.

The penalty for the third offence, was imprisonment without bail or mainprize,
until the next general quarter sessions, assizes, jail delivery, etc.,
there to be indicted, arraigned, etc., and when convicted, judgment to be entered,
that such offender should be transported beyond the seas,
to any of his majesty`'s foreign plantations--Virginia and
New England only excepted--there to remain seven years.

And the said respective courts were also empowered
to give out warrants to the several constables,
etc., where the estate, real or personal, of such offender so to be transported,
should be; commanding them to seize into their hands the profits of the lands,
and to distrain and sell the goods of the person to be transported,
for the reimbursing the sheriffs charges for conveying
and embarking the person to be transported.

And it is also enacted, that in case the offender convicted for the third offence,
shall pay one hundred pounds in court, he shall be discharged from imprisonment,
transportation and judgment for the same.

And it is further enacted, that the like imprisonment, judgment, arraignment,
and proceedings,
shall be against every such offender as often as
he shall again offend after such third offence;
nevertheless is dischargeable and discharged by payment
of the like sum as was payed for his or her said offence,
next before committed,
together with the additional and increased sum of
one hundred pounds more upon every new offence committed.

But this severe act was made temporary,
being to continue in force for three years only after the end of that session,
and to the end of the next session of Parliament, after the end of the three years,
and no longer.

And indeed it was time that persecuting, cruel law should expire;
for the execution thereof tended to the great oppression
and ruin of many of the king`'s innocent,
peaceable subjects and families, especially of the people called Quakers,
of whom the persecutors, in that three years time, while the said act was in force,
furiously endeavoured to rid the nation, by banishment,
or to force them to conform to that church whereof those persecutors were members.
By their frequent imprisonments in order to banishment,
they brought no great honour to their church, priesthood, or profession;
but made many widows and fatherless, as well as poor, even of honest,
industrious families, by their persecutions, cruelties, imprisonments, fines,
and many times spoil of their goods.
Our religious assemblies have been often disturbed
and broken up by the persecuting agents,
officers and soldiers, many of us apprehended and brought before the magistrates,
witnesses called and examined, and no matter of evil fact proved against any of us,
either of any breach of the public peace or sedition,
much less of any contrivance of insurrection,
or of any other dangerous practice whatsoever.
If the meeting was taken altogether in silence,
the persecuting justices would endeavour to make it a seditious conventicle,
when they could have no proof of any sedition or unlawful act,
or colour of evidence thereof against it, or any of our meetings whatsoever.

The manner of their proceeding to conviction against many of us, has been thus;
when apprehended and convened before the magistrates,
and the officers or witnesses called,
they declare they took such persons in a conventicle or meeting.
The magistrate asks,
What did they do there?
If the witness answers he took such an one preaching or teaching, or praying,
and he be asked, What did he say?
Commonly the witness or witnesses cannot remember one sentence, preached or prayed.
However, the persecuting magistrate takes it for granted it was a seditious conventicle,
though he has no proof of any sedition preached, taught, or uttered in prayer,
nor any evidence or knowledge what was said, yet presently he passes judgment,
enters conviction, and imprisons the persons convened.

If any of the persons taken confess they were met to worship God in spirit and in truth,
or to wait upon God, the persecuting magistrates presently lay hold of this and say,
That is enough,
or they have confessed enough to convict them of a conventicle or unlawful assembly.

If the witnesses or informers, have no evidence to give of any overt act,
or religious exercise done in the meeting; but only that all was in silence,
as many times hath been,
yet the persecuting magistrates or justices would either
make a riot or unlawful assembly of such a silent meeting,
when there was not the least appearance of a riot, force or violence,
nor any thing acted or spoken _in terrorem_ or injury of any one`'s person or property,
whatsoever.

When a persecuting justice with a constable and others,
comes huffing and stamping into the assembly, whether all be in silence,
or one preaching, and either commands the people to be pulled out of the meeting,
or the doors to be shut, to keep them in, and their names to be taken,
the officers and other rude persons either pull and hale people out till they are tired,
or take names until they are weary, according as they have command.
The justice then either imprisons or fines many of the persons who are most noted,
though he saw no act committed of any evil tendency.

Persecuting justices would easily receive information against our religious meetings,
how ignorant and impertinent soever they were.
If an envious informer told the justice the Quakers
were met under colour of religious exercise,
contrary to the liturgy and practice of the church of England,
the informer or witness presumes to be judge both of law and fact;
when probably he does not understand what the word liturgy means,
nor can explain the practice of the church of England,
which is not limited to reading the common prayer only;
and if the witness declares there was preaching or praying in such a meeting,
yet remembers not one word or sentence expressed in either, as it has often happened,
nevertheless such silly, ignorant,
and impertinent evidence has been often accepted for conviction.

It was observable as well as memorable,
that as the rulers in those days were often warned of the impending judgments of God,
if they would not leave off their persecution,
so when they were making haste to have us banished out of the land,
and especially out of the city of London and the suburbs, in the years 1664 and 1665,
and for that end the jails were often crowded,
whereby many innocent persons suffered death; God was pleased even then,
in the year 1665,
to hasten his heavy judgment and sad calamity of
the great plague or raging pestilence upon the city,
and some other places in the land, whereby many thousands of the inhabitants died;
sometimes above six thousand in a week, of all sorts,
both of good and evil men and women, besides innocent children.
The calamity being common,
the righteous and the good were taken away from the evil to come,
though it went ill with the wicked, who for all this would not return to the Lord;
neither would the cruel persecutors repent of their abominable cruelties;
but persisted therein what they could, disturbing our meetings and imprisoning,
until they were frightened with the plague.
Even during its prevalence many of our innocent friends were confined in jails;
which seemed no small piece of barbarity and inhumanity,
especially when the contagion so greatly prevailed in the city.
I have told some persons in authority of this cruelty,
to manifest what mercy their church then showed us,
and that men of moderation or any compassion would be ashamed thereof.

I well remember,
that having some times of respite between my imprisonments before the sickness in London,
I travelled to visit our friends in the country,
and sometimes into the northern counties, and near the beginning of that summer,
A+++.+++ D. 1665, when the pestilence was begun in London, I was in the county of Surrey,
and having a meeting at John Smith`'s house at Worplesdon,
his brother Stephen Smith and his wife came to the meeting;
where Stephen and his wife were convinced of the truth,
which the Lord enabled me to declare, and livingly to demonstrate at that time,
as at many others.
And the Lord having laid upon me to come to London,
as I signified to some friends present, after the meeting,
Stephen questioned how I could venture to come to London,
seeing the plague was then broken out there.
I gave account of my submission to the will of God,
and of my faith and trust in him for preservation;
upon which Stephen appeared more satisfied and confirmed in the belief of the truth,
borne testimony to among us at that meeting.

I soon came to London, and my lodging was at the house of William Travers,
tobacconist in Watling street, who with his wife Rebecca,
kindly received and entertained me, as did also her sister Mary Booth,
who lived with her, and the whole family were loving to me and friends.
And the Lord preserved that family, that none of them were infected with the pestilence,
though it greatly increased, and the mortality thereby,
so that in a few weeks great numbers quickly died.

It was a time of great calamity, sorrow and heaviness, to many thousands of all sorts;
and that which added to our friends`' affliction,
was the hardness of our persecutors`' hearts,
their cruelty and barbarity in imprisoning and detaining many of them in prison,
both in Newgate, London, and the White Lion prison in Southwark,
after the plague was greatly broken forth, and many people swept away by it.

I had not then freedom, satisfaction, or peace to leave the city,
or friends in and about London, in that time of great and general calamity, no,
not when the mortality was at the height;
but was concerned and given up in spirit to stay among them to attend friends`' meetings;
to visit friends in prison, and at their houses;
even when many of them lay sick of the contagion, both in prison, and their habitations.
And in all that time the Lord preserved me by his power, through faith,
from the infectious distemper which mercy I esteemed great and wonderful,
and hope ever thankfully to remember,
in a living sense of the divine hand which upheld and preserved me.

Although it was judged the prisons were then infected and poisoned with the contagion,
I was freely given up to suffer imprisonment;
and on first-days took my night cap in my pocket when I went to meeting,
not knowing but I might be apprehended at some meeting, and committed to prison.
The Lord gave me faith to be resigned to his will, either to live,
or to die for his name and truth sake; and through all those dangers and difficulties,
to bear my testimony in faithfulness to his blessed power and life of righteousness,
and thereby sustained and wonderfully preserved my life,
when the cry and sound of mortality was round about us,
from one end and side of the city to another.

As the contagion and sickness increased, many of our persecutors were so terrified,
that their hands were for sometime weakened.
Still many of them were so hardened,
that they were resolved to proceed against us to banishment,
as when Pharaoh saw there was respite, he hardened his heart.
So did our persecutors, when the calamity did not come upon themselves,
though they saw how it was abroad, greatly destroying the inhabitants;
for it was observed in the weekly bill,
that when the plague was most hot and violent in and about London,
seven thousand one hundred and sixty-five died thereof in one week; and in that year,
1665, of the same distemper, sixty-eight thousand five hundred and ninety-six,
according to the yearly bill.

One evening after I had been visiting Friends in some places in the city,
I was taken sick in my stomach and head, and was concerned,
lest any of the family where I lodged should be frightened,
so as to fear the sickness had taken hold upon me,
and I spake to my friend Rebecca Travers, to desire her sister, Mary Booth,
not to be afraid on my account; for said I to her, I shall be well tomorrow,
wishing her to tell her sister so.
And through the Lord`'s mercy I was very well next morning,
though I had been very sick over night.

I was then deeply concerned to visit our friends who were sick in prison,
and out of prison, even when some of them were very near death,
being often in great suffering and travail of spirit,
with earnest prayer and fervent supplications to God for them,
who were sufferers by imprisonment and that visitation, that God would appear for them,
and plead their innocent cause, and afford them speedy help and deliverance.
Being then a witness of that love which casts out fear,
through the great mercy and love of my heavenly Father, manifest in his dear Son,
I was not afraid to visit my friends when sick and in infected prisons.
The Lord bore up my spirit in living faith, above the fear of death,
or the contagious distemper; and my life was resigned in the will of him who gave it,
for my friends and brethren,
for whose sake true Christian love would engage us to lay down our lives to save theirs,
if required of the Lord so to manifest our unfeigned love one for another.
For it is not only in words and outward appearance that true love is really manifest,
but in deed and in truth.
But many who profess Christian love and charity, light and truth,
in these days of liberty, have not had their love tried,
as the love of our friends and brethren was in those
days of sore persecution and great calamity;
wherein the Lord, notwithstanding, gave us great consolation,
comfort and courage--having received certain testimony
and evidence in our hearts of the love of God,
which we did partake of in Christ Jesus, from which we believed no wrath of man,
no persecutions, calamities or distresses, should separate us.
In those times of severe trial, the questions and answers given by the apostle,
were often remembered; Who shall separate us from the love of Christ?
Shall tribulation, or distress, or persecution, or famine, or nakedness, or peril,
or sword?
As it is written.

[quote.scripture, , Rom. 8:35-39]
____
For thy sake we are killed all the day long; we are accounted as sheep for the slaughter.
Nay, in all these things we are more than conquerors, through him that loved us.
For I am persuaded, that neither death, nor life, nor angels, nor principalities,
nor powers, nor things present, nor things to come, nor height, nor depth,
nor any other creature, shall be able to separate us from the love of God,
which is in Christ Jesus our Lord.
____

Further to show my exercise and concern for our friends in that time,
the two following epistles are next inserted.

[.embedded-content-document.epistle]
--

[.letter-heading]
A few seasonable words to all the tender-hearted,
whose spirits are saddened and cast down at the trials of the present time.

[.salutation]
O dear friends,

You that have received the testimony of God`'s love and salvation,
and have tasted of the power of an endless life, look not out,
nor be discouraged at the deep suffering and trial of the present time,
though many have a deep sense thereof upon their spirits,
and the hearts of many be saddened to see how universal
this calamity and overflowing scourge is,
in this day of sweeping, sifting and trying;
wherein the faith of many must be thoroughly tried, and their patience proved,
to the resignation of life and all unto the will of the Father, in whose hands we are,
who knows what is best for his children.
His ways are not to be measured nor found out by the wisdom of man;
for his works and proceedings are in a cross to all carnal reason and expectation,
and to the confounding thereof.
But they who in the faith and patience of the elect seed, give up in his will,
as those that live by faith in him, and whose hope and refuge the Lord is,
shall never be confounded nor afraid, though the earth be removed;
nor yet discouraged or unsettled, because of the wicked,
who make a great flourish like a green bay tree, when he is in great power;
for he passeth away and shall not be found.
And he that enters into the sanctuary of the Lord, and there abides,
shall see the end of his enemies and persecutors, who stand in slippery places,
though for a time they have seemed to prosper in the world.

And dear friends and tender hearts,
who have a sense of the sufferings of the righteous Seed, which bears the afflictions,
sorrows and sufferings of God`'s people through all,
and hath been bruised and wounded under the weight and burden of people`'s iniquities,
though He has been deemed as one plagued or smitten of God;
all of you keep in the sense of the power,
by which you all may feel your preservation through faith in Him,
that is given for a covenant of life and light.
All retire to Him that is manifest for a sure hiding place to the upright,
in the day of calamity and hour of temptation;
and in Him you will witness plenteous redemption and refreshments of his life,
over all the troubles and sufferings of the present time,
and over all fears and doubtings, which would beset any of you,
to weaken you either inwardly or outwardly.
And none are to let in unbelief, or hard thoughts, or to be shaken in mind,
because of the deep sufferings of many of the dear servants of the Lord at this day,
who are as killed and crucified,
and all the day long accounted as sheep for the slaughter;
nor at the great calamity and mortality in this fading city,
which extends to the upright and innocent, in divers places,
as well as to the unrighteous, to both infants and others;
and to divers of the sufferers for truth in their confinements,
who have not contributed to the cause of God`'s displeasure herein,
but are taken away in mercy, as to them, and from the evil to come.
They are delivered and set in safety,
from the future cruelties and wicked designs of their oppressors and cruel minded persecutors,
who have hunted for the blood of the innocent;
and may not only be charged with not visiting Christ when he was sick and in prison,
but also with killing and murdering him in prison;
inasmuch as it is done to any of his little ones,
by their cruel confinement in pestilential or poisonous places.
But we know that for the faithful, there assuredly remain victory, triumph,
and everlasting safety, though it be through death to many of them,
who know that it is neither tribulation nor distress, nor persecution, nor famine,
nor death, nor life, that shall be able to separate them from the love of Christ.
And hereof we have a sure evidence and living confidence,
in the name and power of the Lord our God, to whom be glory and praises forever.

So dear and tender hearts, think not the trials strange that attend us at this day,
nor be discouraged thereat, as if the Lord had either forsaken his heritage,
or left his people desolate; for his love and fatherly care are known to his own,
both in giving and taking away, as he pleaseth; and he is not to be limited,
nor the creature to point him out his way or manner of taking away,
or removing any of his own.
But he is in freeness of spirit to be submitted unto in all things,
that no flesh may glory or boast before him, seeing all flesh is grass,
and the glory of man as the flower that fades.
Nor are any to retain a self-confidence, but live in the pure fear of his name,
and wait upon the Lord in singleness of mind, even in the light in which God dwells,
and wherein the secret place of the Most High, and shadow of the Almighty are known;
where his own seed, his offspring dwells with him,
in whom our safety and dwelling place is, above that which is elementary, earthly,
corruptible, or fading, and above the fears and terrors which are in the darkness,
and deeply seize upon the children of the night, whose habitation is not in the light.
They know not whither to go or run for a habitation,
the terror and fear of death doth so surprise them,
because of the plague in their own hearts;
and the pestilence that walks in darkness lies nearer
than that of the outward sickness or bodily distemper.
For it is the guilt of sin and fear of death,
which make that the more dreadful to them that are in bondage therein,
which is not the effect it hath upon the innocent and blessed of the Lord,
whom he will strengthen upon the bed of languishing,
and whose bed he will make or turn in sickness.

Thus they whose eyes are towards God,
do see what contrary effects the same common calamities, outward afflictions,
or distresses, have on the minds and spirits of persons,
as they differ in nature and spirit.
Though the trials of the innocent this day are a stumbling
block to them who have shut their eyes against the light;
and some whose minds are out of the patience,
stumble at the outward afflictions and deep sufferings of such as are innocent,
as they did who, instead of comforting Job in his affliction,
upbraided him because thereof, as one not upright or innocent.
Howbeit, the righteous shall go on in his way,
and the upright shall grow strong in the Lord,
by whose love and mercy all their trials are sanctified to them;
and all you that trust in him shall be in safety, and it shall go well with you.
Therefore be not dismayed, nor any of you disconsolated,
whose hearts are tender towards God, nor let your souls be cast down by the enemy,
but live in the innocent life of Christ Jesus, the incorruptible seed,
in whom redemption, out of the world`'s corruptions, stands.
For though this be a day of deep trial and desolation to many,
the Lord will yet show forth a signal manifestation
of his power and love for his own seed`'s sake,
and in the prosperity of that righteous testimony,
for which many have suffered and given up liberty and life, as we have done,
whose generation and testimony shall never be extinguished or abolished.
So that as the chosen and faithful who dwell with the Lord, and inherit his blessing,
you may be preserved in the faith and patience of his own seed,
as constant followers of the Lamb, to whom the victory and everlasting dominion belong,
is the travail and desire of our souls, who are your dear friends,

[.signed-section-signature]
George Whitehead, Alexander Parker.

[.signed-section-context-close]
London, the 19th of the Sixth month, 1665.

--

In the year 1665, that very summer in which the plague and mortality were so great,
the persecutors in London were busy to send away
our friends whom they had sentenced for banishment,
and closely detained in prison for that purpose;
they accordingly began early in the year to force our friends on ship-board.

The first Friends they shipped were, Edward Brush, Robert Hayes, and James Harding, who,
on the 24th day of the first month, 1665, early in the morning,
without any timely warning given them,
were hurried down from Newgate to Black Friars`' stairs, by some of Newgate turnkeys,
and from thence to Gravesend, and there forced on ship-board.
Edward Brush, a very aged man,
and a citizen of good repute among his neighbours and many persons of quality,
was thus sent away and banished from his dear wife and child.
But a more lamentable instance of the persecutors`' cruelty in this undertaking, was,
that Robert Hayes being taken fasting out of prison, and weak in body,
having been under a course of physic, was carried forth upon the water to Gravesend,
the season being very cold,
and having no outward refreshment or relief afforded him by the way on the water,
within a very short time after he was put on ship-board he died there,
and his body was brought up to London and buried in our friends`' burying place.

I knew this Robert Hayes; he was a very innocent, loving man, a goodly person,
had a fresh, comely countenance, seemed healthy,
and in his prime and strength when first imprisoned.
I was very sorrowfully affected when I heard how
quickly he was dispatched out of the world,
by that shameful cruelty and inhuman usage inflicted upon him by those merciless persecutors.

On the 18th of the second month, 1665,
seven more of our friends were taken out of Newgate, and carried to Gravesend,
and there put on ship-board for banishment, as the others were before.

It was remarkable, that not many days after those Friends were embarked, Judge Hyde,
one of the grand persecutors, was suddenly cut off by death; and who, it is said,
was seen well at Westminster in the morning, and died in his closet about noon.

About this time the plague began to increase more and more,
and the first that was known to die thereof in the city,
was within a few doors of Edward Brush`'s house,
who was one of the first that was sent away, and banished as before related.
The plague increased, until of that and other distempers,
there died eight thousand in a week, in and about the city of London.
Oh! the hard-heartedness, cruelty and presumption of our persecutors,
who in that time of the great calamity and mortality, in the fifth month, 1665,
took fifty-five, men and women, of our friends out of Newgate,
and forced them on board the ship called the Black Eagle,
which lay some time at Buggby`'s Hole, where they were so crowded,
and the sickness being in Newgate, whence they were carried out to the ship,
wherein also the distemper broke out among them, that the most of them were infected;
insomuch that about twenty-seven of them soon died on ship-board, some at Buggby`'s Hole,
and the rest beyond Gravesend.

I visited these Friends, and had a meeting with them when on ship-board;
and the Lord my God preserved me both from the distemper and from banishment,
wherein I do humbly confess his power and special providence,
to his own praise and glory alone.

[.embedded-content-document.epistle]
--

[.blurb]
=== The second epistle, printed in the year 1665, after the heat of the contagion was over, entitled, _An epistle for the remnant of Friends and chosen of God, whom he hath yet preserved to bear their testimony, in and about the city of London._ To whom this is a testimony of the dear love and tender care which flows forth, and is extended toward them, and all tender hearts who are concerned in the like sufferings, temptations and trials.

[.signed-section-closing]
From their faithful friend and servant in the Lord,

[.signed-section-signature]
George Whitehead.

My dearly beloved friends, brethren and sisters, among whom my soul hath travailed,
and suffered for the afflicted`'s sake,
whose burdens and trials are still with me in spirit, as also the love, tenderness,
care and freeness of spirit,
that have appeared among you towards the afflicted and harmless sufferers,
who have been led and driven as sheep to the slaughter,
for the witness of Jesus and of a good conscience.

Dear hearts, I feel towards you all,
in the spirit and unity of true love in the elect seed,
wherein life and dominion are felt by all that wait patiently upon the Lord,
in true subjection to his eternal power and counsel, in all the exercises,
trials and hardships, that the righteous seed is beset withal;
that being thoroughly tried, you may come forth as gold thoroughly refined,
and the righteous through all these things may go on in their way,
and the innocent and clean in heart may grow stronger and stronger in the Lord,
that truth and righteousness may forever shine forth among you, and all his elect,
to the praise of his name.
He beholds, feels and bears the sufferings of his people,
in his long suffering and patience, wherein the spirits of his chosen ones are exercised,
and by which they shall overcome, and be more than conquerors, where neither calamities,
distresses, life nor death, shall ever be able to separate from that love, virtue,
life and glory, revealed in the faithful in Christ.

My dear hearts, the glory and weight of God`'s righteous testimony of life and salvation,
being in his light truly and evidently manifested in and among you,
you have great cause forever to prize his love and glorify his name,
and stick close to him therein, whatever perils, trials, oppositions,
sufferings or temptations, you meet withal.
Be of a constant spirit and upright mind,
in the unchangeable truth to the Lord God of life,
in whom your preservation and safety stand;
knowing that no weight of affliction or suffering here,
is comparable to the weight of eternal life and salvation in Christ Jesus,
which you are called unto,
through the glorious appearance of God`'s power and gospel of peace and salvation;
for the true sense and enjoyment thereof, doth certainly out-balance and far exceed,
all the sufferings and trials of the present time, though they are very many and deep.

Let none of you be discouraged or shaken in mind at things of this nature,
nor because of the seeming advantage or occasion,
that the wicked and rebellious and envious spirits, or such as are in prejudice,
do take against us, because of that common calamity and late mortality,
which has befallen many of the righteous, as well as the unrighteous,
as to the outward man, in the city of London.
For God`'s testimony and glory shine,
and will shine and break through all these clouds of afflictions,
sufferings and reproaches, with which the habitation of the righteous hath been,
and is encompassed.
Yet the faithfulness and uprightness of many innocent lambs of Christ,
in and about that city, are never to be forgotten,
which so greatly did appear and shine forth in standing to their testimony,
and keeping to the truth in tenderness of conscience and sincerity towards God;
who hath called us to meet together in his fear, and in his everlasting name and power,
with a real respect to his glory and righteous cause,
which is concerned in the obedience of his people,
both in that and all other duties and acts required by him.
Their obedience and spiritual worship, many have not denied or declined,
neither under the trials which have proceeded from men,
nor under those which came from God;
but whether they have been liable to fall into the hands of God or men,
for the proof of their faith,
they have not departed from Him who makes up his jewels through trials and tribulations.
In all these his fatherly care is felt,
and his tender mercy and compassion is seen towards his own,
as to his peculiar offspring, tender babes, sons, and faithful servants, whom he loves,
and therefore chastiseth and trieth, not in anger and fury, but in love,
fatherly care and pity; so that those whose eyes are open in the true light,
and in a right mind and spirit,
have thoroughly weighed the state of the suffering seed among us,
which is in the faith of Abraham, brought forth by the immortal power of an endless life;
considering the faithfulness and godly sincerity of a remnant,
whose life hath testified for God herein, both in doing good,
and suffering for well-doing.
Such who have thus weighed this suffering state, do plainly see,
that neither Satan nor his instruments,
have any real advantage against any of the remnant of this seed,
through any of these trials or sufferings, either from the hands of God or men.
Many have kept their integrity to the last,
and have embraced their trials and afflictions in God`'s tender love,
and have had such unity therewith,
that they have been far from either blaspheming or cursing God,
as the wicked many times have done and will do, when plagues, woes,
torments and pains seize upon them.
Neither Satan nor his instruments have their evil designs answered therein,
as the devil would have had against Job under his affliction,
when he sought to make him curse God to his face.
The truth of our God, and the innocency of his people,
who know the redemption of the soul, which is precious,
shall stand over both men and devils,
inasmuch as the truth is over the devil himself--who hath the power of
death and darkness--even to the confounding and stopping their mouths,
that all who are actuated by the power and spirit of enmity and darkness,
may be convicted, confounded, and left without excuse before the Lord our God,
who will be known to be clear when he judges.

Yea, blessed forever be the name of our God,
who hath given us strength and courage to stand in an evil day,
over hell and death and the devil,
with all his fiery darts and fierce assaults against the righteous.
The Lord hath spared and will spare a remnant, to bear his mark and name upon earth,
and to hold forth a living testimony for his glory and praise amongst the sons of men,
for which many have not loved their lives unto death, but have offered up their lives,
as many manifestly did in that city of London, the last summer,
when such a sore visitation was upon it.
Many offered up life and all for the truth, and their afflicted brethren and sisters;
for whose sakes my soul has been often greatly bowed down and afflicted,
and my bowels yearned for them,
and I was so moved with compassion and brokenness of spirit, that neither life itself,
nor any outward privilege, did seem too dear to me to resign for their sakes.

And though the sickness was so hot in the city and prisons,
some of the persecutors at that time appeared cruel and wicked against the innocent,
to destroy them in these pestilential places of confinement,
in which and also on ship-board--wherein so many were confined for banishment--many
laid down their lives for the witness of a good conscience.
Although the wicked may for a time be lifted up in their wickedness, and insult over us,
because of our deep trials, and the death of so many innocent persons,
yet their being so elevated and hardened against us--who are the people
of the Lord--does but the more make for their own destruction and misery,
as I have often said, and been sensible of.
Their torment, which slumbers not,
is greater than that of many who have died of the pestilence, by which many,
both of good and bad have been removed.
To those that are yet alive and remain in their sins, without taking warning thereby,
it will prove the greatest plague and judgment, who are the least considerate,
being insensible of the hand of the Lord in it, or of their states and conditions.
As to this particular calamity or sickness,
it is in itself not the worst of judgments which God hath in store for a sinful,
provoking, rebellious people or nation;
and God`'s controversy is not yet ended in this nation,
nor the vials of his displeasure emptied upon his
enemies and the persecutors of his seed.
What a sure and heavy judgment is it,
and what misery does it presage to many in this nation,
that so many innocent or righteous persons in it should be taken away,
as those of whom the world is not worthy; but such are taken away from the evil to come,
and from future calamities, and set in safety forever,
from them that have puffed at them, and made a prey of them in their life time.

And as for us that yet remain, who fear the Lord and stick close to him always,
eyeing and setting him before us, in the greatest of our perils and sufferings,
we know his goodness endures forever,
though the mighty and exalted of the earth boast and insult for a time over us;
but the more the suffering is,
the greater will be the consolation and glory to them that continue faithful to the end.

And whatever conclusions are brought forth against us, either by wicked men,
or any who in prejudice turn against us,
and take occasion from the mortality which has come upon
so many Friends in the time of this great calamity,
as if it were in God`'s wrath, indignation, or fury against the body of Friends,
or any of us who are come to the communion of the body of Christ,
which we are members of; or if any that profess the name of the Lord be so clouded,
biassed and prejudiced in their minds,
as to conclude this is a fulfilling of some such
prophecies of wrath and indignation against Friends;
such spirits and evil tidings are plainly seen, and they to be presumptuous,
and no prophets sent of the Lord; and therefore cannot make us afraid,
who confide in the name of our God,
and in that living faith wherein our unity and victory stand.
Our innocent life stands over them in true judgment, against all that,
which among some has crept in at unawares,
to create divisions and enmity against the faithful servants or people of God,
where it is received in any unstable or brittle spirits; and therefore my soul saith,
the Lord rebuke thee Satan, who envies the heritage of God.
Why dost thou subtly present thyself amongst the sons of God, to trouble the innocent,
endeavouring,
with thy fiery darts and temptations of this nature to turn them against their Maker?
Why dost thou subtly make use of instruments in this thy wicked work,
to effect thy treacherous designs?
The Lord will rebuke thee by his mighty power;
for we are sure that where God`'s faithful witness in the conscience is owned,
which ought to be judge in the case, and must decide the controversy,
it does bear witness with us and for us,
and to the justification of all the faithful amongst us, who are really of us,
and belong to the seed of election; and therefore will not go out from us,
who abide in the truth of God which changes not,
being of the seed of Jacob after the spirit,
which is beyond revolting Israel after the flesh.
For herein are we heirs of promise, and then who shall condemn or prophesy wrath,
where God justifies, and not bring condemnation on themselves?
For God`'s love was felt by many under that trial and visitation,
of which they died about that city,
and many were sensible of God`'s love and favour to the very last.

And the life, peace, satisfaction and comfort that many innocent Friends felt,
and that some expressed and signified on their death beds, I am a living witness of,
for them; having sometimes, as the Lord hath drawn me in his love,
been present with many of them when they were very low in the outward man,
and with divers when upon their death beds, in that destructive prison of Newgate,
and some other places.
Yea, when sorrow and sadness have seized upon my spirit,
and my heart and soul have been pierced and wounded when
I have seen the sad sufferings of so many harmless lambs,
on their sick beds in these noisome holes and prisons;
yet at the same time having a deep sense and knowledge
of the Lord`'s love and care to them in that condition,
and truly felt his life and power stirring amongst them; this, on the other hand,
has refreshed and revived my spirit,
knowing that Christ their salvation and redemption was manifest to and in them,
though in that suffering state,
as they have followed and obeyed him through sufferings and tribulations.
With such, to live, was Christ in that state, and to die was gain;
it being through death that the Lord had appointed the final deliverance of many,
from the cruelties and rod of their oppressors, and from the miseries and evils to come.

The faithfulness, uprightness, and innocency of divers of those that were taken away,
their constancy of spirit to the Lord and his living truth,
their unfeigned love to the brethren--by which it was evident they
had passed from death to life,--and that living and faithful testimony
they bore for the Lord in their life time,
being well known and manifest amongst us; their memorial is truly precious to us,
and never to be forgotten;
and we are satisfied that they were counted worthy for the Lord,
and the world was not worthy of them.

And besides some whom God hath restored and raised up again,
who yet remain alive with us, who were under the same trial and sickness,
can testify to God`'s tender love to them;
how freely they were therein by faith given up to the Lord,
under it in his love and favour, which they partook of, either to die or live,
as he should be pleased to dispose of them,
knowing that some that were very dear to the Lord,
even some of his choice jewels and peculiar treasure were removed by it.

So that I must say what I have seen and felt,
that as to the state of faithful Friends in this case,
some by faith according to the will of God were given up,
and desirous rather to die than live; and therein freely embraced the outward affliction,
which was but for a moment, in comparison;
knowing that to die would be a great advantage and gain to them,
that thereby they should be freed from future sufferings and evils,
and their spirits should rest in everlasting peace, joy and triumph.
Others by faith were singly given up in the will of God to die,
if he should so dispose of them, not in themselves expecting life or recovery,
and yet in so being given up, have been restored, to bear their testimony amongst us,
having known and felt that in patience to resign to the will of God in self-denial,
abasement and humility in their affliction, was most consistent with their peace.
And some others of us by faith according to the will of God,
have been kept over the distemper, and hitherto preserved alive;
not for any respect that we may assume to ourselves in the matter, nor for any reason,
as I know,
that can be shown for us more than for some innocent persons that were taken away,
but that the Lord had a respect to his own glory and further service for himself,
which he had for us to do and be employed in;
and that he will preserve a remnant as he hath determined,
to bear his name and hold forth his testimony amongst men,
in their innocent lives and holy conversations.
The glory and praise we give to the Lord,
desiring all of us may faithfully serve him in godly fear and true humility,
the days we have to sojourn here, that we all may ever be to his praise,
in whose hand we are, whether we live or die.
For he makes all things work together for good, to them that love Him,
who are not offended in Him in any of their tribulations or temptations,
when the hour of temptation is upon all flesh,
to try them that dwell upon the face of the earth.
He that has committed unto us the word of his patience, who is Israel`'s keeper,
is our preserver, support and refuge through all these things.
He has made us co-workers together in one and the same spirit of faith and life,
wherein he is obeyed and submitted to,
by his faithful people and servants in their several states, trials and exercises;
and among whom the various effects and fruits of
the same faith are seen and brought forth,
according to his will, who gives life and preservation.

And now, if such as take advantage against us,
whether they be open or secret smiters or enemies,
did either rightly or seriously weigh their conditions,
and let God`'s witness judge in the case, they have no cause to boast or insult over us,
for they are not their own keepers, nor is their life continued by their own power;
and how soon their time may expire, and their judgment overtake them, they know not,
nor how soon their days may be cut asunder.
Their condemnation slumbers not,
who in the pride of their hearts and presumption of their spirits,
turn against the suffering seed of God, under what profession and pretence soever,
though under pretence of the name of the Lord, or profession of the truth itself;
and knowing also, that many who were of their own spirit and principle,
have also been taken away under the same calamity--for it has extended to all sorts,
both holy and profane--they have cause to dread and fear before the Lord,
and not to be high-minded or presumptuous.
For the mouth of the boaster and exalted must be stopped,
and all flesh and carnal reason is to be silent in this matter,
for God`'s power is over it all,
and over that which has threatened or brought evil tidings against his Israel.
We know the same spirit that turns against us, and watches for occasions,
and prophecies our destruction, would have it come to pass,
so as to be reckoned a true prophet; and that is the murderer that kills the poor,
the same that is in our open enemies, and the same that was in Cain against his brother;
and he that is in this spirit, or principle of enmity or prejudice,
hath no eternal life abiding in him.
O let this thing be published in the ears of God`'s people,
and let friends feel my innocent intention and end herein;
having written the more of this nature for prevention of
the enemy`'s subtlety and temptations of this kind,
that the tender and weak may not be ensnared thereby;
and having seen how Satan besets such with temptations upon these deep trials,
to undermine their hope, and to beget unbelief and despair in the mind,
to turn them from the truth, and how he makes use of his instruments in the same way,
to effect his evil end against us; but the Lord will rebuke him,
and bruise him under the feet of his own anointed seed and faithful people.

A common calamity or distemper, as this, which has brought such great mortality,
as it hath been appointed and permitted of the Lord,
has extended and operated according to the spreading
and contagious nature and property of it,
to the bodies of both old and young, good and bad, nocent and innocent; yea,
to many that know not their right hand from the left.
But the iniquities and abominations of the wicked
were the cause of God`'s anger and displeasure herein,
and the original cause of this calamity;
the creation being oppressed under their wickedness,
and the earth defiled under the inhabitants, which cause Heaven to frown upon the world,
and the curse to go forth, and blessings to be withheld from them.
The taking away of good and merciful men, and many innocent persons,
though it be in love to themselves, yet it is in judgment against the other,
who have brought innocent blood upon their own heads,
by their cruelties and persecutions,
and whose hearts are hardened and become implacable against truth and righteousness,
and all them that walk therein, whose souls have been daily vexed and oppressed,
through the ungodly and unchristian conversation of the wicked.

God, who spared not his own Son Christ Jesus, but delivered him to suffer,
and to be numbered among transgressors, both in life and death,
and his soul to be an offering for the offences of many;
hath also given many of his dear children not only to believe on,
but also to suffer with, his own Son.
He hath borne our griefs and sorrows,
and with him he has suffered them to be reckoned and numbered among transgressors,
both in their life and death,
that his followers might bear his reproaches and partake of his sufferings,
who made his grave with the wicked, and with the rich in his death.
And they were esteemed as smitten or plagued of God,
though as to their own conditions it is, and will be well with the righteous forever,
having obtained witness thereof, and their justification from the Lord God,
by whose righteous witness it is known and manifest in secret in men`'s consciences,
where he visits in wrath, or distributes sorrows in his anger, and where he visits,
tries, or chastises in love, favour, and tender mercy.
This witness discovers where the guilt of sin and disobedience is, where deceit,
treachery and revolting from truth are, which occasion terrors and fear of death,
and which incur the anger and wrath of God upon the guilty therein,
and also bring suffering upon the tender and innocent.
These knowing the guilt taken away,
every affliction and trial that they meet with is sanctified to them,
through the tender love and favour of God, wherewith their cup is mixed;
the dregs of which their implacable enemies and persecutors shall drink without mixture.
Now the difference of the two states is felt and discerned in the invisible spirit,
by that which judgeth not by the sight of the eye, or hearing of the ear,
nor barely from the outward appearance of common afflictions--which sometimes
come alike upon all--but in righteousness and truth that judgeth.

As it hath been said of old, concerning the righteous,
whose souls are in the hand of God,
that in the sight of the unwise their departure is taken for misery,
and their going from us to be utter destruction, but they are in peace;
for though they be punished in the sight of men, yet is their hope full of immortality;
and having been a little chastised, they shall be greatly rewarded; for God proved them,
and found them worthy for himself; as gold in the furnace hath he tried them,
and received them as a burnt offering.
Yea, such are they who shall judge the nations and have dominion over the people,
whose Lord, that takes care for his elect, shall reign forever.

Now my dear friends and tender hearts, commit your way to the Lord,
and cast your burden upon him, and he will bear you up,
and sustain you by his own right hand of power.
Live in the immortal seed and spiritual communion,
where life and peace are daily received,
and your mutual refreshment and consolation stand,
and wherein the spirits of just men are seen and felt,
and the life of God`'s faithful servants and martyrs,
and such as have finished their testimony with joy and peace, is enjoyed,
even in this spiritual communion, which reaches beyond all visibles,
and is above all mortal and fading objects or things.
So in the dear and tender love of God, which dwells and lives in my heart towards you,
and all the faithful everywhere, I commit you to Him,
in whom our help and deliverance are; and in the kingdom of Christ`'s patience,
I am your dear and faithful friend and brother,

[.signed-section-signature]
George Whitehead.

[.postscript]
====

Let this be read distinctly,
in the life and authority of God--from whence it
came--among Friends in and about the city of London,
and elsewhere, as any Friends are moved in the life.

====

--
