== Chapter XI

[.section-summary-preface]
The religious assemblies of the people called Quakers, vindicated; first,
from the charge of their being in disturbance of the public peace.
Secondly, from the charge of being seditious conventicles, mentioned in the act of 22 Car.
2+++.+++ Thirdly,
from the charge of being under colour or pretence of an exercise of religious worship,
in other manner than is allowed by the liturgy or practice of the church of England.

To the first objection, we may ask our adversaries what matter of record^
footnote:[5 R. 2, c.7, 15 R. 2, c.2.]
they can justly make against us, the said people, of due conviction,
either from any notorious evidence of fact, or testimony of credible persons,
or confession of our own, as the law provides; of any formidable posture that we meet in,
as that of force and arms, or any menacing words or threats made by us,
or of any contrivance of insurrection,
which in the eye of law and reason might be deemed
or construed to be to the terror of the people,
or in disturbance of the public peace, or of the nature of a riot?
If such,
should not the matter and circumstances of the fact
be specified upon such record as the law enjoins?
But we utterly deny that we ever met in any such formidable posture as is of
the nature or tendency of what the law deems to the terror of the people.
We meet peaceably to wait upon, and really to worship and serve the Almighty God,
as is our bounden duty, according to his grace and light, and the understanding,
which he hath given unto us by his spirit.

In the second year of Henry the fifth, chap.
8, it is provided, that if any riot, assembly, or rout of people, against the law,
be made in any part of the realm, then the justices of the peace,
three or two of them at the least, and the sheriff or under sheriff of the county,
where such riot, assembly, or rout shall be made hereafter,
should come with the powers of the said county, if need were, to arrest them,
and them should arrest; and the same justices, sheriff, or under sheriff,
to have power to record that which they have found
so done in their presence against the law:
and that by record of the same justices, sheriff, or under sheriff, such^
footnote:[5 R. 2, 7. 1 R. 2, 2.]
trespassers or offenders, should be convicted in manner and form,
as is contained in the statute of forcible entry, etc.
And in the same statute it is provided,
that like ordinances and pains should hold place and take effect in cities, boroughs,
and other places and towns enfranchised, which have justices of the peace within them.

Now let our adversaries and persecutors answer us;
where could any of them ever justly make any such
legal and due conviction upon record against us,
for any such riotous meeting or unlawful assembly on our parts,
as has been really in itself of such a nature and tendency as aforesaid,
in disturbance of the public peace?
We positively deny that our assemblies are of any such nature,
however misrepresented by our adversaries.

If it be alleged that our meetings or assemblies are contrary to law,
and therefore in disturbance of the public peace;
we question what law or statute they are contrary unto.

If it be answered, they are contrary to an Act which is both mandatory and penal,
made in the two and twentieth year of King Charles the second, entitled,
An Act to prevent and suppress seditious conventicles:

We answer; That our assemblies are no such seditious conventicles, i. e. for sedition,
strife and rebellion against the government.
It is a mere begging the question, to term our assemblies seditious;
no such thing has ever been proved against them as sedition,
that is a stirring up to rebellion or discord, a raising a faction or mutiny,
as Philips in his New world of words explains it,
but our assemblies are for no such design or end,
nor could ever any overt act of that kind or tendency be proved,
or justly charged against us, in relation to our meetings, or otherwise.
Therefore they are no seditious conventicles or assemblies.
Our assemblies are made up of no such persons or people,
as have committed any such dangerous practices against the government,
as mentioned in the preamble of the said act--though
rude informers and disturbers have come riotously,
and with violence against us into our meetings--neither
are we any such seditious sectaries or disloyal persons,
who under pretence of tender consciences,
have or may at their meetings contrive insurrections;
as also in the preamble of the said Act is specified:
We use no pretence of tender conscience for any such wicked end or design.
The all-seeing and heart searching God knows our innocency and clearness herein;
as also the nation`'s long experience can witness for us.
And if titles and preambles of laws be the keys of laws,
and do evince or show the nature and respective intentions thereof,
then the said Act against seditious conventicles,
where under pretence of tender consciences, insurrections have been or may be contrived,
doth not extend to us.
We pretend nothing but what we really intend,
viz. the spiritual worship and real service of Almighty God, who searches our hearts,
and whom we sincerely reverence and fear.

But if it be objected, that the matter of fact,
incurring the fines and penalties of the said Act against conventicles,
is our meeting under colour or pretence of an exercise of religious worship,
in other manner than according to the liturgy and practice of the Church of England,
or in other manner than is allowed thereby:

We answer, that the words colour or pretence have relation to the preamble,
as who under pretence of tender conscience have,
or may at their meetings contrive insurrections, as late experience has shown.
But such pretence or colour of religious exercise, for any such contrivance,
were abominable deceit and hypocrisy, and never chargeable upon us or our assemblies.
We can challenge the whole world to detect us herein.

We are not conscious to ourselves of any such deed
committed in our assemblies and on our part,
which the liturgy or practice of the church of England allows not.
If we be herein charged, let us know what it is that we have done in our assemblies,
which the liturgy and practice of the church of England allows not of;
seeing the liturgy allows of the holy Scriptures,
which we are sure allow of and enjoin Christians assembling
together to wait upon and worship God in spirit and in truth,
and of the manner thereof, as to the places, whether in houses,
or abroad in fields or mountains, which is our case,
both as to the matter and manner of our assemblies.

If it be still objected,
that our meetings are under colour or pretence of an exercise of religious worship,
in other manner than according to the liturgy and practice of the church of England:

We answer; What that exercise of religious worship is,
that is in other manner than according to the liturgy, should be explained unto us,
and that according to law, seeing this late Act against conventicles,
does not explain what manner it is.

But we find in a statute made in the first year of Queen Elizabeth, chap.
2, that that other manner is thus explained, viz:^
footnote:[What other manner the liturgy allows not.]
"`That if any person or persons whatsoever, shall by open fact or deed,
or shall by open threatenings compel, or cause, or otherwise procure,
or maintain any parson, vicar, or other minister in any cathedral or parish church,
chapel, or in any other place, to sing, or say any common and open prayer,
or to minister any sacrament, otherwise, or in any other manner and form,
than is mentioned in the said book, etc.`"
This does not at all reach our case, we are not found guilty hereof,
and therefore are not condemnable by the law in this case; this concerned the clergy,
not us.
We neither threaten, compel, cause, or any wise procure, or maintain any parson, vicar,
or any else, to sing or say any common or open prayer,
or to minister any sacrament in any cathedral or parish church.
We are so far from that,
we compel no body to any form of singing or praying in God`'s worship,
but persuade men to serve and worship God as he directs;
and for that end desire all may come to his divine grace and good spirit in their hearts,
to guide them in his holy worship,
both as to matter and manner of praying and praising his name,
that they may serve and worship him, not in the oldness of the letter,
but in the newness of the spirit; for such he is, even in our days,
seeking to worship him, as must worship him in spirit and in truth.
Such both pray with the spirit, and sing with the spirit, and with understanding,
according to the ancient apostolical testimony and
practice of the primitive spiritual Christians.

[.asterism]
'''

[.section-summary-preface]
An account of the people called Quakers, sent to prison by Francis Bacon,
when he was steward, and also since he was recorder;
and those mayors of the city of Norwich,
who joined with him since the late Act against Conventicles came forth.

The 10th of the month called July, 1670, Thomas Buddery, John Rust, Edward Monk,
William Waymor, and Anthony Alexander, were sent to prison upon pretence of a riot,
for telling people as they passed to the mayor`'s house, there were the informers,
when people were inquisitive to know which they were.
They were committed by a warrant from the then mayor, and Francis Bacon, steward,
signifying no crime in the warrant,
but till they could find sureties for their behaviour;
where they were in prison till the sessions,
and an indictment brought against them for a riot;
but the grand jury were found better justices, and would not find the bill.
They were detained prisoners about five weeks.

Samuel Duncon and Anthony Alexander, in the year 1670, made their appeal, where,
instead of having justice done them, Francis Bacon, being judge of the sessions,
did absolutely surprise them by his illegal proceedings,
refusing to give them a copy of the records, and made one witness, being also a party,
serve his turn, while the Act says there must be two.
For which they wrote to the mayor, steward, and court of aldermen,
telling them of their injustice,
and for so doing they were committed to prison by the mayor,
till they should find sureties for their appearance at sessions,
upon pretence of scandalous expressions in their said letter,
who was observed to tremble when he signed the mittimus,
and for it they were kept prisoners about a year.

Thomas Atkins was taken out of a meeting the 17th of the fifth month, 1676,
by constables and informers; and being had before the mayor and steward,
and several aldermen in their council-chamber, some of them were very bitter and cruel,
saying, he should pay his twenty pounds, and they tendered him the oath of allegiance,
and he refusing to swear, they sent him to prison,
where he was detained about fourteen weeks.

Thomas Murford had his doors broken open by a constable,
having a warrant from the recorder, for twenty pounds.
Thomas not being at home, he made his appeal when he came home;
but the recorder being judge, and having a jury for his purpose, carried the case,
and from the court committed Thomas to prison, where he was detained twenty weeks.

Simon Gogny was sent to prison the 16th of the first month, 1678, by the recorder,
till he should find sureties for his good behaviour;
because Simon spoke something to him by way of warning,
when he came himself to break up our meeting, telling him of Empson and Dudley;
he was detained eight weeks.

Thomas Buddery was sent to prison by him the 30th of the first month, 1679,
till he should find sureties for the peace, so expressed in his mittimus;
because he answered in defence of truth, in these words, viz:
The service of God is perfect freedom, he was detained in prison over six weeks.

They cannot be ignorant how discouraging and destructive such imprisoning,
spoiling and impoverishing their neighbours, is to the trade of their city,
which in the manufactures much depends upon the wool-combers and worsted-weavers, etc.
And when such poor labouring men are thus spoiled and harassed, as to their livelihoods,
how hard is it for their poor families to subsist?
How can such severities consist either with Christianity or humanity?
Let the principle of justice in all consciences judge:
and may those guilty of such oppressions, repent before they die.

[.asterism]
'''

[.embedded-content-document.address]
--

[.blurb]
=== A copy of an Address from our suffering friends in Norwich, in the year 1679, directed to the knights and burgesses for the county of Norfolk, and city of Norwich. The suffering case of some of the people called Quakers, in the said city.

The goods of several have been taken away, without their being tried by their equals,
only by witnesses in their absence, which was given against them by such as were parties.
When some appealed, and desired a copy of the records,
which were sworn in their absence before their trial, they were denied it.
The recorder who sat for judge of the sessions, would not let the evidence be viva voce,
but made the records, which he would not grant a copy of before the trial,
the only evidence against some appellants, and put them upon disproving that,
and so surprised them; and for complaining of the injustice of it,
two were sent to prison, and kept prisoners about twelve months.
Another that made his appeal, Francis Bacon sent to prison, who asking him,
wherefore he was sent to prison, told him, he should know afterwards;
and he was kept close prisoner eighteen weeks.
John Crow, an attorney, upon warrant from Francis Bacon against Samuel Duncon of Norwich,
on account of a meeting, got into Samuel`'s house when he was from home,
shut up his shop, and he and others kept possession of his house night and day,
to the terror of Samuel`'s wife, and took away his goods;
and when one would have taken account of the goods, John Crow would not suffer it;
but they rather acted like plunderers, than executors of justice.

Francis Bacon slandered the people called Quakers, as being Papists and Jesuits,
exciting the jury at the sessions in Norwich, to bring in presentments against them,
upon which some have been arrested upon a session process for twenty pounds per month,
for not going to the parish church.
He lately prosecuted them for meeting to worship God,
and sent two to prison that he took at meeting,
who were kept prisoners nearly eight weeks in a stinking hole.
One of them he sent to prison without a warrant, and it is said,
threatened to seize upon their house,
and press the constables to execute warrants from him against some of this people,
to take away their goods, and told them, they must break open their doors.

Upon the 19th of the third month, 1679,
two constables came to the house of William Waymor, with a warrant from Francis Bacon,
to distrain for ten pounds five shillings; who unbarred his shop door,
and an inside door being locked, broke it in pieces,
and took goods to the value of ten pounds and better, and appraised them at three pounds,
and said, they must come for more upon the same warrant.
This great spoil is made upon us by mercenary witnesses in our absence,
and given against us, and we thus oppressed by such as are parties.

This kind of procedure, we conceive with submission,
is not more excusable now than it was in the case of Empson and Dudley,^
footnote:[These two oppressors, Empson and Dudley,
were impeached before the court of Parliament for their arbitrary
proceedings and horrid oppressions which they committed,
upon information for the king, having many informers to assist them,
without lawful presentment, trial of lawful peers, or verdict of twelve honest men.
They acted under pretence of a law made in the eleventh year of King Henry VII. c. 3.;
which being contrary to Magna Charta, cap. 29, was made void and repealed, 1 Hen. 8., cap.
6, by the Parliament holden then, and the two oppressors brought to their trial,
condemnation, and execution.
See Coke`'s Instit. 2 part. fol. 51, and 4 part. fol. 40, 41.]
in King Henry the seventh`'s time,
who were impeached and condemned for their arbitrary proceedings--though they pleaded
the prosecution on an Act of parliament--and to be of as dangerous a tendency.
Thus some to gratify their prejudice, others their covetousness,
under pretence of prosecuting the late Act against seditious sectaries,
have very much oppressed the subjects;
and what is charged upon the prosecutors aforesaid, can be proved if required.
Wherefore we entreat your tender consideration of this our suffering condition,
and endeavour for our relief.

[.signed-section-signature]
Signed by Samuel Duncon, and fifteen more of the citizens and inhabitants of Norwich.

[.signed-section-context-close]
Norwich, the 23rd of Third month, 1679.

--

It was very observable that before the dissolution of that long parliament,
in King Charles the second`'s reign,
which made the three Acts before mentioned against us,
there was a great alteration in their spirits, being much turned against persecution,
or persecuting dissenting Protestants,
especially by those laws made against Popish recusants;
and there was certainly an overruling power and hand of the Lord God,
in that alteration and change of the spirit of that parliament, to compassion,
rather than persecution.
He that standeth in the congregation of the mighty, and judgeth among the gods,
did certainly judge and plead for the cause of the innocent sufferers
under the great and long persecutions that had been upon them.
And it was also remarkable, that some time before the said long parliament was dissolved,
many, or most, of our old adversaries, and rigid persecutors therein,
were removed by death, and new members, of better spirits and tempers,
chosen in their room; and before that parliament was ended, it was so changed,
that it appeared almost like a new one, I mean the House of Commons.

The ensuing parliaments appeared more and more considerate,
and inclining to moderation and charity towards dissenting Protestants; and such were we,
the people called Quakers, esteemed,
being publicly manifest by our plain testimony against popery.
Towards the conclusion of this long parliament, which was so much altered for the better,
by new elections, a grand committee of the whole House was appointed,
to inquire into the case of the Quakers suffering
by those old laws made against popish recusants;
as they had for a long time been unduly prosecuted
upon those laws made in the reigns of Queen Elizabeth,
and King James the first.
Divers of us appeared before that committee, among whom were William Mead, William Penn,
myself, with some others, and two things were inquired of us,
of which we were to inform the said committee.

[.numbered-group]
====

[.numbered]
1+++.+++ If we owned ourselves to be Protestant dissenters?

[.numbered]
2+++.+++ How we suffered by laws made against Popish recusants?

====

In both which we fully satisfied the committee, and our case was generally resented,
as an unjust, as well as illegal prosecution and suffering imposed upon us;
since we suffered as Popish recusants, when we were manifest to be real Protestants,
and the Papists were indulged, and went free; yet we envied not their liberty,
nor that of any others, although we deeply suffered in their stead.

It was very remarkable,
that while our persecutors were prosecuting us upon the
Conventicle Act and statutes made for Popish recusants,
and unjustly insinuating against, and aspersing our religious assemblies,
as being seditious conventicles, and very dangerous to plot and contrive insurrections,
about that very time discovery was made of the Popish plot, termed,
that damnable and hellish plot, by the good providence of Almighty God,
brought to light above two years since;
as it is declared in the address of the commons in parliament assembled,
presented to the king, dated Monday, the 29th day of November, 1680.

This plot being strictly inquired into by the commons in parliament,
much information was given about it;
and in the address of both houses of parliament to the king,
complaint was made against the conspirators in these words, viz: A Popish party,
who have not only plotted and intended the destruction of your majesty`'s royal person,
but the total subversion of the government and true religion established among us.

From all which it may be well observed,
that it was not in any of the Quakers`' meetings or assemblies,
nor in the meetings of any other dissenting Protestants, that this conspiracy was found,
but among a Popish party.
How unjust was it therefore, so severely to persecute the people called Quakers,
violently to break up their religious meetings,
under pretence of being seditious and dangerous, to plot and contrive insurrections,
to imprison their persons, to fine them, and often to tear away and spoil their goods?
And not only to treat them thus, but severely to prosecute them,
even upon those laws made against Popish recusants, and not against innocent Protestants,
even whilst--as in the aforesaid address of the commons,
it is said--this restless party (meaning of Papists) not
content with the great liberty they had a long time enjoyed,
to exercise their own religion, privately among themselves,
to partake of an equal freedom of their persons and estates,
with your majesty`'s Protestant subjects, and of an advantage above them,
in being excused from chargeable offices and employments, etc.
So that it then appeared to the parliament,
that the Papists escaped the penalties of those old laws made against them,
for their absence from their parish churches,
much more than the people called Quakers could, who deeply suffered thereby.

After the discovery of the Popish plot, and the impeachment, trial, and condemnation,
of William, Lord Viscount Stafford, thereupon, in December 1680,
the parliament thought it very necessary to provide
some means to increase the interest of all Protestants,
and strengthen and unite them in affection,
for the better security of the kingdom and government, which had been long weakened,
and greatly injured by persecution of true Protestants,
while their adversaries were excused.

Then the parliament bethought themselves of preparing,
and bringing in a bill for dissenting Protestants.
In the votes of the House of Commons, the 16th day of December, 1680, there is this, viz:

A bill for exempting his majesty`'s Protestant subjects
dissenting from the church of England,
from the penalties of certain laws, was read the first time.

Resolved, that the said bill be read a second time, on Monday morning next,
after ten of the clock, in a full house.

In the votes of the 21st of December, 1680, it was again ordered,
that the bill for exempting his majesty`'s Protestant subjects,
dissenting from the church of England, from the penalties of certain laws,
be read on Thursday morning next.

In the votes of the 24th of December, 1680,
the said bill for exempting his majesty`'s Protestant subjects,
dissenting from the church of England, from the penalties of certain laws,
was read a second time; and Resolved, etc.,
that the said bill be committed upon the debate of the House to the committee
to whom the bill for uniting his majesty`'s Protestant subjects is committed,
upon the debate of the House.

Divers Friends, myself and some others,
attended the committee some considerable time that winter, about the said bill,
both early and late.
We desired that it might be made effectual for our just liberty and freedom from persecution,
and clear from all clauses and provisoes which any ways might be a snare to us,
or contrary to our tender consciences; and so as to answer the end intended,
and the reason thereof as declared, both by the title and preamble.
The title is, A Bill of ease to all Protestant dissenters; and the preamble thus, viz:
Forasmuch as some ease to tender consciences in the exercise of religion,
may be an effectual means to unite his majesty`'s
Protestant subjects in interest and affection,
which is highly necessary in this time of eminent danger from the common enemy,
the Papists, be it enacted, etc.

This bill contained divers clauses which are in the
Act of the first of King William the third,
for exempting Protestant dissenters from the church of England,
from the penalties of certain laws, i. e., of those made against Popish recusants;
and other laws made against conventicles, etc.,
whereby we the said people chiefly suffered;
and also in the said bill this special exemption was made in our favour, viz:

And whereas there are certain other persons dissenters from the church of England,
who scruple taking any oath: Be it enacted by the authority aforesaid,
that every such person shall make and subscribe the aforesaid declaration,
and also this declaration of allegiance following, etc.

The first being the declaration mentioned in a statute,
made in the twentieth year of King Charles the second, entitled,
An Act to prevent Papists from sitting in either house of parliament.

The second being the declaration of allegiance, without taking the oath,
or swearing to it; which divers Friends have formerly proffered,
when prosecuted for not taking the oath of allegiance.
They have been willing to sign the declaration without swearing to it,
or using any of the words in it, which render it an oath, as +++[+++I swear this oath, etc.,
or the final imprecation of, So help me God]
which more fully makes it an oath, together with the kissing and fingering the book.

As we were to be exempted from these, we esteemed it a favour then intended us;
though that which was then so much laboured for,
could not in that parliament and reign of King Charles the second,
be brought into an Act; yet there was an honest and good beginning; which afterward,
in the reign of King William the third,
upon more mature deliberation was brought forth in better shape and more effectual.

The chairman of that committee, which sat upon the said Bill of Ease, was Lord Finch,
since Earl of Nottingham, who then appeared favourable and friendly to us,
and for passing the said bill into an Act, if it could have been in that parliament;
and to some of us since that,
he has positively declared his opinion to be for the toleration, i. e.,
the ease of all Protestant dissenters, without which,
neither we nor their church are safe.

In the said committee we met with some interruption by two or three members,
who were favourers of the Presbyterian and Independent Societies.^
footnote:[Col.
Birch and some others.]
They offered terms of ease intended by the said bill, in behalf of their friends,
the Presbyterians and Independents, which we the people called Quakers,
could not assent to, namely the taking the oaths of supremacy and allegiance.
And if they had gotten what they offered, inserted in the Bill or Act,
as terms of ease to dissenting Protestants,
we well knew we should thereby have been excluded
and still exposed to persecution and sufferings.
And we believed that some of the other dissenting Protestants,
which these said members seemed to represent,
were more conscientious than to accept those terms for their ease,
which the said members offered for them, in their behalf;
especially that of taking the oath of supremacy.
I was indeed burdened when they made such an offer,
because I was sensible it tended both to our injury and
the injury of many other conscientious Protestant dissenters.

Wherefore on the same occasion I quickly went both to Col.
Birch and Alderman Love, and cleared my conscience to them,
against what they had offered for a condition of ease to Protestant dissenters;
knowing it would be very uneasy to truly conscientious dissenters,
to have the oath of supremacy imposed upon them; and thereby to swear,
that they utterly declare and testify in their conscience,
that the king`'s highness is the only supreme governor of this realm, etc.,
as well in all spiritual, or ecclesiastical things, or cases, as temporal, etc.
How to reconcile their dissenting in spiritual,
or ecclesiastical matters from the church of England, with this oath, I knew not,
nor did I find they could tell, or demonstrate.
And further by the said oath to promise,
that to their power they shall assist and defend all jurisdictions, privileges,
preeminences, and authorities granted, or belonging to the king,
his heirs and successors, or united and annexed to the imperial crown of this realm.

How any could in good conscience swear to all this,
or upon oath promise such a defence of all these jurisdictions and authorities,
and yet remain conscientious dissenters from the church of England, does not appear;
neither could the said members of parliament, who made the aforesaid offer,
reconcile themselves in this case.
However, I did both seriously and tenderly clear my conscience in the matter to them,
for I wished well to the men.
After all our endeavours and attendance on that parliament and committee,
to have the said Bill of Ease passed with safety into an Act,
the king`'s dissolving the same, prevented it.

One passage I took particular notice of;
one night when we were attending the said committee,
Sir Christopher Musgrave came and complained to the committee, against the severe usage,
or persecution, of many of our friends;
telling the committee the prisons were filled with them;
and how many for small matters were excommunicated and imprisoned;
and what a shame and scandal it was to their church,
to use the Quakers so hardly for such small matters or occasions;
or to the very same effect.

I little expected he would then have appeared openly
to advocate so far our suffering friends,
being a person who professed much zeal for their church;
yet he saw it was not for the honour thereof, to be guilty of such persecution.

Although that parliament could not effect an Act,
intended for the ease of Protestant dissenters, yet before their dissolution,
they passed a vote against the persecution which then was in being, as followeth, viz:

In the votes of the House of Commons, the 10th day of January, so called, 1680,
it was resolved.
That it is the opinion of this House,
that the prosecution of Protestant dissenters upon the penal laws,
is at this time grievous to the subject, a weakening of the Protestant interest,
an encouragement to Popery, and dangerous to the peace of the kingdom.

Being sensible that after a long persecution,
the Lord was pleased to open the eyes of the parliaments,
to see what a Popish design it was, for a Protestant church, so called,
to persecute Protestants,
we were the more concerned at that time to attend the parliament,
and to encourage their endeavours against persecution; to frustrate the design of Popery,
which is persecution and violent coercion; the principal pillars of Popery.
The zeal then stirring in the government against the same, deserved to be countenanced,
though it had not the desired effect at that time, so as to remove persecution,
and the great oppressions thereby.

However just and good motions and endeavours may for a time be overruled and frustrated,
they will in time revive and break forth again, and be made to take effect,
by a divine overruling power and providence;
as in this case of liberty to tender consciences, has in our days appeared.
Thanks be to God, who has opened the eyes of the government on sundry occasions,
especially in latter times, against Popery and persecution,
which are both one in nature and ground; for persecution for conscience is Popery.
Whatever church, people, or profession, are for it, or abet it, they are drunk and blind.

Another instance of the parliament`'s design and endeavours to remove persecution,
was the passing a bill in both Houses,
entitled An Act for the repeal of a statute made in the
thirty-fifth year of the reign of Queen Elizabeth;
and taking notice thereof in the ensuing parliament at Oxford,
in the vote of 24th day of March, so called, 1680-1,
that it was not presented to his majesty, as the rest of the bills were,
for his royal assent.
And also it was resolved, that the House would next day take into consideration,
by what means the said bill miscarried.

According to which order, in the next day`'s votes, it is declared,
that the house took into consideration the matter relating
to the bill which passed both houses in the last parliament,
entitled.
An Act for the repeal of a statute made in the thirty-fifth
year of the reign of Queen Elizabeth,
but was not tendered to his majesty for his royal assent.

How this bill came to miscarry, we did not hear, whether designedly mislaid or stolen;
it was a pity that it was not presented and passed, as both parliaments desired, viz.,
that in 1680, at Westminster, and that at Oxford, 1681.
For if the said statute of the thirty-fifth of Queen Elizabeth had been utterly repealed,
it had given a blow to the design of persecution, and Popery,
which is greatly strengthened and the spirit of persecution gratified thereby;
it being a precedent and plea for the Popish church
to use their most severe persecution against Protestants,
even unto death, for their religion and dissent from the church of Rome.
The said statute of the thirty-fifth of Queen Elizabeth,
is a sanguinary law to force dissenters to abjure the realm upon pain of death,
and in her days several were put to death.
There appears as much reason that that severe and sanguinary law should be disannulled,
as there was for the writ for burning heretics, and all proceedings thereupon,
with all punishment by death in pursuance of any ecclesiastical censures,
which were abolished by the statute of the 29 Car. 2. ch. 9.

For as the persecuting Popish hierarchy and governments unjustly
turned the execution of the said writ against the Protestant martyrs,
so they were as likely to turn the said statute of
Queen Elizabeth against the Protestant dissenters,
and there was the same reason for the repeal of the one as of the other,
both being sanguinary,
and executed to the gratifying of the spirit of Popery and persecution.
The bill for the repeal of the said statute of Elizabeth miscarrying,
and not being presented for the royal assent, was judged a Popish design,
to reserve such a cruel instrument for further persecution against dissenting Protestants.

However, it was a mercy of God to the nation,
to raise up a contrary spirit to that of persecution,
even in the parliament in those days.
And yet that furious spirit remained among many of the clergy,
and the irreligious followers and members of their church,
who were still watching for opportunities to renew persecution against honest,
innocent people, especially against us,
and to enforce a conformity in church and worship with them, contrary to our consciences;
we being under a divine obligation to worship God in spirit and in truth,
and not in human traditions, after the commandments, doctrines, or precepts of men.

It is true we had some times of respite from severe persecution in those days,
upon the king`'s said declaration for liberty to tender consciences,
and the parliament`'s resentment against prosecuting dissenting Protestants,
upon those old laws made against Popish recusants, as being deemed a Popish design;
yet those times of ease were but short,
in comparison with the long continuance of the renewed
persecutions which we suffered in those days.

Informers, like beasts of prey, were lurking and creeping about in many,
or most parts of the nation, where our friends had meetings for the worship of God;
those mercenary agents being encouraged by those of the clergy and persecuting magistrates,
who esteemed them useful servants of their church,^
footnote:[William Crouch and I, Anno 1683, having some discourse with Dr. Sancroft,
Archbishop of Canterbury, at his palace at Lambeth,
about the great sufferings of our Friends by informers,
and I telling him what wicked persons they were,
and that many of them had forsworn themselves, and deserved to be indicted for perjury;
and what a dishonour it was to their church,
to employ such agents to force people to a conformity by persecution and spoil, etc.
To excuse them, his answer was,
There must be some crooked timber used in building a ship: or,
a ship cannot be built without some crooked timber in it.
Was not this a learned and apt comparison,
to show what sort of timber must needs help to build and support their church?
{footnote-paragraph-split}
Though
crooked timber be the most useful in building a ship,
surely the mercenary informers, who are for making spoil and laying waste,
are not so in the church of Christ.
What church is it then,
that is now in danger--as the complaint is--when it wants such
crooked timber as the devouring informers to support if?
Is their being now restrained, the reason of such danger?
This point should be well considered.]
to enforce conformity, though without conviction of conscience.
Several of the priests also turned informers,
and assisted to disturb our friends`' religious meetings in divers places,
all which ministered encouragement to such vile persons,
in their unchristian and destructive work against innocent families and people.

Some of the priests even pleaded for,
and preached up coercion in matters of religion from those texts, Ezra 7:26.
and Rom. 13:1-2., though miserably perverted,
when applied to uphold persecution for matters of conscience,
comparing both texts with the decree of Artaxerxes, king of Persia,
and the great encouragement and liberty of conscience which he granted,
and gave to Ezra and Israel, with respect to the worship and service of their God,
according to their religion and persuasion; as fully appears in the same chapter.
The texts relate to the power, rulers, or magistrates, as God`'s ordinance,
for the punishment of evil doers, and the praise of them that do well;
and not that Christians, or believers in Christ,
should subject themselves in point of religion and worship to the wills,
decrees and edicts of all sorts of rulers and governments in the world,
so as to be of their religion and persuasions, or subject to their impositions,
ways and manners of worshipping God, or idol gods, set up by any of them.
Surely if that had been the apostle Paul`'s and the other apostles`' meaning,
there had been no Christian martyrs, or sufferers for Christ Jesus.

But if an emperor, king, or chief ruler, be a Papist or an idolater,
and would force me to be of his religion, or conform to his way and manner of worship,
upon some great penalties or pains, even of death itself,
I must not therefore comply with him, or be subject to his will and humour therein,
if I be a true Christian,
but stand fast in that liberty wherewith Christ hath set me free,
or otherwise I should fall under miserable bondage, and forfeit my inward peace with God.
And then what good would all the world do me?
I would rather make Moses`' choice, to suffer affliction with the people of God,
than to enjoy the pleasures of sin for a short season,
and at last end in tribulation and anguish of soul.

It was observable,
that when the informers were let loose and countenanced by authority against us,
they generally sought more after our estates than the confinement of our persons,
because imprisonment would not be for their gain,
although many of our friends remained in prisons, according to the following petition.

[.embedded-content-document.address]
--

[.letter-heading]
To The King.

The humble petition of above a thousand prisoners, commonly called Quakers; Showeth,
That our renewed hardships, our continued and increasing imprisonments,
do occasion this our humble complaint and request,
of which we entreat the king`'s favourable acceptance, and tender resentments.
We do solemnly declare, that we know no other cause for our strait confinement,
and hard usage,
than what concerns our tender consciences in serving
and worshipping Almighty God that made us,
being well known to be persons of quiet conversation and peaceable behaviour,
and clear in the sight of God, of all seditious contrivances, plots and conspiracies,
and are not evilly affected towards the king`'s person or government.
Howbeit, several jails are filled, without regard to sex, age, or condition,
not only to the impairing our healths, but endangering many of our lives;
many having already died prisoners,
the greatest part of late being committed for our peaceable, religious meetings;
many of us under fines on that account; and upon the Act of 13 and 14 Car.
2, c. 1, extending also to banishment.
In some jails, many of us crowded in nasty holes, and mixed among felons;
many under sentence of premunire, not for refusing fidelity or allegiance to the king,
but only for not swearing the same for conscience sake:
many are under sentence of excommunication, committed on writs of excom, cap, etc.,
for nonconformity, etc., and have undergone long and tedious imprisonments.
By which confinements and hardships,
many innocent and industrious families are left destitute and in distress;
many honest tradesmen, husbandmen and farmers,
are greatly discouraged and spoiled in their trades and livelihoods,
and many poor families depending on them for employment,
now for lack thereof are exposed to great penury and want;
besides the violence and woful spoil made upon many, both in city and country,
by informers, prosecutions, etc., and for twenty pounds a month,
and two thirds of estates seized into the king`'s hands, etc.,
which will unavoidably force many to shut up their shops,
and leave off their trades and farms, etc., as some have done already,
if not timely relieved.

We therefore, who are concerned in the sufferings aforesaid,
do in all Christian humility request that the king in his princely compassion,
will please to take our distressed case into his tender consideration,
and afford us relief from these hardships and imprisonments,
as he hath formerly done for many of our suffering friends,
which we do thankfully acknowledge, we being sincerely designed by the grace of God,
to live peaceably and inoffensively under the king and his government.

Wherefore,
according as our conversations are found concurring with this our solemn profession,
we humbly crave liberty, that we may provide for our distressed families,
and be capable to render to Caesar those things that are Caesar`'s;
and to God the things that are God`'s;
according to our Christian principle and persuasion.

--

We did not only in this manner,
labour to influence the king with a sense of the general case of our friends`' sufferings,
but also gave him instances thereof, in divers notorious and crying cases,
of manifest hardships and inhuman usage;
in which concern I was many times very free to appear before the king himself;
especially when desired to assist such friends as were concerned for the sufferers,
when they have come to London to apply to him in their behalf.
And when we have had certain accounts of our friends`' sufferings
and great oppressions sent from several parts of the nation,
I have been stirred in spirit, and desirous to acquaint the king therewith,
that he might at least be inexcusable,
and not plead ignorance of those his innocent subjects`' miseries.

In appearing before the king and council, our friends Lawrence Steel and Charles Jones,
Jr., of Bristol, were with me, being come to London to seek relief for our friends,
who were then closely crowded in prison in that city.
Being willing to assist them what I could,
as I was deeply affected on account of our friends,
when I understood their extreme suffering condition, I acquainted prince Rupert,
the Lord President, and the Lord Chancellor, with the case,
and desired we might be heard before the king and council the following council day,
which was granted us.
Prince Rupert and the Lord President appeared most
compassionate and tender toward our friends,
when they understood the extremity of their sufferings,
and the Lord Chancellor was moderate; so that he granted our request,
and we attended the next council day, on the 17th of the twelfth month, 1681-2.

Some question arising about taking off their hats, the clerk of the council,
sir Thomas Doleman, came to the door to take them off, but was forbidden, it was said,
by the king; so it was concluded for them to come
in before the king and council with their hats on;
which they did accordingly.

Some present said, "`Go up to the king, being at the head of the board.`"

George Whitehead then went nearer the king.
Meeting with this slight reflection; "`You pretend conscience:
it seems your conscience is in your hats.`"

[.discourse-part]
_George Whitehead:_
We request that our complaint and suffering case may be heard and considered
abstractly from those religious circumstances we are under,
which may seem disgustful to you, that we may have justice done us.
These persons are come from Bristol,
to seek relief of the king from the hard usage our friends suffer in that city,
beyond the severity of the law, as we conceive.
They are able to speak to matters of fact, from their own knowledge,
how our friends are used in that city; we entreat the king that they may be heard;
and for matter of law, we shall leave that for you to judge of.

[.discourse-part]
_One in council:_ What reason have we to believe their words, against other men`'s oaths,
who are sworn for the king?

[.discourse-part]
_George Whitehead:_
We entreat that they may be heard to give their accounts
on those particulars complained of in our petition,
which is delivered in before you, and I suppose read;
and then we shall refer the credit of the matters complained of to your consciences,
that accordingly we may have justice done us.

[.discourse-part]
_King:_ Your petition is not now read: would you have it read?
It has been read before.

[.discourse-part]
_Lawrence Steel:_ This contains further matter than what has yet been read before you,
+++[+++That was their suffering case drawn up at large, and laid upon the council board.]

[.discourse-part]
_Lord Chancellor:_ Of what do you complain?

[.discourse-part]
_Lawrence Steel:_ We complain of the havock and spoil made upon the freehold and tenement,
and breaking open closets, boxes, etc.

[.discourse-part]
_Lord Chancellor:_ What, you mean of the meeting room?

[.discourse-part]
_Lawrence Steel:_ Nay, the tenement adjoining to the meeting room;
we complain of the rude multitudes haling and tearing women`'s clothes,
and offering shameful incivilities to them;
also of their pulling an innocent man`'s coat off his back,
and taking money out of his pocket, etc.
+++[+++Of this, though he had more to speak, they seemed not willing to hear it.]

[.discourse-part]
_Lord Chancellor:_ Of whom do you complain?

[.discourse-part]
_Lawrence Steel:_ We are loath to criminate persons by name.

[.discourse-part]
_Lord Chancellor:_ But you must tell us who?
Is it the mayor, etc.

[.discourse-part]
_George Whitehead:_ Let them have some of their names.

[.discourse-part]
_Lawrence Steel:_ John Helliar and sheriff Knight, with a rude multitude.

[.discourse-part]
_George Whitehead:_ It appears that the sheriff and John Helliar, and other officers,
have been most busy,
and have encouraged the rude multitude in their abusive and riotous proceedings,
and forced many to jail directly from their meeting, at their will and pleasure,
without any examination before a justice,
or warrant of commitment from any justice of peace;
and then do so crowd and fill the jail,
that the prisoners have not room to take their natural rest;
but some are forced to sit up in the nights, whilst others take their rest.

[.discourse-part]
_Lord Chancellor:_ What would you have the king do?
Would you have him relieve you from the law?

[.discourse-part]
_George Whitehead:_ No: we desire the king may relieve us from such irregular proceedings,
as we conceive the law does not warrant.

[.discourse-part]
_Lord Chancellor:_ Why then do you not take course at law, and relieve yourselves by law?

[.discourse-part]
_George Whitehead:_ The prisoners and sufferers in Bristol,
are disabled from relieving themselves by course of law.

[.discourse-part]
_Lord Chancellor:_ How are they disabled?
What reason can you give that they are so disabled?

[.discourse-part]
_George Whitehead:_ Several reasons, as First; They are prosecuted on the conventicle act,
made the twenty-second year of the king; and all the relief allowed us by law,
is by way of appeal:
and it admits of appeal to no higher court than the court of sessions,
belonging to the same county, which is the county of Bristol,
where there is no probability of relief upon appeal;
because there they must appeal to their adversaries, as some there in authority are;
and John Knight, sheriff, is an extreme adversary, and has been violent against them;
and he has the return of the juries according to his own purpose.

[.discourse-part]
_King:_ Can you not procure a London jury then?
etc.^
footnote:[Supposed to be meant of the jury that acquitted the Earl of Shaftsbury,
and some others upon trial in London.]

[.discourse-part]
_George Whitehead:_ Besides, if they make their appeal,
they are liable to have the oath of allegiance put to them,
to prevent prosecuting their appeal;
for such kind of precipitate course has been used against us.

[.discourse-part]
_One in council:_ He counts the tender of the oath of allegiance a precipitancy, etc.

[.discourse-part]
_George Whitehead:_ No, it is the manner of requiring it, I mean;
when it is done with design to anticipate the appellant,
and prevent the trial of his appeal.

Secondly; The riots and abuses that are committed upon our friends at their meetings,
by tearing women`'s scarfs, beating, throwing persons down, etc.,
which are done by a rude company that are encouraged by the constables and officers,
who should keep the peace.
So that there is none who will arrest or apprehend the rioters, that we know of,
because the officers take their part, and animate them;
and the rioters and abusive persons can readily escape in the crowd,
there being no better notice taken of them by those whose place it is.

The third reason...

[.discourse-part]
_King:_ And thirdly: let us hear the third reason.

[.discourse-part]
_George Whitehead:_ The third reason of their being disabled, is,
for those of our friends that are committed to jail;
though we conceive their commitment irregular,
yet if they should enter actions of false imprisonment against those that committed them,
they may be destroyed in their strait and close confinement,
before they can have relief by a course of law that way;
they being so severely kept under hatches by their adversaries,
if they should enter actions of false imprisonment against them,
that it might be an occasion to them to revenge themselves
the more severely on the prisoners in the mean while.

[.discourse-part]
_One in council:_ Seeing the conventicle act admits of no appeal to any higher court,
than to the same court of sessions for that county,
why do you appeal or make your complaint here?
What would you have the king do for you?

[.discourse-part]
_George Whitehead:_ We desire the king, and you of his council,
tenderly to consider our suffering case,
and how far the king may relieve us from those irregular
proceedings that shall appear beside or contrary to law.

But here George Whitehead was prevented from giving
answer to the objection as he would have done;
That we do not make a formal appeal here, upon the conventicle act, to recover our fines,
and the extortion in distresses;
but for the king to discourage such proceedings for the future, i. e.,
as the law does not encourage.

[.discourse-part]
_Lord Chancellor:_ You would have the king to relieve you from the law,
to interpose between you and the law; which he cannot do.

[.discourse-part]
_George Whitehead:_ No, under favour, Lord Chancellor, that inference follows not,
from what is proposed on our part.
We desire that the king would be pleased to interpose
between us and the destruction that attends us,
through the irregular and extreme proceedings of those persons, who,
whilst they pretend to put the king`'s laws in execution,
and in pursuance of an order from him, exceed all the severity and bounds of the law.
Our present complaint therefore lies not against the law, or execution thereof simply;
but against the mal-administration; against the hard usage,
and exorbitant proceedings we meet withal, contrary to all law and justice,
as we conceive.

[.discourse-part]
_Lord Chancellor:_ Well, we have heard you; you may withdraw.

[.discourse-part]
_George Whitehead:_ May it please the king yet to hear me a little further,
that the king and you his ministers may understand
how probable the truth of our complaint is,
against those irregular and erroneous proceedings in Bristol,
and how incident the justices there are to commit error
in their proceedings against our friends who suffer there,
please to take one instance, viz:

The most of their warrants of commitment, or mittimuses,
whereby our friends are committed to jail, and of which we have here copies,
are defective and wanting in two material points, as;

[.numbered-group]
====

[.numbered]
_First;_ The justices do not therein signify their lawful authority,
as being the king`'s justices of the peace, before whom the prisoners were brought, and;

[.numbered]
_Secondly;_ Their command to the keeper of the jail for safe custody of the prisoners,
is not given in the king`'s majesty`'s name, but in their own private names,
except that there is one named Major, and one William Bristol,
the rest are only in their private or personal names;
no mention is made in their mandamus to the keeper.
That these are in his majesty`'s name to will and require you, etc.,
but only they commit them in their own private names.
This we conceive is irregular and unwarrantable in law;
and this I give only as one instance to evince the probability of the truth of our complaint,
and that those justices are subject to err in their proceedings,
in omitting such material points.

====

[.discourse-part]
_Lord Chancellor:_ Those defects are exceptions pleadable, and they may be heard,
if they remove themselves by _Habeas Corpus._

[.discourse-part]
_Lord President:_ That exception of yours will not serve your turn.

[.discourse-part]
_Lord Chancellor:_ You may withdraw.

[.discourse-part]
_George Whitehead:_ May it please the king, and you his ministers,
to observe this one thing namely; that those officers and rude persons in Bristol,
who have done so much violence and spoil to our friends,
do pretend power and authority from the king, for such their proceedings,
and under pretext of an order from the king to put the laws in execution,
they take liberty to commit all their disorders and abuses against our friends,
because of their innocent meetings.

Which being seriously considered, I hope the king will see cause to do himself justice,
and likewise you his ministers will be concerned to do yourselves, as well as us justice,
by putting some stop to these destructive proceedings,
the violence and spoil they make under such pretence of the king`'s order and authority.
Pray, let it be duly considered, whether or no,
thereby they do not reflect upon the king, and dishonour him before his people,
whilst they render him the patron or mover of these their riotous
and oppressive proceedings against the king`'s peaceable subjects;
and whether or no they do not reflect upon you his ministers,
tending to render you suspicious in the eyes of the people?
I hope, on serious and tender consideration of these things,
you will see cause to do yourselves and us justice.

You have had experience of us,
and of our peaceable deportment towards the king
and government for above these twenty years;
it is very hard we should be thus severely used at this time of day!

We have here a more large and particular state of our suffering case,
which we desire you to receive and take notice of it.

This case at large being very fairly written upon several sheets of paper,
on the one side of each sheet, George Whitehead delivered it to the council board,
in the king`'s presence, where it was received and laid down on the board,
before the Lord Privy Seal, the Lord Chancellor, etc.

At last George Whitehead thus concluded, viz: I pray God preserve the king,
and direct you his ministers, to do justly, and love mercy, and to walk humbly with God.

I do confess I was under a very weighty concern of spirit,
to use my earnest and careful endeavours in solicitation,
in this heavy suffering case of our Bristol friends, who then were sorely persecuted,
oppressed and abused; for it was a time of very hot resolved persecution against them.

Upon a thorough inspection into their case,
and viewing the copies of the warrants of commitment against the prisoners,
together with the accounts of the riotous, shameful,
and abusive work made against our friends, at their meetings in that city,
I clearly perceived both how invidious, inconsiderate, and ignorant of law and justice,
the magistrates of that city were, who were then most busy against our friends,
and most ready to grant warrants against them, either to imprison their persons,
or seize their goods, thereby to gratify mercenary informers,
and the worst of our friends`' persecutors,
to the great dishonour and reproach of that city,
which formerly had been esteemed a place having more
of profession and religion in it than many others.

And considering what a barbarous, persecuting spirit was then got up there,
where our friends were so persecuted and oppressed,
I was the more zealously stirred in spirit by the Lord`'s power,
earnestly to endeavour for an opportunity to plead
their innocent cause before the king and his council.
I may truly say, the Lord made way for me, and did manifestly stand by and assist me.
For I felt his power and hand upon me;
and he gave me clearly to see and understand how to avoid being ensnared by questions,
and how to give seasonable answers;
and not to be discouraged or diverted by such interruptions as I met with.
Blessed be the Lord my God, who gave me power and boldness, and also counsel and wisdom,
to plead the cause of the innocent sufferers for his worthy name and blessed truth sake.

I was sensible the truth of our suffering friends`' case,
as I was enabled to plead and argue the same before the king and his council,
which was then large and full, had some entrance and effect, upon his,
and many of their consciences, though several among them were somewhat opposite.
An order of council was granted and given to the magistrates of Bristol,
to allow our friends better accommodation, as to prison room;
and some of them were removed out of Newgate, into another prison for a time,
until released.

The king appearing affected with the innocency of the sufferers`' case,
allowed me liberty to plead it against the persecutors,
longer than some present would have had me; and not only so,
but he suffered us to stand all the time before him
and his council with our hats on our heads,
which was about three quarters of an hour.
The king had the more reason to suffer us in that posture,
seeing he would not permit our hats to be taken off by the clerk of the council,
when we were called in before him, as we understood,
being minded to give himself some pleasant diversion,
by trying us in our plainness and simplicity,
agreeable to our profession and self-denying testimony.

On the 13th day of August, so called, A. D. 1682,
George Whitehead being called before Sir John Moor, then Lord Mayor of London,
on account of a meeting, the mayor asked him.

[.discourse-part]
_Mayor:_--Did not you preach at the meeting?

[.discourse-part]
_George Whitehead:_--I desire to be excused from answering that question,
for I am not bound to accuse myself.

[.small-break]
'''

After some other discourse,
one of the mayor`'s officers did in effect ask the same question, viz:

[.discourse-part]
_Mayor`'s Officer:_--Did not you take upon you to preach, or teach in the meeting?

[.discourse-part]
_George Whitehead:_--I am not bound to be my own prosecutor;
I am not under an oath _ex officio._
Where are my accusers, those who informed against the meeting?
If they could be so prophetical, as to tell so many days beforehand,
that there would be such a conventicle as the warrant mentions,
surely they may easily tell matter of fact when committed,
if any such was +++[+++but the informers did not then appear to give any evidence.]
To which an officer made this reply, viz:

[.discourse-part]
_Officer:_ We may certainly know some things beforehand, as when the sun sets,
that it will rise next morning, and the course of the tides.

[.discourse-part]
_George Whitehead:_--The course of the sun and tides are settled in the order of the creation;
our meetings are rather accidental, or occasional, and may possibly be altered,
as to time; but if the course of the sun be thought a meet instance, or comparison,
in this case, then had you all need to have a care of striving against them;
for it is in vain to endeavour to stop the sun in its course.

[.small-break]
'''

The mayor called two persons, who apprehended George Whitehead,
to give evidence upon oath.

George Whitehead then warned them,
as they intended to give account to the great Judge of all, to depose nothing,
as matter of fact, but what came within their certain knowledge,
or what they heard and saw.

[.discourse-part]
_A Trainband Officer:_ I saw his lips go, but heard not what he said.

[.discourse-part]
_Constable:_ I heard his voice, but could not tell what he said, so as to make sense of it;
only I heard him mention Jesus Christ and the Spirit.

[.discourse-part]
_George Whitehead:_
Now I desire the Lord Mayor will please to compare
these men`'s evidence with the matter of fact,
as it is stated in the Act of Parliament;
and then it will appear how far short it is of proving the fact,
as it is there described.
The one saw my lips move, but could not hear what I said; the other heard my voice,
and that I mentioned Jesus Christ and the Spirit,
but could not make sense of what I said.
I hope none here will conclude, that to mention Jesus Christ and the spirit,
are contrary to the liturgy of the church of England.
And seeing the evidence falls so much short of proving
the offence as it is described by law,
I desire that proceedings against me on this account may be stopped.

Nevertheless, I had goods in my shop of grocery-ware, seized, taken and carted away,
to a considerable value, by one James Holsworth, druggist, in Tower street, constable,
and others, by a warrant from the said Sir John Moor, then mayor;
but without proof of the least offence committed either
by myself or any other friend in the said meeting.

Surely it was a hard case, that in a solemn, religious assembly,
we might not move our lips, and mention Jesus Christ and the holy Spirit,
without being thus fined, and our goods seized and taken away.

[.embedded-content-document.legal]
--

[.letter-heading]
A Copy of the Warrant for Distress.

[.signed-section-context-open]
London, ss.

Whereas George Whitehead, of Hounsditch, in the parish of St. Buttolph,
within +++[+++for without]
Bishopsgate, London, was upon the 13th day of August, last past,
in the thirty-fourth year of his majesty`'s reign, legally convicted before me.
Sir John Moor, Kt. Lord Mayor of the city of London,
by the oaths of two sufficient witnesses, for that he upon the said 13th day of August,
did take upon him to teach and preach in an unlawful assembly, conventicle, or meeting,
situate in the parish of Allhallows, Lombard street, London,
under colour or pretence of exercise of religion,
in other manner than according to the liturgy and practice of the church of England;
at which conventicle, assembly, or meeting, there were more than five persons,
all of the age of sixteen years and upward, subjects of this realm, unlawfully assembled,
contrary to the late Act of parliament, entitled,
An Act to prevent and suppress seditious conventicles.
For which cause I have imposed upon him a fine of twenty pounds,
by him the said George Whitehead forfeited, for such his first offence,
of which he stands convicted before me,
according to the statute in that case made and provided.

These are therefore in his majesty`'s name, and by virtue of the said Act,
to command you, or some of you to levy the said sum of twenty pounds,
by way of distress and sale of the goods and chattels of him the said George Whitehead;
and that you return the said sum of twenty pounds,
or such part of it as you shall so levy, to me,
to be distributed according to the said Act; and for your so doing,
this shall be your warrant.

Given under my hand and seal, this 10th day of September,
_Anno Regis Caroli Secundi,_ 34. Anno Domini 1682.

[.signed-section-signature]
John Moor, Mayor.

[.signed-section-context-close]
To all constables and other his majesty`'s officers of the peace, within the said city,
whom this may concern.

--

Observe how far short of proof of the matter charged in this warrant,
the said mayor`'s two sufficient witnesses came in their evidence against George Whitehead,
when instead of plain matter of fact done, he makes them rather judges of matter of law,
viz: That he, George Whitehead, took upon him to preach in an unlawful, yea,
a seditious conventicle, when they could never prove any fact of that nature or tendency,
much less could these witnesses,
or the informers be competent judges of law in that case,
when all they saw or heard was George Whitehead move his lips,
and mention Jesus Christ and the holy Spirit; in which words I hope there is no sedition;
nor a disallowance thereof either in the liturgy or practice of the church of England,
for therein both Jesus Christ and the holy Spirit are frequently mentioned.

To manifest how eager our persecutors were to seek our ruin,
here follows a copy of a certificate for another warrant against George Whitehead, viz:

[.embedded-content-document.legal]
--

[.blurb]
=== To the right honourable Sir William Pritchard, Kt. Lord Mayor of the city of London, and to the right worshipful the aldermen of the said city, and to every of them whom it may concern.

These are to certify that George Whitehead, of Hounsditch, in the liberty of London,
grocer, stands convicted by the oaths of two credible witnesses upon record,
before me sir Clement Arminger, Kt+++.+++,
one of his majesty`'s justices of the peace for the county of Middlesex,
for taking upon him to preach and teach in other manner and form
than according to the liturgy and practice of the church of England,
on the 19th day of August last, in the afternoon, in a certain unlawful assembly,
conventicle, or meeting, in the parish of St. Margaret Westminster,
in the county aforesaid, in contempt of an Act of parliament,
made in the twenty-second year of his majesty`'s reign, entitled,
An Act to prevent and suppress seditious conventicles;
by virtue of which Act I have imposed a fine of forty pounds upon him,
the said George Whitehead,
this being the second offence of which he stands convicted before me upon record.

Given under my hand the 5th day of September, _Anno.
Reg. Carol.
Secundi nunc_ Ang.
35, etc.
Anno Domini 1683.

--

It appears that all this prosecution, or rather persecution,
was designed to force us to a strict conformity to the liturgy of the church of England,
or otherwise we must have our goods taken away from us,
and be disabled from obtaining a livelihood, and from buying and selling.
O church of England!
Is such persecution and severity the mark or fruit of a true Christian church?

The great offence assigned and made thus severely punishable by the foregoing certificate,
is preaching and teaching in other manner and form than
according to the liturgy and practice of the church of England,
whereby the liturgy seems preferred before the holy Scriptures, or the holy Spirit,
from whence they came, and from whence true preaching proceeds,
as is well known to all ministers of the spirit.

We find not what form of preaching or teaching, or of sermons,
are in the liturgy of`' the church of England, but forms of prayers, collects, etc.
But as to the practice of that church there is much preaching,
sermons and manner of praying also,
which are not in the liturgy or book of common prayer.
However,
the liturgy and practice of the said church allow
us more liberty in point of ministry and worship,
than our persecutors and their informers have done.

As it was a frequent practice of the persecuting justices
to convict us without any lawful summons or judicial hearing,
upon the information and oaths of mercenary informers,
whom they rendered their credible or sufficient witnesses,
after the same manner was this conviction, before cited, made against me;
although I was had before Sir Clement Arminger the first time,
when taken at our meeting at Savoy, in the Strand, the 23rd day of July, 1682.

Howbeit the informers appeared not face to face,
to prove matter of fact against me; yet it appeared he took their private information,
for he confessed in his own house, in the presence of Edward Brooks,
that upon the information of John Hilton and Gabriel Shadd, notorious informers,
and prosecutors, the conviction was made against me.

The following is an abstract of general exceptions in George Whitehead`'s case,
prepared in order to an appeal against the late conviction made against him,
by sir Clement Arminger, the 4th day of September, 1683; unsummoned and unheard,
in his own defence, etc.

[.numbered-group]
====

[.numbered]
1+++.+++ He conceives the conviction without summons or hearing,
to be contrary to all equity and right, due order of law, and common course of justice,^
footnote:[Vid+++.+++, Coke, Dalt+++.+++, Lambert.]
consequently not consistent with the oath of justices.

[.numbered]
2+++.+++ Contrary to the precedents which God himself hath given; Gen. 3:8 and 18, 21.

[.numbered]
3+++.+++ Contrary to the express law of God; Duet. 19:17-18, and John 7:51.

[.numbered]
4+++.+++ Contrary to the very law, justice, and manner of the ancient Romans,
and other nations; Acts 25:16.

[.numbered]
5+++.+++ Contrary to the intention of the conventicle Act itself;
requiring the taking into custody the persons unlawfully assembled,
to the intent they may be proceeded against according to this Act,
as well as by confession of the party in the first place, in order to conviction.

====

Concerning the circumstances of the fact assigned by the conventicle act, 22 Car.
2.

[.numbered-group]
====

[.numbered]
1+++.+++ The appellant conceives it is impossible to prove those circumstances
mentioned in the act against that assembly for which he stands convicted,
viz: the being met under colour and pretence of religious exercise,
in other manner than according to the liturgy, etc.,
being imputed to the conventicle only, by the said act, and not to the preacher;
and the conventicle for that cause, fineable distinct from the preacher, to wit,
five shillings, or ten shillings a person.
The case and forfeiture of the preacher being distinct in another clause, viz;
every person who shall take upon him to preach or teach in any such conventicle,
being convicted, etc., shall forfeit the sum of twenty pounds.
Here is no exception or circumstances relating to the preacher,
how well soever he preach, if it be in such conventicles, as is described by the act,
that makes the offence.

[.numbered]
2+++.+++ Therefore the appellant requests,
that the court would please to inquire of his prosecutors, or convicting justice,
what manner of religious exercise did the said assembly
pretend or practice that was not according to,
or which disagreed with the liturgy of the church of England?
Or what did the meeting pretend, do, or exercise in religion,
that it can rationally be judged the said liturgy allows not of?
For it is not the omission of such fact or exercise the said act condemns,
but some overt act; and the meeting being wholly passive,
what unlawful fact can possibly be proved against the same?

====

Concerning the circumstances of place, number and preaching,
most generally alledged against our religious assemblies;
the appellant conceives all these, together with the religious exercise thereof,
to be manifestly warranted and allowed by the liturgy of the church of England, viz:

[.numbered-group]
====

[.numbered]
1+++.+++ For assembling, and mutual exhortation and edification, etc.

[.numbered]
2+++.+++ For Christian meetings of considerable numbers.

[.numbered]
3+++.+++ For the liberty of ministering by the gift of Christ received.

[.numbered]
4+++.+++ For worshipping God in spirit and in truth, without limitation to time or place.

====

All these instances are proved in divers epistles,
citations of holy Scripture in the said liturgy, or common prayer book,
of the said church of England; which also often refers us to the holy Scriptures,
and to believe and practice accordingly.
It is generally alledged by convicting justices,
that by the oath of two credible witnesses,
they convict those whom they fine twenty pounds, or forty pounds a man;
when it is commonly on the oath of mercenary informers.
Against such we except, as being no credible witnesses,
but acting for their own unjust gain;
many whereof have made no conscience of their oaths,
but have forsworn themselves in divers cases, as has been proved,
and hereafter may be made apparent.
Credible witnesses who are assigned in law and justice, are no parties,
nor interested persons, as sir John Fortescue, lord chancellor of England,
in the reign of king Henry the sixth, describes them.

As our adversaries, to excuse their severe persecutions,
used divers false pretensions against us,
as that our religious meetings were unlawful conventicles, seditious, riotous, etc.,
so they took divers courses to make us suffer, as by fines, loss and spoil of our goods,
imprisonments, etc.

And seeing it was our persecutors`' design to pursue our ruin one way or other,
it was my great concern and exercise,
earnestly to endeavour to possess the king and government with a right
understanding and sense of the suffering condition of our friends,
and to plead their innocent cause, and solicit for their ease and relief,
more than for my own;
and especially to lay hold of such cases as appeared most heavy and severe,
as being most likely to procure some compassion, and obtain relief;
as where the hardest imprisonments of Friends`' persons were,
and greatest spoil and havoc made upon their goods;
which persecutions were often renewed and continued for some years in this nation,
under the reign of king Charles the second, especially towards his latter end.
