== Chapter XVI

[.chapter-subtitle--blurb]
A Supplement to the Preceding History.

The author has closed the foregoing account of his Christian
travails about the seventy-fifth year of his age,
at which he probably expected the period of his life and labours;
but it pleased God to prolong both, leading his outward man,
by an easy and gradual declension to its natural dissolution, and enabling him,
by preserving his intellects, to employ even the last remains of his bodily strength,
in the same kind of religious services, which he had been from his youth habituated to.
We have therefore thought proper to attend him to the end of his pilgrimage,
by subjoining such occurrences in his latter years as have come to our hands.

On the 3rd day of the eighth month, October, 1714,
the people called Quakers presented a congratulatory address to king George,
upon his accession to the crown, which being read to and graciously accepted by the king,
George Whitehead made a speech to this effect;

[.embedded-content-document.address]
--

Thou art welcome to us, king George.
We heartily wish thee health and happiness, and thy son the prince also.
King William the third was a happy instrument in putting a stop to persecution,
by promoting toleration,
which being intended for uniting the king`'s Protestant subjects,
in interest and affection, it hath so far that effect,
as to make them more kind to one another, even among the differing persuasions,
than they were when persecution was on foot.
We desire the king may have further knowledge of us and our innocency;
and that to live a peaceable and quiet life, in all godliness and honesty,
is according to our principle and practice.^
footnote:[Sewel`'s History of the Quakers, p. 711.]

--

George Whitehead having thus spoken, his name was asked; whereupon he answered,
George Whitehead.
And having it upon his mind to see the prince also,
and intimating his desire to a lord who was gentleman to the prince`'s bed-chamber,
he made way for it: and thus George Whitehead, with some of his friends, got access,
and were introduced by one of the prince`'s gentlemen, into a chamber,
where the prince met them; and then George Whitehead spoke to him,
the substance of which speech was as follows;

[.embedded-content-document.address]
--

We take it as a favour that we are thus admitted to see the prince of Wales,
and are truly very glad to see thee.
Having delivered our address to the king thy royal father,
and being desirous to give thyself a visit, in true love,
we very heartily wish health and happiness to you both;
and that if it should please God thou shouldst survive thy father and come to the throne,
thou mayest enjoy tranquillity and peace.

I am persuaded, that if the king, thy father, and thyself, do stand for toleration,
for liberty of conscience to be kept inviolable, God will stand by you.

May king Solomon`'s choice of wisdom be thy choice,
with holy Job`'s integrity and compassion to the oppressed;
and the state of the righteous ruler commended by king David, viz:
He that ruleth over men must be just, ruling in the fear of God;
and he shall be as the light of the morning, when the sun riseth,
even a morning without clouds, as the tender grass springing out of the earth,
by clear shining after rain.

--

[.offset]
This speech was favourably heard by the prince.

In the year 1715, after the breaking out of that unnatural rebellion,
which was suppressed by the king`'s forces at Preston, George Whitehead,
accompanied by his friend John Butcher,
having obtained an admission to the king`'s presence, presented to him a paper,
a copy of which, found among the author`'s manuscripts, since his decease,
we here insert.

[.embedded-content-document.address]
--

[.blurb]
=== A few words in true love to king George, humbly presented.

Seeing our most gracious God hath been pleased, by his overruling power and providence,
to give thee a free and peaceable accession to the throne of these kingdoms;
O let thy trust and confidence be in the same divine Power,
and thy eye to that light and grace thereby given thee, and the Lord will, no doubt,
confound thy foes,
and disperse and expel that dark cloud and spirit of rebellion
that is risen up against thee and thy lawful government,
constituted for the defence and support of our just liberties and properties,
religious and civil, against popery and slavery.

Thy Christian principle for liberty to tender consciences being maintained and stood by,
against persecution, the pillar of popery,
the Lord will stand by and defend thee and thy royal offspring;
for surely mercy and truth do preserve the king, and his throne is upholden by mercy.
Remember what the Spirit of the Lord spake by king David in his last words;
He that ruleth over men, must be just, ruling in the fear of God,
and he shall be as the light of the morning, even a morning without clouds.

The Lord, the God of hosts be thy defence, thy guide and counsellor,
and replenish thy heart with his wisdom, whereby kings reign and princes decree justice;
for in that wisdom, true dominion stands.

That thou, O king, mayest be a blessing in the hand of the Lord, to these nations,
and enjoy a safe, a peaceable and prosperous reign in this life,
and a crown of righteousness in that to come,
is the hearty prayer of an ancient servant of Jesus Christ,
and a truly loving and faithful subject,

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
London, the 25th of the Eighth month, called October, 1715.

--

In the month called May, 1716, the people called Quakers,
at their yearly meeting in London, drew up an address, and presented it to the king,
testifying their loyalty,
and expressing their sense of the signal providence
of God in confounding the late black conspiracy;
at the presenting of which address, George Whitehead made a previous speech to the king,
signifying:

[.embedded-content-document.address]
--

That in their annual assembly, held for the religious concerns of their Society,
endeavouring to promote and put in practice the duties of religion professed by them,
the sense of the great deliverance had such a weight upon their minds,
that they were willing to express it in an address to king George,
whom God by his providence had brought hither, and preserved, so that he could well say,
he was George, by the grace of God, king of Great Britain, etc.
And that as men carried that saying stamped on the money in their pockets,
so it was to be wished it might be imprinted in the hearts of the subjects.

--

Although now above eighty years of age, and feeble in body,
he nevertheless continued to bear his testimony in the public assemblies,
to the virtue and excellency of that divine grace,
which had supported him from his youth upward, imparting in most sensible expressions,
such choice fruits of his own experiences,
that an attentive hearer could not depart unedified.
And even in meetings about church affairs,
where sometimes diversity of sentiments may arise,
he would express his thoughts with a convincing force and solidity of reasoning,
no less admirable than the unspotted integrity of his grey hairs was honourable.

He wrote in the latter part of his time, several small treatises,
particularly one in the eighty-sixth year of his age, entitled,
An Epistle to our Christian Friends, called Quakers, etc., which being already in print,
we refer thereto.

Sustained by the consciousness of a well led life,
he passed the last infirmities of age with Christian patience and resignation, and,
on the 8th day of the month called March, 1722-3, died the best of deaths; for as Cicero,
in the person of Cato the elder, excellently expresses it;
"`The best end of a man`'s life is,
when the understanding and other senses remaining entire,
nature takes in pieces her own work, which she herself did put together.`"

And again, "`Whatsoever is according to nature, is to be accounted good; and,
what is more natural than for old men to die; a thing, which happens also to young men,
notwithstanding nature`'s opposition and reluctancy.
Young men therefore, seem to me to die,
like as a fierce flame is quenched by abundance of water; but old men,
as when a fire being spent, goes out of its own accord, without compulsion:
and as apples, while green, are plucked from the trees by force, but, when ripe,
fall of themselves; so violence bereaves young men of life, maturity the aged:
which indeed to me is so delightful, that as I approach nearer to death,
methinks I see the land, and after a tedious voyage am at last making to my port.`"

[.asterism]
'''

The following essay, occasioned by the apostacy of George Keith,
was penned by George Whitehead, and submitted to,
and approved by the Morning meeting of London, and subsequently transmitted to,
and approved by the yearly meeting of Philadelphia,
which gave it an extensive circulation, viz:

[.embedded-content-document]
--

[.blurb]
=== The Christian doctrine and Society of the people called Quakers, cleared from the reproach of the late division of a few in some part of America; as not being justly chargeable upon the body of the said people, there or elsewhere. Printed in the year 1693.

[quote.scripture, , Rom. 16:17]
____
Now I beseech you, brethren, mark them diligently which cause divisions and offences,
contrary to the doctrine which ye have learned, and avoid them.
____

[quote.scripture, , Eph 4:31-32]
____
Let all bitterness, and wrath, and anger, and clamour,
and evil-speaking be put away from you, with all malice.
And be ye kind one to another, tender-hearted, forgiving one another, even as God,
for Christ`'s sake, hath forgiven you.
____

Whereas divers accounts have been lately published in print,
of some late division and disputes between some persons
under the name of Quakers in Pennsylvania,
about several fundamental doctrines of the Christian faith,
(as is pretended by one party,) which being particularly mentioned,
and thereupon occasion very unduly taken by our adversaries,
to reproach both the Christian ministry and whole
body of the people commonly called Quakers,
and their holy and Christian profession, both in England and elsewhere,
though no way concerned in the said division or matters charged;
but rather grieved and troubled at it,
and at the indiscreet and reproachful management thereof in print,
to the amusing and troubling the world therewith, and giving occasion to the loose,
ignorant, and profane, to slight and contemn the Truth,
and the interest of the tender religion of our Lord Jesus Christ.

We are, therefore, tenderly concerned for Truth`'s sake in behalf of the said people,
(as to the body of them, and for all of them who are sincere to God,
and faithful to their Christian principle and profession,)
to use our just endeavours to remove the reproach,
and all causeless jealousies concerning us, touching those doctrines of Christianity,
or any of them pretended or supposed to be in question in the said division;
in relation whereunto we do, in the fear of God,
and in simplicity and plainness of his Truth received,
solemnly and sincerely declare what our Christian belief and profession has been,
and still is, in respect to Jesus Christ the only begotten Son of God; his suffering,
death, resurrection, glory, light, power, great day of judgment, etc.

We sincerely profess faith in God by his only begotten Son Jesus Christ,
as being our Light and Life, our only way to the Father,
and also our only Mediator and Advocate with the Father.^
footnote:[Heb. 12:2. 1 Pet. 1:21. John 14:6. 1 Tim. 2:5.]

That God created all things; He made the worlds by his Son Jesus Christ,
He being that powerful and Living Word of God by whom all things were made;^
footnote:[Eph. 3:9. John 1:1-3. Heb. 1:2]
and that the Father, the Word, and the Holy Spirit are one, in divine being inseparable;
one true, living and eternal God, blessed forever.^
footnote:[John 5:7.]

Yet that this Word or Son of God, in the fulness of time took flesh,
became perfect man--according to the flesh,
descended and came of the seed of Abraham and David;^
footnote:[Rom. 1:3-4.]
but was miraculously conceived by the Holy Ghost, and born of the Virgin Mary.^
footnote:[Matt. 1:23.]
And also further declared powerfully to be the Son of God,
according to the spirit of sanctification, by the resurrection from the dead.^
footnote:[Rom. 1:3-4.]

That in the Word or Son of God, was life; and the same life was the light of men;
and that He was that true Light which enlightens every man coming into the world.^
footnote:[John 1:4,9]
And therefore that men are to believe in the Light,
'`that they may become children of the Light.^
footnote:[John 12:36. Isaiah 2:5]
Hereby we believe in Christ the Son of God, as He is the light and life within us;
and wherein we must needs have sincere respect and honour to, and belief in Christ,
as in his own unapproachable and incomprehensible glory and fulness,^
footnote:[1 Tim. 6:16.]
as He is the Fountain of life and light, and Giver thereof unto us; Christ,
as in himself and as in us, being not divided.
And that as man, Christ died for our sins, rose again,
and was received up into glory in the heavens:^
footnote:[1 Pet. 3:18. 1 Tim. 3:16. Matt. 19:28, and 25:31. Luke 9:26, and 24:26.]
he having, in his dying for all,
been that one great universal offering and sacrifice for peace, atonement,
and reconciliation between God and man.^
footnote:[Rom. 5:10-11. Heb. 2:17-18, Eph. 2:16-17. Col. 1:20-22.]
And He is the propitiation, not for our sins only, but for the sins of the whole world.^
footnote:[1 John 2:2. 2 Cor. 5:14. 15. Heb. 2:9.]
We were reconciled by his death, but saved by his life.

That Jesus Christ who sitteth at the right hand of
the throne of the Majesty in the heavens,
is yet our King, High Priest, and Prophet;^
footnote:[Zech. 9:9. Luke 19:38. John 12:15. Heb. 3:1,6.
Duet. 18:15,18. Acts 3:22, and 7:37.]
in his church a minister of the sanctuary and of the true tabernacle,
which the Lord pitched and not man.^
footnote:[Heb. 8:1-2.]
He is Intercessor and Advocate with the Father in heaven,
and there appearing in the presence of God for us;^
footnote:[Heb. 7:25. Heb. 9:24.]
being touched with the feeling of our infirmities, sufferings, and sorrows;
and also by his Spirit in our hearts he maketh intercession according to the will of God,
crying, Abba, Father.^
footnote:[Rom. 8:26,27,34. Gal. 4:6.]

For any whom God hath gifted^
footnote:[Eph. 3:7. 1 Peter 4:10.]
and called sincerely to preach faith in the same Christ, both as within and without us,
cannot be to preach two Christs, but one and the same Lord Jesus Christ;^
footnote:[1 Cor. 7:6, xv.
3, 8.]
having respect to those degrees of our spiritual knowledge of Christ Jesus in us,^
footnote:[John 15:26, and xvi 13, 14, 15.]
and to his own unspeakable fulness and glory,^
footnote:[John 1:16.]
as in himself, in his own entire being; wherein Christ himself,
and the least measure of his light or life, as in us, or in mankind,
are not divided or separable, any more than the sun is from its light.
And as He ascended far above all heavens, that he might fill all things,^
footnote:[Eph. 4:10.]
his fulness cannot be comprehended or contained in any finite creature,^
footnote:[Col. 1:19, and ii.
9.]
but is in measure known and experienced in us, as we are capable to receive the same;
as of his fulness we have received grace for grace.
Christ our Mediator received the Spirit, not by measure,^
footnote:[John 3:34.]
but in fulness; but to every one of us is given grace,
according to the measure of his gift.^
footnote:[Ephes.
i V. 7.]

That the gospel of the grace of God should be preached in the name of the Father, Son,
and Holy Ghost,^
footnote:[Matt. 28:19.]
being one^
footnote:[John 1:1, 2, 3, 4.]
in power, wisdom and goodness, and indivisible,
or not to be divided in the great work of man`'s salvation.

We sincerely confess and believe in Jesus Christ, both as he is true God and perfect man,^
footnote:[John 1:1-2. Rom. 9:5. 1 John 5:20. 1 Tim. 2:5.]
and that he is the Author of our living faith in the power and goodness of God,
as manifest in his Son Jesus Christ,
and by his own blessed Spirit or divine unction revealed in us,^
footnote:[1 John 2:20,27, and i. 1.]
whereby we inwardly feel and taste of his goodness,^
footnote:[1 Peter 2:3. John 6:33,35,51,57,58.]
life and virtue; so as our souls live and prosper by and in him,
and in the inward sense of this divine power of Christ, and faith in the same;
and this inward experience is absolutely necessary to make a true, sincere,
and perfect Christian in spirit and life.

That divine honour and worship are due to the Son of God;^
footnote:[John 5:23. Heb. 1:6.]
and that he is in true faith to be prayed unto,
and the name of the Lord Jesus Christ called upon, as the primitive Christians did,^
footnote:[1 Cor. 1:2. Acts 7:59.]
because of the glorious union or oneness of the Father and the Son;^
footnote:[John 10:30. 1 John 5:7.]
and that we cannot acceptably offer up prayers or praises to God,
nor receive a gracious answer or blessing from God,
but in and through his dear Son Christ.

That Christ`'s body which was crucified, was not the Godhead,
yet by the power of God was raised from the dead;
and that the same Christ who was therein crucified, ascended into heaven and glory^
footnote:[Luke 24:26.]
is not questioned by us.
His flesh saw no corruption;^
footnote:[Ps. 16:10. Acts 2:31, and xiii.
35, 37.]
it did not corrupt; but yet doubtless his body was changed into a more glorious^
footnote:[Phil. 3:21.]
and heavenly condition than it was when subject to divers sufferings on earth;
but how and what manner of change it met withal after it was raised from the dead,
so as to become such a glorious body as it is declared to be,
is too wonderful for mortals to conceive, apprehend, or pry into;
and more meet for angels to see.
The Scripture is silent therein, as to the manner thereof,
and we are not curious to enquire or dispute it;
nor do we esteem it necessary to make ourselves wise above^
footnote:[1 Cor. 4:4. 6.]
what is written, as to the manner or condition of Christ`'s glorious body as in heaven,
any more than to enquire how Christ appeared in divers manners or forms,^
footnote:[Mark xvi, 12. John 20:15.]
or how he came in among his disciples, the doors being shut;^
footnote:[John 20:19. Luke 24:36-37, and xxiv.
31.]
or how he vanished out of their sight, after he was risen.
However, we have cause to believe his body, as in heaven,
is changed into a most glorious condition, far transcending what it was in on earth;
otherwise how should our low body be changed,
so as to be made like unto his glorious body;^
footnote:[Phil. 3:21.]
for when he was on earth, and attended with sufferings,
he was said to be like unto us in all things, sin only excepted;^
footnote:[Heb. 2:17, and 4:15.]
which may not be so said of him as now in a state of glory, as he prayed for;^
footnote:[John 17:5.]
otherwise where would be the change both in him and us?

True and living faith in Christ Jesus the Son of the living God,^
footnote:[John 14:1.]
has respect to his entire being and fulness; to him entirely, as in himself,
and as all power in heaven and earth is given unto him;^
footnote:[Matt. 28:18, 11:27. John 17:2. Heb. 1:4, 2:8.]
and also an eye and respect to the same Son of God,^
footnote:[John 14:23, 17:21-24,26.]
as inwardly making himself known in the soul in every degree of his light, life, spirit,
grace, and truth; and as he is both the Word of faith and a quickening Spirit in us,^
footnote:[1 Cor. 15:45. Rom. 10:7. 8.]
whereby he is the immediate cause, author, object,
and strength of our living faith in his name and power,
and of the work of our salvation from sin and bondage of corruption.
And the Son of God cannot be divided from the least or lowest
appearance of his own divine light or life in us or in mankind,
no more than the sun from its own light; nor is the sufficiency of his light within,
by us set up in opposition to him the man Christ,
or his fulness considered as in himself, or without us;
nor can any measure or degree of light received from Christ, as such,
be properly called the fulness of Christ, or Christ as in fulness, nor exclude him,
so considered, from being our complete Saviour: for Christ himself to be our light,
our life and Saviour,^
footnote:[John 1:4,9. iii.
19, 20, xii.
35, 36, 46, viii.
12,]
is so consistent, that without his light we could not know life,
nor him to save us from sin or deliver us from darkness, condemnation or wrath to come.

And where the least degree or measure of this light and life of Christ within,
is sincerely waited for, followed and obeyed,
there is a blessed increase of light and grace known and felt;
as the path of the just shines more and more, until the perfect day;^
footnote:[Prov. 4:18. Ps. 36:9.]
and thereby a growing in grace, and in the knowledge of God,
and of our Lord and Saviour Jesus Christ, hath been, and is truly experienced.

And this light, life, or Spirit of Christ within, for they are one divine principle,
is sufficient to lead into all truth,
having in it the divers ministrations both of judgment and mercy, both of law and gospel;
even that gospel which is preached in every intelligent creature under heaven.
It does not only, as in its first ministration, manifest sin,
and reprove and condemn for sin;
but also excites and leads them that believe in it to true repentance,
and thereupon to receive that mercy, pardon and redemption in Christ Jesus,
which he has obtained for mankind, on those gospel terms of faith in his name,
true repentance, and conversion to Christ, thereby required.

So that the light and life of the Son of God within, truly obeyed and followed,
as being the principle of the second or new covenant,
as Christ the light is confessed to be,
even as he is the Seed or Word of faith in all men;
this does not leave men or women who believe in the light, under the first covenant,
nor as sons of the bondwoman,
as the literal Jews were when gone from the Spirit of God and his Christ in them;
but it naturally leads them info the new covenant, into the new and living way,
and to the adoption of sons, to be children and sons of the freewoman,
of Jerusalem from above.

It is true that we ought not to lay aside, nor should any undervalue,
but highly esteem true preaching and the Holy Scriptures,
and the sincere belief and faith of Christ, as he died for our sins,
and rose again for our justification,
together with Christ`'s inward and spiritual appearance and work of grace in the soul,
livingly to open the mystery of his death, and perfectly to effect our reconciliation,
sanctification, and justification;
and where ever Christ qualifies and calls any to
preach and demonstrate the mystery of his coming,
death and resurrection, etc., even among the Gentiles,
Christ ought accordingly to be both preached, and believed and received.

Yet supposing there have been or are such pious and conscientious Gentiles,
in whom Christ was and is as the seed or principle of the second or new covenant,
the Light, the Word of faith, as is granted,
and that such live uprightly and faithfully to that Light they have,
or to what is made known of God in them, and who therefore, in that state, cannot perish,
but shall be saved, as is also confessed;
and supposing these have not the outward advantage of preaching, Scripture,
or thence the knowledge of Christ`'s outward coming,
and being outwardly crucified and risen from the dead, can such, thus considered,
be justly excluded Christianity or the covenant of grace, as to the virtue, life,
and nature thereof, or truly deemed no Christians,
or void of any Christian faith in the life and power of the Son of God within,
or be only sons of the first covenant and bondwoman, like the literal outside Jews?
Or must all be excluded any true knowledge or faith of Christ within them,
unless they have the knowledge of Christ as without them? No sure!
for that would imply insufficiency in Christ and his light as within them,
and frustrate God`'s good end and promise of Christ,
and his free and universal love and grace to mankind in sending his Son.
We charitably believe the contrary,
that they must have some true faith and interest in Christ and his mediation,
because of God`'s free love in Christ to all mankind, and Christ`'s dying for all men,^
footnote:[2 Cor. 5:14-15.]
and being given for a light of the Gentiles, and for salvation to the ends of the earth.^
footnote:[Isaiah xlix.
G+++.+++ Luke 2:32. Acts 13:47.]
And because of their living up sincerely and faithfully to his light in them,
their being pious, conscientious, accepted, and saved, as is granted,
we cannot reasonably think a sincere, pious or godly man, wholly void of Christianity,
of what nation soever he may be;
because none can come to God or godliness but by Christ,^
footnote:[John 14:6.]
by his light and grace in them:
yet grant if there be such pious and sincere men or women as have not the Scripture,
or knowledge of Christ as outwardly crucified, etc.,
they are not perfect Christians in all perfections, as in all knowledge,
and understanding all points of doctrine, and outward profession of Christ;
so that they are better than they profess or pretend to be; they are more Jews inward,
and Christians inward, than in outward show or profession.

There are Christians sincere and perfect in kind or nature, in life and substance,
though not in knowledge and understanding.
A man or woman having the life and fruits of true Christianity,
the fruits of the Spirit of Christ in them, who can talk little thereof, or of creeds,
points or articles of faith, yea many that cannot read letters,
yet may be true Christians in spirit and life:
and some could die for Christ that could not dispute for him.
And even infants that die in innocency, are not excluded the grace of God,
or salvation in and by Christ Jesus;
the image and nature of the Son of God being in some measure in them,
and they under God`'s care and special providence.
See Matthew 18:2. 10.

And though we had the Holy Scriptures of the Old and New Testament,
and a belief of Christ crucified and risen, etc.,
we never truly knew the mystery thereof until we were turned
to the light of his grace and Spirit within us:
we knew not what it was to be reconciled by his death and saved by his life,
or what it was to know the fellowship of his sufferings, the power of his resurrection,
or to be made conformable unto his death--we knew not,
until he opened our eyes and turned our minds from darkness
unto his own divine light and life within us.

Notwithstanding, we do so sincerely and greatly esteem and value the Holy Scriptures,
preaching and teaching of faithful, divinely inspired, gifted,
and qualified persons and ministers of Jesus Christ, as being great outward helps,
and instrumental in his hand, and by his Spirit for conversion;
where God is pleased to afford those outward helps and means;
as that we neither do nor may oppose the sufficiency of the light
or Spirit of Christ within to such outward helps or means,
so as to reject, disesteem, or undervalue them;
for they all proceed from the same light and Spirit,
and tend to turn men`'s minds thereunto, and all centre therein.

Nor can the Holy Scriptures or true preaching without,
be justly set in opposition to the light or Spirit of God or Christ within;
for his faithful messengers are ministers thereof,
being sent to turn people to the same light and Spirit in them.^
footnote:[Acts 26:18. 1 John ii.
a Rom. 13:2. 2 Cor. 4:6. 1 Pet. 2:9.]

It is certain that great is the mystery of godliness in itself,
in its own being and excellency, namely,
that God should be and was manifest in the flesh, justified in the spirit,
seen of angels, preached unto the Gentiles, believed on in the world,
and received up into glory.

And it is a great and precious mystery of godliness and Christianity also,
that Christ should be spiritually and effectually in men`'s hearts,
to save and deliver them from sin, Satan, and bondage of corruption;
Christ being thus revealed in true believers, and dwelling in their hearts by faith:
Christ within the hope of glory, our light and life, who of God is made unto us wisdom,
righteousness, sanctification, and redemption; 1 Cor. 1:30.
And therefore this mystery of godliness,
both as in its own being and glory, and also as in men, in many hid and in some revealed,
hath been and must be testified, preached, and believed,
where God is pleased to give commission and prepare people`'s hearts for the same,
and not in man`'s will.

Concerning the resurrection of the dead, and the great day of judgment yet to come,
beyond the grave or after death, and Christ`'s coming without us,
to judge the quick and the dead,
as divers questions are put in such terms;--what the holy
Scriptures plainly declare and testify in these matters,
we have great reason to credit and not to question,
and have been always ready to embrace with respect
to Christ and his apostles`' own testimony and prophecies.

[.numbered-group]
====

[.numbered]
1+++.+++ _For the Doctrine of the Resurrection._

[.small-break]
'''

If in this life only we have hope in Christ, we are of all men most miserable; 1 Cor. 15:19.
We sincerely believe,
not only a resurrection in Christ from the fallen, sinful state here,
but a rising and ascending into glory with him hereafter;
that when he at last appears we may appear with him in glory; Col. 3:4.
1 John 3:2. But that all the wicked,
who live in rebellion against the light of grace, and die finally impenitent,
shall come forth to the resurrection of condemnation.

And that the soul or spirit of every man and woman shall
be reserved in its own distinct and proper being,
so as there shall be as many souls in the world to come as in this; and every seed,
yea every soul, shall have its proper body, as God is pleased to give it; 1 Cor.
XV. A natural body is sown, a spiritual body is raised;
that being first which is natural, and afterward that which is spiritual.
And though it is said this corruptible shall put on incorruption,
and this mortal shall put on immortality;
the change shall be such as flesh and blood cannot inherit the
kingdom of God neither doth corruption inherit incorruption;
1 Cor.
XV. We shall be raised out of all corruption and corruptibility, out of all mortality;
and the children of God and of the resurrection,
shall be equal to the angels of God in heaven.^
footnote:[Matt. 22:30. Mark 12:25. Luke 20:36.]

And as the celestial bodies do far excel terrestrial;
so we expect our spiritual bodies in the resurrection
shall far excel what our bodies now are;
and we hope none can justly blame us for thus expecting better bodies than now they are.
Howbeit we esteem it very unnecessary to dispute or question how the dead are raised,
or with what body they come;
but rather submit that to the wisdom and pleasure of Almighty God.

[.numbered]
2+++.+++ _For the Doctrine of Eternal Judgment._

[.small-break]
'''

God hath committed all judgment unto his Son Jesus Christ;
and he is Judge both of quick and dead, and of the states and ends of all mankind;
John 5:22,27, Acts 10:2,42 Tim. 4:1-1 Pet. 4:5.

====

That there shall be hereafter a great harvest, which is the end of the world;
a great day of judgment, and the judgment of that great day,
the holy Scripture is clear.^
footnote:[Matt. 13:39-41, 10:15, 11:24. Jude 6.]
When the Son of Man cometh in his glory, and all the holy angels with him;
then shall he sit upon the throne of his glory,
and before him shall be gathered all nations, etc.
Matt. 25:31-32, to the end, compared with chap.
Xxii.
31, Mark 8:38, Luke 9:26, and 1 Cor. 15:2,52 Thess. 1:7-8, to the end,
and 1 Thess. 4:16, Rev. 20:12-15.

That this blessed heavenly Man, this Son of Man, who hath so deeply suffered,
and endured so many great indignities and persecutions from his adversaries,
both to himself and his members and brethren, will at last,
even in the last and great day, signally and manifestly appear in glory and triumph,
attended with all his glorious heavenly host and retinue, before all nations,
before all his enemies, and those that have denied him.
This will be to their great terror and amazement;
that this most glorious heavenly man and his brethren,
that have been so much contemned and set at nought,
should be thus exalted over their enemies and persecutors, in glory and triumph,
is a righteous thing with God; and that they that suffer with him,
should appear with him in glory and dignity when he thus appears at last.
Christ was judge of the world and the prince thereof, when on earth; John 9:39, xii.
31; he is still Judge of the world, the wickedness and prince thereof, by his light.
Spirit, and gospel in men`'s hearts and consciences; John 16:11-8, Matt. 12:18,20,
Isaiah 42:1, Rom. 2:1,16 Pet.
iv. 6;
and he will be the Judge and final determiner thereof in that great
day appointed God having appointed a day wherein he will judge
the world in righteousness by that man whom he hath ordained.
Christ foretold,
it shall be more tolerable for them of the land of
Sodom and Gomorrah in the day of judgment,
than for that city or people that would not receive his messengers or ministers, etc.;
Matt. 10:15, 11:24, Mark 6:11, Luke 10:12,14.
It is certain that God knows how to deliver the
godly out of all their trials and afflictions,
and at last to bring them forth and raise them up into glory with Christ;
so he knoweth also how to reserve the unjust and
finally impenitent unto the day of judgment,
to be punished; 2 Pet. 2:9. He will bring them forth unto the day of destruction; Job 21:30.
The Lord can and will reserve such impenitent, presumptuous,
and rebellious criminals, as bound under chains of darkness, as were the fallen angels,
unto the judgment of the great day; Jude 6, Matt. 25:30.
It is not for us to determine or
dispute the manner how they shall be so reserved;
but leave it to God; he knows how.

Touching the opinion of the revolution or transmigration of human souls,
or their passing out of one body into another, etc.,
as it is deemed originally to have sprung from the heathen,
and was received among Jews and some others by tradition,
and said to be the opinion of Empedocles, Pythagoras, and the Egyptians,
and partly of Julian the apostate when he dreamed that the
soul of Alexander the Great was crept into his carcass,
or rather that he was Alexander himself in another body;
and thereupon rejecting the suit of the Persians for peace,
presumptuously proceeded in the war and to bloodshed against them, until, at unawares,
he got his death`'s wound, according as is more fully related in history;
particularly Socrates`'s Scholasticus, lib, 1, chap. 17, and lib, iii.
Chap. 18. Eccles. Chron. fol. 577.
See also Dr. Hammond`'s Annotations on John ix, 1, 2, 3.
We are not concerned in any such notion, but, as a people, are wholly clear of it.

We deem it neither necessary to faith, nor safe to receive or defend,
as either held by those heathen Egyptians or Jews aforesaid;
nor as it is insinuated in a late pamphlet of two hundred queries,
concerning the doctrine of the revolution of human souls, supposing twelve revolutions,
or twelve distinct intervals of life to every man,
as being twelve several times born into the world;
for each one to live or consummate the space of one thousand years on earth.
Though this opinion of such revolution appears not to be
a point in present controversy in the book aforesaid,
or in Pennsylvania, nor maintained as any divine opening, revelation,
or necessary article of faith, but rather evaded from being publicly controverted;
yet inasmuch as there appears some ground of suspicion in the case,
and as it seems to be favoured implicitly by some therefore,
that we as a people may not be suspected about it,
we sincerely declare our clearness from the said opinion,
as really esteeming it not safe to propagate, or maintain,
or trouble people`'s heads or minds with it;
but that all should improve their present time and mercies.
And we are the less concerned about the aforesaid queries and doctrine,
because we find not any known person or persons of credible authority,
that will adventure to assert that opinion, either as divinely revealed or opened,
or as necessary to be believed or received as an article of faith,
or that will undertake to demonstrate how many times or
intervals of life they themselves have lived on earth,
and what transactions or remarkable passages, or things good or bad,
they have done or passed through in those their supposed past intervals of life.

[.small-break]
'''

[.centered]
_Conclusion._

To conclude: as we are persuaded want of walking in the true light,
and want of Christian charity is the great cause of divisions,
in professed Christian societies of all sorts,
and of this difference among a few persons in America,
professing the same light and truth with us:
we are ashamed of and surprised at the bitter language,
and severe consequences and treatment, in some of the printed books from one party,
and the exposing of the weaknesses and unwarrantable expressions of some of the other,
to the open enemies of both, and of religion itself; all which,
as also to make any public rent in a religious society
on personal offences or private occasions,
are greatly unbecoming our Christian profession, charity, or Society.

And we pray God rebuke and stop this troublesome
spirit of enmity and division wherever it is;
for it makes great disturbance and trouble in the creation,
and where it enters in church or state; yet its ill work is no new thing.
It was the same spirit that infested and troubled the primitive Christian churches,
causing divisions and offences contrary to the gospel of peace, at first received,
and whereby parties and schisms were made; and one said I am of Paul, another of Apollos,
another of Cephas; which carnality the apostle reproved, as knowing and testifying
that Christ, whom they all professed, is not divided.
And if Christian tenderness and charity might influence all parties,
we see no real cause for these few persons aforesaid to divide or separate outwardly,
especially about doctrine, seeing both profess one light, one Spirit, one God,
and one Lord Jesus Christ, and faith in him,
and sincerely to believe the holy Scriptures.
And even the person charging the other in print,
professes to "`own the body of the people called Quakers,
and seems to approve of our ancient, faithful, and generally approved Friends,
writers or publishers of our doctrines and principles,
and preachers among us generally owned and approved by us,
as men of sound judgment and understanding,
and as owning the fundamental articles of the Christian and Protestant faith.`"
Thus far the person charging,
in his "`Serious Appeal,`" page 6. As also the same person
further openly signified at the other friends`' meeting,
that "`he and his friends had unity with the most there as to the main.
As also with all faithful friends everywhere,
excepting only some in their meeting that were unsound,`" etc.--`"Reason and
causes,`" page 26. And therefore if most on both sides have unity as to the main,
we may charitably suppose they do not differ in the main
or substance of Christian faith or doctrine before cited,
and sincerely owned and confessed by us; if tenderly and duly considered by both sides,
as men seeking peace, love, and concord.
Wherefore the difference was very indiscreetly managed, aggravated,
and exposed to separation, printing, and reproach, seeing it was not in the main.

We wholly dislike such rending and tearing, such dividing and aggravating proceedings,
and bitter treatment, and have no unity therewith;
but desire the Lord in mercy to repair the breaches,
and heal the backslidings among them,
and amongst all that are esteemed Christian professions and societies,
and incline all to the main, to the true light,
to the substance and life of Christianity, to true love, fervent charity,
and tender-heartedness, and forgiveness towards one another,
and to follow peace with all men, and holiness; without which no man shall see the Lord.

[.blurb]
=== A Postscript, relating to the doctrine of the Resurrection and Eternal Judgment.

At the last trump of God, and voice of the archangel,
the dead shall be raised incorruptible; the dead in Christ shall rise first;
1 Cor. 15:1,52 Thes.
iv. 16, compared with Matt. 24:31.

Many are often alarmed in conscience here by the word and voice of God,
who stop their ears and slight those warnings;
but the great and final alarm of the last trumpet,
they cannot stop their ears against nor escape: it will unavoidably seize upon,
and further awaken them finally to judgment.
They that will not be alarmed in their consciences unto repentance,
nor out of their sins here, must certainly be alarmed to judgment hereafter.

Whosoever do now willfully shut their eyes, hate, contemn, or shun the light of Christ,
or his appearance within, shall at last be made to see,
and not be able to shun or hide themselves from his glorious
and dreadful appearance from heaven with his mighty angels,
as with lightning and in flaming fire,
to render vengeance on all them that know not God
and obey not the gospel of our Lord Jesus Christ;
1 Thess. 7:8, Matt. 24:27, Luke 17:24, Dan. 10:6, Job 37:3.

And though many now evade and reject the inward convictions and judgment of the light,
and shut up the records or books thereof in their own consciences,
they shall all be at last opened, and every one judged of those things recorded therein,
according to their works; Rev. 20:12-15.

Signed in behalf of our Christian profession and people aforesaid;

[.signed-section-signature]
George Whitehead, Ambrose Rigge, William Fallowfield, James Parke, Charles Marshall,
John Bowater, John Vaughton, William Bingley.

--

[.asterism]
'''

The following epistle appears to have been written by him when very far advanced in life,
viz:

[.embedded-content-document.epistle]
--

[.blurb]
=== A Gospel salutation in true Christian love, recommended to Friends, who believe in the name of the Son of God, the true Light; and to all who truly desire to be grounded and settled in the faith of Christ.

[quote.scripture, , John 8:12]
____
I am the light of the world: he that followeth me shall not walk in darkness,
but shall have the light of life.
____

[quote.scripture, , John 12:36]
____
While ye have light, believe in the light, that ye may be the children of light.
____

[.salutation]
Beloved Friends,

Now, in my ancient years,
after a long travel and many years labour in the work of
the ministry of the Gospel of our Lord Jesus Christ,
a renewed salutation of true and tender love he hath laid upon me,
and moved upon my spirit to recommend unto you, by way of an epistle,
I being for some time disabled in the outward man from travelling abroad as formerly;
yet am inwardly often strengthened and renewed in spirit,
through the love and tender mercies and riches of the grace of the Lord our God,
which I have in his dear Son Christ Jesus, to whom be praise, honour and glory,
forevermore.

My dear and beloved friends,
I am still as deeply concerned in spirit for the whole family,
heritage and church of God, as ever;
and for all whose hearts are truly inclined by his
divine grace and good spirit to seek him,
and to be acquainted with him, that they may have eternal life,
by the knowledge of the only true God, and Jesus Christ whom he hath sent,
for this is life eternal, the intent, substance and glory of all true Christian religion:
and that this knowledge may increase, and the glory thereof spread in the earth,
is still my soul`'s desire and breathing to the Lord our God.

And dearly beloved, that in this eternal life,
divine and spiritual knowledge of the only true God and his Son Jesus Christ,
you all may grow, and your souls prosper therein to God`'s eternal glory,
and your everlasting peace, is my soul`'s sincere desire and supplication to Him,
who is the Father and fountain of all our mercies and blessings afforded unto us,
in and through his only begotten Son Jesus Christ.

O! consider,
and diligently mind and remember the great wisdom and love of our most gracious God,
as the cause of his giving his only begotten Son,
that whosoever believefh in him might not perish, but have everlasting life;
who said unto his disciples, "`Let not your hearts be troubled; ye believe in God,
believe also in me.
In my Father`'s house are many mansions, if it were not so I would have told you.
I go to prepare a place for you; and if I go and prepare a place for you,
I will come again and receive you unto myself, that where I am, there ye may be also.`"

Surely we believing in God, who gave his dear Son for our redemption and salvation,
we ought also to believe in his Son as our great Mediator and Advocate with the Father;
considering also, that Christ Jesus,
his being given us as our Mediator between God and men,
and his giving himself a ransom for all men, for a testimony in due time,
and his dying for all men, his tasting death for every man, etc.,
did all proceed from the great love of God,
and not to pay a strict or rigid satisfaction for vindictive justice,
or revenge on God`'s part; for that would leave no place for forgiveness of sins past,
before repentance and faith in Christ and his gospel;
seeing the good will and blessed design of God,
setting forth Jesus Christ to be a propitiation, through faith in his blood,
to declare his righteousness for the remission of sins that are past,
through the forbearance of God, whose blood cries for mercy.
Surely that righteousness and forbearance of God declared
by the propitiatory sacrifice of our Lord Jesus Christ,
for the remission or forgiveness of sins that are past, upon true repentance,
cannot justly be deemed revenge or vindictive justice, as some have asserted against us;
but a free act of the love and wisdom of God to give his Son,
and in him to reconcile the world to himself,
and not to impute their sins that are past to them,
when thoroughly reconciled and united in heart and soul unto him,
by his grace and good spirit.

Oh! "`Behold the Lamb of God,
which taketh away the sin of the world:`" In what respect does Jesus Christ,
as the Lamb of God, take away the sin of the world?
I answer, in two respects:

[.numbered-group]
====

[.numbered]
_First,_ as an universal and most excellent offering and acceptable sacrifice for sin,
in order to obtain redemption and forgiveness by his precious blood,
and even of a most sweet smelling savour to God,
far excelling the legal and typical oblations of animals,
as the offerings and blood of bulls, goats, heifers, sheep, rams, lambs, etc.,
all which Jesus Christ by his own one offering put an end unto.

[.numbered]
_Second;_ Jesus Christ, as the Lamb of God, takes away the sin of the world,
by purging the conscience and purifying the hearts of all
them who truly receive him and believe in him,
even in his holy name and divine power.

====

O! therefore, behold the Lamb of God, which taketh away and putteth an end to sin,
finisheth transgression, and brings in everlasting righteousness.

Let us all look unto the promised Messiah, even unto Jesus,
the author and finisher of our faith, that we all may believe in heart unto,
righteousness, and the salvation of our souls,
so as to be partakers of Christ and his righteousness,
that none may draw back to perdition, nor into the world`'s pollutions,
who have escaped the same through the knowledge of God and his dear Son Jesus Christ,
who is able and truly willing to save to the uttermost all them who come unto God by him.

He who offered up himself a Lamb without spot to God for all mankind,
and thereby became a propitiation for the sins of the whole world,
never designed to leave men in sin and transgression all their days,
but to afford all men grace to lead them to true repentance,
that they might receive that remission, forgiveness,
atonement and reconciliation obtained for them.

That God was in Christ reconciling the world to himself,
not imputing their sins unto them,
but allowing and granting them remission upon true repentance, was, and is a testimony,
and plain indication of the great love, grace and favour of God to the world,
in and through his dear Son.
How wonderfully has God, in his great wisdom, love, kindness, meekness,
long suffering and compassion,
condescended to our low capacities and conditions of the human race,
for our redemption and salvation, by his dear Son Jesus Christ, truly considered,
both as he came and suffered in the flesh, and as he is revealed in the spirit.
O let the weighty consideration of all these things deeply
affect all our hearts and souls sincerely to love,
serve, fear, worship and praise the Lord our most gracious God,
through Jesus Christ forever!

It is to be seriously observed and remembered,
that when Jesus Christ was about to take leave of his disciples,
he recommended them unto the Spirit of truth, the Comforter,
which should testify of him and abide with them forever;
and that he would manifest himself to him that loved Him, and that in a little while,
they, i. e., his disciples, should see him, that is Christ Jesus;
so though he went away in the body, he would come again to them in spirit.

Now, dear friends, it being the Holy Spirit which testifies of our Lord Jesus Christ,
and shows unto us what he takes of Christ, he i. e., the Holy Spirit, shall take of mine,
said Christ, and show it unto you.

The Holy Ghost takes, and shows unto us,
the most excellent properties of our great and glorious Mediator,
his great universal love, meekness, humility and compassion,
that we may by degrees partake thereof,
as we truly obey and follow him in the manifestation of the same Holy Spirit,
whereby the mystery of Christ is revealed,
in and unto the truly spiritually minded believers in his light,
and thereby they become the children of the light.

As our Lord Jesus Christ hath, by his sufferings, one offering, sacrifice and death,
put an end to all the legal offerings, types, shadows and figures, outward ordinances,
rites and ceremonies, and divers washings, or baptisms,
under the Law of Moses and Levitical priesthood, he continues a Priest forever,
after the order of Melchisedeck, King of righteousness and King of peace,
our High Priest over the house and family of God; he having consecrated,
prepared and opened the new and living way of the new covenant,
through the veil of his flesh, for our access into the most holy sanctuary.

Wherefore let us consider what great love God in his divine
wisdom has manifested through his dear Son,
for us and to us; yea, toward the children of men,
that we might have and know access into his everlasting covenant of grace,
mercy and peace, in and through his dear Son Jesus Christ.
Let us prize his great love and goodness forever,
in bringing us into a more glorious dispensation than all
the former dispensations of the law and shadows,
under which the light was so far veiled, that the people of Israel,
when the veil was over their heart, could not look to the end of those shadows and veils,
which were abolished by Christ, but now vanished and fled away,
by the Sun of righteousness more gloriously manifest and brightly shining,
in the new covenant and spiritual dispensation of Christ,
than in all the former dispensations.
So that Moses`' face is unveiled in this day,
although God was pleased to afford his word,
his light and spirit to visit the children of men,
in all generations since the beginning.
And even in the time of the law and the prophets, the voice, the Word and Spirit of God,
was testified unto by Moses, the holy prophets and servants of God,
and the people warned and exhorted to obey the same, for salvation and peace;
but in the day of Christ and of the gospel,
more clearly manifest and brightly shining than under the legal types and shadows,
which Jesus Christ, the substance, put an end to and abolished.
Abraham saw Christ`'s day and rejoiced;
and the spirit of Christ in the holy prophets testified aforehand,
both of his sufferings and of the glory of his day, that should follow.

Now, dear friends, the gospel day, the day of Christ and of his power being dawned,
as in the primitive spiritual Christian days;
after a long night of apostacy and ignorance, the day-spring,
the (sun-rising) from on high having visited us by
the spiritual coming again of our Lord Jesus Christ,
and affording us of his glorious light and Holy Spirit,
let us all sincerely obey and walk in the same,
that we all may have and enjoy life and peace in him,
who has opened a living way unto us into the new
and everlasting covenant of grace and peace;
and let us all continue therein.

The dispensation of Christ is spiritual and glorious, which we are called unto;
it is a ministry of the spirit of Christ, of his light and spirit,
and it must go over all the world and continue unto the end.

When the Lord had opened the eyes of our minds and understandings,
so as our minds were turned from darkness to the light of our Lord Jesus Christ,
and from the power of Satan to God, then we knew true repentance,
and that our true beginning,
in order to receive the true and spiritual knowledge
of our Lord Jesus Christ and true Christianity,
was in the spirit and not in the letter, nor in fleshly observations,
elements or rudiments of the world.

And it was by the same Holy Spirit,
that the excellency of the knowledge of our Lord Jesus Christ,
and the fellowship of his sufferings,
came to be revealed and experienced by degrees in us,
as we followed the same spirit of holiness.

O what excellency is in the true knowledge of our blessed Lord Jesus Christ?
and unto what poverty of spirit and loss of all that is of self must men be reduced,
to obtain this knowledge and to win Christ, and be found in him,
according to the confession of the holy apostle!
Phil.
3.

And what fellowship of Christ`'s sufferings must persons be led into,
if they be made conformable unto his death,
and come to have or enjoy the righteousness which is of God by faith,
even by the faith of Christ?
What then were Christ`'s sufferings?
"`Surely he hath borne our griefs and carried our sorrows:
He was wounded for our transgressions and bruised for our iniquities,
and the chastisement of our peace was upon him; he was oppressed and afflicted,`" etc.

Surely they who come truly into the fellowship of Christ`'s sufferings,
it must be spiritually, by being sensibly burdened, grieved and sorrowful,
wounded and bruised, chastised and afflicted,
for their own transgressions and iniquities,
under the reproofs and chastisements of the spirit of the Lord Jesus Christ,
unto true repentance,
remission and forgiveness of their iniquities through Christ that was wounded, bruised,
yea, and crucified for them, though he never sinned:
and in order to be made conformable unto his death, we all must be crucified with him.
Men must come under the death of the cross,
and by the power of Christ be baptised into his death,
having crucified the flesh with the corrupt affections and lusts thereof,
which they who are Christ`'s true followers have done,
being risen with him by the faith of the operation of God.

Oh! such a suffering, dying, rising and living with Christ, unto God,
must needs be known and inwardly experienced in true believers,
by the work of his grace and Holy Spirit,
which therefore we all ought diligently to follow and walk therein,
that as we all have begun well, at the true beginning in the spirit,
we may hold on in faithfulness unto a blessed end and crown of righteousness.

Dear friends,
how precious is it to be partakers of the excellency of the knowledge of Christ Jesus,
as our Lord, through the fellowship, fruits and benefit of his sufferings,
mediation and intercession!
Let us forever truly prize the great love of God,
so eminently manifest in his dear Son Jesus Christ, by his Holy Spirit!

As the true and saving knowledge of Jesus Christ
is only after the spirit and not after the flesh,
and the glorious mystery of Christ in men revealed by the spirit,
so we ought all to be spiritually minded,
minding the divine light and holy Spirit of grace in our hearts,
and to know one another after the spirit, in a spiritual sense and communion,
that the fellowship of this mystery of Christ may
be truly known and livingly increase among us,
to the glory of God and honour of his beloved Son,
and our universal comfort and true joy in Him, who is the true God and eternal life.

I well remember, how in early days, after we were truly convinced,
and received the blessed truth in the love and simplicity thereof,
and thereby were led into plainness of speech and habit, etc.,
we did in measure also outwardly partake of the fellowship of Christ`'s sufferings,
by being reproached, opposed,
contradicted and calumniated for his name and truth`'s sake,
by the wicked and loose professors and profane;
we resigned unto obedience and bearing the cross for his sake,
who endured a more severe cross for our sakes before us.

It was in the love of the living truth and simplicity which is in Christ Jesus,
through obedience to him in his light and grace, that we became espoused unto him:
this progress is not to be forgotten by any who would be betrothed in righteousness,
true and constant love, unto Christ Jesus, as our spiritual head and husband,
which he truly is unto his church, or mystical body.

O! my dear and beloved friends, be retired inwardly, in your minds and spirits,
unto the light, the grace, the good Word and Spirit of the Lord Jesus Christ in you,
that you may experience the holy Seed, the Word of eternal life and grace,
to grow and prevail more and more, unto an immortal birth and holy generation,
as you become born thereof.

And, dear friends, I cannot but remember the love of our espousals,
and the kindness of our youth at the beginning, and in early days,
and remind you thereof, when we as chaste virgins,
were therein espoused unto Jesus Christ, and when but a few in number;
and how sincerely we loved one another, that we were one another`'s joy in the Lord;
who said unto Jerusalem of old, "`I remember the kindness of thy youth,
the love of thine espousals, when thou wentest after me in the wilderness,
in a land that was not sown;`" which was a low suffering state of deep trials.
Oh! the first love of our espousals should never be impaired, nor left, or forgotten,
but forever retained,
or otherwise we cannot live to God nor prosper in a Christian life in Christ Jesus,
or keep chaste to him as his true spouse and church of the first born written in heaven.

Now, dear friends, to come into and live in a true Christian love and life,
must be through a real self-denial, and taking up the daily cross,
and following Christ Jesus and his example and steps.

This self-denial must be an abasement and denial of all proud conceited self,
that is exalted above others, in secret pride abounding in one`'s own sense,
slighting and contemning others;
and what other evils and corruptions perverse self is addicted unto,
must all be denied and utterly rejected by all who
come to embrace a humble Christian life and condition.

This real denial of self will not allow any to exercise lordship over God`'s heritage,
nor any rigid overruling thereof, though they should pretend eldership;
but to be humble examples to the flock of Christ,
and as fellow helpers in the Lord of the younger, the weak, the feeble and tender,
so as not to quench any good intentions or desires in any such;
and in all humbleness of mind, meekness and long suffering, forbearing,
or supporting one another in love, therein endeavouring for,
and to keep the unity of the spirit in the bond of peace.

And as we are called by one spirit into one true light, life and love,
let us all endeavour diligently in humility to walk therein,
that we may truly appear to be one peculiar people of God and Christ,
one church of the firstborn, one spiritual society, and of one city set upon a hill,
fellow-citizens with the saints, set upon the holy hill of Zion,
shining in the brightness thereof, in all holy conversation, to the glory of our God.

For such is the blessed and glorious state of the true church, the spiritual Zion,
the heavenly Jerusalem, which the saints,
the primitive church of Christ and true Christians of old were come unto,
and also to Jesus the Mediator of the new covenant; whose eyes the Lord had opened,
that they were turned from darkness unto his light, and thereby became light in the Lord;
and they were no more foreigners, nor strangers to the commonwealth of Israel,
who continued faithful, and true believers in the light.

O! how great are the privileges and spiritual blessings in Christ Jesus,
which his faithful subjects and fellow-citizens with the saints partake of,
even in this life!
And how much more in that to come, in his kingdom of glory and triumph!

Zion and Jerusalem, when Israel`'s solemnities of worship were kept in the temple there,
as God had appointed under the law, were in great splendor and applause;
typifying the true spiritual church,
or city of the saints solemnities under the dispensation
of Christ and his glorious gospel,
in whom the most excellent and glorious promises,
to spiritual Zion and heavenly Jerusalem, which are yea and amen,
are fulfilled unto his gospel church: "`The Lord loveth the gates of Zion,
more than all the dwellings of Jacob: glorious things are spoken of thee,
thou city of God.`"
Again, "`Look upon Zion, the city of our solemnities:
thine eyes shall see Jerusalem a quiet habitation,
and a tabernacle that shall not be taken down,`" etc.
This was not fulfilled upon earthly Jerusalem,
for that was taken down and laid waste with the temple and sumptuous buildings thereof,
because of the great provocations, iniquities and cruel persecutions of the Jews,
against the servants of the Lord, and even against the Son of God himself.

Now, beloved friends and brethren, who are called out of darkness into the true light,
and to be fellow-citizens with the saints in light, of whom it may be said,
"`ye are come unto Mount Zion, and unto the city of the living God,
the heavenly Jerusalem,`" etc., walk in the light of the holy city of God,
whereof the Lord God and the Lamb is the light,
and wherein the nations of them that are saved must walk;
that salvation may encompass you, and be as walls and bulwarks unto you,
that the enemy may not invade or scatter you;
that the righteousness of Zion and Jerusalem may go forth as brightness,
and the salvation thereof as a lamp that burneth.

Wherefore, arise, O Zion! and shine, for thy light is come,
and the glory of the Lord is risen upon thee; put on thy strength,
O Zion! put on thy beautiful garments, O Jerusalem! the holy city, etc.

Pray, you friends, consider what the beautiful garments are,
which the inhabitants of the city of God must put on,
and be clothed withal in our Zion and Jerusalem, the true spiritual church?
Must they not be such as the holy apostle exhorts to put on and describes?
Namely, "`Now therefore, as the elect of God, holy and beloved, put on bowels of mercies,
kindness, humbleness of mind, meekness, long-suffering, forbearing one another,
and forgiving one another,
(if any man hath a complaint or quarrel against another) even as Christ forgave,
so do ye.`"
But first the filthy garments must be put off,
the old man with his corrupt lusts and evil deeds,
with all the filthy rags of self-righteousness; these must be mortified and put off,
and the creature also divested of all its own filthy rags of self-righteousness,
before it be invested with the beautiful garments of Zion, or heavenly Jerusalem,
the true spouse of Christ Jesus, or married to the Lamb.
Therefore it greatly concerns all to follow him in the work of regeneration,
the work of sanctification by his Holy Spirit and power, and therein believe,
and sincerely obey him, for the perfecting of holiness in the fear of God,
that Christ may be formed in you; and in his life manifest in you,
all may shine forth as the called, chosen and faithful people of God,
to your everlasting peace in his dear Son, and to the honour,
the glory and renown of his great and excellent name forever.

I would further remind you of this weighty exhortation
of the holy apostle to the church of Christ at Colosse,
viz: "`Above all these things put on charity, (i. e.,
true love) which is the bond of perfectness:
and let the peace of God rule in your hearts, unto which ye are called in one body,
and be ye thankful.`"

The Lord Jesus Christ be with you, and endue you with his holy Spirit of grace,
wisdom and revelation in the knowledge of the mystery of Christ,
that he may dwell in your hearts by faith,
and by his power you may be rooted and grounded in his love,
grace and peace more and more, to the glory of his name,
and your everlasting consolation and joy in his heavenly kingdom.
Amen.

And now, dear friends, let us consider the only begotten Son of God,
our blessed Lord Jesus Christ,
and what confession and honour is given unto him in holy Scripture,
both respecting his eternal Deity and perfect manhood,
and coming therein manifestly in due time, which I mention in order to clear us,
the people termed Quakers, from the unjust imputations of our adversaries,
one while with denying the divinity, another while with denying the humanity of Christ,
or both, as some have done;
and to prevent all occasion of doubts or disputes about the same matter,
I refer you and all concerned to the Scriptures following, viz:
Isa. 7:14.
The Lord himself shall give you a sign;
behold a virgin shall conceive and bear a Son, and shall call his name Immanuel.

A prophecy of Jesus Christ, respecting his birth of the virgin, as a man child,
and his being Immanuel, God with us, or in us.

Isa. 9:6, For unto us a child is born, a Son is given,
and the government shall be upon his shoulder, and his name shall be called Wonderful,
Counsellor, the Mighty God, the Everlasting Father, the Prince of peace:
of the increase of his government and peace there shall be no end.

An excellent prophecy and testimony of Jesus Christ, respecting his birth as a man child,
and his divine wisdom and Deity, as Mighty God, the Everlasting Father, etc.
Mic. 5:2.
and Matt. 1:23. and ii.
1+++.+++ But thou Bethlehem Ephratah, though thou be little among the thousands of Judah,
yet out of thee shall he come forth unto me, that shall be ruler in Israel;
whose goings forth have been from of old, from everlasting.

Showing that Christ existed, as to his Divinity, before he was born in Bethlehem in Judah.

John i. ch.
to ver. 14. In the beginning was the Word, and the Word was with God,
and the Word was God: the same was in the beginning with God;
all things were made by him, etc.
Read to ver. 14. And the Word was made flesh, and dwelt among us;
and we beheld his glory, as the glory of the Only Begotten of the Father,
full of grace and truth.
Rom. 1:3-4.
Concerning his Son Jesus Christ,
which was made of the seed of David according to the flesh,
and declared to be the Son of God with power according to the spirit of holiness,
by the resurrection from the dead: And Rom. 9:5. Whose are the Fathers,
(speaking of Israelites) and of whom as concerning the flesh, Christ came,
who is over all, God blessed forever.

Hence, that Jesus Christ his being truly man and the Son of God, and God over all,
thus declared; first, respecting his manhood, it is said of him, Luke 2nd ch.
And the child grow and waxed strong in spirit, and was filled with wisdom,
and the grace of God was with him: And when twelve years old,
and found in the temple among the doctors, hearing them and asking them questions,
all that heard him were astonished at his understanding and answers,
Luke 2:40,42. 46, 47. and ver. 52.
And Jesus increased in wisdom and stature,
and in favour with God and men.
O wonderful child!
And most excellent heavenly man!
He has left us a blessed example, in order to follow him,
and to grow in his grace and wisdom, by the help of his holy Spirit and power.

Consider also, that by the wondrous works and miracles,
that Christ wrought on earth by the power of God,
he had great adoration and honour in many hearts;
and so do his great and spiritual cures, which by his divine light and power,
he has wrought and worketh on many souls in this day:
glory and honour to his name forever: See Ps. 10:3. and cxivi.
7+++.+++ Isa. 42:6-7. John 11:25-26. Eph. 2:1, etc.

There is no cause to question Christ the Son of God, whom he hath highly exalted,
having a name given him above every name, whereunto every knee shall bow, etc. Phil. 2:9.
Surely, the mighty God or God over all, etc., is a name, yea,
a power divine, above every other name.
Eph. 3:9.
Col. 1:16. And to make all men see what is the fellowship of the mystery,
which from the beginning of the world hath been hid in God,
who created all things by Jesus Christ: Col. 1:16.
For by him were all things created,
that are in heaven and that are in earth, visible and invisible, etc.

As God created all things in heaven and in earth, visible and invisible, etc.,
by Jesus Christ; this bespeaks his being the eternal Wisdom, Power and Word of God, John 1:3.
Rev. 19:13.

See likewise Heb. 1:1-2. God who at sundry times, and in divers manners,
spake in time past unto the fathers by the prophets,
hath in these last days spoken unto us by his Son,
whom he hath appointed heir of all things, by whom also he made the worlds.

Then the Son of God was before the worlds were made; to which agrees, Heb. 11:3.
Through faith we understand,
that the worlds were framed by the Word of God.

See also, John 5:21-23. As the Father raiseth up the dead, and quickeneth them,
even so the Son quickeneth whom he will; for the Father judgeth no man;
but hath committed all judgment unto the Son, that all men should honour the Son,
even as they honour the Father: he that honoureth not the Son,
honoureth not the Father which hath sent him.

How can any so honour the Son, who count him only a mere man?
John 17:5.
And now, O Father!
Glorify thou me, with thine own self, with the glory which I had with thee,
before the world was.

These were Christ`'s own words and testimony, in his prayer to the Father.

See 1 John 5:20. How +++[+++the true God and Eternal Life]
is ascribed to the Son as well as to the Father, who are one; John 10:30.

It is also observable, The children of Israel, who were all baptised unto Moses,
in the cloud and in the sea; and did all eat the same spiritual meat;
and did all drink of the same spiritual drink,
for they drank of that spiritual Rock that followed them,
(or went with them) and that Rock was Christ; 1 Cor. 10:2-4.

And this was long before Christ came in the flesh; Christ was and is the Rock of ages,
and Foundation of many generations, both before and after his coming in the flesh.

Now dear and well beloved friends, for as much as, ever since a people,
we have believed Christ as the true Light and his coming in the flesh;
these Scripture testimonies of him, as to his divinity and manhood,
are recited rather in defence of our Christian faith and holy profession,
against our adversaries unjustly rendering us no Christians,
than to suppose any deficiency on your parts relating thereunto.

The Lord be with you all,
and possess your hearts with his dear love and divine wisdom in Christ Jesus.

[.signed-section-signature]
George Whitehead.

--
