[quote.epigraph, , Ps. 115:1]
____
Ascribe the glory of all to God, for his mercy and truth`'s sake.
____

[quote.epigraph, , Isa. 1:5]
____
The Lord hath opened mine ear,
and I was not rebellious, neither turned away back.
____

[quote.epigraph, , 1 Sam. 7:12]
____
Hitherto hath the Lord helped us.
____

== Chapter I

Remembering the Lord our gracious God,
in his ways and merciful dealings with me from my youth;
how he found me among his lost and strayed sheep,
on the barren mountains of fruitless professions,
and how he drew me to an inward experience of his power and sanctifying work in my heart,
and to know his teaching and spiritual ministry; thereby to enable me by degrees,
experimentally to minister to others, and oblige me to live accordingly;
as also to suffer patiently, with resignation of liberty and life for Christ`'s sake,
when called thereunto, and being supported by his power,
and cheerfully carried through many great trials
and deep sufferings for his name`'s sake,
and having had many eminent deliverances and preservations, even from my young years;
I say, considering these things,
I have been the more concerned for my friends and brethren,
who for conscience-sake have deeply suffered by imprisonments and spoil of goods;
and in the tender bowels of Christ Jesus have truly sympathized
with the faithful in their sufferings and afflictions;
and in his love been many times moved and stirred
up to plead their innocent cause before authority,
as well as to solicit with great industry on their behalf;
wherein the hand of the Lord has been often with me,
and his presence and counsel have strengthened and helped me,
in answer to my prayers and supplications,
and his power by degrees prevailed to mollify the hearts
of many in the several governments towards us.
Glory to the name of the Lord our God, who pleaded the cause of the innocent.

For these reasons, a concern hath long been upon my spirit,
to leave some remarks and footsteps--by an historical account--of my progress,
under the Lord`'s help and conduct, in his work and service: and in order thereto,
to collect from divers papers, notes and memorial, I had reserved,
some of those exercises and transactions,
wherein I have been both actively and passively concerned on Truth`'s account;
and to digest the same into such a plain method as briefly as I well could,
and as I thought might be most intelligible, both in point of fact and doctrine,
with such observations as might conduce to the good end intended, namely,
the glory of God, the honour of his excellent name,
and the advantage of the serious reader,
the more to consider of his divine grace and goodness, which endure forever,
to them that truly love and fear him.

In my time, I have been greatly exercised in defence of the truth of the gospel,
wherein the Lord did early assist me, by his Spirit and power;
on which account I have been concerned in many more
controversies and disputes than are herein related;
and omitting many circumstances,
I have endeavoured not to make too voluminous a narrative,
but sincerely to relate the substance of the most material passages,
which concern our Christian profession and principles, held from the beginning.

Those of our principles which have been chiefly opposed by our adversaries,
and which I have been most obliged to vindicate and dispute for, are,
the light and perfection; the gospel urim and thummim; the kingdom of Christ,
against the kingdom of Satan and antichrist.
Let God arise, and His enemies be scattered.

From early inclinations and desires which the Lord was graciously
pleased to stir up in my heart towards his blessed truth,
as it is in Christ Jesus, I was drawn to be inquisitive after the knowledge thereof,
and how to become truly penitent,
and witness a true amendment of life from such a vain conversation,
as in my childhood I had, with many others, been prone to.
Being partly educated under a Presbyterian ministry,
which the Lord showed me in divers things,
came short of what they professed and pretended in their worships,
preachings and prayings; insomuch that before I heard of the people called Quakers,
I could not cordially join with them; and being at a loss in my spirit,
for what I sometimes secretly desired and wanted, I was as one bewildered,
and wandered further, seeking among other people,
who had some higher and more refined notions concerning spiritual gifts, etc.
I was then about fourteen years of age.

After a short time, I heard of some people called Quakers,
who trembled at the word of God;
and observing how they were reviled and reproached by loose and wicked persons,
occasioned my further inquiry, and thereupon the Lord gave me to believe,
they were his people, and I contended for them and their principles,
so far as they were represented favourably to me, before I was at a meeting of theirs,
or heard any of them minister.

And though the Lord had raised good desires in me toward himself,
that I might know true repentance unto life, yet those desires were often quenched,
and my mind led away through an airy, light disposition, fondness for music, vain mirth,
and other vanities, like other children and youth, when conversant with them.
Howbeit,
the Lord was graciously pleased secretly to follow
me with judgment and reproof in my very young years,
and renewed desires in me after the right way.
But I wanted to know a stay to my mind,
while a hearer of the priests and other professors, not knowing,
or following that light of Christ in me,
which convinced and reproved me for the sins of my youth.

The light shined in darkness, as in a dark place, and was often, clouded,
before it shone out of darkness.
The spirit of the Lord moved upon the waters,
even when darkness was upon the face of the great deep,
before his works of old were wrought.
And in order to bring forth his works in the new creation,
to make us new creatures in Christ Jesus, his spirit moves upon people`'s hearts,
even when unstable as waters,
and his light shines in them before they know God or Jesus Christ,
in order to give them the knowledge of the glory and power of God,
and of his dear Son Jesus Christ.

After some religious discourses with some young men soberly inclined,
and when we had newly heard of a few people called Quakers, in Sedbergh, in Yorkshire,
and in Kendal Barony in Westmoreland,
I was--after my other seeking and wandering--desirous to go to a meeting of theirs,
which was at one captain Ward`'s, at a place called Sunny Bank, near Grayrig chapel.

At my first going to the said meeting, what was most observable to me was,
when I came into the meeting, and sat down seriously among them,
after a little space of silence, a Friend, Thomas Arey,
spake a little while of the spiritual deliverances, travels and progress,
of the Lord`'s people in his way and work;
alluding to Israel`'s deliverance out of Egypt, from under Pharaoh and his task masters.
All which I thought I easily understood allegorically, or mysteriously, as spiritualized;
but there appeared to me a great work of the power of the Lord in the meeting,
breaking the hearts of divers into great sorrow, weeping and contrition of spirit,
which I believed was a godly sorrow for, sin, in order to unfeigned repentance.

I was the more confirmed herein, seeing a young maid go mourning out of the meeting,
whom I seriously followed to observe her sorrowful condition; and beholding her,
being sat down on the ground, with her face down toward the earth,
as if she regarded no body present, she mourning bitterly, cried out.
Lord, make me clean; O Lord, make me clean.
This did far more tenderly and deeply affect my heart than what I had heard spoken,
and more than all the preaching that ever I had heard from man or men.
It was a certain testimony to me, the spirit of the Lord evidencing to my spirit,
that it was a real work of his power upon her heart,
which also operated upon the hearts of others, causing both trembling,
sorrow and contrition, in order to bring them to true repentance and amendment of life,
and so truly to experience the work of regeneration and sanctification,
from sin and uncleanness; and accordingly it proved so to many;
glory to our God forever.

These things upon serious observation, making deep impression upon my mind,
I was the more confirmed in the belief I had before,
that the Lord was at work among that small despised people,
and that he was about to gather and raise up a people unto himself,
to worship him in the spirit and in the truth,
for such he seeks to worship him acceptably; and that this his worship,
is not in the dead and empty forms set up in the will of man.

Under these considerations, I was induced soon to leave the parish priests,
or ministers made by the will of man, having no divine authority from God,
nor commission from Christ, to teach others;
they themselves also being no good examples to the flock,
by their pride and covetousness, contrary to Christ`'s command,
and his ministers`' example, insomuch that I knew I ought to turn away from them,
as in a very short time I did, after the Lord by his light opened my eyes,
to see the blindness of those guides whom I had followed by education and tradition.

And though I met with opposition and hard speeches from some near
relations and others who were hearers of those priests,
for confessing and vindicating truth,
according to that little measure of understanding I then had,
being but weak and young in years, and beset with divers temptations and discouragements,
yet the Lord my God helped and persuaded me to lake up a resolution,
not only wholly to leave the said priests,
but also constantly to resort to the meetings of his despised people called Quakers,
and to sit down among them,
though then but few in number in comparison of what they are since.
Their meetings, which I frequented, were for some time in Sedbergh parish in Yorkshire,
and sometimes in Grayrig and that way, near Kendal in Westmoreland,
the county where I was born.

Some time after I was fully convinced, and my mind turned to the light,
and I was persuaded and resolved to persevere among Friends,
before I heard our dear Friend George Fox.
The first time I heard him minister, was at an evening meeting at Sunny Bank aforesaid,
at Captain Henry Ward`'s house.
I was then very low, serious, and intent in my mind, willing to see and taste for myself,
for my own inward satisfaction;
and I saw and felt that his testimony was weighty and deep;
that it proceeded from life and experience, and did bespeak divine revelation,
and tended to bring to an inward feeling and sense of the life and power of Christ,
and the sanctifying operation thereof in the heart.
His speech was not with affected eloquence or oratory, or human wisdom,
but in the simplicity of the gospel, to turn the mind to the light and life of Christ;
and the Lord abundantly blessed his ministry to many.

Our meetings in Sedbergh then were often at Thomas Blaykling`'s house,
whose family was honest, and of good reputation, and at Gervas Benson`'s house,
who had been a justice of peace; at Richard Robinson`'s at Brigflats,
who was an innocent faithful man, and at other places near, in those parts.
In Westmoreland, the meetings I sometimes went to,
were often at Henry Ward`'s at Sunny Bank, and some other places near the same,
and near Kendal.

Being joined to the said people, in derision named Quakers,
and by the grace of God resolved to continue and persevere in their communion,
and to wait upon God in his light,
wherewith he had enlightened my understanding in a good measure,
I had great satisfaction therein,
being sensible that our society and converse with one another,
as we had received the love of the truth, was helpful and encouraging to us,
and tended to our edification and comfort.
I greatly loved and delighted in the free conversation and fellowship of sober,
faithful Friends.
When I was a school boy at the free-school at Blencoe in Cumberland,
I loved retirement with some other sober, studious scholars,
though but mean and poor in the world, rather than the company of loose,
extravagant boys, though of the gentry, or richer sort,
who were given to much play and gaming.
In that company of which I was most fond,
we were the most profitable one to another in our learning,
and communicating the effects of our studies to each other;
and much more in a spiritual and higher sense,
when we were in some degree come to know the blessed Truth,
in the light of our Lord Jesus Christ.
Our Christian society, and communications therein of our inward experiences,
did all redound to our mutual help and edification in the love of the truth,
as it is in Christ, the light and life, and our great Apostle and minister,
who teaches his true followers to profit in that love and life which flows from him,
the Fountain and Foundation of all our mercies; helps,
and lively encouragements in his way and work,
to whom alone be the praise and glory thereof forevermore.

As to the progress,
which by divine assistance I came to experience in
the work of the Lord Jesus Christ in me,
after I came to be resolved and settled in my mind and conscience,
to join in communion with the said people, and to frequent their assemblies as aforesaid,
the Lord by his light and grace of his Holy Spirit, having fully persuaded me,
that without being converted as well as convinced, and without being regenerated,
sanctified, and born again, I could not enter into his kingdom, nor be an heir thereof;
and that the godly sorrow unto true repentance, and a real amendment of life,
must be wrought by his grace and good spirit in me; and,
that without holiness none can see God.

Upon these, and such serious Christian considerations,
I was persuaded by the grace of God, to give up in obedience to follow Christ Jesus;
to believe in, and obey his light given me, and to wait therein diligently,
to receive power from him to become a true child of God;
for as many as truly receive Christ the Son of God,
he gives them power to become sons of God.

I saw it was my place to retire inwardly to the light, to the grace of God, the immortal,
incorruptible seed, the ingrafted Word, which is our divine principle,
frequently testified of among the said people, according to Holy Scripture.

And my mind being turned to this light,
I came plainly to see my inward and outward state,
and how much I was fallen into a state of degeneracy; how much depraved, corrupted,
and alienated from the life of Christ and of God.
The very vanity of mind and thoughts wherein I had been wandering,
and estranged from the light and life of Christ,
became my great burden and exercise to be delivered from,
that 1 might be truly renewed in the spirit of my mind, and therein joined to the Lord.
I was persuaded to wait in the light, in the way of his judgments,
and to bear and submit to his fatherly chastisements, and reproofs of instruction,
believing, that Zion must be redeemed through judgment,
and her converts with righteousness.
Vain thoughts, imaginations, and wanderings of the mind,
became a suffering and burden to me,
and I earnestly sought the Lord for power to suppress and give me victory over them all,
and to stay my mind upon himself, that I might enjoy inward peace with him.

I had a spiritual warfare to go through, and a body of sin to put off and be destroyed,
though not grown to that maturity, as many of riper years,
who are guilty of many gross evils, by their longer continuance and custom in sinning;
nevertheless I knew a real necessity of the work of sanctification,
inward cleansing from sin, and being born again.
That is the new birth that is born from above,
which only is entitled to the kingdom of Christ and of God,
which no unclean person can inherit.

In waiting upon God, and sincerely seeking after him with my mind inwardly retired,
and my soul desiring and breathing after his name and power,
he was graciously pleased often to renew his merciful visitations to my poor soul,
and in the midst of judgment and chastisements, to remember mercy,
that he might be feared.
The sense thereof did often break and tender my heart,
and cause me to be the more mindful of the work of the Lord our God,
and the more to consider the operation of his divine hand,
whose dealing with me was in judgment and mercy; his eternal word by judgment,
caused fear and trembling in his presence, and by showing mercy, brokenness,
and true tenderness of heart, which I often felt.
In the lively remembrance thereof,
I find still great cause to ascribe the praise and glory to his excellent name,
power and divine goodness, manifest through his dear Son, even the Son of his love,
our blessed Lord and Saviour Jesus Christ.

Many of the Presbyterian priests in Westmoreland, and other northern parts of England,
appeared very envious against us, in the years 1652, 1653, and 1654.
And in their lectures and sermons they reviled and
reproached the Quakers and their ministers,
terming them deceivers and antichrists, come in the last times;
gathering what evil and false reports they could
to incense their credulous hearers against us,
thereby setting both neighbours and families at variance and discord,
like invidious sowers thereof.

Some of their hearers, even of my own relations, and others,
when they have come from their public worship,
and from hearing a preachment against Quakers, have come full fraught therewith,
to talk against them, oftentimes nonsense;
sometimes 1 have returned them a Christian answer, which when rejected,
I have many times found it my place to be silent, and let them clamour and scoff on;
the leaders of the people, even those priests, caused them to err,
and with their sour leaven, soured the spirits of many into enmity,
whereby they hurt many.

My parents were hurt by them, and the more influenced against me for a time,
until the Lord turned their hearts, and opened their understandings,
to see better than they would by following their blind guides,
whose work was to make divisions;
yet my parents and relations had great natural affection and care in their way for me.
For when they appeared most opposed and offended, which was a near trial to me,
because I left their church and ministers, and was joined with the people called Quakers,
their trouble and grief came more from their priest`'s influencing them against us,
and fear of my misfortune, or losing preferment in the world,
than either from any prejudice against me, or my religious profession.
They retained a real natural love and affection to me,
while I was absent from them in the ministry and service of the Truth, about three years,
and in that time had suffered several hard imprisonments, and otherwise for the same,
in Norfolk and Suffolk; and returning to visit them,
they were much reconciled and loving to me,
and their understandings and hearts opened toward me and my friends,
who came to visit me, when at their house.

My mother, some years before her decease, was really convinced of the Truth,
and became a Friend in her heart: and my father seeing the corruption,
pride and avarice of the priests,
retained a love toward Friends till the end of his days.
Likewise my sister Anne, before the death of her mother,
became a friend to Truth and Friends, and continued so, an honest, loving,
and serviceable woman, until death.

It is observable, when the priests or parish ministers,
could not prevail to stop the progress and spreading
of the blessed Truth and power of Christ,
nor prevent the increase of our friends therein,
by all their lectures and reviling sermons and preaching against us,
their work was to endeavour to incense the magistrates, justices, and the government,
against the people called Quakers;
whereupon divers justices and officers were instigated to persecution,
and imprisoned many of our Friends in Kendal and Appleby jails, in Westmoreland,
for bearing testimony against them.
I was moved in the dread and fear of the Lord,
to bear public testimony against their wickedness
in several of their places of worship in Westmoreland,
before I travelled into the south parts of England,
yet the Lord was pleased to preserve me then, from any harm or imprisonment,
having a further work for me in other parts of the nation.

After I had been some time conversant among our friends,
and frequented the meetings to which I belonged, in Westmoreland and Yorkshire,
chiefly between the years 1652 and 1654,
being much inwardly exercised in waiting upon the Lord among them,
where we had little preaching, but our meetings were kept much and often in silence,
or but few words declared, the Lord was pleased sometimes by his power and word of life,
to tender and open my heart and understanding, so that he gave me, among some others,
now and then a {"`ew words livingly to utter, to their and my own comfort,
in Him who opened our hearts in great love one to another,
which then increased and grew among us; blessed be the Lord our God forever.
It was out of these, and such frequently silent meetings,
the Lord was pleased to raise up, and bring forth living witnesses, faithful ministers,
and true prophets, in early days in Westmoreland, and other northern parts,
in the years 1654 and 1655.

The Lord our God having in these latter days and times been
pleased to visit this island with his gospel day and power,
according to his promise unto the Gentiles, and the isles that should wait for his law;
and that his elect, his Christ, in whom his soul delighteth,
should bring forth judgment to the Gentiles; Isaiah xlii.
we also waiting in true silence upon him, and eyeing his inward appearance in spirit,
and the work of his power in us, came truly to see and feel our strength renewed,
in living faith, true love and holy zeal for his name and power;
insomuch that the Lord gradually brought us to experience what he said of old,
by his holy prophet; "`Keep silence before me, O islands;
and let the people renew their strength: let them come near; then let them speak:
let us come near together to judgment.`"

Thus keeping silence before the Lord,
and drawing near to him in a true silent frame of spirit,
to hear first what the Lord speaks to us, before we speak to others,
whether it be of judgment or mercy, is the way for renewing our strength,
and to be his ministers, to speak to others only what he first speaks to us.
O! that the people truly minded this; that they would seriously consider hereof;
then would they not run after, or follow such as their ministers, priests, or prophets,
who run and God never sent them; who say,
"`Thus saith the Lord,`" when God hath not spoken to them; and,
"`who shall not profit the people at all.`"

Before I was esteemed a Quaker, or was joined in communion with them,
I had some understanding given me concerning those parish ministers, or priests,
that they were not sent of God or Christ,
having no divine commission or call to the ministry,
but were made and set up by the will of man, and not experienced,
but artificial preachers of what they studied, or gathered from others,
and composed beforehand, without either waiting for,
or receiving immediate openings or instructions from the spirit of Christ;
and without so much as the real belief thereof,
or of any necessity of the immediate help of the spirit and power of Christ Jesus,
for his ministry, or thereby to preach Him in these days.
But contrariwise, they have denied the same, and opposed our Christian testimony therein,
which none of Christ`'s sheep or flock will do,
for they both hear and know Christ`'s voice, and follow him,
he being their leader and commander; and a stranger they will not follow.

Their pride and covetousness set many well inclined people against,
and caused some to turn away from them; and the more,
when many of them showed their envy and covetousness, in persecuting, imprisoning,
and greatly oppressing the people called Quakers,
for conscientiously refusing to pay tithes, either small or great,
or to gratify the priest`'s avarice.
For the value of a tithe pig or goose, etc.,
they have prosecuted divers honest men to imprisonment in jails,
as if they valued their neighbour`'s pig or goose which they coveted,
more than the liberty or life of their neighbour.
Oh! inhuman and unmerciful!
But when the priests became rigid persecutors and oppressors of us,
it turned greatly to their own disadvantage, disgrace and shame,
and set tender people against them; and our number, when called Quakers,
the more increased.
Though but weak, we came to be the more confirmed against those persecuting ministers,
or parish priests,
knowing that the Christian religion is not a cruel or persecuting religion, but tender,
loving, and compassionate, and not without natural affection;
for that can be no good religion which is void of humanity, one towards another.
We know also, that true Christians were persecuted, but no persecutors;
that they were patient sufferers, not oppressors;
they prayed for their enemies and persecutors, and sought no revenge against them.

I was early convinced and persuaded that tithes ought not to he required or paid,
under the gospel dispensation.
And the reason why those called Quakers, who are true to their Christian principle,
cannot for conscience sake pay tithes, oblations, and obventions in this gospel day,
is generally: First, Because Christ`'s ministry is, and ought to be, a free ministry,
as he commanded his ministers; "`Freely ye have received, freely give.`"

Secondly, Because Jesus Christ, the one offering, and great Apostle,
and High Priest of our Christian profession,
hath by the offering and sacrifice of himself, put an end to tithes and oblations,
or offerings, and the priests`' revenues,
together with that priesthood and first covenant under which they were upheld and maintained;
according to the reasons and arguments which the apostle gives and urges to the Hebrews,
in the 7th, 8th, 9th and 10th chapters.
So that to demand tithes and oblations, revenues or profits thereof,
appears to be a denial of Christ crucified, and his being offered once for all,
and consequently a denying the privileges of the new covenant dispensation and ministry,
ratified by him through the death of the cross.

To return to my own inward state,
and experience in my spiritual travel and progress--when
the Lord was graciously pleased to lead me through the law,
judgment and condemnation against sin in the flesh, which Christ came to condemn,
in order to bring me to the more glorious ministration
and law of the spirit of life in Christ Jesus,
the foundation of the prophets,
and spiritually to experience the mystery of John`'s ministry of repentance,
the washing of regeneration, the axe being laid to the root of the trees,
as well as the cutting off the superfluous branches,
that a thorough work of regeneration might be wrought, these things were spiritually,
and by degrees experienced inwardly, through the obedience of faith,
waiting and persevering in the grace, light and truth received from Christ,
in order to obtain victory over sin and Satan, that his work of sin,
and the body thereof, might be destroyed root and branch.

And whatever divine openings, prophecies, sights, or discoveries,
the Lord was pleased at any time to give me by his Holy Spirit, for my encouragement,
the increase of faith and hope,
I saw I must still be mindful of his inward work of grace, sanctification and holiness,
that it might go on and prosper.
Although many weaknesses and temptations attended, his grace was sufficient for me,
and oftentimes gave me strength and victory over the enemy of my soul,
and frustrated his evil designs.
When he would have come in like a flood, with manifold temptations and devices,
the spirit of the Lord lifted up a standard against him, and repelled him:
"`Glory to our God, and to the Lamb,
in whom is our salvation and strength forever and ever,
whose kingdom is an everlasting kingdom, and his dominion without end.`"

As our blessed Lord Jesus Christ declared, "`If any man will do his will,
he shall know of the doctrine.`"
It was in the day of his power as the light thereof did appear,
that a willingness was wrought in my heart to do his will,
as the same came to be made known to me, and to follow him in self-denial,
and taking up the daily cross, which every man must do that will be his disciple:
by whose light and teaching I came livingly to believe, understand,
and receive those doctrines and principles essential to a Christian life and salvation,
especially and particularly these following, viz:

[.numbered-group]
====

[.numbered]
1+++.+++ God`'s free love in his dear Son Jesus Christ,
and his universal grace in him to mankind;
and that Christ died for all men that were dead in their sins;
he gave himself a ransom for all, for a testimony, in due time,
of God`'s free love to mankind in general;
for it was by the grace of God that Christ tasted death for every man.
So that the free grace and love of God to mankind, are testified and evident,
both in Christ`'s dying for all men, and by his being the "`Light of the world,
which enlightens every man coming into the world.`"

[.numbered]
2+++.+++ The necessity of men`'s repenting, and truly believing the gospel,
and of being so converted to Christ, as to receive Christ,
and to experience a living and steadfast faith in him, in his light, name and power,
in order to become the children and sons of God, it being by his power,
through faith therein, that men become the sons of God; and not by an outward profession,
or traditional belief without Christ,
or without spiritually receiving Christ into their hearts,
to know his work of faith and power in them, unto conversion,
and a real change of their hearts and minds,
by the washing of regeneration which is sanctification, the one baptism,
which is the saving baptism of the spirit, for the washing us from our sins,
and restoring us to newness of life in Christ Jesus.
To understand and witness that the true and acceptable worship of God
"`Is in spirit and in the truth;`" and not after human traditions,
or forms of men`'s prescribing, was a great satisfaction to my soul,
and to be retired in my mind and spirit, to that holy spirit and truth,
even the living Word, wherein God is truly worshipped, bowed unto,
and waited upon in true humility, for therein he comforts and refreshes his people.
All which every true believer in Christ, our light and life, understands,
and knows the necessity of, even of these things,
which are agreeable to holy Scripture testimony.

====

I always had a love to the Bible, and to reading therein, from my childhood,
yet did not truly understand, nor experience those doctrines essential to salvation,
nor the new covenant dispensation, until my mind was turned to the light of Christ,
the living eternal Word,
the entrance whereof giveth light and understanding to the simple.
Yet I do confess,
it was some advantage to me frequently to read the holy Scriptures when I was ignorant,
and did not understand the great and excellent things therein testified of.
For when the Lord had livingly in some measure opened my understanding in the holy Scriptures,
by my often reading the same before, having the better remembrance thereof,
it was a help and advantage to my secret meditations,
when a lively sense and comfort of the Scriptures was in measure given me by the Spirit,
and thereby I was the more induced to the serious reading
and consideration of what I read in the holy Scriptures,
and the comfort thereof made known by the holy Spirit enlightening the understanding.
All the promises of God, which are yea and amen in Christ Jesus,
being truly comfortable when applied by the same Spirit,
for that will make no wrong application thereof;
that Spirit will never apply peace to the wicked, nor to persons living in their sins;
nor tell the unjust that they are just, or righteous in God`'s sight.
It is through faith which is in Christ,
that the holy Scriptures are said to make the man of God, "`Wise unto salvation,
and profitable to him, for doctrine, reproof, admonition,
and instruction in righteousness,
that he may be perfect and thoroughly furnished in every good word and work.`"
Doubtless, Paul esteemed Timothy`'s knowing the holy Scriptures from a child,
to be some advantage and help to him, but it was principally through faith,
which is in Christ Jesus.

These things considered, I would not have Christian parents remiss in educating,
and causing their children to read the holy Scriptures, but to induce them both to learn,
and frequently to read therein, i. e. the Bible.
It may be of real advantage, and profitable to them,
when they come to have their understandings enlightened,
and to know the Truth as it is in Christ Jesus.
I have sometimes observed children in reading the Bible,
have been affected with the good things they have read, from a secret belief of them,
which hath had such impression,
that they have been induced to a more serious consideration thereof,
when the Lord has opened their understandings in some measure,
by the light of his grace in them.

It was without doubt, an advantage, even to the evangelical prophets of God,
that they knew the Law of Moses,
and understood his judgments and threats therein declared.
They had thereby the more advantage over Israel in their ministry, both to warn them,
and to declare such judgments for their great transgressions,
when it was revealed by the Spirit that any of those judgments were approaching;
and the more advantage they had over the people,
because they had the Law of Moses read among them, and professed the same.
So have Christ`'s ministers, who know the holy Scriptures,
the more advantage over the hypocritical professors of the same as their only rule,
who yet are of irregular, corrupt, and disorderly conversations.

By what I have here declared in commendation of holy Scripture,
and the advantage thereof,
I would not be understood to limit the gift of the Spirit of God, or ministry thereof,
or any of his divine graces, from the illiterate, the unlearned,
or from persons of little education,--as ploughmen, herdsmen, shepherds, fishermen, etc.
For God hath given of his good Spirit, and spiritual gifts to such,
and hath promised "`to pour out of his Spirit upon all flesh;
and that sons and daughters should prophesy.`"
And Moses said, "`Would God that all the Lord`'s people were prophets,
and that he would put his Spirit upon them.`"
Among whom, both men and women, learned and unlearned are included.

My entrance into, and beginning in the spirit,
and believing in the light of our Lord Jesus Christ,
was in order really to come into the new covenant and dispensation thereof;
Christ being given both for a light and a covenant,
and to be God`'s salvation unto the ends of the earth.
This new covenant is a covenant of grace, of mercy and peace with God,
in his dear Son Jesus Christ.
It is that reconciliation, that near agreement with God and Christ,
which man must come into, if ever he enjoys true peace.
It is in this covenant that all the Lord`'s people and true Christians know him,
from the least to the greatest, and are all taught of God;
having also his laws written in their heart, and put into their minds,
by his holy Spirit, His divine finger.
It is in this covenant that the Lord blots out all their former forsaken transgressions,
and remembers their sins and iniquities no more,
they continuing in this everlasting covenant, and in his goodness.
He is a God keeping covenant and mercy forever, to them that truly fear him.
Oh I my cry, my soul`'s breathing, my inward spiritual travel,
my watchings and praying have been, "`O Lord, preserve and keep me in thy holy fear,
in humility, in the sense of thy power; that I may never depart from thee,
nor from thy covenant; that I may never dishonour thy Truth, or our holy profession.
And hitherto the Lord has helped me on my spiritual journey and race towards the prize:
I ascribe the glory and praise only to Him, who giveth power to the faint,
and to them of no might he increaseth strength; and often in my weak estate,
hath manifested strength.
Salvation and strength come from Him who is the God of our salvation,
that his redeemed ones may sing of his salvation; yea, of his judgments and mercies,
and ascribe salvation to our God, and to the Lamb that sits with him upon the throne,
in glory and majesty forever.

As it was my early belief and persuasion, when convinced of the blessed Truth,
that all who are truly called into Christ`'s ministry,
to be ministers of the everlasting gospel, and preachers of righteousness,
must be sanctified, divinely inspired,
and gifted for that sacred work and service of our blessed Lord Jesus Christ;
they must be careful that their conversations be as becometh the gospel;
they must live good lives, as well as speak good words; they must be men fearing God,
and eschewing evil; truly fearing God, and hating covetousness,
and giving no offence in any thing, that the ministry be not blamed; concerning which,
the Lord hath laid upon me a godly care, which still remains upon me,
both for myself and others; that our ministry be not blamed,
and that no offence may be given to cause blame thereupon.
What signifies it for any to have a name to live, when they are dead?
What will it avail them?
Or for loose, vain, proud, covetous, or unsanctified persons,
to pretend to be in holy orders, when they themselves are altogether unholy, polluted,
and sinful?
I was in my very young years fully persuaded,
that Jesus Christ would neither employ wicked or
corrupt persons in his sacred service of the ministry,
nor afford such his presence in their preaching,
whatever they pretend or profess in his name.
It is Christ`'s faithful ministers who truly obey him, and follow his example,
that he will accompany with his divine presence and
help in their ministry and gospel testimony.
It was to such he gave this great encouragement and promise; "`Lo, I am with you always,
even unto the end of the world;`" or, throughout all ages.

What that kingly prophet David earnestly prayed to God for, in Psalm fifty-one,
doth truly set forth the state and condition of true gospel ministers,
whose ministry is attended with his power and presence,
and thereby made effectual for the conversion of sinners unto him.
"`Wash me thoroughly from mine iniquity, and cleanse me from my sin.
Create in me a clean heart, O God; and renew a right spirit within me.
Cast me not away from thy presence; and take not thy holy Spirit from me.
Restore unto me the joy of thy salvation; and uphold me with thy free Spirit.
Then will I teach transgressors thy ways; and sinners shall be converted unto thee.`"
These things have I sincerely aimed at, and earnestly desired of the Lord;
and inwardly in spirit travelled for, with my soul and whole heart.
And the Lord in measure answered me therein,
before I travelled abroad in the ministry of the gospel of Christ,
even the gospel of the grace of God;
which gradually he gave and increased from small beginnings in me, and unto me,
blessed be his most excellent name forever: for he promised unto his people, saying;
"`I will give you pastors according to my own heart,
which shall feed you with knowledge and understanding.`"
They are only true pastors and ministers who are of his giving;
and many such he has given, and will give in this gospel-day,
according as was testified by a preacher, both of Christ as come in the flesh,
and of the mystery of Christ as come in spirit.
"`Even the mystery which hath been hid from ages and generations,
but now is made manifest to his saints,
to whom God would make known what is the riches of
the glory of this mystery among the Gentiles,
which is Christ in you, the hope of glory, whom we preach, warning every man,
and teaching every man in all wisdom,
that we may present every man perfect in Christ Jesus; whereunto I also labour,
striving according to his working, which worketh in me mightily.`"

According to a real belief and persuasion that God
would reveal this mystery of Christ in us,
I was made tenderly concerned to wait for the same, that I might experience,
witness and feel the power and coming of Christ inwardly in spirit,
both to sanctify my heart, and give me understanding to do his will.
And when he called me to bear testimony for his name and power,
and also for his inward and spiritual work in man,
I was engaged in spirit to wait for his power and spirit to move and work in me;
and that I might labour in his service according to his working in me thereby,
and not otherwise to run or to strive in my own will, wisdom or strength,
as knowing that without Christ, his power and presence, help and counsel,
I could of myself do nothing, nor any one else.
And when my ability was but small, and I was in much weakness,
fear and trembling many times, the Lord helped me,
and increased strength and ability in my labours beyond expectation;
this care still resting upon me, even in my early travels,
to minister only according to the ability and gift given to me of my heavenly Father,
so to keep within compass of my own gift and ability;
and when the Spirit of the Lord opened and moved but in a few words, 1 must not exceed,
but sit down in silence when that ceased.
Many times in waiting upon the Lord, and secretly breathing to him in silence,
the spring of life would arise,
and open counsel afresh to my own and other souls`' refreshment and consolation.
Often hath my soul been brought low, and the Lord helped me, and renewed my strength,
to persevere in his service; being sensible the more low I was in myself,
and the more in fear toward God, though but weak and simple of myself,
the more he would manifest his power, and bless my endeavours and service.
Let Him have the praise of all, who is forever worthy.

After many blessed and comfortable seasons and refreshments
from the presence of our heavenly Father,
which we enjoyed in our meetings in the northern parts;
and having cleared my conscience in testimony for the Truth,
both in word and Christian conversation toward my parents and relations,
being some time with them before,
I travelled abroad into the south parts of England,--a weighty concern
came upon me to leave my father`'s house and county of Westmoreland,
and to travel abroad southward.
I acquainted some Friends with my prospect, and my dear friend Edward Edwards,
who then was a young man, and lived at Gervase Benson`'s, near Coatley Cragg,
above Sedbergh, though he was not then called into the ministry,
gave up to travel with me, and to keep me company to York, above sixty miles,
it being after harvest, in the year 1654.
Both of us were given up to travel on foot, and went together directly to York,
where we stayed two or three nights, and were at Friends`' meeting there on first-day,
which was but small, and I had a few words given me livingly to declare among them.

Thence we travelled southward in Yorkshire,
and met with our beloved friend and brother in Christ, George Fox,
at one captain Bradford`'s, where we were at a meeting with him in an evening;
and afterward we travelled into East Holderness, to Joseph Storr`'s,
where again we met with George Fox, and divers other Friends,
and were comforted together,
and travelled a little while in that country to some meetings where he was,
who then had the public service wholly upon him there,
for the strengthening and settling Friends in the Light and in the Truth.

I had some testimony laid upon me to bear at two steeple houses,
before I left that county, but met with no hard usage, except haling out;
the Lord supporting me in faith and hope for the service he had for me further south.
My honest, dear friend, Edward Edwards and I parted in Holderness, and Thomas Ralison,
who travelled with George Fox, came with me to Hull,
whence we went that night over the river Humber in their boat,
being about four miles over, into Lincolnshire; we had a rude, abusive,
drunken company in the boat, who threatened, and otherwise abused us,
but the Lord preserved us from being harmed by them.

George Fox and Alexander Parker overtook us, being on foot, in our way toward Lincoln,
and we got to a place at night, where was a meeting next day, being first-day;
and a burden came then upon me,
to go and bear testimony for the Truth at two steeple houses, one in the forenoon,
and the other in the afternoon.
I had no harm or violence at either, except pulling or pushing out.
But Thomas Ralison being at that in the afternoon, was abused and beaten,
and followed into the field by a parcel of young fellows;
and I was sorry that he was so evilly treated.
Next day he and I parted, and I took leave of George Fox and Friends with him,
and travelled on toward Lincoln, taking a meeting by the way,
where the Lord opened my mouth in a living testimony.
After which, I went to Lincoln that night, being but a few miles off,
and there met with John Whitehead, who had been exercised in public service in that city,
and had met with some acceptance there, and gave some account thereof.
I stayed but one night in Lincoln,
being pressed in spirit to travel forward toward Cambridge and Norwich,
though left to travel alone, and still on foot.
I went to Cambridge from Lincoln in less than three days, the days being then short,
though my feet were pretty much galled and blistered,
even before I came out of Yorkshire; yet they amended while I travelled,
before I got to Norwich, and I was preserved in health all along;
which I thankfully esteemed as a great mercy from God,
being then not eighteen years of age.

At Cambridge I was received kindly by alderman Blakeling and his wife,
and by the few Friends there.
James Parnel met me before I went thence, and we were comforted together,
and among those Friends when we met.
After two or three days stay there, I was still pressed in spirit for Norwich;
from Cambridge Thomas Lightfoot travelled with me toward Norwich;
we got within about three miles of Thetford in Norfolk the first night,
the weather being wet and showery.
It was something difficult to get lodging for our
money at a little village where we stayed,
they were so shy or timorous of us; yet being at a house where they sold beer,
we prevailed with them to entertain us that night,
but the room wherein we lodged was but cold and mean, and the window so shattered,
that the snow came in upon us.
The next day we travelled to Wymondham, or Windham,
which is about six miles from Norwich,
where one Robert Constable and his wife kindly received us,
being convinced a little time before, by our dear friend Richard Hubberthorn,
then prisoner in Norwich castle,
for bearing public testimony to Truth at the steeple house at Windham,
where those called Independents met, and one John Money was their preacher.

From Windham we went to Norwich next day, and I visited Richard Hubberthorn in prison,
where we gladly embraced each other in dear and tender love,
and were comforted together in the Lord;
there being then a few Friends in that city convinced by his testimony and suffering,
who coming to visit him in prison, were affected to Truth and Friends.
The most noted, serviceable Friend then in that city, was Thomas Symonds,
a master-weaver, who received travelling Friends; he was a loving, honest man,
and came to receive a gift in the ministry, and was faithful unto death.
He lived and died in the faith, and was partaker of the promises,
which are yea and amen in Christ Jesus.
He was exemplary in the Truth,
and serviceable both in the city of Norwich and county of Norfolk, where he lived.

Though I expected to suffer imprisonment in that city, yet as the Lord so ordered,
I had liberty some weeks to have divers meetings at Thomas Symonds`' house in Norwich,
and at Windham, at Robert Harvey`'s, a glover, who was an honest, innocent man,
that received the Truth in the love of it.
To a meeting at his house, came captain John Lawrence,
who being then tenderly affected with Truth,
was desirous I should have a meeting at his house at Wramplingham,
which I was very willing and glad to have.

To that meeting came three priests, Jonathan Clapham, priest of the town,
and two others to oppose; they stayed in the parlour until the meeting was settled,
and first they peeped out to see me esteeming me but a boy; and because of my youth,
I was somewhat contemptible in their eyes to discourse with;
and I understood they slighted me the more because thereof.
However, Jonathan Clapham would undertake to oppose and interrogate me,
about our not respecting persons by bowing, etc., as one ambitious,
and more regarding worldly honour, and respecting persons,
than seeking the honour which is from above.
He pleaded what he could for it, and the Lord gave me suitable and scriptural answers,
which in the spirit of meekness I returned upon him and his party,
and laid open some of their unscriptural and unwarrantable practices;
and feeling the Lord`'s power and counsel with me,
I had dominion given me to vindicate the Truth, to the confounding the opposers.
After a short time, Jonathan Clapham, and another priest--one Purt--withdrew,
but the third stayed until the meeting was over;
for after the contest with the other two priests was ended,
I had a very good and blessed opportunity to declare the Truth,
and open divers matters of weight, as the Lord was pleased to open them to me,
and enlarge my spirit to demonstrate them, insomuch that at the same meeting,
most of John Lawrence`'s family, with several others,
were convinced and persuaded of the way of Truth.
The Lord gave me great comfort and encouragement,
by his divine assistance in his work and service that day;
and Friends present were greatly satisfied:
and the priests`' contempt of me his poor servant and weak instrument,
turned to the contempt and disgrace of themselves; so that I had then,
and have often had cause to ascribe the glory and praise to the Lord our God,
and to declare that,
"`Out of the mouth of babes and sucklings hast thou ordained strength,
because of thine enemies,
that thou mightest still the enemy and the avenger;`" though
at these things the chief priests be sore displeased.

John Lawrence received the Truth,
and me and others of the Lord`'s messengers in great love and tenderness,
and gave up freely in obedience thereunto.
When he knew a beginning in the Spirit, he turned not back, but persevered,
and bore a faithful testimony in suffering for the truth, both in his person and goods.
He and his family turning to truth and Friends, was a means to draw many after them,
from the mercenary priests, to Christ, his light and free ministry,
that they might know him to be their minister, their High priest, their Shepherd,
and the bishop of their souls.

Near that time, in the ninth and tenth months, 1654,
I had divers meetings in and near Wymondham, and in Norwich.
The Lord was with me, and helped me to publish his name and truth;
to preach the everlasting gospel, and to turn many from darkness to the light,
and from the power of sin and Satan, unto God and his power;
that people might not continue in empty forms and shadows,
but come to the life and substance of true religion, and to the power of godliness,
and to know Christ to be their teacher and leader, whose voice his sheep hear,
and will not follow the voice of a stranger.
Many in those parts were convinced of the truth of these things,
and turned to the light of Christ in them.
Let the work of the Lord praise him, which began in those days,
and has prospered since in that country,
both in the offspring of many who then at first received the love of the truth,
and in many others,
whom the Lord hath blessed in their obedience and willingness to serve him;
being come unto the dawning of the day of Christ`'s power,
wherein his people are a willing people.

The first opposition I met with at a meeting in the city of Norwich,
was at Thomas Symonds`' house, by an Antinomian preacher,
who pleaded for sin to continue, even in the best of saints, through life,
from Paul`'s warfare, etc., Rom.
vii.; and that though they still continue sinners, they are not under the law,
but under grace, and reckoned righteous in Christ.
Much such sin pleasing doctrine we met with from professors in those days,
whom in the name of the Lord we withstood, as 1 did the said Antinomian;
and by the Lord`'s help, stood over him and his perverse gainsayings, to his confusion.
I saw those Antinomians were very dark and corrupt in doctrine,
contrary to Christ`'s work, which is to destroy sin,
and to save his people from sin and transgression.

At that meeting there were some persons deemed Ranters, allowing corrupt liberty.
One of the chief of them seemed to own what I said against the Antinomian;
I had then given me a sense that he was of a corrupt spirit, and told him,
I denied his spirit also, as I did the opposer`'s,
for I felt a zeal from the Lord against them both.
The Lord`'s power was over all,
in whose service he encouraged me from one meeting to another,
insomuch that I was sure the Lord stood by me,
and strengthened my spirit in his work and service;
and the more I travelled and laboured therein, the more my strength in him increased;
for which my soul did often praise his glorious name,
and sing praises to him even in solitary places.

A little time after I had another meeting at Thomas Symonds`' house in Norwich,
on a first-day of the week,
and a company of those persons came who were in the spirit of ranterism;
also the same person who seemed to take my part against the Antinomian opposer.

The power and dread of the Lord God,
fell so weightily upon me to bear testimony against sin and wickedness,
root and branch--against the lust of the flesh, the lust of the eye, the pride of life,
and the love of the world,
that the powerful word of the Lord pierced through the meeting,
and so wonderfully struck down the spirits of those ranters, and other loose spirits,
that they came to me that evening like men greatly wounded and
brought down from their high floating notions of ranterism,
so that they questioned their salvation, which before they thought themselves secure of,
as if their mountain could never be removed; yet now they were under doubts and fears,
and such questioning as.
Men and brethren, what shall we do to be saved?
In compassion to their poor souls,
I earnestly exhorted them to bear the judgment of the Lord, and his indignation,
because they had greatly sinned against him,
that they might find mercy from him through true humiliation and repentance;
with more such like necessary counsel and warning,
as the Lord by his light then showed me was most suitable to their conditions.
I never was acquainted with that sort of people before those in Norwich;
the most of them were convinced of the truth,
and divers of them became reformed in their lives and conversations;
though some turned back into their corrupt carnal liberty, through carelessness,
and want of watchfulness, not keeping in the fear of God.

We have seen in our day, that where the deadly wound in the beast, or beastly nature,
hath been healed, in those who have not gone forward through mortification,
nor patiently waited to see judgment brought forth into victory, they have miscarried,
and turned from the grace of God into lasciviousness, or to embrace the world,
and thereby to sell the truth, and themselves too, even their poor souls,
for their own iniquities.
"`Behold, for your iniquities have you sold yourselves.`"

Some time after the aforementioned meeting at John Lawrence`'s,
I went to visit him and his family and relations that were with them.
His wife, and her sister-in-law, Elizabeth Bedwell,
and others of the family being convinced, were truly loving to Friends,
as were their children.
They were glad of the good service I had at that meeting,
where the three priests were so greatly disappointed
of their designed conquest and so much confounded.
Elizabeth Bedwell told me,
that the wife of the priest of the town and she having discourse before the meeting,
and expecting some dispute between the priests and the Quaker,
the priest`'s wife asked her, saying "`Mrs.
Bedwell, which side will you be for`'.`'`" Elizabeth pleasantly answered her,
"`I`'ll be for the strongest side.`"
After the meeting was over, the priest`'s wife told Elizabeth, "`Now Mrs.
Bedwell, I know you`'ll be of the Quaker`'s side, or for the Quakers,
for you said you would be for the strongest side.`"

John Lawrence would often tell of that meeting with great pleasure,
remembering the service thereof to the truth,
and the disappointment the three priests met with, and how poorly they came off.

Elizabeth Bedwell, who would be for the strongest side, continued a faithful, innocent,
loving Friend in the truth, and an example of humility until death;
and her husband a loving man, and friend to truth and Friends,
especially in his latter years.
It is worthy to be remembered, that both John Lawrence`'s own mother,
and his wife`'s mother, who were very ancient women, came to be convinced,
and received the truth in those times,
and continued Friends in their old age to the last.

Also Joseph Lawrence, who was brother to John Lawrence, and his wife,
received the truth and Friends in true love, and became very serviceable.
Joseph suffered considerably for the truth, by imprisonments before he died.
His wife lived not many years after she received the truth,
but in her day was a very virtuous, sober, ingenuous, and loving Friend;
and by her sober life and good example, left a sweet savour behind her.

Our ancient and faithful friend, William Barber, of Gissing, in the county of Norfolk,
and his wife, early received the truth and Friends in great love and tenderness, in 1654.
I first met him at Diss, in Norfolk,
and declared the truth to him and some others present,
and opened something of the mystery of Christ,
and of the ministry and work of his spirit within,
and also of the enemy`'s contrary work in man,
as the Lord was pleased to open and enable me.
William was very tenderly affected, and broken into tears, and his spirit humbled,
though he had been a great man and captain in the army; truth was near him,
and I felt him near it, and my heart was open and tender toward him,
in the love of Christ.

It was some time after before I saw his wife; she was an honest, sober woman,
received the truth and Friends in great love and tenderness; and continued a faithful,
innocent and loving Friend until her dying day.
I observed the Lord endued her with much patience,
considering the great and long suffering her husband
endured by imprisonment in Norwich Castle,
for the space of twenty years, or more,
chiefly for non-payment of tithes to an old priest of the parish,
who appeared implacably malicious in his prosecution, or rather persecution and revenge.
William Barber bore a faithful testimony through patience and long suffering;
I know of none who suffered like him in those parts,
though many Friends thereabouts have suffered deeply on the same account,
and the Lord supported them therein.

After I had laboured and travelled some weeks in that county,
in the work of the Lord and his gospel, in the winter of 1654,
a weighty concern came upon me to travel into the county of Suffolk,
and first into some part of High Suffolk.
As we went, Robert Constable, the Friend who went with me,
procured an evening meeting at a town called Budsdale,
where the people were pretty civil and quiet.
The next day we went to Mendlesham in Suffolk, to Robert Duncan`'s,
of whom I had a good account before,
and of his being desirous of some Friends to visit them in those parts;
for a meeting of an honest-minded people had been some time kept at his house,
dissenting from the parish priests and their worship; and yet they had several preachers,
or such as esteemed themselves spiritually gifted, in some degree,
to preach and pray among them.

When I came to Robert`'s house, he kindly received me;
next day being the first-day of the week, was their meeting at his house,
into which I went, and sat in silence for some space,
waiting upon the Lord in his holy fear,
to see and feel what he would please by his power
to open unto me to declare to the people there met,
waiting to hear what should be delivered unto them.
Some of their teachers seemed a little uneasy with
our being silent so long as we then were;
whereupon Robert Duncan spake a few words to this purpose,
that peradventure they had been too much in words, or depending on men`'s teaching;
and therefore God now might see it meet to bring them into silence,
that they might come more to depend upon him for teaching.

Some of their preachers were for putting forward one or other of them to prayer;
I let them alone, and patiently bore them in their voluntary devotion.
After a little respite,
the Lord opened and made way for me to preach the truth unto them,
to turn their minds to the true light, that they might know the immortal seed and birth,
which is from above, unto which God`'s everlasting love is;
and that seed and birth which he hates, subdued, crucified and slain.
It was to the inward work of his Spirit, and to the knowledge of Christ in spirit,
and that they might know God`'s teaching by his Spirit,
that I truly desired they might all come.

I was among them really in much humility, meekness and poverty of spirit,
wherein the Lord was with me, and by his invisible power helped me,
for his own name`'s sake, yea, and his seed`'s sake; which I felt among that people.
The Lord had a tender seed and people among them,
towards whom my soul was truly affected,
in the love and bowels of Christ Jesus my Lord and leader,
who went before me in his gospel work and service; to him be the glory thereof forever.

The meeting was kept and ended in much sobriety and seriousness,
and no opposition made therein to what the Lord gave me to declare among them;
they being for the most part well inclined,
and convinced of the truth then testified unto.
And the meeting remained, and was held in that place,
being so well satisfied with the truth and dispensation of the spirit,
as professed and owned among the people called Quakers,
that the friends thereof were content to wait upon the Lord together in silence,
to know and receive life, power and teaching also from him.
And the Lord for many years prospered them,
although when that meeting was reduced to know a state of silence,
some of their former preachers left it for a time; yet afterward returned,
especially one that was most noted, namely Edward Plumsted, senior,
who not only came to be a loving Friend in our Society, as his wife and family were,
but also a preacher of the truth among Friends, some years before he died.

After my first going to Robert Duncan`'s, his wife, who was a weakly woman in body,
and kept her chamber, as she had done for some time, was convinced,
and received the truth, and me also in much love and tenderness.
By the Lord`'s power she was restored to her health and strength,
so that she could walk many miles on foot, and continued an innocent,
loving and faithful Friend until death.

Robert himself was greatly instrumental in the hand of the Lord in his day,
in the support and encouragement of that meeting at his house,
as well as by his great love to Friends, in receiving and entertaining them frequently.
He was such an overseer as was truly given to hospitality`',
and the Lord blessed him both inwardly and outwardly.

After that meeting I was again concerned in spirit to return (o Norwich and that way,
where I had before some effectual service in and for the blessed truth,
among the Friends convinced thereof, and other well inclined people;
also to visit my beloved friend and brother, Richard Hubberthorn, as often as I could,
he being still detained prisoner in Norwich Castle,
where he had but a poor hole to lodge in, upon the end of a cross wall;
which being a little old stone arched hole or room, it broke,
and fell down not many years after.
It was the Lord`'s mercy it fell not while Richard Hubberthorn was in it.
My dear friend, Thomas Symonds, brother-in-law to Robert Duncan,
who had a great love to him and desire for his good,
was at the meeting at his brother Robert Duncan`'s house,
and I returned with him to Norwich.

A few days after, it being near the end of the tenth month, 1654,
there was a lecture at that called Peter`'s church in Norwich,
and I believed the Lord required me to go thither,
to bear such testimony as he would please to give me,
being endued with a holy zeal against iniquity,
and the pride and covetousness even of the high priests in those days,
as well as with compassion to the ignorance and blindness of the people misled by them.

When the priest, one Boatman, had ended sermon, I was suffered to say but very little,
i+++.+++ e. a few words against iniquity, etc., when some of the priest`'s hearers,
came violently upon me to hale me out, some pulling by one arm, and some by the other,
contrariwise; some striving to hale me out at the north door,
and some out at the south porch.
By their violence I got some hurt and inward pain in one side of my breast,
being overstrained by their pulling and haling me contrariwise;
but it pleased the Lord in a few days to remove the
hurt and pain I got by their hard usage.
From the steeple-house I was haled to Guild-hall, before Thomas Toft, mayor,
who after examination about water baptism, and some other things,
committed me to the city jail.

The mayor seemed to seek occasion against me because he had none,
by questioning me about water baptism: asking me, if the baptism of John was from heaven,
or of men?
To which I answered him, if they who now plead for water baptism could prove,
or make it appear that they have commission from heaven to baptize, as John had,
I would own it.
But I supposed he did not intend so, but was for sprinkling infants.
However, though he could get no advantage against me, he would send me to prison.

A little while before I was committed, James Lancaster,
and Christopher Atkinson were committed to the same prison,
though they came some time after me to Norwich;
James was committed for calling people to repentance in the market at Norwich,
he being an ancient faithful Friend, who preached the mighty day of the Lord,
to excite people to repentance in divers places as he travelled into those parts.
But Christopher Atkinson,
though he was kept orderly in his conversation while
James and I remained in that prison with him,
yet after we were released, and he left alone,
he turned loose and scandalous in his conversation,
to the great reproach of our holy profession, among them who desired occasion against us,
and the truth professed by us.

In the prison at Norwich, we were hardly treated by the keeper, one Hunt,
who demanded for one bed for three of us, four pence a night of each;
we thought it was hard measure to demand twelve pence
a night of prisoners for one mean bed,
for three men to be crowded together in, and that in a cold room,
where another prisoner lodged in a bed to himself.
Not finding freedom to gratify the jailor in his oppression and covetousness,
and afraid to bring any charge upon any of our Friends,
to procure us better accommodation in prison,
we thought ourselves necessitated to lodge upon the bare boards on the floor,
in our wearing cloths and little covering besides;
and thus we lodged for eight weeks together in the cold winter,
and though we endured much cold,
yet were through the Lord`'s mercy generally preserved in health.
Such hardship I might think the greater to me,
having been tenderly brought up by my parents, and then so young,
as but about eighteen years old that same winter.
Whilst we were prisoners, our dear friend Thomas Symonds was sent to prison to us,
only for asking a priest a question in the steeple-house after sermon.

At the next sessions for the city, James Lancaster and I were had into court,
before Charles George Cock, then judge; and the great offence he took against us,
was not putting off our hats in court, which we could not for conscience sake submit to,
nor do such homage to mortal man.
This he seemed somewhat highly to resent, as a contempt to the court and to authority,
pleading for respect to superiors, as the duty of servants to masters.
I signified that servants ought to perform their duties, and to serve their own masters,
not with eye-service as men pleasers, but in singleness of heart;
whereas putting off the hat, and bowing to men, and thereby respecting their persons,
is but an eye-service, and men pleasing,
and no real service or duty to superiors or government;
neither do we know any law broken by wearing our hats,
any more than by wearing the rest of our garments,
nor do we thereby intend any contempt against authority.
After a few words of this import,
I bore the judge`'s threatening and insulting patiently, and stood still in silence.

John Bolton of London, being behind me in court, suddenly plucked off my hat,
with the other Friend`'s, supposing thereby to pacify the judge,
and prevent our further suffering,
he with another Friend or two being come from London to visit us;
howbeit we were remanded back to prison, our cold place of confinement.
Suddenly after, on the same day,
our friend John Bolton was sorely troubled in his conscience for plucking off our hats,
and could not rest quiet in himself until he returned into court again,
and made open confession against himself,
condemning what he had done in taking off our hats.
Upon which, as it was related to me, the judge signified, he thought what John had done,
would not hold with the Quakers`' principle.
Note, the greater injury then it was in him, to urge or impose that practice on us,
when he was sensible it was contrary to our principle,
and consequently against our consciences.

John Bolton was sincere and conscientious in his public acknowledgment against himself,
for what he so suddenly did to pacify the judge;
though John had not been long a professed Quaker;
yet he continued zealous for truth unto his end.

It may be observed, that the judge of the said court of sessions in Norwich,
was tenderly cautioned beforehand by letter from us who were prisoners,
against that very course which he took against us in session.

As he was esteemed one expert in the law,
he might know the law was made against transgressors,
and for the encouragement of them that do well; that it was not made to ensnare any man,
nor call him an offender for words,
or for declaring the mind of the Lord as revealed in obedience to him, either in cities,
or other places.
And they that revile and persecute his servants for the same,
are transgressors of the law of God, which is righteous and equal,
and which we desire may be established and practised.
Such magistrates as act accordingly in righteousness, are by us honoured and obeyed,
though not as the world doth, only to the eye or outward appearance,
but in deed and in truth, as in the sight of God.

For our parts, we are cast into bonds by the will of man,
without the manifest breach of any law laid to our charge.
Such magistrates as pretend justice and the law to be their rule, and act contrary,
the Lord never ordained to execute his law;
but such as are just in what he called them unto.

Seeing we were in bonds without the breach of any just law laid to our charge,
we requested we might be brought before the said judge in court,
with our accusers face to face, that we might see what they had to charge against us.

And further in the said letter it is said, we are accused for contemning magistrates.
This accusation is utterly denied as a falsehood; for magistrates,
who do justly according to the law of God, we own and honour as his ministers;
but such as will not do justice, unless they may have the bending of the knee,
or the hat put off, which are not given them of God to require,
nor is it a contempt of magistracy to refuse them,
unless the law of God required the same; but we know not of any such.

I have abstracted the substance of the letter,
only these words to the judge or recorder of Norwich, are near the conclusion thereof,
viz.

"`Thus, Friend, as thou art a judge of the law, mind the Lord in thy place,
that thou may exercise judgment between man and man in righteousness.`"

We could have wished this letter might have taken some effect on the judge,
but the Lord required us to clear our consciences therein,
to whom we committed our cause,
as believing it was our place to give such timely warning; however,
James Lancaster and I were discharged at the said sessions by the judge,
yet for some time after detained in prison by Hunt the jailor,
pretending he had laid actions upon us for what he claimed as a debt owing for lodging;
upon which we were detained, under the same hardships in the cold winter,
in all eight weeks or above, until the jailor died.
And then we were freed out of prison,
so that the Lord delivered us by removing our unmerciful oppressor.

[.embedded-content-document.letter]
--

[.blurb]
=== An answer to a Proclamation which came forth soon after our commitment to prison in Norwich, whereby our then persecutors were the more lifted up against us. The title of the said answer was, viz: The Truth proclaimed, and the Innocent cleared from false informations. The preamble being since added thereto.

Many false informations being then gathered up in several parts of the nation,
against a harmless, innocent people, by scorners termed Quakers,
and they then persecuted by false accusations and slanders,
designed to bring them under great suffering, which many of us underwent in those days,
notwithstanding the fair pretensions and promises of liberty of conscience,
made by some of the chief persons in that government,
pretending to be for a commonwealth, as partly appears in the said proclamation,
gave us occasion to write in behalf of the said people,
as being clear and innocent in the presence of the Lord, and before all men,
from those aspersions then cast upon them.
But surely,
those severe persecutions and imprisonments which were even under that government,
contradicted those fair pretensions and promises of liberty of conscience;
and as contradictory and injurious, and tending to persecution was it,
for any in that government to join the Quakers with the Ranters,
and that upon information too, as appeared in the said proclamation; some whereof,
with the substance of our answer, are recited as folioweth, viz:

That a free and uninterrupted liberty is granted to every man to
exercise and practice the grace dispensed to him from God;
and that every one by the powers is to be protected in their just liberty,
to dispense according to the measure of light and knowledge they have received from God,
without interruption; and to have all just and due encouragement and protection therein;
this liberty and mercy being purchased by the price of much blood.
And therefore freedom and liberty to all persons in this commonwealth fearing God,
is to be protected, answerable to the mercies received,
being delivered and set free from the outward enemies of this commonwealth.

[.offset]
And the things proclaimed against, are, viz.

Imposing upon the consciences of their brethren, offering violence to their persons,
or any otherwise seeking to hinder their liberty therein;
and to be kept within the bounds of the royal law of love.
But they who openly and avowedly, by rude and unchristian practices,
disturb both public and private Christian meetings,
in their religious exercises in the worship of God, whereby the liberty of the gospel,
the profession of religion, and the name of God is much dishonoured and abused.
And many informations being given forth of such practices,
by those under the names of Quakers and Ranters, and such practices are disliked in all,
and proclaimed against,
which be contrary to the just liberty and freedom which
the people of this commonwealth are to be protected in, etc.

[.numbered-group]
====

[.numbered]
_Answer 1._ The power which from God immediately is received,
brings into the true liberty and freedom as pertaining to conscience;
and the pure law of God, which came from the same power,
takes hold upon that which oppresseth the good seed and conscience also.

[.numbered]
2+++.+++ Laws made in the will of man, and man by his own power and will ruling,
do keep in bondage.

[.numbered]
3+++.+++ And though liberty of conscience and liberty of godliness,
have been long pretended and promised,
yet the same is not yet performed nor fulfilled to
those who have been free to lay down their lives,
i+++.+++ e. for this liberty of conscience promised and professed.
Now when the Lord enlightened us by his true light,
and brought us to walk with a pure conscience toward God and man, we find more tyranny,
cruelty, and plotting mischief against us,
than ever those accounted enemies of the commonwealth invented to take away our lives;
though no man can lay any evil to our charge, done or acted, or law broken by us.

[.numbered]
4+++.+++ But for declaring the truth freely, as it is made manifest in us, from the Lord,
against all deceit and unrighteousness of men,
we are shut up and kept close in holes and prisons, among thieves and murderers.
This is the reward and liberty we receive from the world,
for declaring to them in love to their souls,
the eternal truth of God who hath called us,
whom we cannot deny for the world`'s advantage.

[.numbered]
5+++.+++ For witnessing forth in life and power that, which protection is promised to,
many now suffer in England, and have not their just liberty in the exercise of godliness,
though not found guilty of any of those unchristian practices proclaimed against.

[.numbered]
6+++.+++ The people called Quakers do not impose upon the consciences of their brethren,
or any others,
any thing which may embondage their just liberty or freedom in the things of God,
but do desire that liberty;
that all bondage and ties may be taken off the consciences
of all people in matters of the worship of God;
and for the purchasing of this liberty, do we suffer bonds and imprisonments, beatings,
stonings, stocking, and other cruel usage, from those who profess themselves Christians,
magistrates and rulers in this commonwealth, as it is termed:
and these things we suffer without resistance,
waiting for that liberty from the Lord to be freed from their bonds,
who impose upon us things contrary to the light of Christ in the conscience.

[.numbered]
7+++.+++ As to offering violence to any man`'s person, that is far from us,
for Cain`'s nature in us is crucified, from which all murder,
enmity and violence proceed, and from that we are clear before the Lord;
our consciences also bearing us witness,
how free we are from doing any violence to any man`'s person;
but by violence we suffer imprisonment, without the breach of any law proved against us;
so that the liberty proclaimed, is denied us by our persecutors.

[.numbered]
8+++.+++ The royal law of love we sincerely own, and its bounds we do not pass;
and we do love our enemies, who despitefully use us;
and this against them shall bear witness,
when in the sight of God we shall be cleared and justified,
from all slanderous and lying informations formed against us,
and from all bitterness of spirit, rude and unchristian practices,
as biting and devouring one another, hateful and hating one another;
all such practices we testify against, from the spirit of the living God.
And to the light of Christ Jesus in men`'s consciences are we made manifest,
desiring that their minds by it may be guided up unto God, out of all malice, envy,
deceit, debate, malignity, whisperings, backbitings;
and from all false informations and slanders, which wicked and ungodly men cast upon us.

[.numbered]
9+++.+++ They who are in the pure power of God, in whom the life of God is made manifest,
though by the scorners of the world called Quakers, are no fighters nor strikers,
nor revilers, nor scorners, nor truce breakers, nor incontinent,
nor despisers of those that are good; neither biting, nor devouring, nor coveting,
nor oppressing; and all fraud and guile are put far from them,
who in the measure of the eternal Spirit do walk
up in obedience to what they have received from God;
and such are no drunkards, nor swearers, nor liars, nor whoremongers, nor idolaters,
which must never inherit the kingdom of God:
but the day of redemption in Christ Jesus we do witness, and the eternal judgment,
through which the defiled nature cannot pass,
but must be purged and washed from that which defiled;
as many others are defiled whose minds are turned
from the pure light of Christ in the conscience,
and are not come to witness the pure judgment set up in the earth,
through which redemption is witnessed by the righteous seed and generation.

[.numbered]
10+++.+++ And as touching the many informations said to be given forth of such practices,
by those under the names of Quakers and Ranters;
i+++.+++ e. of rude and unchristian practices which are disliked:

We answer, We do utterly deny the principles and practices of Ranters;
who from the light of Christ, which is pure in the conscience,
are turned into the liberty of the flesh, and into all uncleanness,
having their wills at liberty to act uncleanness,
and to practice those things to which the plagues of God are due.
The vials of the wrath of God are to be poured out
upon that filthy nature in which they live,
who have crucified the just in them,--and with the unclean nature which rules in them,
have we no unity nor fellowship: for our unity and fellowship is with them,
who in the light of Christ do walk, and keep out of uncleanness and corrupt lusts.
For neither with the priests of the world, who keep people ever learning,
led about with divers lusts, nor with the Ranters,
who take liberty to fulfill their ungodly lusts, have we unity;
but are clear and free from all such;
and separated by the eternal Spirit from them who turn the grace of God into wantonness.
But with such our unity is, who dwell in the pure power and dread of the living God,
and in his presence; where no flesh can glory, nor uncleanness stand,
but is judged and condemned by the light, which doth justify the righteous,
and condemns the wicked world.

This our answer and serious testimony considered,
how unjust and injurious was it to rank the Quakers with the Ranters,
and that in things scandalous and irreligious, and that upon informations too?
Where was any justice or equity, or judicial proceedings,
thus to compare an innocent people with the scandalous,
and thus to reproach or criminate them upon informations and evil reports.
O justice!
O equity!
O moderation!
O Christian liberty!
Where were you all in those days?
And, O commonwealth! how common, how universal wast thou!
What common weal, or what common welfare--what common good didst thou afford us,
thy peaceable, innocent subjects, and free born English people,
when under thy power and government, we were not allowed to breathe the common air?

Now I proceed with the recital of our answer aforesaid.

[.numbered]
11+++.+++ How contrary to this liberty and protection universally promised and proclaimed,
our (viz: six persons,) unjust imprisonment in the castle and city of Norwich is,
may plainly appear to all persons of understanding,
we being by the eternal Spirit of the living God, called from our earthly habitations,
freely to declare and make manifest the eternal Word of God,
and the powers of the world to come, as made manifest in us by the eternal Spirit,
coveting no man`'s silver nor gold;
but freely declaring what we have freely received from God,
in love to the souls of all people,
that they might also be partakers with us of the powerful truth of God,
that their souls might live in it and know the pure God,
whom all the world in their first state are ignorant of and enemies to.

[.numbered]
12+++.+++ One of us, viz: Richard Hubberthorn, in the Lord`'s work and service,
being moved of him to go to one place where a people were met together;
and when their public exercise was ended,
did speak among them what the Lord had made manifest unto him.
And the people being willing to hear the truth, some were convinced,
and brought to know that which they had been ignorant of.

[.numbered]
13+++.+++ But one called a justice being there, whose envy appeared against the truth,
sent our friend Richard Hubberthorn to prison,
because he would not promise him not to come there any more;
and so from that time hath he been kept in prison twenty weeks,
that was until the date hereof, and detained prisoner a considerable time after,
contrary to law, and to the liberty and protection promised and proclaimed.

====

Another, a Friend of ours, who came to the city of Norwich,
and upon the first-day of the week,
being with some Friends met together to wait upon the Lord;
as they were quietly together in his worship and service, in came the mayor of the city,
and a rude multitude with him, and fell into dispute and contention with the Friend,
disturbing their peaceable meeting; and when he could find no advantage against him,
went his way.
But the next morning he sent a man to desire the
said Friend to come to him under pretence of love;
yet when he came before him and other magistrates of the city,
he committed him to prison; without showing any law broken by the said meeting or Friend;
for it was not the quiet meeting,
but the disturbers thereof that broke the law and the peace.

Two other Friends being moved of the Lord to declare in the street
against the wickedness and ungodliness among the people,
and exhorting them to repent, for that cause they were by the mayor sent to prison.

Another, i. e. George Whitehead, having a concern upon his spirit, on a lecture day,
to go to that place improperly called St. Peter`'s church, in Norwich,
and when their public worship or exercise was ended,
beginning to speak among the people what the Lord had made manifest unto him,
was not suffered, but violently haled out, and by the mayor sent to prison.

And another Friend, who is a citizen in Norwich,
coming into a public place termed the church, upon a lecture day,
when public exercise was ended,
and asking the priest a question concerning what he had been declaring amongst them,
he was violently pulled out;
and because he had not freedom to put off his hat in the time of the priest`'s prayer,
was by the mayor committed to prison until the next sessions,
and from that sessions he was bound over to the next.

Thus people may see what liberty those that fear the Lord have,
under this professed commonwealth, when such who for tenderness of conscience toward God,
cannot respect persons, nor bow to the proud will of man, are imprisoned,
and some indicted,
because at the illegal command of proud men they cannot put off their hats,
though otherwise they walk in all good conversation toward God and man.

Now it is manifest that the said people called Quakers, and we the sufferers,
are not justly charged with those crimes or offences;
but the informers are guilty of great injustice and injury against the innocent,
who are clear in the presence of the living God, and by his Spirit.
So that shame and confusion of face may fall upon our adversaries and persecutors,
who cannot clear themselves from being guilty of the blood of the innocent.
To the light in their consciences we speak; that is, we appeal against them,
who are found enemies to the truth, and fighters against God.

Given forth for the clearing and informing of all simple and tender hearts,
in the pure truth of God, that they stumble not because of reproaches,
which do always accompany the truth wherever it is made manifest,
to the torment of its persecutors, who speak all manner of evil against us falsely,
for the truth`'s sake; but this is our rejoicing,
even the testimony of a good conscience, which all our persecutors cannot cause,
or force us to deny.
But all their tyranny or cruelty against us, and Him that sent us,
for whose name`'s sake we suffer, doth add to our crown of rejoicing,
being made partakers of his sufferings, who suffered the contradiction of sinners;
the same Christ as ever was, is now witnessed in suffering and in joy,
of whom we are witnesses, who are now sufferers for the testimony of Jesus:

[.signed-section-signature]
Richard Hubberthorn, George Whitehead, James Lancaster, etc.

[.signed-section-context-close]
Prisoners of the Lord in Norwich.

[.signed-section-context-close]
From the castle and jail of Norwich, the 24th day of the Twelfth month, 1654.

--

Besides our hard usage, and the severity of our confinement,
to add affliction to our bonds, one Sampson Townsend, by trade a weaver,
who had taken upon him the habit and place of a priest in Austin`'s parish in Norwich,
to make himself famous, published a pamphlet to defame us,
after we were committed to prison, as being in Norwich jail for errors and miscarriages,
as deniers of the Word of God, and the Scriptures, etc.,
for which his envy and falsehood were publicly detected.
And as he appeared malicious and of a persecuting spirit,
endeavouring to incense the magistrates and people against us,
by defaming and reproaching us, thereby making himself infamous;
so he appeared as ignorant and shallow in disputing against us,
at sundry meetings afterward, both in Norwich at Joseph Whitlock`'s,
and at Repham in Norfolk, where I detected and laid him open,
about his pleading for sprinkling infants as Christ`'s baptism.
After Townsend removed to Repham, I having a meeting in that town, he came to oppose me,
but made little work of it; for he was manifestly confounded,
not acknowledging the Word to be before the Scriptures,
but asserting them to be the only Word of God, or the only Word,
which was his old objection against us when in Norwich prison,
for our testimony to Christ being the Word, which was in the beginning.
At that meeting I told him, the word of the Lord came to the prophet, saying, etc.,
and these are the words of Jeremiah to whom the word of the Lord came.
By these, the word which came to the prophets,
and the sayings or words that came from the Word, are distinguished.
For to say the word of the Lord that came to the prophet saying,
is not all one as to say the Scriptures came to the prophet saying,
or that the Scriptures came so often unto him, and uttered those speeches,
sayings and prophecies, which the living Word did,
and which were not written in the Scriptures before the Word said them to the prophet.
The holy Scriptures or Writings, are or contain the sayings or words of the eternal Word,
that is, of God and Christ, as given and revealed unto his servants,
his prophets and ministers; holy men of God spake as they were moved by the Holy Ghost.
What John was commanded to write, were the true sayings of God.
But of Christ he saith, his name is called the Word of God.
And I think it is not slighting, much less contempt of holy Scriptures,
to own them either as the words or true sayings of God,
without giving them the same name or title, which more properly belongs to Christ or God.

After our discourse at the said meeting at Repham, as I was riding out of the town,
the word of the Lord came upon me, to warn the people in the street to repentance,
who for no other cause evilly entreated me, by stoning me in a furious manner;
insomuch that I could scarcely get my horse to stand,
or abide the place where I declared the truth to them,
until they became more calm and quiet.
I cleared my conscience to the people; for the Lord stood by me,
and so preserved and defended me by his power and merciful providence,
that I got very little harm by all their stoning me;
but thereby they showed what fruit their minister, my opposer,
had brought forth by his busy envious opposition against us.

And now to return to my narrative,
when James Lancaster and myself were freed out of Norwich prison,
which was in the first month called March, 1654-5, the jailor being removed by death,
and his wife more tender than he was:
I believed the special hand of the Lord was in our deliverance,
and I was very thankful to him that we were so well freed,
but we left Charles Atkinson still there.
In a short time after I was released, I went to see two prisoners there,
whereupon I was apprehended, and had before Thomas Toft, mayor, and again committed,
and there detained about three weeks, without any proof, or colour of transgression,
or law against me, but only the arbitrary will and prejudice of the mayor.
However, the Lord did not suffer him or them then to detain me long,
having other work for me to do for his name and truth sake.

The reason of Charles Atkinson`'s remaining in prison after the rest,
was partly an action, or an attachment laid upon him by an attorney,
for speaking some rash or hard words to him, which he supposed were actionable;
also the priest who then used to preach to the prisoners,
took occasion to complain against him, if not to lay another action upon him,
for some words spoken, whereby the priest was affronted.
However,
Charles Atkinson was not altogether so prudent or
gentle in his conduct as he ought to have been;
and that was not all, but worse befel him after he was left alone in prison;
for though he got more liberty,
and better accommodation than we had in prison when together,
yet he falling into too much familiarity and conversation
with some inclining to a spirit of ranterism,
he grew loose, and waxed wanton against Christ, his light and truth.
And at a certain time having a little liberty granted him out of prison,
Richard Clayton and I met him at a Friend`'s house in the country,
and perceiving he had got into too much lightness and liberty,
we met with him alone in the field, and seriously admonished and cautioned him,
which he could scarcely bear, without appearing offended and in passion.
I was jealous what might befal him, or become of him,
insomuch that a stop came upon me secretly,
that I had scarcely freedom afterward to visit him in prison.
He had been overmuch affected by some weak, indiscreet persons,
and set up above his place, to his hurt, and some young men have been hurt thereby.

After some time his iniquity broke out,
which my dear brother Richard Hubberthorn gave me notice of,
I being about that time in High Suffolk and other places,
labouring in the work of the Lord.
And when R. Hubberthorn and Thomas Symonds went to Charles Atkinson`'s,
he told them there was no redemption for him.
Thus he was tempted to despair, by the enemy that had prevailed over him,
yet he gave out a severe testimony in condemnation against himself.
When I heard of his foul miscarriage, it brought deep sorrow upon me,
even to solitary mourning and tears, for truth sake, and our poor innocent Friends,
who had lately received the truth, being sensible that both would greatly suffer,
and be reproached thereby.
However, the Lord relieved me after a little while,
and laid it the more upon me to labour and travel about in those parts,
to strengthen the weak, to help and comfort the feeble,
to vindicate the blessed truth and way thereof,
and to exalt and set the same over the head of all deceit and wickedness,
and backsliders, and such as turn into the pollutions of the world,
well knowing and reminding Friends and others, that the truth is the same,
and never changes, and ought not to be blamed;
but such who turn their backs on it are condemnable, and judgment follows them.
The Lord stood by me in that service, and by his power helped and strengthened me,
to strengthen and help many others;
so that the scandal took the less effect to do hurt or mischief in those parts;
glory and dominion to our God, and the Lamb forever and ever.

After my release out of prison the second time,
I travelled in Norfolk and Suffolk to Ingworth, Lammas and those parts,
as well as Windham, Wramplingham, New Bucknam, Gissing, Dysse and Sylam.
And my dear friend and brother Richard Clayton was with me at some meetings in Norfolk,
on that side of the country near Aylesham and Lammas,
where there was an honest-minded people inquiring after the Lord and his living truth,
whose hearts he had prepared to receive the love of the truth.
And I well remember in what manner the Lord opened my heart,
and enlarged me in the gospel testimony toward those people;
it was much in testimony to the universal love and grace of God,
the light of Christ in every man, to turn their minds to it,
therein to wait to know God`'s teachings, and to come into the new covenant dispensation,
where all the Lord`'s people are taught of him, and know him,
from the least unto the greatest, and witness his law written in their hearts,
and his spirit in their inward parts, according to his blessed promises,
and this his new and everlasting covenant,
as prophesied of by the holy evangelical prophets.

In this new covenant, not only the house of Israel and Judah may have a share,
and be partakers of Christ, but all truly believing Gentiles also,
to whom Christ is given for a light and for a covenant,
and to be God`'s salvation to the ends of the earth;
for God is not only the God of the Jews, but of the Gentiles also;
and they are the true Jews and Israel who are spiritually such; Jews inward,
by the spiritual circumcision of the heart unto the Lord by his holy Spirit.

And in order to come under this new covenant dispensation and ministry,
therein to know and experience Christ to be their minister, their teacher,
their high priest and prophet, the people aforementioned,
were persuaded to cease from man, and from all their ministers and priests,
made by the will of man; and mercenary ministers, who preached for filthy lucre and gain,
making a trade of the holy Scriptures, adding their own divinations,
meanings and notions thereto, having no divine revelation,
or commission given them to preach,
much less to make a trade of the words and testimonies of the holy prophets,
Christ Jesus, or his apostles; but walking contrary to their steps and practices,
in pride and covetousness.

The Lord often laid a pressure upon me, and others of his servants,
to testify against the pride and covetousness of the priests,
and their preaching for hire, for tithes, and forced maintenance,
contrary to Christ`'s command, and his ministers`' example.
For this cause they were the more envious against us,
and in their pulpits exclaimed and made a great noise,
to incense the people and magistrates against the Quakers, so called,
even to severe persecution and imprisonments.
And the greater necessity was laid upon me, and others of the Lord`'s servants,
to testify against those proud, covetous and envious priests,
sometimes even in their public places, improperly called churches,
to undeceive the people, that they might not still be led captive,
nor incensed against truth by them.

It is still a matter to me very memorable, that by preaching livingly, the light,
the new covenant, the word nigh to people in their hearts, yea,
the gospel of the free grace and love of God in Christ to mankind,
many were really and effectually convinced and persuaded of the blessed everliving truth,
as it is in Christ Jesus, both in the counties of Norfolk, Suffolk and Essex,
where the Lord led me early to travel, and helped and prospered me in his service;
blessed and praised be his name forever.

When I was at Mendlesham meeting, at Robert Duncan`'s,
A+++.+++ D. 1655,--George Fox the younger, a Suffolk man, was effectually convinced,
and received the truth, being then lately come out of the Parliament`'s army in Scotland.

One remarkable passage I may not omit;
John Lawrence having been a member of an Independent congregation, or church in Norwich,
and because he left them, and received us and our friends, their pastor,
one Timothy Armitage and their elders, called him in question,
and were minded to excommunicate him.
The same year 1655, about spring time, he was summoned to their meeting in Norwich,
at their parish church, called George`'s of Tombland; I went with him thither,
and Edmund Bedwell, his brother-in-law, who had not then left off his sword or falchion,
which I blamed him for, thinking they would take occasion against him and us for it,
as some of them did afterward.
There was a great concourse of people, men and women met together,
with their pastor and elders, and they repeated their allegations against John Lawrence,
to this purpose: his forsaking their communion, entertaining strangers,
or dangerous persons, or holding dangerous doctrines.
I could not perceive any fact or error they could prove against him.

And in giving his reasons why he left their church, whereof he had been a member,
he answered according to the apostle Paul`'s doctrine, who exhorts,
to turn away from such men as have a form of godliness, but deny the power thereof;
such as are proud, heady, high-minded and covetous men,
though they may have a form or profession of godliness, yet denying the power thereof,
from such we are to turn away.
John Lawrence gave the same for his reason, why he turned away from them;
though they had a form or profession of godliness, yet they denied the power thereof;
and therefore he might justly turn away from them.

After which, in the fear and dread of the Lord,
I stood up to declare a few words among them, but they quickly pulled me down,
and by force held me down in the pew where we were;
and some of their proud women that were near us,
expressed their rage and envy against me in particular.
Some of their church forcibly haled and pushed me out of the steeple-house,
and exposed me to a rude multitude, who stood ready to lay violent hands on me,
and they pushed and haled me away through the streets and market place of the city,
sometimes throwing me down upon the stones, whereby I was bruised and hurt;
though the hurt I got thereby, the Lord was pleased to remove in a short time.
They followed and encompassed me, pushing me along, roaring and shouting,
until I came near to the city gate, called Giles`' gate, next to a little pasture ground;
at the upper end of which I saw a great house, where the lady Hubbard dwelt,
as I understood afterward.
Upon the sight of it, I was in a great strait, and at a stand in my mind,
the tumult being great about me, whether I should then go out of the city,
in order to go toward Wramplingham to John Lawrence`'s, which I desired,
or whether I should turn up toward the said great house,
desiring the Lord to direct me at that instant.
I considered that if I should turn out of the city into the high-way,
toward Wramplingham, I might be in danger of loosing my life in the high-way or field,
by that violent tumultuous company that were then about me,
and it would be the less taken notice of.
If I must loose my life,
it would be better to die where my testimony was to be borne within the city of Norwich,
and where my persecution was begun because thereof,
rather than lose my life more clandestinely by the tumult without the city,
or abroad in the field;
for I was given up to suffer what violence the Lord might permit them to do unto me.

On due consideration, I immediately turned up to the lady Hubbard`'s house,
the raging company continuing still about me, J)y whose noise and shouting,
the lady`'s chaplain, Dr. Collins, as he was afterward termed, and most of the family,
came out to see what was the matter, and why such a mob came before the house,
and they saw that I was the person beset and persecuted.

The chaplain understanding what I was, undertook to discourse me,
concerning the spirit which the apostles of Christ had; If I had the same spirit?
I owned that in measure I partake of the same spirit,
though I would not equal my degree of attainment to theirs.
If I had that spirit, the chaplain would have me prove it by some sign or miracle,
as the apostles did?
Or, if I could speak with tongues by a gift of the Spirit, and not by acquirement,
as by human learning.
I answered him, according to the apostle Paul`'s words in that case,
speaking of the diversities of gifts, given by one and the same spirit; as I told him,
all who had the spirit of Christ, had not all those gifts,
as that of tongues and miracles; for to one is given the word of wisdom;
to another the word of knowledge; to another faith; to another working of miracles;
to another prophecy; to another divers kinds of tongues;
to another interpretation of tongues, yet all by the same spirit,
the spirit and power of Christ.

It is evident that these gifts of tongues and miracles,
were not common to all who had the spirit of Christ in the primitive church,
but peculiar to some, as these questions import: Are all apostles?
are all prophets?
are all teachers?
are all workers of miracles?
have all the gifts of healing?
do all speak with tongues?
Implying that all the ministers and members of the
church were not so gifted in all these respects,
though they all had one and the same spirit, from whence these gifts came.
And I may have the word of wisdom, knowledge and faith, by the same spirit,
and yet not the gift of tongues and miracles.
It no ways follows that none have the spirit, but they who have those gifts.
I then clearly saw the chaplain`'s way of reasoning in this case would not hold.

When he perceived how tumultuous and rude the company about me had been against me,
he questioned why I did not quiet or quell them, or supposed I might,
if I had the same spirit or power the apostles had?
I answered him,
that the apostle Paul himself desired the church of the Thessalonians to pray for him,
that the Lord would deliver him out of the hands of unreasonable men,
for all have not faith.
He was therefore sometimes in the hands of unreasonable men, when in tumults,
and the Lord delivered him out of their hands.
While we discoursed, my persecutors stood silent, as in a ring,
and heard us on the subjects before related; our discourse held but a little while,
I suppose about half an hour.

In the mean time came a soldier or trooper, with his sword by his side,
and perceiving me to be the person persecuted and watched for by that rude company,
as I withdrew he came to me, and said he would go along with me,
and guard me to my quarters, or lodging; and laying his hand upon his sword,
commanded the mob to stand off, to make way.
So I was quietly rescued, and he went with me to my dear friend, Thomas Symonds`' house,
in the city.

I saw it was of the Lord I was put in mind to draw toward the lady Hubbard`'s,
when I was in such a strait in the tumult as before related,
and that a stranger should be at last stirred up to rescue
me out of the hands of such unreasonable men,
as had beset and abused me with violence.
I have often been thankful to God for his merciful providence in that deliverance.

The soldier who took such care to rescue me, afterward became a Friend,
and came into society with the people called Quakers,
wherein the Lord showed mercy to him; his name was Robert Turner, of Lynn, in Norfolk.
I knew not that he was the man that rescued me till twenty-five years after,
when I was again prisoner in Norwich castle, with many more Friends, in the year 1680.

In those days prisons and jails were made sanctuaries,
and places of refuge and safety to us, from the fury of the tumultuous mob,
although we met with but mean treatment and hard usage in those places of severe confinement,
many times among notorious criminals;
and although I suffered both in tumults and imprisonments, by hard usage in them,
the Lord helped and sustained me by his divine power and goodness,
so that I was not weary of his service, nor my spirit faint in suffering.
The grateful remembrance of his goodness,
and lively sense of his love to my soul in those days,
still live and remain upon my spirit; praised be our God forever and evermore.

My dear friend and brother, Richard Hubberthorn,
being somewhat longer detained prisoner at Norwich castle, than I was in the city prison,
in the year 1654-5, I had not his company at meetings,
which I had both in Norfolk and Suffolk, until after he was at liberty,
so that for some time I wanted a suitable companion to travel
with me in the work of the gospel ministry in those parts,
except as before related, Richard Clayton travelled with me in some parts of Norfolk,
and Thomas Bond for a short space, at a few meetings,
where I laboured in the Lord`'s work and service.

The Lord greatly assisted me, and gave me living encouragement and comfort,
when I was much alone, in his gospel ministry, and I was the more comforted,
enlivened and animated in spirit by his divine power and presence,
in feeling and perceiving his blessed work to prosper,
and the truth of the gospel of Christ to take effect upon the hearts and spirits of many,
both old and young, tendering them, opening their understandings,
convincing and converting them to Christ the true light, and turning many from darkness,
and the works thereof, to light, and from Satan`'s power to God,
to know his divine power to make them his dear children and people,
as many were in those early days.
And how diligent were many, in going many miles to Friends`' meetings,
both ancient and young men and women, maidens and children.
And what love, what brokenness and tenderness,
would appear in meetings in those days of their first love and espousals, wherein many,
as chaste virgins, were espoused unto Christ Jesus, in his light, life and spirit,
and wherein many of those loving and tender Friends
who were of the first fruits among us,
continued and ended their days.

After Richard Hubberthorn was delivered out of Norwich castle,
we had some comfortable meetings together at Sylam, at Joseph Lawrence`'s,
near Hoxen in Suffolk; at Gissing, at William Barber`'s,
and some other places in Norfolk,
and were comforted together in the work and fellowship of the gospel of Christ Jesus;
and particularly at Pulham, at William Grudfield`'s in Norfolk, who was an ancient,
honest-hearted man, who received the truth and Friends in much love and tenderness.
Also at Matthew Elmy`'s, at Margaret`'s of Ilkisson, in the Nine Parishes,
not far from Beccles, in Suffolk.
He and his wife and family received the love of the truth, and were very honest,
loving people.

On that side the country were gathered a few Friends
who were truly convinced and turned to the Lord,
and to his light and spirit in their hearts; among whom was William Bennet,
whom the Lord endued with his heavenly gift,
so that he became a living minister of the gospel of life and salvation,
being also of an innocent and holy conversation; and afterward,
for his faithful testimony, was a great sufferer in Edmundsbury jail,
as many other Friends were, after king Charles the second came to the crown.

Richard Hubberthorn, and I also, had a considerable public meeting at Beccles in Suffolk,
without doors in an orchard, where several sorts of professing people came,
and some of them opposed; others questioned our testimony,
concerning the light of Christ in men,
or his enlightening every man that Cometh into the world.
Our doctrine of the light within, was chiefly questioned and stumbled at in those times,
even by many great and noted professors and teachers,
as if it had been some new doctrine, though it be both as ancient and Scriptural,
as any other divinity taught by the holy prophets or ministers of God or Christ.

Among the opposers and questioners of our doctrine of the light at that meeting,
was Richard Townsend,
who behaved himself more mildly and gently than some of the company,
seeming to be more upon the inquiry, than anywise prepossessed with prejudice.
Though he stumbled about the light, yet upon our demonstrating the truth thereof,
and how the light shows to man, and reproves him for sin,
and would instruct him to repentance, and lead him out of sin and evil,
if obeyed and followed; and that when the gospel is truly and livingly preached to men,
this light in them answers and bears witness thereto--convinces them of the truth
of what is preached and declared in the demonstration of the Spirit;
and by this light in them,
they are made capable truly to receive what is so preached and testified unto them,
which otherwise they could not of themselves, by their mere natural capacities.
On this wise, or to this effect, the light within, and the doctrine of the light,
being argued for on our parts, the said Richard Townsend confessed,
that there is an echo in men`'s consciences, answering to the ministry of the gospel;
and this echo he somewhat insisted upon,
but could not absolutely oppose the principle of light in men being spiritual.

After our meek and gentle discourse,
with our Christian instructions then given him and others present,
he took these things into further and deeper consideration,
so that truth took such place in him, and bore that weight,
that some time after he came into society with our Friends,
not only to profess the truth he had questioned,
but also to bear witness to it in conversation and public testimony.

In the forepart of the summer, in the year 1655,
I had a very memorable meeting in High Suffolk, at Charsfield,
a few miles from Woodbridge, where George Fox the younger then lived with his father,
and it was the first meeting of Friends on that side of the country,
and the largest that I had before in High Suffolk.
I had no companion then in the ministry with me, but some Friends from Mendleshara side.
To that meeting there came a very great concourse of people of divers sorts;
and the Lord having prepared the hearts of many of
them to seek after and receive the truth,
they came with good intentions and desires.

We had the meeting in an orchard, and it began about the eleventh hour.
After I had waited upon the Lord a little space for his
power to arise and give me strength to stand up in testimony,
the people being in great expectation to hear what might be declared,
the Lord was graciously pleased by his immediate power to give
me strength in his name to bear a living and faithful testimony,
according to the openings and discoveries of his free spirit,
and the gift received of him to preach the everlasting gospel,
in the name and power of our Lord Jesus Christ,
and agreeable also to the Scriptures of truth, the testimonies of the holy prophets,
Christ Jesus and his apostles, his living, divine presence being with me.
I was wonderfully assisted and enlarged in my testimony
for him and his blessed gospel truth,
insomuch that I was enabled to stand nearly five hours that day,
(as many reckoned,) preaching the truth,
and opening those things which concerned the kingdom of Christ and of God,
and men`'s everlasting salvation.
Many were livingly touched in their hearts,
and effectually convinced in their consciences of the truth then declared unto them,
in the power and demonstration or plain evidence of the holy Spirit.

After I had declared for some time, one John Burch, a preacher among the Baptists,
appeared to make some objections about their ordinances, as water baptism,
and also the coming of Christ in person.
And I being called to a spiritual ministry,
in order to bring people out of shadows to the substance, to know Christ in spirit,
and not after the flesh, nor to rest only in a literal knowledge of Christ,
but that they might know him livingly and inwardly after the spirit;
I gave answer to him in the spirit of meekness, for his better information,
and instruction in the way of God more perfectly, than either John`'s baptism,
outward shadows, or mere literal knowledge could bring any one to.
In a little time John was silent and seemed somewhat satisfied,
and after further and serious consideration,
came to receive the truth in an inward sight and sense of the power thereof,
so that he laid down his former preaching and profession,
and became willing to wait upon the Lord among Friends in silence.
After some years, he was raised up to bear testimony to the light,
the spirit and power of Christ Jesus, and to be a minister thereof,
in order to bring people to the knowledge of Christ, and his spiritual baptism in them.
In his ministry, John Burch was very serviceable, especially in his latter days:
he kept the faith, and in the faith of Christ, in love and unity ended his days in peace.

But to return to this memorable meeting; in the latter part came several noted priests,
who were pastors and teachers among the Independents; Francis Woodell,
and one +++_______+++ Habergham, with some others, and made some objections and questionings.
Both the people and John Burch and company,
were very attentive and observant to see what they would make against us,
being wrongfully prepossessed and prejudiced against us,
that we denied the holy Scriptures, Christ, his ordinances, church and ministry, etc.
But in a little discourse with them,
I perceived they were ignorant of our Christian principles and doctrines:
what they had against us,
seemed to proceed chiefly from the false reports of our adversaries,
whereby we had been rendered so anti-christian and anti-scriptural in religion and profession,
that they thought they might easily run us down.
Such prejudging and condemning persons before hearing or due examination,
caused those opposers, and many others,
to go but lamely to work against us, and the clearness
of our Christian confessions and scriptural vindications,
has many times daunted such,
and put a damp upon their spirits when they have come upon trial face to face.
So it appeared at that time with those Independent ministers,
and as I have known in many disputes which I have been concerned in,
with opposers and adversaries, how quickly their charges have been quashed,
when they have appeared against us upon false reports,
and the authorities of envious adversaries;
which they who are credulous will gain no credit by,
especially when they judge or condemn others upon such reports and misrepresentations.
I have often observed in religious controversies,
that my opponent could give me no greater advantage against him,
than by making use of false reports,
or the authority of malicious persons or their books; or giving way to passion,
which blinds men`'s minds, and clouds their reason and understanding.

But those ministers, however prepossessed,
carried themselves moderately towards me and our friends,
and made no long stay after they were clearly and plainly answered,
and their expectations of getting any advantage against us or our doctrine frustrated;
but soon went quietly from our meeting, and the truth greatly gained ground that day,
and many were truly convinced and their hearts turned to God, his grace and truth.

That was the first and foundation meeting which we the people
called Quakers had on that side of High Suffolk,
and which has been continued ever since in those parts; as after that,
for a "`long time at Dalingoo, at Robert Mann`'s; at John Bennet`'s at Bradfield,
and at William Feddeman`'s, and sometimes at Arthur Goddard`'s,
all on that side the country, a few miles from Woodbridge.
These were honest, loving Friends, who thus early received the blessed truth and Friends,
and continued so to the end of their days, and had meetings at their houses.
Some years after, the meeting was settled at Woodbridge,
where it has continued many years.

A little while after, in the same year, Richard Hubberthorn met me in High Suffolk,
and we had a good, large, and quiet meeting at the same place,
whither came some of the ministers and other professors.
Then we met with no great opposition from them, some being more inquisitive than others;
they could not tell what to make of the light within, or immortal seed in man,
which we preached, or our doctrine thereof, though scriptural;
yet in those days these Independent ministers were in high esteem,
and divers of them parish priests.

Things then were quietly managed to the end of the meeting,
and the truth still gained ground; many grew weary of the priests,
and more and more left them and their formal worships and resorted to our meeting,
both in that county as well as in Norfolk,
and many meetings of our Friends were settled in those places.

After considerable labour and service in testimony
for the truth and gospel of Christ Jesus,
in Norfolk and Suffolk, in the years 1654 and 1655,
besides the imprisonment in Norwich before related,
my dear friend Richard Clayton and I meeting again in High Suffolk,
in the fifth month 1655, travelled together into Essex to Colchester, where James Parnel,
that early servant of Christ, was prisoner in the castle,
he being committed but a little time before.
We visited him in prison;
he was given up to suffer for his faithful testimony--was comforted in our visit,
and we were glad to see him so well under that confinement.
We travelled forward on the road towards London,
being desirous to see our brethren and friends in that city, if the Lord had permitted.
We went that day from the White Elm, near Ipswich, to near Chelmsford on foot,
being nigh forty miles;
and in the road meeting with our dear friend and brother George Fox, and Amos Stoddard,
coming from London into Essex, were very glad to see them.
Our desires of going forward were in part answered for that time,
and we were willing to stay with them at some meetings in Essex, which we did,
as at Great Coggeshall and Lexden, near Colchester,
where George Fox gave large testimony to the truth of Christ,
and against the world`'s corruptions.

On the first-day of the week following, being the 29th day of the fifth month 1655,
I had a very good meeting at South Halsted, at John Isaac`'s, in his barn,
Richard Clayton being with me; and John Harwood, a Yorkshire man, having met us in Essex,
was minded to travel a little with us.
At that meeting at Halsted the Lord greatly enlarged
my heart in his gospel testimony toward that people;
for the hearts of many of them were well disposed
and inclined toward God and his blessed truth.
By his invisible power he had opened a door of entrance among them,
as well as a door of utterance unto them.
James Parnel had been instrumental to convince many in those parts that summer,
before his imprisonment at Colchester;
and by his testimony and living ministry various professors were shaken,
and at a loss in their professions and notions which they had gathered in their heads,
without the experience of a true heart work by the power of Christ.
For profession and talk of religion and church,
did greatly abound in those days among many, as well as pride and self conceit,
which the Lord was about to abase, as he manifestly did in a short time after;
for those summer shows of religion would not endure a stormy winter.

I must confess to the glory of God in my own self abasement,
and his bearing sway over my will and affection by his own power, wisdom and providence,
I was at that time prevented from going to London to visit my brethren and friends there,
according to my own desire and affection;
the Lord having then more work and service as well
as suffering for me to go through in the country,
and particularly in the county of Suffolk,
before I might obtain my desire of going to London,
Having had blessed and effectual service by the special assistance of the Lord`'s power,
in Norfolk and in High Suffolk, I must now be a sufferer in Low Suffolk,
and bear my testimony for him, in a hard confinement and inhuman treatment in prison.
In those days, among the exercises which befel several of us,
whom the Lord so early called and sent forth to preach
the gospel of repentance unto life and salvation,
we were led and moved one while to run to and fro,
that knowledge might increase among people, in the ways and dealings of the Lord;
another while to be taken and imprisoned, strictly confined, and severely used,
and many times inhumanly and barbarously treated;
as the subsequent accounts may in part show;
also what manner of spirit ruled and actuated some men under
high professions and pretensions of religion and Christianity;
and how unchristian they were in practice.
