== Chapter II

[.section-summary-preface]
The case of those called Quakers, who were sufferers in Edmundsbury jail in Suffolk;
one whereof was myself.

Upon the 30th day of the fifth month, 1655, being the second-day of the week,
George Whitehead and John Harwood, with Richard Clayton,
passing through a town called Bures, in Suffolk,
Richard Clayton was moved to set a paper upon the steeple house door in that town,
wherein was nothing contained but what was agreeable to holy Scripture.
We two, being gone a little before while he set up the paper,
and looking back and seeing some people about him,
were moved to speak a few words to the people,
exhorting them in the name and fear of the Lord,
to fear God and to return from the evil of their ways.
While we were speaking, there came a constable, Richard Humm,
and carried George Whitehead and John Harwood before Harbert Pelham,
called a justice of peace, being then in Bures,
though his office of justice was not for the county of Suffolk, but for Essex.
Nevertheless he examined us, one after the other,
and in the meanwhile Richard Clayton was kept from us, and not examined there;
neither when he had examined us, could he lay the least breach of any law to our charge,
nor show any thing contrary to the Scriptures in the paper
which Richard Clayton had set upon the steeple house door.
But forthwith he sent us with the constable and some others, to Thomas Waldgrave,
a justice of peace at Smallbridge, near Bures, who also when we came before him,
examined us in some few particulars; and when he had so done,
could lay nothing to our charge to merit suffering,
nor show us any law that we had transgressed, though we demanded it.
He threatened, and would scarcely hear us speak for ourselves,
but caused us to be turned out of his house,
until he and the said Pelham had consulted together against us, as it appeared;
so the same day Richard Clayton was whipped in Bures, though not severely,
by command from the said Waldgrave, as was pretended,
for the paper which he set upon the steeple house door,
and sent out of the town the same day by a pass.
Next day he sent John Harwood to Edmundsbury jail,
and the day following he also sent George Whitehead to the same.

On the 2nd day of the seventh month, 1655, George Rose was also taken,
and sent to the same prison the 4th day of the same month, by John Gurden,
a justice of peace for the county of Suffolk.
The cause of the said George Rose being taken and committed to prison,
was for asking a question of one called a minister of Stoak,
after he had ended his sermon and exercise.

We three who were committed to prison,
were continued prisoners till the next general quarter sessions, holden at Edmundsbury,
the 9th day of the eighth month following; and then were called before William Blumfield,
one of their justices of the peace for the said county, who sat judge of that sessions;
but no more justice than before could we have there.
For John Gurden and Thomas Waldgrave being both on the bench,
our adversaries and accusers informed the judge against us,
and would scarcely suffer us to speak.
Thomas Waldgrave threatened the jailer to fine him forty shillings,
if he did not silence us when we desired to answer an indictment
which was preferred against George Whitehead and John Harwood;
which indictment was groundless and false.
For therein we were termed labourers of Bures,
and accused of several times disturbing the magistrates and ministers,
and with having been several days at Bures before we were taken prisoners.
Whereas,
John Harwood was never in that town or county before that day we were taken prisoners;
neither did we disturb magistrate or minister, as falsely charged;
neither did we speak to any magistrate or minister
in that town before they took us prisoners;
neither did Thomas Waldgrave bring any to prove the indictment, or any thing in it,
but that we owned the paper for which he caused Richard Clayton to be whipped,
which we read and owned publicly in the open sessions.
So without any proof of the indictment,
the jury which they had prepossessed and caused to pass upon us,
brought in their pretended verdict against us,--that we
were guilty according to the manner and form of the indictment;
both which were false, as well as without colour or proof.

A false indictment was likewise preferred against George Rose,
without any appearance of proof also;
wherein they accused him for a common disturber of the peace,
and that he had been several times before and after at Stoak,
though he was never there before the day he was taken prisoner;
and so unjustly proceeded against him as they had against us,
whom the jury had given their judgment against.
And he that sat for judge,
complied with the enmity and injustice of the rest of our adversaries there present,
and imposed a fine of twenty nobles upon each of us, viz: George Whitehead,
George Rose and John Harwood, for which we were detained in prison under great hardships,
for above twelve months after sessions.

Upon the same day before mentioned,
when John Gurden had gotten his envious design against us three,
as he came out of the sessions house door,
George Fox (the younger) was stirred in spirit to speak a few words to him on this wise,
viz; "`Repent of thy unjust actings this day,
for otherwise thou canst not escape the just judgments
of God,`" For which John Gurden took hold of him,
and caused him to be haled before the bench; and accusing him,
said he should go to prison except he would find sureties to appear the next sessions,
but showed no law transgressed by him;
nevertheless he forthwith caused him to be sent to prison,
where he remained with the rest of us,
and partook of the same hardships in the common jail, for above twelve months after,
until we were released together.

Upon the 22nd day of the ninth month, 1655, Henry Marshall, a Cambridgeshire Friend,
was sent to prison by John Gurden, for speaking a few words to one called a minister,
at Boxford, after he had ended his sermon, or devotion; but before he was sent to prison,
John Gurden caused him to be put in the stocks, and there kept about an hour.

At the next general quarter sessions held at Edmundsbury,
the 14th day of the eleventh month, George Fox and Henry Marshall,
were called to be tried; where one called Justice Colthrop, for the county of Suffolk,
sat as judge, who followed the same course of persecution against them,
which before was taken against the three of us before mentioned; for a false indictment,
according to the form of the other, was also preferred against Henry Marshall,
without any proof thereof; and a fine of twenty marks was imposed upon him;
for which he was kept in bonds with the rest of us.
Here were three punishments laid upon a person, viz., the stocks, the prison,
and the fine, for one pretended offence.

But there was no indictment brought in against George Fox (the younger),
neither did John Gurden, who caused him to be imprisoned, appear there,
nor any witnesses come in against him; so that according to the national law,
he ought to have been cleared and set free;
nevertheless he was sent back again to prison, and in the calendar noted,
that he must remain in jail until the next quarter sessions,
except he found sureties for his appearance then and there.
And though detained till that time, yet was not then called, neither set free;
neither would the jailer show any order or warrant for his detention in jail,
though demanded.

So arbitrary against us were these our persecutors in their proceedings,
though professors both of the Christian religion and justice;
pretending to act what they did against us, in the name and behalf of his highness,
the Lord Protector, as they then styled him.
Thus their imprisoning, straitly confining, and fining, were done in his name,
and under pretence of his power.
But the power of the Lord our God, sustained and supported us patiently and innocently,
to bear all those persecutions and severities inflicted upon us,
knowing that it was for his sake, and for the gospel of our Lord Jesus Christ,
that we suffered in those days, and that the cause was His, which we were engaged in,
and he would plead and defend it, as he hath done;
blessed be his worthy name and power forever.

The foregoing case, as to matter of fact,
was fully written and dated in Edmundsbury common jail, the 31st day of the third month,
1656, and subscribed by us who were then prisoners;
therein declaring ourselves willing to seal to the truth with our blood, if required.

John Watteridge, an honest friend of ours in Edmundsbury, was sent to prison to us,
from their quarter sessions held for that town, the 12th day of the second month, 1656,
for refusing to swear to the office of a constable, though he refused not the office,
but the oath, for conscience-sake to Christ`'s command,
"`Swear not at all;`" for which he was fined forty shillings, and so committed.
Thomas Smith, John Clark, with some others being his judges, the first said,
he punished for swearing, and for not swearing.

John Watteridge, when sent to prison, was put in a nasty room, full of fleas,
and lodged upon the floor, not in a bed.
He was detained prisoner about fourteen days, by his own account;
although his cloak was taken from him, at the jailer`'s command,
for four shillings and four pence, demanded for jail fees; but no law showed for it,
no more than for their robbing him of it for the same.

[.offset]
_The paper for which Richard Clayton was whipped at Bures, runs after this manner, viz:_

[.embedded-content-document.paper]
--

If you set up such ministers as seek for their gain from their quarters,
who are greedy and covetous, you set up such as the prophet Isaiah cried against, Isa.
Ivi. 11. If you set up such priests as preach for hire, and divine for money,
you set up such as the prophet Micah cried against, Micah 3:11, etc.

--

With other Scriptures to show the evil fruits,
covetousness and corruptions of false teachers, and leaders, etc.^
footnote:[I have not the entire paper, if I had, I would have inserted it here.]
Which paper Thomas Waldgrave produced against us at the sessions,
but could not produce or show any law broken thereby, no more than he did against me,
for my giving him the title of T. Waldgrave, in my letter to him,
according to his own subscription to his warrant of commitment, as is hereafter shown.
A poor pretence for detaining me fifteen months in prison!

[.offset]
_The substance of a letter which I sent to Thomas Waldgrave,
after he committed me to Bury jail._

[.embedded-content-document.letter]
--

[.salutation]
T+++.+++ Waldgrave,

To thee who art called a justice of peace,
am I moved of the Lord to write against thy unjust dealings.
Before thou sent me to prison,
thou told me I might stay under the constable`'s custody at Bures that week,
till another justice came home, that I might be examined before him; but instead thereof,
within two days time, sent me to prison;
where I and my fellow-prisoner are put among the thieves,
and not allowed the privilege they have;
our friends not being suffered to come in to speak to us,
but are violently haled from the inner door.

And here we are confined as if not worthy to breathe in the common air;
and the jailer acts in rage and tyranny against us,
worse than against thieves and murderers; and to cloak, or excuse himself therein,
alledgeth, that surely thou wouldst not have sent us hither,
unless thou couldst have proved us transgressors;
though thou couldst not charge us with the breach of any law.

Know, that although thou mayst be at ease in thy unrighteousness,
and dost not lay to heart the sufferings of the innocent, who suffer by thee,
yet remember that the judgments of God for this thy cruelty, slumber not.

Remember the end of the persecutors of the true prophets, Christ and his apostles;
of whose sufferings and testimony against all unrighteousness,
we are in measure partakers.

When we demanded of thee, to show us what law we had transgressed,
thou causedst us to be haled out of doors, and consulted with him called Justice Pelham,
against us; though his office is for another county.
When did ever any godly magistrates punish transgressors
without showing them their offence?
But thou hast not convinced us of any.

In thy warrant, I am unduly charged to be a common disturber of the public peace,
but no such disturbance is proved.
Therefore be ashamed of thy injustice against the innocent,
and of making these lies thy refuge therein against us; for know that the righteous God,
who judgeth righteously, will be avenged of such unjust dealings.

We are free that all the world should know the cause of our suffering,
wherein we are in innocency and peace; and that the truth which we profess and own,
shall not lose by our suffering for the name of Christ;
having a cloud of witnesses of the truth for which we suffer.
But as thou art found in the steps of them who persecuted and imprisoned the saints,
and among them that conspire and take counsel together against the Lord and his anointed,
unto such the Lord will speak in his wrath, and vex with his sore displeasure.
Therefore repent of thy cruelty, lest the Lord cut thee off,
and give thee thy portion among the persecutors and uncircumcised.

Remember that now thou art warned,
while the Lord doth not speedily execute his judgments upon thee.
To the light in thy conscience I appeal,
which bears witness against all these practices that are contrary to it,
and is the condemnation of such who live in them.

An answer to these things,
and of the cause of our detainment in these unjust and cruel bonds,
I do demand of thee speedily, thou having caused them to be laid upon us.

[.signed-section-closing]
From an innocent sufferer for the Truth,

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
Edmundsbury Jail, the 15th of the Sixth mo., 1655.

--

This letter Thomas Waldgrave produced in court at the aforesaid quarter sessions,
and the only exception he made against it was, my giving him the title of T. Waldgrave.
I told him I followed his own subscription to his mittimus, whereby he committed me,
having therein so subscribed himself, T. Waldgrave; but he concluded,
it was not for me to do as he had done; whereby he proved no crime at all against me.

[.offset]
_Copy of the mittimus._

[.embedded-content-document.legal]
--

[.letter-heading]
To the constables of Bares, and to the keeper of the jail of Bury.

I have sent you herewithal the body of George Whitehead, of Orton,
in the county of Westmoreland, being an idle wandering fellow,
and a common disturber of the peace of this nation; requiring you,
in the name of his highness the Lord Protector, etc., to receive him into your jail,
and him there safely to keep,
that he may be forthcoming before the justices at the next sessions for the peace,
to be holden for this county at Bury,
then and there to be proceeded withal according to law;
and hereof I require you not to fail; this 1st day of August, 1655.

--

Observe, an idle wandering fellow; this is false in fact,
as well as scurrilous and disdainful; for,

[.numbered-group]
====

[.numbered]
1+++.+++ I am well known to be no such person;
for after my parents took me away from that noted school at Blencoe, in Cumberland,
at the request of some Friends, I taught first a private, then a public school.

[.numbered]
2+++.+++ After that I was at my father`'s house part of a summer, and then was not idle,
but industrious in what was proper for me, not being educated either in idleness,
nor willing to eat the bread of idleness,
that I might prevent all reflection and reproach against me on that account.

[.numbered]
3+++.+++ And when it pleased God to call me by his Word from my father`'s house,
and out of my native country, to preach the everlasting gospel,
therein I laboured faithfully, and travelled in the service thereof,
according to the grace and ability given me of God, in his dear Son Christ Jesus.

[.numbered]
4+++.+++ A common disturber of the public peace of this nation,
is also unjustly charged against me; for I was, and am of a peaceable conversation,
being also a minister of the gospel of peace.

[.numbered]
5+++.+++ How came I to be termed an idle wandering fellow, in the warrant of commitment,
seeing in the indictment at quarter sessions I was called labourer?
Thus self-contradictory was this our prosecutor; where envy is, there is confusion.
Could he reasonably think himself more dishonoured
by my giving him his own title of T. Waldgrave,
than he did by his injurious and illegal proceedings against us?

====

And that it may further appear what kind of warrants these justices made against us,
here follows also a copy of John Gurden`'s warrant of commitment against George Rose.

[.embedded-content-document.legal]
--

[.letter-heading]
Suffolk.--To the keeper of the Common jail, at Bury, St. Edmunds, and to his deputy,
and deputies there.

Forasmuch as upon examination of George Rose, late of Halsted, in the county of Essex,
glazier, and upon examination taken upon oath before us, against the said Rose,
sufficient cause appears unto us,
whereby to enforce Rose to find two able and sufficient sureties
for his personal appearance at the next sessions of the peace,
to be holden for the Franchess of Bury, St. Edmunds,
and thence not to depart without license of the court.
And forasmuch as the said George Rose refused to find sureties,
we therefore herewithal send you the body of the said George Rose,
requiring you in the name of his highness the Lord
Protector of the commonwealth of England,
to receive him into the said jail, and him there safely to keep until the next sessions;
if in the mean time he the said George, being by his own confession,
one now usually called a Quaker,
shall not in the mean time find such able and sufficient
sureties for his appearance as aforesaid.
Dated at Affington, the third day of September, 1655.

--

[.numbered-group]
====

[.numbered]
_Observe.
1+++.+++_ What legal precedent could they have for such a warrant of commitment,
when they neither assign cause to require such sureties, nor any matter of fact,
as a breach of law deserving imprisonment?

[.numbered]
_2+++.+++_ Though his confessing himself one called a Quaker,
seems to be made the reason of his commitment,
we cannot think it was either a legal or valid reason, or cause of such severity,
as these persons were bent upon against us.
How evident is it therefore, that their own invidious wills were their only laws therein?

====

[.offset]
_The substance of a letter to William Blumfield,
who sat for judge at the Quarter Sessions aforesaid._

[.embedded-content-document.letter]
--

To thee who art called a justice, am I moved of the Lord God to write;
therefore in moderation read and consider,
that thou mayest be informed for whom thou hast acted.
Friend, in the judgment seat at sessions, thou wast set to judge of causes,
according to justice; but the cause of the oppressed, who suffer for righteousness,
thou hast not regarded, in joining with the persecutors against us who so suffer.
They preferred a lying indictment against us without evidence of fact,
and caused a company of poor ignorant men,
who knew us not (i. e. a jury,) to give a verdict, so termed, upon oath, which was,
that we were guilty according to the manner and form of the indictment,
which in neither was true, wherein they did forswear themselves.
And then by thy fining us, thou hast joined with our persecutors who imprisoned us,
namely, those called Justice Waldgrave and Justice Gurden,
whose injustice many took notice of,
in their standing to be both our accusers and judges.
In consenting to act according to their wills, which are cruel and envious,
thou hast acted contrary to the just witness of God in thee;
and in lending an ear to them and their council, thou hast not taken counsel of God:
and woe unto them that take counsel, but not of me, saith the Lord;
that cover with a covering, but not of my spirit, that they may add sin unto sin.

The swift witness of God will pursue thee, and judge thee for partaking with the wicked.
Thy conscience is defiled, and the profession, held in unrighteousness, is stained;
all thy profession of God and Christ will not cover or hide thee,
from the righteous judgments which will come upon all them that join in iniquity:
and though hand join in hand, the wicked shall not go unpunished.

Therefore consider what, and for whom, thou hast acted.
Own the light of Christ in thy conscience, and it will let thee see,
how thou canst not have peace with God in these things,
and how forwardly and unadvisedly thou hast acted against us,
as thou wouldst not be done by.
Consider, wouldst thou be taken passing on the highway about thy lawful occasion,
examined and imprisoned, contrary to the law of God, and of the nation,
and in prison suffer ten weeks, and then be fined and sent back to prison again,
as we were, contrary to the laws of justice and equity?
Honestly deal with thyself, and see if thou hast done to us as thou wouldst be done by.

When did ever any godly magistrate act such things?
Let the witness of God in thy conscience judge whether these things be of God or no;
whether persecution and cruelty become them that profess Christianity and godliness,
yea or nay.

Consider thy ways, and come out from among the persecutors,
and repent of these unjust actions,
that thy hands may be washed from the guilt of their blood,
who suffer for righteousness`' sake,
lest thou have thy portion among them who are in the offences against Christ`'s flock,
who suffered persecution by the seed of evil doers;
for he that offends one of the least of them who believe in him,
'`It were better that he had never been born,
or that a millstone were hung about his neck and he cast into the sea.`'

Therefore, now from the Lord thou art warned,
before whom thou canst not excuse thyself in these things before mentioned,
and declared in love to thy soul.
Whether thou wilt lay them to heart or not, I am clear;
having peace and consolation by Christ Jesus in my sufferings for righteousness`' sake;
not being convinced of the breach of any known law.
Glory to the Lord God forever.

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
Edmundsbury common jail, the 20th day of the Eighth month, 1655.

--

Our persecutors having confined five of us in prison, by their warrants before recited,
and by their quarter sessions, passed judgment of fines upon most of us,
it is meet that some account should be given of our treatment and usage in prison.

After two of us were first sent to prison,
we had a lodging in an upper room two or three weeks,
and then understanding that the jailer would exact upon us for rent,
and expecting our confinement might be of long continuance, we desired a free prison,
upon which we were turned into the common ward among felons.
After continuing a few weeks, a Friend, Samuel Duncon, in compassion to us,
privately gave the jailer some money to let us lodge above again from the felons.
But when the time for that money was ended,
the jailer insisted upon his old exaction of four pence a night from each of us,
which we were neither free to yield, nor to suffer any of our friends to be charged with,
but desired a free prison, and we were again turned into the common ward.
Whilst we lodged above, after the Friend gave the money to the jailer,
two notorious robbers,
who were of that company that had robbed sir George Wyninif`'s house,
and were condemned at the assizes before, broke prison and made their escape,
leaving their irons and shackles behind them.
We were glad that we were not present in the common ward at the time they broke out,
for they were desperate fellows, and made their escape for their lives.
We esteemed it a providence that the said Friend had for
that little time procured our lodging apart from the felons.

Now we were settled in the common ward among felons, in a low, dungeon like place,
under a market house, our lodging being upon rye straw, on a damp earthen floor,
though we were therewith content, and the place sanctified to us.
But not being willing to contribute to the jailer`'s extortion,
nor tree to buy any of his beer, he keeping a tap house,
and divers of his prisoners often drunk, his rage arose very much against us,
after we were so many as five, sent to prison successively, and all in the common ward,
and in the time of our confinement drinking only water.

That for which he appeared most enraged against us,
was because we frequently testified and cried against the foul and horrid sins of drunkenness,
swearing, and other disorders and abuses among the prisoners,
and which the jailer`'s servants occasioned by suffering
their excessive drinking strong beer for his ungodly gain.

But the Lord stirred us up the more zealously to
cry aloud against the wickedness of the jailer,
his servants and prisoners for these gross evils and disorders;
because the jailer made a profession of religion and piety,
being member of a Presbyterian church in Bury,
and calling in the prisoners on first-days toward evening,
to instruct them and exercise his sort of devotion among them.
Because I told him of his hypocrisy therein, his fruits being so much contrary,
his daughter was offended, saying, "`What! call my father a hypocrite,
who has been a saint forty years?
Now to evince some of his fruits, and of our treatment by him and his agents,
observe what follows.

On the 21st day of the tenth month, 1655,
the jailer smote George Rose on the face till he drew blood; and on the 28th,
he smote George Fox and John Harwood on their faces before several witnesses.
On the 21st of the eleventh month,
he smote George Whitehead on his face till the blood came out at his mouth,
only for reprehending and detecting some falsehoods he had uttered against us,
which some present heard; whereupon a woman of his own society or profession,
seeing his fury and violence, told him he dishonoured the gospel.
It seems she was more tender and conscientious than he.

Many other times he shamefully abused us both in words and actions, whereby his servants,
tapster and turnkey,
and some of his drunken prisoners took the greater encouragement to follow his example;
for his tapster often grossly abused us, and not only threatened us,
but cast a stone violently, whereby he hit one,
and in his rage took up a stool to have smitten or cast at some of us,
but was prevented by one present taking hold of it.
He often slandered and beat some of us on the face,
and also violently buffeting with his fists,
for no other cause but reprehending his and their wickedness.

Some of the prisoners also have often abused us, by taking away our food,
alledging the jailer gave them leave to do so,
and thereby taking occasion to do us mischief, several times beating some of us, stoning,
despitefully using us, threatening to kill, and to knock some of us on the head.

One said if he did kill us, he should not be hanged for it,
and that there was no law for us if he did kill us;
and being drunk with the jailer`'s strong beer,
he kicked and wounded some of us on the legs, and greatly abused us,
knowing it was against our principle and practice to fight or beat him again;
which we could easily have done to him and the rest
of the jailer`'s drunkards that abused us,
if our principle would have allowed, being five of us, mostly able and lively young men.
But we esteemed it greater valour and more Christian,
patiently to suffer such injuries for Christ, than to fight for him, or avenge ourselves;
and rather, when smitten on one cheek, to turn the other, than to smite again.
The said drunken prisoner who had so abused us, when he was a little sober,
confessed that the jailer made him worse than he would have been against us.
But by such inhuman usage,
the jailer could not force our compliance with his covetous designs,
or corrupt practices for gain.

On the 19th day of the second month, 1656, he came into the common ward,
and asked if we would pay him for keeping us here?
We asked him what we owed him.
He said, "`Fourteen pence a week,
each of you;`" though some of us had been thirty-one weeks in that common jail,
and none of us did then lie in any bedding of his;
but when some straw was brought us to lie on,
which was allowed by the county for the prisoners`' use there, we paid for bringing it,
or we might not have had it.
We told the jailer, that when we demanded a free prison, he turned us into this place;
upon which he commanded the turnkey to take away our bed clothes, saying,
"`Take away their clothes, and leave them nothing but the straw to lie upon,
and take away their boxes.`"
So the turnkey and tapster took them all away, and left us not so much as our night caps,
which were hung up in a basket by the wall.

And moreover the jailer threatened to take away our coats from off our backs;
we told him he might do so if he would,
for he might as well take them as our other goods, viz; our bed clothes,
a coat and a cloak, and our boxes, wherein was our food, i. e. bread and cheese,
linen and other things.
"`Then,`" said he, "`I will not take your coats till warmer weather.`"
We told him he would shame his profession.
He said, "`That`'s no matter, you are all heretics.`"
After the above said goods were taken away, the jailer`'s daughter said,
"`They have robbed you of all.`"

Those goods were detained from us about twenty-four weeks,
in which time we were forced to lie in part of our wearing clothes, upon the straw;
yet the Lord gave us patience and comfort in our sufferings,
as he did his servants of old, who suffered the spoiling of their goods joyfully;
being also made willing not only to suffer such spoil,
but to lay down our lives for Christ`'s sake: glory to his name forever,
who thus supported and comforted us in our tribulations.

On the 28th, Mary Petche, an honest, poor Friend,
who was employed to bring us necessaries, coming to prison with some linen for us, viz:
two shirts, two caps, two bands and four handkerchiefs,
we having been robbed of the rest as before,
the jailer caused the same to be taken from her,
and would not suffer her to deliver them to us.
And the same day the turnkey took away George Rose`'s coat, which he usually wore;
at other times not suffering our provision to be delivered to us,
until he had stopped the woman that brought it and searched into her basket,
to see what she had brought for us.

Not complying to take lodgings of the jailer, at 2s. 4d. a week each of us,
nor to pay him 1s. 2d. each, demanded by him,
for the time we had been in the free prison, the common ward,
he proffered us some privileges if we would submit to his terms; which we refusing,
his anger still continued against us, insomuch that on the 3rd day of the third month,
he commanded his tapster to take away George Fox`'s hat,
which the tapster took from his head; but the same day the jailer`'s wife,
being more compassionate than her husband, brought him his hat again,
and said she did not know that her husband commanded the tapster to take it from him.

Having shown such examples of malice and abuse to us,
some of the prisoners when almost drunk,
still took the more encouragement to repeat their violence against us, especially one,
who was often most base and abusive, beating and kicking us,
and smiting some of us on the face, without reprehension by turnkey or tapster,
when they have been present and known us so abused; but instead thereof,
the tapster then also beat one of us on the face, though when they were out of drink,
and not incensed by the jailer, we had them generally under and quiet.

But on the 19th of the third month,
two of the prisoners so violently smote George Fox on the face,
that the blood came out at his mouth and nose.
On the 21st day following,
one of them shamefully spit upon George Rose and George Fox`'s faces,
pulling them by their noses, as they have done by us several times;
and on the 22nd day of the same month, George Fox standing at the inner door,
a pot of coals and ashes were thrown in his face by one of the prisoners.

Thus, day by day for a time we were abused, beaten, buffeted, kicked, spurned at,
and despitefully used, for no other cause,
but testifying against the frequent drunkenness, swearing,
wickedness and ill government in that prison; and against the tyranny, cruelty,
and bad example of the jailer, his turnkey and tapster.
It is too tedious to enumerate all their abuses and
acts of violence and cruelties against us;
and being therein conscious to themselves, lest they should be exposed,
the turnkey threatened to take away our inkhorns, and did take away one,
with several papers, saying we should write no more,
and often watching to hinder us from writing.

Having often threatened to lock us up in the women`'s ward, a low, filthy room,
because of our constant testimony against their gross disorders,
as also against allowing the tapster to let the prisoners
have so much strong drink as to drink to excess,
and the abuse of themselves and others; the jailer, instead of reforming,
proceeded in his unwarrantable allowance of such excess,
and in punishing us for our righteous testimony.

On the 26th day of the third month,
he caused George Rose to be put into the women`'s ward;
upon which George Whitehead bade the jailer take notice,
that it was for declaring against drunkenness and swearing, which he himself connived at,
that he caused him to be put there.
For which words the jailer caused him also to be forthwith shut up in the same ward;
and likewise George Fox and Henry Marshall, we being one in our testimony;
so we four were there locked up and confined near two hours;
and when we asked but for a stool of our own to sit upon,
they would not suffer us to have it.

After they had let us all out, they put George Rose into the said ward again,
and there confined him about four hours, and stones were cast in at the window,
some of them striking him;
the tapster also taking strong drink in his mouth and spirting
it in his face as he looked out at the window.

But our punishment from the jailer did not end here.
Whilst George Rose was shut up in the women`'s ward,
the jailer came to George Whitehead and George Fox, and said,
"`If ye will persuade George Rose to be quiet, he may come forth.
George Whitehead told him that he would not persuade him from crying against wickedness.
Whereupon in his rage, he threatened to put us three into the dungeon,
and caused George Rose to be brought out of the women`'s ward,
and threatened to let us down into the dungeon with a cart rope;
but he and the turnkey put us, i. e. George Whitehead, George Fox, and George Rose,
down a ladder into the dungeon, where they seldom put any, except some very quarrelsome,
murderous persons; for it is about four yards deep under ground, and very dark,
and but a little compass at the bottom, and in the middle of it an iron grate,
with bars above a foot distant from each other, and under the same a pit or hole,
we knew not how deep.
But being warned by a woman that saw us put down, and pitied us,
we kept near the sides of the dungeon, that we might not fall into the pit.
There we were detained nearly four hours, singing praises to the Lord our our God,
in the sweet enjoyment and living sense of his glorious presence,
being nothing terrified nor dismayed at their cruelties,
but cheerfully resigned in the will of the Lord to suffer for his name and truth`'s sake,
if they had left us to perish in that dark, dismal, and stinking dungeon;
though the Lord would not suffer that,
besides the jailer might fear being hanged if he had detained us,
and we had died in the dungeon.

When we were let out of the dungeon, the turnkey,
at his shutting us up in the common ward,
suffered a malicious prisoner to come in and smite George Rose violently on the head,
without reprehending him for it; but that was a common practice among these persecutors,
especially when drunk.

While we were in the dungeon, several of our friends came to visit us from Norwich,
Colchester, Halsted in Essex, and other places, but were not suffered to come to us,
nor we to speak to them.
At other times they have thus dealt by us and our friends,
when they have come many miles to see us;
and when kept out and they have come to the prison door or window,
they have had water cast upon them by some of the jailer`'s company,
pretending that he had order from the justices that
none of our friends should come to us;
yet he and his wife told them that if they would pay the turnkey, they might come to us;
and he told them that if they would give him 6d. or 4td. a-piece,
he would let them come to us; but they refused to gratify his covetousness therein.
Our friends have been many times unjustly kept out from us; yea,
when some Friends of Norwich have waited long without doors to come in and see us,
both they and we have been disappointed and prevented from seeing one another.
Thus our friends have been kept from us without doors, and we daily abused within.

The prisoner who was most abusive to us, being one of the jailer`'s drunkards,
threw a naked knife fiercely at one of us, and it missing,
he threatened to kill some of us, saying he could but be hanged,
he had but a life to lose.
He also having taken away some of our things, we acquainted the jailer therewith,
and told him if there was any more blood shed by this prisoner, it would lie at his door;
and if he did not allow him in what he had done against us,
we wished him to command him to restore us our things; but instead thereof,
his answer was,
"`Let him do what he will,`" in the hearing of this most abusive prisoner;
whereby he took the more encouragement to abuse us, and the woman Friend also,
who brought in our necessaries; on whom he laid violent hands, pushing her backward.
The turnkey also that night smote two of us for refuting
some of his aspersions cast upon us,
and said he could not use us bad enough.

This abusive prisoner, who had threatened to kill some of us,
taking encouragement from the example of the jailer, turnkey and tapster,
one night being furiously drunk,
after we were locked and bolted close in the common ward,
resolved to kill one or other of us that night,
as with curses he threatened over and over;
nothing must serve him but he must be the death of some of us.
But in faith in the name and power of the Lord, we stood over him,
believing he should not have power to hurt any of us, though he attempted it,
taking up a fire brand; but we saw his power was limited, that he could not harm,
much less kill any of us.

He had a boy in the same ward, about ten years old;
and as the boy was kneeling by the wall, frightened to see his father in such a rage,
the father presently took up a stone bottle, and violently threw it at his poor boy,
but missed him, and broke it to pieces against the wall,
the poor boy narrowly escaping with his life.
For if it had hit him on the head he had probably been killed.

Still the drunken, outrageous man continued in his fury;
he must needs kill somebody that night, either his poor boy, or some other,
or else he would not be pacified.
Seeing him thus murderously resolved, it immediately came upon me with great weight,
as I believed from the Lord, let us not see murder committed in our presence;
whereupon I said to my fellow sufferers, let us seize him, and hold him hand and foot,
till he will be quiet; and they presently took hold of him,
laid him gently upon his back, and held him fast, hand and foot, as I think,
above an hour`'s time, in which he made a roaring noise, but to no purpose;
for we were all closely warded up in a low, dark place,
hard to be heard in other parts of the prison; nay, I am persuaded,
if any of us had cried out murder,
we should scarcely have had one come to relieve any of us.

However, we prevented the intended murder, by holding the drunkard`'s hands and feet,
till he was quiet and went to sleep,
as we made him promise before we would let him loose, having a strict eye over him,
to prevent his doing any mischief; for though we had not cords to bind him with,
yet we were sensible he needed to be bound or restrained from doing mischief,
as much as any outrageous mad person.

Although the Lord enabled us patiently to bear and
suffer gross abuses and despiteful usage,
much more than here related, without any retaliation or revenge,
yet murder ought to be prevented, if possible, by any lawful means or restraint.
As the prophet Elisha said, concerning the king`'s messenger sent to take him;
"`See how this son of a murderer hath sent to take away my head;
look when the messenger cometh, shut the door, and hold him fast at the door,`" etc.

William Dewsbury in true love, came to visit us in Bury jail;
and understanding something of the jailer`'s cruelty, wrote him a letter as followeth,
viz:

[.embedded-content-document.letter]
--

[.letter-heading]
For Robert Newton, keeper of the jail in Bury.

Thy cruelty and oppressing the innocent, is come up in remembrance before the pure,
eternal, dreadful God; and if thou do not repent and speedily return to the living God,
and diligently attend to his pure law in thy conscience,
that it may guide thee to cease from thy cruelty,
and restore to the servants of the Lord what thou hast taken from them,
and no more offer any violence to them--which if thou so do,
thou knowest not but that the Lord may show mercy;
but if thou continue in thy pride and stubbornness, thou had better never have been born:
the eternal, dreadful God will stretch out his hand against thee,
and render vengeance upon thee, and will wound thee in thy inwards,
that anguish and pain shall take hold upon thee;
that thou shalt be tormented day and night, in the presence of God and his holy angels,
and thy portion shall be with all the unrighteous, whose worm never dies,
and fire never shall be quenched; for such as thou sowest thou shalt reap;
and thou shalt know this is the word of the Lord God.
'`The day draws nigh,`' what is declared the Lord will bring upon thee;
remember thou art warned in thy life time--if thou
perish thy blood will be upon thy own head.

[.signed-section-signature]
William Dewsbury.

--

The jailer was greatly tormented and enraged at this letter.

Some of the abuses were examined by the magistrates in Bury,
and clearly evinced to them before the jailer`'s face.

After we had suffered such hard usage by the jailer, his turnkey and tapster,
and some of the drunken prisoners,
an account thereof was sent to some of our friends at London, which they put in print,
and acquainted Oliver Cromwell the Protector, so called,
and his deputy Fleetwood therewith,
whereupon order was given to have the matters complained of inquired into.
I was first called out and examined, the 22nd day of the third month, 1656,
before John Clark and Thomas Chaplain, called justices, the jailer being present;
and upon the 22nd, George Rose was also called before some of those justices,
the jailer present; and his and his agents`' abuses proved against him at both times,
concerning his smiting George Rose and George Whitehead on their faces,
until the blood came out at their mouths.
The jailer to excuse and lessen his violence,
would have them believe he only chucked us under the chin,
and that he took me by the nose.

Upon the 6th day of the fourth month, I being again had before the said John Clark,
Thomas Chaplain, and one called Justice Moody, and Major Sparrow,
to be examined on the said complaint, John Clark,
who first took upon him to be our chief interrogator, or examiner,
appeared very much to favour the jailer,
tearing a note sent by a Friend to warn them to examine matters,
and do justice without partiality; which when I delivered,
he presently tore in pieces without reading, or suffering the rest concerned to read it.
I told him he should have seen what was in it before he had rent it.
He said, that was all he would do with it.
I then warned them to see justice done.
But as our paper was reading, and I questioned about the abuses related,
John Clark would not have me to answer matters particularly as read, but said, read it,
and then let him answer to it.
But as it was read, I answered the particulars,
and gave them a clear account of matters of fact of the jailer`'s cruelty.
Some of which he confessed when I put them home to him,
particularly the taking away our goods, or necessaries,
which he commanded the turnkey to take from us,
with other injuries and violence done to us.
Some of the justices present, confessed the jailer was to blame,
and warned him not to suffer us to be abused by his servants; for if they did,
they would send them to Ipswich jail, and commended G. W. for a moderate man.

On the same day George Rose was also again examined,
and again made it appear how the jailer had abused us, and used violence to us,
such as smiting him and George Whitehead on their faces,
until the blood came out at their mouths;
and his tapster`'s smiting him more than ten times, and spirting beer in his face.
The jailer confessed that all that was written by
us of his taking away our things was true;
but because George Rose reproved him for his cruelty.
Justice Clark bade the clerk write down, that it was for assaulting the jailer;
partially pleading to extenuate his offence.
Seeing such partiality,
we could not expect a full and true account would be returned to Oliver Cromwell,
Protector, but that our sufferings would be prolonged, as they were,
for some time after these grievances were clearly made manifest to the justices.

However, our discovering the jailer`'s cruelty, had some effect upon him,
though he was sorely vexed to be thus exposed,
yet it brought some fear and restraint upon him;
and for some time before we were released out of prison, we enjoyed more quietness,
although drunkenness and much disorder, and ill government,
was suffered and continued in that prison.
When I have in the fear of God told the jailer thereof, and testified against him,
for suffering the same for his own lucre, his answer often to me was, Away devil,
away devil, etc.
And to George Rose, for the same cause, he would cry, when he went toward him,
Now comes wide mouth, now comes wide mouth;
because George Rose spoke somewhat louder to him,
against permitting so much drunkenness in his house as he did;
he being a professor of religion, a member of a church, and instructor of others,
and by his daughter esteemed a saint forty years;
and doubtless he was the more favoured in the examination, by his neighbour, John Clark,
because of his religion, membership and fellowship.

When the barbarous treatment and hardships which we endured in the said jail,
were much noised abroad,
our Friends at London were compassionately concerned for our relief,
and thereupon Oliver Cromwell was several times applied to, particularly by Mary Sanders,
a friend of ours, who was a servant, a waiting gentlewoman in Cromwell`'s family.
She often took opportunities to remind him of our suffering condition,
and of other Friends also being confined in prisons, as she has often told me.
She afterwards married our beloved Friend Henry Stout, of Hertford.
She was a good example in that family of Oliver Cromwell`'s, while she lived there,
and continued in her integrity in true Christian faith, and love to Friends unto the end.

Anne James, of London, who afterward married our dear Friend Robert Duncon,
was tenderly concerned for us, when we were in Bury jail;
and she also acquainted Oliver Cromwell with our case, and sought our relief,
which was at last obtained, after I had suffered fifteen months, or above,
in the said jail, and the rest of my fellow-prisoners above a year,
except Henry Marshall, who suffered nearly a year; all of us, God knows,
under severe restraint and great hardships.

Yet I am still truly and humbly thankful to the Lord our God,
in remembrance of his great kindness to us,--how wonderfully he
supported and comforted us through and over all these our tribulations,
strait confinement, and ill usage, and preserved us in bodily health.
In the comfortable enjoyment of his glorious divine power and presence,
several of us have often been made to sing aloud in praise to his glorious name; yea,
his high praises have been in our mouths oftentimes,
to the great amazement and astonishment of the malefactors
shut up in the same ward with us.
When walking therein, our hearts have been lifted up in living praise to the Lord,
often for several hours together, with voices of melody.
Oh! the sweet presence and power of the Lord our God,
how precious to be enjoyed in prisons and dungeons, and strait confinements.
O my soul, still bless thou the Lord, and forever praise his excellent name,
for the true inward sense and experience thou hast often and long had, and still hast,
of his divine power and unspeakable goodness.
Glory and dominion be to our God, and to the Lamb that sits upon the throne,
forever and ever.
Let the praise be unto him in whom is our help, salvation and strength.

Although we were confined to a noisome common ward, and strait, stinking yard,
without any accommodation, yet the Lord by his power so sanctified the confinement to me,
that I had great peace, comfort, and sweet solace,
and was sometimes transported and wrapped up in spirit, as if in a pleasant field,
having the fragrant scent, and sweet smell of flowers and things growing therein,
though I was not in an ecstasy or trance, my senses being affected therewith.
The Lord made bitter things sweet unto me, and hardships easy;
although we were sensible our persecutors and oppressors were so cruel toward us,
that they cared not if we had all perished in that jail.
But our trust and confidence was in the name of the Lord Jehovah,
in whom is everlasting strength and safety: to whom be everlasting glory,
dominion and praise, world without end.

I humbly hope and trust in the Lord,
I shall never forget his lovingkindness and mercy shown unto me,
in those cloudy days of distress and affliction.

[.offset]
_A Copy of Our Release._

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Thursday, the 16th of October, at the Council at Whitehall.

Ordered by his highness the Lord Protector, and the Council,
that the Quakers imprisoned at Colchester, in the county of Essex,
and Edmundsbury and Ipswich, in the county of Suffolk,
be forthwith released and set at liberty: and it is referred to sir Francis Russell,
to take care that the same be done accordingly;
as also to consider how the fines set upon them, or any of them, if any,
may with most conveniency be taken off and discharged:
and likewise to take order that upon their being set at liberty, as aforesaid,
they be forthwith sent to their respective homes.

[.signed-section-signature]
W+++.+++ Jessop, Clerk of the Council.

--

Pursuant to this order, sir Francis Russell took special care to put it in execution.
He sent his clerk to the prison to see us set at liberty, which was done accordingly;
and in kindness to us, gave us an order or warrant to produce in our defence,
if there should be occasion, that we might travel without molestation or interruption;
not confining us to go to our respective homes.
He was a considerate and tender-spirited man,
and showed compassion toward us and our friends,
who were sufferers for conscience sake toward God;
he appeared clearly against persecution.
From the good character which I had of him,
and the kindness he had shown us in our suffering, I went to visit him in the year 1659,
as I travelled near that way, which he took kindly,
and entertained me with religious and friendly discourse.
One part of it was,
he intimated his having been very much against the severity James
Nayler had met with when prosecuted before the House of Commons,
in the year 1656.
