== Chapter VIII

The next year after the city and suburbs of London
were so greatly depopulated by the plague,
the dreadful fire began, and broke out in Pudding-lane,
over against the place where the Monument stands.
In a few days time, a very great part of the city within the walls,
was burnt down and the habitations consumed, except a few streets and parts of streets;
to the great amazement, terror and distraction of the inhabitants,
who were forced to flee for their lives, with what goods they could save,
into Moor-fields, and the out parts,
and there to lie abroad with their goods for several nights and days;
the country bringing in bread for their relief.
My soul greatly pitied the inhabitants, when I saw them lie in the fields, in that poor,
mournful condition, as they did.

One morning as my friend and brother, Josiah Cole and I were at Gerard Roberts`',
in Thomas Apostles, London, and going up toward the top of the house,
observed how violently the fire went on toward Thames street and those parts
of the city--and hearing what rattling and crackling the fire made in the houses,
Josiah said,
"`This looks like a Popish plot or work;`" and we were both in the same mind.
I observed afterward the fire broke out in divers places, distinct one from another,
so that it was very probable several wicked agents
were at work in carrying on and putting it forward.

One passage I may not omit by the way, because it has been misrepresented,
and false reports spread about it.
One Thomas Ibbott, or Ibbit, a Huntingtonshire man,
who was convinced of the truth at a large meeting which I had at Thomas Parnell`'s,
in his barn at King-Rippon, in Hunts,
a considerable time before the fire--came to London two days before the fire,
in great haste, being on a sixth-day of the week, and alighted off his horse,
with his clothes loose,
and was supposed by some to be a person under distraction or discomposure of mind,
as I understood by divers.
He hastened very much or ran through the city, toward Whitehall,
in such a posture as many of the inhabitants were forced to flee from the fire
when they had scarcely time to put on or fasten their wearing clothes about them.
Such a sign he appeared to be, and foretold his vision he had before,
that the city would be laid waste by fire, as I was informed;
for I did not see him until that morning when the fire broke out.
But the evening after Thomas Ibbott had passed through the city,
I met with some of our women Friends at the Bull and Mouth, near Aldersgate,
who gave me a pretty full account of him.
He had been with them that day, and told them his vision of the fire,
and message to London; and to them he appeared very zealous and hot in his spirit,
when he told them thereof; and they were afraid he was under some discomposure of mind,
which made them somewhat question or doubt of what he told them.

When they related the same to me, I had a fear and caution upon my spirit,
so that I durst not oppose or question his vision or message, but told them,
I knew the man; he was convinced by me at a meeting at King-Rippon, in Huntingtonshire,
and is a sort of a manly person, zealous and somewhat of a hot spirit,
or to this effect I said.
So that his spirit is nearer to those destroying angels, or fiery spirits,
that are ministers of wrath and severe judgments, than those Friends are,
who have attained to a further growth in the spirit of the Lamb, Christ Jesus.
And he might sooner have a discovery of such an evil or judgment,
or mischief permitted to come upon the city,
than they whose spirits are more meek and gentle,
and more settled in quietness and peace.
I very well remember this was the import of my answer to them,
who gave me an account of the man, and his vision and message, as he told them;
so far was I from opposing the same, as has been falsely reported concerning some of us,
who then were in London,
and concerned in public testimony for the blessed truth of our God,
and Lord Jesus Christ; Josiah Cole and I being then in the city.
Yet I was not at that time without secret fear concerning this Friend, Thomas Ibbott,
lest he might run out, or be exalted by the enemy, into some conceit, or imagination,
especially when he saw his vision coming to pass the next morning,
when the fire broke out as aforesaid, from the place where it began,
and early in the morning was got down to the bridge and Thames street,
the wind being easterly, and so high,
that it drove the fire violently and irresistibly before it,
blowing great flakes over houses, and from one to another.

That morning the fire broke out, some of us met at Gerard Roberts`' house,
where Thomas Ibbott met us, and told us he must go to the king with a message,
which was to warn him to release our friends out of prisons,
or else the decree of the Lord would be sealed against him in three days time,
to his destruction or overthrow.
Upon which I was afraid he would be too forward, and give occasion against Friends,
and cause others to reproach truth and them.
Whereupon I earnestly charged him, if he went, not to limit a time,
if he had a warning to give the king to release our friends,
there being many then in prisons--that he would set no time of the king`'s death or end,
or that might be so taken or construed as a prophesy thereof;
for he might cause truth to suffer if he did.
I was indeed greatly concerned for truth and his own sake,
poor man! lest he should be hurried into distraction;
for I clearly saw where his danger was,
though his vision of the fire was apparently true, which I never opposed,
but rather granted that it might be foreshown him.
Also I observed in a letter of his a few days before the fire was over,
that he mentioned the true number of days when the vision of fire should be accomplished;
so that he had a certain vision and discovery given him in that particular.
And to show that there remained a sincerity in the man,
after his mind came to be settled, he wrote a letter to some Friends in London, wherein,
after he remembers his love to G. W., J. C., and S. H., he hath these words following,
viz:

[.embedded-content-document.letter]
--

I dare not much stir up or down any ways, for people`'s looking at what was done,
lest the Lord should be offended, further than my own outward business lies.
I have been much tempted and exercised;
yet through mercy have found help in the needful time.
Whatsoever slips or failings Friends saw in me, in the time I was with them,
I would have none take notice of, for I was under great exercises,
and often ran too fast, which the Lord in his due time, gave me a sight of.
In the love of my Father, farewell.

[.signed-section-signature]
T+++.+++ I.

--

When the city was burnt down and laid in ashes, we had our meetings on the fourth-day,
weekly, near Wheeler street; our usual place, the Bull and Mouth,
being then demolished by the fire, at which place our meetings had been most disturbed;
and at other out parts off and about the city,
we kept our meetings at the usual times and places, as at the Peel in St. John`'s street,
Westminster; Horsleydown on Southwark side; Ratcliff, Devonshire house, Old Buildings;
and had then some respite and ease from violent persecution and disturbance for a time,
until the city came in a great measure to be rebuilt.

Yet still the persecuting spirit and design of persecution remained
in our adversaries so many of them were not cut off by the plague,
who took no warning thereby, nor by the following consuming tire,
which had laid waste the best part of the city.

Though the Lord our God was pleased to give our friends in London, faith and courage,
as well as resolution to build our meetinghouse in Whitehart court,
by that called Gracechurch street;
yet we were not then without expectation of further persecution and suffering,
for meeting in that, as well as other places in and about the city.
And so it came to pass after the meetinghouse was built;
our meetings were frequently disturbed, especially on the first-day of the week,
by the trained bands and informers, and many of us by force haled out,
and our meetings often kept in the street,
where sometimes we had opportunities openly to declare the truth and preach the gospel,
as well as publicly to pray to Almighty God; yet not always suffered so to do;
but often violently pulled away whilst in the exercise of the gospel ministry.
Likewise when we have been in solemn prayer to Almighty God,
we have been laid hold on and violently taken, and many of us had to the Exchange,
and there kept under a guard of soldiers until the afternoon;
and then had before the mayor, who would be ready to fine or imprison us,
or to bind us over to appear at the sessions, or rather to take our words to appear,
if he was a person of some moderation towards us.
The latter obligation we chose;
that was conditionally to promise we would appear if the Lord pleased,
rather than be bound by recognizance or bond to appear,
because commonly in their recognizances, they would put the words,
And in the mean time to be of good behaviour.
But we could not assent to be so bound,
because we knew they would interpret our religious,
solemn meetings a breach of good behaviour,
which meetings we could never yield to decline.
But as for me, my share has been imprisonment,
oftener than liberty upon parole or promise;
being more cautious of being any ways ensnared thereby,
contrary to my Christian liberty and testimony,
than of imprisonment or outward confinement; which was not only my own care,
respecting my inward peace and liberty in Christ Jesus,
but it was also the care of all faithful friends and brethren in those days,
to keep out of all such snares as would infringe that liberty.
We chose rather to expose our persons to be trampled on in the streets,
by our persecuting adversaries, if permitted,
than to bow down our souls at their command; Isa. 51:23.

Although in those suffering times I was much concerned
to attend our disturbed meetings in and about London,
yet at times I had a concern laid upon me to visit
our friends and their meetings in the county of Surrey,
particularly on that side where our dear friend Stephen Smith and his family lived;
they having not long before that time, in great love received the truth,
through my testimony, as before related.
I visited and had divers good and blessed meetings,
both at Stephen Smith`'s house at Purbright,
and other places towards Guilford and those parts, where the Lord was with me,
and helped and comforted me in his work and service, as at other times and places.

I was committed to prison at the Marshalsea in Southwark, with several other Friends,
for a meeting in the said county of Surrey, on the 22nd day of June, 1668.

After we were apprehended at the meeting, being on the first-day of the week,
by one of the justices, George Vernon,
we had liberty to meet him and the other at Guilford the next morning,
where they consulted and made a warrant,
and sent us to the Marshalsea prison in Southwark, for the time appointed,
which was but short, and the imprisonment pretty easy, the keepers being civil to us;
but the shortness of the imprisonment was usually upon the act for banishment,
not so much designed in our favour, as to rid the land of us, which the Lord frustrated.

The Lord showed me that my place and service,
as well as suffering for the testimony of Jesus Christ,
would be much in the city of London, as it had been before,
to the convincement and conversion of many to God,
by the testimony he had committed unto me, and attended with his blessing and presence,
though I had travelled much about in this nation, and deeply suffered also.
Seeing the city of London then to be the principal place of my stay,
wherein I was also freely given up in service and suffering for the blessed truth;
the Lord was also pleased to show me that it would be well for me to marry an honest,
approved Friend of London;
and accordingly that faithful servant of the Lord and his people, Anne Greenwell,
then a widow, was presented to my mind,
and after serious consideration and seeking the Lord for full satisfaction,
having also the approbation and encouragement of several ancient, faithful brethren,
I made known my mind to her, which, upon due consideration, was by her accepted.

Though there was a disparity as to age between us, she being several years above my age;
I looked beyond that, to what was most excellent in her, and permanent, namely,
her virtue and piety, to which she had been very early inclined from her youth;
and being one of the first receivers of the truth, in the spirit and power thereof,
after our friends first came to London,
she approved herself faithful and very serviceable,
and was accordingly greatly approved by faithful Friends.

On these and other weighty considerations we were well satisfied
to proceed in the good order of truth and Friends,
to the publication of our intention of marriage, if the Lord pleased,
at sundry public meetings of our friends, both of the women and the men,
having a Christian care upon our spirits to be exemplary for good order, love,
unity and peace in the church among Friends; and we proceeded to accomplish our marriage,
which was solemnized at a meeting appointed for the same, in our Friends`' meeting room,
at John Elson`'s, at the Peel, in that called St. John`'s street, where,
on the 13th day of the third month, A. D. 1670, we solemnly, in the fear of the Lord,
took each other, and entered into the covenant of marriage,
in the presence of the Lord our God and many faithful witnesses then present,
promising with God`'s assistance, mutual love and faithfulness to each other.
And the Lord blessed our marriage and meeting, and us toward each other therein.

As divine Providence led me in the choice of a person,
whom I believed would be a suitable companion and help to me,
and that would be willing to sympathize and bear
part with me in my sufferings on truth`'s account,
so she proved not only a faithful wife, but as a dear sister,
and like a tender mother to me, after our marriage, in all my sufferings,
both by imprisonments and spoil and loss of goods.
All this she bore patiently, being resigned with me in the will of our God,
who enabled us by his power to stand faithful through all;
blessed be his glorious name forever,
in whose love we were preserved and continued towards each other to the end of her days;
having lived in peace and comfort, and in true, mutual, and constant love,
until parted by death.
I cannot forget the tender care which this my dear companion had over me,
and for my liberty,
when I was divers times confined in prisons for my testimony on the Lord`'s account,
whose mercies in all respects I greatly prize, and hope shall never forget.
In a printed treatise, entitled, [.book-title]#Piety Promoted,# the life, service,
and death of my said wife are largely related,
and testimonies given thereof by many faithful Friends.

My dear wife was married to me seventeen years and nearly two months,
and was faithful and loving until death, and ended her days in great peace,
the 27th day of the fifth month, 1686, having by faith in, and faithfulness to,
our Lord Jesus Christ,
obtained a good report in her place and services in his church and people.

I remained a widower two years, wanting about a week, in which time,
I was for a while in a strait, whether or no I should ever marry again,
and earnestly sought the Lord to resolve and direct me,
both in the matter and in my choice, if I should marry.
I found freedom and clearness in the fear of God,
being also encouraged by some loving friends and brethren,
to propose marriage to Anne Goddard, an honest and virtuously inclined maid.
She then kept a shop in White chapel, London, and came of a good, honest,
and reputable family, being the daughter of captain Richard Goddard, clothier,
and Anne his wife, of Reading, who were then deceased.

After our agreement, and due procedure towards marriage, in the way of truth,
and unity of Friends,
our marriage was solemnized in a large public assembly
at our meetinghouse near Devonshire square,
London, the 19th of the fifth month, 1688.
She was an ingenuous and careful wife,
and we were mutually comforted together in true love and tender affection,
becoming so near relations.
The Lord so sanctified our disappointments and afflictions to us in this world,
that he gave us faith and patience, with submission to his providence,
to enable us to bear them,
and to look beyond all external objects of delight and afflictions here below,
which are but momentary, unto an eternal inheritance in his heavenly kingdom;
glory to his excellent name forever.

To return to the design of this history, relating to my concern in sufferings, trials,
and exercises, with many others, for the truth of God,
Our persecutors did not take warning, either by the plague and great mortality thereby,
or by the devouring fire,
which destroyed and laid waste the greatest part of the city of London,
as before mentioned.
They did not desist from their inhuman work of persecution,
but when they could not prevail to banish or destroy
us by their two former edicts or acts of Parliament,
then a third act was devised to impoverish us in our estates,
by mercenary as well as merciless informers.

The title of the third act is, viz:

[.embedded-content-document.legal]
--

[.blurb]
=== An Act to prevent and suppress seditious conventicles, 22 Car. 2, 1670.

[.offset]
The preamble, viz.,

For providing further and more speedy remedies against the
growing and dangerous practices of seditious sectaries,
and other disloyal persons, who, under pretence of tender consciences, have,
or may at their meetings, contrive insurrections, as late experience hath showed.

The matter of fact assigned therein, viz: Any subject of this realm,
of the age of sixteen years, or upward, being present at any assembly, conventicle,
or meeting, under colour or pretence of any exercise of religion,
in other manner than according to the liturgy of the church of England.
Five persons or more being assembled together, in any house inhabited, or uninhabited,
field or place.

The manner of conviction, viz: Any one or more justices of the peace,
or chief magistrate, required and enjoined, upon proof to him, or them, of such offence,
either by confession of the party, or oath of two witnesses, or by notorious evidence,
and circumstance of the fact, to make a record of every such offence, under his,
or their hands and seals; which record so made,
shall be taken and adjudged to be a full conviction of every such offender,
for such offence.
+++[+++Whereupon fines were imposed, and heavy distresses made.]

The penalties, by fines, etc., viz. A fine of five shillings for the first offence,
and ten shillings for the second: which fine and fines,
for the first and every other offence,
to be levied by distress and sale of the offender`'s goods and chattels;
or in case of the poverty of such offender,
upon the goods and chattels of any other person convicted of the
like offence at the same conventicle--so as the sum to be levied,
amount not in the whole, to above the sum often pounds for one meeting.

One third part of the monies levied, for the use of the king.

Another third part thereof, for the use of the poor of the parish, etc.

And the other third part thereof, to the informer and informers,
and to such person or persons, as the justice, or justices, etc., would appoint,
having regard to their diligence and industry, in the discovery, dispersing,
and punishing of the said conventicles.

And that the preacher, or teacher in any such meeting, assembly, or conventicle,
must for every such first offence, forfeit the sum of twenty pounds, etc.
And if the preacher or teacher be a stranger, and his name and habitation not known,
etc., or shall be thought unable to pay the same, the justice, justices, etc.,
are empowered and required to levy the same by warrant,
upon the goods and chattels of any such persons who shall be present at the same conventicle.
And the money so levied, to be disposed of in manner aforesaid.
And if such offender shall at any time again commit the like offence, or offences,
he shall for every such offence, incur the penalty of forty pounds,
to be levied and disposed as aforesaid.

Every person convicted of wittingly and willingly suffering any such meetings, etc.,
to be held in his or her house, out-house, barn, or yard,
shall forfeit the sum of twenty pounds, to be levied as aforesaid:
and in case of his or her poverty,
upon the goods and chattels of such persons who shall
be convicted of being present at the same conventicle;
and the money so levied, to be disposed of in manner aforesaid.

And it was provided, that no person by any clause of this Act,
should be liable to pay above ten pounds, for any one meeting,
in regard of the poverty of any other person, or persons.

It was also enacted, that justices, chief magistrates, constables, headboroughs,
and tithing-men, by warrant, should, and might, with such aid and force,
as they thought fit, break open, and enter into any house, or other place,
upon information of any such conventicle,
and take into their custody the persons there assembled, to be proceeded against, etc.

And it was further enacted, that this Act, and all clauses therein,
be construed most largely and beneficially, for the suppressing of conventicles,
and for the justification and encouragement of all
persons to be employed in the execution thereof.

--

Thus I have recited so much of the contents of the said Act,
as may show the nature and tendency of it, and which in the execution thereof,
did severely affect us as a people,
merely for our religious concern in serving and worshipping Almighty God,
according to our religious persuasions and consciences,
for which end our meetings were held, both peaceably and innocently, on our parts.
And it was observable that the design of this Act was:

[.numbered-group]
====

[.numbered]
1+++.+++ To force a general conformity to the liturgy and practice of the church of England.

[.numbered]
2+++.+++ The agents employed for that work, were generally a company of idle, loose,
profligate, and mercenary informers, by that law let loose to seek honest people`'s ruin,
by making great havoc and spoil of their goods.

[.numbered]
3+++.+++ Those informers were the more bold and confident in their course of persecution,
eagerly pursuing peaceable subjects, and the ruin of their families,
where they had some proud persecuting justices to encourage them,
ready to grant them warrants, and to force officers to assist them.

[.numbered]
4+++.+++ That which animated and emboldened those informers in their prosecutions,
was the clandestine course of conviction,
upon the oath of two of them made before a justice or two,
having for their own interest and gain, a third part of the fines;
though such clandestine and partial prosecution, conviction and punishment,
against free-born subjects of England, were expressly contrary to their just liberties,
the great charter, and to the common law and justice of England;
being also destructive of their property and birthrights.

[.numbered]
5+++.+++ Many of those mercenary informers not only very ignorantly gave information upon oath,
but also many times swore falsely in fact; and divers of them upon trial afterward,
were proved guilty, and legally convicted of perjury,
and stood in the pillory for the same, being prosecuted by other dissenters, not Quakers.
Though we afterward proved many of the informers
forsworn in several informations given upon oath,
wherein they swore notoriously false in fact; yet this prosecution and proof was made,
and took effect against them to weaken and discourage their
proceedings after the heat of persecution was much over;
of which I intend a further relation hereafter.

====

It was observable, that many of these informers came to beggary,
and some of them to miserable ends,
when their trade of informing against religious meetings was ended.
And what they got by their trade in making spoil upon others, did not prosper,
nor turn to the king`'s profit, nor to that of the poor,
no more than their work of persecution did to the honour of the king or church,
which they pretended and boasted they were servants to.
They in effect telling us.
Hey! we are servants to the king, and to the church;
we will make you fanatics leave your conventicles and conform;
and such like language we have often met with from them.

Upon the 5th day of the fourth month, 1670, our friends being met as usual,
in a peaceable manner, at their meetinghouse in Whitehart court, in Grace-church-street,
(so called,) London, where George Whitehead being moved publicly to pray to God,
in time of prayer was laid hold on by some of the soldiers, pulled away,
and haled out of the meeting, as they did John Bolton also, an ancient citizen,
for declaring the truth to the people, advising them, who were rude, to be sober.
They were both had to the Exchange, and there kept six hours, after which,
according to order, they appeared at Guild-hall, before Sir Joseph Sheldon;
George Whitehead called for their accusers, to have them face to face.

Some of the soldiers being called to give evidence,
George Whitehead warned them to take heed what they swore;
and he also warned Joseph Sheldon, and the rest with him,
to do nothing but what they would answer before the great God,
who would judge righteously.
'`For,`' said he, '`we apprehend that we are taken contrary to law, even to this present Act,
by soldiers, where there was no resistance made by any of us: we desire to be heard.`'

Joseph Sheldon said, "`If you be illegally convicted,
you may make your appeal;`" endeavouring to stop George Whitehead from pleading.

[.discourse-part]
_George Whitehead:_--I desire to be heard.

But being interrupted several times, he said,
"`I require you in point of justice to hear me,
being a free-born Englishman;`" whereupon they did a little permit him.
"`We would not have you that are our judges,
in the mean time to prejudice your own consciences, by an illegal conviction;
nor to do anything but as you will answer the great God;
for we have a tenderness to your consciences.`"

[.discourse-part]
_Joseph Sheldon._--Well, we must answer for what we do: take you no care for that.

The witnesses being upon their oaths, one affirmed, that George Whitehead was preaching,
or teaching, when they took him.

Joseph Sheldon commanded the witnesses to be gone, or depart.

[.discourse-part]
_George Whitehead:_--I desire the witnesses may stay till I have answered:
but Joseph Sheldon urged them still to depart.

[.discourse-part]
_George Whitehead:_--They have absolutely forsworn themselves; for I was not preaching,
nor teaching, when they took me.

Another that stood by the justice, said, "`You were praying when they took you.`"

[.discourse-part]
_George Whitehead:_--Take notice, this man has spoken truth.
But the witness has forsworn himself, in saying that I was preaching.

Nevertheless, the clerk wrote down, George Whitehead an offender;
but what judgment was given by the justices against him or John Bolton,
they did not hear, either of fine or imprisonment, at that time.
The Lord was pleased sometimes to touch the consciences,
even of some of the magistrates and our adversaries,
whereby they were stopped in their proceedings,
and prevented from running us to the extreme severity
and penalties of the persecuting laws.

Upon the 26th day of the fourth month, 1670, being the first-day of the week,
our friends being again assembled In their meeting place aforesaid, in Whitehart court,
Sir Samuel Starling, then lord mayor, and some others,
having ordered a priest to be there,
he read common-prayer and preached a sermon in the gallery,
seeming to preach up and excite to love, according to these Scriptures of Paul,
Eph. 5:2, and 4:2. 15; the commendation of love being the priest`'s chief subject.
But contrary thereto in the time of his preaching,
the soldiers being present to guard him and disturb us,
were rude and abusive to divers of our friends, for speaking a few words to the priest,
to show him how contrary their actions were to his preaching; though he did not rebuke,
or stop them from their rudeness and violence to our friends, women, as well as men.

A great concourse of people came and were present at the meeting,
many to attend the priest; and many out of curiosity and novelty,
to hear and see what work the priest and his company would make.
For it seemed a very strange thing to see a minister or priest of the church of England,
stand up and read common-prayer, say or sing their service,
and preach in a Quakers`' meeting, deemed an unlawful conventicle,
and therein to preach up love and charity,
and at the same time to be attended and guarded with a company of soldiers,
to apprehend and persecute the Quakers for an unlawful meeting or conventicle.
These proceedings appeared as strange as they were inconsistent.

After sermon was ended, George Whitehead stood up,
and preached the gospel of peace and love, to show how contrary thereto persecution was.
The people were quiet and still, and gave audience,
and the meeting was in a peaceable posture for a little time, until two rude fellows,
with the soldiers following them, violently pulled George Whitehead down,
and by their force pushed down some women, and carried him to the mayor`'s,
and kept him awhile in his yard.
His name, and some false information against him, being carried to the mayor,
he quickly sent out a warrant to commit him to the compter,
then in the Gate-house at Bishopsgate, for making a disturbance,
until he should find sureties, or was delivered by law;
and thus far without first calling in,
or admitting George Whitehead to be heard in his own defence.

But George Whitehead coming to have a sight of the warrant of his commitment,
desired to speak with the lord mayor himself, which some of his officers made way for;
when George Whitehead told the mayor, that there was a mistake in the warrant,
which was that charge against him for making a "`disturbance,
for there was no such thing; he made no disturbance,
but contrary wise quieted the people by seasonable advice and counsel.
To which the mayor said, he would examine further into it after evening prayer;
but in the mean time sent George Whitehead to the compter,
and in the evening sent for him again, and then said to George Whitehead,
Your women have disturbed the minister; asking him further.
Do they not disturb you?

George Whitehead answered, that there was a concourse of people of all sorts,
many not being our friends, who made a noise; but for our women,
some did speak something as they might judge it their duty;
and probably thought they might, seeing the priest`'s hearers did speak;
the priest one sentence, and they another, and when they cried.
Lord have mercy upon us, some of the women did cry, Woe to you hypocrites.
After other discourse between George Whitehead and the mayor,
the constable and another with him, were sworn; and all that they could testify was,
that he stood up and preached after their minister had ended;
but what he preached they could not tell.

The mayor said, "`If the minister had done all, it was a conventicle,
and I must fine you twenty pounds.`"
And then after he said, "`forty pounds.`"

George Whitehead said, "`If I had preached sedition, or discord,
against either the government, or peace of the nation,
if that could be made appear against me, I might justly suffer by this law,
being entitled, An Act to prevent and suppress seditious conventicles.
But seeing the witnesses cannot tell what I did preach,
I may signify the substance and tendency thereof.
A necessity being laid upon me, woe had been unto me, if I had not preached the gospel;
and it was no other,
but the gospel of peace and salvation by Christ Jesus that I preached,
to exalt the power of godliness, directing people thereunto, in Christ,
that they might not remain under empty and lifeless forms of profession.`"

The mayor said, "`I believe both you and others do good,
or have done good with your acting.`"

"`See then how evident it is, that what we suffer, is for doing good,
and not for any sedition or injury.

The mayor said, "`Well, I must fine you forty pounds, this being the second offence;
you were convicted before Sir Joseph Sheldon once before.`"

[.discourse-part]
_George Whitehead:_--Must I suffer for preaching the gospel of peace,
as if I had been preaching sedition?
This is strange.
Doth the law make no difference?
Besides, I was not convicted according to this law or Act, before Justice Sheldon;
for it was there made appear, that the witness forswore himself against me,
as some there that stood by testified; for he swore that he took me preaching,
when many could testify, as some there did affirm, that I was praying,
and not at that time preaching.

[.discourse-part]
_Mayor:_ But were you on your knees with your hat off when they took you?

[.discourse-part]
_George Whitehead:_ Yea, I was, and the meeting was in a reverend posture of prayer;
the men with their hats off, and the soldiers pulled me down when I was praying.

[.discourse-part]
_Mayor:_ However, you were in a religious exercise.

[.discourse-part]
_George Whitehead:_
If praying to God must be accounted a religious exercise not allowed by the liturgy;
yet I do not understand that praying is included
in that clause that mentions preaching or teaching, etc.
As where it is said,
"`That every person who shall take upon him to preach or teach in any such meeting,
assembly, or conventicle, and shall thereof be convicted as aforesaid,
shall for every such first offence the sum of twenty pounds forfeit.`"
Now here is no praying mentioned, therefore I desire thy judgment,
whether by preaching or teaching can be meant praying.

[.discourse-part]
_Mayor:_ No, praying is not mentioned; however, your conviction is recorded;
you may make your appeal.

[.discourse-part]
_George Whitehead:_ To whom shall I make my appeal, but to those that wrong me?

[.discourse-part]
_Mayor:_ I must do according to law; I must fine you forty pounds.

[.discourse-part]
_George Whitehead:_ Then I must be fined for preaching the gospel of peace,
as if I had been preaching sedition.
By this it is all one case to preach sedition or the gospel of peace.
But such a law makes no difference between preaching sedition,
and preaching the gospel of peace, I must deny,
as being both against reason and against God.
And God who judges righteously, and by whom actions are weighed,
will judge between thee and us in this thing.

I do not remember that the fine threatened upon this
pretended conviction was ever levied upon my goods,
though divers others were to great excess.

Another passage, by the way, I think meet to observe.
On a fourth-day of the week I was taken out of a meeting at Whitehart court,
in Gracechurch street, by an officer abetted by some others,
and had before the said Samuel Starling, lord mayor,
where information was given against me, that I was taken at such a meeting;
and the question being, what did I do there, or what manner of religious exercise had we,
the officer answered, he took me preaching.
The mayor would needs have it that it was a conventicle,
and our exercise of religion contrary,
or not according to the liturgy and practice of the church of England.
I answered.
The witness does not prove that;
he questioned if the liturgy or common prayer was read among us at that meeting.
I told him he should not proceed against me beyond his evidence.
What says the witness?
we are not bound to accuse ourselves.
The witness does not say any such thing as that we
exercised religion contrary to the liturgy,
neither does he evidence that we had not the liturgy read among us.
He can only say, he came into the meeting when I was preaching; and took me preaching,
but does not know what I preached; so that he came into the meeting in sermon time,
and the liturgy or common prayer used not to be read in sermon time.
This allegation I used to him, because he deemed our meeting a conventicle, and unlawful,
if the common prayer was not read in it; and therefore I urged the evidence he had,
which did not prove the matter of fact against me,
or any of us who were at the said meeting,
so that he could not reasonably proceed against us, upon the evidence given,
yet I told him our manner of religious exercise is well known.

I had some religious discourse with the said lord mayor, at some certain times,
and endeavoured to possess him with better principles than those of persecution.
He being something of a professor of religion, and sometimes touched with truth,
carried it more fairly toward me than some other persecutors did,
and I had some fairer quarter from him than from some other magistrates.
He was not one of the worst persecutors in those days,
though sometimes too much concerned with others in
that unchristian work of persecution against us.

Upon the 17th day of the fifth month, 1670, being the first-day of the week.
Friends were kept without doors in the street, near their meetinghouse,
at Peel in St. John`'s street, so termed, by red coat soldiers and a constable;
and when two women spake a few words of truth and soberness,
the soldiers came and violently pulled them away.
As they came to take them,
some were so violent that they pushed men and women with their muskets,
and tore part of Mary Wicks`'s clothes, her scarf and apron,
and pinched her--bruising some of the men Friends with their muskets,
whereupon one Friend cried out to the constable to keep the peace.

George Whitehead, near the latter end of the meeting,
being moved in much tenderness and brokenness of spirit to call upon the Lord in prayer;
presently after he began,
the soldiers came rudely and violently pulled him away into the entry among them.

George Whitehead then told them of their wickedness and incivility toward the women,
and how much below both soldiers and the spirits of men they acted,
in abusing peaceable men and women as they had done.
Presently after they pulled into their sentry or guard, John Scott and Samuel Richardson,
and these three were detained in their custody nearly three hours;
and then a great company of red coat soldiers guarded them to an ale house near Clerkenwell,
where two justices were, viz: justice Foster and justice Boules,
with a great company of the king`'s horsemen or guard before the door.

As George Whitehead and his friends were brought to the door, he called out for justice,
saying, '`I am glad we are come before the civil magistrates;
we desire justice of you against the soldiers,
who have kept us out of our meeting in the street, and taken us contrary to law,
even contrary to the present act of Parliament,
which does not require them to meddle with meetings, unless where resistance is made;
and upon certificate thereof, as the act mentions.
Besides, some of these soldiers behaved themselves rudely, abused several of our friends;
and punched some of the women with their muskets, and hurt them.
In the next place, we wholly except against these soldiers being witnesses,
looking upon them as not fit, nor ought they to be accepted for witnesses against us,
having broken the law themselves.`'

George Whitehead several times called for justice,
as they would answer the great God of heaven and earth,
who will judge righteously between us.
The justice said, "`You shall have justice.`"
Whereupon a major on horseback said to the justices, "`Sir,
he will preach till night if you will hear him,`"

The justice bowed, with his hat off, to the major,
and showed him great reverence and readiness to convict the prisoners.
The major and captain, with others,
alighted and came in to see the two justices do their work against the prisoners;
and the red-coats were called, and many of them came in to bear witness against us;
but George Whitehead excepted against them as unlawful witnesses, as before.
However, contrary to law and equity,
they were put upon their oaths to witness against the prisoners, whom they had abused,
and illegally apprehended,
the justices not at all cautioning them to take heed what they swore, but the major did.
What they informed against George Whitehead upon oath was,
that there were about three hundred met in the street; that they took him preaching,
standing on a bulk or stall.

George Whitehead answered, '`That is not true, I was praying, standing on the ground,
but leaning on a stall.`'

[.discourse-part]
_Soldiers._
We took him praying, but leaning on a bulk.

[.discourse-part]
_George Whitehead:_ See how confused and contradictory they are in their evidence,
for preaching and praying are two things;
neither is praying mentioned in that clause of the act that
is made against such as take upon them to preach or teach.

[.discourse-part]
_Justice Foster._
You conjured them together to the meeting.

[.discourse-part]
_George Whitehead:_ That is not true,
for they were gathered together before I came to the meeting.

[.discourse-part]
_Major._
He does as much as tell the justice he lies.

[.discourse-part]
_George Whitehead:_ I do not tell him he lies; but I say again,
it is false that I conjured the people together.
The major reproved the soldiers for going beyond his order,
in going out into the street to take our friends, saying,
I gave you order only to keep them out in the street, and you to keep sentry at the door.

[.discourse-part]
_Justice Boules._
Sir, but after you were gone, I ordered them to take those that preached,
and I thank them.

[.discourse-part]
_Justice Foster._
What a devil did you come there to pray for?

[.discourse-part]
_George Whitehead:_ Do these words become a magistrate?
We did not meet to hear or sing ballads in the street, nor do we meet at play houses,
nor at bawdy houses, nor at drinking houses, to be drunk, where the devil is served;
but singly to serve and worship the living God, for which we suffer.

The major and some more with him, seemed highly concerned at those words--calling out,
'`Who do you accuse?
Who do you accuse for going to bawdy houses?`'
Whereupon some of the company present smiled one upon another.

[.discourse-part]
_George Whitehead:_ I accuse none, but tell you what meetings we do not come at, nor own;
and for what end we do meet.

The information the soldiers gave against John Scott, was, that they took him preaching,
which was, because when they came with violence, he desired them to be moderate,
and what crime did he thereby commit?

Their information against Samuel Richardson, was,
that he laid violent hands upon one of their muskets; but this was utterly false,
and denied by Samuel Richardson, for he was standing peaceably, as he said,
with his hands in his pocket in the meeting.

Then the justices seeming to incline to convict the prisoners upon the act against conventicles,
George Whitehead had a few words with them about it, pleading to prevent their severity.
But justice Foster urging to have them convicted, two warrants were made,
and the said George Whitehead, John Scott, and Samuel Richardson,
were had to New prison by the constable and soldiers:
the troopers all the time of their examination standing before the door where they were.

It was observable that in their mittimus,
they missed setting down George Whitehead`'s name; and instead thereof,
set down Arthur Gotten, who was a soldier that helped to take them.

The next day after the commitment, being the second-day of the week,
and 18th day of the fifth month, and about the sixth hour in the afternoon,
the two justices aforesaid came to the prison;
and when they had called George Whitehead into the room to them,
they asked him his name and place, which he answered,
and then they spoke to this purpose;
That they had several laws which they could proceed upon against him,
and particularly the statute of Oxford, the oath, etc.
The clerk having the oath of allegiance in his hand,
written with blanks left for the names, and a law book before them.

George Whitehead answered, '`I desire you would not go about to ensnare us,
for the law was not made to make men transgressors, but to punish them,
where it finds such.
We were apprehended and accused as breakers of the late act against conventicles,
let us first be tried upon that act, and cleared, and not have a new snare laid for us.`'

[.discourse-part]
_Justice Foster._
We will not lay snares for you;
if you will pay your twenty pounds you shall be discharged.

George Whitehead answered something about the said act, as not justly chargeable thereby;
but they quickly caused him to withdraw, and called in John Scott,
who had a long discourse with them; they accusing him for being an old soldier,
and proffered him the oath, according to the Oxford act,
made against non-conformist ministers, which he refusing to take,
they threatened to detain him in prison six months; after which,
they again called in George Whitehead and Samuel Richardson,
and asked George Whitehead if he would pay his twenty pounds,
and if he would promise to come no more at the meeting at Peel?

George Whitehead answered,
'`I cannot pay any fine or money for praying to God or worshipping him;
and as for promising to come no more there, I am not my own; I stand in the will of God,
neither can I promise any such thing as to forbear coming to worship or pray to God.`'

One of them asked Samuel Richardson, "`Will you promise to come no more at meeting?`"

[.discourse-part]
_Samuel Richardson._
I can promise no such thing.

[.discourse-part]
_Justice._
Will you pay your five shillings?

[.discourse-part]
_Samuel Richardson._
I do not know that I owe thee five shillings.

So, having fined George Whitehead twenty pounds, as they said, but it was not levied,
and Samuel Richardson five shillings, they discharged them.
But they detained John Scott in prison six months, it was supposed on the Oxford act,
though he was no non-conformist minister, nor pretending to holy orders;
and what great crime had they against him in his
desiring moderation from the rude and violent soldiers?

We were sensible of the Lord`'s power and presence,
and that he stood by us and strengthened us in bearing our faithful.
Christian testimony for his name and worship,
through all these exercises and persecutions.
I was sensible also that the Lord our God would plead our innocent cause,
and that he often did plead it, even in the consciences of many of our adversaries,
persecutors and judges,
and that sometimes they were hard put to it to proceed or carry on their work against us.
At that time, and many other times,
the Lord our God was pleased so to restrain the remainder of their wrath,
as not to suffer them to proceed to the execution thereof,
nor of the evils thereby designed; glory honour,
and dominion be to our God and to the Lamb, forever and ever.
