== Chapter XIV

Under a profession of Christianity, the Protestant religion and church,
and also under pretence of law, legal authority, serving the church and king, etc.,
a company of loose, irreligious, profligate wretches,
have been encouraged and suffered to plunder, rob, steal, break houses, commit burglary,
tear away, and make havoc and spoil of their neighbours`' goods;
as those informers have shamefully done, and all this to support a Protestant church,
and to be countenanced or encouraged by the same therein, especially by priests!

What Protestant age or church can parallel such barbarities and cruel persecution,
all circumstances considered?
And how scandalous to church and state are such agents?
Oh!
Church!
Church! thou hadst need to be greatly humbled under the mighty hand of God: however,
under all these inhumanities, the hand of the Lord our God supported us,
and carried us through them; and his divine hand and power was with us and assisted us,
both in our suffering, opposing, and testifying against such cruelties;
and in our endeavours to make the king and government sensible thereof;
whereby he was at last induced so far to commiserate our extreme suffering,
as to afford us relief from those devourers,
by signifying his pleasure to some of his subordinate ministers,
magistrates and justices to put a stop to and prevent that destructive
persecution and spoil made upon us by those informers;
insomuch that their unjust trade and gain ceased,
being discountenanced both by the justices,
and by the quarter sessions in London and Middlesex,
and their course stopped in other parts of the kingdom,
and such discoveries made of their wickedness and injuries,
that some of them were forced to escape, and others turned to beggary;
their ungodly gain and ill gotten goods did not prosper with them,
nor succeed to support them.

After their trade of informing was over, I remember George Hilton, informer,
came to my house, complaining to me, that he was to be a servant to a great person,
but he wanted clothes, or money to buy him some; whereupon I gave him something,
being willing to render good for evil,
he having been a very injurious adversary against myself and many others of our friends;
however I was comforted, for that the case was so well altered,
as from taking away our goods by force,
now these poor wretches were fain to come and beg of us.

A great number of our friends in many, or most counties throughout England,
were sorely oppressed, and many of them greatly impoverished,
being charged or estreated in the exchequer, and writs annually issued out against them,
to the several sheriffs of the counties, to make seizure on their goods and estates,
under pretence of their being recusants, for twenty pounds per month,
and for two-thirds of their estates,
for their monthly absence from their parish churches, so called,
and thereupon their corn and cattle and other goods
were seized and taken away by the bailiffs, etc.
Seizing for eleven months, twenty pounds a month,
which amounts to two hundred and twenty pounds forfeiture in that space of time.
The rude bailiffs, when they had seized on farmers`' goods, remained at their houses,
eating and drinking until they had gotten the goods removed.

This sort of suffering was as extreme as unjust,
being by old laws never intended against the people called Quakers,
that we should suffer as popish recusants, who are not such persons;
but if we had not been so scandalously misrepresented,
the persecutors would have had no pretence or colour for such their barbarous persecution.

Upon this case of oppression and persecution, the king being applied to,
and moved by some of us for a noli prosequi, or stay of process in the exchequer,
he was pleased to give direction to the lord treasurer and attorney general for the same,
that the exchequer writs might not be issued out against our friends on that occasion;
for the case, we knew, did affect the king and his friends, who were popish-recusants,
seeing we suffered in their stead, who never were Papists,
nor popishly affected in the least, but wholly averse thereto.

When the king`'s consent was obtained for the stay of process in the case,
the following petition was drawn up by Rowland Vaughan, an attorney, employed by us,
he being informed how far Gilbert Latey and I had proceeded in our solicitation therein,
and what effect the same had with the king.

To Lawrence, Earl of Rochester, Lord Treasurer of England.

The humble petition of us whose names are here under subscribed,
on the behalf of the persons called Quakers, named in the list hereunto annexed, showeth,
That in pursuance to the king`'s reference made to his attorney general,
upon petition to him lately made, by many of his suffering subjects,
commonly called Quakers, he, the said attorney general, amongst other things, did,
on the 20th of January last, 1685, make his report,
That the persons named in the list hereunto annexed,
are convicted for their monthly absence from church, and are returned into the exchequer,
and in charge there for twenty pounds a month.

That upon the reading of the said report,
the king was graciously pleased to signify his royal pleasure amongst other things,
that process might be forthwith stayed from issuing forth for the future
out of the exchequer against the said persons named in the said list.

That it now remains under the consideration of the attorney general, to direct,
or prepare fit instruments to discharge the proceedings,
as well against the persons named in the said list,
as all others mentioned in the said report.

That forasmuch as process is now likely to issue forth out of the exchequer against
the persons named in the said list before the attorney general can prepare,
or direct fit instruments to be made for relief of the persons in the said report,
according to the king`'s gracious will and pleasure.

May it therefore please the said Lord Treasurer in the mean time,
to issue forth his warrant to the clerk of the Pipe,
for staying of process against the persons named in the said list,
until their discharge can be effectually completed,
in pursuance of the king`'s said gracious will and pleasure.
And the said petitioners shall, etc.

A copy of the Lord Treasurer`'s warrant to the clerk of the Pipe.

After my hearty commendations,
these are to authorize and direct you to forbear making forth any process against
any of the persons mentioned in these four sheets of paper hereto annexed,
each sheet being subscribed by myself;
and the three first sheets having four columns of names, the fourth only two;
till the next term: and if any processes are already made forth,
you are immediately to supersede the same: and for so doing this shall be your warrant.

Rochester.

Whitehall, Treasury chamber, March 4, 1685.

To my very loving friend, the clerk of the Pipe, or his deputy, etc.

I was very industriously concerned to obtain such a warrant
for a speedy stop to be put to the said processes,
which were then ready to be issued forth of the said Pipe office in Gray`'s inn:
I had something to do, first with the treasurer`'s deputy,
and clerks of the treasury chamber, about their high demands of fees,
which we could not answer; whereupon I made complaint to the Lord Treasurer himself;
and he was so kind, as to cause them considerably to abate their demands of fees,
and to accept of what we could give:
I remember our friend Samuel Waldenfield kept me company at that time one day.

So the warrant was delivered to me.

Rowland Vaughan went with me to the clerks of the Pipe, with our warrant to stay process,
who seeing such a long list of a great number of names annexed to the warrant,
demanded very high fees, amounting to many hundred pounds,
which we could in no ways come near: they were very huffing and high towards us,
though we civilly treated them, threatening if we did not pay them the fees demanded,
that the writs should be issued out to the sheriffs of the several counties,
to seize upon our friends`' estates; and to be sure it would be done to purpose,
for said they, This is like to be the last time, seeing process was to be stopped;
so that if the writs then went forth,
they concluded they would be the more severely executed
and fall heavier upon the convicted than ever.
Such like threats were to affright us into a compliance
with their unreasonable demands of fees;
which we neither would nor could do; whereupon we parted at that time.

Being much toiled, weakened, and impaired in my health,
by attending and labouring for our friends`' relief in that case,
I was taken suddenly ill, so that I was forced to keep house a few days:
yet still the burden of friends`' sufferings lay so heavy upon my spirit,
and care to have them relieved, by a stay to the said processes,
that they might not be further issued forth against them,
that I forthwith sent to divers friends to let them know how the case stood with me,
and how far I had procured and brought forward the case,
in order to their relief from the exchequer process;
particularly I sent for my companion, Gilbert Latey,
he being then in the country at Kingston, at his mother-in-law`'s, Ann Fielder,
who quickly came to London: and I acquainting him, and our loving friend William Mead,
how our case stood, as to the clerks of the Pipe, they refusing to stay the process,
unless they had the fees they demanded;
I desired Gilbert Latey and William Mead to go and treat with those clerks,
and see what they could bring them to:
at last they brought them so far to abate their demands,
as to come down to those friends`' terms, and accept of what they proffered, i. e.,
about sixty pounds instead of the many hundreds demanded,
though it was not without complaining that they were deprived
of what they esteemed their proper fees and dues.
However our friends did as well as they could with them,
to prevent their complaining to the king,
and getting leave thereupon to issue any further
process against our friends in the counties.

The stay of proceedings thus obtained,
prevented the ruin of some hundreds of our friends in their respective counties,
and saved many thousands of pounds in their estates;
and I had great peace and comfort in the Lord,
in that he made me any ways useful in helping towards our
friends`' relief from those heavy persecutions and oppressions.
Blessed be the Lord my God, who greatly helped me to serve him in helping his people.

Another case of hardship and suffering befell our friends at two of their meetings, viz:
the one at the Park in Southwark, and the other at the Savoy in the Strand, Westminster;
by having their meetinghouses taken from them,
and possessed by soldiers and their officers, and made guard houses of,
and our friends kept out, and forced to meet without doors.

The case more particularly is as follows, viz:

About the third month, 1685,
the soldiers came and made part of the said meetinghouse at the Park, a guard house,
and did great spoil and damage, about and in the same by pulling down pales,
digging and cutting down trees, carrying away and burning them;
and also the wainscotting and benches about the room,
and they carried away one of the out doors, and many of the casements:
and when the soldiers drew out to the camp, they left the house open.
Whereupon John Potter, the then owner, entered again,
and made up the outward door and some other necessary repairs,
and had a survey of the damages done, which amounted to about forty pounds.

The soldiers returning from the camp, again possessed themselves of the place,
and kept their guard therein for some time, in manner following, viz:
on the 22nd of October, 1686, a quarter-master belonging to Col.
Hayle`'s regiment, came to the chambers of the said John Potter`'s tenants,
and demanded entrance, which being denied, the quartermaster, with the help of soldiers,
broke in, handed away their goods, and turned out three aged women to another house.
When they had taken possession of our said meetinghouse and rooms below,
they pulled down the galleries, and made a brick wall cross the lower room,
with many other alterations,
as if they intended to have the sole and perpetual possession to themselves,
having made a sort of a place for prayers, or a mass house, in one end,
enclosed from the rest by the said partition wall; notwithstanding the said John Potter,
the owner,
showed his lease and title to the premises several times to the Colonel and his quarter-master;
by which they understanding his right and title, the Colonel asked him if he would sell,
and what he would have for it?
But that he could not yield to,
knowing what other use the lease was intended and used for;
the low room being our meeting place,
he could not in good conscience shut his friends out of the same.

But being by force kept out of our meetinghouse and property, as before related;
we had no other way to have the same restored, but by application to the king,
and also for our meeting place at the Savoy in the Strand.
Whereupon my friend Gilbert Latey and I were desired to attend the king;
to which we gave up, I being prepared to vindicate our property,
especially in our meetinghouse at Park aforesaid.
When we had sent notice to the king of our desire to attend him in this case,
and that he would please to appoint the time, he granted our request therein.

On the 1st of the tenth month, 1686, in the morning,
Gilbert Latey and myself went to Whitehall, and in a lower room of the closet-keeper`'s,
waited some time.
When we had sent up word to the king of our waiting for admittance, after some time,
he came down to us, and the said Col. Hayles only with him.

After I had opened our case to him,
how our said meetinghouse at Park was detained from us,
I found that he had been misinformed and prepossessed;
as if that meetinghouse and others were forfeited to him on the conventicle act.
I presently showed him the mistake, for by that act the owner`'s houses,
where meetings were held, were not forfeit, but they fineable; the penalty was fines,
not forfeiture of houses; and yet, as I told him,
I hoped he would not take advantage against us upon that act,
seeing he had intimated that his opinion was for liberty of conscience, from persecution.

He further alleged that John Potter had given his
consent to part with the said house for a compensation;
as also the Colonel affirmed,
having given the king the notes he had taken out of John`'s lease,
showing the conveyance of the title from one to another,
till it was settled on John Potter.
But the king told me, as the Colonel had informed him,
that since John had assented to part with the said meetinghouse for a compensation,
we had had a meeting about it, and that our friends had persuaded John not to sell it.

To all which I gave answer.
That John Potter never appeared of that mind to us, as to sell it,^
footnote:[John Potter fully cleared himself thereof to friends`' satisfaction.]
and that it is really a property, etc.
I further told him that divers of our meetinghouses in London were seized,
and the broad arrow set upon the doors, pretendedly for the king,
in the reign of king Charles the second,
and particularly our meetinghouse at Gracechurch street;
where the mayor encouraged a priest of the church of England to read their mass,
or liturgy, and to preach; which was such a wonder,
that a priest should come and read common prayer, and preach in a Quakers`' meeting,
that people did numerously gather and crowd into and about the meeting;
and afterward at another meeting,
the priest came to be so affrighted with their crowding and noise, that he got away,
and forbore coming again to read and preach in our meetinghouse.

The king smiled at my mentioning their mass,
because I presume he understood that the book of common
prayer was much of it taken out of his mass book.

Having taken notes out of our friends`' lease of the said meetinghouse at Park,
I demonstrated the title and pleaded the property against the said Col.
Hayles`' pretensions or claim to it.

After pretty much discourse upon this matter, the king several times gave this answer,
"`I am resolved to invade no man`'s property or conscience.`"
And he told us he would look further into the title and inform himself,
but that at present he could not Spare the place, because of his guards.

Our friend Gilbert Latey being with me, spake also to the king,
about the Savoy meetinghouse;
our friends being there kept out in a cold yard for many weeks, by the guards.
Whereupon Gilbert requested the king to grant our
friends their liberty to meet twice a week,
it being winter time, and hard for ancient people to stand abroad in the cold.
The king did not refuse his request, but was pleased to delay it for a time,
for further consideration.

However our endeavours in God`'s power and counsel, took such effect upon the king,
that in a few weeks after he caused both our meetinghouses, viz: at Park and Savoy,
to be restored to us.

Before we parted from the king that time,
I mentioned to him our friends`' great sufferings in Nottinghamshire and Leicestershire,
by Smith the informer, and two or three petty justices, that took his part;
and I entreated two or three lines from the Lord Sunderland, to the Duke of Newcastle,
to put a stop to the said informer`'s proceedings.
The king freely granted my request,
and two or three times promised to speak to the Lord Sunderland,
to write to the Duke of Newcastle for the same purpose.
After which, one of the lords of the council, at my desire,
undertook to procure a letter forthwith from the Earl of Sunderland,
pursuant to the king`'s promise before mentioned.
Our friends and John Edge also, were concerned to attend the result thereof;
so that through the power and help of the Lord our God, in our endeavours,
a general stop to those persecuting devourers, the informers, was obtained,
to the great comfort and relief of our suffering friends throughout the nation.
I was greatly comforted in serving them to the utmost of my ability, for their relief,
when the Lord opened a way for such endeavours, and I had great peace therein.
And though I was often much wearied, and some times weakened, as to the outward man,
yet the Lord revived my spirit and renewed my strength,
and gave me suitable arguments to plead in that service, to authority.
In all which, I humbly confess and praise his divine power and goodness;
glory to his name forever.

Being tenderly concerned to visit the king,
in order to encourage that good work he had begun and declared for,
in respect to liberty of conscience, in matters of religious worship,
and to intimate the good effects of his declaration for that intent towards dissenters;
as well as to acquaint him with some information I had from Leeds, in Yorkshire,
of sufferings remaining upon some of our friends there,
Gilbert Latey and I had admittance into the king`'s presence,
on the 14th of the tenth month, 1687, at Whitehall.
The king appeared glad to see us, and the substance of our discourse was as follows, viz:

George Whitehead: We are glad to see the king,
and heartily wish him health and happiness, and a happy and prosperous reign,
and that his government may be easy to him in all respects, that is,
to himself and the people.

King: I thank you; and for your parts, I believe well of you and your friends;
and that you do wish me well.

George Whitehead: I desired to attend the king some time since,
but a long journey this summer, into the north parts of England, and some sickness since,
prevented.
We have daily cause to bless God for the mercy we enjoy under the king,
as being made instrumental in the hand of God therein,
and daily to pray for the king`'s preservation.

In this late journey I have been as far as Cumberland,
and other parts of the north of England,
and find the good effects of the king`'s declaration for liberty of conscience,
and how well it is resented by all good people, by all who are sober,
moderate and rational.

King: It is well resented by all good Christians I am sure.

George Whitehead: I find that persons of understanding and quality,
do commend the king`'s prudence and conduct therein.
And many innocent families,
who have been sorely distressed by the persecutions
and hardships they have long been under,
have received such relief through the king`'s clemency and declaration,
that they find cause daily to pray for the king,
and to him may justly apply the words of that just man Job, in this case,
respecting the justness of his proceeding, "`Thou hast broken the jaws of the wicked,
and delivered the prey out of his teeth.`"
"`And the blessing of them that were ready to perish under their hardships,
came upon me.`"
And further, that by thy declaration for liberty of conscience,
thou hast yielded submission to the great God and given to him his due therein, namely,
that God may rule and bear sway in men`'s consciences,
whose sovereign right it is to rule therein; "`And when the Lord reigns,
let the earth rejoice;
and when the evil beasts of prey are made to cease out of the land,
the earth shall yield her increase; according as God`'s holy prophets have testified.`"

King: It is very true.

George Whitehead: Let liberty of conscience, as declared or promised,
be vindicated or maintained, and the good effects thereof will appear more and more.

King: I am resolved to maintain it as long as I live,
and make it as firm as a magna charta, and more firm if possible,
that it may remain for the benefit of future ages,
and that posterity may not have cause to alter it.

George Whitehead: Whensoever the king shall please to call a Parliament,
we do heartily wish it may be such as may concur with the king`'s clemency,
according to his declaration, for liberty of conscience, and confirm it by a law;^
footnote:[This was on occasion of something spoken by the king,
in a former discourse to the same purpose.]
and for our parts, I hope we shall contribute our endeavours,
so far as argument and reason will go, or may prevail, to persuade them to confirm it,
and give it the sanction of law, and repeal those penal, persecuting laws,
which are against that liberty.

+++[+++Those persecuting laws, as the conventicle acts and others,
being to force persons by penalties, contrary to their consciences,
belief and persuasions, even in point of worship,
consequently tend to make them hypocrites towards Almighty God,
which no sincere soul can yield to.]

King: You have a right to election of members of Parliament:
I would have your friends to have a care that they do not give
their voices for such that are against liberty of conscience.

George Whitehead: It concerns us all to have a care of that;
it is certain there can be no free Parliament upon a general and free election,
whilst the oaths of supremacy and allegiance, and tests requiring a conformity,
are made the qualifications of all members of Parliament;
for such qualifications admit none to be members of Parliament,
but such as are strict churchmen for conformity.
Whereas a mixed,
or more equally chosen Parliament is most likely to consider all interests,
and to establish liberty of conscience, which those penal, persecuting laws allow not.

King: Those laws and qualifications are against property, and destructive to it.
+++[+++With other words full and explanatory of his mind, to the same effect,
not so clearly remembered,
but generally importing those limitations to be also against
the king`'s interest and prerogative of the crown,
as well as against the people`'s property.]

George Whitehead: By a mixed Parliament,
I meant consisting of dissenters and of such churchmen as are against persecution,
as the grand jury at Hertford assizes,
who stopped all the presentments against dissenters for twenty pounds a month,
some time before the king`'s declaration for liberty of conscience came forth.
This mixed grand jury appeared a fit example, as I thought,
in this case relating to a free Parliament.

King: You know when I was Duke of York, how envious many were against me,
and how monstrously they pictured me in their pamphlets,
to render me odious to the nation, and what a dangerous successor I should be.
But in point of Christianity, I freely forgive them all.

George Whitehead: That is a great point of Christianity and charity indeed,
freely to forgive injuries, and is generous and noble;
and I am truly glad to hear so much from the king.
It is true, the Duke of York was such a formidable person in the thoughts of many,
that they greatly feared and were jealous of of his succeeding:
but now since come to the crown,
he has given such open demonstration of his clemency and good will to the people,
as has convinced many of their mistake therein,
and given them cause to lay aside their former fears and jealousies of that kind.

King: I was always of the same judgment for liberty of conscience,
that now I have declared publicly.
I remember about twenty years ago, or above, I was at Tunbridge,
though I never drank the waters; there was one Owen, John Owen, a dissenter,^
footnote:[Dr. Owen.]
who had a mind to speak with me, but was,
or seemed something bashful or fearful of coming to me,
until some acquainted me therewith;
and then I gave him liberty to come and speak with me, and told him my opinion,
that it was for liberty of conscience, as I have now declared.

George Whitehead: I heard as much a great while ago, from Edmund Waller, esq.,
who is lately dead; he signified to the same purpose,
concerning the Duke of York`'s being of that opinion for liberty of conscience,
long since.

Gilbert Latey: That which the king has signified secretly, he has now declared openly,
to the comforting the hearts of many thousands,
who truly bless God for the king`'s kindnesses,
and return hearty thanks to the king for the same;
and for all the kindnesses thou hast shown to us the Lord reward thee,
and return thee a thousand fold into thy own bosom.

King: I thank you heartily.

Gilbert Latey: We remember when we were at Windsor to attend the late king,
which was a time of great persecution,
when we were likely to be torn to pieces by our persecutors, how kind thou wast to us;
and we can truly say we were not easy in our minds till we had seen the king`'s face,
that we might acknowledge the kindnesses we have formerly received from him.
And further, I remember when we were last with the king,
as I am not willing to approach the king`'s presence often,
being afraid to appear too troublesome, I made it my request,
that our poor friends at Kingston might enjoy their meetinghouse again,
which they had been long kept out of, and were forced to stand in the street.
And likewise, that the king would suffer us again to meet in our meetinghouse at Savoy,
where I live.
Whereupon the king was pleased to promise us, that he would speak to sir Edward Evelin,
then mayor of Kingston, that our friends should have their meetinghouse again;
which accordingly was granted them.
And the king has also been lately pleased to give
us possession of our meetinghouse at Savoy:
I do therefore for myself, and in behalf of the rest of our friends at Westminster,
return the king our humble and hearty acknowledgment and thanks for the same.

George Whitehead: I have one particular case from Leeds in Yorkshire,
which our friends desired me to acquaint the king with; and that is,
the magistrates of Leeds, in the late persecutions,
have been more severe to our friends there, than in all the county of York besides.
At Leeds they have not only imprisoned them and endeavoured
to banish them out of the land,
having prosecuted them in order to banishment,
on the statute of the 13th and 14th of the late king,
which extends to imprisonment and transportation,
but also they have taken away their goods for their religious meetings,
and do still keep the goods of one person or more unsold,
and refuse to restore the goods to the respective owner or owners,
when desired by our friends concerned.
Wherefore we entreat the king to speak to the Lord President,
to write two or three lines to the mayor and aldermen of Leeds,
to cause them to restore the goods to the respective owners.
+++[+++And thereupon George Whitehead delivered the case in writing to the king.]

King: I will do it; I will speak to my Lord Sunderland to write as you desire.

+++[+++Which accordingly he did,
and an order was the next day taken out for restitution of the said goods.]

George Whitehead: We thankfully acknowledge the king`'s kindness in this case also.

Gilbert Latey: We pray God reward the king into his bosom,
for all his favours and kindnesses, and grant him, if it be His will,
long life and a happy reign here, and a crown of immortal glory hereafter.

George Whitehead: We sincerely desire it.

King: I thank you heartily.

A copy of the said order follows, viz:

Whitehall, December 14th, 1687.

Gentlemen,

The king being informed that some goods belonging
to John Wales and other Quakers of Leeds,
which were seized and taken from them, upon the account of their religious worship,
do remain unsold, in the hands of John Tood,
who was constable at the time of the seizure, or in the hands of some other persons;
and his majesty`'s intention being,
that all his subjects shall receive the full benefit
of his declaration for liberty of conscience,
his majesty commands me to signify his pleasure to you,
that you cause the goods belonging to the said John Wales,
and all other Quakers of Leeds,
which were heretofore seized upon the account of religious worship, and are unsold,
in whose hands soever they remain, to be forthwith restored to the respective owners,
without any charge.
I am, gentlemen, your affectionate friend and servant,

Sunderland, P.

Superscription,--For Mr. Mayor and the Aldermen of Leeds, in the county of York.

Finding it our Christian duty to be industrious in our solicitations
for our conscientious and religious liberty,
and for the ease and relief of our friends from their great hardships, under long,
severe persecutions for the same, when the Lord our God had made way for it,
and opened a door for access to the king and the government,
and inclined his and their hearts to hear and understand our grievances,
we were the more obliged to lay hold of God`'s providence therein,
and to make the best improvement thereof we could, with his assistance,
which he graciously and freely afforded us, who laboured in that service.

And as the king granted our friends relief and liberty from their cruel persecutions,
imprisonments, fines, forfeitures, seizures, and spoil, etc., we could do no less,
in point of civility and gratitude, than return him our own,
and our friends`' hearty thanks.
And also as Christians, pray for him and all in authority; for if as Christians,
we are required to love and pray for our enemies and persecutors,
much more are we obliged to do so for our friends,
and such who show kindness and compassion towards us,
when under persecutions and afflictions.

Some of the principal passages in king James`'s declaration
to all his loving subjects for liberty of conscience:
given at his court at Whitehall, the 4th day of April, 1687,
in the third year of his reign, viz:

"`It having pleased Almighty God,
not only to bring us to the imperial crown of these kingdoms,
through the greatest difficulties, but to preserve us by a more than ordinary providence,
upon the throne of our royal ancestors; there is nothing now that we so earnestly desire,
as to establish our government on such a foundation as may make our subjects happy,
and unite them to us, by inclination as well as duty;
which we think can be done by no means so effectually,
as by granting to them the free exercise of their religion for the time to come; and add,
that to the perfect enjoyment of their property,
which has never been in any case invaded by us, since our coming to the crown:
which being the two things men value most, shall ever be preserved in these kingdoms,
during our reign over them, as the truest methods of their peace and our glory.

"`We cannot but heartily wish, as it will easily be believed,
that all the people of our dominions were members of the Catholic church;
yet we humbly thank Almighty God it is, and hath of long time been,
our constant sense and opinion, which upon divers occasions we have declared,
that conscience ought not to be constrained,
nor people forced in matters of mere religion:
it has ever been directly contrary to our inclination;
as we think it is to the interest of government, which it destroys by spoiling trade,
depopulating countries, and discouraging strangers; and finally,
that it never obtained the end for which it was employed.

"`And in this we are the more confirmed,
by the reflections we have made upon the conduct of the four last reigns:
for after all the frequent and pressing endeavours that were used in each of them,
to reduce this kingdom to an exact conformity in religion,
it is visible the success has not answered the design,
and that the difficulty is invincible.
We therefore out of our princely care and affection unto all our loving subjects,
that they may live at ease and quiet, and for the increase of trade,
and encouragement of strangers, have thought fit, by virtue of our royal prerogative,
to issue forth this our declaration of indulgence,
making no doubt of the concurrence of our two houses of Parliament,
when we shall think it convenient for them to meet.

"`In the first place we do declare, that we will protect and maintain our archbishops,
bishops and clergy, and all other our subjects of the church of England,
in the free exercise of their religion, as by law established,
and in the quiet and full enjoyment of all their possessions,
without any molestation or disturbance whatsoever.
And that all, and all manner of penal laws, in matters ecclesiastical,
for not coming to church, or for any other non-conformity to the religion established,
be immediately suspended, etc.

"`And to the end that by the liberty hereby granted,
the peace and security of our government, in the practice thereof, may not be endangered,
we have thought fit, and do hereby straitly charge and command all our loving subjects,
that as we do freely give them leave to meet and serve God after their own way and manner,
be it in private houses, or places purposely hired or built for that use,
so that they take a special care that nothing be preached or taught amongst them that
may any ways tend to alienate the hearts of our people from us or our government:
and that their meetings and assemblies be peaceably, openly, and publicly held;
and all persons freely admitted to them.
And that they do signify and make known to some one
or more of the next justices of the peace,
what place or places they set apart for those uses.

"`And that all oar subjects may enjoy such their religious assemblies,
with greater assurance and protection, we have thought it requisite,
and do hereby command, that no disturbance of any kind, be made, or given unto them,
under pain of our displeasure, and to be proceeded against with the utmost severity,
etc.`"

With much more in the said declaration, respecting liberty of conscience,
from certain oaths, pains, penalties, forfeitures, and disabilities, etc.
In conclusion, the king thus declared, viz:

"`And although the freedom and assurance we have hereby given,
in relation to religion and property,
might be sufficient to remove from the minds of our loving subjects,
all fears and jealousies in relation to either,
yet we have thought fit further to declare,
that we will maintain them in all their properties and possessions,
as well of church and abbey lands,
as in any other their lands and properties whatsoever.`"

Considering the difficult circumstances the king was under,
being reputed of the Roman Catholic church, so called, or declared Papist,
his declaration for liberty of conscience,
so contrary to the religion and practice of that persecuting church,
was the more remarkable;
and it appeared that the Lord had opened his understanding therein,
above the priests and others of that religion and church,
whose principle and practice and chief support, are coercion, force and persecution,
about matters of religion and conscience;
contrary to the said declaration for liberty of conscience,
which in itself appears both rational, prudent and politic.

1+++.+++ Respecting those of his own communion for their liberty;
yet there appeared to be also a conscience on his part in the case;
especially seeing he so solemnly declared,
That for a long time it had been his sense and opinion,
that conscience ought not to be constrained,
nor people forced in matters of mere religion.

2+++.+++ Respecting his promise to the bishops and clergy of the church of England,
he seemed therein cautious and politic,
to quiet and put them out of their fears of losing their great revenues, tithes,
oblations and obventions, etc.
As also to quiet the great and rich men concerned in abbey lands, impropriate tithes,
and great revenues thereby, etc.

3+++.+++ As for us the people commonly called Quakers, and our ministers,
having no such revenues as tithes, hire, or wages for preaching, to lose,
our gospel being free, we were not so afraid of popery or a popish prince and clergy,
as those who enjoy those great revenues which the popish church and priesthood claim,
and would gladly come into and possess.

4+++.+++ The king having often seriously declared liberty of conscience,
as from force and persecution, to be his principle and persuasion,
and we who had long deeply suffered, partaking thereof,
especially in the latter part of his reign,
had great reason to be the more easy and thankful,
that we had some relief from those extreme persecutions
and hardships we had long suffered under.

6+++.+++ Howbeit,
the king`'s aforesaid declaration not having the sanction of an act of Parliament,
for the confirmation and continuance thereof,
we did not think our liberty secured to us thereby,
any more than it was under the reign of his brother, king Charles the second,
but uncertain and precarious, as it was before,
when we had only that king`'s specious promises and declarations,
which lasted but a little while, and were soon made void by the Parliament and himself,
and many persecutors let loose upon us again,
because the liberty granted was not passed into a law.

6+++.+++ Lastly; as to king James the second`'s abdication or removal from the throne,
upon the revolution, it is not my business or concern,
to treat of the particular causes or occasions thereof;
they are matters of state and government.

Although the liberty of conscience declared and allowed by him to us,
and other dissenters, whereby we all had relief, was envied by our persecutors, priests,
and others, yet that could not be the cause of his abdication,
so as to move divine providence thereto,
or cause his armies to be dispirited or discouraged from defending and supporting him;
for he thought himself safe both with dissenters, in allowing them their liberties,
and with the church of England,
by their professed doctrine of passive obedience and non-resistance;
and especially safe with the Quakers by their passiveness
and non-resistance under their manifold sufferings and persecutions;
and their being principled not to revenge, fight, kill, or destroy men`'s lives.

What then moved divine providence to give such an invisible stroke upon his army,
so as they could not stand to support him?
Not the lenity, indulgence, or kindness of the prince to his conscientious,
dissenting subjects, but some other cause, best known to the Divine Majesty,
the Searcher of hearts, by whom both the intentions and designs of men and princes,
as well as their actions, are foreseen and known;
who by His power and spirit can move upon the waters, even upon the spirits of men,
nations and kingdoms, to cause what overturnings and revolutions he pleases.
For it is certain, the Most High rules in and over the kingdoms of men,
and he giveth them to whomsoever, and for what causes he pleases; Dan. 4:17,25,32,35.

Glory to the Most High, the great Emperor over the world, who has hitherto helped us,
preserved his peculiar people, and defended them through many storms and tempests,
and divided the sea, the many waters and floods,
for his redeemed to pass through towards their everlasting
inheritance and rest in his kingdom of glory and triumph:
glory, glory forever.
